### ISSUE TITLE
please link to pkgsrc package

### ISSUE THREAD

**Issue by 0-wiz-0** [PyCQA/pylint#1000]
pkgsrc (coming from NetBSD, but portable to lots of platforms, see http://pkgsrc.org/) provides a pylint package since 2014 . I have just updated it to 1.6.1.
Please mention it on the homepage. 
Installation instructions:
``pkg_add py27-pylint``
Webpage link for the package:
http://pkgsrc.se/devel/py-pylint
Thanks.

**Comment by PCManticore** [comment]
If by the homepage, you are referring to http://pylint.org, then this issue has to be reported to https://bitbucket.org/logilab/pylint.org.

**Comment by PCManticore** [comment]
Otherwise, I am happy to accept pull requests that documents this installation in our current docs!

**Comment by 0-wiz-0** [comment]
You are right, I meant pylint.org.
I've opened a ticket there, thanks for the pointer!
https://bitbucket.org/logilab/pylint.org/issues/14/please-link-to-pkgsrc-package
