### ISSUE TITLE
Unable to mark same line with pylint special case and special case defined by other tool

### ISSUE THREAD

**Issue by samdmarshall** [PyCQA/pylint#1010]
I ran into this issue last night while trying to make parts of my code as ignored by my code coverage tool `coverage.py` as well as marking code to be ignored by `pylint`'s rules. `coverage.py` uses the expression `# pragma: no cover` on a line to mark that specific line or the block it contains as ignored by the code coverage report. In my case I have an object that must be subclassed and a couple of methods implemented by the new implementation or an exception will be raised because it isn't implemented correctly. Because these methods are never called directly there will be no code coverage for them. Since the implementations simply raise an exception, there is no self use so `pylint` asks me to refactor it into a function rather than a method, but the idea here is to guarantee a contract for the subclasser I cannot remove the methods.

### Steps to reproduce
```
class Foo(object):
    def __init__(self):
        self.bar = None
    def someAction(self): # pylint: disable=no-self-use # pragma: no cover
        raise Exception('Please subclass this class and implement this method')
```
Run `pylint` on the code snippet, I have to either mark it as ignored by `pylint` or mark it ignored by `coverage.py`. Either way i am going to get errors and misrepresentation of data about the code in question. 

### Current behavior
`pylint` doesn't support parsing the option if it is inline with any other comment.

### Workaround
The workaround I implemented was to place the `pylint` ignore rule like this:
```
class Foo(object):
    def __init__(self):
        self.bar = None
    # pylint: disable=no-self-use
    def someAction(self): # pragma: no cover
        raise Exception('Please subclass this class and implement this method')
```
But I am not 100% sure as to what this behavior will invoke. E.g.: will it silence the no-self-use for only that method or everything below that line in the scope of this class implementation? This turned out to be my only viable option to make them both co-exist and do what I intend for them to do.

### Expected behavior
I'm not 100% sure on this since Python doesn't have a multi-line comment or other means making these two behaviors co-exist without some fuzzy parsing of the comment strings.

### pylint --version output
pylint 1.6.1, 
astroid 1.4.7
Python 2.7.10 (default, Oct 23 2015, 19:19:21) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)]

**Comment by PCManticore** [comment]
Hi,

I think you can combine the fact that pylint's pragma controls are stopping after the first semi-colon. For instance, if you merge the two pragmas into ``# pylint: disable=no-self-use; #pragma: no cover``, both of the tools stop complaining. Here is my output for instance, without it and with it:

```
D:\Projects\repos\tests>py -3 -m coverage report
True
Name    Stmts   Miss  Cover
---------------------------
a.py        7      1    86%
b.py        7      0   100%
---------------------------
TOTAL      14      1    93%

D:\Projects\repos\tests>py -3 -m coverage report
True
Name    Stmts   Miss  Cover
---------------------------
a.py        5      0   100%
b.py        7      0   100%
---------------------------
TOTAL      12      0   100%
```

Also, using a pylint pragma over the method will apply to all the other remaining blocks from the scope, not just to that particular method. 
Just a quick question, in your example, wouldn't you benefit more by using abc.abstractmethod with ABCMeta as a metaclass, in order to ensure that you do not instantiate subclasses of this class without actually implementing all the methods ? (pylint can also prove this, if you are using abc.ABCMeta).

Let me know if this solution works for your use case.

**Comment by samdmarshall** [comment]
Yep! that does work for me. I wasn't aware of the meta-class approach you suggested, I will have to look into that pattern over what i have implemented so far. Thanks!
