### ISSUE TITLE
Switch to pytest

### ISSUE THREAD

**Issue by PCManticore** [PyCQA/pylint#1025]
pytest seems to be the better testing framework out there, receiving lots of love from contributors and whatnot. I am not necessarily a pytest user, but from what I saw, it might provide us some benefits over unittest, such as using simple asserts instead of the unittest boilerplate, better and nicer diffs, parametrized fixtures.

Here are the next steps we might do for switching to it:
- [ ] use pytest as our test runner
- [ ] use https://github.com/pytest-dev/unittest2pytest to rewrite the tests and fix any issues
- [ ] rewrite the functional tests to be parametrized instead of being dynamically built as they are now.

Once done, we should handle the same for astroid.

@The-Compiler @AWhetter let me know if something else is missing. Probably we'll need some help with the rough edges, if we will encounter those while switching.

**Comment by rogalski** [comment]
Started by @degustaf in #1199

**Comment by PCManticore** [comment]
pylint uses pytest now, thanks to @degustaf There will be still things to flesh out in the future, but I consider this issue done as is.
