### ISSUE TITLE
Add switch to change column offset from 0 to 1

### ISSUE THREAD

**Issue by pylint-bot** [PyCQA/pylint#104]
Originally reported by: **Anonymous**

----------------------------------------

Request to add a switch to change column index offset from 0 to 1.

Explanation
=========
pylint indexes the characters in a source code file starting with 0.

Thus, if an error is detected starting with the 5th character in a line, the column variable of the "--msg-template" format string is 4.

This is a problem when using an editor that starts its index of the characters on a line with 1, e.g. MSVS.

Using the following command line option
      --msg-template="{path}({line},{column}): [{msg_id}({symbol})] {msg}"
it is possible to use a double click on a pylint output line in the MSVS output window to jump straight to the relevant place in the source code file. - Only, the jump is always one character off. Continuing above example, MSVS jumps to the 4th instead of the 5th character in the relevant line.

Clearly this is a minor inconvenience but it would be nice to have an option to make it work perfectly.

----------------------------------------
- Bitbucket: https://bitbucket.org/logilab/pylint/issue/104

**Comment by PCManticore** [comment]
I'm not keen on adding another CLI flag for supporting something as this. Closing this for now.
