### ISSUE TITLE
too-many-function-args

### ISSUE THREAD

**Issue by The-Compiler** [PyCQA/pylint#1045]
Not sure if this is related to #1044, but with the current master and this code:

```python
import functools

@functools.lru_cache()
def foo():
    pass

foo.cache_clear()
```

I get:

```
E:  7, 0: Too many positional arguments for function call (too-many-function-args)
```

**Comment by PCManticore** [comment]
Probably related to https://github.com/PyCQA/astroid/commit/6fba2eca13450d4949bc2925b3a0f4aa3157d968
