### ISSUE TITLE
Disable Module Docstrings

### ISSUE THREAD

**Issue by sylvaiam** [PyCQA/pylint#1047]
On our team, we try to keep it to one class per file. This causes module-level docstrings to be identical copies of class-level docstrings. Is there a way to disable just module-level docstring errors, without disabling docstrings altogether?
Thanks for any help!

**Comment by PCManticore** [comment]
No, there is currently no straight way to do that.

But of course, you can do the following for instance:

```
# pylint: disable=missing-docstring
# pylint: enable=missing-docstring


class A: # will emit only for this.
   pass
```

**Comment by PCManticore** [comment]
Let's close this in favor of https://github.com/PyCQA/pylint/issues/1164, which explicitly suggests the idea of splitting the check into multiple messages that can be disabled, such as ``missing-module-docstring``.
