### ISSUE TITLE
[Feat Request] Support for metrics for "afferent coupling" (CA)

### ISSUE THREAD

**Issue by moylop260** [PyCQA/pylint#1048]
Now pylint supports cyclomatic complexity and I found a excellent article of other good metric called `afferent coupling (CA)` and generating a good combination we could got a excellent additional parameter for QA

More info in the following blog:
https://www.toptal.com/software/coupling-and-cyclomatic-complexity?utm_campaign=blog_post_coupling_and_cyclomatic_complexity&utm_medium=email&utm_source=blog_subscribers

Is a valid feature (extension or normal checker) for pylint?

**Comment by PCManticore** [comment]
I wouldn't include this in pylint, it's out of its scope. Maybe you can write an external plugin which can be installed on base by base case.
