### ISSUE TITLE
regression when using flymake

### ISSUE THREAD

**Issue by pylint-bot** [PyCQA/pylint#106]
Originally reported by: **Aurélien Campéas (BitBucket: [auc](http://bitbucket.org/auc), GitHub: @auc?)**

----------------------------------------

emacs + flymake-mode + pylint is a powerful combo

However recent pylint releases have broken some of the sweetness.

The epylint thing only works with this change::

```
#!python

@@ -76,7 +77,8 @@
 
     # Start pylint
     # Ensure we use the python and pylint associated with the running epylint
-    lintPath = os.path.join(os.path.dirname(__file__), 'lint.py')
+    from pylint import lint
+    lintPath = lint.__file__
     options = options or ['--disable=C,R,I']
     cmd = [sys.executable, lintPath] + options + ['--msg-template',
             '{path}:{line}: [{symbol}, {obj}] {msg}', '-r', 'n', childPath]


```
Then, within emacs, several issues:

* coloring is now wrong (everything looks like an error, e.g. in red)
* some errors are "No module named uicfg_flymake.py" ...
* the minibuffer/message content is weird-looking, e.g.

    pylint: [[1;31mundefined-variable[0m, ] [1;31mUndefined variable 'StringField'[0m [6 times]

----------------------------------------
- Bitbucket: https://bitbucket.org/logilab/pylint/issue/106

**Comment by PCManticore** [comment]
This was apparently fixed by f8fdbc3f. If there are still issues with flymake + epylint, please create a new issue per each existing problem.
