### ISSUE TITLE
Absolute imports from the __future__ cause import-self errors.

### ISSUE THREAD

**Issue by dmtucker** [PyCQA/pylint#1069]
### Steps to reproduce
1. Use `from __future__ import absolute_import` in `__init__.py` of a package (e.g. mypkg).
2. Use an absolute import (e.g. `from mypkg import mymod`) in the same `__init__.py`.
### Current behavior

```
[W0406(import-self), ] Module import itself
```
### Expected behavior

(no error)
### pylint --version output

```
pylint 1.6.4, 
astroid 1.4.8
Python 2.7.9 (default, Mar  1 2015, 12:57:24) 
[GCC 4.9.2]
```

**Comment by PCManticore** [comment]
I tried reproducing this with the latest version, but I can't. If you still experience this issue, please reopen it with a reproducing case. Thanks!

**Comment by dmtucker** [comment]
I cannot reproduce this anymore either. I tested with Pylint 1.7.2 on Python 3.6.1 and Python 2.7.13.
