### ISSUE TITLE
Support output to a file to support tox on CI servers

### ISSUE THREAD

**Issue by johnthagen** [PyCQA/pylint#1070]
Currently [`tox` cannot redirect commands to files](https://bitbucket.org/hpk42/tox/issues/73/pipe-output-of-command-into-file), which means when running Pylint from within `tox` there seems to be no way to output the results to a single (for example HTML) file that a CI server can store for display.

`--file-output=y` used to be close to what is needed, but it [was removed in 2.0](https://docs.pylint.org/en/latest/whatsnew/changelog.html#what-s-new-in-pylint-2-0), and also created a different file for each module which is difficult to navigate.

Here is the [StackOverflow question](https://stackoverflow.com/questions/10439481/save-pylint-message-to-a-file) that relates to this.

`flake8` added this feature for the same reason: https://gitlab.com/pycqa/flake8/issues/15

> ...however my main usage of flake8 is from within tox running under jenkins (using the violations plugin). Since tox doesn't support shell redirection...

**Comment by PCManticore** [comment]
Why not redirecting pylint command in your tox file into a file?

**Comment by johnthagen** [comment]
@PCManticore Because (and this was new to me as I hadn't tried before) [`tox` does not support file redirection](https://bitbucket.org/hpk42/tox/issues/73/pipe-output-of-command-into-file), so there is no way to do it that I am aware of.

**Comment by acerv** [comment]
Hello,

I've the same problem when running pylint inside tox. And also this is more complicated once you need to develop a multiplatform application.

The only way to save the pylint stdout inside a file, is to tell tox to use bash or cmd, according with the platform, with '>' operator. Unfortunately, there's not a way to do so but creating multiple tox environments once for each platform, that is (of course) a huge waste of space and time.

Perhaps makes the automation system really complicated and difficult to handle.

**Comment by PCManticore** [comment]
Thanks for the input @acerv It seems this will be definitely useful, so I'd be happy to reintegrate a `--file-output` functionality for the entire output.
