### ISSUE TITLE
pylint doesn't work with python3.4.3

### ISSUE THREAD

**Issue by WielkiZielonyMelon** [PyCQA/pylint#1076]
### Steps to reproduce
git clone https://github.com/pycqa/pylint
cd pylint
sudo **python3** setup.py install

pylint --version
`No config file found, using default configuration`
`pylint 2.0.0,`
`astroid 1.4.8`
`Python 3.4.3 (default, Oct 14 2015, 20:28:29)`
`[GCC 4.8.4]`

### Current behavior
pylint dummy
`No config file found, using default configuration`
`Traceback (most recent call last):`
`  File "/usr/local/bin/pylint", line 9, in <module>`
`    load_entry_point('pylint==2.0.0', 'console_scripts', 'pylint')()`
`  File "/usr/local/lib/python3.4/dist-packages/pylint-2.0.0-py3.4.egg/pylint/__init__.py", line 13, in run_pylint`
`    Run(sys.argv[1:])`
`  File "/usr/local/lib/python3.4/dist-packages/pylint-2.0.0-py3.4.egg/pylint/lint.py", line 1292, in __init__
    linter.check(args)`
`  File "/usr/local/lib/python3.4/dist-packages/pylint-2.0.0-py3.4.egg/pylint/lint.py", line 718, in check
    self._do_check(files_or_modules)`
`  File "/usr/local/lib/python3.4/dist-packages/pylint-2.0.0-py3.4.egg/pylint/lint.py", line 829, in _do_check`
`    for descr in self.expand_files(files_or_modules):`
`  File "/usr/local/lib/python3.4/dist-packages/pylint-2.0.0-py3.4.egg/pylint/lint.py", line 861, in expand_files`
`    self.config.black_list_re)`
`  File "/usr/local/lib/python3.4/dist-packages/pylint-2.0.0-py3.4.egg/pylint/utils.py", line 900, in expand_modules`
`    is_namespace = spec.type == modutils.ModuleType.PY_NAMESPACE`
`AttributeError: 'tuple' object has no attribute 'type'`

### Expected behavior
Start working [;

### pylint --version output
No config file found, using default configuration
pylint 2.0.0,
astroid 1.4.8
Python 3.4.3 (default, Oct 14 2015, 20:28:29)
[GCC 4.8.4]

**Comment by PCManticore** [comment]
Install astroid from https://github.com/PyCQA/astroid.

**Comment by WielkiZielonyMelon** [comment]
Updated to astroid 1.5.0 and pylint started working. Thanks!
