### ISSUE TITLE
Remove virus link in documentation

### ISSUE THREAD

**Issue by mackeyja92** [PyCQA/pylint#1089]
The link to the PyCharm integration in the readthedocs for pylint is pretty much a virus hole. Please remove it immediately. 

![screen shot 2016-08-26 at 2 12 37 pm](https://cloud.githubusercontent.com/assets/10620022/18018994/3112cae8-6b97-11e6-8e2e-eb8892c82f73.png)

Direct link to the docs that contain the link [here](https://docs.pylint.org/en/1.6.0/ide-integration.html).

**Comment by PCManticore** [comment]
I don't get, what link?

**Comment by mackeyja92** [comment]
The one highlighted in the image above.

**Comment by PCManticore** [comment]
Thanks, should be done.

**Comment by mackeyja92** [comment]
That was quick, thanks.
