### ISSUE TITLE
The check_message decorator

### ISSUE THREAD

**Issue by iselind** [PyCQA/pylint#1091]
I've been trying to figure out what's the purpose and point of the check_messages decorator. For example:

@utils.check_messages('redefined-argument-from-local')
def visit_excepthandler(self, node):

I cannot really see why it's being used, sure you assign 'redefined-argument-from-local' to visit_excepthandler's checks_msgs but then what?

checks_msgs seems to be used in the auto registration of checkers. Looks like a convoluted way of accomplishing this, at least to me. Then again i have neither the history nor the original intention. Are there more to this than what i've found so far?

**Comment by PCManticore** [comment]
The decorator is used for keeping track of what messages a visit method is going to emit. Knowing this, pylint will not call those particular visit methods in the case when the emitted messages are disabled by the user.
