### ISSUE TITLE
strings and bytes objects for Python 3.5

### ISSUE THREAD

**Issue by iselind** [PyCQA/pylint#1092]
Can pylint help in keeping track of strings and bytes objects and especially when they get mixed? If so, how?

In my Application i can explicitly say that for all my strings there shouldn't be any binary data, only strings. Can i tell pylint that i would like any usage of bytes objects to be forbidden?

**Comment by PCManticore** [comment]
No, we do not currently support this. Probably something similar will land when we will have PEP 484 support, but it will probably depend on the annotations you give to the functions / objects rather than prohibiting across the board the usage of bytes or other objects.

**Comment by The-Compiler** [comment]
FWIW you can start Python 3.5 with `-bb` to make it throw an exception (or `-b` for a warning) whenever bytes and strings are compared (or otherwise mixed).

**Comment by iselind** [comment]
Awesome tip, much appreciated!
