### ISSUE TITLE
TypeError: print_full_documentation() takes exactly 1 argument (2 given)

### ISSUE THREAD

**Issue by iselind** [PyCQA/pylint#1093]
### Steps to reproduce
1. Clone pylint
2. Execute "cd doc"
3. Execute "make text"

### Current behavior
pylint % cd doc 
doc % make text
sphinx-build -b text -d _build/doctrees   . _build/text
Running Sphinx v1.4.6
making output directory...
loading pickled environment... not yet created

Exception occurred:
  File "/home/patriki/storage/pylint/doc/exts/pylint_features.py", line 26, in builder_inited
    linter.print_full_documentation(stream)
TypeError: print_full_documentation() takes exactly 1 argument (2 given)
The full traceback has been saved in /tmp/sphinx-err-b4dROC.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [text] Error 1
[FAIL] doc % cat /tmp/sphinx-err-b4dROC.log
# Sphinx version: 1.4.6
# Python version: 2.7.3 (CPython)
# Docutils version: 0.12 release
# Jinja2 version: 2.8
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sphinx/cmdline.py", line 243, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/application.py", line 204, in __init__
    self._init_builder(self.buildername)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/application.py", line 279, in _init_builder
    self.emit('builder-inited')
  File "/usr/local/lib/python2.7/dist-packages/sphinx/application.py", line 551, in emit
    results.append(callback(self, *args))
  File "/home/patriki/storage/pylint/doc/exts/pylint_features.py", line 26, in builder_inited
    linter.print_full_documentation(stream)
TypeError: print_full_documentation() takes exactly 1 argument (2 given)

### Expected behavior
The expected number of arguments should be provided.

### pylint --version output
% pylint --version
No config file found, using default configuration
pylint 1.5.6, 
astroid 1.4.5
Python 2.7.3 (default, Jun 21 2016, 18:38:19) 
[GCC 4.7.2]

**Comment by iselind** [comment]
Oops, some unintentional formatting in there, hope you don't mind...

**Comment by iselind** [comment]
The bug report above is based on Debian Wheezy...

I get a similar issue in my Debian Jessie docker image:
sphinx-build -b text -d _build/doctrees   . _build/text
Running Sphinx v1.4.6
making output directory...
loading pickled environment... not yet created

Exception occurred:
  File "/home/patriki/storage/pylint/doc/exts/pylint_features.py", line 26, in builder_inited
    linter.print_full_documentation(stream)
TypeError: print_full_documentation() takes 1 positional argument but 2 were given
The full traceback has been saved in /tmp/sphinx-err-zdbh7o0d.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Makefile:110: recipe for target 'text' failed
make: *** [text] Error 1

**Comment by PCManticore** [comment]
The problem is that you are using pylint 1.5.6 for some reason? print_full_documentation accepts an extra argument only in the code from the master branch and in fact, pylint_features.py does not even exist in other releases.

**Comment by iselind** [comment]
The output from pylint --version is indeed showing which Pylint i have installed on my Debian Wheezy machine. If i do the same for my Debian Jessie docker image i get
% pylint --version
No config file found, using default configuration
pylint 1.6.4, 
astroid 1.4.8
Python 3.4.2 (default, Oct  8 2014, 10:45:20) 
[GCC 4.9.1]

As i said, i get the same issue in my Debian Jessie docker image. The make text command is performed on master though.

**Comment by PCManticore** [comment]
The command might be called on the master branch, but you have another pylint installed in your PATH.

This is how the print_full_documentation call looks on master: https://github.com/PyCQA/pylint/blob/master/doc/exts/pylint_features.py#L26
This is how it looks on the released version: https://github.com/PyCQA/pylint/blob/1.6.0/doc/exts/pylint_features.py#L13

The former is probably importing the locally installed pylint from your environment, rather than the one installed from master. You should separate them by running the latter in a virtualenv or just don't have installed the former in the first place.

**Comment by iselind** [comment]
So, just to clarify then. I should be able to perform a `make text` on master if there is no pylint installed on the machine. Did i get that right?
Or should i be doing that on the released version branch?

Eventually when i sort things out and decide that i would like to contribute something. Do i make that contribution based on the master branch then or the released version branch? Which way is the "preferred way"?

**Comment by PCManticore** [comment]
``make text`` can work even if you have multiple pylint installations, as long as it runs in a virtualenv, in order to not use a different pylint installation.

So this should be all you need (not tested). Let me know if the following works for you:

```
$ python -m virtualenv venv
$ . venv/bin/activate
$ git clone https://github.com/PyCQA/pylint
$ cd pylint/doc
$ make html # should use the pylint installation from virtualenv in order to work
````

Regarding the contribution, all the time it should be to the master branch. If it is a fix that needs backporting into an already released version, I can do it when the feature / fix gets merged.

**Comment by iselind** [comment]
Inside `venv` i have to do `pip3 install Sphinx` just to get started but then it seems i still have to install pylint from what i cloned to be able to build the documentation. I get `ImportError: No module named 'pylint'`. So to sum it up, the provided instructions are not enough to build the docs.

I used python3 instead of python on that first command.

**Comment by iselind** [comment]
I'll play around a bit more with it tomorrow

**Comment by iselind** [comment]
To generate the documentation i had to do the following command sequence:
```bash
$ python3 -m virtualenv venv
$ . venv/bin/activate
$ pip install Sphinx
$ git clone https://github.com/PyCQA/pylint
$ cd pylint
$ python3 setup.py install
$ cd doc
$ make html
```
This might be good to keep in the documentation somewhere. Where would it fit the best?
