### ISSUE TITLE
Main description on pypi still has link to bitbucket

### ISSUE THREAD

**Issue by KennethNielsen** [PyCQA/pylint#1100]
### Steps to reproduce
1. Got to e.g: https://pypi.python.org/pypi/pylint/1.6.4
2. The top description says development is hosted on bitbucket, but when following the link to bitbucket the page says pylint was moved to github

### Current behavior

Gets wrong link

### Expected behavior

Get the correct one ;)

### pylint --version output

N/A

**Comment by The-Compiler** [comment]
I think #1102 will fix this for the next release.

**Comment by KennethNielsen** [comment]
@The-Compiler thanks

**Comment by PCManticore** [comment]
Closing, going to be fixed by #1102.
