### ISSUE TITLE
epylint and pylint are inconsistent by default for things like trailing whitespace errors

### ISSUE THREAD

**Issue by stanleybak** [PyCQA/pylint#1105]
### Steps to reproduce
1. create python file with trailing whitespace
2. run pylint on it
3. run epylint on it

### Current behavior
pylint reports trailing whitespace (and missing docstring erorrs), epylint doesn't report any errors

### Expected behavior
both should report the errors. If I want to ignore trailing whitespace or missing docstrings, I should edit my `.pylintrc` file.

### pylint --version output
pylint 2.0.0, 
astroid 1.5.0
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2]

### Problem source
In `epylint.py`, on line 89 it sets the default options if none are provided to epylint: `options = options or ['--disable=C,R,I']`. I believe this is what disables the errors by default when running epylint.

**Comment by PCManticore** [comment]
Yes, this is the cause of the issue. You can override the options passed to epylint, so that you can have error parity for both tools.

**Comment by stanleybak** [comment]
Shouldn't error parity be the default option?
