### ISSUE TITLE
Rendering variables to use on locals with render_to_response (Django)

### ISSUE THREAD

**Issue by Diegow3b** [PyCQA/pylint#1106]
### Steps to reproduce
1. Set up variables on views.py

### Current behavior

I set up my variables with the data i need on my templates but the pylint says i dont use the variable on my view context

### Expected behavior
Do not show erros because i use this variables  in template

### pylint --version output 
pylint 1.1.0, 
python 2.7
Django 1.8

**Comment by PCManticore** [comment]
I don't really understand this issue? Can you provide an example with a small reproducing piece of code? Also, pylint 1.1.0 is *extremely* old when it comes to pylint.
