### ISSUE TITLE
rcfile generation is not deterministic

### ISSUE THREAD

**Issue by BAG-CK** [PyCQA/pylint#1108]
### Steps to reproduce
1. call: pylint --generate-rcfile > .pylintrc1
2. call: pylint --generate-rcfile > .pylintrc2
3. Compare content of .pylintrc1 and .pylintrc1

### Current behavior
disable tag in [MESSAGE CONTROL] chapter has a different order of list members every time you generate a new rcfile.
Regular expressions in chapter [BASIC] allways have different order inside the file every time you generate a new rcfile.

### Expected behavior
--generate-rcfile should generate the rcfile deterministicly.
The order of configurations should not majorly change with new versions of pylint to make it more comfortable to check new default configs against your own custom config using a simple diff.

### pylint --version output
pylint 1.6.4, 
astroid 1.4.8
Python 3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:44:40) [MSC v.1600 64 bit (AMD64)]

**Comment by moylop260** [comment]
Duplicated https://github.com/PyCQA/pylint/issues/1087
Please check the following fix https://github.com/PyCQA/pylint/pull/1090
Or install the master version to validate it

**Comment by PCManticore** [comment]
Seems to be fixed by master.
