### ISSUE TITLE
Pylint allows commented function parameters

### ISSUE THREAD

**Issue by RoyIacob** [PyCQA/pylint#1152]
### Steps to reproduce
1.  create function with commented parameter:

def foo(
  \# some comment
  variable):
  return True

2.  Run pylint on this code.

### Current behavior

This doesn't emit any errors.

### Expected behavior

I can't find any guidelines on this but I'd figure it's non standard and should be disallowed. Doc strings should always be encouraged due to use of foo.__doc__ or help(foo).

### pylint --version output

pylint 1.1.0, 
astroid 1.0.1, common 0.60.1
Python 2.7.12 (default, Oct 19 2016, 16:32:37) [C]

**Comment by PCManticore** [comment]
I see no reason to emit an error for this, especially since comments for parameters might have their purpose, such as documenting the type of a parameter for the mypy tool.
