### ISSUE TITLE
Enhancement: New Checks: Missing shebang & Missing/Bad Encoding

### ISSUE THREAD

**Issue by GadgetSteve** [PyCQA/pylint#1156]
### Steps to reproduce
1. Create a python file, module, etc. that starts with the docstring from the first line
2. Run pylint on that module

### Current behavior
Currently if all other coding is good no errors, warnings or infos are issued

### Expected behavior
For maximum portability and consistency of behaviour all python files should have as the first line:

`#!/usr/bin/env python`
or
`#!/usr/bin/env python3`

Likewise the second line, _or the first if the shebang is missing_ should be on of:
`#coding=`_encoding name_
or 
`# -*- coding:` _encoding name_ `-*-`
or basically anything that gives a match for `coding[=:]\s*([-\w.]+)` anywhere on the line.

See PEP-263, 394 & 397 amongst others.

If the **first** line of each file is not a valid shebang line I would like to see at least a Warning of "_File missing shebang line - may not execute correctly on some platforms_" 

If the second line is not `#encoding` _something_ then I would like to see a Warning or at least an Info of "_Missing encoding default encoding will be assumed and some editors may not work_" however if the second line is an encoding **but** not a valid encoding then an Error "Invalid or Potentially Incompatible Encoding" should be raised. Valid encodings for this purpose are limited to ASCII, LATIN-1 and UTF-8 _case independent._

### pylint --version output
No config file found, using default configuration
pylint 1.6.4,
astroid 1.4.8
Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)]

No config file found, using default configuration
pylint 1.6.4,
astroid 1.4.8
Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)]

**Comment by PCManticore** [comment]
This does not make sense for a general static analysis tool which can receive packages and modules as an input, input which is not necessarily intended to be executed as a script.
