### ISSUE TITLE
Reconsider warnings enabled by default

### ISSUE THREAD

**Issue by rowillia** [PyCQA/pylint#1178]
Wanted to start a thread about reconsidering which linters are enabled by default in PyLint.  Most new users likely interact with pylint by installing it and running `pylint <my project>`.  Currently, this is likely to produce hundreds if not thousands of errors in a mature code base.  https://medium.com/@acboulder/type-hints-are-scary-f52d07a36a31#.amip5xlb4 (we should fix some of the other issues raised here like ordering errors)  is a great write up about this experience.  2 of the questions in @PCManticore's talk https://www.youtube.com/watch?v=0jKbNpEjkhI were also around this.

In particular, I'm not a fan of the `too-many-*` rules being on by default.  Not that they aren't good checks!  I think it's valuable to note which methods are targets for refactoring, but I don't think that should cause a linter to fail.  In practice, I've seen linters like this wind up with a slow bleed until some poor developer pushes things over the limit and now it falls on him to refactor everything so he can make the change he needs.  I should be able to ask pylint for refactoring targets, but ideally that wouldn't be my first experience with PyLint (Unless I opt in 😄 )

PyLint itself disables a number of these - https://github.com/PyCQA/pylint/blob/master/pylintrc#L55-L64 .  The upcoming 2.0 release is a nice break with which we can re-evaluate some of these defaults.

I would suggest the default be something similar to what was suggested in the above medium post as well as the ones filtered out in PyLint's `pylintrc` file.

What's people's thoughts on this?  I think it's worth revisiting before 2.0 releases.

**Comment by The-Compiler** [comment]
This seems like an exact duplicate of #746 :wink:

**Comment by rowillia** [comment]
@The-Compiler Ah yes...thanks!  I missed that one 😄
