### ISSUE TITLE
Feature request: linting from stdin

### ISSUE THREAD

**Issue by cpitclaudel** [PyCQA/pylint#1187]
Hi there,

pylint is one of the few checkers supported by [Flycheck](https://github.com/flycheck/flycheck/) that doesn't support checking input passed on stdin. Could this feature be added?

Concretely, the proposal is that one would be able to call pylint this way:

   cat /home/clement/test.py | pylint --stdin-file-name /home/clement/test.py - 

instead of 

    pylint /home/clement/test.py

At first, it may not be clear what advantages this may have.  Here's a short explanation.

* Flycheck checks files (buffer contents): it doesn't need the file to be saved.  Since pylint requires the file to be checked to exist on disk, however, Flycheck must save the buffer.

* When this happens with other linters, we usually just write the temporary file to `/tmp`; with pylint, however, we can't do that: saving to /tmp breaks relative imports.

* Instead, we're forced to save a temporary copy of the file *in the same folder* as the original file.  So we save our temporary as `/home/clement/flycheck_test.py` in the example above.

* Unfortunately, this approach is invasive: if the user calls e.g. `grep` while a check is in progress, grep will find matches in the temporary file.  If the code is on a backed-up folder (dropbox, owncloud, …), the back-up application might pop up a window saying "uploading new file flycheck_test.py`. etc.  A concrete example of this problem is at https://github.com/flycheck/flycheck/issues/1173

Moving to stdin solves this problem neatly: we can pass pylint the contents of the unsaved buffer without saving first, while tipping it about the file name.  This has worked nicely with many other checkers (jshint and luacheck have `--filename`, rubocop has `--stdin`, scss has `--stdin-file-path`, jshint has `--stdin-filename`, flake8 has `--stdin-display-name`, etc.)

How hard would it be to implement such a feature?  Someone over at http://stackoverflow.com/questions/27862659/pylint-read-from-stdin asked for the same thing, and apparently on GNU/Linux passing /dev/stdin to pylint seems to work OK (except of course for imports), so hopefully the required amount of work should be relatively low?

Thanks!

**Comment by PCManticore** [comment]
Given these arguments, it would make sense for pylint to gain this ability. Unfortunately, the required amount of work does not look relatively low, since it assumes almost all the time that its inputs are files or modules. With some refactoring around the linter module, this might be accomplished. One thing to note, though, is that it needs the whole content read in one pass, it can't do analysis on a line by line basis.

**Comment by cpitclaudel** [comment]
Thanks for the encouraging comment! I'll open a PR to make it easier to discuss concrete code :)

**Comment by eflanigan00** [comment]
Has this been solved?

**Comment by cpitclaudel** [comment]
Nope
