### ISSUE TITLE
Feature request: Ignore unused imports when they are imported `as _`

### ISSUE THREAD

**Issue by Strilanc** [PyCQA/pylint#1190]
Unused warnings should treat `import x as _` like they treat  `_ =  x()`: the underscore name means that the lack of usage is somehow intentional and not worth warning about.

An example where this would be useful is testing if a library is present:

    def is_twisted_present():
        try:
            import twisted as _
            return True
        catch ImportError:
            return False

### Steps to reproduce
1. Create an `test.py` file containing just the line `import math as _`
2. Run `pylint test.py --reports=no`

### Current behavior

A warning is printed: `W:  1, 0: Unused math imported as _ (unused-import)`

### Desired behavior

No warnings.

**Comment by PCManticore** [comment]
Sounds like a reasonable request.
