### ISSUE TITLE
Warn on uses of subprocess.POpen preexec_fn= argument

### ISSUE THREAD

**Issue by gpshead** [PyCQA/pylint#1195]
The `subprocess.POpen` `preexec_fn=` argument is unsafe to use as it can lead to deadlocks. pylint should warn users about this.

For details why see the warning in https://docs.python.org/3/library/subprocess.html.

**Comment by PCManticore** [comment]
Sounds reasonable.

**Comment by befreeman** [comment]
I'm taking a look at this for PyCon 2018 sprints!
