### ISSUE TITLE
Detect legacy ternary conditional hacks

### ISSUE THREAD

**Issue by rogalski** [PyCQA/pylint#1204]
Still some of these old constructs may be found, [even in Pylint code](https://github.com/PyCQA/pylint/blob/master/pylint/checkers/variables.py#L1182).

Correct:

    true_value if boolean else false_value

Should yield error:

    (false_value, true_value)[boolean]
    boolean and true_value or false_value

**Comment by PCManticore** [comment]
I agree, this would be useful. In the case of pylint, given its age, finding these kind of constructs it's not a surprise.
