### ISSUE TITLE
FR: Lint for unittest.TestCase descendants not calling super(…).setUp()

### ISSUE THREAD

**Issue by Capstan** [PyCQA/pylint#1206]
I recently introduced a bug where by creating a child test case with a `setUp()` method without an initial call to `super(MyTest, self).setUp()`, some necessary calls were omitted. It seems like the following calls in descendants of `unittest.TestCase` not calling their parents' versions would be worthy of a lint error:

* https://docs.python.org/2/library/unittest.html#unittest.TestCase.setUp
* https://docs.python.org/2/library/unittest.html#unittest.TestCase.tearDown
* https://docs.python.org/2/library/unittest.html#unittest.TestCase.setUpClass
* https://docs.python.org/2/library/unittest.html#unittest.TestCase.tearDownClass

**Comment by Capstan** [comment]
My follow-up question is, how might one check that these calls exist, and maybe even are the first call (modulo decorator wrappers)?

**Comment by rogalski** [comment]
@Capstan if you ware willing to implement it, there is a [`super-init-not-called` check](https://github.com/PyCQA/pylint/blob/4ba16605d52a331bcc466f7f5d101dae7244a303/pylint/checkers/classes.py#L1105), which may be modified for checking for setUp and tearDown inheritance on unittest.TestCase instance.

**Comment by PCManticore** [comment]
I think this is a bit too specific and I would see it more as an extension, rather than a default check.
