### ISSUE TITLE
"trailing-whitespace" can be triggered erroneously 

### ISSUE THREAD

**Issue by vinnyrose** [PyCQA/pylint#1219]
### Steps to reproduce
1. Place a formfeed (insert a page break) character in a python module.
2. Run pylint on module.

### Current behavior
"trailing-whitespace" is raised

### Expected behavior
"trailing-whitespace" should not be raised

#### Details
A formfeed (`\f` or `\x0c`) is considered a valid whitespace character in python. It's easy to understand why normal whitespace (spaces and tabs) would raise a 'training-whitespace' detection, as normal whitespace has the side-effect of taking up space and is considered by the lexical analysis as "leading whitespace" for the indentation calculations. A formfeed, however,  has a different side-effect in that it creates a page break and is not considered as "leading whitespace".
Therefore I purpose that the following be the correct check: (from here: https://github.com/PyCQA/pylint/blob/pylint-1.6.4/pylint/checkers/format.py#L950)

                    stripped_line = line.rstrip('\s\t')

Reference:
https://docs.python.org/3/reference/lexical_analysis.html

### pylint --version output
pylint 1.6.4, 
astroid 1.4.8
Python 2.7.11 (default, May  3 2016, 09:23:25) 
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.29)]

**Comment by PCManticore** [comment]
Sounds reasonable. Want to send a pull request?

**Comment by vinnyrose** [comment]
Working on it.

**Comment by PCManticore** [comment]
@vinnyrose any news here? No rush, just want to see if this could be fixed.

**Comment by vinnyrose** [comment]
@PCManticore All set here.

**Comment by PCManticore** [comment]
Thanks, will do a review shortly!
