### ISSUE TITLE
incorrect 'no-member'

### ISSUE THREAD

**Issue by vitaly-zdanevich** [PyCQA/pylint#1230]
try this code:
```
def calc():
    selected_records = [{'1': 11}]
    if len(selected_records) == 1:
        return selected_records[0] if selected_records else {}
    return selected_records

print(calc().get('1'))
```
pylint return incorrect
`E:  7, 6: Instance of 'list' has no 'get' member (no-member)`

### pylint --version
```No config file found, using default configuration
pylint 1.6.4,
astroid 1.4.8
Python 3.5.2 (default, Oct 11 2016, 04:59:56)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)]```

**Comment by petrpulc** [comment]
Well, but pylint does not know that line 5 is really unreachable... Therefore it rightfully thinks you might return a list...

**Comment by rogalski** [comment]
pylint currently does not understand control flow. Also, returning different types from single function will always give trouble for static analysis.

**Comment by vitaly-zdanevich** [comment]
ok, but what about interpreting pydoc? for example if function have this line:
`:rtype: list or dict`
today PyCharm use this for analys

**Comment by PCManticore** [comment]
We don't take in consideration documentation hints, we're not PyCharm. Probably in the future we will have type hints support as described by PEP 484.

**Comment by PCManticore** [comment]
I'm closing this, since there are a bunch of issues in need for control flow as well. We'll get to have this supported some day.
