### ISSUE TITLE
incorrect analysing of etree

### ISSUE THREAD

**Issue by vitaly-zdanevich** [PyCQA/pylint#1234]
```
from lxml import etree

print(etree.tostring)
```
pylint says that
`Module 'lxml.etree' has no 'tostring' member (no-member)`

but this is wrong.

### pylint --version output
```
No config file found, using default configuration
pylint 1.6.4,
astroid 1.4.8
Python 3.5.2 (default, Oct 11 2016, 04:59:56)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)]
```

**Comment by PCManticore** [comment]
Try with ``pylint --extension-pkg-whitelist=lxml``. This library is a C library, pylint can't know out of the box what members does it have.
