### ISSUE TITLE
except MyException as e: Invalid variable name "e" - why?

### ISSUE THREAD

**Issue by vitaly-zdanevich** [PyCQA/pylint#1236]
### Steps to reproduce
pylint against code with such line:
`except subprocess.CalledProcessError as e:`

### Current behavior
`Invalid variable name "e" (invalid-name)`

### Expected behavior
no warning - because this is a popular approach for the naming of a variable in such place - and I do not think that this is bad - even [official documentation](https://docs.python.org/3.5/library/csv.html#examples) use this 'naming convention'

### pylint --version output
```
pylint 1.6.4,
astroid 1.4.8
Python 3.5.2 (default, Oct 11 2016, 04:59:56)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)]
```

**Comment by PCManticore** [comment]
Please check the documentation. We emit this message for variables with short names, which can be more explicit with regard to their purpose if they are longer. Check the docs to see how to change the regular expreasion that does this or how to whitelist this particular letter.

**Comment by vitaly-zdanevich** [comment]
But maybe will be better to exclude such case (name of the exception 'e') from error out of the box?

**Comment by zurcher** [comment]
You can add 'e' to the good-names list here:
https://github.com/PyCQA/pylint/blob/master/pylint/checkers/base.py#L1164

**Comment by amitauddy** [comment]
except HTTPError as _: and pylint accepted this.

**Comment by florisla** [comment]
To clarify, in `.pylintrc` you can simply add

    [BASIC]
    good-names=
        i,
        e,
        logger,
