### ISSUE TITLE
Add an option for validating alphabetical order of imports?

### ISSUE THREAD

**Issue by butla** [PyCQA/pylint#1240]
If I don't have some specific subgroups  (within the [PEP8](https://www.python.org/dev/peps/pep-0008/#imports) groups) of imports I like to keep them in alphabetical order.

Right now there's an option to validate import grouping according to PEP8: wrong-import-order (C0411).
I would like an additional option to check for alphabetical order within those PEP8 groups.

What do you think about this?

**Comment by moylop260** [comment]
FYI [isort](https://pypi.python.org/pypi/isort) supports this case too
I mean,
```bash
`isort --diff my_file.py`
@@ -1 +1 @@
-from os import path, environ
+from os import environ, path
```

**Comment by butla** [comment]
@moylop260 Yup, I know :) But it would be nice if I didn't need to install another tool just for this small (at least I think it's small) feature. Pylint does a lot anyway :)

But I'm not dying for this functionality. It's just a "nice to have".

**Comment by PCManticore** [comment]
I think this will be a bit too much and it will make it even more pedantic.
