### ISSUE TITLE
Pylint fails with Python 3.6

### ISSUE THREAD

**Issue by nvdv** [PyCQA/pylint#1241]
### Steps to reproduce
1.  Launch pylint with Python 3.6 

### Current behavior
`AttributeError: 'TreeRebuilder3k' object has no attribute 'visit_joinedstr'`

Details: https://travis-ci.org/nvdv/vprof/jobs/186750275
No problems with other versions of Python: https://travis-ci.org/nvdv/vprof

### Expected behavior
No error.

### pylint --version output
pylint 1.6.4
astroid 1.4.9
Python 3.6.0 (default, Dec 24 2016, 00:01:50) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]

**Comment by PCManticore** [comment]
We don't support 3.6 yet. You can try with the version from master branch, for both pylint and astroid.

**Comment by rayluo** [comment]
Is this issue a duplication of #1113? There was a bugfix PyCQA/astroid#365 mentioned in that thread, but it is unclear whether that one ever made it into a release.

**Comment by PCManticore** [comment]
Yes, this is a duplicate of #1113. It wasn't yet released, but it will be released with pylint 2.0. When exactly, I can't tell, but should be relatively soon. In the meantime, support for 3.6 can only be obtained from the master branch.

**Comment by beardedeagle** [comment]
Confirmed working using master branch of astroid and pylint.

**Comment by Tarrasch** [comment]
I got this working with

    pip install git+https://github.com/PyCQA/astroid.git

I will however warn that I have little idea of other possible bad side effects of doing this. Hopefully none. :)
