### ISSUE TITLE
Dunder methods assigned to `None`

### ISSUE THREAD

**Issue by rogalski** [PyCQA/pylint#1263]
### Steps to reproduce
One of Python 3.6 changes:  [It is now possible to set a special method to None to indicate that the corresponding operation is not available. For example, if a class sets `__iter__()` to None, the class is not iterable. (Contributed by Andrew Barnert and Ivan Levkivskyi in issue 25958.)
](https://docs.python.org/3/whatsnew/3.6.html)

Consider code snippet:

```
class Custom1:
    __iter__ = None
    __next__ = None


class Custom2:
    pass


for o in Custom1():
    print(o)
for o in Custom2():
    print(o)
```

Running this code results in;
``` 
(py36) mac-mini:pylint rogalski$ python3 dunder_none.py 
Traceback (most recent call last):
  File "dunder_none.py", line 10, in <module>
    for o in Custom1():
TypeError: 'Custom1' object is not iterable
```

### Current behavior
One error message is emitted:
```
E: 12, 9: Non-iterable value Custom2() is used in an iterating context (not-an-iterable)
```

### Expected behavior
Two error messages are emitted.

### pylint --version output
master
```
(py36) mac-mini:pylint rogalski$ python -m pylint --version
__main__.py 2.0.0, 
astroid 1.5.0
Python 3.6.0 (default, Dec 26 2016, 14:24:38) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

**Comment by PCManticore** [comment]
Interesting, thanks.
