### ISSUE TITLE
no-member warning with ctypes that inherit from _CData

### ISSUE THREAD

**Issue by dalai4git** [PyCQA/pylint#1268]
### Steps to reproduce
Run pylint with following script

    import ctypes
    ctypes.Structure.from_buffer

### Current behavior
pylint warns that Structure has no member from_buffer. The same is true with other _CData members.

### Expected behavior
no warning

### pylint --version output
    pylint 1.6.4
    astroid 1.4.9
    Python 3.5.2 (default, Nov 17 2016, 17:05:23)
    [GCC 5.4.0 20160609]

**Comment by PCManticore** [comment]
Yep, I can reproduce this, thank you!

**Comment by PCManticore** [comment]
I can't reproduce this any longer with pylint 1.7.2. Do note that by default we don't emit no-member if we can't infer the object properly.
