### ISSUE TITLE
msg-template not editable when pylint is called from a python script

### ISSUE THREAD

**Issue by DnPlas** [PyCQA/pylint#1269]
### Steps to reproduce
Call pylint from a python script as:
(pylint_stdout, pylint_stderr) = lint.py_run(command_options = "%s -E --msg-template={path} {msg} my_module.py", return_std=True)
and print the output of pylint_stdout.readlines()

### Current behavior
When printed, pylint_stdout is not formatted as defined in command_options (see above), but instead, the message is shown as defined in pylint/eplyint.py (line 90-92):

cmd = [sys.executable, "-c", run_cmd] + options + [
    '--msg-template', '{path}:{line}: {category} ({msg_id}, {symbol}, {obj}) {msg}',
    '-r', 'n', child_path] 

### Expected behavior
The output when printing pylint_stdout.readlines() should be: 
PATH MSG

But you get, instead:
PATH:188: error (E1101, no-member, OBJECT) MESSAGE

### pylint --version output
No config file found, using default configuration
pylint 1.6.4, 
astroid 1.4.8
Python 2.7.6 (default, Oct 26 2016, 20:30:19) 
[GCC 4.8.4]

**Comment by DnPlas** [comment]
I got a solution just by modifying lines 90-91 of pylint/epylint.py as:
    cmd = [sys.executable, "-c", run_cmd] + [
        '--msg-template', '{path}:{line}: {category} ({msg_id}, {symbol}, {obj}) {msg}',
        '-r', 'n', child_path] + options
But I'm not sure whether this is acceptable or not.

**Comment by PCManticore** [comment]
Yes, this could work. A patch would be great at this point.

**Comment by DnPlas** [comment]
Okay, sending the patch for this one
