### ISSUE TITLE
Clean up issue list for Pylint project

### ISSUE THREAD

**Issue by rogalski** [PyCQA/pylint#1280]
Currently Issues tab is in quite messy state. There are bugs imported from Bitbucket (going as far as version 1.1), many bugs are duplicates of each other, many of them refers to same root cause (most prominent example is `control_flow`, other is what is currently being solved in #1242 etc.).

There are few things to do:

- [ ] assign correct labels for all of the bugs (if there are related bugs with no common tag, create it)
- [ ] verify if bugs reproduces on repository top, if not - merge tests that proves that and close them.

@PCManticore what would be a best way to help you with that? I noticed that me and @degustaf started commenting on some of the issues, but not all comments we addressed we're re-tagged. Is there a better way to perform this process?

**Comment by PCManticore** [comment]
I went ahead a couple of weeks ago and cleaned up the issue lists. @rogalski also gained commit rights, so that he can help with triaging and issue management as well.

Thank you @rogalski, by the way, for creating this issue.
