### ISSUE TITLE
Creating a library with a magic class which avoids no-member

### ISSUE THREAD

**Issue by kootenpv** [PyCQA/pylint#1293]
So I'm afraid this will be a relatively long post, but I've tried a lot of things.

My library will return a value based on the filename. parsed json, pickle or just a string.
It goes by filename + extension. This is what the lib communicates with the users of said library.

I added a "no_exist" parameter to this function. If the file does not exist, it would normally throw, but I allow users to define a default value here. E.g. a list, or a dictionary.
The problem is that pylint complains about this, and I do not expect my users to have to add an exception, because if my library would not be able to 100% cover all the cases, I would just quit this functionality.
Anyway, I have now implemented it like this:

```python
def reader(fname, read_fn, no_exist="Throw"):
    fname = path.make_path(fname)
    if not os.path.isfile(fname) and no_exist != "Throw":
        return no_exist
    return read_fn(fname)
```

where `read_fn` could return a pickle.

The problem is that when I try to use this functionality, pylint complains that the object does not have a member X or whatever, because `pylint` thinks it will get a string.

This is absolutely not possible by design! If the file does not exist, while trying to read it, it will throw an exception. That is unless someone would give a default, upon which that would be returned. But it would never just return the string "Throw"!

I just keep getting `no-member` false positives from pylint.

My other idea was to use something like this:

```python
    class Throw():
        def __getattr__(self, x):
            return {}
```

but that does not help; I assume pylint probably just reads the source code and thus concludes that there is no member.

 So the question is: **how as a library maintainer can I prevent `no-member` errors**?

I thought perhaps the following would be a clue for me to do anything hacky necessary to accomplish my goal. In the changelog it states:

- Don’t emit no-member for classes with unknown bases.

How could I create an "unknown base"?!

You can find the context in which it was mentioned here https://pylint.readthedocs.io/en/pylint-1.5/changelog.html

**Comment by PCManticore** [comment]
Hi,

I think the best solution for your use case is writing a brain tip for your library. Check here for some examples: https://github.com/PyCQA/astroid/tree/master/astroid/brain. In your brain tip, you can either patch the AST to return something that could work for you, or you can insert a fake base class in your inheritance, if you have anything like this, or you can write an inference tip, which will control what pylint infers when inferring your function. What exactly you could do depends on what error are you getting, an example, where ``no-member`` is emitted, could help.

**Comment by kootenpv** [comment]
@PCManticore Thanks for your reply. I tried to look at the documentation + examples, but I'm not sure what to do.

As for an example, you could see the code above to get an idea.

For the actual code, you could have a look here: https://github.com/kootenpv/just/blob/master/just/__init__.py#L48

Whenever another script tries to load a pickle with `just.read`, pylint thinks that the object returned by pickle is of type "Throw", while logically this is not possible! The `Throw` class is only there because someone might want to give `None` as a default fallback variable.

To reproduce:

    pip install just

In python:

    class A():
        x = 1

    just.write(A(), "data.pkl")
    data = just.read("data.pkl") 
    data.x # this line that will say "Class 'Throw' has no member 'x'"
 
The problem in pylint's judgement is related to the code in the link. I'm very curious if someone could come up with a solution!

Obviously this is not interesting code, it's just an example of where I would prefer pylint to be silent.

**Comment by PCManticore** [comment]
I just pushed a commit which should help with this. Currently, we don't emit no-member when we detect that the object in question has a ``__getattr__`` method implemented, but this check was happening only for instances, not for classes. I added the same verifications for classes, since the following is possible:

```
class A(type):

   def __getattr__(self, attr):
       return attr
class B(metaclass=A):
    pass
B.missing
```

This change doesn't answer the question, though, of what a library maintainer can do in order to avoid spurious no-members when linting the code. In this case, if modifying the actual source code is not possible, then one can write a brain tip where:

- a ``__getattr__`` method can introduced in the body of the class

- an unknown base class can be introduced in the class's bases. Unknown here means any name that can't be inferred by pylint. Here' s a rough pseudocode of how this could look:

```
def transform_class(node):
    node.bases.append(astroid.Name('DoesNotExist'))
    # or
    node.body.append(astroid.FunctionDef(name='__getattr__')

astroid.MANAGER.register_transform(astroid.ClassDef, transform_class, is_thing_class)
```
Let's close this for now. If you have any questions about how to write a brain tip or a pylint plugin, let me know.

**Comment by kootenpv** [comment]
@PCManticore Thanks for the reply. It sounded like it is exactly what I would need? Avoid no-member by just implementing `getattr`. Somehow it does not seem to work.

I tried to update to the git master versions, pylint (2.0) gets an error, updated astroid (but then I get a runtime error), just ran the latest astroid again, and now getting:

    AttributeError: module 'astroid' has no attribute 'extract_node'

I'm not sure if updating pylint has any chance to solve the problem.

Just to be clear, I don't care about "as a maintainer" to have the error, it's just that I want to solve the issue for the users; i.e. not requiring them to pylint-"ignore" my objects. I think we're on the same page.

It would seem quite a small thing, so I hope it can be solved without writing a brain tip, but if you think that that's the only way, then I'd gladly take your offer :)
