### ISSUE TITLE
guard against uses of copy.copy(os.environ)

### ISSUE THREAD

**Issue by sebbov** [PyCQA/pylint#1301]
This is a FR (for your consideration) for pylint to include a warning against using of the construct in the title (or variants).

The intent of the construct's author most likely is to get a dict that holds a copy of the environment values.  However (at least in 2.7), it fails to achieve that.  As a result the construct can inadvertently result in changes in the os environment or in dicts believed to be local to a thread.

See  https://bugs.python.org/issue15373 for further explanation.

thanks,
-seb.

**Comment by PCManticore** [comment]
Thank you, this makes sense, especially since the result seems a bit surprising.

**Comment by AWhetter** [comment]
To any new contributors, this will require changing `StdlibChecker.visit_call` to look for calls to `copy.copy` that take os.environ, and raising a new message that recommends that the user use `os.environ.copy()` instead.
