### ISSUE TITLE
PyQt5 undefined variable erro

### ISSUE THREAD

**Issue by omdaniel** [PyCQA/pylint#1303]
### Steps to reproduce
1. Use wildcard import to for PyQt5 modules
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *

2. Use classes imported from those modules
QDialog, QDialogButtonBox, QIcon, etc....

3. Run pylint
note: wildcard import warning produced and expect, but should not produce erros

### Current behavior

E:  8,19: Undefined variable 'QDialog' (undefined-variable)
E: 15,15: Undefined variable 'QDialogButtonBox' (undefined-variable)
E: 15,37: Undefined variable 'QDialogButtonBox' (undefined-variable)
E: 16,25: Undefined variable 'QDialogButtonBox' (undefined-variable)
E: 21,22: Undefined variable 'QVBoxLayout' (undefined-variable)
E: 26,17: Undefined variable 'QMainWindow' (undefined-variable)
E: 33,16: Undefined variable 'QLabel' (undefined-variable)
E: 34,27: Undefined variable 'Qt' (undefined-variable)
E: 38,18: Undefined variable 'QToolBar' (undefined-variable)
E: 39,28: Undefined variable 'QSize' (undefined-variable)
E: 42,24: Undefined variable 'QAction' (undefined-variable)
E: 42,32: Undefined variable 'QIcon' (undefined-variable)
...

### Expected behavior

Only warning from (wildcard-import)

### pylint --version output
pylint 1.5.4, 
astroid 1.4.7
Python 3.5.2 |Anaconda 4.2.0 (64-bit)| (default, Jul  2 2016, 17:53:06) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]

**Comment by rogalski** [comment]
Since `PyQt5` is a C-extensions, it needs to be added to whitelist for Pylint to built an AST from "untrusted" source.

Please try running pylint with cmdline argument: `pylint --extension-pkg-whitelist=PyQt5  filename.py`

**Comment by omdaniel** [comment]
Thank you, that fixed the import issues
