### ISSUE TITLE
Unable to import 'os' (import-error)

### ISSUE THREAD

**Issue by bdurant** [PyCQA/pylint#1305]
### Steps to reproduce
$ cat li.py 
#!/usr/bin/env python
"""foobar"""
import os
print os.listdir(os.curdir)

$ pylint --reports=n li.py
************* Module li
F:  3, 0: Unable to import 'os' (import-error)

$ which python
/usr/bin/python

$ python --version
Python 2.7.6

$ ls /usr/lib/python2.7/os.py
/usr/lib/python2.7/os.py

$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.5 LTS"

### Current behavior
pylint reports an import error

### Expected behavior
No errors should be reported by pylint

### pylint --version output
$ pylint --version
pylint 1.1.0, 
astroid 1.0.1, common 0.61.0
Python 2.7.6 (default, Oct 26 2016, 20:30:19) 
[GCC 4.8.4]

**Comment by PCManticore** [comment]
pylint 1.1.0 is really ancient, we provide no support for it. Not sure why this happens, since I don't have access to a 14.04 Ubuntu, but it might be a path problem.
