### ISSUE TITLE
For an exception: Class 'message' has no 'startswith' member

### ISSUE THREAD

**Issue by sam-s** [PyCQA/pylint#1307]
### Steps to reproduce
```
try:
    raise Exception("foo")
except Exception as ex:
    if ex.message.startswith("foo"):
        print "Got foo"
```

### Current behavior

```
error (E1101, no-member, feed_sentiment) Class 'message' has no 'startswith' member
```

### Expected behavior

no error, no warning.
the code is correct:
```
>>> type(Exception("foo").message)
<type 'str'>
>>> Exception("foo").message.startswith
<built-in method startswith of str object at 0x10520d360>
```

### pylint --version output

```
pylint 1.6.4, 
astroid 1.4.9
Python 2.7.13 (default, Dec 19 2016, 08:29:22) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

See also [SO](http://stackoverflow.com/q/41983285/850781).

**Comment by rogalski** [comment]
I'll quote my SO answer.

```
import astroid

node = astroid.builder.parse("""
    ex = Exception()
    msg = ex.message
""")
print list(node.locals['msg'][0].infer())  # [<ClassDef(message) l.0 [exceptions] at 0x34aadd0>, <ClassDef(message) l.0 [exceptions] at 0x3482cb0>]
```

`ex.message` is inferred as custom classdef, where it should be string (or in general case, value passed to exception constructor).

**Comment by PCManticore** [comment]
Can you try with pylint 2.0? We should be good there, due to the object model support added a couple of months back in astroid 1.5.

**Comment by sam-s** [comment]
I use whatever pip installs.

**Comment by PCManticore** [comment]
I'm closing this, since it works on master, with astroid 1.5.
