### ISSUE TITLE
Issue #1080 remains: Missing "Undefined variable 'l_b' (undefined-variable)"

### ISSUE THREAD

**Issue by Aufschlauer** [PyCQA/pylint#1309]
My expectation is that after issue #1080 has been fixed, the next release will included the fix for the issue. But I just installed pylint 1.6.5 (released 22. Jan. 2017, 15:06 MEZ) and I tested against the test code: Pylint still does not detect variable l_b:

https://github.com/PyCQA/pylint/issues/1080

I don't know how to re-open the issue, so I open a new issue referring the to the old ticket. I hope this way is OK?

**Comment by PCManticore** [comment]
I think this change didn't make it in 1.6.5 (which was a very small release). You can try the code from master branch to see if it works for you.
