### ISSUE TITLE
Support #noqa:<Error Number>

### ISSUE THREAD

**Issue by gyger** [PyCQA/pylint#1310]
_This is an enhancement request._

pylint at the moment ignores all errors in a line ended with # noqa. 
Flake supports to list specific errors only, by using
`# noqa:<Error No>`
See here: https://pypi.python.org/pypi/flake8

This would be awesome, if can for example only ignore an alignment error in a line.

**Comment by JonathanWillitts** [comment]
Is it specifically the `# noqa` syntax you want to use? 

If not this can already be done with: `# pylint: disable=<error-name>`

e.g.
`# pylint: disable=line-too-long`

**Comment by gyger** [comment]
OK, I didn't know this. I didn't find the documentation and found the #noqa on flake8, so expected it to work also here, but I think if there is an errorspecific option that is good enough.

**Comment by JonathanWillitts** [comment]
Some documentation on it here: https://docs.pylint.org/en/latest/faq.html#message-control 

You can use the syntax to disable errors/warnings at either the line, block or module level, or alternatively disable for all modules (using CLI syntax when calling pylint, or via a pylintrc config file).
