### ISSUE TITLE
__all__ is not honoured for imported modules

### ISSUE THREAD

**Issue by wrohdewald** [PyCQA/pylint#1312]
### Steps to reproduce
1. 

[bug.zip](https://github.com/PyCQA/pylint/files/750483/bug.zip)

pylint3 a.py b.py

### Current behavior
b.py is illegal because Bclass is not available, but pylint3 does not emit an error.
If b.py uses Aclass instead of Bclass, pylint3 emits a warning about unused Bclass which is wrong for the same reason.

### Expected behavior
Honour __all__ in the imported module.

I scanned your repository with git log --grep __all__ and found nothing done after the version I am using, so I think this bug should still be in master.

### pylint --version output
pylint3 1.5.6, 
astroid 1.4.8
Python 3.5.2+ (default, Sep 22 2016, 12:18:14) 
[GCC 6.2.0 20160927]

**Comment by rogalski** [comment]
Thanks for submitting an issue!

**Comment by wrohdewald** [comment]
since you reverted the commit to astroid, please re-open this issue. It is valid again.

Author: Łukasz Rogalski <rogalski.91@gmail.com>
Date:   Sun Feb 5 13:57:40 2017 +0100

    Revert "Fix namespace population when wildcard import is used (#397)" (#398)
    
    This reverts commit 3e6ef99928137a396a6ee9c75351f4194b2471e8.
