### ISSUE TITLE
Pylint having problems with symbolic links

### ISSUE THREAD

**Issue by marceloslacerda** [PyCQA/pylint#1316]
Hi, pylint is having problems finding modules that are in a subdirectory of a symbolic link. Consider the following document tree:

    /scratch/pylint/
        A.py
        B.py
        __init__.py

If I run pylint against **A.py** I get no errors:

>$ cd /scratch/
>
>$ mkdir pylint
>
>$ cd pylint/
>
>$ echo "from B import *" > A.py
>
>$ touch B.py
>
>$ touch __init__.py
>
>$ pylint -r n /scratch/pylint/A.py 
>************* Module pylint.A
>W:  1, 0: Wildcard import B (wildcard-import)

If I create a new symbolic link pointing to **/scratch/pylint**, again, no errors:

>$ ln -s /scratch/pylint/ /scratch/pylint2
>$ pylint -r n /scratch/pylint/A.py
>************* Module pylint.A
>W: 1, 0: Wildcard import B (wildcard-import)
>
>$ pylint -r n /scratch/pylint2/A.py
>************* Module pylint2.A
>W: 1, 0: Wildcard import B (wildcard-import)

But if I create a submodule and move the python files there, like this:

    /scratch/
        pylint/
            A.py
            B.py
            __init__.py
        pylint2 -> /scratch/pylint/

I get the following error:

>$ cd pylint2
>$ mkdir my_module
>$ mv *.py my_module/
>$ pylint3 -r n /scratch/pylint2/my_module/A.py
>************* Module A
>W: 1, 0: Wildcard import B (wildcard-import)
>**E: 1, 0: Unable to import 'A.B' (import-error)**

This issue was [first discovered](https://github.com/flycheck/flycheck/issues/1203) in the flycheck repository.

### pylint --version output
>pylint3 1.5.2, 
>astroid 1.4.9
>Python 3.4.2 (default, Oct  8 2014, 10:45:20) 
>[GCC 4.9.1]

**Comment by PCManticore** [comment]
Here is what I am getting using the code from the master branch:

```
(root) ➜  pylint2 python -m pylint /home/claudiu/projects/tests/scratch/pylint2/my_module/A.py -rn
No config file found, using default configuration
************* Module my_module.A
C:  1, 0: Invalid module name "A" (invalid-name)
C:  1, 0: Missing module docstring (missing-docstring)
W:  1, 0: Wildcard import B (wildcard-import)
W:  1, 0: Relative import 'B', should be 'my_module.B' (relative-import)

----------------------------------------------------------------------
Your code has been rated at -30.00/10 (previous run: -30.00/10, +0.00)
```

It seems to work, but I can't point you exactly to what change made this. I'm closing this, but if you can't confirm it works for you using 2.0, then please reopen the issue. Thank you!
