### ISSUE TITLE
Wrong unnecessary parens message

### ISSUE THREAD

**Issue by pylint-bot** [PyCQA/pylint#132]
Originally reported by: **Marc Rintsch (BitBucket: [blackjack](http://bitbucket.org/blackjack), GitHub: @blackjack?)**

---

Source

```
#!python
SPAM = not (0 < 1)
```

leads to:

```
C:  1, 0: Unnecessary parens after 'not' keyword (superfluous-parens)
```

which is not true because `not (0 < 1)` has a different result from `not 0 < 1`.

---
- Bitbucket: https://bitbucket.org/logilab/pylint/issue/132

**Comment by rogalski** [comment]
> it's still syntactically superfluous

This is enough for me to close it as wontfix.
