### ISSUE TITLE
2.0 milestone management

### ISSUE THREAD

**Issue by PCManticore** [PyCQA/pylint#1322]
Hey @rogalski and other folks interested in this,

First of all, I'm sorry for not being very involved in the project lately. I'm struggling to find time to contribute amidst other responsabilities, work and personal life. 

We didn't have a major release since quite a while, if I recall correctly, the last minor one was in July, while 1.6.0 was around February - March last year. While we do have plenty of changes in master, I was hoping in 2.0 to have at least stages finished and ready, thus justifying a 2.0 release. But as I see the current situation, the 2.0 release won't happen too soon, due to my time constraints, with the current milestone setup.

This is why I'm creating this issue. Since there are some issues left for the 2.0 milestone, what do you think we should push forward with and what we should remove from this release? 

What I would really like to have in this release would be:

- stages (getting sane issue)
- Python 3.6 support
- (maybe) configuring pylint interactively, although I can live without it.

Probably we are halfway through python 3.6 support, so that shouldn't take too long. What's your opinion about this? Should we postpone stages for later and make this release a 1.7.0? Should we make it a 2.0, without stages? Should we wait for having stages finished, knowing this might push the release for maybe one month, two months ahead?

**Comment by degustaf** [comment]
My opinion would be to push for python 3.6 support as soon as possible. Considering it has been released for almost 2 months now, and we keep getting bug reports about it not being supported.

**Comment by rogalski** [comment]
I'd say let's finish up Python 3.6 and ship 1.7.0. (with astroid 1.5.0).
Bump a priority for "getting sane" to be included in 2.0.
About interactive Pylint configuration: if intention is to do something like `tox-quickstart` (completely new endpoint), it can be implemented and shipped in minor release. I don't think it should be a blocker to major.

**Comment by PCManticore** [comment]
Thanks for the input. I created the 1.7.0 milestone, which contains only the Python 3.6 support issue. 2.0 gets delayed to April, hopefully we'll manage to finish the remaining of the issues from that milestone until then. 1.7.0 is targeted to March 14, but I think we can have it closer than this, depending on how much support we still need to add.
