### ISSUE TITLE
[Documentation] No installation note for Windows users

### ISSUE THREAD

**Issue by bald** [PyCQA/pylint#1340]
### Steps to reproduce
1.  Visit https://www.pylint.org/#install
2.  For Windows, it says: `pip install pylint # see note`
3.  `see note` is a link and directs to https://pylint.readthedocs.io/en/latest/#note-for-windows-users

### Current behavior
Missing chapter: Note for windows users

### Expected behavior
There should be a chapter, or the link itself can be removed

**Comment by PCManticore** [comment]
Thank you. This issue has to be reported at https://bitbucket.org/logilab/pylint.org. Unfortunately, pylint.org is out of our control. Also, for recent versions of pylint, there isn't any distinction between Windows and other OSes, as long as ``python -m pylint`` behaves the same on all of them.
