### ISSUE TITLE
Disable invalid-name warning and locally-disabled info message on same line

### ISSUE THREAD

**Issue by gbritton1** [PyCQA/pylint#1341]
### Steps to reproduce
1.  def ok(foo): # pylint: disable=invalid-name,locally-disabled
2. run pylint
3. 

### Current behavior
See the message:
message: 'I0011:Locally disabling invalid-name (C0103)'
at: '26,1'
source: 'pylint'

### Expected behavior
supression of the I0011 message

### pylint --version output
No config file found, using default configuration
pylint 1.6.4,
astroid 1.4.8
Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:01:18) [MSC v.1900 32 bit (Intel)]

**Comment by PCManticore** [comment]
Thanks. This behaviour should be fixed in the code from the master branch, where the information category is disabled by default.
