### ISSUE TITLE
Using nltk tokenizer gives AttributeError: 'TreeRebuilder3k' object has no attribute 'visit_joinedstr'

### ISSUE THREAD

**Issue by jsanpedro** [PyCQA/pylint#1349]
### Steps to reproduce
1. Import nltk.tokenize and instantiate a WordPunctTokenizer:
from nltk.tokenize import WordPunctTokenizer
tokens = WordPunctTokenizer().tokenize("tokenize me")
print(tokens)

### Current behavior
pylint crashes with message: 
> AttributeError: 'TreeRebuilder3k' object has no attribute 'visit_joinedstr'

### Expected behavior
Some pylint warnings

### pylint --version output
No config file found, using default configuration
pylint 1.6.5, 
astroid 1.4.9
Python 3.6.0 |Continuum Analytics, Inc.| (default, Dec 23 2016, 13:19:00) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]

**Comment by rogalski** [comment]
Python 3.6 support is not yet released, but you may try running it with pylint and astroid from master branches.

**Comment by thorade** [comment]
I had the same issue today, so I tried updating, 
`conda update pylint` was still giving me pylint 1.6.4,
`python -m pip install -U pylint` finally installed pylint 1.7.1 and that worked for me on Python 3.6

Not sure why Anaconda ships an incompatible version!?
