### ISSUE TITLE
pylint default disabled checkers should be a separate parameter from user-defined

### ISSUE THREAD

**Issue by fermulator** [PyCQA/pylint#1353]
as a child from #1352

### Steps to reproduce
1. run : "python -m pylint --generate-rcfile | grep disable="
2. users then either:
    a) wipe that list, and define their own custom disabled checkers
    b) append to that list and never think about it again
    c) they dont' change it
    d) meticulously maintain diffs

### Current behavior

For users (c) that do not use a rcfile with "disable=", when pylint adds new default disabled checkers, they benefit from the optimization.

But for (a) or (b) users, they'll never benefit from future additions/removals from the pylint project for this list.

This current list is documented : https://pylint.readthedocs.io/en/latest/reference_guide/features.html#messages-control-options

### Expected behavior

TBD

I was thinking, as an enhancement, to support a /new/ (hidden?) parameter like "default-disable=...".
Let users specify their own disabled checkers without wiping or having to manage the built-in pylint disabled checkers;

If a user /DOES/ want to run a checker which is disabled by default, they can just have "enable=<FOO>" after it.

### pylint --version output

$ python35 -m pylint --version
No config file found, using default configuration
main.py 1.5.5,
astroid 1.4.5
Python 3.5.1 (default, Dec 11 2015, 13:17:22)
[GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]

**Comment by DanielNoord** [comment]
I don't think this is a good idea. With improved documentation and the ``--generate-toml-config`` flag you can already see what the default disables are. You can then add on to this.
This adds unnecessary complexity to configuration handling which should be solved by clearer documentation and usability improvements to the `pylint-config` command.

I'd vote to close.
