### ISSUE TITLE
Link broken in doc/tutorial.rst

### ISSUE THREAD

**Issue by aklawy** [PyCQA/pylint#1370]
### Steps to reproduce
1. Go to the tutorial page
2. Click the link http://www.daniweb.com/code/snippet748.html under **Your First Pylint’ing**
3. You'll be redirected to an unrelated page

### Current behavior
You get redirected here (https://www.daniweb.com/hardware-and-software/microsoft-windows/threads/748/cant-read-io-sys), which is unrelated

### Expected behavior
A direct download link to the code snippet.

**Comment by PCManticore** [comment]
daniweb.com is not related to us.
