### ISSUE TITLE
ignore-patterns does not skip top-level files

### ISSUE THREAD

**Issue by TimurNurlygayanov** [PyCQA/pylint#1384]
### Steps to reproduce
1. Create repository with README.md file
2. Run pylint: pylint --ignore-patterns='\s+\.md|\w+\.sh' ./*
3. Run pylint with other parameters:
pylint --ignore-patterns='\S+\.md|\S+\.sh' ./* 

### Current behavior
Pylint will print all errors in README.md and *.sh scripts in the repository.
And there is no way to ignore these files.

### Expected behavior
Pylint will ignore all files which contain string "README" in names of file of directory.
Probably it is a good idea to add the option which will force pylint check only Python files.

### pylint --version output
pylint --version
pylint 1.6.5, 
astroid 1.4.9
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609]

**Comment by rogalski** [comment]
Hello, thanks for submitting an issue, I renamed issue to make it closer to actual behavior.

Right now list of files to check is built in [`pylint.lint.PyLinter.expand_files`](https://github.com/PyCQA/pylint/blob/master/pylint/lint.py#L865). It calls [`pylint.utils.expand_modules`](https://github.com/PyCQA/pylint/blob/master/pylint/utils.py#L836). In this file check [`_basename_in_blacklist_re`](https://github.com/PyCQA/pylint/blob/master/pylint/utils.py#L891)  is run only for subfiles and subdirectories and is not run for top-level files.

I'm not sure whether this was intended behaviour, but IMHO it's viable improvement suggestion.

**Comment by yupbank** [comment]
why is this closed ?

**Comment by rogalski** [comment]
Because 38608a6d165dced47939fbd612419fd64eacca63 was merged.
