### ISSUE TITLE
clarify in FAQ Python version support (3.6+)

### ISSUE THREAD

**Issue by fermulator** [PyCQA/pylint#1399]
### Steps to reproduce
1. Read https://github.com/PyCQA/pylint/issues/1072
2. OH, the FAQ says since v1.4 we support Python 3.3+
    (https://pylint.readthedocs.io/en/latest/faq.html#what-versions-of-python-is-pylint-supporting)

### Current behavior
Users will very easily (blindly) upgrade their python to 3.6+, and suddenly portions of pylint will no longer function.

### Expected behavior
Update the FAQ to denote a table matrix of version compatibility.

**Comment by rogalski** [comment]
I don't see a point in preparing 1.6.6 with updated docs, when we can simply ship 1.7.0 with working code.

**Comment by fermulator** [comment]
We'll need to make it clear that <1.7.0 doesn't support Python 3.6 in the FAQ.
