### ISSUE TITLE
pylint should run safely (DO NOT throw exceptions) when it stumbles over code it can't interpret

### ISSUE THREAD

**Issue by fermulator** [PyCQA/pylint#1408]
ENHANCEMENT

### Steps to reproduce
1. Sometimes there will be pylint version incompatibilities or even bugs.

 2. Example:
   See the scuffles of Python3.6 support:
   https://github.com/PyCQA/pylint/issues/1072
   https://github.com/PyCQA/astroid/issues/362

 3. I suppose "exact steps" are unspecific - but more of a general comment/concern for future scenarios like this.

### Current behavior
When pylint stumbles over some unsupported blob of code, it MAY throw an Exception/Error as of today.

### Expected behavior
When these occur, it would be preferred (I think?) - that pylint executes SAFELY, without throwing an error. Instead, when we trip over a line of code, or perhaps an entire file/module/package that cannot be inspected, pylint should instead throw a warning or message into the report indicating as such, and move on with the next set of line(s)/file(s).

Not sure if this breaks the contract/design of pylint ... but it really would make it more stable/reliable. Especially as some groups are using this for continuous integration, it really shouldn't throw exceptions when it can't handle something.

(the trade-off to be considered of course, is that as the % of "uninspected code" grows relative to "inspected code" ... )

### pylint --version output
```
python -m pylint --version
No config file found, using default configuration
__main__.py 1.6.5, 
astroid 1.4.9
Python 3.6.0 (default, Jan 19 2017, 02:47:46) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

**Comment by rogalski** [comment]
Both of linked issues are related to adding new node types to AST. It's done rarely enough that I don't see much value in handling such cases gracefully.

Real "root cause" of this issue is 8 month break between last meaningful release (1.6.5 was just minor copyright header changes). In future we should aim to release early and release often.

**Comment by PCManticore** [comment]
I don't think this could help at all. As @rogalski mentioned, this only happens whenever we need to add support for a new python version. But given we are all volunteers here, I think we can all agree that a 8 month break between meaningful releases isn't that long, given our limited time and resources.

**Comment by fermulator** [comment]
Can you point me in the rough direction of where in the code I MIGHT accomplish then, and i'll fork and fix myself?

**Comment by rogalski** [comment]
@fermulator You'll have to find all places where visitor pattern such as `visit_{NODE_CLASS}` is used. I we cannot find proper method to call, call some reasonable generic "default". You'll have to figure out those details yourself.

I imagine both astroid and pylint changes will be required.

This would be my initial search for astroid:
https://github.com/PyCQA/astroid/search?utf8=%E2%9C%93&q=visit_&type=
