### ISSUE TITLE
Pylint crashes with stackoverflow

### ISSUE THREAD

**Issue by maruthijr** [PyCQA/pylint#1410]
### Steps to reproduce
1. Download attached zip and unzip two files into a folder [twofiles.zip](https://github.com/PyCQA/pylint/files/900005/twofiles.zip)
2. Run `pylint --rcfile=pylintrc ./compiler.py `

### Current behavior
It fails with `RuntimeError: maximum recursion depth exceeded while calling a Python object`

### Expected behavior
It should succeed analysis

### pylint --version output
pylint 1.6.5, 
astroid 1.4.9
Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 26 2016, 12:10:39) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]

### Initial finding
It does not like this line: `rv.identifiers = object.__new__(self.identifiers.__class__)`
if that line is commented, it goes ok

#################
Full traceback is here:
[pylintTraceback.txt](https://github.com/PyCQA/pylint/files/900011/pylintTraceback.txt)

Is this related to: https://github.com/PyCQA/astroid/issues/204

**Comment by dementedhedgehog** [comment]
That's one lovely bug report.

**Comment by MasterOdin** [comment]
I encountered the same bug in a [python file](https://github.com/MasterOdin/pylint_runner/blob/bf68deebf35e643b576d192961f95d9e7e40528f/pylint_runner/main.py) in one of my projects. It seems that [this line](https://github.com/MasterOdin/pylint_runner/blob/bf68deebf35e643b576d192961f95d9e7e40528f/pylint_runner/main.py#L157) would cause the infinite recursion, unless I casted `pylint_file` to a string (`str(pylint_file)`). 

Version:
```
pylint --version
No config file found, using default configuration
pylint 1.7.0,
astroid 1.5.1
Python 2.7.13 (default, Dec 18 2016, 07:03:39)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

**Comment by PCManticore** [comment]
This no longer reproduces with 
```
pylint 2.5.0-dev1
astroid 2.4.0
Python 3.8.1 (default, Feb 13 2020, 10:17:07)
[Clang 8.1.0 (clang-802.0.42)]
```
