### ISSUE TITLE
report filename being checked

### ISSUE THREAD

**Issue by techtonik** [PyCQA/pylint#1414]
For debugging `pylint` crashes and hangs, it is convenient to make it report the filename that is being processed.

http://stackoverflow.com/questions/43076534/report-filename-that-is-being-checked/43084405#43084405

### pylint --version output
(1,4,1)
https://chromium.googlesource.com/chromium/tools/depot_tools.git/+/master/third_party/pylint/__pkginfo__.py

**Comment by rogalski** [comment]
Maybe correct approach would be to attach this information as an attribute of exception raised during parsing? Maybe implement custom `__repr__` along with it.

**Comment by The-Compiler** [comment]
What exception?

**Comment by techtonik** [comment]
In my case `pylint` just hanged on `bdb` files from standard library, so no exceptions was thrown.

**Comment by Pierre-Sassoulas** [comment]
Closing as duplicate of https://github.com/PyCQA/pylint/issues/1554
