### ISSUE TITLE
astroid.exceptions.AttributeInferenceError: '__getitem__' not found on <ClassDef.generator>

### ISSUE THREAD

**Issue by vmalloc** [PyCQA/pylint#1417]
### Steps to reproduce
1. git clone https://github.com/getslash/slash -b bugfix/3.6
2. make pylint

### pylint --version output
pylint 1.7.0,
astroid 1.5.1
Python 3.5.2 (default, Dec 28 2016, 22:15:06)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]

**Comment by PCManticore** [comment]
Thank you. Will fix it for 1.7.1

**Comment by PCManticore** [comment]
Closed by https://github.com/PyCQA/astroid/commit/b6cf7abf6b3ffe38e77a83cc38d4446d1be66930
