### ISSUE TITLE
Ignore-imports for duplicate code does not work for tuple imports

### ISSUE THREAD

**Issue by davidroeca** [PyCQA/pylint#1422]
I know that I can fix this by increasing the multiple lines check, but that prevents duplicate-code checks elsewhere. Depending on the number of imports/the location of the module this is my preferred way to explicitly import in a flexible way. Not sure how easy this would be to fix since it's import-contextual.

### Steps to reproduce
1. Install pylint in a python3.5 virtualenv
2. Generate an rcfile and set ignore-imports=yes
3. Create a.py:
```python
'''a.py'''
from os import (
    path,
    pipe,
    popen,
    abort,
)

def do_something_else():
    '''Print the dirs'''
    print(dir(path))
    print(dir(pipe))
    print(dir(popen))
    print(dir(abort))
```

4. Create b.py:
```python
'''b.py'''
from os import (
    path,
    pipe,
    popen,
    abort,
)

def do_something():
    '''Print the types'''
    print(type(path))
    print(type(pipe))
    print(type(popen))
    print(type(abort))
```

### Current behavior

```
(venv)$ pylint a.py b.py
************* Module b
R:  1, 0: Similar lines in 2 files
==a:2
==b:2
    path,
    pipe,
    popen,
    abort,
)
 (duplicate-code)

-------------------------------------------------------------------
Your code has been rated at 9.17/10
```

### Expected behavior

```
(venv)$ pylint a.py b.py
-------------------------------------------------------------------
Your code has been rated at 10.00/10
```

### pylint --version output
pylint 1.7.0, 
astroid 1.5.1
Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609]

**Comment by chkno** [comment]
This and #2019 appear to describe the same issue.
