### ISSUE TITLE
False positive non-iterable on temporyFile?

### ISSUE THREAD

**Issue by MarkSymsCtx** [PyCQA/pylint#1435]
### Steps to reproduce
1.  Sample file
#!/bin/python

"""
Test the TemporaryFile iterator
"""

import os
import tempfile

with tempfile.TemporaryFile() as nullfh:
    nullfh.write(b'Hello world!')
    nullfh.seek(0, os.SEEK_SET)
    for line in nullfh:
        line = line.strip()
        print line

### Current behavior

Reports "E: 13,16: Non-iterable value nullfh is used in an iterating context (not-an-iterable)"

### Expected behavior

Should not produce an error as the file handle produced by TemporyFile() is iterable as the code functions as expected.

### pylint --version output

pylint 1.7.1, 
astroid 1.5.2
Python 2.7.5 (default, Nov  6 2016, 00:28:07)

**Comment by PCManticore** [comment]
This is solved in master branch.
