### ISSUE TITLE
Prefix with underscore the private objects from testutils

### ISSUE THREAD

**Issue by cpennington** [PyCQA/pylint#1438]
### Steps to reproduce
1. Run the tests for https://github.com/landscapeio/pylint-django

### Current behavior
The tests break with

```
Traceback (most recent call last):
  File "test/test_func.py", line 6, in <module>
    from pylint.testutils import make_tests, LintTestUsingFile, cb_test_gen, linter
ImportError: cannot import name make_tests
```

### Expected behavior
The tests pass.

The `make_tests` function was removed in https://github.com/PyCQA/pylint/commit/2fa1375777a1314051ae5f7945ef4e189f30a5e4

**Comment by PCManticore** [comment]
To be honest, something as testutils should be considered private, outside of maybe a couple of functions from that file.

**Comment by cpennington** [comment]
@PCManticore: yeah, that's fair. The difficulty is that as an author of a pylint plugin, there's no clear pattern for writing a test of that plugin, except for pylint itself. https://github.com/landscapeio/pylint-django (not mine), and https://github.com/edx/edx-lint (mine) both ran afoul of this when that function was removed.

**Comment by ceridwen** [comment]
If it's a private API, shouldn't it be marked as _testutils.py?  Or are all of pylint's APIs private?  If so, that ought to be indicated somewhere.  At least astroid's `__init__.py` has some indications of what the private and public APIs are.  As it is, there's little documentation (and realistically no one's stepping up to improve that) and this has caught two users.  If not a leading underscore, a note somewhere about what is and isn't private?

**Comment by PCManticore** [comment]
That's a reasonable suggestion, we could probably prefix the private APIs with underscore, leaving only the handful public APis untouched. Nobody managed to do that so far because it wasn't a concern to anyone and the problem with the removed functionality is that it was for an obsolete testing methodology of Pylint (being obsoleted by test_functional, which is way saner than the former).
