### ISSUE TITLE
Support for multiple 'min-similarity-lines' values?

### ISSUE THREAD

**Issue by jacebrowning** [PyCQA/pylint#1448]
Due to test fixtures and similar expected data payloads, I often have some duplicate test code. 
I would like to be able to set a different value for `min-similarity-lines` in my test code than my application code.

Is this possible? Is there a way to nest configuration files?

I would consider just disabling the rule for test code, but that doesn't seem possible either (https://github.com/PyCQA/pylint/issues/214).

**Comment by PCManticore** [comment]
Right now this is not possible, not until https://github.com/PyCQA/pylint/issues/618 gets addressed.
