### ISSUE TITLE
False positive in global-variable-not-assigned

### ISSUE THREAD

**Issue by robertwb** [PyCQA/pylint#1453]
### Steps to reproduce

def func():
    global sys
    import sys

### Current behavior

global-variable-not-assigned

### Expected behavior

No error.

### pylint --version output

pylint 1.7.1, 
astroid 1.5.2
Python 2.7.6 (default, Oct 26 2016, 20:30:19) 
[GCC 4.8.4]

**Comment by rogalski** [comment]
[This logic for searching of assignments needs to be improved.](https://github.com/PyCQA/pylint/blob/30f0ff9178f75385c63ee0c445223641494a95aa/pylint/checkers/variables.py#L750)

Just in case any contributor wants to take a shot at this one ;)

**Comment by mar-chi-pan** [comment]
I'll have a look
