### ISSUE TITLE
ujson package no loads member

### ISSUE THREAD

**Issue by AHLinJie** [PyCQA/pylint#1454]
### Step
1. pip install ujson

### Current behavior
imoprt ujson
ujson.loads("{}")

### Expected behavior
error (E1101, no-member, post_basic) Module 'ujson' has no 'loads' member

### pylint --version output
pylint 1.7.1, 
astroid 1.5.2
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609]

**Comment by AHLinJie** [comment]
E:  2, 0: Unable to import 'ujson' (import-error)

**Comment by rogalski** [comment]
Please check whether it works after setting `extension-pkg-whitelist=ujson`

Can you elaborate on your last comment?

**Comment by AHLinJie** [comment]
got it .
thanks.

i fogot  
UltraJSON is an ultra fast JSON encoder and decoder written in pure C with bindings for Python 2.5+ and 3
