### ISSUE TITLE
Pylint gives E1102 (not-callable) when using robobrowser.find

### ISSUE THREAD

**Issue by jlf0dev** [PyCQA/pylint#1460]
### Steps to reproduce
1. Install robobrowser on python3(pip3 install robobrowser)
2. Use: `Robobrowser.find()` or `Robobrowser.find_all()`
3. Run pylint on file

### Current behavior
[not-callable] Robobrowser.find is not callable [E1102]
[not-callable] Robobrowser.find_all is not callable [E1102]

### Expected behavior
As far as I know, Pylint should not be seeing these properties as errors. Robobrowser actually uses the BeautifulSoup find for these properties so there may be an issue there. I have checked and my Robobrowser is using BeautifulSoup4.

### pylint --version output
pylint 1.7.1,
astroid 1.5.2
Python 3.5.3 (default, Jan 19 2017, 14:11:04)
[GCC 6.3.0 20170118]

**Comment by PCManticore** [comment]
There's no way for pylint to figure out what's happening with `robobrowser.RoboBrowser.find`. If you take a look at the code, `find` is equivalent to `self.parsed.find`, where `parsed` is `self.state.parsed -> self._states[self._cursor]` etc. It's super convoluted and `self._states` is somewhat of an empty list. Feel free to disable this error in place using a disable pragma. Another potential solution would be to add a brain tip in astroid for `robobrowser` but I'm not familiar enough with `robobrowser` to add a transform for it.
