### ISSUE TITLE
crash with TypeError

### ISSUE THREAD

**Issue by DanielCollins** [PyCQA/pylint#1463]
### Steps to reproduce

1.  create a.py https://gist.github.com/DanielCollins/f5d688f037f5a358c71976f55a9211d2
2.  virtualenv venv -p python3.6 && source venv/bin/activate
3.  pip install pylint WeasyPrint
4. venv/bin/pylint a.py

### Current behavior

A big TypeError. https://gist.github.com/DanielCollins/2550d711e14bc2965bebd7ae13204c08

### Expected behavior

not crash.

### pylint --version output

    No config file found, using default configuration
    pylint 1.7.1, 
    astroid 1.5.2
    Python 3.6.1 (default, Mar 27 2017, 00:27:06) 
    [GCC 6.3.1 20170306]

**Comment by DanielCollins** [comment]
i have trouble finding out which line within weasyprint is the culprit. seems like pylint is examining modules recursively without printing which one it is stuck on. it chokes when i point it at most of the modules inside `venv/lib/python3.6/site-packages/weasyprint`

**Comment by DanielCollins** [comment]
WeasyPrint==0.36.

I think it is the context manager in __init__.py

**Comment by rogalski** [comment]
Thanks for submitting an issue!

See https://github.com/PyCQA/astroid/pull/429 for fix. The only thing left is to trim test-case code so that it's a minimal code that triggers a problem.
 
If anyone is willing to help with that, it would be great.

**Comment by DanielCollins** [comment]
@rogalski https://gist.githubusercontent.com/DanielCollins/5d92ac4f0c37103e3b1a268ca6879111/raw/68f05625c4d9f338dc93c757efa3e6baf989c0c9/gistfile1.txt

**Comment by DanielCollins** [comment]
that is nonsense code, `result` is undefined. but it is about as small as an example i can find that makes it crash.

**Comment by rogalski** [comment]
@DanielCollins thanks.

It looks like there is something wrong with our understanding of context managers or `contextlib.contextmanager` decorator. I guess catching this exception is reasonable short-term fix, but underlying issue still needs to be debugged.
