### ISSUE TITLE
A bunch of errors with opencv wrapper

### ISSUE THREAD

**Issue by chrishenx** [PyCQA/pylint#1465]
What do I need to do in order to get rid of the errors shown because of cv2.
Mainly, "cv2 has no [WHATEVER] member".

### pylint --version output
No config file found, using default configuration
pylint 1.7.1,
astroid 1.5.2
Python 3.5.3 (v3.5.3:1880cb95a742, Jan 16 2017, 16:02:32) [MSC v.1900 64 bit (AMD64)]

**Comment by rogalski** [comment]
Please check whether it works after setting `extension-pkg-whitelist=cv2`.

**Comment by chrishenx** [comment]
Thanks a lot sir!

I did't knew that option actually existed.

**Comment by rogalski** [comment]
Sure, no problem.

**Comment by ultraN** [comment]
@rogalski do you any fix plan in the future? rather than add it into whitelist?
