### ISSUE TITLE
Skip no-members checks on objects which modules are not fully defined

### ISSUE THREAD

**Issue by rogalski** [PyCQA/pylint#1466]
### Steps to reproduce
#1465, #1454

### Current behavior
Errors emitted.

### Expected behavior
Maybe they don't have to be emitted?
What if no-member checker would skip emitting messages when `expr` is a module, but it's not `fully_defined()`?

### pylint --version output
master

**Comment by rogalski** [comment]
Just to clarify, obviously we would emit some form of informational message (or `warnings.warn`).

Something along lines of:
_this module is not covered due to source code being unavailable. Consider setting {whitelist-arg}={mod}_

**Comment by PCManticore** [comment]
Sounds good to me. Left just a small comment on the PR, but other than that the idea seems fair enough and it will probably reduce the amount of false positives we emit out of the box.
