### ISSUE TITLE
An Error from pylint — cannot import moudle name "exceptions"

### ISSUE THREAD

**Issue by Anthorty** [PyCQA/pylint#1475]
### Steps to reproduce
1. open a py file with Sublime 3(use pylinter)
2. Ctrl + B to build this file
3. Then I got this error message

### Current behavior
got  an error:"ImportError: cannot import name ecption"

### Expected behavior
Check normally

### pylint --version output
The lastest version

**Comment by rogalski** [comment]
Please prepare a minimal complete example - for what we know you simply just run your script which raises an error and Pylint is not even involved. Feel free to reopen after preparing minimal example (*.py file which cause malfunction after running `pylint my_file.py`) from cmdline

**Comment by Anthorty** [comment]
This error is been fixed.
The reason is I installed python2 and python3 at the same time,so the pylinter always found python2 first.
I changed python's path order,so pylinter can find python3's path and work correctly.

**Comment by Anthorty** [comment]
The error is been fixed
The reason is I installed python2 and python3 at the same time,so the pylint always found python2 first.
I changed python's path order,so pylint can find python3's path and work correctly.
