### ISSUE TITLE
Enforce two blank lines between top-level definitions

### ISSUE THREAD

**Issue by chrisspen** [PyCQA/pylint#1492]
Is there a built-in rule to check for missing blank lines between top-level definitions?

I'd like to enforce Google's [style guide](https://google.github.io/styleguide/pyguide.html?showone=Blank_Lines#Blank_Lines), and it seems like everything's supported except this rule.

If it's not currently supported, how would I add it?

**Comment by PCManticore** [comment]
No, there isn't anything like that. I would also like to keep the PEP 8 rules to a minimum. For these kind of checks, pycodestyle is better suited.
