### ISSUE TITLE
FAQ has wrong link to installation guide

### ISSUE THREAD

**Issue by Kryan90** [PyCQA/pylint#1499]
In the FAQ (https://pylint.readthedocs.io/en/latest/faq.html#how-do-i-install-pylint), the installation guide points to http://pylint.readthedocs.io/en/latest/installation.

It should be: https://pylint.readthedocs.io/en/latest/user_guide/installation.html

**Comment by rogalski** [comment]
Thanks for submitting an issue!

I'm not familiar with RST, is it possible that we have a notion of _relative_ links between docs pages? Having absolute URLs in docs smells bad to be honest.
