### ISSUE TITLE
Assigning to attribute '__class__' not defined in class slots

### ISSUE THREAD

**Issue by cprogrammer1994** [PyCQA/pylint#1506]
I change the `__class__` of objects that were successfully `released()`.
I pasted a short example below, but I have similar code in [ModernGL](https://github.com/cprogrammer1994/ModernGL).
I added slots in [this commit](https://github.com/cprogrammer1994/ModernGL/commit/1900804411e6d7e8f29f258eefb0e5bbf881738a). In my case it is critical to let the user access objects that were released already, this is why I must change the `__class__`.

I am not sure if other `__magic__` attributes are affected or not.

### Steps to reproduce

```py
class InvalidFoobar:
    __slots__ = ['foobar']


class Foobar:
    __slots__ = ['foobar']

    def release(self):
        self.__class__ = InvalidFoobar
```

### Current behavior

```py
self.__class__ = InvalidFoobar
```

causes

```
E0237:Assigning to attribute '__class__' not defined in class slots
```

### pylint --version output

```
pylint 1.7.1,
astroid 1.5.2
Python 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]
```

**Comment by PCManticore** [comment]
I think this would make sense, as long as we verify that the class that gets set has the same layout as the current class

**Comment by cprogrammer1994** [comment]
Thank you for the fix!

Will the next version contain this change?
