### ISSUE TITLE
JSON output format does not include "msg_id" field

### ISSUE THREAD

**Issue by sbwong** [PyCQA/pylint#1512]
### Steps to reproduce
1.   Run PyLint with output-format = json on any file that generates error or warning messages

### Current behavior
The returned results have no "msg_id" field, so the caller cannot process the results based on the message type which is unique to the msg_id, as opposed to the actual message text.

The currently returned fields are:  message, line, module, path, symbol, type, column, obj

### Expected behavior
Include the msg_id field in the returned JSON dictionaries by default, just as the msg_id is returned by default in the other output-formats.    

The impact on existing user code should be minimal for those that are using normal JSON decoders as the additional field will be ignored as an unused field in the resultant dictionary.

Additional note:  It would be nice if the "msg-template" option could be used to control the fields being returned by the json output-format just like it does for the other output-formats, e.g.  msg-template = '{{ "id":{msg_id}, "location": {obj}, "line":{line}, "msg":{message}" }}'

### pylint --version output

No config file found, using default configuration
pylint 1.7.1,
astroid 1.5.2
Python 3.5.3 (v3.5.3:1880cb95a742, Jan 16 2017, 16:02:32) [MSC v.1900 64 bit (AMD64)]

**Comment by rogalski** [comment]
Thanks for submitting an issue!

Sounds reasonable.

In case anyone is willing to submit a PR, implementation is fairly trivial. [`handle_message` in json.py](https://github.com/PyCQA/pylint/blob/master/pylint/reporters/json.py#L28) needs to add extra key-value pair to appended dictionary. `msg.msgid` attribute contains message id.
