### ISSUE TITLE
False positive of wrong-import-order

### ISSUE THREAD

**Issue by chrisspen** [PyCQA/pylint#1516]
I have code like:

    import httplib
    import ssl

And `pylint==1.6.4` throws the error:

    standard import "import ssl" comes before "import httplib" (wrong-import-order)

However, both ssl and httplib are standard libraries.

    https://docs.python.org/2/library/ssl.html
    https://docs.python.org/2/library/httplib.html

I can't upgrade to a more recent version of pylint because of many open bugs in the 1.6.5 and 1.7.* releases, which are already reported.

Even then, if I flip the import order, I get the same error...but for:

    standard import "import httplib" comes before "import ssl" (wrong-import-order)

**Comment by PCManticore** [comment]
This works on 1.7.X, there isn't anything we can do about it.
