### ISSUE TITLE
Deprecated unittest assert functions not found when using testtools

### ISSUE THREAD

**Issue by ianw** [PyCQA/pylint#1523]
The following correctly gives  ``Using deprecated method assertRaisesRegexp()`` 

```python
import unittest

class RegexTestCase(unittest.TestCase):
    def first(self):
        with self.assertRaisesRegexp(RuntimeError, "runtime error"):
            raise RuntimeError
```

but using "testools.TestCase" doesn't

```python
import testtools

class RegexTestCase(testtools.TestCase):
    def first(self):
        with self.assertRaisesRegexp(RuntimeError, "runtime error"):
            raise RuntimeError
```

I do understand that testtools isn't unittest, but in this case it seems it should be a straight inheritance as they do seem to be referring to the same thing (at least for this function, testtools wraps other stuff I guess).

```
>>> import testtools
>>> import unittest
>>> a = testtools.TestCase
>>> b = unittest.TestCase
>>> print(a.assertRaisesRegexp)
<function TestCase._deprecate.<locals>.deprecated_func at 0x7f1830b80ae8>
>>> print(b.assertRaisesRegexp)
<function TestCase._deprecate.<locals>.deprecated_func at 0x7f18347ec268>
>>> 
```

I can see the matching in stdlib.py is looking for this ```depreacated_func``` wrapper to trigger this, so I guess something must be confusing the inheritance matching; I can see in ```stdlib.py:visit_node``` that ```node.func.infer``` is empty in the testtools case.

testtools is pretty common wrapper around unittest, and it would be good to get this warning if possible

```
$ .tox/pylint-py35/bin/pylint --version
No config file found, using default configuration
pylint 1.7.1, 
astroid 1.5.3
Python 3.5.3 (default, May 10 2017, 15:05:55) 
[GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]
```

**Comment by PCManticore** [comment]
I don't think this belongs in deprecated-method, since this check is for stdlib modules only.
