### ISSUE TITLE
Circular import: "class already defined"

### ISSUE THREAD

**Issue by jhpratt** [PyCQA/pylint#1527]
### Steps to reproduce
1. Circular import
2. Class defined in one of the files

### Current behavior
Error: class already defined (function-redefined)

### Expected behavior
No error

### pylint --version output
pylint 1.5.2, 
astroid 1.4.4
Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609]

**Comment by PCManticore** [comment]
Please provide a minimal working example. It will also be great if you can test with the latest release, e.g 1.7.
