### ISSUE TITLE
Option to exclude `self` when counting arguments

### ISSUE THREAD

**Issue by jhpratt** [PyCQA/pylint#1528]
### Current behavior
Counts `self` when counting arguments

### Expected behavior
Option to exclude `self` when counting arguments. The most common usage doesn't use it as an argument.

### pylint --version output
pylint 1.5.2, 
astroid 1.4.4
Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609]

**Comment by PCManticore** [comment]
I'm not sure what this issue is about. Can you clarify a bit what do you mean?
