### ISSUE TITLE
False E0602 on simple lambda currying

### ISSUE THREAD

**Issue by OfirAgami** [PyCQA/pylint#1561]
### Steps to reproduce
1. add = lambda a: lambda b: a + b

### Current behavior
[pylint] E0602:Undefined variable 'a'

### Expected behavior
It shoudn't alert, there is no error here.

### pylint --version output
pylint 1.7.1,
astroid 1.5.3
Python 2.7.13

**Comment by PCManticore** [comment]
Duplicate of  https://github.com/PyCQA/pylint/issues/760.
