### ISSUE TITLE
NO_SETUPTOOLS=1 python setup.py requires setuptools

### ISSUE THREAD

**Issue by mwhudson** [PyCQA/pylint#1571]
### Steps to reproduce
1. Do not have setuptools installed
2. Download & unpack pylint 1.7.2
2. Run NO_SETUPTOOLS=1 python setup.py

### Current behavior

```
# NO_SETUPTOOLS=1 python setup.py 
Traceback (most recent call last):
  File "setup.py", line 42, in <module>
    exec(f.read(), __pkginfo__)
  File "<string>", line 16, in <module>
ImportError: No module named pkg_resources
```

(you don't just need pkg_resources, the next line imports setuptools)

### Expected behavior

The usual setup.py complaint about not having a command to run.

### pylint --version output

I think this was introduced by e14a722db9bf81c626fe5ee5ed2251e0935cb9be so is present in 1.7.0 and up.

I don't really know what the point of the NO_SETUPTOOLS stuff is but maybe it could just be removed? I found this because I wanted to help update pylint in Debian/Ubuntu.

**Comment by PCManticore** [comment]
Yes, we could probably just remove the NO_SETUPTOOLS stuff and be done with it.
