### ISSUE TITLE
Add error end column to the output then add the information in all the checkers

### ISSUE THREAD

**Issue by purpleP** [PyCQA/pylint#1590]
Right now it's hard to use pylint as linter integrated into text editor, because it isn't showing where error ends and sometimes doesn't even show where error starts (shows zero column for example in unused import)

**Comment by PCManticore** [comment]
You can customize this by using the ``--msg-template`` parameter. How each editor integration is using it though is not something that pylint should be aware of.

**Comment by purpleP** [comment]
@PCManticore According to docs you only have `column` fiend. Which is the column where error starts. I'm talking about outputting where the error ends.

**Comment by purpleP** [comment]
@PCManticore The issue isn't resolved. Please reopen.

**Comment by pappasam** [comment]
I agree, this issue should be re-opened

**Comment by Pierre-Sassoulas** [comment]
This is a huge one though. By the way I read that linked issue in dense analysis and highlighing till the end of the line should indeed be prefered. This can be the default value until we manage to add the real information in all the checkers.

**Comment by Pierre-Sassoulas** [comment]
Closing as completed because it was done in https://github.com/PyCQA/pylint/issues/5336
