### ISSUE TITLE
How to add a check to verify that all packages have a README.md file

### ISSUE THREAD

**Issue by mitar** [PyCQA/pylint#1591]
I was considering implementing a plugin which would require that every sub-package (sub-directory with `__init__.py`) of my larger Python package contains a `README.md` file. It seems this is not really possible to do with current plugin system?

**Comment by PCManticore** [comment]
You could implement this by having your checker implement ``visit_module``. Inside, you should check if the ``node`` argument is a package, by checking the ``is_package`` attribute. If so, then you can check the presence of a ``README.md`` file. Shouldn't be too difficult though

**Comment by mitar** [comment]
Oh, thanks! Let me try!

**Comment by mitar** [comment]
Thanks! Worked very well. Really easy to do.

```python
import os.path

from pylint import checkers, interfaces
from pylint.checkers import utils


class RequireReadme(checkers.BaseChecker):
  __implements__ = interfaces.IAstroidChecker

  name = 'require-readme'
  priority = -1
  msgs = {
    'W5501': (
      "README.md is missing in the package.",
      'require-readme',
      "All packages should have a README.md.",
    ),
  }

  @utils.check_messages('require-readme')
  def visit_module(self, node):
    if not node.package:
      return

    if not os.path.exists(os.path.join(os.path.dirname(node.path), 'README.md')):
      self.add_message(
        'require-readme', node=node,
      )


def register(linter):
  linter.register_checker(RequireReadme(linter))
```
