### ISSUE TITLE
Feature request: Option to lint on locally disabling with numbers

### ISSUE THREAD

**Issue by porglezomp** [PyCQA/pylint#1599]
I'm currently trying to replace all of the instances of `# pylint: disable=E###` etc, where features are disabled by error number rather than by name. It would be useful to have this lint to help keep those numbered errors from creeping back into the code when disables are occasionally necessary.

**Comment by hippo91** [comment]
Sorry for this comment but i don't really understand your request.
Could you be more precise please or maybe @PCManticore could explain me?
Thanks

**Comment by porglezomp** [comment]
When you have an inline comment disabling something, with `# pylint: disable=`, you can disable it either with a number or a name. It would be nice to have a lint that would warn you if you used a number, and suggested the name of the corresponding lint.

An example, you might have `# pylint: disable=C0103`, and this lint could warn about that and suggest you use `# pylint: disable=invalid-name`.

**Comment by hippo91** [comment]
Alright! Thank you @porglezomp ! 
I understand now. I will have a look ASAP!
