### ISSUE TITLE
Search in docs does not work, all results redirects to index

### ISSUE THREAD

**Issue by 1oglop1** [PyCQA/pylint#1600]
Hello, I'm not sure if this is a problem of pylint or sphinx, please correct me if this should be addressed there.

### Steps to reproduce
1. Go to https://pylint.readthedocs.io/en/latest/search.html
2. Type `pylintrc`
3. See the result leading to: Frequently Asked Questions
4. Check the result URL http://docs.pylint.org/en/latest/faq.html?highlight=pylintrc
5. Click the result

### Current behavior
When you click the search result, you are redirected to the docs index page, which is pretty annoying.

### Expected behavior
Clicking the search result takes you to the desired page

### pylint --version output
I used only docs -> latest

**Comment by rogalski** [comment]
Thank you for submitting an issue!

@PCManticore we should either force yielding correct links in [readthedocs API calls](https://readthedocs.org/api/v2/docsearch/?q=pylintrc&project=pylint&version=latest&language=en), or maybe reach to docs.pylint.org owners to set up redirection that does not trim query string.

**Comment by rogalski** [comment]
I guess it's need to be reported at https://bitbucket.org/logilab/pylint.org

**Comment by 1oglop1** [comment]
Shall I create a duplicate there? Why is the code duplicated ? (btw I do not like bit bucket)

**Comment by rogalski** [comment]
@1oglop1 we are not the owners of pylint.org domain and server.
See #1488 for similar case.

>Shall I create a duplicate there? 

Feel free to do so, I'll do it this weekend anyway (unless someone outruns me 😉  )

**Comment by rogalski** [comment]
https://bitbucket.org/logilab/pylint.org/issues/16

**Comment by bittner** [comment]
Why does the domain "docs.pylint.org" end up in the generated docs at all? I don't see anything related in the [Sphinx configuration](https://github.com/PyCQA/pylint/blob/master/doc/conf.py). :confused:

**Comment by willingc** [comment]
From mailing list:

Web Search
-------------
I went back and checked a Google search and a Duck Duck Go search on "pylint".

- On Duck Duck Go, https://www.pylint.org and https://pylint.readthedocs.io/en/latest/ are the first two hits.
- On Google, https://www.pylint.org and https://pypi.python.org/pypi/pylint are the first two hits.

For a "pylint pylintrc" search:

- On Duck Duck Go, the website and v2.0 ReadTheDocs page are in the top four hits.
- On Google, the v1.6.5 ReadThe Docs page and the GitHub repo are in the top two hits.

I'm not an SEO person but someone else may have a suggestion on how to improve the hit rate for v2.0 ReadTheDocs on Google. 

ReadTheDocs Search
-----------------------
When I try searching on "pylintrc" from the search box, I do receive 6 hits. Unfortunately, each of those when clicked redirect to the docs home page. Searching for "init-hook", I see the same behavior. 

This is a bug/configuration error in Sphinx setup or the theme of some sort.

There is an open issue on the  GitHub repo: https://github.com/PyCQA/pylint/issues/1600

I will try to take a look at it when time permits.

**Comment by PCManticore** [comment]
This should be fixed now. `docs.pylint.org` was marked as the canonical domain for serving the documentation, which is why the redirect & search didn't quite work. Now I marked `pylint.pycqa.org` as the canonical domain, and this should fix the problem. If you go to `docs.pylint.org` you'll be redirected to `pylint.readthedocs.io` (as this was the redirect that the owners of pylint.org added). The navigation uses `readthedocs.io` as well, the search though uses the canonical `pylint.pycqa.org` domain, but since it is just a readthedocs.io instance, it redirects correctly. Let me know if you still have issues with search or the documentation in general!
