### ISSUE TITLE
Inline disable clause followed by other text is handled counterintuitively

### ISSUE THREAD

**Issue by rogalski** [PyCQA/pylint#1617]
### Steps to reproduce
    x = MagicObjectWithDunderEquals()
    func(x == True) # pylint: disable=E712 @IgnorePep8

### Current behavior
Local disable clause is ignored.

### Expected behavior
Local disable clause is not ignored.

### pylint --version output
master

### Comments
It works fine with semicolon after message ID:

    x = MagicObjectWithDunderEquals()
    func(x == True) # pylint: disable=E712; @IgnorePep8

Since none of emitted message IDs/symbolic names actually have spaces in them, it seems like it's feasible to simply treat space as delimiter.
https://github.com/PyCQA/pylint/blob/master/pylint/utils.py#L66

**Comment by hippo91** [comment]
I'm unable to reproduce this. In my case the local disable clause is ignored but i got ``bad-option-value`` message.

**Comment by rogalski** [comment]
Yes. I misinterpreted an issue encountered by my colleague at work and was slightly to eager to reach false conclusions. Closing it.
