### ISSUE TITLE
[easy] No warning on duplicate imported name

### ISSUE THREAD

**Issue by pylint-bot** [PyCQA/pylint#162]
Originally reported by: **Anonymous**

----------------------------------------

I would love it if the following generated a warning:

from .a import x
from .b import x

----------------------------------------
- Bitbucket: https://bitbucket.org/logilab/pylint/issue/162

**Comment by allanlewis** [comment]
:+1:

**Comment by PCManticore** [comment]
@allanlewis this should be relatively easy to contribute. :P

**Comment by gbworks** [comment]
I am looking into this enhancement. Will provide an update once code is ready.
