### ISSUE TITLE
no-member with Qt signals using PySide

### ISSUE THREAD

**Issue by kimrandell** [PyCQA/pylint#1633]
### Steps to reproduce
1. Create **pyside_signal.py**:
```python
from PySide import QtGui
app = QtGui.QApplication([])
app.focusChanged.connect(lambda x: None)
```
2. Run
`pylint pyside_signal.py --extension-pkg-whitelist=PySide`

### Current behavior
> E: 3, 0: Instance of 'Signal' has no 'connect' member (no-member)

### Expected behavior
No errors.

### pylint --version output

> pylint 1.7.2,
astroid 1.5.3
Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)]

Note that this was already fixed for PyQt:
https://github.com/PyCQA/pylint/issues/658

**Comment by AWhetter** [comment]
Fixed in https://github.com/PyCQA/astroid/commit/4ad940ddf6afc044af21a17a01fb9acb0f8f2a6a
I hope to be able to test with PySide2 soon so that I can fix the issue for that as well if needed.

**Comment by DGalt** [comment]
Has this been checked against PySide2 yet? I'm seeing this issue there. I.e. equivalent PySide2 code to the example in the OP:

### Steps to Reproduce: 

Create file **testsig.py** containing: 
```
from PySide2 import QtWidgets
app = QtWidgets.QApplication([])
app.focusChanged.connect(lambda x: None)
```
followed by running:
`pylint testsig.py --extension-pkg-whitelist=PySide2`

Produces:
` E1101: Instance of 'Signal' has no 'connect' member (no-member)`

### pylint --version output
```
pylint 2.1.1
astroid 2.0.3
Python 3.6.4 | packaged by conda-forge | (default, Dec 24 2017, 10:11:43) [MSC v.1900 64 bit (AMD64)]
```

**Comment by PCManticore** [comment]
@DGalt nope, we haven't checked against PySide2 yet, but if you can confirm it's still happening, would you mind creating a separate issue?
