### ISSUE TITLE
Schema versioning question. semver?

### ISSUE THREAD

**Issue by lasote** [PyCQA/pylint#1650]
Hi, we are developing Conan C/C++ package manager, it's based on Python recipes and we use pylint to check the "quality" of the recipes and warn the user.
Currently, we are depending on fixed `pylint==1.6.5` but we are wondering if we can upgrade to 1.7 or 1.8 in a safety way. Are your keeping backwards compatibility between minor versions? Thanks for your effort and great project.

https://github.com/conan-io/conan/issues/1710

**Comment by rogalski** [comment]
Can you clarify on what you mean by keeping backwards compatibility?

Obviously we do not guarantee that linting output won't change. New checks are added. Old checks are improved to catch more violations (or to avoid false-positives). Sometimes avoiding false positives means that we get some new not-emitted false-negatives. You can also get different results with different version of astroid.

**Comment by lasote** [comment]
Basically:
 - parameters (Like:  '--py3k', "--reports=no", "--disable=no-absolute-import", "--persistent=no", etc.) 
 - json output format (field "type" of types "warning" "error" with a "message")

Thanks!

**Comment by rogalski** [comment]
All of those are part of public API which shall not break in minor releases.

JSON output format recently got new key/value pair in 418cf5b1a48f885edbc30cfe0b93e2b221903df4, but this is clearly not breaking change.

In terms of future development, it's possible that some public-API-breaking-changed may be introduced in 2.0.

**Comment by rogalski** [comment]
I'll close it for now, but I'll reopen if further clarification would be required.
