### ISSUE TITLE
Report column for unused imports

### ISSUE THREAD

**Issue by patrys** [PyCQA/pylint#1654]
When multiple tokens are imported from the same module it's hard to tell which one is superfluous, especially when using pylint from within an IDE where often the entire line ends up being highlighted.

**Comment by PCManticore** [comment]
We don't have access to the column offset of unused imports. For pylint all tokens have the same column and this in fact coming from Python's ast module. Other than using another low level ast module which provides columns for these tokens there is not much we can do here.
