### ISSUE TITLE
Pylint is looking files on python Packages

### ISSUE THREAD

**Issue by ignacio-chiazzo** [PyCQA/pylint#1656]
Installed `pylint`, when I run `pyplint src/*` it throws me errors on python package. All that I want to do is to check all files within the `src` folder.

**Structure Folder**
-- src
-----__init__.py
-----a.py
-----b.py

### Steps to reproduce
1.  Installed pylint
2. pylint src/*

The error that I am getting is : 

![screen shot 2017-09-11 at 7 50 56 pm](https://user-images.githubusercontent.com/11672878/30301734-8a6704be-972a-11e7-9cc7-3af390cd3e6c.png)
 

Which comes from [this library](https://github.com/timothycrosley/isort/blob/01df61383cf1d85a3b912ce501532ff15cbd1bd9/isort/settings.py#L182) that Python has. 

**Version**
pyenv 1.1.3

**Comment by rogalski** [comment]
Can you provide minimal report case that triggers this issue?

Error clearly comes from `int(max_line_length)`, which makes me think that config file comes from somewhere else that project directory, maybe from your home dir? 

This looks like looked up location list:
```python
@lru_cache()
def from_path(path):
    computed_settings = default.copy()
    _update_settings_with_config(path, '.editorconfig', '~/.editorconfig', ('*', '*.py', '**.py'), computed_settings)
    _update_settings_with_config(path, '.isort.cfg', '~/.isort.cfg', ('settings', 'isort'), computed_settings)
    _update_settings_with_config(path, 'setup.cfg', None, ('isort', ), computed_settings)
    _update_settings_with_config(path, 'tox.ini', None, ('isort', ), computed_settings)
    return computed_settings
```

**Comment by ignacio-chiazzo** [comment]
The error comes from Isort library that python has (`/Users/myuser/.local/share/virtualenvs/got-7zSIX2Qa/lib/python3.6/site-packages/isort/settings.py`), particularly this line 

https://github.com/timothycrosley/isort/blob/01df61383cf1d85a3b912ce501532ff15cbd1bd9/isort/settings.py#L182-L183

**Comment by rogalski** [comment]
@ignacio-chiazzo In case I didn't make it clear - yes, it comes from said line.

The thing is actual _value_ passed to `int()` comes from user-defined settings.

    max_line_length = settings.pop('max_line_length', '').strip()

Where

    settings = _get_config_data(file_path, sections).copy()

And those settings comes from somewhere _in your environment_. It's not pylint fault that your isort is misconfigured.

**Comment by ignacio-chiazzo** [comment]
oh sorry, I misunderstand your first commend. Yes, you're right. @rogalski 

Anyways why pylint is looking at that file? why does it check that?

thanks so much for replying me so fast!

**Comment by PCManticore** [comment]
This is a problem with isort, not with pylint
