### ISSUE TITLE
Incorrect useless-else-on-loop warning

### ISSUE THREAD

**Issue by davisyoshida** [PyCQA/pylint#1661]
### Steps to reproduce
Run pylint the following code:

    def main():
    for _ in range(10):
        if 1 < 2:
            for _ in range(3):
                if 3 < 2:
                    break
            else:
                break
    else:
        return True
    return False

    if __name__ == '__main__':
        print(main())
### Current behavior
Pylint raises a useless-else-on-loop warning for the outer else statement. It seems that the break inside the else statement of the inner for loop is not correctly handled by pylint.

### Expected behavior
There should be no warning. If this code is run then the outer else statement will not execute (False is printed) which means that the else statement is not useless.

### pylint --version output
pylint 1.7.1, 
astroid 1.5.2
Python 3.6.2 (default, Jul 20 2017, 03:52:27) 
[GCC 7.1.1 20170630]

**Comment by rogalski** [comment]
Wrong code is in `_loop_exits_early` in https://github.com/PyCQA/pylint/blob/master/pylint/checkers/base.py#L121 .

It seems like we do not check else block in inner loop, because it's enclosed in if statement.

**Comment by PCManticore** [comment]
Closed by https://github.com/PyCQA/pylint/pull/1687
