### ISSUE TITLE
Warn about unused disables

### ISSUE THREAD

**Issue by nschloe** [PyCQA/pylint#1666]
Sometimes, I put local exceptions in my code like
```python
# pylint: disable=too-many-arguments
def fun(a, b):
    return a+b
```
Here, the exception isn't really needed since the function doesn't have too many arguments (anymore). Is there a way for pylint to report this?

**Comment by rogalski** [comment]
I browsed a code a little bit, but from what I see that won't be easy with current design.

We collect all local disables on one pass and then refer to collected data in `add_message` method, exit early is done if message is disabled.

As a result, there is no clear place to put code before message is disabled  (to start tracking of rejected messages) or after message is re-enabled (to check if rejected messages contains locally disabled message).

If anyone would be interested in investigating more, I recommend taking look at `PyLinter.file_state` and `MessagesHandlerMixIn.add_message`

**Comment by PCManticore** [comment]
Check ``useless-suppression``, this should fix your problem:

```
$ pylint a.py --enable=useless-suppression
No config file found, using default configuration
************* Module a
C:  1, 0: Missing module docstring (missing-docstring)
C:  2, 0: Argument name "a" doesn't conform to 'argument-name-hint' template (invalid-name)
C:  2, 0: Argument name "b" doesn't conform to 'argument-name-hint' template (invalid-name)
C:  2, 0: Missing function docstring (missing-docstring)
I:  1, 0: Useless suppression of 'too-many-arguments' (useless-suppression)
```

**Comment by rogalski** [comment]
Oh, wow, learning something new every day :) . Somehow I missed that in a codebase.
