### ISSUE TITLE
Seems that d8c6920912377f26a9613a15c6b3937d89f138ec didn't make it to release

### ISSUE THREAD

**Issue by alkuzad** [PyCQA/pylint#1668]
### Steps to reproduce
1. pip install pylint===1.7.2
2. echo 'import sys;print 1 if len(sys.argv) > 0 else 2' > test.py
3. pylint test.py | grep 'len-as-condition'

### Current behavior
Outputs:
No config file found, using default configuration
C:  1,22: Do not use `len(SEQUENCE)` as condition value (len-as-condition)

### Expected behavior
Should output better message:
Do not use `len(SEQUENCE)` to determine if a sequence is empty

### pylint --version output
pylint --version
No config file found, using default configuration
pylint 1.7.2,
astroid 1.5.3
Python 2.7.6 (default, Jan 16 2014, 16:21:56)
[GCC 4.1.2 20080704 (Red Hat 4.1.2-46)]

https://github.com/PyCQA/pylint/commit/d8c6920912377f26a9613a15c6b3937d89f138ec was added to master in May but release 1.7.2, released in June does not have it.

Is that manual merge bug or just release schema does not allow changing of API ? What is the process of releasing pypi ?

**Comment by rogalski** [comment]
You can verify branches and tags which contain said commit in Github GUI (below commit message, above commit author). For this change, it says clearly that it does not belong to any tagged release, and lives only on master branch.

1.7 was branched from earlier commit and does not contain referenced one. See [commit history for 1.7 branch](https://github.com/PyCQA/pylint/commits/1.7). 

> Is that manual merge bug or just release schema does not allow changing of API ?

Typically, after major release only bug fixes are added in subsequent minor releases (and that's the case here).

> Is that manual merge bug or just release schema does not allow changing of API ?

@PCManticore is release manager. Releases are done "when time is right", we don't have any planned roadmap - there are not enough contributors to plan work in reasonable way.

**Comment by alkuzad** [comment]
@rogalski I know how to check history but thanks for reminder. 

The problem is that when code exists only in master, especially one that is simple enough to not be any problem - does not add any value. It was just waste of time to make it as no one will use it on production.

And indeed current message is not descriptive.

**Comment by PCManticore** [comment]
Feel free to install from master if that solves your problem with code living only in master. We'll release it once the time is right, which will be sometimes this year.
