### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by SowingSadness** [PyCQA/pylint#1670]
### Steps to reproduce
1.  pylint request_generation
2. catch error )
![image](https://user-images.githubusercontent.com/576443/30697407-8e623dd0-9ee7-11e7-82ea-0f412499ab17.png)
[request_generation.zip](https://github.com/PyCQA/pylint/files/1321256/request_generation.zip)

### pylint --version output
C:\>pylint --version
pylint 1.7.2,
astroid 1.5.3
Python 3.6.2 (v3.6.2:5fd33b5, Jul  8 2017, 04:14:34) [MSC v.1900 32 bit (Intel)]

**Comment by rogalski** [comment]
When opened in Atom, `asn1_utils.py` is shown as single-line line. When re-saved with fixed encoding, problem no longer occurs.

**Comment by SowingSadness** [comment]
@rogalski thx for you answer. 
You are right, this files have "\r" line separator symbol. But I do not understand why is it problem for pylint?
We have many files  created in old macos. They all have that line separator. If I will change that, I lost line history in repository annotation :(

**Comment by rogalski** [comment]
OK, I found a little bit of time to do through debug.

For your file (with `\r` as endline char), `fh.readline` method yields full file as single (comment) line. `readline` is used as "data source" to `tokenize` module, therefore out collected tokens does not match built AST tree, which causes discrepancy.

I'm no yet sure what would be a good workaround for this. If anyone have a good idea, pull requests are welcome.

**Comment by SowingSadness** [comment]
In this case, i think It's not pylint issue

**Comment by ram-bv** [comment]
If PyLint responds this way to files with \r in them, or because of any other cause, maybe there should be a friendly error message saying "Your file has \r in it so PyLint can't run"?
