### ISSUE TITLE
pylint 1.7.3 still has 1.7.2 version number

### ISSUE THREAD

**Issue by kyrios123** [PyCQA/pylint#1684]
### Steps to reproduce
1. pylint --version
2. check Changelog

### Current behavior
1.
```
No config file found, using default configuration
pylint 1.7.2, 
astroid 1.5.3
Python 2.7.13 (default, Jan 12 2017, 13:55:14) 
[GCC 6.3.0]
```
2.
```
------------------
Pylint's ChangeLog
------------------

What's New in Pylint 1.7.2?
===========================

Release date: 2017-06-03
```
### Expected behavior
1. version 1.7.3
2. changelog for version 1.7.3

### pylint --version output
see above

**Comment by PCManticore** [comment]
make sure you are using the recently installed binary and not something else. This is what I'm getting on my machine.

```
(env) claudiu@root$ pylint --version
pylint 1.7.3, 
astroid 1.5.3
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609]
(env) claudiu@root$ 
```

**Comment by kyrios123** [comment]
You're right, shame on me. I still had an old terminal open.
