### ISSUE TITLE
Enhancement request: Respect XDG basedir spec

### ISSUE THREAD

**Issue by jleclanche** [PyCQA/pylint#1688]
https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html

Reference code: https://github.com/PyCQA/pylint/blob/master/pylint/config.py

Pylint currently defaults PYLINT_HOME to ~/.pylint.d. The basedir spec would expect it to be in `$XDG_CONFIG_HOME/pylint`, defaulting `$XDG_CONFIG_HOME` to `$HOME/.config` if it is not set.

Thoughts?

**Comment by PCManticore** [comment]
Closed as dupicate of https://github.com/PyCQA/pylint/issues/1364. I'm not keen on adding yet another place where pylint's configs can live.
