### ISSUE TITLE
Please keep an up-to-date changelog

### ISSUE THREAD

**Issue by underyx** [PyCQA/pylint#1689]
I can't find release notes for 1.7.3 and 1.7.4. Could you note down changes made in all new releases?

**Comment by kayhayen** [comment]
Thanks for creating the issue. At least I found out that I am not alone in not finding it.

**Comment by PCManticore** [comment]
The linked commit contains the changes that went in 1.7.3 and 1.7.4. As mentioned there, 1.7.3 contains two backports from master, while 1.7.4 is just a bogus release because 1.7.3 had `.pyc` files in it.
