### ISSUE TITLE
unicode as a type is found undefined

### ISSUE THREAD

**Issue by crystalfp** [PyCQA/pylint#1696]
### Steps to reproduce
Check the following file:

```
title = "A normal perché"
cond = True
if isinstance(title, unicode):
    print("Is unicode")
if isinstance(cond, bool):
    print("Is bool")
```

pylint complains:
E:  4,21: Undefined variable 'unicode' (undefined-variable)

Instead no complain for bool

Is something related to python 2 vs. 3?

### pylint --version output

pylint 1.7.4,
astroid 1.5.3
Python 3.6.2 (v3.6.2:5fd33b5, Jul  8 2017, 04:57:36) [MSC v.1900 64 bit (AMD64)]

**Comment by rogalski** [comment]
You are using name which is undefined in Python 3.x. It's not a `pylint` issue.
