### ISSUE TITLE
Exception parsing Python 3.6 formatted string

### ISSUE THREAD

**Issue by nieksand** [PyCQA/pylint#1705]
### Steps to reproduce
1. Plop this little snippet of Python 3.6 code in a .py file and run pylint:
```
def bug():
        print(f'{"blergh:":<20}')
```

### Current behavior
Pylint throws an exception while apparently traversing AST.

Capture of Pylint output:
https://gist.github.com/nieksand/c8968518e36c43d68af30c69c90e37c0

### Expected behavior
Graceful Pylint exit if syntax not supported.  

### pylint --version output
```
wart:~ nieksand$ pylint --version
No config file found, using default configuration
pylint 1.7.4, 
astroid 1.5.3
Python 3.6.2 (default, Jul 17 2017, 16:44:47) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

**Comment by rogalski** [comment]
Thank your for submitting an issue!

**Comment by PCManticore** [comment]
This is fixed by https://github.com/PyCQA/astroid/commit/515936563ff8bea1a9764ed01eb500c35a305445#diff-310d4a337efe2a241937d62d2f8ffd75
