### ISSUE TITLE
Back port "False positive bad-python3-import for stat module" to 1.7

### ISSUE THREAD

**Issue by tiran** [PyCQA/pylint#1708]
#1565 was not back ported into 1.7 branch. Release 1.7.4 still contains the erroneous bad-python3-import for the stat module. Please back port 2e50e9ee1806bb019c3cdc79bfe594a923fa483d

**Comment by PCManticore** [comment]
With a huge delay, we just released 1.7.5, which contains this change. sorry for the long wait!
