### ISSUE TITLE
Similarities within one file are not found

### ISSUE THREAD

**Issue by VladimirChukharev** [PyCQA/pylint#1711]
Perhaps, this is a request for enhancement.

### Steps to reproduce
Create two files and run pylint against one and two of them.
f1.py:
```
#!/usr/bin/env python
# -*- coding: utf8 -*-

"Demonstration of not found similarities: file 1."

def func1():
    "A function with enough lines"
    var = [
        1,
        2,
        3,
        4,
        ]
    print var

def func2():
    "A similar function"
    var = [
        0,
        2,
        3,
        4,
        ]
    print var
```

f2.py:
```
#!/usr/bin/env python
# -*- coding: utf8 -*-

"Demonstration of not found similarities: file 2, exposing the duplication in file 1"

def func2():
    "Another similar function"
    var = [
        10,
        2,
        3,
        4,
        ]
    print var
```

### Current behavior
No duplication is found in f1.py alone:
```
 $ pylint f1.py
No config file found, using default configuration

--------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 10.00/10, +0.00)
```
Similarities are found if both files are checked:
```
 $ pylint f1.py f2.py
No config file found, using default configuration
************* Module f2
R:  1, 0: Similar lines in 3 files
==f1:19
==f1:9
==f2:9
        2,
        3,
        4,
        ]
    print var (duplicate-code)

------------------------------------------------------------------
Your code has been rated at 8.89/10 (previous run: 8.89/10, +0.00)
```

### Expected behavior
Duplication is found also when pylint is run for one file.

### pylint --version output
 ```
$ pylint --version
No config file found, using default configuration
pylint 1.7.4, 
astroid 1.5.3
Python 2.7.14 (default, Oct  3 2017, 15:04:39) 
[GCC 4.2.1 Compatible FreeBSD Clang 3.4.1 (tags/RELEASE_34/dot1-final 208032)]
```

**Comment by rogalski** [comment]
> Duplication is found also when pylint is run for one file.

Why? Why `pylint` should browse through files in your directory blindly in order to _maybe_ find a duplication? You told `pylint` explicitly _not to look at_ other files.

**Comment by VladimirChukharev** [comment]
Sorry that I was not clear enough. You completely missed the point because of this.

I do not ask pylint to look into other other files. I ask for an enhancement: let pylint look for similarities within the same file.

Currently, it does not even try to do so, it searches for duplication between files, not between different parts of the same file.

My example with the second file only shows that there is a duplication within the first file: two parts of the first file are same as one part in the second. Hence, those two parts are same between them. You can also see this with your eyes.
