### ISSUE TITLE
R1707 trailing-comma-tuple ignoring lists

### ISSUE THREAD

**Issue by meeech** [PyCQA/pylint#1713]
### Steps to reproduce
1. `trailingcomma = ['f'],`

### Current behavior
Error not raised

### Expected behavior
To get the message for R1707

### pylint --version output
pylint 1.7.1,
astroid 1.5.3
Python 3.5.3 (default, Jun  5 2017, 14:27:24)

trailing-comma-tuple works as expected when presented with `trailingcomma = 'f',`

**Comment by rogalski** [comment]
Thank your for submitting an issue.
@brycepg was kind enough to start working on it in #1721.

**Comment by brycepg** [comment]
I've been bitten by this issue before, fixed :)
Thanks for the issue
