### ISSUE TITLE
support xml output

### ISSUE THREAD

**Issue by 201power** [PyCQA/pylint#1714]
Current pylint does not support xml output. Is it possible to output the code analysis results in xml?

**Comment by danields761** [comment]
Yes, this possible, see [here](https://pylint.readthedocs.io/en/latest/technical_reference/features.html#reports-options)

**Comment by rogalski** [comment]
You'd need to implement your own reporter class, similarly to e.g. `pylint.reporters.json.JSONReporter`.

Pull requests are welcome!

**Comment by PCManticore** [comment]
I see no reason why we should support xml. If you need such output, it's possible to use a custom reporter or build something on top of the json reporter.

**Comment by chingc** [comment]
Most continuous integration platforms support the xUnit/JUnit XML or Cucumber JSON reporting formats for test results.  Having this support would make it easy to integrate linting into the CI pipeline.  Please reconsider.

**Comment by allanlewis** [comment]
You could use `pytest-pylint` to run Pylint and use Pytest's `--junit-xml` option.
