### ISSUE TITLE
C0411 Importing user module on python 3

### ISSUE THREAD

**Issue by camilonova** [PyCQA/pylint#1716]
### Current behavior
I have a local module called user and pylint is thinking is the user module on python 2

`from user.data import CHOICES`

### Expected behavior
It should take user module as a local module instead as a python module

### pylint --version output
pylint==1.7.4

**Comment by rogalski** [comment]
If you want to lint 3.x code, you need to use 3.x interpreter to do linting (and vice versa). We use underlying `ast` module as a basic source of information about code. This module is part of interpreter - we cannot switch between 2.x and 3.x on demand, it's just impossible.

**Comment by camilonova** [comment]
How do I use the 3.x linter?

I did use `pip install pylint` and pip was installed using python3

**Comment by dstromberg** [comment]
Some OS's have a package for pylint3 which provides a /usr/bin/pylint3 or similar.

On others, try:
python3 -m pylint

**Comment by camilonova** [comment]
@rogalski I just tried again with a fresh virtualenv using python3.6 and it is reporting `user` as a python module (it is in python2, not python3).

`pylint==1.7.4`

![screen shot 2017-12-09 at 5 04 53 pm](https://user-images.githubusercontent.com/202559/33799905-17845dba-dd03-11e7-9903-ba2c11984c1b.png)

I only want to run the linter for python3, no need to switch on demand.

**Comment by camilonova** [comment]
@rogalski this is still happening, I'm sure of using pylint with python3. I don't need to check python2.

Maybe there is any way to tell `ast` this is a python3 file?
