### ISSUE TITLE
pylint text output has no metadata about the msg-template to parse the data.

### ISSUE THREAD

**Issue by komal436** [PyCQA/pylint#1717]
### Steps to reproduce
1. run pylint on a file and output it to a txt file
2. Eg: pylint text.py | out-file temp.txt

The metadata will be helpful to parse the output text easily.

### Current behavior
1. The temp.txt doesn't have any info on the template used to format the output.

### Expected behavior
1. The output file should have the metadata about the msg-template

### pylint --version output
PS D:\pylint> pylint --version
Using config file D:\pylint\pylintrc
pylint 1.8.0,
astroid 1.5.3
Python 3.6.3 |Anaconda, Inc.| (default, Oct 15 2017, 03:27:45) [MSC v.1900 64 bit (AMD64)]

**Comment by rogalski** [comment]
For parsable output, `json` output format seems much more feasible.

**Comment by komal436** [comment]
@rogalski : You are right. Since pylint support the text output format. It will be good to have the complete metadata needed to parse the output.

**Comment by danields761** [comment]
@komal436 , here is workaround: you can write custom reporter (see -f option), which overrides `BaseReporter.handle_message` method, and inspect frames below. The most interesting frame is the frame of `MessagesHandlerMixIn.add_message` method which holds all message metadata.

**Comment by PCManticore** [comment]
Please use `json` reporter or a custom reporter for this use case.
