### ISSUE TITLE
missing-docstring is emitted even with docstrings written.

### ISSUE THREAD

**Issue by Everspace** [PyCQA/pylint#1722]
### Steps to reproduce

Use the following snippet for `example.py`:

    #!/usr/bin/env python
    """
    Does Things
    """

    def dotinate(strings):
        """Joins an iterable with dots"""
        return '.'.join(strings)

    help(__name__)

### Current behavior

Running 

    pylint example.py

Results in 

    ##########Linting Output - pylint##########
    ************* Module example
    1,0,convention,C0111:Missing module docstring
    6,0,convention,C0111:Missing function docstring

### Expected behavior

Silence

### pylint --version output

    No config file found, using default configuration
    pylint 1.7.4,
    astroid 1.5.3
    Python 3.7.0a2 (v3.7.0a2:f7ac4fe, Oct 17 2017, 17:06:29) [MSC v.1900 64 bit (AMD64)]

On Windows 10 Pro Build 15063.674

**Comment by rogalski** [comment]
It does not reproduce on any released versions of Python interpreter.

It's likely related to [this entry in core changelog](https://docs.python.org/3.7/whatsnew/3.7.html#changes-in-the-python-api):
> Module, FunctionDef, AsyncFunctionDef, and ClassDef AST nodes now have a new docstring field. The first statement in their body is not considered as a docstring anymore. co_firstlineno and co_lnotab of code object for class and module are affected by this change. (Contributed by INADA Naoki and Eugene Toder in bpo-29463.)

**Comment by rogalski** [comment]
Adding link to relevant patch in CPython code, in case anyone want to take a shot at it: https://github.com/python/cpython/pull/46/

**Comment by PCManticore** [comment]
Fun times, supporting 3.7. :)

**Comment by PCManticore** [comment]
This is fixed in the master branch.
