### ISSUE TITLE
install error osx 10.11.6

### ISSUE THREAD

**Issue by schroef** [PyCQA/pylint#1734]
### Steps to reproduce
1. Open terminl
2. Paste > pip install pylint
3. See error

### Current behavior
When i try to install pylin using provided install code i see a error. I believe i have python3.4

### Expected behavior
Proper installment

### pylint --version output
???

<img width="906" alt="screen shot 2017-11-12 at 04 21 58" src="https://user-images.githubusercontent.com/6923008/32697173-50217806-c737-11e7-8a08-ecc1745e17a4.png">

**Comment by moylop260** [comment]
You are affecting a folder where your user dont have access.

You could try “pip install —user pylint”
or try “sudo”

**Comment by schroef** [comment]
Using user pylint, this gets returned

<img width="894" alt="screen shot 2017-11-12 at 16 01 51" src="https://user-images.githubusercontent.com/6923008/32702821-f1225174-c798-11e7-8797-5df7bce29f40.png">

Im dont know really much about terminal and installing items. Whats the complete code for the sudo?? You mean; sudo pip install —user pylint?

**Comment by schroef** [comment]
sudi pip install —user pylint gives me this error that im not the owner???

<img width="1440" alt="screen shot 2017-11-12 at 16 03 45" src="https://user-images.githubusercontent.com/6923008/32702843-38a89eb8-c799-11e7-9941-333a83ce4481.png">

**Comment by schroef** [comment]
I know changed permission of cache folder to read & write. Then tried running sudi pip install again. But that again gave the error about folder not beeing owned.

then tried sudi pip install pylint, which gave a small yellow warning and then installed something.

<img width="1440" alt="screen shot 2017-11-12 at 16 07 03" src="https://user-images.githubusercontent.com/6923008/32702877-c9a121ce-c799-11e7-971a-36f8f3161b2e.png">

**Comment by PCManticore** [comment]
@schroef I'm afraid this is not a pylint problem. One solution to avoid all this hassle is to install pylint in a virtualenv
