### ISSUE TITLE
Naming-style options not available

### ISSUE THREAD

**Issue by zspitz** [PyCQA/pylint#1744]
### Steps to reproduce
```
pylint --const-naming-style=any test.py
```

### Current behavior
```
pylint: error: no such option: --const-naming-style
```

### Expected behavior
The [documentation](https://pylint.readthedocs.io/en/latest/user_guide/options.html) seems to imply that the predefined naming style options are available. It also seems to already have been merged into master (#1046).

### pylint --version output
```
pylint 1.7.4,
astroid 1.5.3
Python 3.6.2 (v3.6.2:5fd33b5, Jul  8 2017, 04:57:36) [MSC v.1900 64 bit (AMD64)]
```

**Comment by PCManticore** [comment]
This feature wasn't released yet, it will be part of 1.8 once that gets released.
