### ISSUE TITLE
pylint --rcfile not-existing-file  uses default config

### ISSUE THREAD

**Issue by thisch** [PyCQA/pylint#1747]
### Steps to reproduce
1. pylint --rcfile not-existing-file

### Current behavior
`pylint --rcfile not-existing-file`

outputs

`No config file found, using default configuration`

### Expected behavior

pylint should raise an exception/output error msg if a non-existing rcfile was specified on the commandline. Using the default configuration is quite surprising IMO. In my company we've recently moved/renamed the pylintrc file but forgot to adapt the script containing the call to pylint. We were wondering why our pylint jenkins job showed so many errors. If pylint would have printed a warning to the console and returned an non-zero exit status we would have immediately noticed that the pylintrc filename was wrong.

### pylint --version output

pylint 1.7.2, 
astroid 1.5.3
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609]

**Comment by PCManticore** [comment]
This definitely sounds like a good improvement, thanks for raising the issue.
