### ISSUE TITLE
pyreverse generate activity diagram

### ISSUE THREAD

**Issue by jethroguce** [PyCQA/pylint#1749]
is it possible to make `pyreverse` generate an activity diagram from functions or class definition?

![Activity Diagram](http://s.plantuml.com/imgp/1d5-activity-diagram-beta-016.png)

current PlantUML Syntax can be found here.
http://plantuml.com/activity-diagram-beta

**Comment by PCManticore** [comment]
I'm afraid no. While technically it would be possible, we currently lack the manpower to tackle such projects, especially in components that don't receive that much love such as `pyreverse`
