### ISSUE TITLE
Module 'pygit2' has no ... member (no-member) even with extension-pkg-whitelist=pygit2

### ISSUE THREAD

**Issue by thecjharries** [PyCQA/pylint#1750]
### Steps to reproduce
I've been trying to come at this a few different ways to make sure I'm not doing something stupid. If I am, I can't figure out what it is.

The short version is this command doesn't work:
```bash
$ pylint --init-hook='import os;import pygit2;print(pygit2.discover_repository(os.getcwd()))' --extension-pkg-whitelist=pygit2 <some file with pygit2>
```
### Current behavior
I'm running this on Windows 10 17025. As much as I'd like to blame the issue on WSL's very interesting innards, it looks like the problem happens natively in PowerShell and `cmd`.
#### `bash`
```bash
$ pylint --init-hook="import os;import pygit2;print(pygit2.discover_repository(os.getcwd()))" --extension-pkg-whitelist=pygit2 <some file with pygit2>
<repo path>/.git/
************* Module tmp
E:  5, 6: Module 'pygit2' has no 'discover_repository' member (no-member)

---------------------------------------------------------------------
```
To fully duplicate my config, I recorded setting up a `virtualenv` following [`pygit2`'s official docs](http://www.pygit2.org/install.html#libgit2-within-a-virtual-environment):

[![asciicast](https://asciinema.org/a/fh6jzhLnw6mbiarfApmP5j2mv.png)](https://asciinema.org/a/fh6jzhLnw6mbiarfApmP5j2mv)

Edit: I forgot to mention I had to install these packages to actually build `libgit2`:
```
needed today: python-dev cmake libssl-dev libgit2-dev libffi-dev libffi6
already had: python openssl build-essential git
```
I previously installed `pip` via [`get-pip`](https://github.com/pypa/get-pip) and used it to install `virtualenv`. There might be others I missed. RHEL distros might have it a bit easier; the linker doesn't require so much massaging.

These are the commands I used (well, the successful ones, anyway):
```bash
$ cd /tmp
$ virtualenv venv
$ source venv/bin/activate
$ export LIBGIT2=$VIRTUAL_ENV
$ wget https://github.com/libgit2/libgit2/archive/v0.26.0.tar.gz
$ tar xzf v0.26.0.tar.gz
$ cd libgit2-0.26.0/
$ cmake . -DCMAKE_INSTALL_PREFIX=$LIBGIT2
$ make
$ make install
$ export LDFLAGS="-Wl,-rpath='$LIBGIT2/lib',--enable-new-dtags $LDFLAGS"
$ cd ..
$ ./venv/bin/pip install pygit2
$ pip install pygit2
$ python -c 'import pygit2'
$ ./venv/bin/pip install pylint
$ mkdir some_repo
$ cd some_repo
$ git init
$ pylint --init-hook='import os;import pygit2;print(pygit2.discover_repository(os.getcwd())))' --extension-pkg-whitelist=pygit2 <some file with pygit2>
```
(That last one changed because I wasn't actually reviewing the results until I started writing this; I originally screwed up the module to parse)

#### `PowerShell`
```powershell
PS$ pylint --init-hook='import pygit2;print(pygit2.discover_repository(\".\"))' --extension-pkg-whitelist=pygit2 'import pygit2; pygit2.discover_repository'
<repo path>/.git/
************* Module tmp
E:  5, 6: Module 'pygit2' has no 'discover_repository' member (no-member)
```
#### `cmd.exe`
```Batchfile
C> pylint.exe --init-hook="import os;import pygit2;print(pygit2.discover_repository(os.getcwd()))" --extension-pkg-whitelist=pygit2 tmp.py
<repo path>/.git/
************* Module tmp
E:  5, 6: Module 'pygit2' has no 'discover_repository' member (no-member)
```

#### `python`
```python
from os import name
from subprocess import call, Popen
from sys import stderr, stdout

# This will verify in your local
# import pygit2
# pygit2.init_repository(getcwd())
# print pygit2.discover_repository(getcwd())

with open('tmp.py', 'w+') as tmp_out:
    tmp_out.write(
            r"""
# pylint: disable=C0111
import os
import pygit2
print pygit2.discover_repository(os.getcwd())
		""")
version_command = 'pylint --version'

easy = (
    "pylint"
    " --init-hook"
    " 'import os;import pygit2;print(pygit2.discover_repository(os.getcwd()))'"
    " --extension-pkg-whitelist=pygit2 tmp.py"
)

complicated = [
    "pylint",
    "--init-hook",
    "import os;import pygit2;print(pygit2.discover_repository(os.getcwd()))",
    "--extension-pkg-whitelist=pygit2", "tmp.py"
]

shells = [
    {  # https://github.com/mattjmorrison/Pylint/blob/master/epylint.py#L140
        'method': Popen,
        'route': complicated
    },
    {
        'method': call,
        'route': ['bash', '-c', easy]
    }
]

if 'nt' == name:
    shells += [
        {
            'method': call,
            'route': ['powershell.exe', easy]
        },
        {
            'method': call,
            'route': ['cmd.exe', '/c'] + complicated
        }
    ]


for shell in shells:
    for command in [version_command, shell['route']]:
        p = shell['method'](
            command,
            shell=True,
            stdout=stdout,
            stderr=stderr
        )
        if hasattr(p, 'wait'):
            p.wait()
    print '*' * 40
```

### Expected behavior

To be honest, I'm not sure what that the behavior of `extension-pkg-whitelist` is supposed to be. I tried it because #779 was the most similar-sounding issue I was able to find while looking at this (it's almost two years old). I am pretty sure it shouldn't be erroring. I think the error has to do with [the extra installation steps](http://www.pygit2.org/install.html#the-run-path) and the native extensions, but I have no idea how debug that.

For now, I've just wrapped my `pygit2` imports in with `# pylint: (disable|enable)=no-name-in-module`.

### pylint --version output
```bash
$ pylint --version
pylint 1.7.4, 
astroid 1.5.3
Python 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)]
```

**Comment by thecjharries** [comment]
Just to make sure I wasn't crazy, I followed the installation guide with and without a `virtualenv` on a bare metal CentOS box. It was much easier to install everything, but still had the same issue with `pylint`.

**Comment by PCManticore** [comment]
@thecjharries Sorry for the long wait! You might want to try with `pylint --extension-pkg-whitelist=_pygit2` instead, since this seems to be the module from where the `discover_repository` function is actually coming from. By default `extension-pkg-whitelist` is not able to know which extension module to load: https://github.com/libgit2/pygit2/blob/master/pygit2/__init__.py#L32
