### ISSUE TITLE
Disable redefined-builtin for six imports

### ISSUE THREAD

**Issue by jart** [PyCQA/pylint#1752]
In the TensorFlow codebase, the following lines are repeated this many times:

```
      6 from six.moves import map  # pylint: disable=redefined-builtin
     10 from six.moves import range  # pylint: disable=redefined-builtin
     21 from six.moves import zip  # pylint: disable=redefined-builtin
    165 from six.moves import xrange  # pylint: disable=redefined-builtin
```

It's kind of painful. Can we just disable that at the source?

**Comment by PCManticore** [comment]
These messages should not be emitted for `six` since pylint 1.7, when we added the `redefining-builtins-module` option. You can check the release notes for that release where we mention adding this feature: https://pylint.readthedocs.io/en/latest/whatsnew/1.7.html

**Comment by jart** [comment]
I want this to be stock.

**Comment by PCManticore** [comment]
Stock what? Did you read the link I gave in my comment? This is *stock*, it is enabled by default.

**Comment by jart** [comment]
Looking at the source code, it seems the [default value](https://github.com/PyCQA/pylint/blob/56a6723f96dddd1e70e668d808e8446fd53b841f/pylint/checkers/variables.py#L361) for this setting includes `six.moves`. In that case, I was wrong; and I really want to thank you guys for having already taken the initiative on this. What an excellent piece of software.
