### ISSUE TITLE
__module__ and __qualname__ in class body is not undefined

### ISSUE THREAD

**Issue by diefans** [PyCQA/pylint#1753]
### Steps to reproduce
```python
import logging


class Class:
    log = logging.getLogger(__module__ + '.' + __qualname__)
```

### Current behavior
```
src/foo.py:5: [E0602(undefined-variable), Class] Undefined variable '__module__'
src/foo.py:5: [E0602(undefined-variable), Class] Undefined variable '__qualname__'
```

### Expected behavior
no E0602, since it is obviously not undefined, at least in python 3.5, 3.6, 3.7 and pypy3.5

### pylint --version output
```
No config file found, using default configuration
pylint 1.7.4, 
astroid 1.5.3
Python 3.5.4 (default, Nov 15 2017, 17:49:51) 
[GCC 5.4.1 20160904]
```

**Comment by PCManticore** [comment]
Thanks!

**Comment by brycepg** [comment]
My notes for working on this:

__qualname__ is defined in class locals for python 3.3+
__module__  is defined in class locals for 2 and 3

You can use the `locals()` builtin inside a class to see what's defined:

```python
class Foo:
    print(locals())
```

The class methods do not have access to these locals (using the nonlocal keyword doesn't even work)
A module does not have these variables in locals

**Comment by PCManticore** [comment]
Thanks @brycepg for tackling this one :)
