### ISSUE TITLE
Exception clause doesn't allow tuples as variables for tuple of exception classes

### ISSUE THREAD

**Issue by frenchtoast747** [PyCQA/pylint#1756]
### Steps to reproduce
1. In a virtual environment, install Openstack's keystoneauth1 package: `pip install keystoneauth1==3.2.0`
1. Create a small Python file:
    ```python
    """
    asdf
    """
    from keystoneauth1 import exceptions

    # create a predefined tuple constant of exceptions to catch
    CONNECTION_FAILURE_EXCEPTIONS = (
        exceptions.connection.ConnectFailure,
        exceptions.connection.UnknownConnectionError,
    )

    try:
        raise exceptions.connection.ConnectFailure('Oops :(')
    # try to catch the tuple of exceptions, which is valid Python.
    except CONNECTION_FAILURE_EXCEPTIONS as exc:
        print 'Something bad happened! {}'.format(exc)

    ```
1. Run `pylint test.py`

### Current behavior
When running pylint on the above test file, it reports a `catching-non-exception` error for the tuple given:

```
E: 15, 7: Catching an exception which doesn't inherit from Exception: CONNECTION_FAILURE_EXCEPTIONS (catching-non-exception)
```

### Expected behavior
I would expect that error not to be present. Consider the following similar example:
```python
"""
asdf
"""

EXCEPTIONS = (
    ValueError,
    KeyError,
    TypeError,
)

try:
    raise TypeError('Oops :(')
except EXCEPTIONS as exc:
    print 'Something bad happened! {}'.format(exc)
```

When pylint is run on the above code, it doesn't report foul play on the `EXCEPTIONS` tuple.

### pylint --version output
pylint 1.7.4,
astroid 1.5.3
Python 2.7.3 (default, Apr 10 2012, 23:31:26) [MSC v.1500 32 bit (Intel)]

---

I'm not sure why this is failing under the circumstances. I have ensured that both of the Openstack Keystone Exception classes are indeed inheriting from `Exception`. Passing in a literal tuple of the keystone exceptions works as expected, but having a variable of the same tuple does not. I would imagine that the tuple traversal is failing or not going deep enough to determine if the classes inherit from `Exception` or `BaseException`.

**Comment by PCManticore** [comment]
Thank you @frenchtoast747 ! The referenced commit should fix this problem, we're going to release it as part of 1.8 soon.

**Comment by frenchtoast747** [comment]
Awesome! Thank you very much @PCManticore !

**Comment by dmtucker** [comment]
I believe https://github.com/PyCQA/pylint/issues/2431#issuecomment-414813068 suggests this is still open.
