### ISSUE TITLE
Allow disabling of all enabled flake8 rules

### ISSUE THREAD

**Issue by gucciferXCIV** [PyCQA/pylint#1759]
Pylint and flake8 are often used and run together, _and_ they check many of the same things.
Considering that, it'd be useful if pylint (and potentially flake8, as well) had a single error code that a user could add to the value list for `disable` in their config file, or a CLI flag for only using it in certain instances, that would prevent pylint from printing the same errors flake8 had printed just beforehand.
That rule/flag would basically say to:

1. Check the flake8 config to figure out what errors are enabled.
2. Disable the errors' pylint equivalents in pylint.

It'd prevent duplicate errors, which are, at the least, annoying. If this were done in flake8, you'd just swap flake8 and pylint for one another in my rule explanation above.

My basic plan for the implementation would be:

Assuming pylint CLI received the proper flag or `flake8-duplicate-errors` is added to pylintrc's `disable`...
1. Make a dict of all errors in flake8 that have a pylint equivalent, with that equivalent as their value.
2. Have pylint search for flake8 config files the way flake8 does, only using the config with the highest priority, reading the ignored errors rule if there is one. This can basically be copy/pasted from flake8's source.
3. If errors are ignored in the flake8 config file, make a list of them.
4. Run through the dict from step 1, skipping the keys that are also in the list from step 3, returning all the other keys'(error codes') values(pylint equivalents) as the value of `flake8-duplicates-errors` using the dict from step 2.

I'm not including a commit and PR yet because I'd like to see if other people would find it useful first. If it's decided this feature should be added and we can agree on a basic plan for how to go about implementing it, I'd be fine with taking care of writing and submitting it.

Any thoughts, ideas, whatevers, are of course welcome.

**Comment by PCManticore** [comment]
I'm afraid this ties us to another tool. Ideally this should be handled by a wrapper tool, such as [prospector](https://pypi.python.org/pypi/prospector) or something else.

**Comment by gucciferXCIV** [comment]
I was going to say that it might be better to do this as a plugin or something like that, that's separate from core pylint, but the ticket was already fairly long.

So in flake8 there's an ``OptionManager`` class and I can call ``extend_default_ignore()`` and have flake8 ignore any rules added to ``ignore`` by the plugin. Is there anything like that for pylint plugins? I'm looking at the pylint docs now but don't see anything.
