### ISSUE TITLE
Version 1.8

### ISSUE THREAD

**Issue by millerdev** [PyCQA/pylint#1765]
Any idea when 1.8 will be released? Apologies if you're already working on it. I'm eager to have some of the new features incorporated into https://stickler-ci.com/

**Comment by PCManticore** [comment]
Definitely this month, but not exactly sure when. We do have some issues left for this milestone, but to be honest, outside of the f-string crash issue, we have no blocker for this release (and probably we'll move the rest to the next release)

**Comment by PCManticore** [comment]
I'm closing this for now.
