### ISSUE TITLE
background process would not stop after editor is closed

### ISSUE THREAD

**Issue by Cologler** [PyCQA/pylint#1785]
Change the `pylintrc` to

```
[MASTER]
jobs=2
```

I got over 100+ python process.

env:

visual studio code
pylint 1.7.2
Python 3.6.3

**Comment by Cologler** [comment]
https://github.com/Microsoft/vscode-python/issues/453#issuecomment-352595651

**Comment by PCManticore** [comment]
I'm sorry but you'll need to provide more details. This looks more like something that `vscode-python` should be responsible, in the sense that when `pylint` gets closed, its process pool gets closed as well.
