### ISSUE TITLE
subclasses of ignored-classes should also be ignored

### ISSUE THREAD

**Issue by jonathanverner** [PyCQA/pylint#1795]
There seems to have been a patch proposed at some point
(https://lists.logilab.org/pipermail/python-projects/2012-February/003176.html) but it seems it was not merged?

### Steps to reproduce
1. define a class `A` and its ancestor `B`
2.  add `ignored-classes=A` to `pylintrc`
3. check `B.test()`

### Current behavior
Shows the `no-member` warning for attribute test of class B.

### Expected behavior
Should ignore the attribute access since `B` is a descendant of `A` which is ignored
(see the above referenced patch for the reasoning why this would make sense)

### pylint --version output
Using config file /home/vernjaff/zdroj/brython_runner/pylintrc
pylint 1.8.1, 
astroid 1.6.0
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609]

**Comment by PCManticore** [comment]
I think the simplest solution for this is to just put the subclass in `ignored-classes`. This is going to be slow for checking every subclass against `ignored-classes`.
