### ISSUE TITLE
zip-builtin-not-iterating false positive when used as reversed function argument

### ISSUE THREAD

**Issue by rogalski** [PyCQA/pylint#1803]
### Steps to reproduce

    for a, b in reversed(zip(x,y)):
        pass

### Current behavior
    [W1637(zip-builtin-not-iterating), _._] zip built-in referenced when not iterating

### Expected behavior
    No error.

### pylint --version output
    Python 2.7, astroid 1.6.0, pylint 1.8.1

### How to fix
We need `reversed` function to be [added to this set](https://github.com/PyCQA/pylint/blob/df53e1eb10c72c77036ef22e59e1b81f6b96582b/pylint/checkers/python3.py#L73)

**Comment by gaurikholkar** [comment]
Hello!. I would like to work on this one

**Comment by gaurikholkar** [comment]
@rogalski I tried to reproduce the error with
`Python 2.7.1 , astroid 1.6.0, pylint 1.8.1`
Didn't get any error. Can you specify the exact Python version?

**Comment by rogalski** [comment]
You need to explicitly enable this message in pylintrc file or use --py3k command line switch.

**Comment by gaurikholkar** [comment]
@rogalski working now. Thanks!
