### ISSUE TITLE
Negative column number in report with triple quoted string

### ISSUE THREAD

**Issue by noxdafox** [PyCQA/pylint#1822]
The following code:

```python
import threading

""" 
Some string here
"""
```

Produces a negative column in the report:

```bash
$ pylint3 /tmp/test.py

************* Module test
W:  5,-1: String statement has no effect (pointless-string-statement)
W:  1, 0: Unused import threading (unused-import)
```

```bash
$ pylint3 --version

pylint3 1.6.5, 
astroid 1.4.9
Python 3.5.3 (default, Jan 19 2017, 14:11:04) 
[GCC 6.3.0 20170118]
```

Tested also with Pylint 1.7.4 and 1.8.1.

The triple quoting and the positioning (not as module docstring) seems to reproduce the issue.

**Comment by PCManticore** [comment]
Thanks I can reproduce this one!

**Comment by kczapla** [comment]
I looked into that. It seems that issue is astroid related. Value of col_offset of node, that represents triple quote expression is -1. PyLint checkers only read from this field.

**Comment by PCManticore** [comment]
Thanks for taking a look @kczapla ! This is just a problem of the underlying Python parser that we use, which could only be solved by using a different parser altogether.  Here's an example on how the col_offset is wrong:
```
from ast import parse
blob = '''
import threading

"""
Some string here
"""
'''
print(parse(open('a.py').read()).body[-1].col_offset) # will print -1
```

**Comment by cpitclaudel** [comment]
The problem with closing this without a fix is that it forces all consumers to fix it themselves.  IOW, the Emacs, vscode, atom, vim plugins will all have to add wrappers to the output of pylint to make it make sense.  A complete fix might not be possible, but wouldn't it work to change that `-1` to `0` when printing the message?  UIs and clients won't do much better than that, and it will save lots of duplication.
