### ISSUE TITLE
Pyreverse: Broken Command Line Parsing

### ISSUE THREAD

**Issue by pylint-bot** [PyCQA/pylint#183]
Originally reported by: **Emile Anclin (BitBucket: [anclin](http://bitbucket.org/anclin), GitHub: @anclin?)**

---

Pyreverse does not seem to recognize a malformed command line, and instead crashes in different ways. Examples of this problem and part of the discussion are in [issue 22](#22/pyreverse-valueerror-need-more-than-1#comment-9586892);

---
- Bitbucket: https://bitbucket.org/logilab/pylint/issue/183

**Comment by Pierre-Sassoulas** [comment]
This was fixed at some point, there is a proper argparse output for unknown arguments..
