### ISSUE TITLE
W1506 "threading.Thread needs the target function" incorrectly reported.

### ISSUE THREAD

**Issue by choppsv1** [PyCQA/pylint#1840]
### Steps to reproduce

bug.py:

    """Reproduce false positive"""
    import threading

    TH = threading.Thread(None, lambda: print("a target function"))
    TH.start()
    TH.join()

Verify the code:

    $ python bug.py
    a target function

### Current behavior

    $ pylint -sn -rn bug.py
    No config file found, using default configuration
    ************* Module bug
    W:  4, 5: threading.Thread needs the target function (bad-thread-instantiation)

### Expected behavior

No warning emitted.

### pylint --version output

pylint 1.8.1,
astroid 1.6.0
Python 3.6.4 (default, Dec 23 2017, 19:07:07)
[GCC 7.2.1 20171128]

**Comment by PCManticore** [comment]
Yup, thanks for reporting this issue! This would need a small change in https://github.com/PyCQA/pylint/blob/master/pylint/checkers/stdlib.py#L203, in which we should check that the length of args is bigger than 1, in which case the target function is already being passed.
