### ISSUE TITLE
pylint dependency on astroid given on pypi is vague

### ISSUE THREAD

**Issue by cdyson37** [PyCQA/pylint#1841]
This is a meta-bug, but it bit me.

I think e.g. pylint 1.8.1 depends on at least astroid 1.6.0 (for [extract_node](https://github.com/PyCQA/astroid/commit/b8dc84f2fc08bdfd82f852ecb3b98e7cf7547ec9)), however [pypi](https://pypi.python.org/pypi/pylint) only specifies "<2.0".

**Comment by PCManticore** [comment]
Yup, makes sense, we could definitely use a pin for ">=1.6,<2.0".

**Comment by PCManticore** [comment]
This is fixed in 1.8.2: https://pypi.python.org/pypi/pylint/1.8.2
