### ISSUE TITLE
[BUG] numpy float128 member shown as unknown

### ISSUE THREAD

**Issue by satyammittal** [PyCQA/pylint#1848]
### Steps to reproduce
1. in python, write numpy.float128
2. run pylint

### Current behavior
severity: 'Error'
message: 'E1101:Module 'numpy' has no 'float128' member'
at: '29,15'
source: 'pylint'
code: 'E1101'

### Expected behavior
should pass it

### pylint --version output
No config file found, using default configuration
pylint 1.8.2, 
astroid 1.6.1
Python 2.7.12 (default, Nov 20 2017, 18:23:56) 
[GCC 5.4.0 20160609]

**Comment by hippo91** [comment]
Thank you @satyammittal for this issue. It is in fact the same as issue #779 so i close this one.
