### ISSUE TITLE
Module member check error

### ISSUE THREAD

**Issue by noaRricky** [PyCQA/pylint#1857]
### Steps to reproduce
1. I type np.random.randn(8)

### Current behavior
the pylint tells me Module 'numpy.random' has no 'randn' member. However, the code runs well

### Expected behavior
pylint should not show any error informaion

### pylint --version output
1.7.4

**Comment by PCManticore** [comment]
This should work now in pylint 2.0 (e.g master branch) thanks to @hippo91 . Check https://github.com/PyCQA/pylint/issues/779 for more details on the related pull requests that made this happen.
