### ISSUE TITLE
Couple of pyreverse tests are failing with astroid 2.0

### ISSUE THREAD

**Issue by PCManticore** [PyCQA/pylint#1875]
### Steps to reproduce
1. Use astroid 2.0 as in the following commit 88d336e
2. Run the test suite using tox

### Current behavior
A couple of pyreverse tests are failing as seen here https://travis-ci.org/PyCQA/pylint/jobs/339795792

### Expected behavior

For tests to not fail. I did a `git bisect` and the faulty commit seems to be https://github.com/PyCQA/astroid/commit/025c9cc00c537f15f827c7b9698b9e58f8d813bf. Not sure *why* would this cause the pyreverse tests to fail though, probably these new attributes are triggering different visit paths in pyreverse.

**Comment by PCManticore** [comment]
CC @brycepg

**Comment by brycepg** [comment]
The name of the attribute is 'whatever' is coming from `astroid/brain/brain_builtin_inference.py:34` when inferring strings
