### ISSUE TITLE
Add the man page generation back in

### ISSUE THREAD

**Issue by AWhetter** [PyCQA/pylint#1887]
Currently is has been stripped out to make the LongHelp classes work, but it needs to be added back in.

**Comment by AWhetter** [comment]
Hey @hippo91. Just a heads up that I've rebased the `per_dir_config` branch with master today. Not much changed in `pylint/config.py` so I'm hoping that it won't create any conflicts for you.

**Comment by hippo91** [comment]
Thanks for your message @AWhetter ! I don't think i will have any conflicts but i can't check for now. I'm quite busy. I hope i'll have a bit a free time next weekend to work on this!

**Comment by Pierre-Sassoulas** [comment]
We're removing the man page generation as it's not used by debian packaging see https://github.com/PyCQA/pylint/issues/5283#issuecomment-964735075
