### ISSUE TITLE
Add `--version` flag back in

### ISSUE THREAD

**Issue by AWhetter** [PyCQA/pylint#1891]
The old template for what was printing out is currently sitting under a TODO in the PyLinter constructor in the `full_version` variable.

**Comment by fffergal** [comment]
OK. So from first glance, this needs something in CLIRunner to handle the `--version` option, and print the string in the linter and exit. So probably after option parsing, but before plugin handling? Should keep the version string on the PyLinter object too so IDE's &c. have access to it?

**Comment by fffergal** [comment]
Think I’ll use parser preprocess method and make version option part of “Commands” group. Realise all this is probably in the git history somewhere so will go hunting.

**Comment by fffergal** [comment]
OK, with some `git log -S version` and stepping in `python -m ipdb $(which pylint) --version` I've found that version printing is actually handled by stdlib optparse, and just need to pass it into its OptionParser, assuming we still use it.

**Comment by AWhetter** [comment]
I think you're right that we want to keep the version string somewhere for IDEs to use. It could even be a module level constant.
We've switched to argparse and this is handled by the CLIParser in `pylint/config.py`.
The PyLinter object used to pass the version string into the constructor of the OptionParser (https://github.com/PyCQA/pylint/blob/03aa4ca2d6a78a4d9dc69438cbc76b982aca1569/pylint/config.py#L481). But with argparse it has to be added a explicitly as a flag, so we probably want to add it as a command line specific option (https://github.com/PyCQA/pylint/blob/602c7122e1ab8866a3905c4a99407c2331ca28e9/pylint/lint.py#L852).

**Comment by fffergal** [comment]
OK good, that’s what I was considering before I discovered optparse. I even added a definition before I decided to look and see if there was from before I should add back.

**Comment by fffergal** [comment]
Thanks for the tips!

**Comment by fffergal** [comment]
Please see PR #1958. Thank you.

**Comment by PCManticore** [comment]
Thanks for tackling this @fffergal !

**Comment by fffergal** [comment]
Thank you.
