### ISSUE TITLE
Stop allowing a checker to be registered more than once

### ISSUE THREAD

**Issue by AWhetter** [PyCQA/pylint#1892]
Currently we raise a warning and keep going which will probably cause problems. We should either not register the duplicate or error out. My preference would be to simply not register the duplicate. pytest errors out when registering a plugin more than once, but this can be annoying because sometimes plugins are discovered through entry points and sometimes you have to specify it on the command line.
We should check for duplicates based on the class, not on the name. Having multiple checkers with the same name is a convenient way of turning off many error messages, and in fact the "basic" default checkers do this.

**Comment by AWhetter** [comment]
I think use `isinstance`. We wouldn't want two checkers raising the same messages.

**Comment by fffergal** [comment]
See PR. Left some comments about why not actually using isinstance, but can change. Is there a way I can move issues with PRs to in progress on the project?

**Comment by AWhetter** [comment]
Closing via #1918. Thanks for the contribution!

**Comment by fffergal** [comment]
Thank you.
