### ISSUE TITLE
Use a custom exception for when a checker has priority over zero

### ISSUE THREAD

**Issue by AWhetter** [PyCQA/pylint#1893]
Currently we raise a ValueError in PluginRegistry.register_checker.

**Comment by fffergal** [comment]
I can pick up little things like this.

Just tried it but struggling to get tests in the per_dir_config branch passing. Any tips?

**Comment by AWhetter** [comment]
A lot of the tests are failing in that branch at the moment. There's a task to fix them up (https://github.com/PyCQA/pylint/projects/1#card-7507643) but for now don't worry about them too much. Run pylint manually and check that your change is working. If you can add automated tests for your change then that would be great, even if it only raises an exception so that we have a note to fix it as part of the test fixing task.

**Comment by fffergal** [comment]
OK, managed to make a test that doesn't use any of the broken bits, `tox -- -k invalid_priority` works.

**Comment by AWhetter** [comment]
Closed via #1910
