### ISSUE TITLE
Remove six compatibility shims from the code base

### ISSUE THREAD

**Issue by PCManticore** [PyCQA/pylint#1895]
We use `six` to have a Python 2/3 compatible codebase. In #1763 we decided to have the next major release Python 3 only, which means we can remove the Python 2 compatibility shims that we previously added.
Once this is done, we can also remove `six` as a dependency.

**Comment by sushobhit27** [comment]
@PCManticore I would like to work on this issue.

**Comment by PCManticore** [comment]
Hey @sushobhit27 Feel free to tackle these issues! I'm a bit busy these days with some travelling so I won't be around for reviews and whatnot, but as soon as I'm back, I'll take a look over your PRs!

**Comment by sushobhit27** [comment]
@PCManticore Since six has to be removed for python3, all @python2_only test cases can be removed from /test/unittest_checker_python3.py, right?
