### ISSUE TITLE
Remove (some) Python 2 specific checks

### ISSUE THREAD

**Issue by PCManticore** [PyCQA/pylint#1896]
We have a bunch of checks that are only emitted when running on Python 2. We decided in #1763 to support only Python 3 for the next major release, which means that these checks will never be triggered and can be safely removed. Doing a `git grep` in the projects yield around +10 checks that are in this situation:
```
pylint/checkers/base.py:                  {'maxversion': (3, 3)}),
pylint/checkers/base.py:                      {'maxversion': (3, 0)}),
pylint/checkers/exceptions.py:              {'maxversion': (3, 0)}),
pylint/checkers/format.py:              {'maxversion': (3, 0)}),
pylint/checkers/imports.py:              {'maxversion': (3, 0)}),
pylint/checkers/misc.py:              {'maxversion': (3, 0)}),
pylint/checkers/newstyle.py:              {'maxversion': (3, 0)}),
pylint/checkers/newstyle.py:              {'maxversion': (3, 0)}),
pylint/checkers/newstyle.py:              {'maxversion': (3, 0)}),
pylint/checkers/newstyle.py:              {'maxversion': (3, 0)}),
pylint/checkers/newstyle.py:              {'maxversion': (3, 0)})
```

**Note**: we should not remove for now the checks from Python 3 porting checker (`checkers/python3`). We can definitely remove its checks that are syntax checks (say octal literal, which will never be triggered on Python 3), but for the rest of AST checks, we should remove the `maxversion` limit so that we could still run the `py3k` check but this on Python 3.

**Note**: We still want to keep some checks around. We now use `typed_ast` for parsing Python code, and we'll be able to parse Python 2 code as well via some special flag a la `pylint --two`. In this case we still want a bunch of checks around (but we can :fire: the rest).

**Comment by sushobhit27** [comment]
@PCManticore I would like to work on this issue.

**Comment by graingert** [comment]
@PCManticore why was deprecated-lambda py2 only? Seems valuable on python 3 too
