### ISSUE TITLE
Pylint returns error for 'asend' in asynchronous generator objects. [PEP 525/Python3.6]

### ISSUE THREAD

**Issue by xNinjaKittyx** [PyCQA/pylint#1907]
### Steps to reproduce
1. Create an Asynchronous Generator [PEP 525](https://www.python.org/dev/peps/pep-0525/)
2. Use `asend()`

### Current behavior
Pylint returns E1101:Generator 'generator' has no 'asend' member; maybe send?

### Expected behavior
Should check if the generator is from an async def func, and not give an error for using asend.

### pylint --version output

pylint 1.8.2,
astroid 1.6.1
Python 3.6.0

**Comment by tgandor** [comment]
Same version (1.8.2) - I tried circumventing it, by type hinting the generator function, namely `-> typing.AsyncGenerator[None, MySendType, None]`, but it doesn't help.

**Comment by PCManticore** [comment]
We don't support type hints yet.
