### ISSUE TITLE
Support running pylint from a separate virtualenv from the one the analyzed program is using

### ISSUE THREAD

**Issue by pfmoore** [PyCQA/pylint#1913]
I would like to use pylint to provide checking for my Python code in my text editor (VS Code). However, rather than installing pylint in my system Python, or in every project virtualenv, I'd like to have a central install (using `pipsi` or a simple dedicated virtualenv).

I can't see any documentation suggesting that sort of usage is supported - and I don't believe I can do this by manipulating `PYTHONPATH` (both because it's not easy to configure in VS Code, and because it's not possible to *remove* the site-packages that pylint is installed in by manipulating `PYTHONPATH`). Could this be added? Maybe by supporting a `--target-python=/path/to/interpreter/for/script` command line flag?

**Comment by PCManticore** [comment]
Thanks for the issue. I'm not exactly sure I understand, wouldn't `./path/to/other/env/python -m pylint` do the trick already?

**Comment by pfmoore** [comment]
No, because I don't have pylint installed in that environment. And I don't want to install it there - there are 2 particular situations, (1) where the other environment is my system Python which I deliberately keep with *no* non-standard packages present, and (2) where the other environment is a project-specific environment, and I don't want to have to manage adding pylint to every environment I edit Python code in, many of which are temporary testing environments.

**Comment by kapsh** [comment]
AFAIK virtualenv can be activated in the program code. Usually it contains file `bin/activate_this.py` which should be passed to `exec` to achieve this. 
I sketched pseucode like this:

```
def activate_venv(path):
    activator = os.path.join(path, 'bin', 'activate_this.py')
    exec(open(activator).read(), {'__file__': activator})


def pylint_main(args):
    if args.working_virtualenv:  # value of --virtualenv command line switch
        activate_venv(args.working_virtualenv)
    ...
```

And it even works. After invoking `activate_venv` function in Python interpeter running inside one venv to activate another I can import packages from second venv. Not sure how it will play with Pylint though, but at first glance feature looks possible.

**Comment by kapsh** [comment]
Looks like it works fine via `--init-hook` command line argument. I wrote this primitive wrapper, @pfmoore you can save the following code to `runpylint.sh` and run it as `runpylint.sh /path/to/venv/root --options files`.

```
#!/bin/bash

venv="${1:?missing path to virtualenv}"
shift

hook_code="import os; act = os.path.join(\"$venv\", 'bin', 'activate_this.py');\
    exec(open(act).read(), {'__file__': act})"
python -m pylint --init-hook "$hook_code" "$@"
```

**Comment by pfmoore** [comment]
@kapsh Thanks, I'll try to give that a go. May take a while - I don't really know much about pylint (just enough to enable it in VSCode) so I'll have to work out how it all hangs together.

Feel free to ping me if I look like I've not got round to it, and thanks for looking into it.

**Comment by kapsh** [comment]
@pfmoore For this you only need to know how to replace `pylint` command to wrapper path in your editor. But there can be another gotcha: I encountered that not all tools bootstrap `activate_this` file. So you may need to copy it manually from here https://github.com/pypa/virtualenv/blob/master/virtualenv_embedded/activate_this.py.

**Comment by pfmoore** [comment]
Thanks @kapsh. This seems to work, but there are other peculiarities with how VS Code appears to run its linter that I need to understand better before I can set things up the way I want. But those issues aren't with pylint, so I'm going to close this issue as your approach is a good solution to my original question.
