### ISSUE TITLE
RFE: more granularity in missing-docstring

### ISSUE THREAD

**Issue by sam-s** [PyCQA/pylint#1920]
### Steps to reproduce

Consider the following code:
```
def global_func(x):
    def local_func(y):
        return y + 1
    return [local_func(y) for y in x]

class MyClass(object):
    def my_method(self):
        global_func(self)
```
### Current behavior
```
z.py:1: [C0111(missing-docstring), ] Missing module docstring
z.py:1: [C0111(missing-docstring), global_func] Missing function docstring
z.py:2: [C0111(missing-docstring), global_func.local_func] Missing function docstring
z.py:6: [C0111(missing-docstring), MyClass] Missing class docstring
z.py:7: [C0111(missing-docstring), MyClass.my_method] Missing method docstring
```

### Desired behavior

These 5 issues are very different in their priorities.
While documenting modules and classes is probably quite important, local function doc is often superfluous, and sometimes even methods do not have to be documented.

I suggest 
* `missing-docstring-module`
* `missing-docstring-function`
* `missing-docstring-class`
* `missing-docstring-method`
* `missing-docstring-local`

instead of the single `missing-docstring`.
You already have (at least) 7(!) different `too-many-*` messages, so this does not look like an overkill.

### pylint --version output
```
pylint 1.8.2, 
astroid 1.6.1
Python 2.7.14 (default, Mar  1 2018, 19:26:37) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

**Comment by PCManticore** [comment]
I'm not entirely opposed to the idea, this just requires someone to do it.

**Comment by PCManticore** [comment]
This is currently being handled by https://github.com/PyCQA/pylint/pull/2036 with the old ticket being #1164. Feel free to comment on the PR for suggestions or reviews!
