### ISSUE TITLE
Discussion: Check for idiomatic/pythonic swap values for variables

### ISSUE THREAD

**Issue by pheanex** [PyCQA/pylint#1922]
Hey PyCQA,

according to i.e. [David Goodger@python.net](http://python.net/~goodger/projects/pycon/2007/idiomatic/handout.html#swap-values) and others it is idiomatic/pythonic to use tuple unpacking for swapping values of variables instead of using a temporary variable like in other languages.
How do you feel about adding a pylint checker for this idiom in particular and what do you generally think about adding more checkers for idioms of that kind in order to support writing more idiomatic code?

**Comment by brycepg** [comment]
pylint does do some checks some anti-idioms already.  `len-as-condition` (use implicit boolean conditions of containers), `singleton-comparison` (avoid x == None), `consider-iterating-dictionary`, & more

I'd be for a checker for unnecessary temporary variables in a variable swap. Something like `unnecessary-temporary-variable` or `could-use-tuple-unpacking`. The checker could look for three adjacent assignment statements and determine if they are used for swapping variable values.

**Comment by pheanex** [comment]
Thank you brycepg for your feedback. I already started [something rudimentary](https://github.com/pheanex/pylint/pull/1). I'd be happy for some feedback.
