### ISSUE TITLE
pylint has issues with IntEnum.name type detection

### ISSUE THREAD

**Issue by jleclanche** [PyCQA/pylint#1932]
```py
# test.py
from enum import IntEnum


class MyEnum(IntEnum):
    FOO = 1

    def whats_my_name(self):
        return self.name.lower()


print(MyEnum.FOO.whats_my_name())
```

### Steps to reproduce
1.  `pylint -dC test.py` with the file above

Output:
```
E:  8,15: Method 'name' has no 'lower' member (no-member)
```

### pylint --version output
pylint 1.8.2, 
astroid 1.6.1
Python 3.6.4 (default, Jan  5 2018, 02:35:40) 
[GCC 7.2.1 20171224]

**Comment by PCManticore** [comment]
Thanks for the report @jleclanche It still amazes me how much weird stuff goes around in `enum`.

**Comment by geckon** [comment]
Reproducible for a _plain_ `Enum` as well: #2062
