### ISSUE TITLE
Catch invalid string literals with `--py3k

### ISSUE THREAD

**Issue by PCManticore** [PyCQA/pylint#1938]
### Steps to reproduce
1. Lint the following `a = ur'aaa'`

### Current behavior
Does not emit anything

### Expected behavior
We should say that this is invalid in Python 3.

### pylint --version output
master

**Comment by sushobhit27** [comment]
@PCManticore Can I pick this issue, IMO a check need to be inserted in visit_assign like below:

def visit_assign(self, node):
        if isinstance(node.value, astroid.node_classes.Const) and \
            isinstance(node.value.value, unicode):
                self.add_message('explicit-unicode-assignment-not-allowed', node=node)

However I cant figure out, how to check for --py3k option in this function.

**Comment by PCManticore** [comment]
Hey @sushobhit27 ! Yes definitely! This check should actually be done in the python 3 porting checker, which you can find in `pylint/checkers/python3.py`. 

Right now all those checks are called only on Python 2 whenever the `--py3k` option is passed to `pylint` at CLI. In the future though, we might run those checks with Python 3 as well, which means that some of them will never be triggered while running on Python 3.

Also a third comment regarding your approach, this check should in fact look for tokens rather than just for `unicode` objects, because we want to blacklist just the `ur''` syntax, which is a syntax error in Python 3.

**Comment by sushobhit27** [comment]
@PCManticore  If I understood correctly, this new check will go here https://github.com/PyCQA/pylint/blob/b93cdf863896556c95b064f8405d648c69953ffa/pylint/checkers/python3.py#L990 
however existing checks under this checker like "old-ne-operator" is not working with --py3k.

(pylint) C:\Users\ssolan>
(pylint) C:\Users\ssolan>cat abc.py
def func():
    return 1 <> 2

(pylint) C:\Users\ssolan>pylint --py3k abc.py
No config file found, using default configuration

(pylint) C:\Users\ssolan>

Above behaviour is same with python2.7 and python3.
Am I missing something here?

**Comment by PCManticore** [comment]
Hey @sushobhit27 

Yes, you got it right, the new check should go in that class.
Regarding why the `old-ne-operator` doesn't work for you, that's odd! It works for me for Python 2.7. What `pylint` version do you have?

**Comment by PCManticore** [comment]
Forgot to reply @sushobhit27 The thing is that the Python 3 porting checker is activated only on Python 2, it does nothing on Python 3. That might change though since for Pylint 2.0 we'll only support Python 3 as a running environment, but we'd still want to analyze Python 2 files. 
Thanks for the PR btw!
