### ISSUE TITLE
ValueError in logging.LoggingChecker

### ISSUE THREAD

**Issue by ReneGrellert** [PyCQA/pylint#1944]
### Steps to reproduce
1. Paste the following test-method in unittest_checker_logging.py:

```
def test_error_with_invalid_format(self):
        node = astroid.parse('''
            import logging
            logging.error('0} - {1}'.format(1, 2))
        ''')
        self.walk(node)

```
2. Run the unittests
3. See the module fail

### Current behavior
Writing a line like the one in the unittest-method will result in the following exception:

> Traceback (most recent call last):
>   File "C:\Users\ReneG\git\TTS\pylintLauncherVenv.py", line 74, in <module>
>     run = pylint.lint.Run(sys.argv[1:], exit=False)
>   File "C:\PythonVirtualEnv\TTS_710_x64\lib\site-packages\pylint\lint.py", line 1347, in __init__
>     linter.check(args)
>   File "C:\PythonVirtualEnv\TTS_710_x64\lib\site-packages\pylint\lint.py", line 768, in check
>     self._do_check(files_or_modules)
>   File "C:\PythonVirtualEnv\TTS_710_x64\lib\site-packages\pylint\lint.py", line 901, in _do_check
>     self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
>   File "C:\PythonVirtualEnv\TTS_710_x64\lib\site-packages\pylint\lint.py", line 980, in check_astroid_module
>     walker.walk(ast_node)
>   File "C:\PythonVirtualEnv\TTS_710_x64\lib\site-packages\pylint\utils.py", line 1014, in walk
>     self.walk(child)
>   File "C:\PythonVirtualEnv\TTS_710_x64\lib\site-packages\pylint\utils.py", line 1014, in walk
>     self.walk(child)
>   File "C:\PythonVirtualEnv\TTS_710_x64\lib\site-packages\pylint\utils.py", line 1011, in walk
>     cb(astroid)
>   File "C:\PythonVirtualEnv\TTS_710_x64\lib\site-packages\pylint\checkers\logging.py", line 166, in visit_call
>     self._check_log_method(node, name)
>   File "C:\PythonVirtualEnv\TTS_710_x64\lib\site-packages\pylint\checkers\logging.py", line 192, in _check_log_method
>     self._check_call_func(node.args[format_pos])
>   File "C:\PythonVirtualEnv\TTS_710_x64\lib\site-packages\pylint\checkers\logging.py", line 213, in _check_call_func
>     if is_method_call(func, types, methods) and not is_complex_format_str(func.bound):
>   File "C:\PythonVirtualEnv\TTS_710_x64\lib\site-packages\pylint\checkers\logging.py", line 266, in is_complex_format_str
>     for _, _, format_spec, _ in string.Formatter().parse(inferred.value):
> ValueError: Single '}' encountered in format 

### Expected behavior
The line gets a warning "Invalid format string"

### pylint --version output
tested with 1.8.2 and 2.0.0 and Python 2.7.14

**Comment by PCManticore** [comment]
Thanks for the report!
