### ISSUE TITLE
pylint complains assertRaisesRegex is deprecated

### ISSUE THREAD

**Issue by smoser** [PyCQA/pylint#1946]
### Steps to reproduce
We have unit tests that we need to work in python 2.6 all the way to 3.6.

Older unittest2.TestCase (as seen in CentOS 6) do not have an
assertRaisesRegex method.  They only have the now-deprecated
assertRaisesRegexp.

We need our unit tests to work there and on newer python (3.6),
so we just fill the method in as seen in the test case.

This causes pylint to complain that assertRaisesRegex is deprecated.

One thing to note is that we can work around this by using getattr:

      if not hasattr(TestCase, 'assertRaisesRegex'):
          TestCase.assertRaisesRegex = getattr(TestCase, 'assertRaisesRegexp')

1. Create mytest.py

        $ cat mytest.py
        from unittest2 import TestCase
      
        if not hasattr(TestCase, 'assertRaisesRegex'):
            TestCase.assertRaisesRegex = TestCase.assertRaisesRegexp
      
        class TestMe(TestCase):
            """Test Regex"""
      
            def test_my_regex(self):
                """Use assertRaisesRegex."""
                value = "9a"
                with self.assertRaisesRegex(ValueError, r"invalid.*%s" % value):
                    int(value)

2. Run pylint on file

### Current behavior

      $ python3 -m pylint --rcfile=/dev/null mytest.py
      Using config file /dev/null
      ************* Module mytest
      W: 25,13: Using deprecated method assertRaisesRegex() (deprecated-method)

Note that it actually complains on the use of assertRaisesRegex (not assertRaisesRegex**p**)
and the warning comes not from the hackery but the use of assertRaisesRegex.

### Expected behavior

No errors on assertRaisesRegex are expected.

### pylint --version output

      $ python3 -m pylint --rcfile=/dev/null --version
      Using config file /dev/null
      __main__.py 1.8.2, 
      astroid 1.6.1
      Python 3.6.4+ (default, Feb 12 2018, 08:25:03) 
      [GCC 7.3.0]

**Comment by wulfgarpro** [comment]
+1

**Comment by PCManticore** [comment]
This should be fixed in the master branch now.
