### ISSUE TITLE
Unexpected no-name-in-module error

### ISSUE THREAD

**Issue by formulahendry** [PyCQA/pylint#1955]
### Steps to reproduce
1. Download  https://github.com/VSChina/iot-edge-python-docker/blob/e817575416449751bd705528b2e024e196d1a52b/modules/PythonModule/filter.py
2. Run `pip install azure-iothub-device-client==1.3.0.0b0`
3. Run `pylint filter.py --disable=all --enable=F,E,unreachable,duplicate-key,unnecessary-semicolon,global-variable-not-assigned,unused-variable,binary-op-exception,bad-format-string,anomalous-backslash-in-string,bad-open-mode`

### Current behavior
There are **no-name-in-module** lint errors
```
No config file found, using default configuration
************* Module filter
E: 11, 0: No name 'IoTHubClient' in module 'iothub_client' (no-name-in-module)
E: 11, 0: No name 'IoTHubClientError' in module 'iothub_client' (no-name-in-module)
E: 11, 0: No name 'IoTHubTransportProvider' in module 'iothub_client' (no-name-in-module)
E: 12, 0: No name 'IoTHubMessage' in module 'iothub_client' (no-name-in-module)
E: 12, 0: No name 'IoTHubMessageDispositionResult' in module 'iothub_client' (no-name-in-module)
E: 12, 0: No name 'IoTHubError' in module 'iothub_client' (no-name-in-module)
```

### Expected behavior
There should not be **no-name-in-module** lint errors

### pylint --version output
```
pylint 1.8.2,
astroid 1.6.1
Python 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)]
```

**Comment by PCManticore** [comment]
This seems to be a C extension module, you could try running pylint with `--extension-pkg-whitelist=iothub_client` to see if that gets rid of this problem for you. Unfortunately we have some limitations with regard to C extensions, so the only way we could analyze those is to import the modules and build ASTs from the actual module object.
Unfortunately I can't actually test that this works since this package seems to be Windows specific? I might be wrong though.

**Comment by formulahendry** [comment]
Hi @PCManticore , yes, it wrap the c code. And the package 1.3.0.0b0 version of the package (https://pypi.python.org/pypi/azure-iothub-device-client/1.3.0.0b0) supports on Linux.

> the only way we could analyze those is to import the modules and build ASTs from the actual module object
Is this need to be improved in the future? So for now, I need to use `--extension-pkg-whitelist=iothub_client`, right?
