### ISSUE TITLE
Disable 'line too long' checks just for shebang line?

### ISSUE THREAD

**Issue by jfhc** [PyCQA/pylint#1957]
Feature request: I would like to *not* disable C0301, but ignore it just for a shebang line (if present). E.g. if the first line of the file starts with `#!`, don't check for C0301, otherwise act as normal?

I posted about this [on stackoverflow](https://stackoverflow.com/q/49425288/8131703):

> So if the max line length is 5 (for sake of example), with this file:
> 
>     #!/run/stuff
>     x=3
>     print(x)
> 
> They should complain about the third line but not the first one. 
> 
> But with this file:
> 
>     x = 1 + 1 + 1
>     # Print the result
>     print(x)
> 
> It should complain about all three lines.

**Comment by PCManticore** [comment]
This seems a bit too specialized, but ColonelF suggested a potential solution that could work without any additions to pylint: https://stackoverflow.com/a/49462966/211050
