### ISSUE TITLE
too-many-function-args with functions inside six.moves.urllib_parse 

### ISSUE THREAD

**Issue by mpeterson** [PyCQA/pylint#1965]
### Description

There seems to be a problem with the usage of urllib.parse through six and how pylint handles it, leading to a `too-many-function-args` error.

### Steps to reproduce

1. Create file foo.py
2. Run pylint on it

**foo.py**
```python
from six.moves import urllib_parse as urlparse

urlparse.urlunparse(
    urlparse.ParseResult('http', '', '', None, None, None)
)
```

### Current behavior

```
$ pylint foo.py
No config file found, using default configuration
************* Module foo
C:  1, 0: Missing module docstring (missing-docstring)
E:  3, 0: Too many positional arguments for function call (too-many-function-args)

----------------------------------------------------------------------
Your code has been rated at -20.00/10 (previous run: -20.00/10, +0.00)
```
That would result in a `too-many-function-args` error from PyLint on urlunparse, as you can see.

### Expected behavior 

The linter succeeds without the `too-many-function-args` error.

### pylint --version output
```
$ pylint --version
No config file found, using default configuration   
pylint 1.8.3,                                       
astroid 1.6.2
```
```
$ python -c 'import six; print(six.__version__)'
1.11.0
```
```
$ python --version
Python 2.7.14
```

**Comment by PCManticore** [comment]
This is fixed now in astroid 1.6, we'll just have to release it.
