### ISSUE TITLE
Require two blank lines surrounding functions

### ISSUE THREAD

**Issue by garyking** [PyCQA/pylint#1970]
How can I get pylint to require that there are exactly two blank lines surrounding functions? Or does this rule not exist in pylint yet?

**Comment by jwkvam** [comment]
I think you want [pycodestyle](https://github.com/PyCQA/pycodestyle)

**Comment by garyking** [comment]
Is there any reason why pylint doesn't also enforce this one rule, among the many others that it does support?

**Comment by PCManticore** [comment]
No one got to implement it, we don't have rules for the entire PEP 8. You definitely want pycodestyle here as I don't see pylint implementing PEP 8 anytime too soon.
