### ISSUE TITLE
Raise an exception is maxversion is not a tuple

### ISSUE THREAD

**Issue by PCManticore** [PyCQA/pylint#1986]
### Steps to reproduce
1. Create a new pylint checker and set `maxversion` for a message to something else than a tuple, say a string.
2. Enable the checker and see that the message is never emitted.

### Current behavior
The message is never emitted.

### Expected behavior
We should raise an exception here. What is happening is that on Python 2 we can compare objects of different types, while on Python 3 this fails with an exception. In this case we were comparing a string to a tuple (sys.version_info), resulting in the condition to be false all the time.

### pylint --version output
1.8 and master, but more important in 1.8.

**Comment by fureigh** [comment]
Taking a look as part of the PyCon sprint. 🐍🎉

**Comment by PCManticore** [comment]
Given that we're on Python 3 now, it's going to error when comparing objects of different types anyway.
