### ISSUE TITLE
PyLint doesn't handle python six very well.

### ISSUE THREAD

**Issue by pylint-bot** [PyCQA/pylint#200]
Originally reported by: **Thomas Grainger (BitBucket: [graingert](http://bitbucket.org/graingert), GitHub: @graingert?)**

----------------------------------------

When using `from six.moves import range` pylint complains that built-ins are being overridden.

In actual fact it should complain that the built-in range is used rather than the forward-looking six.moves version.

https://bitbucket.org/logilab/pylint.org/issue/4

----------------------------------------
- Bitbucket: https://bitbucket.org/logilab/pylint/issue/200

**Comment by PCManticore** [comment]
For the record, this was fixed with https://github.com/PyCQA/pylint/commit/ad7c2cd38f7213edd1ff37aaead86d5ae8390df4 a while ago.

**Comment by graingert** [comment]
oh sweet, GitHub
