### ISSUE TITLE
Getting "import-error" for package that exists in pipenv

### ISSUE THREAD

**Issue by garyking** [PyCQA/pylint#2002]
I've got a project, where pipenv is setup. In pipenv, the `timeago` package is installed, but it's not installed in my global pip. 

So when I run `pylint file.py`, it tells me `E:  3, 0: Unable to import 'timeago' (E0401: import-error)` even though it does actually exist, in the pipenv.

It should be possible to point pylint to the pipenv copy of all packages, so that this error does not occur.

**Comment by tetienne** [comment]
@garyking Did you manage to solve your issue?

**Comment by garyking** [comment]
@tetienne No, I just stopped using pylint.
