### ISSUE TITLE
Pylint giving sequence index error where there should be none

### ISSUE THREAD

**Issue by rmullin7286** [PyCQA/pylint#2017]
### Steps to reproduce
    def format_user_info(info):
        """format a user info dict for printing."""
        yes = red('Yes')
        no = 'No'
        info = 'USER INFO:\n'
        info += '\tName: {}\n'.format(info['name'])
        info += '\tUser: {}\n'.format(info['username'])
        info += '\tWSU ID#: {}\n'.format(info['sid'])
        info += '\tAccount Expired: {}\n'.format(yes if info['accountExpired'] else no)
        info += '\tPassword Expired: {}\n'.format(yes if info['pwdExpired'] else no)
        info += '\tAccount Disabled: {}\n'.format(yes if info['accountDisabled'] else no)
        info += '\tLast Logon: {}'.format(info['lastLogon'])
        return info

### Current behavior
Pylint gives the error "Sequence index is not an int, slice, or instance with __index__" on every line where I call the index of info, which is a dict 

### Expected behavior
There should be no errors in this function, since it's valid code

### pylint --version output
pylint 1.8.4,
astroid 1.6.3
Python 3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 18:11:49) [MSC v.1900 64 bit (AMD64)]

**Comment by PCManticore** [comment]
Even if `info` the parameter can be a dict, later on you're reassigning it to a string, which cannot be indexed with strings, so the error you're receiving is correct.
