### ISSUE TITLE
allow-wildcard-with-all should have an option to restrict its use to within __init__.py

### ISSUE THREAD

**Issue by NeilGirdhar** [PyCQA/pylint#2026]
Importing `*` is the standard way to populate packages in `__init__.py`.  Importing `*` is ugly within modules.  Could we have a third option to allow-wildcard-with-all besides yes and no that restricts it to `__init__.py`?

**Comment by NeilGirdhar** [comment]
Yes, that makes perfect sense.

**Comment by AWhetter** [comment]
To any new contributors who want to look at this issue; [The imports checker](https://github.com/PyCQA/pylint/blob/1c0356f0683901e6e3561f4caeb176ff3e20be1e/pylint/checkers/imports.py#L789) is responsible for raising `wildcard-import`. It will need to check that the scope of the import node is a [module](http://astroid.readthedocs.io/en/latest/api/astroid.nodes.html#astroid.nodes.Module) and that the module is a package.

**Comment by PCManticore** [comment]
Fixed by https://github.com/PyCQA/pylint/pull/2084
