### ISSUE TITLE
bad-mcs-classmethod-argument conflicts with PEP 8

### ISSUE THREAD

**Issue by NeilGirdhar** [PyCQA/pylint#2028]
Pylint states:

> Metaclass class method __new__ should have 'mcs' as first argument (bad-mcs-classmethod-argument)

However, this disagrees with [PEP 8](https://www.python.org/dev/peps/pep-0008/#function-and-method-arguments):

> Always use `cls` for the first argument to class methods.

Please consider updating pylint since the Python developers are unlikely to change PEP 8.

**Comment by PCManticore** [comment]
Truth be told, initially I was reticent about this issue, but after some consideration I think it might be best to get rid of the checks that verify the type of metaclasses and whatnot, and always look for `cls` instead.
