### ISSUE TITLE
Disable specific issues using filename pattern

### ISSUE THREAD

**Issue by apnewberry** [PyCQA/pylint#2033]
I often name my functions with an underscore prefix, and then I test them from an accompanying `test_thing.py` file. Pylint warns me about `protected-access` in the test file.

I think I want to prevent pylint from complaining about "protected-access" in `test_*.py` files. Pylint has `ignore-patterns=test_.*.py`, but I want to ignore `test_*.py` only for a particular warning, "protected-access". Currently I'm using `# pylint: disable=protected-access` at the top of each test file, but it'd be nice to avoid redundancy by specifying an ignore pattern for specific issues.

Is there a way to do that? If not, I think this feature might be useful.

**Comment by PCManticore** [comment]
We don't support it, but we probably won't support this feature too soon. There's some work under way though to support multiple configuration files per directory, which means that you can at least control some of the error messages per each directory. See #1988  for more details.
