### ISSUE TITLE
unbalanced tuple unpacking for unknown variable

### ISSUE THREAD

**Issue by Yanpas** [PyCQA/pylint#2061]
### Steps to reproduce
1. insert this `a,b = sys.argv[0:2]`

### Current behavior
[pylint] E0632:Possible unbalanced tuple unpacking with sequence: left side has 2 label(s), right side has 0 value(s)

### Expected behavior
no warnings

### pylint --version output
No config file found, using default configuration
pylint 1.8.4,
astroid 1.6.3
Python 3.5.2 (default, Nov 23 2017, 16:37:01)

**Comment by PCManticore** [comment]
pylint is actually correct here as the script in question might not have been provided some arguments on the command line. I would suggest disabling the error message in place with `# pylint: disable=unbalanced-tuple-unpacking`.

**Comment by Yanpas** [comment]
Maybe it should treated as warning? If argv will have size less than 2 - it will be still an error in my case : the script can't be started with insufficient number of arguments

**Comment by awsumbill** [comment]
Hello, I had this same issue.

Type `# pylint: disable=unbalanced-tuple-unpacking` at the end of the line with the error.

Hope this works :)
