### ISSUE TITLE
Enum: Method 'name' has no 'lower' member (no-member)

### ISSUE THREAD

**Issue by geckon** [PyCQA/pylint#2062]
### Steps to reproduce
```py
#! python3

from enum import Enum

class MyEnum(Enum):
    FOO = 1
    BAR = 2

    def __str__(self):
        return self.name.lower()

```

Run `pylint` on the file above.

### Current behavior
`E: 10,15: Method 'name' has no 'lower' member (no-member)`

### Expected behavior
No error. Enums have `name` propery which contains a string.

### pylint --version output
```
$ pylint --version
No config file found, using default configuration
pylint 1.8.4, 
astroid 1.6.3
Python 3.4.6 (default, Mar 22 2017, 12:26:13) [GCC]
```

**Comment by PCManticore** [comment]
Thanks, I can reproduce this issue.

**Comment by befreeman** [comment]
Will take a look into this tonight!

**Comment by hippo91** [comment]
@dineshtrivedi apparently no one has worked on this yet. Maybe @befreeman ?
Feel free to dig in and make a PR!
