### ISSUE TITLE
Provide Github checks API integration for automated pylint PR review

### ISSUE THREAD

**Issue by gpshead** [PyCQA/pylint#2065]
Github now has an API to accept code review annotations in https://developer.github.com/v3/checks/.
It'd be great for pylint, presumably being run on a CI system, to integrate with this by outputting annotations in the code annotation format Github expects to be easily fed into the API.

**Comment by DanielNoord** [comment]
@Pierre-Sassoulas Aren't we already doing this? I think this issue was forgotten about when the move to GitHub for the CI was made.

**Comment by Pierre-Sassoulas** [comment]
It's not about pylint's own GitHub action, it's about a feature un pylint to be able to be integrated in GitHub checks. It's very interesting by the way I'm glad I've seen this one.

**Comment by jacobtylerwalls** [comment]
Work in progress at #4322

**Comment by Pierre-Sassoulas** [comment]
Should we close this one as duplicate, @jacobtylerwalls ? 4322 is not a PR and all the discussion happened here.

**Comment by jacobtylerwalls** [comment]
Duplicate of #4322
