### ISSUE TITLE
Need Guidance on Custom Pylint Checker for Library Module

### ISSUE THREAD

**Issue by knappador** [PyCQA/pylint#2073]
Hello there,  I'm developing a library for doing double-entry accounting:
https://github.com/knappador/enron-py

I'm building a `ContextManager` for proper transaction treatment.  While I can find transactions that don't end up in a proper state before leaving scope, this occurs at runtime.  I'd like to get a linter in place for static analysis.

Because the warnings will always be tied to a `with` scope, I would like to write for a scope-based interface if it exists.  Is there a preferred class I can implement?

Second, because it's a library, is there a manner of including the lint checker so that pylint can load the customer checker at library import or would I need to guide users to customize their config?  Can I ship the custom lint checker with the project?

Source issue https://github.com/knappador/enron-py/issues/6

**Comment by knappador** [comment]
The situation where a lint warning needs to be generated will be of the following form:

```python
with Accounting:   # context manager will track instance creation from here
    result = talk_to_database().black_box_stuff()
    de = DoubleEntry(result...) 
    if (result.some_condition):
        Accounting.realize(de)  # this logic path consumes the double entry
    else:
        return False
# at this point at runtime, in the else branch, we end up warning that the DoubleEntry was
# created but not consumed, meaning we may have just created an accounting violation.
```

I can start analysis whenever context is opened.   I'll be looking for certain API calls in all branches that indicate that each `DoubleEntry` instance is used once and only once inside a context.  Otherwise I want to warn that a subtle bug surface has been introduced.

I also need to be aware if a `DoubleEntry` is consumed without holding any context.  This would result in no ability to guarantee thread safety or to properly track the `DoubleEntry` fate.

**Comment by PCManticore** [comment]
Sounds good. I don't have specific suggestions but feel free to look at the checkers that we currently have for some inspiration.
