### ISSUE TITLE
Delete pylint-gui references in man pages

### ISSUE THREAD

**Issue by GalaxyLJGD** [PyCQA/pylint#2078]
The pylint-gui references made in [line 29](https://github.com/PyCQA/pylint/blob/5ccbf9eaa54c0c302c9180bdfb745566c16e416d/man/epylint.1#L14) and [14](https://github.com/PyCQA/pylint/blob/5ccbf9eaa54c0c302c9180bdfb745566c16e416d/man/pylint.1#L29) of pylint and epylint man pages, respectively, should be deleted, because it was removed from the program.

**Comment by PCManticore** [comment]
Removed in master
