### ISSUE TITLE
docparams should consider type annotations

### ISSUE THREAD

**Issue by AWhetter** [PyCQA/pylint#2083]
Currently docparams always checks that a type exists for each parameter and for the return type. If type annotations exist on the function signature for a parameter and/or return type then `missing-type-doc` and/or `missing-return-type-doc` should not get raised.

To any new contributors looking to fix this issue; this should only need changes in https://github.com/PyCQA/pylint/blob/master/pylint/extensions/docparams.py. Wherever `missing-type-doc` and `missing-return-type-doc` are raised, we can add a check to make sure that an annotation does not exist as well.

### pylint --version output
master

**Comment by sushobhit27** [comment]
@AWhetter Can I work on this issue, seems 
if func_node.returns:
            return
for annotations check in visit_return will be enough for "missing-return-type-doc". If it looks ok, will try to figure out for other check also.

**Comment by AWhetter** [comment]
Sounds good to me!
