### ISSUE TITLE
Make pylint <dir> work like pylint <dir>/*.py

### ISSUE THREAD

**Issue by pylint-bot** [PyCQA/pylint#21]
Originally reported by: **Andrew Pennebaker (BitBucket: [mcandre](http://bitbucket.org/mcandre), GitHub: @mcandre?)**

----------------------------------------

Most linters offer CLI syntax of linter <dir> meaning lint all relevant files in a directory. Typically, users run linter ., to lint the current directory.

pylint rejects this for directories with no __init__.py, such as collections of standalone, one-off scripts. As a mitigation, we can use pylint *.py, but it would be nice to type pylint ., in keeping with conventional linter syntax.

----------------------------------------
- Bitbucket: https://bitbucket.org/logilab/pylint/issue/21

**Comment by PCManticore** [comment]
Closing in favor of #352 (that is a newer issue, but with more discussion at hand)
