### ISSUE TITLE
wrong behavior cv2(python-opencv) module

### ISSUE THREAD

**Issue by aoxiangwu** [PyCQA/pylint#2105]
### Steps to reproduce
from cv2 import VideoCapture

### Current behavior
E0611:No name 'VideoCapture' in module 'cv2'

### Expected behavior
no error, VideoCapture is a class in cv2

### pylint --version output
C:\Users\w\Downloads\angular>pylint --version
No config file found, using default configuration
pylint 1.9.0,
astroid 1.6.4
Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)]

<img src="https://i.loli.net/2018/05/16/5afbf4b7c2552.png" alt="cv2.png" title="cv2.png" />

**Comment by PCManticore** [comment]
Hi, can you try with `pylint --extension-pkg-whitelist=cv2`? The problem is that cv2 is an extension package and we can't quite understand it properly.
