### ISSUE TITLE
Doc tutorial is out of date

### ISSUE THREAD

**Issue by tojo13** [PyCQA/pylint#2118]
The tutorial at https://pylint.readthedocs.io/en/latest/tutorial.html or https://github.com/PyCQA/pylint/blob/master/doc/tutorial.rst uses the python 2 `print` statement and the pylint report feature (`-r`) is enabled by default.

I would be happy to update the content of this page as I found it useful for learning pylint!

**Comment by PCManticore** [comment]
Thanks, please do! That would be great.
