### ISSUE TITLE
pytest | pylint --version  is failing on master

### ISSUE THREAD

**Issue by sushobhit27** [PyCQA/pylint#2142]
### Steps to reproduce
1. python -m pytest test -x -vv

### Current behavior
=========================================================================================== FAILURES ===========================================================================================
______________________________________________________________________ test_functionality[func_bad_cont_dictcomp_py27.py] ______________________________________________________________________

module_file = 'func_bad_cont_dictcomp_py27.py', messages_file = '/home/sussolan/git_repos/pylint_bugfix_sandbox/pylint/pylint/test/messages/func_bad_cont_dictcomp_py27.txt', dependencies = []

    @pytest.mark.parametrize("module_file,messages_file,dependencies", gen_tests(FILTER_RGX),
                             ids=[o[0] for o in gen_tests(FILTER_RGX)])
    def test_functionality(module_file, messages_file, dependencies,):

        LT = LintTestUpdate() if UPDATE else LintTestUsingModule()

        LT.module = module_file.replace('.py', '')
        LT.output = messages_file
        LT.depends = dependencies or None
        LT.INPUT_DIR = INPUT_DIR
>       LT._test_functionality()

test/test_func.py:144:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
test/test_func.py:65: in _test_functionality
    self._test(tocheck)
test/test_func.py:76: in _test
    self.linter.check(tocheck)
../../../pylint/pylint/lint.py:785: in check
    self._do_check(files_or_modules)
../../../pylint/pylint/lint.py:918: in _do_check
    self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
../../../pylint/pylint/lint.py:998: in check_astroid_module
    walker.walk(ast_node)
../../../pylint/pylint/utils.py:1143: in walk
    self.walk(child)
../../../pylint/pylint/utils.py:1145: in walk
    cb(astroid)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <pylint.checkers.variables.VariablesChecker3k object at 0x6fffd9e92b0>, node = <Assign l.3 at 0x6fff71400b8>

    def _store_type_annotation_names(self, node):
>       type_annotation = node.type_annotation
E       AttributeError: 'Assign' object has no attribute 'type_annotation'

../../../pylint/pylint/checkers/variables.py:1344: AttributeError
------------------------------------------------------------------------------------- Captured stdout call -------------------------------------------------------------------------------------
'Assign' object has no attribute 'type_annotation'
=========================================================================== 1 failed, 49 deselected in 3.54 seconds ============================================================================

### Expected behavior
There should be no error.

### pylint --version output

Traceback (most recent call last):
  File "/home/sussolan/.virtualenvs/python3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 574, in _build_master
    ws.require(__requires__)
  File "/home/sussolan/.virtualenvs/python3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/sussolan/.virtualenvs/python3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 783, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (pylint 2.0.0.dev0 (/home/sussolan/git_repos/pylint), Requirement.parse('pylint==2.0.0'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sussolan/.virtualenvs/python3.6/bin/pylint", line 4, in <module>
    __import__('pkg_resources').require('pylint==2.0.0')
  File "/home/sussolan/.virtualenvs/python3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3086, in <module>
    @_call_aside
  File "/home/sussolan/.virtualenvs/python3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3070, in _call_aside
    f(*args, **kwargs)
  File "/home/sussolan/.virtualenvs/python3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3099, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/sussolan/.virtualenvs/python3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 576, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/home/sussolan/.virtualenvs/python3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 589, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/home/sussolan/.virtualenvs/python3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 778, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pylint==2.0.0' distribution was not found and is required by the application

**Comment by PCManticore** [comment]
You need to install the latest astroid from astroid's master branch in order for the tests to work. Also make sure to use `tox` instead of just `pytest` as it prepares all the dependencies beforehand.

**Comment by sushobhit27** [comment]
@PCManticore now executed using tox by following command, but still getting errors, albeit different ones
$ python -m tox -e py36


py36/lib/python3.6/site-packages/pylint/test/functional/redundant_unittest_asser                                                                                                                t.py s [ 99%]
s                                                                        [100%]

=================================== FAILURES ===================================
______________ test_functionality[func_bad_cont_dictcomp_py27.py] ______________

module_file = 'func_bad_cont_dictcomp_py27.py'
messages_file = '/cygdrive/c/cygwin64/home/sussolan/git_repos/pylint/.tox/py36/l                                                                                                                ib/python3.6/site-packages/pylint/test/messages/func_bad_cont_dictcomp_py27.txt'
dependencies = []

    @pytest.mark.parametrize("module_file,messages_file,dependencies", gen_tests                                                                                                                (FILTER_RGX),
                             ids=[o[0] for o in gen_tests(FILTER_RGX)])
    def test_functionality(module_file, messages_file, dependencies,):

        LT = LintTestUpdate() if UPDATE else LintTestUsingModule()

        LT.module = module_file.replace('.py', '')
        LT.output = messages_file
        LT.depends = dependencies or None
        LT.INPUT_DIR = INPUT_DIR
>       LT._test_functionality()

py36/lib/python3.6/site-packages/pylint/test/test_func.py:144:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
py36/lib/python3.6/site-packages/pylint/test/test_func.py:65: in _test_functiona                                                                                                                lity
    self._test(tocheck)
py36/lib/python3.6/site-packages/pylint/test/test_func.py:84: in _test
    self._check_result(self.linter.reporter.finalize())
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <test_func.LintTestUsingModule object at 0x6ffd0ff54a8>
got = 'C: 35: Wrong continued indentation (add 2 spaces).\n    for x in range(3)                                                                                                                }  # [bad-continuation]\r\n    ^ |\nC: 38: Wrong continued indentation (remove 4                                                                                                                 spaces).\n          for x in range(3)}  # [bad-continuation]\r\n      |   ^\n'

    def _check_result(self, got):
>       assert self._get_expected().strip()+'\n' == got.strip()+'\n'
E       AssertionError: assert 'C: 35: Wrong...      |   ^\n' == 'C: 35: Wrong .                                                                                                                ..      |   ^\n'
E         Skipping 85 identical leading characters in diff, use -v to show
E         - tinuation]
E         + tinuation]
E         ?           +
E               ^ |
E           C: 38: Wrong continued indentation (remove 4 spaces).
E         -           for x in range(3)}  # [bad-continuation]...
E
E         ...Full output truncated (4 lines hidden), use '-vv' to show

py36/lib/python3.6/site-packages/pylint/test/test_func.py:68: AssertionError
____________________ test_functional[cellvar_escaping_loop] ____________________

test_file = <test_functional.FunctionalTestFile object at 0x6ffd6b2a5c0>

    @pytest.mark.parametrize("test_file", TESTS, ids=TESTS_NAMES)
    def test_functional(test_file):
        LintTest = LintModuleOutputUpdate(test_file) if UPDATE else LintModuleTe                                                                                                                st(test_file)
        LintTest.setUp()
>       LintTest._runTest()

py36/lib/python3.6/site-packages/pylint/test/test_functional.py:377:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <test_functional.LintModuleTest object at 0x6ffc9518c88>

    def _runTest(self):
        self._linter.check([self._test_file.module])

        expected_messages, expected_text = self._get_expected()
        received_messages, received_text = self._get_received()

        if expected_messages != received_messages:
            msg = ['Wrong results for file "%s":' % (self._test_file.base)]
            missing, unexpected = multiset_difference(expected_messages,
                                                      received_messages)
            if missing:
                msg.append('\nExpected in testdata:')
                msg.extend(' %3d: %s' % msg for msg in sorted(missing))
            if unexpected:
                msg.append('\nUnexpected in testdata:')
                msg.extend(' %3d: %s' % msg for msg in sorted(unexpected))
>           pytest.fail('\n'.join(msg))
E           Failed: Wrong results for file "cellvar_escaping_loop":
E
E           Expected in testdata:
E             44: undefined-loop-variable

py36/lib/python3.6/site-packages/pylint/test/test_functional.py:321: Failed
___________________ test_functional[undefined_loop_variable] ___________________

test_file = <test_functional.FunctionalTestFile object at 0x6ffd6a8ad30>

    @pytest.mark.parametrize("test_file", TESTS, ids=TESTS_NAMES)
    def test_functional(test_file):
        LintTest = LintModuleOutputUpdate(test_file) if UPDATE else LintModuleTe                                                                                                                st(test_file)
        LintTest.setUp()
>       LintTest._runTest()

py36/lib/python3.6/site-packages/pylint/test/test_functional.py:377:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <test_functional.LintModuleTest object at 0x6ff8db79cf8>

    def _runTest(self):
        self._linter.check([self._test_file.module])

        expected_messages, expected_text = self._get_expected()
        received_messages, received_text = self._get_received()

        if expected_messages != received_messages:
            msg = ['Wrong results for file "%s":' % (self._test_file.base)]
            missing, unexpected = multiset_difference(expected_messages,
                                                      received_messages)
            if missing:
                msg.append('\nExpected in testdata:')
                msg.extend(' %3d: %s' % msg for msg in sorted(missing))
            if unexpected:
                msg.append('\nUnexpected in testdata:')
                msg.extend(' %3d: %s' % msg for msg in sorted(unexpected))
>           pytest.fail('\n'.join(msg))
E           Failed: Wrong results for file "undefined_loop_variable":
E
E           Expected in testdata:
E              6: undefined-loop-variable
E             25: undefined-loop-variable

py36/lib/python3.6/site-packages/pylint/test/test_functional.py:321: Failed
====== 3 failed, 941 passed, 65 skipped, 49 deselected in 1012.88 seconds ======
ERROR: InvocationError for command '/cygdrive/c/cygwin64/home/sussolan/git_repos                                                                                                                /pylint/.tox/py36/bin/python -Wi /cygdrive/c/cygwin64/home/sussolan/git_repos/py                                                                                                                lint/.tox/py36/lib/python3.6/site-packages/coverage run -m pytest /cygdrive/c/cy                                                                                                                gwin64/home/sussolan/git_repos/pylint/.tox/py36/lib/python3.6/site-packages/pyli                                                                                                                nt/test/' (exited with code 1)
___________________________________ summary ____________________________________
ERROR:   py36: commands failed

**Comment by PCManticore** [comment]
Might be related to cygwin somehow? The tests pass on Travis and AppVeyor.

**Comment by sushobhit27** [comment]
@PCManticore cygwin is the best setup right now I have, will try to manage with it somehow. Thanks for the info btw.

**Comment by PCManticore** [comment]
Makes sense. If you notice some failures that are particular to cygwin, feel free to fix it and send a PR with that! Since we don't test on cygwin by default, there might be checks that don't work on that platform right now.
