### ISSUE TITLE
Allow per-file configuration via a comment-line

### ISSUE THREAD

**Issue by exhuma** [PyCQA/pylint#2143]
`vim` has a very powerful feature called [modelines](http://vimdoc.sourceforge.net/htmldoc/options.html#modeline) [[2](http://vim.wikia.com/wiki/Modeline_magic)]. While the full feature-set of something like vim-modelines does not make sense for a linter I think there is one interesting feature: *being able to override any setting for that one file only*.

pylint already allows disabling messages for one file by adding a special comment to the top of the file:

    # pylint: disable=missing-docstring

But the following does not work:

    # pylint: max-line-length=120

It is absolutely arguable that per-project linting settings should go into a `pylintrc` for that project. But on rare occasion you may have a good reason why a setting should be overridded for one specific file only. For example, the file was migrated from another project and don't want to completely reformat it, or a module contains a lot of long-winded statements and you want to relax the 80-column rule without completely disabling it.

There may be other situation where it may make sense to override other settings for just one file. For example when developing a kind of DSL in a module which will have names not conforming to the standard PEP8 notation. If those "invalid" names are localised to only one module, a "modeline-like" feature would allow specifying a new regex for just that one file.

All this combined would allow a more fine-grained control over the linter without completely silencing it.

**Comment by exhuma** [comment]
I've come across another, similar use-case:

The `# pylint ...` comments can not only be used to disable messages in a local block. This could then also be used to change the regex for valid names (which by default contain `i`, `j` & co).

It may sometimes be useful to change that list in a more local scope without adding a new name to the `pylintrc` for the project.

**Comment by PCManticore** [comment]
While this sounds pretty powerful, it feels like a feature that's going to be used mostly by power users. It's also a fairly big change to implement, as we'd need to rework quite a lot of the configuration management.
I'm not opposed to the idea, I just don't find the right incentive to dedicate a couple of weeks to implementing it.

**Comment by PCManticore** [comment]
As mentioned, this probably requires too much effort and complexity added.
