### ISSUE TITLE
Integrate rstlint for our documentation

### ISSUE THREAD

**Issue by PCManticore** [PyCQA/pylint#2150]
https://github.com/twolfson/restructuredtext-lint

**Comment by pheanex** [comment]
Is a `find . -type f -iname '*.rst' -exec rst-lint {} \;` after https://github.com/PyCQA/pylint/blob/master/tox.ini#L74 enough or did you have anything more fancy in mind?

**Comment by PCManticore** [comment]
That works!

**Comment by pheanex** [comment]
Ok cool, do we also want to fail the build if rstlint complains?
