### ISSUE TITLE
Use python-docs-theme 

### ISSUE THREAD

**Issue by Mariatta** [PyCQA/pylint#2167]
[python-docs-theme](https://github.com/python/python-docs-theme/) is the sphinx theme used by [docs.python.org](https://docs.python.org), [devguide.python.org](https://devguide.python.org), and [packaging.python.org](https://packaging.python.org).
When using this theme, you'll be borrowing an element of the trust and credibility established by Python core developers. 
I think it is appropriate to be used by pylint.
If interested, I can try create the PR for this.
Thanks.

**Comment by PCManticore** [comment]
Sounds good, please do! Would be great to have an overhaul of the docs.
