### ISSUE TITLE
Bug / new check: useless-return

### ISSUE THREAD

**Issue by nickdrozd** [PyCQA/pylint#2176]
Here is a function from `pylint/utils.py`:

```
    def _check_id_and_symbol_consistency(self, msgid, symbol):
        try:
            alternative = self._alternative_names[msgid]
        except KeyError:
            alternative = False
        try:
            if not alternative:
                alternative = self._alternative_names[symbol]
        except KeyError:
            # There is no alternative names concerning this msgid/symbol.
            # So nothing to check
            return None
        old_symbolic_name = None
        old_symbolic_id = None
        for alternate_msgid, alternate_symbol in alternative.old_names:
            if alternate_msgid == msgid or alternate_symbol == symbol:
                old_symbolic_id = alternate_msgid
                old_symbolic_name = alternate_symbol
        if symbol not in (alternative.symbol, old_symbolic_name):
            if msgid == old_symbolic_id:
                self._raise_duplicate_symbol(msgid, symbol, old_symbolic_name)
            else:
                self._raise_duplicate_symbol(msgid, symbol, alternative.symbol)
        return None
```

Should this function trigger `useless-return`? There are two `return`s, and they both return `None`, which does seem useless. Deleting just the last line triggers `inconsistent-return-statements`. Deleting the last line as well as the `None` from the early `return` doesn't trigger any warning. That seems like the best form of this code, so maybe there should be a check to see if all `return`s return `None`. This could be a new check, or it could be incorporated into `useless-return`.

I came across this from messing around with `nodes_of_class` in Astroid. I changed something pertaining to `Return` nodes and this started showing up: `pylint/utils.py:821:4: R1711: Useless return at end of function or method (useless-return)`. It doesn't seem like an error.

**Comment by PCManticore** [comment]
`useless-return` is emitted when you have only one return in your function, something along the lines of ```
def first():
   ...
  return None

def second():
    ...
     return
```

In case you have multiple returns, `inconsistent-return-statements` kicks in to verify that they all return a type or none of them do so. They're slightly different checks with different purposes.
