### ISSUE TITLE
False positives for C0414

### ISSUE THREAD

**Issue by zenogantner** [PyCQA/pylint#2183]
`import os.path as path`
is not a useless import alias: You can now refer to `os.path` as `path`.

It should not be caught as C0414.

This issue was introduced with this commit:
https://github.com/PyCQA/pylint/commit/b0f6184e03182736f8423441dfb87985da28e209

**Comment by PCManticore** [comment]
The warning is emitted here because you can do `from os import path`, there's no need to have `import os.path as path`.

**Comment by zenogantner** [comment]
Got it! Thank you, and sorry for the noise.

**Comment by PCManticore** [comment]
No worries!
