### ISSUE TITLE
Adding new Checkers Discussion/Enhancement

### ISSUE THREAD

**Issue by pheanex** [PyCQA/pylint#2194]
What do you think about adding checkers for some/all of the following anti-patterns:
* [Not using dict comprehension](https://docs.quantifiedcode.com/python-anti-patterns/readability/not_using_a_dict_comprehension.html#)
* [Assigning lambda to a variable](https://docs.quantifiedcode.com/python-anti-patterns/correctness/assigning_a_lambda_to_a_variable.html)
* [Putting type information in a variable name](https://docs.quantifiedcode.com/python-anti-patterns/readability/putting_type_information_in_a_variable_name.html#)

If we decide to add those, I would offer to write the checkers.

**Comment by PCManticore** [comment]
Not using dict comprehension sounds like an useful refactoring check, but I found the other ones too nitpicky. I always disable the assigning lambda to variable check whenever I'm working on a project that uses pyflakes/flake8, while the one with the variable name sounds odd, as I saw exactly no one doing that.

**Comment by pheanex** [comment]
:+1: Thank you for the feedback.
I am going to create the dict comprehension check then.
