### ISSUE TITLE
Annotation checks for useless-super-delegation crash in many cases

### ISSUE THREAD

**Issue by cschramm** [PyCQA/pylint#2210]
From https://github.com/PyCQA/pylint/pull/2098#issuecomment-396972097

To reproduce run pylint with  #2098 in place on this sample code:

```
from typing import List


class Test:
    def __init__(self, _arg: List[int]) -> None:
        super().__init__()
```

pylint crashes as the annotation is a `Subscript` and does not have a `name` attribute.

**Comment by PCManticore** [comment]
Thanks for the heads up @cschramm
