### ISSUE TITLE
Gitlab mirror is not updating

### ISSUE THREAD

**Issue by pradyunsg** [PyCQA/pylint#2216]
An FYI issue.

https://gitlab.com/PyCQA/pylint currently says:

> The repository failed to update 7 months ago.
> Repository mirroring has been paused due to too many failed attempts, and can be resumed by a project master.
> Last successful update 1 year ago.

**Comment by PCManticore** [comment]
This is probably something for @sigmavirus24  as he probably enabled the gitlab mirroring. To be honest I know nothing about that, so I'm closing this issue. Maybe Ian can help.
