### ISSUE TITLE
NotImplemented incorrectly reported as undefined

### ISSUE THREAD

**Issue by chrisspen** [PyCQA/pylint#2232]
I have a method like:

    def __cmp__(self, other):
        if not isinstance(other, type(self)):
            return NotImplmented
        return cmp(self.name, other.name)

And `pylint>=1.9.2` reports the error:

    E:139,19: Undefined variable 'NotImplmented' (undefined-variable)

This is a built-in constant as explained [here](https://docs.python.org/3/library/constants.html#NotImplemented). Built-ins are implicitly defined, and should not be interpreted as undefined by pylint.

**Comment by PCManticore** [comment]
pylint is right, that's a typo, it is `NotImplemented`.

**Comment by chrisspen** [comment]
Good catch. Sorry for the noise.
