### ISSUE TITLE
Authoritative overview-page for all messages

### ISSUE THREAD

**Issue by pheanex** [PyCQA/pylint#2235]
Whenever I use pylint and encounter a message/code I have not seen before, I like to understand it's background/reasoning.
Therefore I study its short description and if that is not enough, I look it up on a search engine of my choice and mostly find the following:
* Discussions on stackoverflow about this message (if it makes sense at all, why its good/bad, personal opinions)
* [Pylints feature page](http://pylint.pycqa.org/en/latest/technical_reference/features.html)
* Github issues about this message (here)
* Blogposts about similar or this issue
* Description for some messages on http://pylint-messages.wikidot.com/all-messages

Scanning through all the above sources is quite some work and in most cases does not give me what I want exactly and not in a convenient way.
This is because:
* Stackoverflow is too opinion-based and does not cover all messages
* The Github issue on pylint for this message contains too much noise (i.e. discussion on technical implementation of this message)
* Blogposts don't focus on exactly this message and tend to babble too much and is also very different on different messages, because its written by different people at different times (outdated!)
* pylint-messages.wikidot.com is actually quite nice in terms of the description and structure, but lacks some/most of the messages, is sometimes also just the short-description from our source here and is (afaik) not directly managed by this community, which does not make it authoritive. In addition to that it's layout feels outdated.

What I therefore suggest is to add one authoritive, official PyCQA/pylint [github-page](https://pages.github.com/) or a rst/markdown document that has elaborate descriptions/background for each message and is nicely formatted and up-to-date. Maybe even integrated with "msgs".
Something in the direction of [quantifiedcode](https://docs.quantifiedcode.com/python-anti-patterns/readability/comparison_to_true.html)

This would especially help Python beginners and people who want to understand these rules/suggestions more thoroughly, instead of just blindly following/accepting them.

If there is a consensus that something like this would be beneficial, I'd offer to start the draft.

If you know of anything that already exists and covers this, please tell.

**Comment by PCManticore** [comment]
We already had this idea (https://github.com/PyCQA/pylint/issues/1056) but we just didn't have time to tackle it. As of now, the only authoritative source from the list you gave is the pylint documentation. It would be definitely great to have a more fine grained explanation for each message in our documentation, that lives in its own part of the documentation rather than being conflated in the automatic generated features page.

**Comment by sushobhit27** [comment]
I was also thinking along the same lines as in many task issue created by @PCManticore, I found that other linters like pytype, ESLint have good and concise documentation, while pylint's is mostly scattered.

One more thing I would like to have, which will be useful only for contributors:
When I start working on a new checker, I know what should be message catergory i.e Refactoring, error or warning etc, but I don't know exact code, so I just copy previous message code for new check and increment the last digit.
So suppose if there was an existing warning code W1712, I will create the new warning check with message code W1713.
However many times, this new msg code is already being used somewhere else. I keep on incrementing message code till it does not stop giving error that given message code can't be used for two different messages.

How about having a next available message code in each category to tackle above issue. I know this is not something of high value, but a small nice to have thing.

**Comment by PCManticore** [comment]
@sushobhit27 `pytype` definitely doesn't seem to have a comprehensive documentation. ;-) ESLint though is gorgeous.

Regarding the error codes problem you mentioned, the way I usually do is to find the next error message id in the class I need to put a check, increment by one, then do a `git grep <msg id>` to see if something else already uses. This is pretty much a super fast process as majority of files have the checks in order. I don't think we'd need to dedicate a page just for the next message code.

**Comment by pheanex** [comment]
Okay, I finally found some time to start working on this.

I was thinking of using Github Pages with markdown and a /docs directory for a simple and easy start.
That way, we can easily integrate this here in this repository and have the authoritive source close.
Structure-wise I would start with one landing(index) page similar as https://eslint.org/docs/rules/ and have one document for each rule.

For a draft on a rule see https://pheanex.github.io/pylint/#R1705

I also added a "Testcases"-link in the resources-section, so users can easily see other testcases for this rule, to either learn from them, or suggest new ones for even better coverage.
The problem here is that the filenames for functional-test-cases is not standardised
=> If you also think this is a feature worth having, we have to think about renaming the testcases. Otherwise tracking different filenames for each single rule would be too much work.

In addition to that I also added a link "Issue Tracker", to make it is easy for users to see open issues or report bugs/features.

=> What do you think?

**Comment by PCManticore** [comment]
This looks simply gorgeous! Thanks a lot @pheanex !

I have some questions though. Why wouldn't we use `pylint.pycqa.com` instead of using Github Pages + Markdown? This would mean maintaining two sets of documentation in two separate frameworks, one in Sphinx and one in Markdown.

Regarding the test cases filenames, we could probably change them to be named after the check they are testing. Unfortunately some of them are version specific, so we'd still have a couple of them that have say `_py36` or a different identifier in the name, but we can probably rename those as well, as long as they have a corresponding `rc` file.

**Comment by pheanex** [comment]
I guess you mean [pylint.pycqa.org](http://pylint.pycqa.org)?
=> I'll create it in Sphinx then.

Postfixing the testcases with a version sounds fine to me. I'll probably add links to all versions then.
