### ISSUE TITLE
RuntimeError when running pylint with python 3.7.0 

### ISSUE THREAD

**Issue by jreese** [PyCQA/pylint#2247]
Attempting to lint my project with Python 3.7.0 results in pylint throwing a RuntimeError.  Linting with 3.6.5 works correctly as expected.

### Steps to reproduce
1.  git clone https://github.com/jreese/aioitertools
2.  pyenv local 3.7.0
3.  python3 -m pip install -U pylint
4.  pylint --version && pylint --rcfile .pylint aioitertools setup.py

### Current behavior

RuntimeError: https://gist.github.com/jreese/34f77ca53bebc9222514784cbdc9bb05

### Expected behavior

Normal lint run: https://gist.github.com/jreese/56c3eeabaabb155d05bc9fb9cdac194c

### pylint --version output

No config file found, using default configuration
pylint 1.9.2,
astroid 1.6.5
Python 3.7.0 (default, Jul  4 2018, 01:03:13)
[GCC 8.1.1 20180531]

**Comment by brycepg** [comment]
Python 3.7 is supported on the preview release: `pip install pylint astroid --pre -U`

**Comment by jreese** [comment]
I updated to the prerelease build, and now I get a AttributeError related to type annotation.  I updated the description, if you could reopen the issue.

**Comment by jreese** [comment]
Scratch that, didn't catch that astroid wasn't updated to the prerelease version.  Sorry for the noise.

**Comment by brycepg** [comment]
My bad I didn't notice that you were using pylint prerelease (skimmed too much). Good to know that astroid needs to be explicity included in the prerelease upgrade.
