### ISSUE TITLE
Attribute error in 2.0.0.dev1 with python3 and flask

### ISSUE THREAD

**Issue by JustgeekDE** [PyCQA/pylint#2256]
### Steps to reproduce
1. clone https://github.com/JustgeekDE/pylint-exception-example
2. create a python3 virtualenv
3. install the requirement-dev.txt
4. run ```pylint src```

### Current behavior
Results in an error ```AttributeError: 'Attribute' object has no attribute 'infered'```

### Expected behavior
Some error message, rather than an unexpected program termination

### pylint --version output
```a
pylint 2.0.0.dev1
astroid 2.0.0.dev3
Python 3.7.0 (default, Jun 29 2018, 20:13:13)
[Clang 9.1.0 (clang-902.0.39.2)]
```

### Further info:

Using the current pylint version on the app.py file will result in a StopIteration exception (see requirements.txt for the specific versions). Using the current dev version of pylint fixes this problem, but instead results in an AttributeError.

**Comment by PCManticore** [comment]
Thanks for the issue. This was already fixed but the code wasn't released. I just did a new dev release so make sure to get them with `pip install pylint astroid -U --pre`.

**Comment by JustgeekDE** [comment]
Yepp, it's working with the new version.

That was fast, thank you!
