### ISSUE TITLE
Exponential performance drop with conditional string concatenations

### ISSUE THREAD

**Issue by setrofim** [PyCQA/pylint#2260]
### Steps to reproduce
The issue can be reproduced with the following code in a module:

```
# test.py

def func():
    var1 = ''
    if True:
        var1 += ''
    if True:
        var1 += ''
    if True:
        var1 += ''
    if True:
        var1 += ''
    # .
    # .
    # .
    var2 = var1.capitalize()

```

### Current behavior

Running` pylint test.py` with the above results in exponentially worse performance as the number of `if` clauses increases. On my system, I get the following timings:

```
num_ifs   	time
10		 0.77s
12		 1.63s
14		 5.28s
16		19.98s
18		1m21.18s
20		5m20.15s
```
![pylint-runtime](https://user-images.githubusercontent.com/904685/42384259-7308b4a6-8131-11e8-8573-4fca2c099695.png)

While the example above is contrived, the conditional concatenations need not reside in one function. In the code line where this originally manifested, it was as a result of composition and nesting of calls to a couple of functions, each only doing a few conditional concatenations.

### Expected behavior

Given that each `if` statement forms a branch in a binary tree of code flow possibilities, I would expect no worse than `O(nlog(n))` behavior in the number of conditional string concatenations.

### pylint --version output

```
$pylint --version                      
No config file found, using default configuration                              
pylint 1.9.2,                          
astroid 1.6.5                          
Python 3.6.3 (default, Oct  3 2017, 21:45:48)                                  
[GCC 7.2.0]
```
Going back in `pylint` versions, this was first observed with `v1.7.0`; prior to that, run time does not appear to be affected by the number of `if` clauses.

**Comment by brycepg** [comment]
Fixed on `astroid` master. There is now a cap on the number of possible results from inference
