### ISSUE TITLE
Add a way to ignore by full path, not basename

### ISSUE THREAD

**Issue by whatisaphone** [PyCQA/pylint#2279]
Background info:

I have adopted a rickety old Python codebase and I'm in the process of cleaning it up. I'm using a number of code quality tools including pylint, flake8, and mypy. My process for each checker has been to set up sane default rules, and an ignore list explicitly ignoring all files in the project. Then one by one I clean a file and remove the exclusion.

Unfortunately that won't work for pylint because according to the latest [docs](https://pylint.readthedocs.io/en/latest/technical_reference/features.html) both `ignore` and `ignore-patterns` only look at base names, not full paths. My exclude list for flake8 looks something like this:

```
exclude =
    auth/models.py
    auth/views.py
    dashboard/models.py
    dashboard/views.py
```

I don't see any way in Pylint to ignore only e.g. auth/views.py, while enforcing rules in dashboard/views.py. Pylint is the only tool I couldn't manage to configure in a way that supports cleaning things up progressively.

I would like to use Pylint on this project. Is there a chance the options could be expanded to support this use case?

**Comment by soullivaneuh** [comment]
The best and simplest way is to provide a `--ignore-path` option and respect the `.gitignore` system which is the most popular.

Example:

```
python --ignore-path .gitignore
```

We can also make `.gitignore` or vcs ignore files usage to be the default. Indeed, ignored files do not need to be linted.

This technique is used by many tools. You can take a look with `eslint` or `stylelint` for example.

You may want to use a dedicated ignore parser for that. I found one: https://github.com/mherrmann/gitignore_parser

**Comment by Pierre-Sassoulas** [comment]
@matusvalo do you think we can close this one ?

**Comment by matusvalo** [comment]
I think we can close it. `--ignore-paths` can be used:
```
--ignore-paths=^auth/models.py$,^auth/views.py$,^dashboard/models.py$
```

It is not 100% due #5398 but should work.

**Comment by soullivaneuh** [comment]
@matusvalo @Pierre-Sassoulas the `--ignore-paths` option does not have the same behavior.

What about the `.gitignore` style solution?

**Comment by Pierre-Sassoulas** [comment]
@soullivaneuh could you open a new enhancement issue for taking the ``.gitignore`` into account ?

**Comment by soullivaneuh** [comment]
@Pierre-Sassoulas sure! Please consider https://github.com/PyCQA/pylint/issues/7371.

Thanks!
