### ISSUE TITLE
Pylint depends on Graphviz & crashes if missing / Improve report-graph usage

### ISSUE THREAD

**Issue by pylint-bot** [PyCQA/pylint#228]
Originally reported by: **Emile Anclin (BitBucket: [anclin](http://bitbucket.org/anclin), GitHub: @anclin?)**

---

Pylint's **report graphs** depends on _Graphviz_ since it uses _logilab.common.graph.DotBackend_ which just checks the extension of the output file.

But it took me a long road to figure out how to even to trigger this problem. (It is deactivated either by "-E" or "-rn", which is not totally obvious from the documention; and I used these options because I was only interested in the dependency graph -- which makes sense to me). 
I found someone on [stackoverflow](http://stackoverflow.com/questions/12055037/pylint-appears-not-to-generate-an-import-graph) complaining about the same issue; so
I used his .pylintrc file and triggered another bug:

```
#!bash

IOError: [Errno 2] No such file or directory: '/home/<my_username>/~/~/gr.dot'
```

ihmo it proves that it is seldom used, and I would move it to  **Pyreverse** ;) 
(I was preparing to pull-request a small patch for #168, but then I remembered Pylint's graph generation...)

---
- Bitbucket: https://bitbucket.org/logilab/pylint/issue/228

**Comment by Pierre-Sassoulas** [comment]
This crash does not happen anymore in the latest version.
