### ISSUE TITLE
Msg template path issue with multiple /src folders in path

### ISSUE THREAD

**Issue by gjsduarte** [PyCQA/pylint#2280]
**Note:** This bug is not reproducible in version 2.0!!

### Steps to reproduce
1. Have your source code under /src
2. Have a folder with source code under a subfolder called /src, such as /src/something/src/code/xxx.py
3. Run pylint with the --msg-template={path}

### Current behavior
Pylint outputs:
somethingcode/xxx.py

### Expected behavior
Pylint outputs:
something/src/code/xxx.py

### pylint --version output
pylint 1.8.2,
astroid 1.6.1
Python 3.6.3 (default, Nov 21 2017, 14:55:20)

**Comment by PCManticore** [comment]
Should be fixed by https://github.com/PyCQA/pylint/commit/0d913675ec682401b2814bb2a8ae06a66f22ebbd once it gets released (that's in the 1.9 branch)
