### ISSUE TITLE
New checker for accessing last element of list/tuple

### ISSUE THREAD

**Issue by sushobhit27** [PyCQA/pylint#2286]
### Steps to reproduce
1. $ cat sample1.py
seq = [1, 2, 3, 4, 5, 6]
last_elem = seq[len(seq) - 1]

2. $ pylint sample1.py --disable=missing-docstring,invalid-name

### Current behavior
---------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: -5.00/10, +15.00)

### Expected behavior
there can be refactoring message at line 2 to suggest to rewrite it as:
last_elem = seq[-1]
as last element of iterable can always be accessed by [-1]

### pylint --version output
pylint 2.0.0.dev1
astroid 2.0.0.dev3
Python 3.6.4 (default, Jan  7 2018, 15:53:53)
[GCC 6.4.0]

**Comment by PCManticore** [comment]
I'm pretty sure this is well known even across beginners. :) I don't think it's worth having this check in `pylint`.

**Comment by sushobhit27** [comment]
@PCManticore May be not for guys coming from C++ background as we have habit of accessing last element of seq like seq[seq.size() - 1]
Infact I raised this issue as one of my teammate few days back asked exactly the same thing "Is it always safe to do seq[-1] for accessing last element?"
anyways I might be bugging you with these kind of issues in future also :smiley:
