### ISSUE TITLE
2.0.0 accidentally removed python2 support

### ISSUE THREAD

**Issue by vilagithub** [PyCQA/pylint#2294]
https://pypi.org/project/pylint/2.0.0.dev2/#files has a wheel for both py2 and py3
https://pypi.org/project/pylint/2.0.0/#files only has a py3 one

**Comment by PCManticore** [comment]
This is intended as pylint 2.0 drops Python 2 support. Our mistake was early on with the dev releases to not remove the `universal` flag from `setup.cfg`.

**Comment by vilagithub** [comment]
Wow, where did you announce that ?

**Comment by vilagithub** [comment]
I would have expected as least a warning for a transition period and surely not a break from a -dev release to a final one :-/

**Comment by PCManticore** [comment]
Everywhere. In the documentation, in the issue tracker. Yes, that was our mistake with the dev release, but that's it now. If you want python 2 support, stick with pylint 1.9+. We're doing regular bug fix releases on that branch.
