### ISSUE TITLE
bad-continuation doesn't consider multiple with-statements

### ISSUE THREAD

**Issue by The-Compiler** [PyCQA/pylint#2301]
With this block:

```python
            with log.ignore_py_warnings(
                category=DeprecationWarning,  # error
                message=r'({})'.format('|'.join(messages))  # error
            ), log.ignore_py_warnings(
                category=PendingDeprecationWarning,
                module='imp'
            ), log.ignore_py_warnings(
                category=ImportWarning,
                message=r'Not importing directory .*: missing __init__'
            ):
                importlib.import_module(name)
```

pylint wants me to further indent the first lines (marked with `# error`), presumably to tell them apart from the body of the `with:`.

However, it does not want me to further indent the other two blocks, which seems inconsistent.

This appeared with pylint/astroid 2.0, it seems in earlier versions it didn't want to further indent things at all.

**Comment by PCManticore** [comment]
Confirming that I can reproduce this as well. Also given the adoption of `black` as a standard formatting tool in Python, I wonder if it makes sense to still suggest a further indentation for telling apart the body of the `with` from its arguments, given that `black` does not do that.

**Comment by fxfitz** [comment]
I'm seeing this as well with 2.4.4 (but not 1.9.5).

**Comment by Pierre-Sassoulas** [comment]
`bad-continuation` has been removed in #3571, black or another formatter can help you with this better than Pylint
