### ISSUE TITLE
W1632 reported for python3 code

### ISSUE THREAD

**Issue by eccles** [PyCQA/pylint#2303]
Could not find this in current list of issues

### Steps to reproduce
1. Use the input() builtin in source code.py
2. python3 -m pylint --rcfile=pylintrc code.py
3. W1632: input built-in referenced (input-builtin)

### Current behavior

W1632: input built-in referenced (input-builtin)

### Expected behavior

No warning issued as this is python3

### pylint --version output

pylint 2.0.0
astroid 2.0.0.dev4
Python 3.6.5 (default, Apr  1 2018, 05:46:30) 
[GCC 7.3.0]

**Comment by PCManticore** [comment]
While you're running on Python 3, most likely you have enabled the Python 3 porting mode. This is the same as issue #2115.
