### ISSUE TITLE
Consider demoting 'try-except-raise' to warning or refactor level

### ISSUE THREAD

**Issue by pR0Ps** [PyCQA/pylint#2323]
From the way the rest of the messages are organized, it seems like the error level is reserved for issues that will cause a problem when executed (see `no-member`, `too-many-function-args`, etc). While the code that `try-except-raise` catches is should definitely be refactored, it doesn't actually cause any issues execution-wise (that I know of).

Because of this, I'd like to propose that the `try-except-raise` message get demoted to the warning or refactor level. I realize that there has already been a release with `try-except-raise` being considered an error, but I figured I'd propose it anyway since I couldn't find any documentation regarding what is considered a breaking change.

Is this something that's possible? If so, I'd be more than happy to submit a PR to implement it.

Related:
 - Initial `try-except-raise` implementation: #1939 
 - Issues regarding catching subclasses: #2284, #2302
 - Proposed fix for the previous issues: #2308

**Comment by PCManticore** [comment]
Thanks, this make sense. I omitted the fact that it was an error during review, but it should be a warning.

**Comment by PCManticore** [comment]
Regarding your question, it's definitely possible and feel free to submit a PR!
