### ISSUE TITLE
Skipping unused-import for type comments doesn't work with 3.7

### ISSUE THREAD

**Issue by scop** [PyCQA/pylint#2345]
Skipping unused-import for typing imports used in type comments doesn't seem to work with 3.7. It does work with 3.6, they are suppressed properly there. I guess it's an astroid bug (node.type_annotation always is empty based on a very quick test), but filing here for someone who knows what they're doing to check.

### Steps to reproduce

```
$ cat bug.py 
from typing import Any, List
a = 1 # type: List[Any]
$ python -m pylint bug.py | grep unused-import
```
### Current behavior

```
bug.py:1:0: W0611: Unused Any imported from typing (unused-import)
bug.py:1:0: W0611: Unused List imported from typing (unused-import)
```

### Expected behavior

(no output)

### pylint --version output

```
$ python -m pylint --version  # current git master
__main__.py 2.0.0
astroid 2.0.1
Python 3.7.0 (default, Jul 20 2018, 16:55:26) 
[GCC 7.2.0]

```

**Comment by PCManticore** [comment]
Right, the problem is that we use the `typed_ast` library to get support for type comments, which itself does not have support yet for Python 3.7. We only install for Python <3.7, which is why you are seeing these errors.
