### ISSUE TITLE
Confirm API for the PluginRegistry

### ISSUE THREAD

**Issue by AWhetter** [PyCQA/pylint#2360]
#1886 introduced the PluginRegistry so that a linter instance does not need to be passed to plugin "register" functions. Does this do everything that plugins need? Is there anything that we want to add/remove.

Currently the class has the following attributes and methods:
* add_message
* clear_by_id_managed_msgs
* config
* disable
* disable_noerror_messages
* disable_report
* disable_reporters
* enable
* enable_report
* error_mode
* file_state
* for_all_checkers
* get_by_id_managed_msgs
* get_message_state_scope
* is_message_enabled
* msg_status
* msgs_store
* print_full_documentation
* python3_porting_mode
* register_checker
* register_options
* register_report
* register_reporter
* report_is_enabled
* reporter
* reports
* stats

**Comment by PCManticore** [comment]
I think we shouldn't necessarily need everything from this list, from a quick look some of these methods look like they might be in fact private methods. Here's just some that don't look like it should be part of the API:

- get_by_id_managed_msgs
- for_all_checkers
- clear_by_id_managed_msgs
- get_message_state_scope
- print_full_documentation

You can exercise your judgement if something needs to be public or not in this case. Plugins shouldn't need access to all the linter's internals.

**Comment by DanielNoord** [comment]
This is no longer relevant as the branch this is referring to is likely not going to be merged anyway.
