### ISSUE TITLE
ArcanistPyLintLinter is not compatible with the installed version of pylint. Minimum version: 1.0.0; installed version: . 

### ISSUE THREAD

**Issue by sheoran** [PyCQA/pylint#2367]
Tool https://github.com/phacility/arcanist/blob/master/src/lint/linter/ArcanistPyLintLinter.php
is broken with 2.0.1 but works with 1.9.2 only thing I can notice is off is ',' at the end or 1.9.2, which doesn't exist for 2.0.1

### Exception
EXCEPTION: (ArcanistMissingLinterException) ArcanistPyLintLinter is not compatible with the installed version of pylint. Minimum version: 1.0.0; installed version: . at [<arcanist>/src/lint/linter/ArcanistPyLintLinter.php:104]

### Current behavior
pylint --version
pylint 2.0.1
astroid 2.0.1
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609]

### Expected behavior
pylint --version
pylint 1.9.2, 
astroid 1.6.5
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609]

### pylint --version output
pylint 2.0.1
astroid 2.0.1
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609]

**Comment by mthuurne** [comment]
The comma is present in the regex used to extract the version: [`$regex = '/^pylint (?P<version>\d+\.\d+\.\d+),/';`](https://github.com/phacility/arcanist/blob/master/src/lint/linter/ArcanistPyLintLinter.php#L41). Changing that `,` to `,?` should make it work with old and new PyLint releases, I think.

**Comment by PCManticore** [comment]
@sheoran This seems to be an arcanist issue. As mentioned by @mthuurne adapting the regex should make it work.
