### ISSUE TITLE
Optional feature: return statement at the end of a function

### ISSUE THREAD

**Issue by pylint-bot** [PyCQA/pylint#237]
Originally reported by: **Anonymous**

---

It would be nice to have a checker checking whether all functions end with a return-statement. The trivial statement
'return '
should be allowed, too. This feature should be optional and by default be turned off in the config file, e.g.
'min-returns=0'.

---
- Bitbucket: https://bitbucket.org/logilab/pylint/issue/237

**Comment by PCManticore** [comment]
Closing in favor of https://github.com/PyCQA/pylint/issues/1267
