### ISSUE TITLE
useless-import-alias is too strict

### ISSUE THREAD

**Issue by webartifex** [PyCQA/pylint#2423]
For some common libraries the canonical way to import now causes a pylint warning

### Steps to reproduce
1. pip install rpy2
2. import rpy2.robjects as robjects
3. or, import rpy2.rinterface as rinterface

### Current behavior
pylint issues the warning "C0414: Import alias does not rename original package (useless-import-alias)"

### Expected behavior
This should not be a warning/error

### pylint --version output
pylint 2.1.1
astroid 2.0.4
Python 3.6.5 (default, Apr  1 2018, 05:46:30) 
[GCC 7.3.0]

### Bug introduction
https://github.com/PyCQA/pylint/commit/b0f6184e03182736f8423441dfb87985da28e209

### Potential duplicate
https://github.com/PyCQA/pylint/issues/2309

### Related issue
https://github.com/PyCQA/pylint/issues/2183
IMHO `from os import path` should be allowed to remain `import os.path as path` as the Google style guide does not allow `from ... import ...`

**Comment by sushobhit27** [comment]
@webartifex this is fixed in 2.2 and will be available soon.
https://github.com/PyCQA/pylint/pull/2402
