### ISSUE TITLE
Pylint PyCharm plugin

### ISSUE THREAD

**Issue by leinardi** [PyCQA/pylint#2433]
Hi, I just want to let you guys know that I just published a Pylint plugin for PyCharm:

![image](https://user-images.githubusercontent.com/273338/44430062-de1fb780-a599-11e8-86ac-1c00304c071a.png)

Compared to the External tools solution, it doesn't require any configuration, it allows to navigate the violations very easily and it is easier to access since it has its own Terminal tab.

https://github.com/leinardi/pylint-PyCharm-plugin

**Comment by PCManticore** [comment]
Hey @leinardi This is awesome! Would you mind sending a PR for adding it here? https://github.com/PyCQA/pylint/blob/1e03ef9b6f692ac1c0004b76e430c0c96351d554/doc/user_guide/ide-integration.rst#L5

**Comment by leinardi** [comment]
@PCManticore I don't mind at all. Done :+1:
