### ISSUE TITLE
If the output format is Json and there are no messages, there is no output at all

### ISSUE THREAD

**Issue by leinardi** [PyCQA/pylint#2446]
### Steps to reproduce
1. run Pylint on a file/package that has no errors using `-f json`

### Current behavior
Pylint produce no output at all.

### Expected behavior
Pylint should output an empty Json, so that the output can still be parsed as Json:
```
[]
```

The current behavior is generating a EOF exception when I try to parse the output of Pylint as Json and there are no messages.
As a workaround I have, before parsing, [check if there is an output](https://github.com/leinardi/pylint-PyCharm-plugin/blob/5d67d446bc84bedbac26e8636dec077abcf4aeaf/src/main/java/com/leinardi/pycharm/pylint/plapi/PylintRunner.java#L102) or not but, imho, it would be better to always provide a Json output so that can be always parsed as Json.

### pylint --version output
```
pylint 2.1.1
astroid 2.0.4
Python 3.6.6 (default, Jul 19 2018, 14:25:17) 
[GCC 8.1.1 20180712 (Red Hat 8.1.1-5)]
```

**Comment by PCManticore** [comment]
Thank you, this definitely makes sense!
