### ISSUE TITLE
False 'bad-python3-import' with `import turtle`

### ISSUE THREAD

**Issue by aivarannamaa** [PyCQA/pylint#2453]
### Steps to reproduce
1. Create test.py with `import turtle` or `from turtle import forward`. Script may include also usage of imported names.
2. Check it with `pylint --enable=bad-python3-import test.py`

### Current behavior
Output includes `W1648: Module moved in Python 3 (bad-python3-import)`

### Expected behavior
Should not emit bad-python3-import as the module is actually present (and has same name both in Python 2 and Python 3).

### pylint --version output
pylint 2.1.1
astroid 2.0.4
Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:04:45) [MSC v.1900 32 bit (Intel)]

**Comment by PCManticore** [comment]
Definitely a bug!
