### ISSUE TITLE
pyreverse:  pyreverse doesn't link sub-classes to an abstract class

### ISSUE THREAD

**Issue by rahul1990gupta** [PyCQA/pylint#2479]
### Steps to reproduce
1. Run `git clone git@github.com:pixelogik/NearPy.git`
2. Run `cd nearpy/storage`
3. Run ` pyreverse -o .png .`
4. Open classes_No_Name..png
### Current behavior
You will see a UML diagram like this.This has three classes `RedisStorage`, `MemoryStorage` and an abstract class `Storage`. See the diagram here. 
https://drive.google.com/file/d/1MQ8igLIhNIfVUM0VyXfrcFYdOwDs6V0f/view?usp=sharing

### Expected behavior
classes `RedisStorage` and `MemoryStorage` should inherit from abstract class `Storage` 

### Pylint version 
pylint (1.1.0)

**Comment by umed48** [comment]
is there any news?

**Comment by PCManticore** [comment]
@ovegug No news, no one got to work on this issue (and not a lot of work was done on pylint recently as  well)

**Comment by rahul1990gupta** [comment]
If I get some time, I can start working on it. Will post updates on the thread. :D

**Comment by levitsky** [comment]
I noticed when you are building from inside the package (`nearpy/storage` in your example) the inheritance is lost. This is reproducible even for empty classes.
If you go up two times and build the diagram for all of `nearpy`, you get the correct inheritance in the output. However, it's not sufficient to get out of `storage` and run `pyreverse -o png storage`, at least in this case.

I am having a similar problem with another package, `pyteomics`, where parts of inheritance relations are not shown for some of the classes.
