### ISSUE TITLE
# pylint: … line comments do not play well with other code analyzers (they have to appear at the end)

### ISSUE THREAD

**Issue by posita** [PyCQA/pylint#2485]
Consider someone who uses Mypy notations, pyflakes, pylint, and bandit. This will confuse pylint:

`…  # type: … # noqa: E501 # pylint: disable=line-too-long # nosec`

Pylint will give you the warning: `pylint: Bad option value 'line-too-long # nosec'  ("bad-option-value")`. Pylint requires the line be written as follows (with the `# pylint` comment at the end):

`…  # type: … # noqa: E501 # nosec # pylint: disable=line-too-long`

See also #199 and #2297.

**Comment by PCManticore** [comment]
Should be fixed now. Please give it a go and let me know if it works for you!

**Comment by PCManticore** [comment]
@DevynCJohnson Thanks but I don't think your PR actually changes anything for your linked issues. As mentioned in https://github.com/PyCQA/pylint/pull/2537#discussion_r224197606, the current `master` should deal with all the linked issues, but your PR improves though a potential bug in `format.py` related to `line-too-long` and other additional linter comments. I also have to complain about the use of `try to fix the issue`, please avoid it as it's quite patronising.
