### ISSUE TITLE
property setter lead to R0902 (too-many-instance-attributes)

### ISSUE THREAD

**Issue by zinnjonas** [PyCQA/pylint#2486]
### Steps to reproduce

    class DummyClass:

        def __init__(self):
            self._one = None
            self._two = None
            self._three = None
            self._four = None
            self._five = None
            self._six = None

        @property
        def one(self):
            return self._one
    
        @one.setter
        def one(self, one):
            self._one = one

        @property
        def two(self):
            return self._one
    
        @two.setter
        def two(self, two):
            self._two = two
    
        @property
        def three(self):
            return self._three
    
        @three.setter
        def three(self, three):
            self._three = three
    
    
      def test():
        dummy = DummyClass()
        dummy.one = "1"
        dummy.two = "2"
        dummy.three = "3"

### Current behavior

    $ pylint -d C0111 test.py
    ************* Module test
    test.py:3:0: R0902: Too many instance attributes (9/7) (too-many-instance-attributes)
    
    ------------------------------------------------------------------
    Your code has been rated at 9.60/10 (previous run: 9.60/10, +0.00)

### Expected behavior
No warnings, because there are just 6 instance attributes in the class. 

The calls in the test function generates the 3 extra counts to the instance attributes.

### pylint --version output

    pylint 2.1.1
    astroid 2.0.4
    Python 3.7.0 (default, Jul 15 2018, 10:44:58) 
    [GCC 8.1.1 20180531]

**Comment by PCManticore** [comment]
@zinnjonas This is expected, but not because you have the property setters, but because you have the additional properties. So you have six private instance attributes followed by three public attributes, which are the new `one` `two` and `three` properties, resulting in 9. The check here is correct, and most likely there's some refactoring to that class that can be done.

**Comment by MaKaNu** [comment]
What kind of refactoring are you mentioning at this specific point? I refactored code from silly globals to a class which holds now the Parameters. This leads to a similar problem here described. Because I use sys.argv to get custom user params I would already use up to 4 class attributes. I could reduce this to maybe 2 but more is not possible because then I would destroy most of my oop-ish things.

**Comment by hippo91** [comment]
@MaKaNu it is hard to say what to do without seeing your code. Maybe the number of attributes of your class is the good one. Don't forget that pylint is a tool. It just provides advice and it is probably not a good idea to follow them blindly.
At the end it is always the developer who decides.

**Comment by MaKaNu** [comment]
@hippo91 I was wondering what could be a good refactoring for the code of the OP. I also was wondering about the advice of just 7 attributes, where it would come from and why actually 7 not 6 or 8. I wanted a better intuition why the number above 7 could lead to an antipattern.

**Comment by hippo91** [comment]
@MaKaNu a possible refactoring of the original OP **may** be to split it into to classes and/or use `dataclass`. However it will strongly depend on the context and the original code. The choice of the limit fixed to 7 parameters is arbitrary. To my knowledge there is no precise/exact limit to determine whether or not it could lead to antipattern or not.

**Comment by ManelBH** [comment]
For some reason property setters only count as an attribute if the property is set within the module. I'm sorry but this seems an attempt at labeling a bug as a feature, the current implementation of the rule isn't consistent and really needs some justification.

If despite this considering setters the same as private attributes is really your intention this is still very questionable. A class implementation and it's public interface are two different things. I'd like to hear the rationale behind having a rule that considers both the same, or how do you argue 4 properties with setters being the same as 8 different attributes. I can't see how any of this would lead to better code, this rather discourages proper encapsulation.

**Comment by hippo91** [comment]
@ManelBH please open a specific issue with a snippet. Thanks in advance.
