### ISSUE TITLE
How to suppress showing source?

### ISSUE THREAD

**Issue by janhn** [PyCQA/pylint#2501]
The 'Pylint output' docs say: "Sometimes the line of code which caused the error is displayed with a caret pointing to the error. This may be generalized in future versions of Pylint."

Is there a way to suppress this feature? I'd like to get just one line per issue in the output.

It seems that the -E command line options does this, but that also ignores my enable/disable settings in the rc file, which is not desired.

If there's no option/configuration setting for this, could it be separated (e.g. show_source=no)?

**Comment by PCManticore** [comment]
@janhn There's currently no support for disabling that. If you need a single line per output, I suggest writing a custom reporter but currently there are no plans to support this feature.

**Comment by janhn** [comment]
> @janhn There's currently no support for disabling that. If you need a single line per output, I suggest writing a custom reporter but currently there are no plans to support this feature.

Well, it's probably simpler to filter the output (which is what I originally expected from -E), but then, calling the output-format 'parseable' is a bit of an overstatement, isn't it?

**Comment by PCManticore** [comment]
@janhn `parseable` might be a misnomer for this reporter, as it is not intended to be `parseable` per se, but just to have a particular structure recognized by editors: https://github.com/PyCQA/pylint/blob/3f2842400795ae1aaffc4ae6c35c4ef26857c239/pylint/reporters/text.py#L161. While I understand your frustration, adding a command line flag for controlling every tidbit of pylint's output is not going to happen, so if you need to not have those caret lines, feel free to use an additional parsing step on top of `pylint`.
