### ISSUE TITLE
E0704 getting applied too liberally

### ISSUE THREAD

**Issue by ahonnecke** [PyCQA/pylint#2506]
### Is your feature request related to a problem? Please describe
I can't ignore E0704 on just one line.

### Describe the solution you'd like
I would like # noqa: E0704 to work, or for pylint to magically determine when a raise is inside an except block inside of a function

### Additional context
I have a method that catches, and then handles an exception

```python
    def fail(self, error):
        raven_client.captureException(data={'message': 'Caught exception in fail!'})
        self.task_log.caught_error = error
        if settings.RAISE_TASK_FAILURES:
            raise  # noqa
        return self._teardown(False)
```

```python
raise  # NOQA: E0704
```

Also does not work.

This throws:
```
server/tasks/task_helper.py:115:12: E0704: The raise statement is not inside an except clause (misplaced-bare-raise)
```

**Comment by PCManticore** [comment]
@ahonnecke This does not work because we don't use `noqa`, we use `# pylint: disable=<message ID or symbol>`.
