### ISSUE TITLE
Suppress W0231 (super-init-not-called) for empty super __init__ method

### ISSUE THREAD

**Issue by TakingItCasual** [PyCQA/pylint#2512]
I have a base class where I define the `__init__` method as the following:

    def __init__(self, cmd_args):
        pass

This is so that all subclasses expect an argument to be given during instantiation (regardless of if they override `__init__`). As there's no need to call `super().__init__(cmd_args)` in the subclasses, I'd like for W0231 to be suppressed in these particular cases.

**Comment by PCManticore** [comment]
I'm not sure what kind of base class you have there, but if the class in question does not inherit from a different class, then this error is not emitted. `pylint` only emits it when it detects that your class was meant to be used as a concrete class but without calling into its parents. I don't think this use case is valid so I'm closing this issue.
