### ISSUE TITLE
pylint too slow on travis-ci, probably wrong CPU detection

### ISSUE THREAD

**Issue by skirpichev** [PyCQA/pylint#2519]
Recently (10 days ago or so) travis-ci jobs with pylint (called as ``pylint diofant``) started timeout (not always, but very often) for the diofant, see build log: https://travis-ci.org/diofant/diofant/jobs/430486447.

I noticed that if I add ``-j1`` option - problem disappear.  I guess, that it might be related with CPU detection code (i.e. it may spawn too much processes, like pytest plugin does in issue https://github.com/pytest-dev/pytest-xdist/issues/9).  I also didn't noticed any random slowdowns while running pylint tests on my own computer.

**Comment by xmo-odoo** [comment]
@skirpichev could pylint have updated beyond 2.0 somehow on travis (either your requirements or whatever cache they have)? 2.0 seems way the hell slower than 1.x (on a relatively large codebase I have a slowdown of ~5x from 1.7 to 2.x).

**Comment by skirpichev** [comment]
@xmo-odoo, as you can see from the build log - pylint 2.1.1 was installed.  It was working some time ago.  Maybe some it's dependence was updated more recently.

**Comment by PCManticore** [comment]
@xmo-odoo This is a known problem with the 2.X releases, check https://github.com/PyCQA/pylint/issues/2198 which is a similar issues that occurs with pandas. 

Regarding the original issue, I'm not sure what's happening, is it possible to run `import multiprocessing; print(multiprocessing.cpu_count())` and see if it matches the number you are expecting?

**Comment by skirpichev** [comment]
> I'm not sure what's happening, is it possible to run ... and see

Sure, you can run that on travis-ci and see.  What happens and why it's wrong described in the referenced issue https://github.com/pytest-dev/pytest-xdist/issues/9.

**Comment by skirpichev** [comment]
@PCManticore, beware, your fix will not work on PyPy3 (and on any py2 too, btw), see https://github.com/pytest-dev/pytest-xdist/issues/316
