### ISSUE TITLE
singleton-comparison error wrongly suggests using "is True" or "is False"

### ISSUE THREAD

**Issue by gpshead** [PyCQA/pylint#2527]
`_check_singleton_comparison` contains error messages that give bad advice to the user.
  https://github.com/PyCQA/pylint/blob/master/pylint/checkers/base.py#L2051

"just 'expr' or 'expr is True'" etc..

The `is` and `is not` operators should _never_ be used to compare to `True` or `False`.  `is` and `is not` are only useful to compare to `None`.

The error messages involving True and False in that checker should be simplified to `"just 'expr'"` and `"just 'not expr'"`.

It is exceedingly rare that anyone would ever want to perform an identity check against the interpreter's True or False builtin values in normal code.  Use boolyness, never depend on bool type singletons.

**Comment by PCManticore** [comment]
Thanks for the report! Should be fixed now.

**Comment by xenic** [comment]
Why do you say this:
> The `is` and `is not` operators should _never_ be used to compare to `True` or `False`. `is` and `is not` are only useful to compare to `None`.

Given https://www.python.org/dev/peps/pep-0285/ which declares True and False to be singletons like None, why not test against them the same way (if you care about the type in addition to the truthiness, otherwise, clearly just use 'expr')?

**Comment by gpshead** [comment]
It is very rare for code to _need_ something to be the specific bool True/False instance.  Things that say they return true or false don't need to return a bool instance, they can return an integer or something else that evaluates to true or false when tested.

That True and False are singletons is a current CPython implementation detail because it made sense as an internal VM optimization.  I wouldn't expect that to be true on all Python VMs.

Anyways this issue and the PR just removed the lint error text promoting the idea of using `is True` and similar.  People still can, it's just that it usually isn't what people want so we shouldn't suggest it everywhere.
