### ISSUE TITLE
enum.IntFlag is just thought of as an int after bitwise operations

### ISSUE THREAD

**Issue by nicktimko** [PyCQA/pylint#2534]
https://docs.python.org/3/library/enum.html#intflag

> The next variation of `Enum` provided, `IntFlag`, is also based on `int`. The difference being `IntFlag` members **can be combined using the bitwise operators (`&`, `|`, `^`, `~`) and the result is still an `IntFlag` member**. However, as the name implies, `IntFlag` members also subclass int and can be used wherever an int is used. Any operation on an `IntFlag` member besides the bit-wise operations will lose the `IntFlag` membership.

pylint thinks that the bit-wise ops *do* lose the `IntFlag` membership.

### Steps to reproduce
```python
from enum import IntFlag

class Perm(IntFlag):
    R = 4
    W = 2
    X = 1

rw = Perm.R | Perm.W

assert isinstance(rw, Perm)
assert isinstance(rw, int)
assert isinstance(rw.value, int)  # E1101

# also IntFlags
(~Perm.R).value  # E1101
(7 & Perm.R).value  # E1101
(rw ^ Perm.W).value  # E1101
```

### Current behavior
```
$ python intenum.py  # (no AttributeExceptions)
$ pylint -E intenum.py
************* Module intenum
intenum.py:12:18: E1101: Instance of 'int' has no 'value' member (no-member)
intenum.py:15:1: E1101: Instance of 'int' has no 'value' member (no-member)
intenum.py:16:1: E1101: Instance of 'int' has no 'value' member (no-member)
intenum.py:17:1: E1101: Instance of 'int' has no 'value' member (no-member)
```

### Expected behavior
No warnings

### pylint --version output
```
$ pylint --version
pylint 2.1.1
astroid 2.0.4
Python 3.6.4 (default, Mar 26 2018, 16:21:07) 
[GCC 5.4.0 20160609]
```

**Comment by PCManticore** [comment]
Thanks for reporting this bug!

**Comment by PCManticore** [comment]
Alright, pushed a fix in astroid for this. Unfortunately now these operations are inferred as `Uninferable` rather than actual `IntFlag` objects. But at least they won't emit these errors any longer.
