### ISSUE TITLE
DeprecatedUseChecker

### ISSUE THREAD

**Issue by belm0** [PyCQA/pylint#2536]
### Is your feature request related to a problem? Please describe
Use of annotations and static analysis for API deprecation isn't a common pattern in Python.  It should be.  It's extremely frustrating to deal with runtime deprecation warnings from libraries:  headache to filter call sites in your own codebase vs. those of transitive dependencies, not sufficient for CI and ensuring that regressions don't get committed to a codebase, etc.

### Describe the solution you'd like
Well, Python should have a standard `@deprecated` decorator, and lint tools should flag uses of classes, methods, attributes, functions, etc. with the decorator.  It's unbelievable that Python has a fancy type annotation system, but no standard way to annotate things as deprecated for static analysis.

To get the ball rolling, I'd like to see a DeprecatedUseChecker which is flexible enough to take a list of decorator types (since there's no standard type in Python) and report when decorated items are used.  The common pattern will be for libraries to define their own `@deprecated`, or perhaps use a 3rd party library with a simple decorator definition.  The pylint user feeds those decorator types to the checker, and... done.   (And maybe someday Python gets a clue and has a standard decorator.)

I'd like to know:
   * does something like this already exist?
   * reasons why this won't work?
   * is there an checker with most of the basic functionality I can derive DeprecatedUseChecker from?

**Comment by PCManticore** [comment]
@belm0 While I agree with the general idea, I don't think the onus should be on Pylint to provide this functionality. We currently have a `deprecated-method` checker, but it relies on a hardcoded list of methods, categorised by their deprecation version. It would be possible to add an additional functionality on top of it that analyses Python functions/methods and looks for `DeprecationWarning` and `PendingDeprecationWarning`. Another improvement would be to allow providing a custom based list of deprecated qualified function/method names, which could probably help as well.
I suggest starting this DeprecatedUseChecker as a separate plugin for now and if it catches in popularity, we could pull it in the core.
