### ISSUE TITLE
Pyreverse cleanup & refactoring

### ISSUE THREAD

**Issue by pylint-bot** [PyCQA/pylint#254]
Originally reported by: **Emile Anclin (BitBucket: [anclin](http://bitbucket.org/anclin), GitHub: @anclin?)**

---

The _Pyreverse_ subproject doesn't seem to be very active and hasn't evolved a lot past years. It inheritates a lot of complexity and functionality which was removed in 2008; using _Pyreverse_ on _Pyreverse_ shows that the class hierarchy has some useless or almost useless classes; the same holds true for some methods or attributes. Before adding new functionalities, I suggest a big cleanup which could include:
- move the _pylint.pyreverse.utils_ snippets to where they are needed [done]
- expose the _ClassDiagram._nodes_ attribute as _nodes_ and remove trivial methods [more pythonic API, done]
- remove the useless _Figure_ class and move a _FilterMixin_ method into _ClassDiagram_ [done]
- remove _ClassDiagram.objects_ attribute and use the _nodes_ instead [done]
- disentangle _Diadef_-Something and _Linker_ classes [separation of concerns, partially done]
- move LocalsVisitor and Linker back from _astroid_ to _Pyreverse_ and remove _ASTWalker_ and  _IdGeneratorMixIn_ inheritage (removing also unneeded  functionalities like "tag") [done]
- Let ClassDiagram and PackageDiagram inherit from BaseDiagram to clarify functionalities [done]
- Add a print while parsing a module (specially interesting for big project in order so see some progress)

All the _done_ stuff is in a patch queue and I have some more ideas like that. Please feel free to comment or reject any of the proposals...

---
- Bitbucket: https://bitbucket.org/logilab/pylint/issue/254

**Comment by PCManticore** [comment]
Closing this. Not sure what this patch queue ever was, but I assume the patches landed already.
