### ISSUE TITLE
R1705 (no-else-return): Also apply for "raise"

### ISSUE THREAD

**Issue by pheanex** [PyCQA/pylint#2558]
Currently we have a check for "no-else-return", which covers the following case:
```python
if var:
  return 1
else:
  return 2
```

and would suggest this instead:
```python
if var:
  return 1
return 2
```

I suggest this checker also covers the same for "raise", either by enhancing this checker, or adding a new one.
```python
if var:
  raise ExceptionA
else:
  raise ExceptionB
```
=>
```python
if var:
  raise ExceptionA
raise ExceptionB
```

**Comment by pheanex** [comment]
Okay.
Since both "return" and "raise" are similar in behavior, would you either emit a no-else-return or a no-else-raise  for the following "mixed"-cases?
```python
if car:
  return 1
else:
  raise 2
```
Because it could also be simplified to:
```python
if car:
  return 1
raise 2
```

**Comment by PCManticore** [comment]
That's a good question. In that case we might be able to retrofit `no-else-return` to something along the lines of `no-else-branch`. It would be interesting to see what other tools are doing, such as `eslint`.

**Comment by jrobertson98atx** [comment]
Given the example above:

```
if car:
  return 1
else:
  raise 2
```

Shouldn't it be a 'no-else-return' since there's **no** need for the **else** due to a **return** in the if?

And following would be a `no-else-raise`:

```
if car:
  raise 1
else:
  return 2
```

**Comment by PCManticore** [comment]
Sounds about right!

**Comment by pheanex** [comment]
Shouldn't we also add some tests for the mixed cases? At least I did not see any in the PR.
Thanks for the work btw @jrobertson98atx  :smile:

**Comment by jrobertson98atx** [comment]
> Shouldn't we also add some tests for the mixed cases? At least I did not see any in the PR.

Yep, that'd be a good idea.  I'll add some mixed raise/return tests.  Thanks.
