### ISSUE TITLE
implement inline options

### ISSUE THREAD

**Issue by pylint-bot** [PyCQA/pylint#256]
Originally reported by: **Anonymous**

---

just like inline disable, inline options will be active for only that block of code.

for example:

```
#pylint: class-rgx=[a-z][a-z0-9_]+$
```

to change the class name regex for a module.

---
- Bitbucket: https://bitbucket.org/logilab/pylint/issue/256

**Comment by PCManticore** [comment]
While this looks nice in theory, in practice, it is going to require a lot of implementation effort for not too much gain. Closing this.
