### ISSUE TITLE
Pylint 2.1.1 doesn't understand async iterables

### ISSUE THREAD

**Issue by terrisgit** [PyCQA/pylint#2560]
Please reopen https://github.com/PyCQA/pylint/issues/2311 or consider this issue to be a regression

**Comment by PCManticore** [comment]
As mentioned with https://github.com/PyCQA/pylint/issues/2311#issuecomment-433386519, that issue is fixed in pylint 2.2.0 and astroid 2.1 (you'll need to get them from github now, but they will be available soon)
