### ISSUE TITLE
False positive `E1111` (`assignment-from-no-return`) for `sys.stdin.read()`

### ISSUE THREAD

**Issue by jeffwidman** [PyCQA/pylint#2571]
False positive `E1111` (`assignment-from-no-return`) for `sys.stdin.read()`.

[Code](https://github.com/dpkp/kafka-python/blob/481f88068bdf0a18f12fd7a811b795f889d35fc7/kafka/record/_crc32c.py#L140-L142):

    if __name__ == "__main__":
        import sys
        data = sys.stdin.read()

The final line here throws `E1111`:

    E: Assigning to function call which doesn't return (assignment-from-no-return)

However, `sys.stdin.read()` does return, so this is a false positive.

Pylint version: 2.1.1

Weirdly, this is only thrown on python 3.5 and 3.6, not on 2.7 or 3.4. 

You can see the full test matrix here: https://travis-ci.org/dpkp/kafka-python/builds/446012872

**Comment by PCManticore** [comment]
Thanks, this is definitely a bug!

**Comment by DanielNoord** [comment]
@Pierre-Sassoulas Can't reproduce this anymore!
