### ISSUE TITLE
how to get a list of the disabled messages and ignored files for current configuration

### ISSUE THREAD

**Issue by GliderGeek** [PyCQA/pylint#2574]
## Question
First of all thanks for this awesome linter!

my question is whether is it possible to load the current pylintrc file and get the disabled errors and ignored files from this configuration?

I am trying to make it easier to add pylint to existing projects and have adapted the following strategy:
1. run pylint without any config
2. add all errors to the 'disable' list
3. figure out which ones i actually care about and uncomment (activate) them
4. run pylint again and figure out which files cause these errors
5. list these files under 'ignore' to keep them quite and to provide a todo-list for code improvement. 

This is a lot of manual labor, so i have created a simple cli to do steps 1 and 2 of this: [pylintconfig](https://github.com/GliderGeek/pylintconfig)

Now i would like to extend this to the other steps and for this i would need to load the current pylintrc file and get the current disabled messaged and ignored files. 

I have found `from pylint.config import find_pylintrc`, but i don't get a lot further than that. Would be great if you could help out.

**Comment by PCManticore** [comment]
@GliderGeek Thanks for creating an issue. Other than using `configparser` to parse the config file returned by `find_pylintrc`, I don't see any available solution out of the box that pylint provides.
