### ISSUE TITLE
Python global keyword vs. Pylint W0603

### ISSUE THREAD

**Issue by 526677804** [PyCQA/pylint#2577]
## Question
**Steps**
Try to lint following code:

VAR_A = 10
def foo():
	global VAR_A   // [1]

**Behavior**
using default configuration
************* Module test.mytest
W0603: Using the global statement (global-statement)     // [1]

**pylint --version**
pylint 2.1.1
astroid 2.0.4
Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:04:45) [MSC v.1900 32 bit (Intel)]

**question**under the premise of full compliance with the specification, how should global keywords be named to pass the lint,or how to better solve the above problems,while fully complying width the specifications?

**Comment by PCManticore** [comment]
@526677804 Thanks for creating an issue. pylint complains here that you are using the `global` keyword to indicate a potential code smell. It's not a matter on how the global keywords are named, but rather the fact that you are relying on global state (which in most of the cases can be refactored into state per function)
