### ISSUE TITLE
Using functools partial on a function gives a too-many-function-args when using the function

### ISSUE THREAD

**Issue by sblask** [PyCQA/pylint#2588]
Consider the change in https://github.com/sblask/imsa/pull/1/commits/bca45bcd8432876ac6c9c6ed9f2683cf8b230a4e

Before applying the change, pylint shows no error. After, I get a `too-many-function-args` error(https://travis-ci.org/sblask/imsa/builds/452231861#L556) here: https://github.com/sblask/imsa/pull/1/commits/bca45bcd8432876ac6c9c6ed9f2683cf8b230a4e#diff-1aadb8ddef89a1a93b339ea042159355R294 Which is a call on the original function that has not been overridden.

```
$ pylint --version output
pylint 2.1.1
astroid 2.1.0-dev
Python 3.5.2 (default, Nov 23 2017, 16:37:01)
[GCC 5.4.0 20160609]
```

**Comment by PCManticore** [comment]
Thanks for creating an issue @sblask !

**Comment by hippo91** [comment]
@sblask thank you for the bug.
Here is a simple reproduction case:
```
"""
Bug test 2588
"""
from functools import partial

def root_function(first, second, third):
    """
    A function that will be partially applied
    """
    return first + second + third


if __name__ == "__main__":
    partial_func = partial(root_function, 1, 2, 3)  # pylint: disable=invalid-name
    print(partial_func())
    print(root_function(1, 2, 3))
```

And the pylint's output:
```
************* Module bug_2588
bug_2588.py:16:10: E1121: Too many positional arguments for function call (too-many-function-args)

------------------------------------------------------------------
Your code has been rated at 2.86/10 (previous run: 2.86/10, +0.00)
```
