### ISSUE TITLE
As a pylint developper, astroid is often out of date and makes pylint tests fail non explicitely

### ISSUE THREAD

**Issue by Pierre-Sassoulas** [PyCQA/pylint#2590]
The error you encounter because of that are not explicits at all and it's hard to guess that problems are not caused by the code you modified but by astroid being too old. 

This may seem a problem that should not happen often, but I had it 3 times in less than a month and I had to ask for help the first time, and think of it then test on the master branch the other times. I think that Astroid is out of date often enough that the documentation for launching test should include `tox --recreate`. Or maybe a mecanism to update automatically ?

**Comment by pradyunsg** [comment]
tox.ini can include recreate=True.

From https://tox.readthedocs.io/en/latest/config.html?highlight=recreate:

> recreate=false(true|false)
> &nbsp;&nbsp;&nbsp;&nbsp;Always recreate virtual environment if this option is true.

**Comment by Pierre-Sassoulas** [comment]
Would'nt it make tests longer all the time ? Maybe we just need developpers to be aware that they need to recreate it the first time they use it.

**Comment by PCManticore** [comment]
Yes, that's going to make the tests run longer. I think we can document `--recreate` in more places. If anyone has some time for a PR, that would be amazing!
