### ISSUE TITLE
Error installing pylint

### ISSUE THREAD

**Issue by mcandre** [PyCQA/pylint#2592]
When I try to install pylint, I get an error with the astroid package: `NameError: name 'implementation_name' is not defined`.

**Comment by almmechanics** [comment]
Looks like a pattern seen with other pip installs when using an older version of `setuptools`.

There's a solution offered by @PCManticore [here](https://github.com/PyCQA/pylint/issues/2538) which advises running `pip3 install setuptools -U` before installing `pylint`

**Comment by PCManticore** [comment]
Thanks for the comment @almmechanics ! @mcandre Let me know if you still have this issue after following those instructions.
