### ISSUE TITLE
pylint slow if code uses tqdm

### ISSUE THREAD

**Issue by bosr** [PyCQA/pylint#2596]
Hi,

Thanks for Pylint!

I'm having some performance trouble, similar to https://github.com/PyCQA/pylint/issues/2198, but this time a simpler, reproducible case:

```python
"""
This is a bug demonstration module.
"""
import tqdm


for _ in tqdm.tqdm(range(10)):  # same with tqdm.trange
    pass
```

### Steps to reproduce
1. Create a file `bug_demo.py` with the above content.
2. Run `time pylint bug_demo.py`
3. Grab some coffee ;)

### Current behavior
- with pylint 2.2.0-dev and astroid 2.1.0-dev, running time ~ 64sec
- with pylint 2.1.1 and astroid 2.0.4, running time ~ 57sec
- with pylint 1.9.2 and astroid 1.6.5, running time: 27sec

### Expected behavior
- running time ~ 0.1sec

### pylint --version output
```
pylint 2.2.0-dev
astroid 2.1.0-dev
Python 3.6.6 | packaged by conda-forge | (default, Jul 26 2018, 09:55:02)
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)]
```

Thanks for your help, cheers.

**Comment by PCManticore** [comment]
Thanks for creating an issue! It's definitely too slow.

**Comment by bosr** [comment]
Hi, thanks for the update. You gave me the idea of redoing my tests on other Python versions.

Actually, it looks like the problem only occurs on my anaconda Python 3.6.6, not on anaconda Python 3.5.5, nor on vanilla Python 3.5.6 or vanilla Python 3.6.6. In all cases, tqdm is `4.28.1` installed via pip.

Basically I tested: {A1, A2, A3, A4} x {C1, C2}, where
```
- A1: anaconda python 3.6.6
- A2: anaconda python 3.5.5
- A3: vanilla 3.5.6 (installed via pyenv)
- A4: vanilla 3.6.6 (same)

- C1: pylint 2.2.2 & astroid 2.1.0
- C2: pylint 2.3.0 & astroid 2.2.0
```

The only configurations with the bug are the ones involving anaconda Python 3.6.6.

# Using anaconda Python 3.6.6 (one of the latest conda stable)

I still have the bug with latest pypi-published versions (64sec)
```
pylint 2.2.2
astroid 2.1.0
Python 3.6.6 | packaged by conda-forge | (default, Jul 26 2018, 09:55:02) 
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)]
```

Still using Python 3.6.6, but now with the master PyLint 2.3.0 and master astroid (2.2.0), I still have the bug (64sec)
```
pylint 2.3.0
astroid 2.2.0
Python 3.6.6 | packaged by conda-forge | (default, Jul 26 2018, 09:55:02) 
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)]
```

# Using anaconda Python 3.5.5

No bug latest pypi-published versions (~0.6sec)
```
pylint 2.2.2
astroid 2.1.0
Python 3.5.5 | packaged by conda-forge | (default, Jul 23 2018, 23:45:11) 
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)]
```

No bug latest master versions (~0.6sec)
```
pylint 2.3.0
astroid 2.2.0
Python 3.5.5 | packaged by conda-forge | (default, Jul 23 2018, 23:45:11) 
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)]
```

# Using vanilla Python 3.5.6 (not from anaconda)

No bug (~0.7sec) with the following:
```
pylint 2.2.2
astroid 2.1.0
Python 3.5.6 (default, Oct 13 2018, 11:34:43) 
[GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.2)]
```

No bug either (~0.7sec) with the latest master of astroid and pylint:
```
pylint 2.3.0
astroid 2.2.0
Python 3.5.6 (default, Oct 13 2018, 11:34:43) 
[GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.2)]
```

# Using vanilla Python 3.6.6 (not from anaconda)

No bug (~0.7sec) with the following:
```
pylint 2.2.2
astroid 2.1.0
Python 3.6.6 (default, Oct 13 2018, 11:33:17) 
[GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.2)]
```

No bug either (~0.7sec) with the latest master of astroid and pylint:
```
pylint 2.3.0
astroid 2.2.0
Python 3.6.6 (default, Oct 13 2018, 11:33:17) 
[GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.2)]
```

**Comment by hippo91** [comment]
@bosr interesting benchmark. 
May we conclude that `pylint` is not the cause of your troubles but most probably your python/anaconda version is the source of the problem?

**Comment by bosr** [comment]
@hippo91 yes, there's no reason to impute this bug to `pylint`/`astroid`. I hoped this data would make someone tilt (like "hey, on anaconda python x they implement this as that, etc), but nevermind.

Cheers and thanks again for `pylint`!

**Comment by hippo91** [comment]
@bosr it was a pleasure.
I'm sorry to be unable to help you more but i don't know anything about anaconda/vanilla. 
Maybe you can ask for help toward anaconda developer team.
I'm closing this issue but don't hesitate to reopen it or add comment if you got more information.
