### ISSUE TITLE
unittest_lint.test_more_args fails with python 3.7.1 and windows 10

### ISSUE THREAD

**Issue by ReneGrellert** [PyCQA/pylint#2604]
### Steps to reproduce
1. run "python -m tox -e py37 -- -k unittest_lint -v" (with python 3.7 obviously) on windows
2. see the unittests fail

### Current behavior
Output:
py37 inst-nodeps: C:\Users\ReneG\workspaces\pylint\.tox\.tmp\package\1\pylint-tt-2.2.0.dev0.zip
py37 installed: apipkg==1.5,astroid==2.1.0.dev0,atomicwrites==1.2.1,attrs==18.2.0,colorama==0.4.0,coverage==4.5.2,execnet==1.5.0,isort==4.3.4,lazy-object-proxy==1.3.1,mccabe==0.6.1,more-itertools==4.3.0,pluggy==0.8.0,py==1.7.0,pylint-tt==2.2.0.dev0,Pypubsub==4.0.0,pytest==4.0.0,pytest-forked==0.2,pytest-runner==4.2,pytest-xdist==1.24.1,six==1.11.0,wrapt==1.10.11,wxPython==4.0.3
py37 run-test-pre: PYTHONHASHSEED='812'
py37 runtests: commands[0] | python -Wi 'C:\Users\ReneG\workspaces\pylint\.tox\py37\Lib\site-packages/coverage' run -m pytest --junitxml=../TEST-pylint-tt.xml 'C:\Users\ReneG\workspaces\pylint\.tox\py37\Lib\site-packages/pylint/test/' -k unittest_lint -v
============================= test session starts =============================
platform win32 -- Python 3.7.1, pytest-4.0.0, py-1.7.0, pluggy-0.8.0 -- C:\Users\ReneG\workspaces\pylint\.tox\py37\Scripts\python.EXE
cachedir: .tox\py37\.pytest_cache
rootdir: C:\Users\ReneG\workspaces\pylint, inifile: pytest.ini
plugins: xdist-1.24.1, forked-0.2
collected 1107 items / 1056 deselected

py37\Lib\site-packages\pylint\test\unittest_lint.py::test_no_args PASSED [  1%]
py37\Lib\site-packages\pylint\test\unittest_lint.py::test_one_arg[case0] PASSED [  3%]
py37\Lib\site-packages\pylint\test\unittest_lint.py::test_one_arg[case1] PASSED [  5%]
py37\Lib\site-packages\pylint\test\unittest_lint.py::test_one_arg[case2] PASSED [  7%]
py37\Lib\site-packages\pylint\test\unittest_lint.py::test_one_arg[case3] FAILED [  9%]
py37\Lib\site-packages\pylint\test\unittest_lint.py::test_one_arg[case4] PASSED [ 11%]
py37\Lib\site-packages\pylint\test\unittest_lint.py::test_two_similar_args[case0] PASSED [ 13%]
py37\Lib\site-packages\pylint\test\unittest_lint.py::test_two_similar_args[case1] PASSED [ 15%]
py37\Lib\site-packages\pylint\test\unittest_lint.py::test_two_similar_args[case2] PASSED [ 17%]
py37\Lib\site-packages\pylint\test\unittest_lint.py::test_two_similar_args[case3] PASSED [ 19%]
py37\Lib\site-packages\pylint\test\unittest_lint.py::test_more_args[case0] PASSED [ 21%]
py37\Lib\site-packages\pylint\test\unittest_lint.py::test_more_args[case1] PASSED [ 23%]
py37\Lib\site-packages\pylint\test\unittest_lint.py::test_more_args[case2] PASSED [ 25%]
py37\Lib\site-packages\pylint\test\unittest_lint.py::test_pylint_visit_method_taken_in_account PASSED [ 27%]
py37\Lib\site-packages\pylint\test\unittest_lint.py::test_enable_message PASSED [ 29%]
py37\Lib\site-packages\pylint\test\unittest_lint.py::test_enable_message_category PASSED [ 31%]
py37\Lib\site-packages\pylint\test\unittest_lint.py::test_message_state_scope PASSED [ 33%]
py37\Lib\site-packages\pylint\test\unittest_lint.py::test_enable_message_block PASSED [ 35%]
py37\Lib\site-packages\pylint\test\unittest_lint.py::test_enable_by_symbol PASSED [ 37%]
py37\Lib\site-packages\pylint\test\unittest_lint.py::test_enable_report PASSED [ 39%]
py37\Lib\site-packages\pylint\test\unittest_lint.py::test_report_output_format_aliased PASSED [ 41%]
py37\Lib\site-packages\pylint\test\unittest_lint.py::test_set_unsupported_reporter PASSED [ 43%]
py37\Lib\site-packages\pylint\test\unittest_lint.py::test_set_option_1 PASSED [ 45%]
py37\Lib\site-packages\pylint\test\unittest_lint.py::test_set_option_2 PASSED [ 47%]
py37\Lib\site-packages\pylint\test\unittest_lint.py::test_enable_checkers PASSED [ 49%]
py37\Lib\site-packages\pylint\test\unittest_lint.py::test_errors_only PASSED [ 50%]
py37\Lib\site-packages\pylint\test\unittest_lint.py::test_disable_similar PASSED [ 52%]
py37\Lib\site-packages\pylint\test\unittest_lint.py::test_disable_alot PASSED [ 54%]
py37\Lib\site-packages\pylint\test\unittest_lint.py::test_addmessage PASSED [ 56%]
py37\Lib\site-packages\pylint\test\unittest_lint.py::test_addmessage_invalid PASSED [ 58%]
py37\Lib\site-packages\pylint\test\unittest_lint.py::test_init_hooks_called_before_load_plugins PASSED [ 60%]
py37\Lib\site-packages\pylint\test\unittest_lint.py::test_analyze_explicit_script PASSED [ 62%]
py37\Lib\site-packages\pylint\test\unittest_lint.py::test_python3_checker_disabled PASSED [ 64%]
py37\Lib\site-packages\pylint\test\unittest_lint.py::test_full_documentation PASSED [ 66%]
py37\Lib\site-packages\pylint\test\unittest_lint.py::test_pylint_home PASSED [ 68%]
py37\Lib\site-packages\pylint\test\unittest_lint.py::test_pylintrc PASSED [ 70%]
py37\Lib\site-packages\pylint\test\unittest_lint.py::test_pylintrc_parentdir PASSED [ 72%]
py37\Lib\site-packages\pylint\test\unittest_lint.py::test_pylintrc_parentdir_no_package PASSED [ 74%]
py37\Lib\site-packages\pylint\test\unittest_lint.py::TestPreprocessOptions::test_value_equal PASSED [ 76%]
py37\Lib\site-packages\pylint\test\unittest_lint.py::TestPreprocessOptions::test_value_space PASSED [ 78%]
py37\Lib\site-packages\pylint\test\unittest_lint.py::TestPreprocessOptions::test_error_missing_expected_value PASSED [ 80%]
py37\Lib\site-packages\pylint\test\unittest_lint.py::TestPreprocessOptions::test_error_unexpected_value PASSED [ 82%]
py37\Lib\site-packages\pylint\test\unittest_lint.py::TestMessagesStore::test_check_message_id PASSED [ 84%]
py37\Lib\site-packages\pylint\test\unittest_lint.py::TestMessagesStore::test_message_help PASSED [ 86%]
py37\Lib\site-packages\pylint\test\unittest_lint.py::TestMessagesStore::test_message_help_minmax PASSED [ 88%]
py37\Lib\site-packages\pylint\test\unittest_lint.py::TestMessagesStore::test_list_messages PASSED [ 90%]
py37\Lib\site-packages\pylint\test\unittest_lint.py::TestMessagesStore::test_add_renamed_message PASSED [ 92%]
py37\Lib\site-packages\pylint\test\unittest_lint.py::TestMessagesStore::test_add_renamed_message_invalid PASSED [ 94%]
py37\Lib\site-packages\pylint\test\unittest_lint.py::TestMessagesStore::test_renamed_message_register PASSED [ 96%]
py37\Lib\site-packages\pylint\test\unittest_lint.py::test_custom_should_analyze_file PASSED [ 98%]
py37\Lib\site-packages\pylint\test\unittest_lint.py::test_filename_with__init__ PASSED [100%]

================================== FAILURES ===================================
_____________________________ test_one_arg[case3] _____________________________

fake_path = [1, 2, 3], case = ['a/']

    @pytest.mark.parametrize(
        "case", [["a/b/"], ["a/b"], ["a/b/__init__.py"], ["a/"], ["a"]]
    )
    def test_one_arg(fake_path, case):
        with tempdir() as chroot:
            create_files(["a/b/__init__.py"])
            expected = [join(chroot, "a")] + ["."] + fake_path

            assert sys.path == fake_path
            with lint.fix_import_path(case):
>               assert sys.path == expected
E               AssertionError: assert ['C:\\Users\\... '.', 1, 2, 3] == ['C:\\Users\\R... '.', 1, 2, 3]
E                 At index 0 diff: 'C:\\Users\\ReneG\\AppData\\Local\\Temp\\tmpq1dfl2ji\\a\\' != 'C:\\Users\\ReneG\\AppData\\Local\\Temp\\tmpq1dfl2ji\\a'
E                 Full diff:
E                 - ['C:\\Users\\ReneG\\AppData\\Local\\Temp\\tmpq1dfl2ji\\a\\', '.', 1, 2, 3]
E                 ?                                                         --
E                 + ['C:\\Users\\ReneG\\AppData\\Local\\Temp\\tmpq1dfl2ji\\a', '.', 1, 2, 3]

py37\Lib\site-packages\pylint\test\unittest_lint.py:187: AssertionError
--- generated xml file: C:\Users\ReneG\workspaces\pylint\TEST-pylint-tt.xml ---
============ 1 failed, 50 passed, 1056 deselected in 5.41 seconds =============`

I tracked it down to the case "a/", where fix_import_path adds a trailing "\\". 

### Expected behavior
The unittests become success.

### pylint --version output
'2.2.0-dev'

**Comment by PCManticore** [comment]
Thanks for the report @ReneGrellert !

**Comment by DanielNoord** [comment]
I'm going to close this as our CI seems to pass on these versions. Let me know if this is still an issue and we could re-investigate.
