### ISSUE TITLE
PyLint 2.2.2 W0107 using pass on Custom Exceptions

### ISSUE THREAD

**Issue by bsdtux** [PyCQA/pylint#2623]
### Steps to reproduce
1. Create a python module with the following
`class RunTaskError(Exception):
    """A base task to be inherited by task failure exceptions."""
    pass
`
2. Then run pylint with the following
pylint module_name

### Current behavior
[W0107(unnecessary-pass), RunTaskError] Unnecessary pass statement

### Expected behavior
When following the user defined documentation here
https://docs.python.org/3/tutorial/errors.html#user-defined-exceptions 
I would expect that pylint allow for me to use pass in that regard.

### pylint --version output
pylint 2.2.2
astroid 2.1.0
Python 3.7.0 (default, Aug 27 2018, 08:38:45)

**Comment by bsdtux** [comment]
While looking through the pylint repository I came across an exceptions file that does similar things and noticed that pass was not used. Removing the pass did not cause any issues.

**Comment by TheSnoozer** [comment]
seams related to https://github.com/PyCQA/pylint/issues/2616#issuecomment-442738701

**Comment by PCManticore** [comment]
Thanks @TheSnoozer ! @bsdtux Just remove the `pass` statement there.
