### ISSUE TITLE
maximum recursion depth exceeded after upgrade to the recent pylint & astroid

### ISSUE THREAD

**Issue by skirpichev** [PyCQA/pylint#2628]
### Steps to reproduce
1. clone & install [diofant](https://github.com/diofant/diofant/) without extra deps (pip install .)
2. install pyllint
3. run pylint -j1 diofant

### Current behavior

RecursionError, see e.g. [this build](https://travis-ci.org/diofant/diofant/jobs/460248594)

It doesn't help if I increase recursion limit.  E.g. with ``--init-hook="import sys; sys.setrecursionlimit(2000)"`` it doesn't finish test job in a reasonable time (~1h) on my system.

### Expected behavior

Tests pass, as before.  Workaround: downgrade pylint AND also add astroid deps, see https://github.com/diofant/diofant/commit/879f199540d5c34b379739f0af6b7935dcebd325#diff-380c6a8ebbbce17d55d50ef17d3cf906

### pylint --version output

pylint 2.2.2
astroid 2.1.0
Python 3.5.3 (default, Sep 27 2018, 17:25:39) 
[GCC 6.3.0 20170516]

**Comment by PCManticore** [comment]
Thanks for the report!

**Comment by PCManticore** [comment]
Hey @skirpichev 

As mentioned in https://github.com/PyCQA/pylint/issues/2388#issuecomment-598111552, I can no longer reproduce the recursion error in diofant with either pylint 2.4.4 or 2.5.0. Please give it another try and let us know if you can still reproduce the error. Thank you!

**Comment by skirpichev** [comment]
I will try.  But it seems to be working now; I reverted pinning of astroid and use most recent versions of pylint and deps.  @PCManticore, looking forward to see 2.5!
