### ISSUE TITLE
False Positive E0611 when importing some constants from SSL Library

### ISSUE THREAD

**Issue by S3ntinelX** [PyCQA/pylint#2629]
Sorry if this is a duplicate

### Steps to reproduce
1. import ssl
2. print(ssl.PROTOCOL_TLS) 

### Current behavior
Flagged as an E0611, however will be printed correctly by the python interpreter. I believe this also occurs with some of the other constants in the ssl library.

### Expected behavior
Should not cause an error

### pylint --version output
pylint 2.2.2
astroid 2.1.0
Python 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:05:16)  [MSC v.1915 32 bit (Intel)] 

and

pylint 2.1.1
astroid 2.0.4
Python 3.6.7 (default, Oct 22 2018, 11:32:17)
[GCC 8.2.0]

**Comment by PCManticore** [comment]
Thanks @S3ntinelX ! Should be fixed with latest astroid.
