### ISSUE TITLE
Unused argument not reported when the name is `args`

### ISSUE THREAD

**Issue by ssssssyan** [PyCQA/pylint#2642]
### Steps to reproduce
1. Write a function that looks like `def process_file(file_dat, args=None)`. There is no special config to suppress `Unused argument` error.
2. No error reported when `args` is not used inside `process_file`.
3. Change the line to `def process_file(file_dat, foo=None)`,  pylint reports `Unused argument` error on `foo`.

### pylint --version output
pylint 2.0.1
astroid 2.0.1
Python 3.6.4 (default, Mar 22 2018, 14:11:17)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]

**Comment by PCManticore** [comment]
Hi. Thanks for reporting an issue. Unfortunately I cannot reproduce this bug using both 2.0.1 and the latest pylint. Do make sure you don't have `args` in `ignored-argument-names`, which could result in `args` being ignored.
