### ISSUE TITLE
Dead link on website

### ISSUE THREAD

**Issue by ElToro1966** [PyCQA/pylint#2650]
### Steps to reproduce
1. Click on List of supported IDEs under IDE Integration on the pylint.org main page.
2. Page https://docs.pylint.org/ide-integration opens with message "Sorry. This page does not exist yet."

### Expected behavior
Page with list of supported IDEs

**Comment by PCManticore** [comment]
Hi @ElToro1966 Unfortunately there's nothing I can do about the the pylint.org site. It's being maintained by the original authors of pylint, Logilab, with their issue tracker being hosted at https://bitbucket.org/logilab/pylint.org. I don't know if they still maintain it or not.
Regarding https://docs.pylint.org/ide-integration, we don't own that either, but if you remove the `ide-integration` part you can see that it's being redirected to readthedocs, with that page living at https://pylint.readthedocs.io/en/latest/user_guide/ide-integration.html.
Let me know if that makes sense!
