### ISSUE TITLE
Symilar don't accept folders

### ISSUE THREAD

**Issue by tovmeod** [PyCQA/pylint#2659]
The symilar command seems to expect a list of filenames, I would expect it to just take the basedir for my project and check all files there.

I actually made a patch in my installation, Can I create a PR for that?

also the -d option is broken, I'm getting "ValueError: invalid literal for int() with base 10: "

Do anyone actually use it?

### Steps to reproduce
1. symilar foldername
2.
3.

### Current behavior
An exception is raised

### Expected behavior
It should go trough all the files recursively

### pylint --version output
pylint 2.2.2
astroid 2.1.0
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0]

**Comment by PCManticore** [comment]
@tovmeod thanks for creating an issue. It is definitely possible that no one uses `symilar` seriously, I have not touched that in years or maybe never. If you can, definitely send a patch.
