### ISSUE TITLE
false negative for jq in wrong-import-order

### ISSUE THREAD

**Issue by mcandre** [PyCQA/pylint#2678]
wrong-import-order is treating jq as a builtin

**Comment by PCManticore** [comment]
This is coming from `isort`, which `pylint` uses internally to figure out if an import is stdlib, local or third party. I suggest adding `jq` to pylint's `known-third-party` setting or report the bug upstream to `isort`: http://pylint.pycqa.org/en/latest/technical_reference/features.html?highlight=known-third-party#imports-checker-options
