### ISSUE TITLE
[BUG] Dunder method signatures like __aexit__ shoudn't be considered duplications

### ISSUE THREAD

**Issue by webknjaz** [PyCQA/pylint#2682]
The problem is that magic methods with implement standard protocols shouldn't be considered duplications. Their signatures are pre-defined so it's no surprise that they are duplicated.

It looks like making signatures multiline (because they'd be too long otherwise and type hints can take extra space) causes minimal line limit for code duplication comparison be reached.

### Steps to reproduce
```python
    # pylint: disable=duplicate-code
    async def __aexit__(  # pylint: disable=duplicate-code
            self,
            exc_type: typing.Optional[typing.Type[BaseException]],
            exc_val: typing.Optional[BaseException],
            exc_tb: typing.Optional[types.TracebackType],
    ) -> typing.Optional[bool]:  # pylint: disable=duplicate-code
```

### Expected behavior

No error. I think this case should be globally ignored.

### pylint --version output
```console
$ pylint --version
pylint 2.2.2
astroid 2.1.0
Python 3.7.1 (default, Oct 21 2018, 21:08:23) 
[GCC 7.3.0]
```

**Comment by PCManticore** [comment]
I don't think this check is capable of ignoring such blocks of code. It's pretty primitive and relies only on the duplicated count of lines instead of something more fancy such as anti-unification. I don't think it's worth fixing this as is, just disable it locally or change the number of lines on which `duplicate-code` to trigger.

**Comment by webknjaz** [comment]
It's not but it's a good suggestion and is still a bug.

**Comment by PCManticore** [comment]
We have limited resources and we need to prioritize on what is important to fix and what is not. This one falls in the latter category as you can simply disable the error in place where you'd need. there's no need for additional complexity just to handle each edge case people find in the linter.
