### ISSUE TITLE
pylint doesn't recognize http.client members in python 3

### ISSUE THREAD

**Issue by halbii** [PyCQA/pylint#2687]
### Steps to reproduce
1. Install python 3.6.5 on Windows 10 or Ubuntu 18
2. Create a python file including:

import http.client
a = http.client.OK  # or another member, e.g. UNAUTHORIZED

3. run pylint -E [path/to/file]

### Current behavior
pylint does not recognize the member

### Expected behavior
pylint recognizes http.client's members

### pylint --1.8.4 or pylint --2.2.2 output
Module 'http.client' has no 'OK' member (no-member)

**Comment by PCManticore** [comment]
Thanks for reporting an issue! `pylint` does not know those members because they are added dynamically using `globals()`. We should add a brain inference file in `astroid` to make those recognisable.
