### ISSUE TITLE
Host pre-commit hooks

### ISSUE THREAD

**Issue by s0undt3ch** [PyCQA/pylint#2692]
Would you be OK with a PR migrating the pre-commit hook stuff from https://github.com/pre-commit/mirrors-pylint into PyLint's repo?

**Comment by PCManticore** [comment]
Sure, thanks for doing that!

**Comment by mattlbeck** [comment]
@PCManticore Did this migration happen? I don't see a .pre-commit-hook.yaml on master...

**Comment by s0undt3ch** [comment]
I never got to do it, it's in https://github.com/PyCQA/pylint/pull/3007 now.
