### ISSUE TITLE
--enable-all  should be restricted to checkers meaningfull for py2k or py3k

### ISSUE THREAD

**Issue by dputhier** [PyCQA/pylint#2699]
Hi,
I'm getting a little confused with the meaning of --enable=all. As a user, I would like to be able to activate all checkers that are meaningful for a Python 2 **or** 3 version. For instance, if I'm using Python 3 I don't wan't pylint to complain about something related to Python 2 syntax. Indeed, it seems to me that **from __future__ import absolute_import** is related to Python 2 not Python 3. If I would follow the advice of pylint I would then add this import to my code while the default behaviour of Python 3 is to use absolute import (If I understood well from what I have read).
Best 

    pylint --py3k --enable=all  test.py 
    ************* Module test.py
    test.py:10:0: W1618: import missing `from __future__ import absolute_import` (no-absolute-import)

**Comment by PCManticore** [comment]
@dputhier This is a bit confusing, but I'm not sure if this requires a separate solution. `--enable=all` does exactly what it says, it enables all the existing checkers. At the same time, ``--py3k`` acts at a separate level by enabling Python 2/3 porting related checks, which are disabled by default. Whenever you do `--enable=all` though you basically requesting those extra checks as well. In this case I don't think it makes sense to pass both `--py3k and `--enable=all`, so one of them should be removed depending on what you want to do there.
