### ISSUE TITLE
Support ellipsis as sole expression

### ISSUE THREAD

**Issue by dimaqq** [PyCQA/pylint#2718]
Python ellipsis `...` is a thing. Pylint doesn't like it, for example:

```
def unfinished_function():
    ...


def foo():
    if unfinished_block:
        ...

    with unfinished_context:
        ...


class CustomException:
    ...
```

**Comment by PCManticore** [comment]
What does `Pylint` complain about? What's the error that is emitted? Also we have an issue template for a reason, a lot of that information is useful to us to figure out what version are you using and so on.

**Comment by dimaqq** [comment]
Well, `pointless statement` of course!

**Comment by dimaqq** [comment]
And newest released version of course!

**Comment by dimaqq** [comment]
Thank you, Claudiu!
