### ISSUE TITLE
AENUM creating class bodies dynamically causes pylint warning

### ISSUE THREAD

**Issue by fordp2002** [PyCQA/pylint#2719]
https://stackoverflow.com/questions/54423962/aenum-creating-class-bodies-dynamically-causes-pylint-warning
1
### Current behavior
Error
### Expected behavior
No Error

### pylint --version output
<class 'AttributeError'>: 'For' object has no attribute 'value'

[installed astroid-2.2.0.dev0 pylint-2.3.0.dev1]

**Comment by PCManticore** [comment]
Thanks for the report. This was a bug in the `astroid` library used by `pylint`. The latest `master` branch of `astroid` should fix this problem.
