### ISSUE TITLE
Possible to whitelist non-installed modules for ROS? 

### ISSUE THREAD

**Issue by andersfischernielsen** [PyCQA/pylint#2726]
Hi, I'm currently researching how to build static bug checkers of python packages in the [Robot Operating System](http://www.ros.org) at the IT University of Copenhagen. I have a few questions related to the possibility of using `pylint` in order to build some of these checkers. 

It is possible to create so-called packages in ROS using Python (among other languages). I'm trying to see if it is possible to verify that the imported modules in these packages exist with `pylint`, but I'm having a hard time getting the expected behaviour (I have too many false positives). 
I'd like to verify whether these declared modules exist based on the requirement specification (a list of modules) of the ROS package - without installing all the required modules using e.g. `pip`. 
I have tried using the parameter `--extension-pkg-whitelist=packagename` but I am still getting false positives. 

What I'm wondering is: 
* Do I have to install all the declared modules using e.g. `pip` in order for `pylint` to detect them correctly? 
* Is it possible to feed pylint a `requirements.txt` (or a similar format) that will then allow `pylint` to detect these imports as non-errors (again without installing)? 

I will also submit this to the mailing list, since I'm unsure whether this is the correct place to post.

**Comment by PCManticore** [comment]
Hi @andersfischernielsen 

I think your use case is better fitted for [astroid](https://github.com/PyCQA/astroid) instead, which `pylint` uses internally to figure out things like the import system and general understanding of Python code and structure. Alternatively you can also write a [custom plugin](http://pylint.pycqa.org/en/latest/how_tos/custom_checkers.html) in which you can consume a list of dependencies from either `requirements.txt` or even from a configuration in `pylintrc`

Unfortunately, even with `astroid, you definitely need the module to exist. If it's not importable using the normal import system, then `pylint` will emit an `import-error`, as we've reimplemented the import system. I think your best bet at this point is probably a custom plugin.
