### ISSUE TITLE
Document what enable / disable can receive (e.g. group of checks)

### ISSUE THREAD

**Issue by Bernhard10** [PyCQA/pylint#2732]
## Question
I have a project that should run on python2 and python3, so I would like to have the py3k checkers enabled in addition to the usual checks. 
Is this possible? I know that `--py3k` disables normal checks.

**Comment by PCManticore** [comment]
Yes, all you have to do is set `enable=all` in your pylint configuration file. What `--py3k` does is that it disabled by default the Python 3 porting checks, but that can be bypassed by enabling the corresponding checks individually, e.g. either via `enable=all` or via `enable=<your default checks>,python3`

**Comment by Bernhard10** [comment]
Thanks. I knew about `enable=all`, but `enable=python3` is really what I was looking for.

Is there some documentation where I can find what words for groups of checks are accepted with the enable option?

**Comment by PCManticore** [comment]
@Bernhard10 I don't think there is officially but we should add that. You can enable / disable individual numeric check names (`W...`), symbolic names (`no-member`) or checker classes, e.g. `python3`, `format`, `typecheck`, which are the names of each group of checkers.
