### ISSUE TITLE
I wanna feedback a bug.

### ISSUE THREAD

**Issue by COCO5666** [PyCQA/pylint#2733]
My code is right, but it prompt error as the following picture shows.
![image](https://user-images.githubusercontent.com/36597804/52416093-bf9b8180-2b23-11e9-864d-7371b47a3090.png)

There are all the relevant codes in the test.zip file.
[test.zip](https://github.com/PyCQA/pylint/files/2841217/test.zip)

**Comment by Pierre-Sassoulas** [comment]
Here's the code in test.zip :
```
def singleton(obj):
    '''
    #This is a decorator used to add functions and property to a class.
    '''
    #add class's property
    obj._instance = None

    #add/rewite class's function
    def __new__(cls, *args, **kwargs):
        if cls._instance:
            return cls._instance
        else:
            cls._instance = object.__new__(cls, *args, **kwargs)
            return cls._instance
    obj.__new__ = __new__

    #add class's function
    @classmethod
    def getInstance(cls, *args, **kwargs):
        '''
        get single instance
        '''
        if obj._instance:
            return obj._instance
        else:
            return obj.__new__(cls)
    obj.getInstance = getInstance

    return obj

#using singleton decorate to add functions and property to selector class.
@singleton
class selector():
    pass

if __name__ == '__main__':
    ins = selector.getInstance()
    print('ins=', ins)
    ins2 = selector.getInstance()
    print('ins2=', ins2)
```
Pylint 2.2.2 result : 

```
test.py:37:10: E1101: Class 'selector' has no 'getInstance' member (no-member)
test.py:39:11: E1101: Class 'selector' has no 'getInstance' member (no-member)
```

Code execution : 

```
ins= <__main__.selector object at 0x7f34d6cd8e48>
ins2= <__main__.selector object at 0x7f34d6cd8e48>
```

**Comment by PCManticore** [comment]
Hi @COCO5666 Thanks for the report! Unfortunately this is not a problem that `pylint` could solve easily. First of all, right now pylint does not have support for decorators or any form, including class decorators like the one from your example. The other more difficult problem though is the fact that the class object gets mutated in the decorator, which is not something that can be tracked with static analysis easily. For now I suggest either using `--ignored-classes` to ignore the errors from that singleton or `--generated-members` to "fake" the existence of that method in the singleton class.
