### ISSUE TITLE
Pylint does not know SciPy.special.log_ndtr

### ISSUE THREAD

**Issue by astrozot** [PyCQA/pylint#2742]
### Steps to reproduce

> from scipy.special import log_ndtr

### Current behavior

PyLint shows the error message

No name 'log_ndtr' in module 'scipy.special' pylint (no-name-in-module)

### Expected behavior

No error expected

### pylint --version output

pylint 2.2.2
astroid 2.1.0
Python 3.7.1 (default, Dec 14 2018, 13:28:58)

**Comment by PCManticore** [comment]
I think `scipy.special` might be a C extension or something of sorts. If you do `--extension-pkg-whitelist=scipy.special`, the error goes error. Do note though that `--extension-pkg-whitelist` imports the module you specify to build an AST from the live module, but that's the only solution viable through which we can lint C extensions. Another alternative would be to write an astroid brain plugin, but we cannot do that for all the libraries.
