### ISSUE TITLE
used-before-assignment is not always triggered (part 2)

### ISSUE THREAD

**Issue by pylint-bot** [PyCQA/pylint#276]
Originally reported by: **Claudiu Popa (BitBucket: [PCManticore](http://bitbucket.org/PCManticore), GitHub: @PCManticore)**

---

```
#!python

a = c
b = c
c = None
```

The given code triggers an used-before-assignment only for `a=c`.

---
- Bitbucket: https://bitbucket.org/logilab/pylint/issue/276

**Comment by PCManticore** [comment]
I think this is fine, a new run would unveil it anyway.
