### ISSUE TITLE
python -m pylint --version

### ISSUE THREAD

**Issue by thisch** [PyCQA/pylint#2764]
### Steps to reproduce
1. run python -m pylint --verbose

### Current behavior

Output of the above command
```
__main__.py 2.3.0-dev2
astroid 2.2.0-dev
Python 3.7.2 (default, Dec 29 2018, 06:19:36) 
[GCC 7.3.0]
```

### Expected behavior

Expected output:

```
pylint 2.3.0-dev2
astroid 2.2.0-dev
Python 3.7.2 (default, Dec 29 2018, 06:19:36) 
[GCC 7.3.0]
```

### pylint --version output

see above

**Comment by PCManticore** [comment]
This makes sense and it's probably easy to fix. Mind submitting a PR if you have time for it?

**Comment by thisch** [comment]
If it is okay if we simply replace %prog by "pylint", then I'll create a PR.

**Comment by PCManticore** [comment]
Yep!
