### ISSUE TITLE
PyLint has become very slow

### ISSUE THREAD

**Issue by balloob** [PyCQA/pylint#2765]
_This is not an issue in pylint, but it impacts pylint, so I just wanted to create an issue and I'll close it right away, to help people looking for a solution._

The package isort, a dependency of PyLint, released new version 4.3.5 on Feb 24. This release includes a significant slowdown ([issue](https://github.com/timothycrosley/isort/issues/848)). On bigger projects, this can cause Travis to timeout. 

Until the issue is resolved, you should pin isort to the last known working version: 4.3.4.

**Comment by PCManticore** [comment]
Thanks for the heads up @balloob !
