### ISSUE TITLE
Add stable version of docs

### ISSUE THREAD

**Issue by hemberger** [PyCQA/pylint#2790]
There are no `stable` docs for pylint at http://pylint.pycqa.org/en/latest/
![image](https://user-images.githubusercontent.com/846186/53765380-af599680-3e84-11e9-994c-3945b95f3c30.png)

It would be useful to have a stable version of the docs (in addition to the `latest` docs) for the following reasons:
* It provides users with documentation that is consistent with the latest version on PyPI.
* It reduces confusion about which version is the latest release version.

I recently ran into a situation where a sysadmin thought that 2.4.0 was the latest stable version, and the docs only being generated for 2.4.0 contributed to that confusion.

### Describe the solution you'd like
I think, ideally, two things would happen here:
1. Update the SemVer tag for the current development version to include the `-dev` suffix (PR #2789)
2. Configure sphinx / ReadTheDocs to build a stable version

### Additional context
ReadTheDocs handles versioning like this automatically. From [their docs](https://docs.readthedocs.io/en/stable/versions.html):
> We also create a stable version, if your project has any tagged releases. stable will be automatically kept up to date to point at your highest version.

I see that pylint's docs are also hosted by ReadTheDocs, so I'm not sure why the latest tagged release (2.3.1) isn't showing up as `stable`.

**Comment by PCManticore** [comment]
Hey @hemberger Thanks for creating this issue! I'm not sure what happened but the versions were inactive in ReadTheDocs. I switched them on and `stable` should now be the default one.

**Comment by hemberger** [comment]
Sorry to bump this closed thread, but somehow `2.4.0` has made its way back to the stable version of the ReadTheDocs page (http://pylint.pycqa.org/en/stable/index.html), even though I don't see a `2.4.0` release or git tag. Any idea what has happened here @PCManticore?

**Comment by PCManticore** [comment]
@hemberger Sorry for the late reply. I don't know what happened here, but it seems that `stable` was targeting `origin/3.8`, which probably indicates that it started from a branch that added Python 3.8 support. I cleaned that up and `stable` should now point to `2.3.1` as expected.
