### ISSUE TITLE
modes feature

### ISSUE THREAD

**Issue by pylint-bot** [PyCQA/pylint#28]
Originally reported by: **Sylvain Thénault (BitBucket: [sthenault](http://bitbucket.org/sthenault), GitHub: @sthenault?)**

----------------------------------------

we would like to have modes which are a set of sections in the pylintrc file regrouping options overrides. A mode may be set using a command line option as well as in a specific file using inline instruction.

We may remove/deprecate -E option then.

----------------------------------------
- Bitbucket: https://bitbucket.org/logilab/pylint/issue/28

**Comment by PCManticore** [comment]
Closing this as it lacks a proper context in order to know what to do here.
