### ISSUE TITLE
Simple method to print version info

### ISSUE THREAD

**Issue by hemberger** [PyCQA/pylint#2800]
### Is your feature request related to a problem? Please describe
I'd like to be able to print the version information for pylint from within a python script that calls `pylint.lint.Run` (so as to log the full version information about the run). This is currently possible in three different ways, but I feel like they are too complex for the task.

1. 
```python
from pylint.lint import Run
try:
    Run(['--verbose'])
except SystemExit:
    pass
```
This is necessary because the optionparser is calling `sys.exit(0)` after processing `--verbose`. I thought `Run(['--verbose'], do_exit=False)` would solve this problem, but `do_exit` apparently doesn't control this particular exit.

2.
```python
import sys
import subprocess
subprocess.check_call([sys.executable, '-m', 'pylint', '--version'])
```
This is fairly succinct, but it is unsatisfying to add a dependence on the `subprocess` module.

3.
```python
import sys
from pylint.lint import version, astroid_version
print('pylint {}\nastroid {}\nPython {}'.format(version, astroid_version, sys.version))
```
This is fine, but it depends on knowing that the astroid version is critical to a complete picture of the version of the linter. Better to provide a canonicalized way to output the full version info.

### Describe the solution you'd like
I believe the simplest solution is to add a function `print_version` (or similar) accessible from `pylint` or `pylint.lint`. This could be called when creating the OptionParser to avoid duplicating the `full_version` string construction.
```python
>>> import pylint
>>> pylint.print_version()
pylint 2.3.1
astroid 2.2.3
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0]
```

A slightly less satisfying solution could be to modify the OptionParser so that `do_exit=False` is respected when calling `Run(['--version'], do_exit=False)`. In addition to being less satisfying, I'm also not certain it's easily achievable.

I'd be happy to submit a PR for this, taking into account any preferences for implementation that you might have.

### Additional context
It was hard to search for past issues that may have covered this topic, since every report is asked to provide the version info, so apologies if this is a duplicate!

**Comment by PCManticore** [comment]
Hye @hemberger Thanks for creating an issue! Yeah, this is a good idea.

I think a `pylint.version()` which returns a `namedtuple` in the form of `PylintVersion(pylint_version=Version(major, minor, patch), astroid_version=Version(major, minor, patch))` would be ideal, meaning it could be introspected for other purposes than just printing it to stdout. If you're interested in sending a PR for this, that would be amazing.

**Comment by hemberger** [comment]
Great! I hope you don't mind if I ask you some follow-up questions before I submit the PR -- I'd like to make sure that it achieves both of our goals.

1. What tool would you like me to use to parse the version string provided by `pylint.__pkginfo__.version` and `astroid.__pkginfo__.version`?  I could imagine using the parsing functions in setuptools, distutils, or packaging, or manually parsing it if you don't want to import any of these modules in `pylint/__init__.py`.

2. I find the `namedtuple` a bit harder to use for printing a human-readable version.
```python
def version():
    PylintVersion = collections.namedtuple('PylintVersion',
                                           'pylint_version astroid_version')
    return PylintVersion(pylint_version=__version__,
                         astroid_version=__astroid_version__)
```
This outputs:
```
>>> print(pylint.version())                                                     
PylintVersion(pylint_version='2.4.0-dev0', astroid_version='2.2.5')
```
I imagine it would be even less human-readable once the version numbers are converted to tuples as well.

One solution is to add a `version_string()` method that calls `version()` and then formats it into a nice human-readable string. Another option is to replace the function `version()` with a class `Version()` that handles its own string representation:
```python
class Version():
    def __init__(self):
        self.pylint_version = __version__
        self.astroid_version = __astroid_version__
    def __str__(self):
        return "pylint {}\nastroid {}\nPython {}".format(
            self.pylint_version, self.astroid_version, sys.version)
```
I have a slight preference for using the class instead of the named tuples, but if you disagree, please point me in the direction you'd like to proceed. Thanks!

**Comment by PCManticore** [comment]
@hemberger Sorry for the belated reply.

1. We should already have a `numversion` exported in each `__pkginfo__`. Actually `__pkginfo__.version` is constructed from a `numversion` tuple of values.

2. Using a `Version` class with a `__str__` implementation sounds good to me, let's do that instead.

**Comment by hemberger** [comment]
No worries about the delay -- thanks for getting back to me!

I have a few follow-up questions about `numversion` before I submit the PR.

**pylint**
In `pylint.__pkginfo__`, the `numversion` currently does not include the dev version -- it's only (major, minor, patch), even if `dev_version` is not None. How do you want to handle that? Do you want to add a 4th element to the tuple, and if so, what would you want it to look like? Perhaps:

```python
(2, 4, 0, 'dev0')  # dev release
(2, 4, 0, None)    # official release
```
However, I'm not sure how useful this is, since it breaks the ability to use `>` and `<` to compare versions, since e.g. `(2, 4, 0, 'dev0') > (2, 4, 0, None)` returns `True`. We have the same issue if we use a numerical dev version in the tuple.

**astroid**
In `astroid.__pkginfo__`, the situation with `numversion` is more problematic, because the version parsing code has trouble with dev versions:

```python
>>> version = '2.2.1-dev1'
>>> numversion = tuple(int(elem) for elem in version.split(".") if elem.isdigit())
>>> numversion
(2, 2)
```
This can be modified for consistency with `pylint` once we decide how we want to handle dev versions.

-------------

If you want to keep comparable version objects around (i.e. so that you can easily ask if one version is newer than another), then I'd recommend using a standard version parsing package, such as [packaging](https://pypi.org/project/packaging/) (which is used by `setuptools`) or `distutils` (which is in the python STL, though this doesn't support [PEP 440](https://www.python.org/dev/peps/pep-0440/) versioning, so you'd need to use their specific format, e.g. `2.4.0a0` instead of `2.4.0-dev0`).

Another couple of options available to us:
1. Re-implement the basic logic of these versioning modules in the `Version` class that we'll add here.
2. Forego a "numerical" version altogether, and make the user responsible for choosing an appropriate method to parse and compare the version string, should they need to.

It is certainly nice to be able to write `pylint.numversion > (2, 4, 0)`, but this will never work with dev versions (as far as I'm aware), and it would probably be overkill to define all the `__gt__`, `__lt__` etc. operators for a `pylint.Version` class.

How would you like to proceed, @PCManticore? I apologize for the overload of information, but since this isn't my project, I want to make sure you have all the information you need to make a choice you're happy with.

**Comment by PCManticore** [comment]
@hemberger Thank you for the thorough comments, really appreciate all this information and the thoughts around various edge cases.

Using `packaging` sounds like a good option to me, especially if it is already included by `setuptools`. I wonder if maybe both `astroid` can export a `version` object similar to `sys.version_info`, as in `Version(major=2, minor=2, patch=1, dev: Optional[int])`, in which case we'd be able to implement only `__eq__` and `__lt__` and use [functools.total_ordering](https://docs.python.org/3.8/library/functools.html#functools.total_ordering) to get a class with rich comparison abilities. Does that sound a good approach to you?

**Comment by hemberger** [comment]
I never forgot about this, but I was hesitant to make a PR with such substantive changes without having a better understanding of the codebase. Coming back to this over a year later, I see that 7831157f47800edc929be9b3c13f6d19f9a0645b achieves what I fundamentally wanted to do:
```python
import pylint.constants
print(pylint.constants.full_version)
```
While having version objects would be nice for version comparisons, it is not something that this issue demands. Since there doesn't seem to be much interest in this otherwise (except perhaps academic), I'll close this PR. Please feel free to reopen it if you'd like to keep this issue around.

Thanks again for your time!
