### ISSUE TITLE
Why C0325: (superfluous-parens), : Unnecessary parens after 'print' keyword

### ISSUE THREAD

**Issue by cclauss** [PyCQA/pylint#2801]
### Is your feature request related to a problem? Please describe
Why does __Why C0325: (superfluous-parens), : Unnecessary parens after 'print' keyword__ still exist in pylint?  There are just 300 days until the end of life of Python 2 and pylint contains a warning that encourages users to break compatibility with Python 3 by converting their __print()__ function calls into legacy __print__ statements that are syntax errors in Python 3.

### Describe the solution you'd like
Remove the warning that parens are unnecessary after the print keyword and no longer raise an error on code that is valid in both Python 2 and Python 3.

### Additional context
Add any other context about the feature request here.

**Comment by PCManticore** [comment]
@cclauss `superfluous-parens` is not necessarily for the `print` keyword, but for all the keywords around which parens can be added. It seemed we still had a reference in the code base for `print` itself but I just removed it in https://github.com/PyCQA/pylint/commit/4f25b4e67917b8e9c422e5ee3bb8705ce691a5fc. But other than that, we don't emit this check any longer for `print` with any `pylint` 2.X versions, which suggests to me that probably you noticed this error in `pylint 1.9` or something?

**Comment by Arnau-Ninerola** [comment]
@cclauss I don't think this is fixed. I am using pylint version 2.3.1 and this message shows: 
`Unnecessary parens after 'if' keyword (superfluous-parens)`

**Comment by gyermolenko** [comment]
@Arnau-Ninerola could you please provide a code snippet and pylint results?

**Comment by cclauss** [comment]
Please provide the line of code that PyLint is complaining about.

Try running that code through the Python Software Foundation's [black](https://github.com/psf/black) and see if it also removes those parens.

**Comment by Arnau-Ninerola** [comment]
Here is the code:
`if (option == 'start'):`

And the Pylint response:
`27:0: C0325: Unnecessary parens after 'if' keyword (superfluous-parens)`

**Comment by gyermolenko** [comment]
@Arnau-Ninerola Cxxx messages are about conventions, not errors. And such parens indeed can be removed

**Comment by cclauss** [comment]
Those parens are required in JavaScript, etc. but they are not required in Python.  __Black__ will remove them.

**Comment by Arnau-Ninerola** [comment]
@gyermolenko Ah alright! I thought the convention was to use parens in the if as you have to use them on print in python 3.
@cclauss  Thanks, I haven't used Black yet, maybe I will start tho I am not yet convinced that it will change my code. I prefer to do it manually for now
