### ISSUE TITLE
Segmentation Fault on parallel runs

### ISSUE THREAD

**Issue by jolaf** [PyCQA/pylint#2812]
In my development environment (Ubuntu 18.04 64-bit) `pylint` sometimes crashes with Segmentation Fault.

That can't be reproduced somewhat reliably, but it seems the problem occurs (more often?) when multiple `pylint` processes are running on the same machine simultaneously, OR if `--jobs` command line switch is used.

I've got a 30 MB crash file from Ubuntu Apport that contains stack trace, but I'm not sure how to submit it.

Unfortunately, I can't provide the code being linted.

```
lint.py 2.3.1
astroid 2.2.5
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0]
```

**Comment by PCManticore** [comment]
@jolaf Thanks for reporting the issue. Do you have any C extensions in your code? Do you happen to use `--extension-pkg-whitelist` with any of those? These might hint on why you are getting a Segmentation fault, but if that's not the case, it's probably better to find a minimal reproduction example.

**Comment by jolaf** [comment]
@r.kondratenko

**Comment by jolaf** [comment]
@PCManticore Yes, I do have whitelisted C extensions, but I couldn't find traces of their involvement in the stack trace.

Here's the Ubuntu Apport crash file, maybe it would be of some help:
https://www.dropbox.com/s/wtfev4rh3jxp765/_home_buildmaster_.local_lib_python3.6_site-packages_pylint_lint.py.340788395.crash

**Comment by PCManticore** [comment]
Unfortunately without a small reproduction example I can't do much. I don't have access to a Ubuntu Apport and it's also time consuming from my end. If you do manage to reproduce this with a short example with latest `pylint` installed from the `master` branch, I can take another look.
