### ISSUE TITLE
__init_subclass__ is a class method that takes subclass

### ISSUE THREAD

**Issue by BTaskaya** [PyCQA/pylint#2813]
```py
class Operation:
    def __init_subclass__(cls):
        if not hasattr(cls, '_op'):
            raise AttributeError("XYZ")
            
        if cls._op is OperationType.CALL:
```
```
restrict/restrict.py:22:11: E1101: Class 'Operation' has no '_op' member (no-member)
```
Subclasses of operation have `_op` attribute.  
```
batuhan@arch-pc > pylint --version
pylint 2.3.1
astroid 2.2.5
Python 3.7.1 (default, Oct 22 2018, 10:41:28) 
[GCC 8.2.1 20180831]
```

**Comment by NeilGirdhar** [comment]
I would make _op an abstract classmethod.

**Comment by BTaskaya** [comment]
It is like ORM Models.

```py
@OperationType.CALL
class RestrictAdd(Operation):
    cls = X
    methods = {'add'}
    access = Access.BY_CASE
```

The `OperationType` adds `_op` value.

**Comment by NeilGirdhar** [comment]
I understand, but if you use abstract classmethods, I think your code will be more Python, and pylint won't complain.

**Comment by PCManticore** [comment]
I agree with @NeilGirdhar here, there's no way for `pylint` to know that your subclasses provide this attribute without looking throughout your codebase to keep track of them, which sounds like a terrible idea from a performance point of view. Just define an abstract method and pylint will be happy.
