### ISSUE TITLE
W0621 Redefining name 'xxx' from outer scope when name is completely different

### ISSUE THREAD

**Issue by squarewave24** [PyCQA/pylint#2817]
in my flask api controller 

```
@app.route('/restrictions', methods=['GET', 'PUT', 'POST'])
def restrictions():
    """
    Top Level endpoint for /restrictions. Available methods:
    """
    if request.method == 'GET':
        return get_all()
     ...
```

```

def get_all():
    """
    get all restrictions from unobtanium.restriction table
    """
    ....
```
### W0621:  50,12: get_all: Redefining name 'restrictions' from outer scope (line 19)

if i rename the top method from `restrictions():` to `asdf():`  the error goes away

**Comment by PCManticore** [comment]
You probably get this error because you have a `restrictions` variable somewhere in your scope, which `pylint` complains about. Unfortunately I cannot reproduce using the given example, we probably need the entire file or another minimal reproduction example to figure this out.

**Comment by squarewave24** [comment]
> You probably get this error because you have a `restrictions` variable somewhere in your scope, which `pylint` complains about. Unfortunately I cannot reproduce using the given example, we probably need the entire file or another minimal reproduction example to figure this out.

I think you are right. i prefixed the main method with get_ and that fixed the issue
