### ISSUE TITLE
PyLint 1.9.4 and Python 2.7.16/2.7.13

### ISSUE THREAD

**Issue by paulmaia** [PyCQA/pylint#2823]
A clean install (today) of Python 2.7.16 (my previous install of Python 2.7.13 had same issue) with only PyLint added, crashes with the below error message. Installing PyLint 1.6.5 allows PyLint to run successfully. What is the latest version of PyLint that can successfully run on Python 2.7.x?

c:\Python27\Lib\site-packages>c:\python27\Scripts\pylint.exe
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "c:\python27\Scripts\pylint.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\pylint\__init__.py", line 16, in run_pylint
    Run(sys.argv[1:])
  File "c:\python27\lib\site-packages\pylint\lint.py", line 1270, in __init__
    ), option_groups=self.option_groups, pylintrc=self._rcfile)
  File "c:\python27\lib\site-packages\pylint\lint.py", line 466, in __init__
    config_file=pylintrc or config.PYLINTRC)
  File "c:\python27\lib\site-packages\pylint\config.py", line 464, in __init__
    self.reset_parsers(usage, version=version)
  File "c:\python27\lib\site-packages\pylint\config.py", line 478, in reset_parsers
    self.cfgfile_parser = configparser.ConfigParser(inline_comment_prefixes=('#', ';'))
TypeError: __init__() got an unexpected keyword argument 'inline_comment_prefixes'

**Comment by PCManticore** [comment]
@paulmaia 1.9.4 is the latest version you can use for 2.7.X, but you might be hitting a dependency issue with `python-future`, which itself is not a dependency of `pylint`: https://stackoverflow.com/questions/44659242/setuptools-force-version-of-another-package-if-present-while-not-forcing-inst

**Comment by paulmaia** [comment]
I appreciate the reply. I don't understand what this means:
    but you might be hitting a dependency issue with python-future,
    which itself is not a dependency of pylint.
I read the other thread and the indication is that 0.16.0 or later of future will address this. 
I am at 0.17.1 and the issue is still there.

I have back-revved Future to 0.16.0 with no joy
I uninstalled future with no joy
The only solution that works (if you want to call it that) is to back-rev PyLint, which leaves me with an inferior Lint experience.

The issue is easy to reproduce. Clean install of Python 2.7.16 and PyLint 1.9.4
None of the solutions described so far (except back-revving PyLint) will allow me to run PyLint. 
Everyone is pointing finger at everyone else and no one has a 'real' solution.
