### ISSUE TITLE
use wsgi to run py_run get std error

### ISSUE THREAD

**Issue by M1ssakira** [PyCQA/pylint#2837]
### Steps to reproduce
1.  i call the py_run in a django project, this is the code:
```py
    with tempfile.NamedTemporaryFile() as temp:
        temp.write(text)
        temp.seek(0)

        # ARGS = " -r n --disable=R,C"
        (pylint_stdout, pylint_stderr) = lint.py_run(
            temp.name, return_std=True)

    logger.debug(pylint_stdout.getvalue())
    print ('------>',pylint_stdout.getvalue(),pylint_stderr.getvalue())
    formatted_dict = format_errors(pylint_stdout.getvalue())
```
it work well when i run the project by commond line  , i get output from pylint_stdout.getvalue(). the print statement  output like this:
('------>', ''xxxxxx Your code has been rated at -32.31/10\n \n ", 'No config file found, using default configuration\n')

2. when i use uwsgi to run this django project , it doesnt work, and get error  in stderr,the print statement  output like this:
('------>', '', 'unable to load configuration from from pylint import epylint;epylint.Run()\n')

### Current behavior
i use command line to run the code it work well, but use uwsgi to run the project, it doesnt work
the result in steps.`
### Expected behavior
work well  by use uwsgi to run the project

### pylint --version output
pylint 1.9.4, 
astroid 1.6.5
Python 2.7.6 (default, Feb 12 2019, 18:12:13) 
[GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.10.44.4)]

---

commond line :('------>', ''xxxxxx Your code has been rated at -32.31/10\n \n ", 'No config file found, using default configuration\n')

use uwsgi : ('------>', '', 'unable to load configuration from from pylint import epylint;epylint.Run()\n') 

i read a little source code , and i know py_run to create a subprocess to check the code ,and i log  cli in py_run inside
commond line :  ['/Users/yaowang/.pyenv/versions/2.7.6/bin/python', '-c', 'from pylint import epylint;epylint.Run()', '/var/folders/dy/_41xp3kx6znd5mh1tgr9f0dw0000gp/T/tmp65emVv']

use uwsgi run the project:  ['/Users/yaowang/.pyenv/versions/2.7.6/bin/uwsgi', '-c', 'from pylint import epylint;epylint.Run()', '/var/folders/dy/_41xp3kx6znd5mh1tgr9f0dw0000gp/T/tmp9zCmRN']
 
if i dont have config file , it should be use default configuration, right?  but use uwsgi to run project,  it show ‘unable to load configuration’,  i  dont now why. i guess maybe about uwsgi and popen , could you give me some suggest about this problem？ thank you.

**Comment by PCManticore** [comment]
Hey @M1ssakira Thanks for opening an issue. I don't think this error is actually related to `pylint` , there must be some bad interaction going on between a Python subprocess and uwsgi. I don't know why exactly you need to run `epylint` with `uwsgi` but it does not seem like a good use case for running a linter. Sorry to not be of more help, but I doubt we actually need to support this use case.

**Comment by M1ssakira** [comment]
thank you for reply, i use linter by python code bacause in the webdsite, user can write some validation rule code to check data, the validation rule code transfer to backend, i want to check the code, i read pylint doc,and  find the epylint.pu_run() function can call linter in program,so i use this function .(write code into a tmpfile, and call the py_run) in this case, Is there a better function(in pylint) to do this? (sorry, i am not a english native speaker,maybe have some syntax error)

**Comment by PCManticore** [comment]
Hey @M1ssakira Turns out you were right. We were using in `epylint.py_run` the executable that started the Python script that had the `py_run` call, but in your example the executable was `uwsgi`, not `python`. The linked commit should address this issue, we try to figure out if we are using `python` and if we do not, we fallback to it instead. Please give it a go and let us know if that worked for you.

**Comment by M1ssakira** [comment]
thank you for you job ! this work for me. beacuse uwsgi change the sys.executable,  i find the issue about this action https://github.com/unbit/uwsgi/issues/670. Another problem is maybe multiple version python(include virtual env), we dont have a good way to find the right one, but its uwsgi'probelm. thank you again !
