### ISSUE TITLE
Regaridng wrong-import-order detection by pylint

### ISSUE THREAD

**Issue by anubhavsinha98** [PyCQA/pylint#2852]
## Question
Hi @PCManticore I am using Pylint version 1.9.3, when I earlier used to run the pylint for my codebase wrong-import-order was not being detected in my code, but after sometimes(Mostly after December or January) it's being detected. Is there any reason for it, or the pylint version 1.9.3 have been updated to do so now?

Thanks

**Comment by PCManticore** [comment]
Hi @anubhavsinha98 It's entirely possible that `isort` got updated, leading to new errors being surfaced. `pylint` uses that library for the `wrong-import-order` check. Right now we don't pin it in 1.9.X, we only pin it to `isort<5` in 2.X.
