### ISSUE TITLE
__init__() got an unexpected keyword argument 'inline_comment_prefixes'

### ISSUE THREAD

**Issue by williamskg6** [PyCQA/pylint#2860]
I know similar issues like this have been opened and closed, but none of the previous solutions offered to others work.  

Windows 10, 64-bit
32-bit Python 2.7.14 is installed (installed with ArcGIS Desktop)
pylint 1.9.4 is installed
future 0.17.1 is installed
futures 3.2.0 is installed

All were installed via pip.  

### Steps to reproduce
Attempt to run pylint.exe

No matter what arguments are provided to pylint, I get:
TypeError: __init__() got an unexpected keyword argument 'inline_comment_prefixes'

**Comment by PCManticore** [comment]
Hi, thanks for the report. Unfortunately the 1.9.X is no longer under maintenance. Also `inline_comment_prefixes` was most likely coming from a third party library that somehow got into the dependency tree when installing pylint.
