### ISSUE TITLE
proposal:  pylint test mode

### ISSUE THREAD

**Issue by belm0** [PyCQA/pylint#2863]
Proposal:  let pylint help with testing pylint plugins

I'd like to test pylint plugins by simply writing python modules, annotating the code with expected pylint messages in the form `# pylint: expect=symbol1,...`, and running pylint on the module with a `--test` option.

In this mode messages are suppressed if they match an `expect` annotation.  Other messages propagate.  Additionally, at the end of processing a module, there will be an error for any `expect` annotation which did not have a corresponding message raised.

**Comment by PCManticore** [comment]
This is the approach we're taking internally for writing tests, as those from the `functional` directory. But while this works for us, I doubt it's going to fully work for plugins, especially since the format and structure relies on non public interfaces and API. While I would be happy to include this functionality, leveraging the code from `test_functional`, it's something that I don't find that important right now to work on. If it is something that would be of interest to you, please take a look at `test_functional.py` and the corresponding tests from the `tests/functional` directory, but it will take a bit of work to make that format easily grokable to the outside of `pylint`.

**Comment by belm0** [comment]
For what it's worth, I implemented this crudely to test Trio's pylint checker.
https://github.com/python-trio/trio/pull/700

The hacky approach was to make a token checker which simply outputs the expected message annotations to stdout, then run that plugin in parallel with the plugin under test via a pytest invoking pylint.lint.Run.

```python
def test_pylint(capsys):
    # Run pylint on this file with the pylint-expect-message plugin enabled
    # and compare actual vs. expected pylint messages.
    #
    # pylint output synopsis:
    #    expected_line1:expected_symbol1
    #    expected_line2:expected_symbol2
    #    ...
    #    *** delimiter message
    #    actual_line1:actual_symbol1
    #    actual_line2:actual_symbol2
    #    ...
    Run([
        '--load-plugins=trio.testing.pylint-missing-await,trio.tests.pylint-expect-message',
        '--disable=all',
        '--enable=expect-message,missing-await,not-context-manager,not-an-iterable',
        '--score=n', '--msg-template={line}:{symbol}', __file__
    ],  do_exit=False)
    expected = set()  # set of (line_number, symbol)
    actual = set()
    target = expected
    for line in capsys.readouterr().out.splitlines():
        if line.startswith('*'):
            # end of expected section
            target = actual
            continue
        target.add(tuple(line.split(':')))
    assert actual == expected, 'pylint message check (ACTUAL == EXPECTED) failed'
```

**Comment by PCManticore** [comment]
@belm0 Just curious, did you try [assertAddsMessage](https://github.com/PyCQA/pylint/blob/master/pylint/testutils.py#L239) and [assertNoMessage](https://github.com/PyCQA/pylint/blob/master/pylint/testutils.py#L233), did they work for you? You still need to write a unit test like class, parsing the code that you are planning to test, but with those two context manager, you could theoretically do the same kind of tests, albeit less powerful that the one from `functional`.

**Comment by belm0** [comment]
Thank you-- I hadn't looked at testutils.py, some interesting things there.

Mainly, keeping the code to be linted as strings seems to have poor readability and not IDE-friendly, so I'd prefer the approach like `functional`.  I still think having pylint support this approach without boilerplate would reduce test friction and maybe help the quality 3rd party plugins.
