### ISSUE TITLE
''' block comment ''' String statement has no effect

### ISSUE THREAD

**Issue by badochov** [PyCQA/pylint#2864]
### Steps to reproduce
1.'''block comment'''

### Current behavior
closing ''' is highligthed with warning String statement has no effect

### Expected behavior
it shouldn't be highlighted

**Comment by matkoniecz** [comment]
> pylint --version output

Note that this part seems to be missing in your issue

**Comment by badochov** [comment]
2.3.1
astroid 2.2.5
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]

**Comment by PCManticore** [comment]
For block comments use the `#` instead of quotes, `pylint` does not accept the latter as a form of documentation other than in docstrings.

**Comment by MoonStruckHorrors** [comment]
I believe this needs to be fixed. Please refer the following tweet:

https://twitter.com/gvanrossum/status/112670605505077248
