### ISSUE TITLE
Checker/extension for amount of code in a try block

### ISSUE THREAD

**Issue by TNThieding** [PyCQA/pylint#2877]
### Is your feature request related to a problem? Please describe
Currently, Pylint does not have a checker to enforce PEP 8's guidelines about try/except statements and the amount of code in the ``try`` clause: "Additionally, for all try/except clauses, limit the try clause to the absolute minimum amount of code necessary. Again, this avoids masking bugs."

### Describe the solution you'd like
I propose adding either a checker or an extension (probably the latter) that enforces a maximum number of lines inside of a ``try`` block. The maximum number of lines would be configurable.

### Additional context
I would be willing to implement this feature myself. I'm mostly posting this issue/feature request to see if anyone else thinks this is a worthwhile addition to the package. Any opinions from other contributors would be greatly appreciated.

**Comment by PCManticore** [comment]
Hi, thanks for opening an issue. An extension that does this sounds good to me, definitely worth having it. Probably not enabled by default though, given that the amount of code that it will flag could be pretty large, but worth having it as an extension nonetheless.

**Comment by TNThieding** [comment]
Thanks for the feedback. I’ll start work on this as an extension checker later this week or this weekend.
