### ISSUE TITLE
protocol buffer support

### ISSUE THREAD

**Issue by pylint-bot** [PyCQA/pylint#29]
Originally reported by: **Sylvain Thénault (BitBucket: [sthenault](http://bitbucket.org/sthenault), GitHub: @sthenault?)**

----------------------------------------

this is probably rather a pylint-brain or astroid issue as it should be done using the new transformation API.

----------------------------------------
- Bitbucket: https://bitbucket.org/logilab/pylint/issue/29

**Comment by PCManticore** [comment]
Closing this for now. If someone wants to add protocol buffer support, they can create another issue, as it is a pretty specific case.
