### ISSUE TITLE
pip-installed wheel generates travis spam on macOS

### ISSUE THREAD

**Issue by fluffy-critter** [PyCQA/pylint#2907]
### Steps to reproduce
1. Run `pylint` with any set of command line arguments on macOS

### Current behavior

```
windowlick[~/projects/Publ] (feature/198-html-entities) fluffy$ pipenv run pylint -f colorized publ

--------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 10.00/10, +0.00)

profiling: /Users/travis/build/ionelmc/python-lazy-object-proxy/build/temp.macosx-10.13-x86_64-3.7/src/lazy_object_proxy/cext.gcda: cannot open: No such file or directory
```

### Expected behavior

Not outputting that final `profiling` line.

### pylint --version output

```
pylint 2.3.1
astroid 2.2.5
Python 3.7.2 (default, Jan 13 2019, 12:50:01) 
[Clang 10.0.0 (clang-1000.11.45.5)]
profiling: /Users/travis/build/ionelmc/python-lazy-object-proxy/build/temp.macosx-10.13-x86_64-3.7/src/lazy_object_proxy/cext.gcda: cannot open: No such file or directory
```

**Comment by jacobgarcia** [comment]
Bump. Even cannot run linter-pylint because of this

**Comment by jacobgarcia** [comment]
And it's not only when installing via pip. I already installed it from source code, and this happens too

**Comment by raphael-leger** [comment]
Same problem here.

Due to this extra line, Atom thinks pylint encounters an error and can not lint python files anymore, highlighting this error every time a file is opened.

**Comment by wizzl35** [comment]
I tracked this down to lazy-object-proxy.  `pip install lazy-object-proxy==1.3.1` fixes my issues.  Not very satisfactory solution.  I guess we will have to wait for pylint or astroid to pin to an earlier version or lazy-object-proxy to fix this bug.

**Comment by fluffy-critter** [comment]
Ah, good find. I'll open a bug against lazy-object-proxy and close this one.

**Comment by SupperSu** [comment]
I am new to profile and pylint, so please tolerate my stupid question, who is travis, is this the reason why we defined it as spam? I have no such user in my laptop Mac.
