### ISSUE TITLE
Discourage the use of constants added by the site module

### ISSUE THREAD

**Issue by alanyee** [PyCQA/pylint#2925]
### Is your feature request related to a problem? Please describe
I have seen use of `exit()` in the wild, though the uses of `quit()`, `copyright`, `credits`, and `license()` should also be discouraged. pylint does not currently check and mark down on this behavior.

### Describe the solution you'd like
If `exit()` or `quit()` is detected in a python script, the linter should throw some kind of message like: `Using exit() instead of sys.exit() in programs.` or `Using quit() instead of sys.exit() in programs.`.

For `copyright` and `credits`, suggest creating their own string literal instead of using the constants.

For `license()`, suggest the use of an explicit print statement instead of using the constants.

### Additional context
https://docs.python.org/3/library/constants.html#constants-added-by-the-site-module

**Comment by PCManticore** [comment]
Hi @alanyee Thank you for the suggestion, this could be useful to have.
