### ISSUE TITLE
False-positive while unpacking a list being created with append.

### ISSUE THREAD

**Issue by Max16hr** [PyCQA/pylint#2934]
### Steps to reproduce

    import numpy as np
    
    def GetList():
        L = []
        for i in range(2):
            L.append(i)
    #     L = [0, 1]
        return L
    
    diff = np.subtract(*GetList())
    print(diff)
    

### Current behavior

Pylint raises an error in line 10: `No value for argument in function call`. But the program is working fine.
It is also working when `GetList()` is returning `[0, 1]` directely but not if you create it iteratively by `append()`.

### Expected behavior

No error.

### pylint --version output

pylint 2.3.1
astroid 2.2.5
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]

**Comment by PCManticore** [comment]
Hi @Max16hr thank you for the report! This is the same issue as https://github.com/PyCQA/pylint/issues/2461 so I'll close this one as a duplicate.
