### ISSUE TITLE
Recommended way to obtain a message description

### ISSUE THREAD

**Issue by PetrWolf** [PyCQA/pylint#2936]
## Question
Dear PyLint maintainers,

I recently helped add a [PyLint plugin](https://github.com/JetBrains/teamcity-messages/pull/200) to the [JetBrains/teamcity-messages](https://github.com/JetBrains/teamcity-messages) project, integrating PyLint with the [Code Inspection](https://www.jetbrains.com/#BuildScriptInteractionwithTeamCity-ReportingInspections) feature of TeamCity.

[The code](https://github.com/JetBrains/teamcity-messages/blob/master/teamcity/pylint_reporter.py) uses a custom Reporter to emit special "service message" to TeamCity for each encountered issue. It also registers each unique issue type and that's where I ran into problems.

I used  `MessagesStore.get_message_definition()` to retrieve a full description of an issue type, which worked fine, but it turns out this was moved and renamed in a recent PyLint release. I can adapt the code based on PyLint version, but perhaps there is a better way?

Please could you recommend a way of retrieving a description of a message given its message if (from a custom reporter)?

Thank you!

**Comment by PCManticore** [comment]
Hey @PetrWolf 

Sorry for all this mess, we recently overhauled our message handling and we had to change a few things here and there in a backwards incompatible way.

Right now the authoritative way of grabbing the messages is using `MessagesStore .get_message_definitions()` which returns a list of `MessageDefinition` instances.

Let me know if that helps.

**Comment by PetrWolf** [comment]
Thank you, that works.
