### ISSUE TITLE
New check: interactive-exit

### ISSUE THREAD

**Issue by nickdrozd** [PyCQA/pylint#2942]
There are two exit functions, `exit` and `sys.exit`. [According to the docs](https://docs.python.org/3/library/constants.html#exit), `exit` is "useful for the interactive interpreter shell and should not be used in programs".

So add a check that suggests `sys.exit` instead of `exit`. This should be an easy one.

(Before adding it, verify that this is actually a good idea.)

**Comment by PCManticore** [comment]
Yeah, this sounds like a good idea! It was already mentioned in https://github.com/PyCQA/pylint/issues/2925, so I'm closing this issue to consolidate this feature request in a single one.
