### ISSUE TITLE
Facing trouble in testing a block of code which is derived from _check_docs_utils.py

### ISSUE THREAD

**Issue by lilithxxx** [PyCQA/pylint#3004]
## Question
I am trying to test [these lines](https://github.com/oppia/oppia/blob/f52947f8628dba82f307a2f3d4f70225a953d20e/scripts/docstrings_checker.py#L129-L138) in our codebase which is derived from this [block](https://github.com/PyCQA/pylint/blob/f6df51513267072b78b208c3ce2144a1155aa299/pylint/extensions/_check_docs_utils.py#L142) but it seems to be un-testable. I think they will only get executed if the exception target is a function but as far as I know, all exceptions should be sub-classes of "BaseException" so its target will only be of Class type and not a function type.

For example, an exception is raised like this: `raise Exception()` and the Exception is of type 'Class' and all exceptions should be of type class, i.e we cannot raise a function as exception as we will get an error from Python.

Can anyone please help me in testing this as its a part of my GSoC project. Thanks!

**Comment by PCManticore** [comment]
I have no idea what this issue is about, I'm sorry. This is also not a Q/A site, it's only for bugs and feature requests of pylint. Feel free to ask your GSoC mentor for help.

**Comment by lilithxxx** [comment]
@PCManticore I already asked my mentor for help and he suggested to talk to you guys about this. I am just asking under what conditions can [this](https://github.com/PyCQA/pylint/blob/f6df51513267072b78b208c3ce2144a1155aa299/pylint/extensions/_check_docs_utils.py#L142) line of code be hit?

Also, in your issue template there was an option to ask questions that's why I asked it here.
