### ISSUE TITLE
Running pylint 2.3.1 wih python 3.5 on Windows10 always throws an type error

### ISSUE THREAD

**Issue by kanchanaanil** [PyCQA/pylint#3009]
###Steps to reproduce
Install python 3.5 on Windows 10
run: pip install pylint
run pylint -V

### Current behavior
Throwing an type error

Expected behavior
Should not throw type error

###pylint --version output
This also throws an type error 
pip list shows enum34-1.1.6 , astroid-2.2.5 and pylint-2.3.1

I've installed and uninstalled couple of times both astroid and pylint as well as python
Please find attached files: Type error image and installed modules list

<img width="960" alt="Python_3_5_Pylint_2_3_1_Windows10_Error" src="https://user-images.githubusercontent.com/26023575/61323233-11f87100-a82d-11e9-8824-8665fb9ac634.png">

<img width="960" alt="Python_Modules_Installed" src="https://user-images.githubusercontent.com/26023575/61323295-3b190180-a82d-11e9-94f7-a79a8c3f5a05.png">

**Comment by PCManticore** [comment]
I think somehow you got a bad version of `typing` installed. If you do a `pip install typing -U` probably this should go away. I'm not entirely sure though, as I cannot reproduce this issue.
