### ISSUE TITLE
'Arguments' object has no attribute 'posonlyargs' in functional tests with pytest

### ISSUE THREAD

**Issue by Pierre-Sassoulas** [PyCQA/pylint#3022]
There is an error `'Arguments' object has no attribute 'posonlyargs'` for a lot of functional tests when launching tests with `pytest`. Do you have any idea how to solve this ?

### Steps to reproduce
1. Clone pylint repository
2. pip3 install pytest
3. python3 -m pytest tests/test_functional.py

### Current behaviour

```
python3 -m pytest tests/test_functional.py
==== test session starts ====
platform linux -- Python 3.7.3, pytest-5.0.1, py-1.8.0, pluggy-0.12.0
rootdir: /home/pierre/workspace/pylint, inifile: pytest.ini
collected 374 items

tests/test_functional.py .F.Fs.FFFF.F..F..Fs.s.s....sF.F.F.F.F.....s.F.F.sFF....s.FFFFF..F..
...
>       args = list(itertools.chain(called.args.posonlyargs or (), called.args.args))
E       AttributeError: 'Arguments' object has no attribute 'posonlyargs'
```

### Expected behaviour

Same results than when testing with `tox -e py37`

**Comment by PCManticore** [comment]
You need to do either `tox -e py37 --recreate` or install the latest `astroid` from the repository. `posonlyargs` landed in `astroid` `master` a while ago.

**Comment by gyermolenko** [comment]
Can confirm that with pylint from master (2.4.0.dev0) / astroid 2.2.5 I receive this error.
Installing astroid from master fixes the issue.

**Comment by ab-w** [comment]
Fwiw, it appears to no longer be necessary to install `astroid` from master. `astroid==2.3.0` is now available and it seems to have resolved the issue. It installed when I updated my project's environment.
