### ISSUE TITLE
Give a hint to swap if statement arms if the condition starts with `not`

### ISSUE THREAD

**Issue by windelbouwman** [PyCQA/pylint#3034]
Hi,

Currently, the code below does not give any improvement suggestions:

```python
if not BLA:
    print(22)
else:
    print(99)
```

It would be good if there was a suggestion made to swap the arms of the if statement like this:

```python
if BLA:
    print(99)
else:
    print(22)
```

What is your opinion on this? Is this a good pylint suggestion?

**Comment by PCManticore** [comment]
Not seeing why this would be so useful for everyone.
