### ISSUE TITLE
Distinguishing function calls from lambda functions that make function calls

### ISSUE THREAD

**Issue by bje-** [PyCQA/pylint#3046]
I recently had a bug that could have been found by Pylint, but am not quite sure how Pylint would identify the problem reliably. I had a dictionary whose values were lambda functions that make a function call, eg:

```
def foo(n):
  return n

x = {1: lambda: foo(1), 2: foo(2)}
print(x)
```

The intent was that every dictionary value was to be a lambda function, but i erroneously made the value for 2 just a bare function call. The result of the example above is: `{1: <function <lambda> at 0x7fe578e03b90>, 2: 2}`.

### Describe the solution you'd like

It would be good if, somehow, Pylint could identify this mistake, perhaps by identifying if a majority of the dictionary values are lambdas, interspersed with bare function calls? Obviously, in many cases, bare function calls here are fine and even desirable.

**Comment by PCManticore** [comment]
This most likely could have been caught by a tool like `mypy` as long as the code was annotated, with something along the lines of:
```
x: Dict[int, Callable[[int], int]] = {1: lambda: foo(1), 2: foo(2)}
```

At this moment though it's out of the scope for `pylint`, which does not have the full capabilities of a type checker.
