### ISSUE TITLE
Count ancestors only in user code

### ISSUE THREAD

**Issue by GoldsteinE** [PyCQA/pylint#3057]
### Is your feature request related to a problem? Please describe
Sometimes I need to inherit from classes defined in third-party libs. Sometimes these classes have long inheritance chain. I can't do anything about this, but still get too-many-ancestors.

### Describe the solution you'd like
I want there was an option to count ancestors only in "local" code, so pylint will complain only about the part of problem I can fix.

### Additional context
Here's example where it would be useful: https://stackoverflow.com/questions/22834392/understanding-too-many-ancestors-from-pylint/43090406

**Comment by PCManticore** [comment]
Thanks, I think this sounds like a sensible approach.
