### ISSUE TITLE
Access to a private function in inner class emits protected-access 

### ISSUE THREAD

**Issue by kown7** [PyCQA/pylint#3066]
This issue might be related to #1159 and maybe others.

### Steps to reproduce

The following code emits a W0212:

```python3
# pylint: disable=C0111, R0903


class Aclass:
    a = 42

    @staticmethod
    def foobar(i):
        Aclass._bar(i)

    @staticmethod
    def _bar(i):
        print(i)

    class Bclass:
        @staticmethod
        def foobar(i):
            Aclass.Bclass._bar(i)

        @staticmethod
        def _bar(i):
            print(i)


Aclass.foobar(Aclass.a + 3)
Aclass.Bclass.foobar(Aclass.a)
``` 

### Current behavior
```
************* Module pylint_test
pylint_test.py:19:12: W0212: Access to a protected member _bar of a client class (protected-access)
```

### Expected behavior

A solid 10/10 score.

### pylint --version output

pylint 2.3.1
astroid 2.2.5
Python 3.6.8 (default, Jan 14 2019, 11:02:34)
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]

**Comment by PCManticore** [comment]
This is somewhat of an edge case as the check would need to be aware where this entire chain of objects is coming from.

**Comment by kown7** [comment]
I was unsure whether this is was a coding error on my side or not.
