### ISSUE TITLE
Use of `.iteritems` detection fails in three contexts

### ISSUE THREAD

**Issue by DylanYoung** [PyCQA/pylint#3069]
## Situation One (defaults in functions):

    def get_partial_metadata(full_metadata=None):
        if full_metadata is None:
            full_metadata = get_full_metadata()
        metadata = {key: lst for key, lst in full_metadata.iteritems()}
        return metadata

## Situation Two (dicts created in __init__):

    class Boop(object):
        def __init__(self, mapping):
            self.map = mapping

        def demo(self):
            self.map.iteritems()

## Situation Three (copy of globals):

    module_dict = globals().copy()
    IMPORTER_TYPES = [name.lower() for name, cls in module_dict.iteritems()]

### Current behavior
None of these reports an error :(

### Expected behavior
All of these situations should report `W1620(dict-iter-method)`

### pylint --version output
pylint 1.9.5, 
astroid 1.6.6
Python 2.7.16 (default, Apr 26 2019, 16:26:18) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]

**Comment by PCManticore** [comment]
Hey @DylanYoung Thanks for the report! There seems to be a difference between the `python3` checker on pylint 2.X vs pylint 1.9.X. On pylint 2.X, the errors are emitted, but on the other version, we try to detect if the owner of the attribute is a dictionary or not (which we seem to fail when the object gets passed down from a different call site).
I think we should adapt 1.9.X to be the same as pylint 2.X for this check, so we should remove that restriction (or backport the content of `python3` to 1.9.X)

**Comment by Pierre-Sassoulas** [comment]
Closing because it's related to the py3k checker that was removed from pylint.
