### ISSUE TITLE
More concise checkers

### ISSUE THREAD

**Issue by jtrakk** [PyCQA/pylint#3070]
I'm mostly posting this in case others like the idea and want to discuss a concise checker API. Perhaps people have thoughts about how it should look or want to try writing an implementation.

### Is your feature request related to a problem? 

Writing a checker requires lots of boilerplate. For example, https://github.com/PyCQA/pylint-django/blob/master/pylint_django/checkers/forms.py

### Describe the solution you'd like

A much less verbose checker API. Perhaps something like this.

```py
import pylint

chkr = pylint.Checker(base_id='33')

@chkr.check(visit="Name")
def undefined_reference(checker, node):
    """The referenced name "{context}" is undefined."""
    if node.infer() is not None:
        return 
    yield message(context=node.value)
        

```

On:
```py
bar + 1
```

Generating:

```
foo.py:1:0: E3301 (undefined-reference): The referenced name "bar" is undefined.
```

**Comment by PCManticore** [comment]
I'd be open to find more concise forms of writing a checker. I'm not entirely sold on the one suggested, especially the magic `visit` parameter to `check`. We should definitely see what other linters are doing in this regard. Regardless of the approach, we're going to keep the current way of writing a checker a long time to main compatibility with the huge swath of plugins using the old structure.

**Comment by jtrakk** [comment]
### [ebb-lint](https://github.com/flowroute/ebb-lint/blob/master/ebb_lint/checkers/check_misc_dubious_syntax.py) 

Uses lib2to3 matcher syntax to find offending segments and yields a triple of the node(?), error object, and optionally extra data.


```py


useless_parens = Error(
    209,
    '{stmt} is not a function; parentheses are not required')


@register_checker("""
yield_expr< stmt='yield' yield_arg< 'from' atom< lparen='(' any* ')' > > >
""", python_minimum_version=(3, 4, 1))
def check_useless_parens_on_yield_from(stmt, lparen):  # ✘py27 ✘py33
    if lparen.prefix:
        return
    yield stmt, Errors.useless_parens, {'stmt': 'yield from'}


```

### [flake8-bugbear](https://github.com/PyCQA/flake8-bugbear/blob/master/bugbear.py)

You define a method to check and you call it from the visit method:


```py
def visit_For(self, node):
    self.check_for_b007(node)
    self.generic_visit(node)



def check_for_b011(self, node):
    if isinstance(node.test, ast.NameConstant) and node.test.value is False:
        self.errors.append(B011(node.lineno, node.col_offset))



B011 = Error(
    message="B011 Do not call assert False since python -O removes these calls. "
    "Instead callers should raise AssertionError()."
)
```

### [flake8 pandas-vet](https://github.com/deppen8/pandas-vet/blob/master/pandas_vet/__init__.py)

Similar to flake8-bugbear but you define a function to check and call it from the visit method.

```py
def check_for_read_table(node: ast.Call) -> List:
    """
    Check AST for occurence of the `.read_table()` method on the pandas object.
    Error/warning message to recommend use of `.read_csv()` method instead.
    """
    if isinstance(node.func, ast.Attribute) and node.func.attr == "read_table":
        return [PD012(node.lineno, node.col_offset)]
    return []
    
    

def visit_Attribute(self, node):
    """
    Called for `.attribute` nodes.
    """
    self.generic_visit(node)  # continue checking children
    self.errors.extend(check_for_values(node))    
    
PD015 = VetError(
    message="PD015 Use '.merge' method instead of 'pd.merge' function. They have equivalent functionality."
)    
```

### [bandit](https://github.com/PyCQA/bandit/blob/master/bandit/blacklists/imports.py)

Just checks for imports and calls, so it can be very concise.

```py
sets.append(utils.build_conf_dict(
    'import_ftplib', 'B402', ['ftplib'],
    'A FTP-related module is being imported.  FTP is considered '
    'insecure. Use SSH/SFTP/SCP or some other encrypted protocol.',
    'HIGH'
))
```

**Comment by jtrakk** [comment]
> I'm not entirely sold on the one suggested, especially the magic visit parameter to check. 

I don't like the string-typed specifier either, but isn't that how pylint works -- i.e. by using visitors specified by the name of the astroid node class?

```py
func = getattr(visitor, "visit_" + self.__class__.__name__.lower())
```

I would prefer to tell Pylint

```py
@visit(Foo)
def _(self, node): ...
```
instead of 
```py
def visit_Foo(self, node): ...
```

but I don't know how to make it visit me like that. Which method do I need to customize to change the visiting strategy?

**Comment by Pierre-Sassoulas** [comment]
I think breaking the checker API is not worth it, there's documentation about it, there's a lot of existing checkers and a lot of documentation is automatically generated based on it. I don't think the current API is bad enough to warrant so much churn when we have a lot on our plate already.

**Comment by DanielNoord** [comment]
Note that with some of the recent refactors you now only need to inherit from one of the basic checker classes, optionally define a checker name attribute, create the visit method and add the register function to your file.
We have removed almost all boilerplate already without relying on decorators etc.
