### ISSUE TITLE
Pylint crash astroid StopIteration

### ISSUE THREAD

**Issue by toonn** [PyCQA/pylint#3096]
### Steps to reproduce
1. Create a GitHub Actions workflow that uses pylint with py3.7.

### Current behavior
Link to a failed check: https://github.com/toonn/ranger/runs/215575795#step:5:9
I'm sorry for not reproducing the log in full here but GH's interface makes it close to uncopyable. I'm afraid this limits the ability to view to log to others who are already in the public beta.

### pylint --version output
I'm not sure which version GH-Actions uses and I'm fairly confident the problem's actually they're using incompatible versions of pylint and astroid but I don't know where else to report this.

**Comment by PCManticore** [comment]
@toonn This uses pylint 1.9.X and Python 3.7. This version of Python is not supported by pylint 1.9, you will have to update to Pylint 2.X to use Python >3.7.
