### ISSUE TITLE
Constant Name (C0103) PEP 8 Misinterpretation

### ISSUE THREAD

**Issue by rcgoodfellow** [PyCQA/pylint#3111]
Pylint seems to take the [statement](https://www.python.org/dev/peps/pep-0008/#constants)

> Constants are usually defined on a module level and written in all capital letters with underscores separating words.

To mean that all module level variables are constants, which is not what the above is saying. It's saying that **if** something is a constant, then it is usually at module level and written in all capitals. A reasonable interpretation of this is that constants **should** be written in all capitals and placed at module level, but **not** that all module level variables are constants.

The current pylint interpretation results in rampant capitalization ad nauseam in places where it absolutely does not belong, especially when folks run pylint over simple scripts. I do not see any mention in PEP 8 of capitalizing module or script level variables simply due to their scope.

**Comment by PCManticore** [comment]
I think you are right, this was badly interpreted since the beginnings of this check. It's definitely something we should change in 2.5.

**Comment by rcgoodfellow** [comment]
Thanks!
