### ISSUE TITLE
missing comma in pylintrc "enable" section does not cause a parsing failure

### ISSUE THREAD

**Issue by mscruggs-agari** [PyCQA/pylint#3122]
### Steps to reproduce
1. create a `pylintrc` file with an `enable` argument like:

```
enable=
  trailing-whitespace,
  missing-final-newline,
  eval-used,
  exec-used,
  print-statement,
  unused-variable,
  blacklisted-name    # <-- note the lack of trailing comma
  unused-import,
  deprecated-module,
  reimported,
  parse-error
```

2. run `pylint`

### Current behavior

`pylint` runs a full report, but the checks below the line without the trailing comma are not checked.

### Expected behavior

`pylint` throws an error while parsing `pylintrc`.

### pylint --version output

Encountered this issue in py27 and py35:

```
python -m pylint --version
Using config file /somewhere/over/the/rainbow/pylintrc
__main__.py 1.9.5, 
astroid 1.6.6
Python 2.7.10 (default, Feb 22 2019, 21:55:15) 
[GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.37.14)]
```

```
python -m pylint --version
pylint 2.4.0
astroid 2.3.0
Python 3.5.6 |Anaconda, Inc.| (default, Aug 26 2018, 16:30:03) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
```

**Comment by PCManticore** [comment]
Thanks, I can confirm the issue.

**Comment by mzagozen** [comment]
I've been testing how pylint handles enabling unknown checks:
- in `pylintrc`: silently ignored
- passed via a CLI argument `--enable foo`: silently ignored
- in source comment `# pylint: enable=foo`: E0012: bad-option-value

Shouldn't all of the above result in an error?
