### ISSUE TITLE
`import-outside-toplevel` checks and OS-specific stdlib modules, e.g. `resource` / `winreg`

### ISSUE THREAD

**Issue by nth10sd** [PyCQA/pylint#3124]
## Question
With pylint 2.4.0, there is a new `import-outside-toplevel` check. Modules such as `resource` are not available on Windows, whereas modules like `winreg` are. I have to wrap code that imports these modules into `try..except ImportError` blocks, but in doing so, pylint 2.4.0 throws a `import-outside-toplevel` check error.

May I know if the recommended way forward is to add ignore lines for these modules? Or should they be whitelisted in pylint 2.4.0 itself?

**Comment by PCManticore** [comment]
Thanks for opening an issue. `pylint` does not raise `import-outside-toplevel` when the imports are enclosed by `try-except` blocks, but when the imports found themselves in a separate scope such as a function. 
To control the modules that are permitted to be imported in functions you can use the new `--allow-any-import-level` option which receives a comma separated value string containing module names.

Hope this helps.

**Comment by nth10sd** [comment]
You're right, I had confused the situation between having an import in `try-except` blocks and separate scope/functions.

I also now use `allow-any-import-level` under `[IMPORTS]` section in `.pylintrc` to specify `resource` and `winreg` going forward.

Thanks for the prompt help!
