### ISSUE TITLE
Pylint 2.3.0 installs Astroid 2.3.0 which has breaking changes

### ISSUE THREAD

**Issue by dancodos** [PyCQA/pylint#3125]
Having `pylint==2.3.0` in our requirements file trigged an auto-download of the newest version of Astroid which caused breaking changes in our build. Namely, we got lots of `Instance of '' has no 'Object' member (no-member)` for dynamically generated classes. Explicitly setting `astroid==2.2.5` in our requirements fixed the issue, but it was surprising that this introduced breaking changes in an older version of Pylint.

### pylint --version output
pylint 2.3.0
astroid 2.3.0
Python 3.7.2 (default, Feb 25 2019, 20:43:22)
[Clang 10.0.0 (clang-1000.11.45.5)]

**Comment by balloob** [comment]
We got hit too at @home_assistant. 

Would it be possible for pylint to pin the version of astroid in use?

**Comment by PCManticore** [comment]
Just fixed with #3130 . Will be part of 2.4.1 shortly.

**Comment by balloob** [comment]
Thanks @PCManticore. What do you think of the idea of pinning the Astroid version?

**Comment by PCManticore** [comment]
I guess that could work, we could pin it to a minor release (2.3) for now.
