### ISSUE TITLE
PyQt signals are unsubscriptable

### ISSUE THREAD

**Issue by vallsv** [PyCQA/pylint#3140]
Hi.

As Qt provides signals with the same name but without the same signature (argument types are not the same), PyQt provides a way to select the one we want to connect.

```
foo = qt.QComboBox()
foo.activated[str].connect(callback)
```

It looks like Pylint can't deal with it.

```
def callback(*args, **kwargs):
    pass

foo = qt.QButtonGroup()
foo.buttonClicked[qt.QAbstractButton].connect(callback)

foo = qt.QComboBox()
foo.activated[str].connect(callback)
foo.activated[int].connect(callback)
foo.currentIndexChanged[str].connect(callback)
foo.currentIndexChanged[str].connect(callback)
```
Here is a pylint output:

```
PyLint: Value 'foo.buttonClicked' is unsubscriptable
PyLint: Value 'foo.activated' is unsubscriptable
PyLint: Value 'foo.activated' is unsubscriptable
PyLint: Value 'foo.currentIndexChanged' is unsubscriptable
PyLint: Value 'foo.currentIndexChanged' is unsubscriptable
```

Here is my version of pylint:
```
pylint 2.3.1
astroid 2.2.5
Python 3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)]
```
And i use the PyQt extension (`extension-pkg-whitelist=PyQt5`).

Any idea if it is a pylint but? Or something already fixed?

Thanks a lot.

**Comment by vallsv** [comment]
Oh, that's a duplication of #2543? I guess?

**Comment by PCManticore** [comment]
Yeah, looks like a duplicate! Thank you for the extra details though.
