### ISSUE TITLE
How to solve incorrect type detection

### ISSUE THREAD

**Issue by sbrunner** [PyCQA/pylint#3146]
## Question
With the new version of pylint and astroid
With the following simplified code (see httpexceptions inheritance: https://docs.pylonsproject.org/projects/pyramid/en/latest/api/httpexceptions.html#module-pyramid.httpexceptions):
```
from pyramid.httpexceptions import (HTTPBadRequest, HTTPMethodNotAllowed,
                                    HTTPException)

def create():
    if ...:
        return HTTPMethodNotAllowed(...)
    if ...:
        return HTTPBadRequest()
    return FeatureCollection() if ... else None


features = protocol.create(self.request)
for feature in features.features:
    ...
```

I get the error E1101: Instance of 'HTTPMethodNotAllowed' has no 'features' member (no-member)
Who is not bad, then I try to transform like that:

```
from pyramid.httpexceptions import (HTTPBadRequest, HTTPMethodNotAllowed,
                                    HTTPException)

def create():
    if ...:
        return HTTPMethodNotAllowed(...)
    if ...:
        return HTTPBadRequest()
    return FeatureCollection() if ... else None


features = protocol.create(self.request)
if isinstance(features, HTTPException):
    raise features
if features is not None:
    for feature in features.features:
        ...
```
But I get the following errors:

E0702: Raising NoneType while only classes or instances are allowed (raising-bad-type)
E1101: Instance of 'HTTPMethodNotAllowed' has no 'features' member (no-member)

Then I see that pylint don't understand the `isinstance` is it possible to solve that or should I ignore the errors?

See original code: https://github.com/camptocamp/c2cgeoportal/pull/5342/files

**Comment by PCManticore** [comment]
Thanks for opening an issue! Currently pylint's inference cannot figure out that certain branches are forced with `isinstance` so it infers every possible value leading to this kind of false positives. Control flow inference is something on our roadmap but it's going to take a while until we can start working on it. For now I recommend disabling the error in place using `# disable: ...` or using various flags to ignore certain classes for this check, such as `--ignored-classes`, `--ignored-modules` or `--generated-members`.
