### ISSUE TITLE
Undeserved R1722 (again)

### ISSUE THREAD

**Issue by SamyCookie** [PyCQA/pylint#3147]
follow #3145 

### Steps to reproduce
1. lint this code
```
def run()
    from sys import exit
    exit()
run()
```

### Current behavior
launch a linting recommandation R1722 (consider-using-sys-exit)

### Expected behavior
no recommation

### pylint --version output
pylint 2.4.2
astroid 2.3.1
Python 3.5.3 (default, Sep 27 2018, 17:25:39) 
[GCC 6.3.0 20170516]

**Comment by PCManticore** [comment]
Thanks, will be fixed in the next minor release.
