### ISSUE TITLE
broken links in www.pylint.org/

### ISSUE THREAD

**Issue by dpinol** [PyCQA/pylint#3153]
## Question
All the internal links I tested at main website are broken

- Fully customizablehttp://docs.pylint.org/message-control
- IDE integration: http://docs.pylint.org/ide-integration
- Editor integration: http://docs.pylint.org/ide-integration (shouldn't it be editor-integration?)

**Comment by PCManticore** [comment]
Thanks for opening an issue. Unfortunately the PyCQA's pylint team does not own the `pylint.org` domain. That one is owned by the original authors of `pylint`, namely Logilab. The `pylint` and `astroid` project moved off Logilab's Bitbucket repository to Github more than 5 years ago, but the `pylint.org` domain remained their property. Right now the recommended way of getting the documentation is via http://pylint.pycqa.org or via ReadTheDocs, while `docs.pylint.org` has a redirect to point to our ReadTheDocs installation.
