### ISSUE TITLE
scipy.signal.gaussian not registred

### ISSUE THREAD

**Issue by vallsv** [PyCQA/pylint#3154]
Hi,

Here is an API from `scipy` not properly discovered.

```
PyLint: Module 'scipy.signal' has no 'gaussian' member
```
Generated using
```
import scipy.signal
scipy.signal.gaussian(128, std=13)
```

If it is easy to fix, with a kind of tutorial/example, i can try to provide a PR.

**Comment by PCManticore** [comment]
Thanks for opening an issue! The best choice you have is to add a transform plugin to `astroid` here: https://github.com/PyCQA/astroid/tree/master/astroid/brain. Here's one for `numpy` for example: https://github.com/PyCQA/astroid/blob/master/astroid/brain/brain_numpy_random_mtrand.py The `scipy` one could be made in a similar fashion.

**Comment by vallsv** [comment]
Looks to be really easy then.
Let me few days. Ill maybe try :-)

**Comment by vallsv** [comment]
Hi. I created this PR https://github.com/PyCQA/astroid/pull/702 in order to fix my problem. Hope it can be useful.
