### ISSUE TITLE
Assigning result of a function call, where the function returns None

### ISSUE THREAD

**Issue by vallsv** [PyCQA/pylint#3160]
Hi

I reach that problem with this following code:
```
from typing import Optional

def getFoo() -> Optional[str]:
    return None

def getRealFoo() -> Optional[str]:
    result = getFoo()
    return result
```
This call `result = getFoo()` created this error `Assigning result of a function call, where the function returns None`.

Any idea why? Is that an issue? I fixed the error by specifying again the type: `result: Optional[str] = getFoo()`.

**Comment by PCManticore** [comment]
Hi, thanks for opening an issue. `pylint` currently does not support type annotations but it's something we plan to work on at some point. This check looks to see if you have assign the result of a function that does not return anything to a value, which your code does. Unfortunately until we'll have type annotation support, there's no way we can fix this particular problem.

**Comment by vallsv** [comment]
Ok, thanks for the feed back.
