### ISSUE TITLE
Omit unused-import for packages without actions (e.g., silence_tensorflow)

### ISSUE THREAD

**Issue by bersbersbers** [PyCQA/pylint#3163]
### Is your feature request related to a problem? Please describe
`import silence_tensorflow` triggers an `unused-import` warning.

### Describe the solution you'd like
No warning should be issued; the package is "used" by importing it and has not other methods/variables/...

**Comment by PCManticore** [comment]
I have no idea what `silence_tensorflow` is supposed to be doing but this seems like you could disable the error in place. Ideally you should not have modules that are used solely for their import side effect as that's an antipattern.

**Comment by bersbersbers** [comment]
> I have no idea what `silence_tensorflow` is supposed to be doing

Just for the record, from https://pypi.org/project/silence-tensorflow/:
> Simple python package to shut up Tensorflow warnings and logs.

Otherwise, I do agree.
