### ISSUE TITLE
False no-member positive on socket / SSLSocket.getpeercert

### ISSUE THREAD

**Issue by scop** [PyCQA/pylint#3166]
t.py:
```python 
import socket
import ssl

ctx = ssl.create_default_context()
address = ("example.com", 443)
with socket.create_connection(address) as sock:
    with ctx.wrap_socket(sock, server_hostname=address[0]) as ssock:
        print(ssock.getpeercert())
```

```
$ pylint t.py | grep no-member
t.py:8:14: E1101: Instance of 'socket' has no 'getpeercert' member (no-member)
```

Pylint (2.4.2, astroid 2.3.1) doesn't appear to notice that `ssock` is not just a `socket`, but (by default) `SSLSocket` which does have that member:
https://docs.python.org/3/library/ssl.html#ssl.SSLContext.wrap_socket
https://docs.python.org/3/library/ssl.html#ssl.SSLSocket.getpeercert

**Comment by scop** [comment]
No longer seems to happen with 2.7.2 / astroid 2.5.1, maybe fixed?

**Comment by hippo91** [comment]
@scop thanks for the update. As it seems to be fixed i close the issue. If it not the case, tell me and i will reopen it.
