### ISSUE TITLE
--ignore are not correctly hanlded

### ISSUE THREAD

**Issue by henri9813** [PyCQA/pylint#3180]
### Steps to reproduce
1. clone this: https://github.com/henri9813/tar-progress
2. run: `pylint tar_progress/ --ignore=tar_progress/classes/windows.py` 

### Current behavior

`windows.py` is analysed

Whereas if:
3. run: `pylint tar_progress/ --ignore=windows.py`  
`windows.py` is well ignored.

### Expected behavior

`windows.py` should not be parsed, because the path: `tar_progress/classes/windows.py` is ignored.

**Comment by PCManticore** [comment]
This is expected, `--ignore` supports only basenames as mentioned in the documentation. There's already an issue to fix that in https://github.com/PyCQA/pylint/issues/2279.
