### ISSUE TITLE
Report dangerous-default-value for instances of list, dict, set

### ISSUE THREAD

**Issue by scop** [PyCQA/pylint#3183]
It would be useful for `dangerous-default-value` to warn about more things than just plain list, dict, and set. For example collections.defaultdict is equally dangerous as dict.

Not sure if this should actually report for any values that are instances of list, dict, or set. On the other hand immutable instances of those aren't dangerous, so maybe the best would be if it could be reported just mutable ones.

If the instance of stuff isn't available, I guess extending the hardcoded list to include various known implementations e.g. in the collections module would be an improvement.

**Comment by PCManticore** [comment]
Thanks, this sound reasonable.

**Comment by scop** [comment]
If you can outline which approach of the suggested ones you'd prefer and give some hints how to implement it (e.g. how to do the needed instanceof-like calls with astroid instances, or other hints whichever way you'd prefer to see it), I could have a crack at it.

**Comment by PCManticore** [comment]
Hey @scop I think extending the list with a predefined set of mutable collections utilities should suffice for now. Is there something this extension would not include? 

Regarding your second question, there are multiple approaches:
* once an object is inferred, you call `.qname()` on it if it's an instance of something / function / class, to get its fully qualified name and compare that against a known list
* you can use `astroid.helpers.is_subtype` to check if a type is a subtype of another one
* or you can use `pylint.checkers.is_subclass_of` to determine if something is a subclass of a different `Class` node

This is not an exhaustive list, there's probably other ways to check what you need, including type checking against the `astroid` nodes themselves.

**Comment by scop** [comment]
Extending the check with known mutable collections would be an improvement, but it not take unknown mutable collections into account :) I.e. user defined ones.

I believe checking if the value is an instance of `collections.abc.MutableSequence`, `collections.abc.MutableSet`, or `collections.abc.MutableMapping` would implement this best.

**Comment by scop** [comment]
Come to think some more of this, it's not just the collections, but _any_ mutable object instance (or an immutable collection that contain one) is dangerous as a default, so this issue is much wider. Anyway I'll submit a PR that adds the mutable `collections.*`.
