### ISSUE TITLE
PyLint does not run on PyOdide

### ISSUE THREAD

**Issue by PythonLinks** [PyCQA/pylint#3199]
It would be nice for PyLint to run in the browser.  
PyOdide from Mozilla is cPython compiled to WebAssembly, and running in the browser. 
I was hoping that PyLint would run on it. 

Thanks to Python Buddy for this idea. 

### Steps to reproduce
1. I have attached the code at the bottom of this page. 

### Current behavior
*Uncaught (in promise) Couldn't find a pure Python 3 wheel for 'lazy-object-proxy == 1.4.*'
**

I do not even know what lazy-object-proxy is.  I presume that it is part of PyLint.  A search on this github repository did not yield anything.  Maybe it is a PyOdide problem.  Should I post this but report there?

### Expected behavior
Since all I am doing is loading PyLint, I did not expect any error message 

### pylint --version output
Should be the most recent version on PyPi.

### Here is the code to reproduced the problem. 

`
<html>

<head>
   <script type="text/javascript" src="https://pyodide.cdn.iodide.io/pyodide.js"></script>
  <script type="text/javascript">
    pythonCode = `

import micropip
linter = None
def something_awesome(*args):
    import pylint
    linter = pylint
    print(pylint)

micropip.install('pylint').then(something_awesome)
`

    languagePluginLoader.then(() => {
      pyodide.loadPackage(['micropip'])
    }).then(() => {
      console.log(pyodide.runPythonAsync(pythonCode));
    })
  </script>

</head>

<body>
<h1>
      Demonstrates the PyLint bug. 
</h1>   
<p> The idea was to load PyLint. The bug report is <br>
Uncaught (in promise) Couldn't find a pure Python 3 wheel for 'lazy-object-proxy == 1.4.*'
    <br>
    You have to run it first and then open the javascript console later. 
    </p>
 
    
</body>

</html>
`

**Comment by PCManticore** [comment]
Thanks for opening an issue. `lazy-object-proxy` is a library we use in `astroid` for having proxies to node classes. It's a third party library and we don't have that much control over it other than switching libraries, which I don't think it's worth to do right now. Other than that the team behind pylint is a small one and with not a lot of available time to contribute so spending it on making pylint work with PyOdide will not be a good allocation of our contribution time. If you're interested in getting pylint work with PyOdide definitely a good step would be to check why `lazy-object-proxy` does not work but that's definitely out of our wheelhouse.

**Comment by PythonLinks** [comment]
Understood. 
Thank you for the reply.  The confirmation that the problem is somewhere over here is a great help.   When I get motivated, I now know how to chase it down. 

In the meantime I now have PyOdide catching Python syntax errors in Python edited in the browser. Not as good as PyLint, but it does go a long way to being helpful.

Warm Regards
Chris

**Comment by maxwrlr** [comment]
Hey @PythonLinks, I stumbled across the same problem, but I found jedi, which is a pure python package, that gives you all the functionality that something like VSCode is having.

**Comment by PythonLinks** [comment]
Very cool.  Are you using it with Ace Editor?

**Comment by maxwrlr** [comment]
No, I'm using Monaco.

**Comment by miniBloq** [comment]
Is there anyway to get `jedi` telling _what_ a syntax error is instead of just _where_ it is in the code running by Pyodide? In particular, syntax errors inside `asyncio` coroutines "fail silently" and I was trying at least to get the linter helping with that. But can't find error messages, just error positions...

**Comment by DanielNoord** [comment]
You might be in the wrong repository for this. This is the `pylint` repo, you can find `jedi` [here](https://github.com/davidhalter/jedi).

**Comment by miniBloq** [comment]
Sorry, and thanks!

**Comment by maxwrlr** [comment]
@krishnagogada I used `@codingame/monaco-jsonrpc` but instead of passing a real WebSocket to `listen` I pass an object with similar functions that is posting the LSP messages to a WebWorker which then calls `JediLangServer.lsp._procedure_handler` using PyOdide.

**Comment by MarcSkovMadsen** [comment]
Hi @maxwrlr . Could you share a link to some minimum working example of this?

**Comment by maxwrlr** [comment]
@MarcSkovMadsen [Sure](https://github.com/maxwrlr/monaco-python).
