### ISSUE TITLE
Test request: implementation class has public methods not defined in base class

### ISSUE THREAD

**Issue by jeffb4** [PyCQA/pylint#3203]
### Is your feature request related to a problem? Please describe
Sometimes we forget to update base classes to specify new public methods

### Describe the solution you'd like
A pylint warning that a class defines public methods not originally defined in a base class

**Comment by PCManticore** [comment]
Hey @jeffb4 Thanks for opening an issue. While the idea sounds alright, I'm not sure if it's a good fit for the core pylint. I think having it as a PyPI plugin could also work for you.
