### ISSUE TITLE
Telling Pylint where to find a module ?

### ISSUE THREAD

**Issue by SheepDomination** [PyCQA/pylint#3205]
How do I tell pylint where a module is installed ?

**Comment by PCManticore** [comment]
Hey @SheepDomination 

I'm not entirely sure what your comment mean. Usually `pylint` figures out a module's location by checking common paths, such as the standard library or the current directory in case it's a local import, and thus it does not have a knob to configure for specifying where to look for modules.

If this is related to having an `import-error`, there are multiple things you can try to figure out to see if `pylint` is correct when emitting that error or not:

- if the module is a C extension, `pylint` won't be capable to find it and load it accordingly. You can pass `--extension-pkg-whitelist=<module name>` to `pylint` to force it to load and import a C extension
- if the module is a Python one, but it's in a non-standard location, there is not much you can do other than ignoring the module altogether, using `--ignored-modules=...`
- if the module is in a standard location but the error is emitted on a submodule, you can check to see if that submodule does anything funky with dynamic features of Python such as import hooks and `globals()` modification

Hope this helps.
