### ISSUE TITLE
Proxy Plugin for local Transform Plugins

### ISSUE THREAD

**Issue by hernot** [PyCQA/pylint#3219]
Hi
The following is not a true feature request but bug and general support questoin do fit even worth I just wanted to indicate my little transform plugin proxy plugin to you. 
 
It checks if on the file path of a module (eg. MyModule.py) defining a specific node (for now ClassDef only) a corresponding transform plugin module (eg. MyModule.ast.py) can be found and tries to load it.

More details can be found at https://github.com/hernot/pylint_plugin_proxy

**Comment by PCManticore** [comment]
Hey @hernot  Thanks for opening an issue. Unfortunately we're a small team of volunteers and these kind of questions are a better fit for StackOverflow and other mediums. 
I'm also not sure what the bug looks like, so if you can actually reproduce a bug with a minimal reproduction example, please open a bug report with all the relevant details.

**Comment by hernot** [comment]
Hi Claudiu
Inline Response (answers below questions asked)
Message sent on Mittwoch, 30.10.2019, 01:39 -0700 by Claudiu Popa:
> Hey @hernot  Thanks for opening an issue. Unfortunately we're a small
> team of volunteers and these kind of questions are a better fit for
> StackOverflow and other mediums. 
> I'm also not sure what the bug looks like, so if you can actually
> reproduce a bug with a minimal reproduction example, please open a
> bug report with all the relevant details.
> 

No need for a report. 

It was just meant as an hint for you as a team to my github repo
hosting a single transform plugin module module. Just in case sombody
would as whether it would be possible to store and distribute transform
plugin modules along with the modules and packages they provide
additional static information for.

Best
Best Xristoph
