### ISSUE TITLE
Formatting error for multiple spaces after a keyword is not emitted

### ISSUE THREAD

**Issue by finefoot** [PyCQA/pylint#3220]
Like

    if          0 == 1:
        pass

or

    def         func():
        pass

for example.

There is a sentence in PEP 8 about what to do if the statement is too long for one line and it specifies a single space character:

>  (...) it's worth noting that the combination of a two character keyword (i.e. if), plus **a single space**, plus an opening parenthesis creates (...)

So I'd assume, a single space is the way to go for keywords.

**Comment by PCManticore** [comment]
Because no one got to implement it yet.

**Comment by enkidulan** [comment]
I've started working on it as part of PyCon Canada sprints

**Comment by jacobtylerwalls** [comment]
`bad-whitespace` was removed in #3577 as not fitting pylint's roadmap, so since this code style issue is most like that warning, I suggest closing this issue on that basis.
