### ISSUE TITLE
RFE: warn about disables using identifiers, promote symbolic names

### ISSUE THREAD

**Issue by scop** [PyCQA/pylint#3250]
### Is your feature request related to a problem? Please describe

Would be nice to have a way to pylint emit warnings for `pylint disable=...` lines that use message identifiers as opposed to their symbolic names in code. The symbolic names can mostly be just understood when reading related code, whereas identifiers require one to look them up.

### Describe the solution you'd like

A warning message if one uses for example `# pylint disable=W0612` containing a suggestion to use `disable=unused-variable` instead.

### Additional context

I think I can have a look at implementing this sometime unless someone beats me to it, but posting this RFE to probe acceptability/desirability first.

**Comment by PCManticore** [comment]
Hey @scop 

Thank you for creating an issue! We already support this pattern with `use-symbolic-message-instead`. It is disabled by default though as it is an informational check, so you have to enable it explicitly:
```

python -m pylint a.py --enable=use-symbolic-message-instead
************* Module a
a.py:1:0: I0023: Id 'C0114' is used to disable 'missing-module-docstring' message emission (use-symbolic-message-instead)
```

**Comment by scop** [comment]
Oh, cool. However informational messages don't seem to cause a nonzero exit status, which I would like for this message. Is there a way to accomplish that?

**Comment by PCManticore** [comment]
There isn't a way to accomplish this I'm afraid, other than promoting this check to a different category in `pylint` itself.

**Comment by scop** [comment]
Ok, filed #3251 for the confurability :)

**Comment by dbaty** [comment]
For the record, a colleague of mine (@xavfernandez) recently released [a pylint plugin](https://pypi.org/project/pylint-message-id/) that registers such a warning message. The documentation is a bit short for now, but basically one just needs to:

1. Add `pylint-message-id` to your requirements.

2. And add the following line to the `.pylintrc`:

       load-plugins=pylint_message_id

And you get the following warnings:

    file.py:5: [C9001(numerical-message-id), ] Numerical message identifier used: W0123 - use eval-used instead

**Comment by xavfernandez** [comment]
I did not know about `use-symbolic-message-instead` :crying_cat_face: .

Since then, I've opened #3363 and its patch-plugin [pylint-strict-informational](https://pypi.org/project/pylint-strict-informational) so this becomes:

1.  Add `pylint-strict-informational` to your requirements.
 2. And add the following lines to the `.pylintrc`:

    ```
    load-plugins=pylint_strict_informational
    enable =
        use-symbolic-message-instead
    ```

**Comment by scop** [comment]
Very nice, thanks!
