### ISSUE TITLE
Suppress redefined-builtin for specific builtins

### ISSUE THREAD

**Issue by jonathanunderwood** [PyCQA/pylint#3263]
### Is your feature request related to a problem? Please describe
I'd like in general to keep redefined-builtin warnings (i.e. W0622). But often on projects usiing a database/ORM I want to make use of `id` as a variable, and so would like to suppress that warning only for that one specific builtin.  

### Describe the solution you'd like
It would be good to have a configuration parameter that could be set to a list of builtins to suppress that warning for.

**Comment by PCManticore** [comment]
Thanks for the report @jonathanunderwood I agree, this makes sense.

**Comment by gabrieldrs** [comment]
hey, I would like to tackle this.

Just to be sure that I'm in the right page, this change must go in the variables checker, and a new option should be added to the options tuple right?

**Comment by kapsh** [comment]
@gabrieldrs hello, are you working on this? I'd also like to see this feature and could take a shot on it if there are no work in progress.

**Comment by gabrieldrs** [comment]
Hey @kapsh I haven't been able to look at this, please, feel free to take it :)
