### ISSUE TITLE
pylint/2.4.4 doc build fails because it refers to non existing `../pylint/utils.py`

### ISSUE THREAD

**Issue by sandrotosi** [PyCQA/pylint#3265]
Hello,
the doc makefile still refers to `../pylint/utils.py` (https://github.com/PyCQA/pylint/blob/master/doc/Makefile#L143-L150) but that file has been removed now.

this prevents the update to the debian package; is there a quick workaround we can implement here?

thanks!

**Comment by PCManticore** [comment]
Hey @sandrotosi Not sure why that file was needed in the first place, just removed it with https://github.com/PyCQA/pylint/commit/3d8e0b39f2c41e50c664847a3397c60ee883efd4. I imagine you'll need a new 2.4.5 release to update the debian package? Let me know if that's the case to push a new bug fix release.

**Comment by sandrotosi** [comment]
thanks! no need to rush out a release only for this, i just took that patch and applied to our packaging, so we're good for now :)

**Comment by PCManticore** [comment]
Alright, thank you for confirming! Let's close this now since the fix will be part of the next patch release.
