### ISSUE TITLE
Pylint displays E0001 error code while importing packages. Code functions.

### ISSUE THREAD

**Issue by Fernal73** [PyCQA/pylint#3270]
Arch Linux on Termux:

$ pylint --version
pylint 2.3.1
astroid 2.2.5
Python 3.8.0 (default, Nov 14 2019, 15:41:40)
[GCC 8.3.0]

Termux:
$ pylint --version
pylint 2.3.1
astroid 2.2.5
Python 3.8.0 (default, Nov 20 2019, 20:44:46)
[Clang 8.0.7 (https://android.googlesource.com/toolchain/clang b55f2d4ebfd35bf6

import random
throws an error with code E0001 when used in python source.

(Should this be a pylint issue or should I post it on the Github projects for Termux and/or ArchLinux for Termux?)

https://github.com/PyCQA/pylint/issues/2976#issuecomment-557801624

**Comment by PCManticore** [comment]
Can you post the exact file that triggers this exception as well as the output? There must be something amiss especially since `random` is a stdlib package and `pylint` should find that without issues.

**Comment by Fernal73** [comment]
https://github.com/Fernal73/LearnPython3/blob/master/Intermediate/generator.py

This is one of the files that produces the error message.

I've currently suppressed the errors by updating .pylintrc and
.prospector.yaml.

It throws up E0001 in red at the import statements.

If you still can't reproduce the problem, I'll revert the suppressions and
post the results.

**Comment by Fernal73** [comment]
Updated with error.

**Comment by Fernal73** [comment]
https://github.com/termux/termux-packages/issues/4612#issuecomment-561672577

Closing bug. Fixed via Termux support.

**Comment by Fernal73** [comment]
On installing prospector via pip , I was able to reproduce the error importing the modules once more.

**Comment by Fernal73** [comment]
Do I need to open a separate bug on Prospector or will you do the needful?

**Comment by PCManticore** [comment]
Sorry I'm not entirely sure how to reproduce this error, so feel free to report a bug on Propsector side as well.

**Comment by Fernal73** [comment]
I can't find any pre-existing issues on Prospector. I think a link to this
bug should suffice as a bug report. I'm not inclined to re-describe the
issue. There's a limit to bureaucratese I can stand---from anyone.

**Comment by Fernal73** [comment]
pip install prospector==1.2.0.dev3
is the solution for now. Closing this issue.
