### ISSUE TITLE
E0611 false positive for scipy.spatial

### ISSUE THREAD

**Issue by GonerGenesis** [PyCQA/pylint#3273]
### Steps to reproduce
from scipy.spatial import ConvexHull

### Current behavior
E0611: No name 'ConvexHull' in module 'scipy.spatial' (no-name-in-module)

### Expected behavior
Should not cause an error

### pylint --version output
pylint 2.4.4
astroid 2.3.3
Python 3.7.5 (default, Oct 17 2019, 12:16:48) 
[GCC 9.2.1 20190827 (Red Hat 9.2.1-1)]

**Comment by PCManticore** [comment]
`scipy.spatial` seems to be in C so `pylint` cannot properly find that definition. You can use `--extension-pkg-whitelist=scipy` to tell `pylint` to dynamically load `scipy` for finding these kind of attributes (or you can ignore the module with `--ignored-modules`)
