### ISSUE TITLE
dict-iter-missing-items does not recognize tuple keys

### ISSUE THREAD

**Issue by lovetox** [PyCQA/pylint#3283]
### Steps to reproduce

```
mydict = { (a, b): c }

for (a, b) in mydict:
   print(a, b)
```

### Current behavior

Introduced with https://github.com/PyCQA/pylint/issues/2761

This yields now `dict-iter-missing-items`

if iterate with `mydict.keys()` it yields `consider-iterating-dictonary`

so there is no way anymore to iterate such a dict without warning or error, with one exception, using items() and casting the values to something like `_` which is ugly, or not unpacking at all in the `for` line.

### Expected behavior

Recognize if keys are tuples and dont throw this error

### pylint --version output

pylint 2.4.4
astroid 2.3.3
Python 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:17:05) [MSC v.1900 64 bit (AMD64)]

**Comment by Pierre-Sassoulas** [comment]
It makes sense, thank you for creating the issue.
