### ISSUE TITLE
warning when asserts have a string literal as condition

### ISSUE THREAD

**Issue by rjthomson** [PyCQA/pylint#3284]
A common mistake is to write asserts with a message as the only parameter.
For example:
`assert "unreachable code"`
instead of:
`assert False, "unreachable code"`
In the malformed case, the string will evaluate as `True` and the assertion will never hit.

Could Pylint warn if an assert has a string literal as the first parameter?

**Comment by PCManticore** [comment]
This is a good suggestion, thank you.

**Comment by anubh-v** [comment]
@PCManticore, may I work on this?
My current idea is to implement the logic for this check in the following method of `BasicChecker`
https://github.com/PyCQA/pylint/blob/a4136c14b98e65e1fe0bab4ec28564700ef983ed/pylint/checkers/base.py#L1380-L1388

**Comment by PCManticore** [comment]
@anubh-v Sure thing, feel free to tackle any issue you don't see assigned already.
