### ISSUE TITLE
Missing member on HTTPStatus enum instance

### ISSUE THREAD

**Issue by Hawk777** [PyCQA/pylint#3296]
### Steps to reproduce
1. Lint the code `print(http.HTTPStatus(404).phrase)`.

### Current behavior
test.py:2:6: E1101: Instance of 'HTTPStatus' has no 'phrase' member (no-member)

### Expected behavior
No errors.

### pylint --version output
pylint 2.4.4
astroid 2.3.3
Python 3.6.9 (default, Nov 10 2019, 00:34:23) 
[GCC 9.2.0]

This looks a bit like #2950, but that was apparently fixed prior to astroid 2.3.3 (at least based on the commit date, Astroid 2.3.3 was released on November 6 while #2950 was closed on September 12, so I assume it contains the fix) and referred to accessing enum members via their named constants rather than by the constructor. It also looks a bit like #2626, but that is about methods while this is about data members; also, it seems that #2950 was fixed by making Astroid explicitly aware of `HTTPStatus`, whereas #2626 is about a custom enum, so it seems like a separate issue.

**Comment by PCManticore** [comment]
Thanks for the report.
