### ISSUE TITLE
unwanted unsubscriptable-object on exception.args

### ISSUE THREAD

**Issue by craynic** [PyCQA/pylint#3315]
### Steps to reproduce
    class InvalidTimestampException(ValueError):
        def __str__(self):
            return "Invalid timestamp %d" % self.args[0]

### Current behavior
E1136: Value 'self.args' is unsubscriptable (unsubscriptable-object)

### Expected behavior
no error

### pylint --version output

pylint 2.4.4
astroid 2.3.3
Python 3.8.0 (default, Oct 23 2019, 18:51:26)

**Comment by craynic** [comment]
I'm upgrading from py2.7 to py3.8 . No error reported before.
If there is a better way to get the arg, I'm glad to learn.

**Comment by PCManticore** [comment]
This should no longer be the case for Pylint 2.5 once it's released. The fix landed in https://github.com/PyCQA/astroid/commit/b55fc8d9731e3527ab9c4c34488a6471d0aca62f if I'm not mistaken.
