### ISSUE TITLE
PyLint merge with Coverage reports (code now broken, sigh)

### ISSUE THREAD

**Issue by doctormo** [PyCQA/pylint#3323]
I made a fairly hacky script to run pylint over code that had been run in tests and was mentioned in the coverage report. This was then added on top directly in the html (This is not how I would have like dot have done it, but coverage is also a tangled weave of code).

https://gitlab.com/inkscape/extensions/blob/master/tests/add_pylint.py

But now with a a recent upgrade, the Run construction has changed and the code is borked. I don't want to have to pin the pylint version, but I understand this is a specialised use of pylint in a CI builder in conjunction with coverage reporting.

**Comment by PCManticore** [comment]
Hi @doctormo Please follow the issue template when reporting an issue, it's not clear what the regression is and the script is definitely not a minimum reproduction example. I'm closing this but feel free to reopen with more details related to what's actually broken.

**Comment by doctormo** [comment]
It was a feature request.

Eh, I'm not minded enough to write another issue. The templates are confusing and don't really fit. I'll just fork pylint, I don't really need to upstream anything anyway since using pylint in this way is clearly not supported.

But do keep in mind that getting data out of pylint in a computer-readable fashion would be very useful for a lot of applications.
