### ISSUE TITLE
Request a "Framework :: Pylint" classifier on PyPI

### ISSUE THREAD

**Issue by xavfernandez** [PyCQA/pylint#3335]
Having such a classifier would help discover Pylint plugins on PyPI.

[PyPI-Support](https://github.com/pypa/pypi-support/issues/new?labels=classifier+request&template=new-trove-classifier.md) would be the place to perform such a request.

[Flake8](https://pypi.org/search/?c=Framework+%3A%3A+Flake8) and [pytest](https://pypi.org/search/?c=Framework+%3A%3A+Pytest) have such classifiers.

**Comment by PCManticore** [comment]
Thanks for the idea! Requested it at https://github.com/pypa/trove-classifiers/issues/26.

**Comment by pradyunsg** [comment]
Heads up -- getting a few maintainers of pylint plugins, to respond saying "we'll use this" would be required for getting that classifier.
