### ISSUE TITLE
DatetimeIndex has no tz_localize member

### ISSUE THREAD

**Issue by ndclt** [PyCQA/pylint#3344]
### Steps to reproduce
1. Save the following lines in a script
```python
import pandas as pd

pd.DatetimeIndex([], name='time').tz_localize('UTC')
```
2. run pylint on this script

### Current behavior
Pylint returns:
```
[E1101(no-member), ] Instance of 'DatetimeIndex' has no 'tz_localize' member
```

### Expected behavior

No error, `tz_localize` is a member of `DatetimeIndex` ([pandas documentation](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DatetimeIndex.tz_localize.html)).

### pylint --version output

```
pylint 2.4.4
astroid 2.3.3
Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0]
```

**Comment by sschlueters** [comment]
This also affects the function `tz_convert` (see [pandas documentation](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DatetimeIndex.tz_convert.html)) and the property `timetz` ([pandas documentation](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DatetimeIndex.timetz.html), but not the property `tz` ([pandas documentation](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DatetimeIndex.tz.html)).

**Comment by clavedeluna** [comment]
No longer an issue as with #4910
