### ISSUE TITLE
Support gi.require_version mixed in with imports (wrong-import-position)

### ISSUE THREAD

**Issue by dseomn** [PyCQA/pylint#3349]
### Is your feature request related to a problem? Please describe
[PyGObject imports](https://pygobject.readthedocs.io/en/latest/getting_started.html) trigger `wrong-import-position` because they require calling a function before importing some modules, e.g.:

```python
import gi
gi.require_version("Gtk", "3.0")
from gi.repository import Gtk
```

### Describe the solution you'd like
What do you think about adding a configuration option for functions to ignore for the purposes of `wrong-import-position`?

**Comment by PCManticore** [comment]
Thanks for opening an issue. I'm not sure how common this pattern would be, so I'd like to have more data points before adding a new configuration option just for this check. In the meantime you can disable the check inline where you need to call `gi.require_version()`.

**Comment by dseomn** [comment]
https://github.com/nzjrs/pygobject/network/dependents shows about 11k repositories on GitHub that depend on PyGObject, so I think that's a reasonable lower bound on how common this is. I suspect there are a fair number of users on assorted GitLab instances though, since that seems to be popular among GTK people. Is 11k enough to justify this, or should I try to get a better estimate?

For what it's worth, I also see 2M+ [search results on GitHub](https://github.com/search?p=2&q=pkg_resources.require+extension%3Apy&type=Code) for [pkg_resources.require](https://setuptools.readthedocs.io/en/latest/pkg_resources.html#basic-workingset-methods), but the search query isn't very good, and the function I'm looking for is "intended more for use in quick-and-dirty scripting and interactive interpreter hacking than for production use". So I would put more stock in the 11k users of PyGObject than 2M+ potential uses of `pkg_resources.require`.
