### ISSUE TITLE
pylint stops seach after E0001

### ISSUE THREAD

**Issue by marcelotrevisani** [PyCQA/pylint#3353]
### Steps to reproduce
1. Create ``foo.py`` with the following content:

```python
def foo(bar):
    print("TESTING")
    print(bar_err)
    foo_dict = {
        "a": 0,
        "b: 1
        "c": 10
    }
    bar = [1, 2, 3]
    print(bar)
    for b in bar_err:
        print(bz.val())
```

2. Run ``pylint`` on that file
```pylint foo.txt```

3. The current output is:
```
************* Module foo
foo.py:6:14: E0001: EOL while scanning string literal (<unknown>, line 6) (syntax-error)

```
and it stops the search, if I remove that error regarding the dictionary ``foo_dict`` it will return all the errors

```
************* Module foo
foo.py:1:0: C0102: Black listed name "foo" (blacklisted-name)
foo.py:1:0: C0114: Missing module docstring (missing-module-docstring)
foo.py:1:0: C0102: Black listed name "foo" (blacklisted-name)
foo.py:1:0: C0102: Black listed name "bar" (blacklisted-name)
foo.py:1:0: C0116: Missing function or method docstring (missing-function-docstring)
foo.py:3:10: E0602: Undefined variable 'bar_err' (undefined-variable)
foo.py:6:8: C0103: Variable name "b" doesn't conform to snake_case naming style (invalid-name)
foo.py:6:13: E0602: Undefined variable 'bar_err' (undefined-variable)
foo.py:7:14: E0602: Undefined variable 'bz' (undefined-variable)
foo.py:6:8: W0612: Unused variable 'b' (unused-variable)

----------------------------------------------------------------------
Your code has been rated at -21.43/10 (previous run: -14.29/10, -7.14)

```

### Current behavior
Returning just
```
************* Module foo
foo.py:6:14: E0001: EOL while scanning string literal (<unknown>, line 6) (syntax-error)
```

### Expected behavior
Return all the problems:
```
************* Module foo
foo.py:6:14: E0001: EOL while scanning string literal (<unknown>, line 6) (syntax-error)
foo.py:1:0: C0102: Black listed name "foo" (blacklisted-name)
foo.py:1:0: C0114: Missing module docstring (missing-module-docstring)
foo.py:1:0: C0102: Black listed name "foo" (blacklisted-name)
foo.py:1:0: C0102: Black listed name "bar" (blacklisted-name)
foo.py:1:0: C0116: Missing function or method docstring (missing-function-docstring)
foo.py:3:10: E0602: Undefined variable 'bar_err' (undefined-variable)
foo.py:6:8: C0103: Variable name "b" doesn't conform to snake_case naming style (invalid-name)
foo.py:6:13: E0602: Undefined variable 'bar_err' (undefined-variable)
foo.py:7:14: E0602: Undefined variable 'bz' (undefined-variable)
foo.py:6:8: W0612: Unused variable 'b' (unused-variable)

```

### pylint --version output
```
pylint 2.4.4
astroid 2.3.3
Python 3.7.3 | packaged by conda-forge | (default, Dec  6 2019, 08:54:18) 
[GCC 7.3.0]
```

**Comment by PCManticore** [comment]
Hi @marcelotrevisani 

Unfortunately that's not quite possible right now. The `syntax-error` is emitted by the builtin `ast` Python library, which parses the code in order to obtain an abstract tree, on top of which we add various improvements and checks. 

That basically means that if the source file is not parseable, there is not much we can do, since we cannot parse the remainder of the file to build a proper AST out of it. It's possible that there are other parsing libraries out there that are able to work with syntactic errors such as this one, but we cannot switch to another one right now.

Hope that makes sense and thank you for using pylint.

**Comment by marcelotrevisani** [comment]
> Hi @marcelotrevisani
> 
> Unfortunately that's not quite possible right now. The `syntax-error` is emitted by the builtin `ast` Python library, which parses the code in order to obtain an abstract tree, on top of which we add various improvements and checks.
> 
> That basically means that if the source file is not parseable, there is not much we can do, since we cannot parse the remainder of the file to build a proper AST out of it. It's possible that there are other parsing libraries out there that are able to work with syntactic errors such as this one, but we cannot switch to another one right now.
> 
> Hope that makes sense and thank you for using pylint.

I see...
Thanks for your reply!

**Comment by marcelotrevisani** [comment]
@PCManticore  just one more thing, should that error be a ``FATAL`` error then?
According to the documentation:
```
F fatal, if an error occurred which prevented pylint from doing further processing.
```

**Comment by marcelotrevisani** [comment]
Because it is preventing pylint from doing further processing. Does it make sense?
