### ISSUE TITLE
Warn about redundant parentheses

### ISSUE THREAD

**Issue by astier** [PyCQA/pylint#3354]
### Problem

pylint does not warn me about redundant parentheses like `x = (1)`
pycharm does warn me what I like.

### Solution

Introduce a warning about redundant parentheses.

**Comment by PCManticore** [comment]
Hi, thanks for the report. While this would be nice to have, I think you'll be better off using `flake8` or `black` for these kind of formatting issues. We do have various formatting checkers but they are not a priority for `pylint` at this moment.
