### ISSUE TITLE
E1101: Module 'rpm' has no 'RPMTAG_NAME' member (no-member)

### ISSUE THREAD

**Issue by bcl** [PyCQA/pylint#3371]
### Steps to reproduce

On a system (eg. Fedora 31) with the python3-rpm module installed write a simple script:

```
#!/usr/bin/python3
import rpm
print(rpm.RPMTAG_NAME)
```

Run pylint on it:
`pylint-3 ./rpm-test.py`

Observe the error:
```
************* Module test-rpm
/test-rpm.py:4:0: C0305: Trailing newlines (trailing-newlines)
/test-rpm.py:1:0: C0103: Module name "test-rpm" doesn't conform to snake_case naming style (invalid-name)
/test-rpm.py:1:0: C0111: Missing module docstring (missing-docstring)
/test-rpm.py:3:6: E1101: Module 'rpm' has no 'RPMTAG_NAME' member (no-member)
```

I have created a git repo with docker/podman files so it can be easily demonstrated from non-fedora systems:

https://github.com/bcl/pylint-rpm-1739167

rpm is a C module, it populates the constants in the module init with this function:
https://github.com/rpm-software-management/rpm/blob/master/python/rpmmodule.c#L274
using `PyModule_AddIntConstant` if that's of any help.

On rawhide the following package versions are installed:

```
pylint-2.4.4-2.fc32.noarch
  python3-astroid-2.3.3-6.gitace7b29.fc32.noarch
  python3-isort-4.3.21-6.fc32.noarch
  python3-lazy-object-proxy-1.4.3-2.fc32.x86_64
  python3-mccabe-0.6.1-14.fc32.noarch
  python3-pylint-2.4.4-2.fc32.noarch
  python3-setuptools-41.6.0-1.fc32.noarch
  python3-six-1.14.0-1.fc32.noarch
  python3-typed_ast-1.4.1-1.fc32.x86_64
  python3-wrapt-1.11.2-4.fc32.x86_64
  python3-rpm-4.15.1-2.fc32.x86_64
```

**Comment by PCManticore** [comment]
Hi, thanks for the report. We can't do much when dealing with C modules. You can pass `--extension-pkg-whitelist=rpm` to `pylint` which will make it import the module in order to build an AST from it, but that might not be acceptable to you. Otherwise, you can use `--ignored-modules` or `--generated-members` to fake those attributes so `pylint` could skip them.

**Comment by bcl** [comment]
Thanks for the quick response, adding it to the whitelist seems to work fine.
