### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by mernst** [PyCQA/pylint#3376]
The "Python Packages" section of https://docs.pylint.org/en/1.6.0/installation.html doesn't seem to have instructions for installing pylint.
Should
  `python -m pip install pip`
be
  `python -m pip install pylint3`
or
  `python -m pip install pylint`
?

**Comment by PCManticore** [comment]
Thanks for the report! Yeah, it should be `python -m pip install pylint` instead. The 1.6 version is no longer maintained though and the current versions have the proper installation example: http://pylint.pycqa.org/en/2.4/user_guide/installation.html
