### ISSUE TITLE
Suggest to iterate thorough dict items() instead of keys

### ISSUE THREAD

**Issue by EugeneZelenko** [PyCQA/pylint#3389]
It'll be great to recognize loops that could iterate through items() instead of keys.

Example of problematic code pattern:

```
for d in a_dict:
    print(d, a_dict[d])
```

**Comment by PCManticore** [comment]
Thanks for the report!

**Comment by ursmaheshj** [comment]
for d in a_dict.values():
    print(d)

**Comment by yushao2** [comment]
Opened PR #4445 , please take a look :)

There might be some issues as it is my first time contributing and I'm still not 100% sure if I'm doing it right

**Comment by cdce8p** [comment]
> ```py
> for d in a_dict.values():
>     print(d)
> ```

@ursmaheshj Could you explain what you mean, I'm not quite following? At least I can't think of any case where I would use `dict.values` and later access the keys from it. Just to get them, I would need to iterate over all items again and even then can't be sure that it's the right key.

**Comment by ursmaheshj** [comment]
> @ursmaheshj Could you explain what you mean, I'm not quite following? At least I can't think of any case where I would use `dict.values` and later access the keys from it. Just to get them, I would need to iterate over all items again and even then can't be sure that it's the right key.


>@cdce8p  Yeah got it, i think i just misunderstood the issue.

**Comment by craiga** [comment]
Thanks so much for your work here!

An hour ago I was going to log a bug against this change, but it turned out that my code contained an insidious little bug where it wasn't iterating over a data structure as it should've been. Thanks again!
