### ISSUE TITLE
Simplifying assignment operators operation with same variable in left and right hand side of assignment

### ISSUE THREAD

**Issue by EugeneZelenko** [PyCQA/pylint#3391]
It'll be great to have check which will suggest to simplify assignment operators, like "value = value + 1" to "value += 1".

**Comment by elfring** [comment]
:eyes: I am looking for further clarification also according to the general topic “[Increase the usage of augmented assignment statements](https://github.com/PyCQA/pylint/issues/5174 "Better support for augmented assignment statements")”.

**Comment by EugeneZelenko** [comment]
@DanielNoord: Thank you!
