### ISSUE TITLE
Suggesting to use min()/max()

### ISSUE THREAD

**Issue by EugeneZelenko** [PyCQA/pylint#3406]
It'll be great to recognize code patterns that could be replaced with min() and max() functions. For example:

`
if value < 10:
    value = 10
`

with `value = max(value, 10)`

**Comment by Qwiddle13** [comment]
@Pierre-Sassoulas who's the right person to review the pull request?

**Comment by Pierre-Sassoulas** [comment]
Well, at least a contributor with write access with the time to review and anyone with the time to review :)
