### ISSUE TITLE
Simplify Boolean expressions

### ISSUE THREAD

**Issue by EugeneZelenko** [PyCQA/pylint#3407]
It'll be great to have check similar to [Clang-tidy readability-simplify-boolean-expr](https://clang.llvm.org/extra/clang-tidy/checks/readability-simplify-boolean-expr.html), so statements like `os.access(file_name, os.R_OK) is False` would be suggested to be replaced with `not os.access(file_name, os.R_OK)`.

**Comment by PCManticore** [comment]
That would be nice.

**Comment by EugeneZelenko** [comment]
Thank you for help!

**Comment by Pierre-Sassoulas** [comment]
Thank you @ethan-leba :)

**Comment by ethan-leba** [comment]
My pleasure!

**Comment by EugeneZelenko** [comment]
> My pleasure!

Thank you for implementation!
