### ISSUE TITLE
Maximum recursion depth exceeded on simple code

### ISSUE THREAD

**Issue by K900** [PyCQA/pylint#3414]
### Steps to reproduce
1. Install the latest `pylint` version

```
# as of this writing:
astroid==2.3.3
isort==4.3.21
lazy-object-proxy==1.4.3
mccabe==0.6.1
pylint==2.4.4
six==1.14.0
wrapt==1.11.2
```
2. Create a file with the following contents:

```python
k = {}
(_ for k in dict(**k))
```
3. Run `pylint yourfile.py`

### Current behavior

Pylint crashes with "maximum recursion depth exceeded".

### Expected behavior

Pylint does not crash with "maximum recursion depth exceeded".

### pylint --version output

```
pylint 2.4.4
astroid 2.3.3
Python 3.8.1 (default, Jan 22 2020, 06:38:00) 
[GCC 9.2.0]
```

**Comment by K900** [comment]
Interestingly, changing the name of the loop variable to anything other than `k`, e.g. `a` or even `_`, makes this not crash anymore.

**Comment by K900** [comment]
Also interestingly, `k = {}; (_ for k in {**k})` does _not_ crash.

**Comment by K900** [comment]
Also, `_` in the original example seems to be completely irrelevant, as long as it's a valid expression (i.e. not a syntax error). `0 for k in ...`, `None for k in ...`, `k for k in ...`, etc. all crash equivalently.

**Comment by PCManticore** [comment]
Thanks for the report!
