### ISSUE TITLE
No documentation for errors thrown can be found here in a table

### ISSUE THREAD

**Issue by OutsourcedGuru** [PyCQA/pylint#3419]
### Problem
Running pylint throws a barrel-ful of errors which are not found anywhere in your repository. Search for "E302", "E402", for example, and you'd get nothing. Then search any of the authoritative sites like PyPi, python.org or any website which delivers pep8 or pylint and you'll still not find a table of errors-versus-guidance.

### Describe the solution you'd like
Presumably, somewhere in the source code for pylint is an engine which detects what it sees as problems and then reports an error like E302. It would be nice if pylint could provide documentation for that lookup table. Indicating the offending line might work for the first two or three errors since it points to a line number. But once you've started working through the laundry list of errors now the line numbers are all off.

In theory, a link like this could be included in the error response:

https://github.com/PyCQA/pylint/errors.md#E302

**Comment by PCManticore** [comment]
Please search the documentation next time: http://pylint.pycqa.org/en/latest/technical_reference/features.html

Also you can use `pylint --help-msg=<msg id or msg symbol>` to figure out what an error code is supposed to be about.

I don't know from where you got those two error codes, but they are not valid `pylint` codes.

**Comment by OutsourcedGuru** [comment]
@PCManticore You just provided a link to a page which makes no reference whatsoever to magic numbers like E302. That's the suggestion: update your documentation to add the magic number.

![Screen Shot 2020-03-19 at 6 06 13 PM](https://user-images.githubusercontent.com/15971213/77128164-5a93aa00-6a0c-11ea-938f-4a5f4da74066.png)
