### ISSUE TITLE
Pylint hangs when ran on a file[BUG]

### ISSUE THREAD

**Issue by rahulrachh** [PyCQA/pylint#3426]
### Steps to reproduce
1. Go to the "https://github.com/pandas-dev/pandas".
2. Now Download the whole project with the name "pandas-master.zip".
3. Extract the zip file.
3. Now go to "pandas-master\pandas\tseries".
4. Open cmd from that folder and run the following commands.
3. Run the following command in the cmd from that folder:
    1. "pylint --disable=all --enable=W0231 offsets.py"
    2. "pylint --disable=all --enable=W0231,W0233 offsets.py"  
    3.  "pylint --disable=all --enable=W0233 offsets.py"
    4. "pylint offsets.py"

### Current behavior
1. After running command(1), pylint gets stuck on line 1107 giving the error called W0231-(super- 
    init-not-called).
2. After running the command(2) the output is same as above.
3. After running the command(3), the output is nothing and it doesnt give any output.
4. After running the command(4), the ouput scans several lines and gets stuck at line 1198, giving error of W0223 (abstract-method)

### Expected behavior
All the four codes' expected output would be a rating out of 10 that is given after the end of the scanning of file.

### pylint --version output
pylint 2.4.4
astroid 2.3.3
Python 3.7.6 (tags/v3.7.6:43364a7ae0, Dec 19 2019, 00:42:30) [MSC v.1916 64 bit (AMD64)]

**Comment by PCManticore** [comment]
Thanks for the report @rahulrachh

**Comment by rahulrachh** [comment]
Yes same here used the master version and instead of 2.4.4. and it doesn't cause trouble. Thanks.
