### ISSUE TITLE
run unit-tests in a chroot right after build

### ISSUE THREAD

**Issue by pylint-bot** [PyCQA/pylint#343]
Originally reported by: **Anonymous**

----------------------------------------

I'm reporting http://www.logilab.org/ticket/22586

Hello,
in Debian we usually build packages in a clean chroot, with no more than build-depends{,-indep} installed.
In this situation, I'm not able to run unittests, because they import from pylint, which is not available because the packge was just built and not installed.
also setting the PYTHONPATH to build/lib doesn't help.
You can see the full build log attached.

Regards,
Sandro

----------------------------------------
- Bitbucket: https://bitbucket.org/logilab/pylint/issue/343

**Comment by PCManticore** [comment]
Closing. People can use tox if they want to test pylint without installing.
