### ISSUE TITLE
Incorrect answer in FAQ on Python 2 files?

### ISSUE THREAD

**Issue by r3m0t** [PyCQA/pylint#3431]
## Question
Hi, the docs say:

> That is, Pylint 2.X is still able to analyze Python 2 files, but some specific checks might not work, as they would assume that their running environment was Python 2.

Firstly, I get syntax-error when I try to lint a file with a `print` statement. Secondly, how does it assume the running environment is Python 2? I think it means Python 3?

Does that mean that to lint Python 2 and 3 compatible code I need to run both versions of pylint?

**Comment by rahulrachh** [comment]
fdgdgdfgdgdgdgd

**Comment by PCManticore** [comment]
Thanks for the report @r3m0t The documentation is no longer up to date. We do not support Python 2 explicitly with the pylint 2.X release line, but if your code is Python 2/3 compatible, you might still be able to lint it with 2.X. If you need to lint a file with Python 2 specific syntax, I'm afraid that only 1.9.X can be used, but that release line is no longer maintained.
