### ISSUE TITLE
[meta] github required checks misconfigured?

### ISSUE THREAD

**Issue by asottile** [PyCQA/pylint#3449]
it looks like `appveyor/branch` is part of the required checks for merging, however this check will only appear when a branch is pushed directly to `PyCQA/pylint` and not for forks -- I believe the check for PRs is `appveyor/pr`

**Comment by PCManticore** [comment]
Thanks for the issue! This was closed by the protected branches rules which included `continuous-integration/appveyor/branch` for some reason. Once it was removed, all the PRs are properly marked as ready to be merged.
