### ISSUE TITLE
 Module 'dlib' has no 'get_frontal_detector' member pylint

### ISSUE THREAD

**Issue by smane2000** [PyCQA/pylint#3453]
### Steps to reproduce
1.
2.
3.

**Comment by PCManticore** [comment]
I'm sorry, what is even `dlib`? Is this a C extension? If so, you can use `--extension-pkg-whitelist` to tell `pylint` to dynamically import the module to figure out its members. Alternatively you can use `--ignored-modules=dlib` or `--generated-members=dlib.get_frontal_detector`.

**Comment by smane2000** [comment]
Thanx for replying but it's not of c it's of python...dlib is a software library in python which detects the landmarks of face.
