### ISSUE TITLE
Docstring length limit check

### ISSUE THREAD

**Issue by sanjioh** [PyCQA/pylint#3455]
### Is your feature request related to a problem? Please describe
I think it would be nice if pylint could have docstrings checked for max length; that is, if it had distinct limits for code length and docstring length.
That would allow compliance with PEP 257 (which suggests 72 characters as length limit for docstrings), independently of the code length limit enforced.

### Describe the solution you'd like
A new error identifier for docstrings that go beyond their own lenght limit.

### Additional context
I'm not familiar with the codebase, but AFAICT the best place for such check would be the docstyle extension.

**Comment by PCManticore** [comment]
Hey @sanjioh Thanks for the report. I believe this should go in https://github.com/PyCQA/pydocstyle rather than here. We tend to move away from offering pure PEP 8 + PEP 257 checks and other tools such as `pydocstyle` are a better fit for more low level checks like this one.
