### ISSUE TITLE
syntax error 

### ISSUE THREAD

**Issue by ejazfazli** [PyCQA/pylint#3456]
harpconvert -a 'latitude > 33.6570 [degree_north]; latitude < 34.1631 [degree_north]; bin_spatial(271,-55,0.5,721,-180,0.5); derive(latitude {latitude}); derive(longitude {longitude})' r"C:\Users\Ejaz Fazli\Downloads\S5P_OFFL_L2__NO2____20200101T055716_20200101T073846_11490_01_010302_20200102T225627.nc" \r"C:\Users\Ejaz Fazli\Downloads\converted_product.nc"

i dont know whats wrong with this code ?

**Comment by PCManticore** [comment]
I'm sorry, I don't know what this issue is about. Not even sure it's about pylint.

**Comment by ejazfazli** [comment]
this code is giving me a syntax error E0001 while running it on python.
