### ISSUE TITLE
`no-member` check provides random results depending on current directory and other factors

### ISSUE THREAD

**Issue by actionless** [PyCQA/pylint#3477]
### Steps to reproduce

a)
1. `cd /tmp/`
2. `git clone https://github.com/actionless/pikaur.git`
3. `cd ./pikaur`
4. `git checkout 902355ae70a1eeefdafe81b0d53816f9ab66ec29`
5. `pylint pikaur`

```
************* Module pikaur.search_cli
pikaur/search_cli.py:132:19: E1101: Instance of 'PikaurArgs' has no 'positional' member (no-member)

-------------------------------------------------------------------
Your code has been rated at 9.99/10 (previous run: 10.00/10, -0.01)
```

b)
1. `cd /tmp/`
2. `git clone https://github.com/actionless/pikaur.git`
3. `cd ./pikaur`
4. `git checkout 902355ae70a1eeefdafe81b0d53816f9ab66ec29`
5. `pylint pikaur/*`

```
************* Module pikaur.args
pikaur/args.py:333:7: E1101: Instance of 'PikaurArgs' has no 'positional' member (no-member)
pikaur/args.py:333:41: E1101: Instance of 'PikaurArgs' has no 'positional' member (no-member)
pikaur/args.py:334:8: E1101: Instance of 'PikaurArgs' has no 'positional' member (no-member)
pikaur/args.py:335:8: E1101: Instance of 'PikaurArgs' has no 'positional' member (no-member)
************* Module pikaur.info_cli
pikaur/info_cli.py:53:20: E1101: Instance of 'PikaurArgs' has no 'positional' member (no-member)
************* Module pikaur.install_cli
pikaur/install_cli.py:111:37: E1101: Instance of 'PikaurArgs' has no 'positional' member (no-member)
pikaur/install_cli.py:201:12: E1101: Instance of 'PikaurArgs' has no 'positional' member (no-member)

------------------------------------------------------------------
Your code has been rated at 9.92/10 (previous run: 9.92/10, +0.00)
```

c) NOTE: i don't have .pylintrc in home dir
1. `cd ~`
2. `git clone https://github.com/actionless/pikaur.git`
3. `cd ./pikaur`
4. `git checkout 902355ae70a1eeefdafe81b0d53816f9ab66ec29`
5. `pylint pikaur`

```
$ pylint pikaur

-------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 9.99/10, +0.01)
```

### pylint --version output

```
pylint 2.4.4
astroid 2.3.3
Python 3.8.2 (default, Feb 26 2020, 22:21:03)
[GCC 9.2.1 20200130]
```

**Comment by PCManticore** [comment]
Thanks for the report!

I cannot fully reproduce this issue when it comes to the output. The only cases that are different are when running `pylint pikaur` vs `pylint pikaur/*`. The semantics for those commands are different. 

The former analyses the package `pikaur` (thus pylint attempts to figure out on its own the files that composes the package), while the latter reaches pylint as all the files in the `pikaur` directory as expanded by the shell via `*` operator.  

Theoretically it shouldn't be a difference though, and we should be able to emit the `no-member` error. I'm keeping this open for more investigation.

**Comment by actionless** [comment]
yeah, those are two separate issues:

1) `pylint pikaur` vs `pylint pikaur/*` output

2) `pylint pikaur` produce different output depending on different directory (/home/user vs /tmp)

**Comment by Pierre-Sassoulas** [comment]
Closing as stale, lib specific and hard to reproduce.
