### ISSUE TITLE
CheckerTestCase's linter not allow whitelisting the Feature Under Test

### ISSUE THREAD

**Issue by richtier** [PyCQA/pylint#3486]
The `pylint.testutils.CheckerTestCase` uses `pylint.testutils.UnittestLinter`, which changes some behavior in a non transparent way: there is no check to see if messages are enabled/disabled.

As a result `@set_config(disabled=[...])` and `@set_config(enabled=[...])` have no effect.

It would be useful if `@set_config(enabled=[...])` worked during unit tests to avoid noise in the test: `CheckerTestCase.assertAddsMessages` fails if there are more messages than we're testing for.

I tried to do `@set_config(enabled=[...])` to remove that noise but did not work because `UnittestLinter` does not triage against `enabled` or `diasbled`.

### Solutions:
- raise a warning when `@set_config(enabled=[...])` or `@set_config(disabled=[...])` is called; or
- Make UnittestLinter check `disabled` and `enabled`

**Comment by DanielNoord** [comment]
Let's close as `won't fix`. I'll revisit this if somebody desperately needs this. Changes to the configuration parsing have made the use of that decorator different anyway.
