### ISSUE TITLE
Undefined variable for globals()

### ISSUE THREAD

**Issue by kzhui125** [PyCQA/pylint#3511]
```py
globals()['test1'] = 'test1'
globals()['test2'] = 'test2'

print(test1)
print(test2)
```

<img width="573" alt="1" src="https://user-images.githubusercontent.com/11925432/80285967-3c337380-875b-11ea-8d41-b1036f49183d.png">

**Comment by PCManticore** [comment]
Hey @kzhui125 Thanks for the report. Modifying globals and recognising them is not supported by `pylint`.  You can get around with this if you use `--additional-builtins=test1,test2`, but by default `pylint` will not be able to recognise any globals added at runtime.
