### ISSUE TITLE
Imports within TYPE_CHECKING can induce "cyclic-import"

### ISSUE THREAD

**Issue by NeilGirdhar** [PyCQA/pylint#3525]
Suppose you have two modules: a.py and b.py.  `a` imports `b`, but `b` needs `a` in order to do type annotations, then this is usually done by importing `a` within a `TYPE_CHECKING` block.  Unfortunately, this causes pylint to report `cyclic-import`.

Possibly related to https://github.com/PyCQA/pylint/issues/3285

**Comment by ssbarnea** [comment]
Not only this but they can produce very weir errors, ones reported to files that do not have any imports related to the cyclic ones inside, at least with current code from master. I cannot reproduce the problem with v2.6.0 release, but that one has other issues.

**Comment by BobDotCom** [comment]
This issue appears to have been marked as resolved but I'm still running into it on pylint 2.11.1, python 3.9.7. The only thing that seems to fix it is using a block disable.
```py
if TYPE_CHECKING:
    # pylint: disable=cyclic-import
    ...
```Can anyone else confirm if they're experiencing this or if I misinterpreted the status of this issue?

**Comment by Pierre-Sassoulas** [comment]
@BobDotCom any chance you could provide a reproducing example ?
