### ISSUE TITLE
Add check to enforce Python 3 no arguments super call style

### ISSUE THREAD

**Issue by federicobond** [PyCQA/pylint#3541]
Python 3 does not require any arguments in calls to `super`, which helps make code more clear in most cases. While there are still use cases for super with arguments, they are very uncommon in most codebases, and junior devs usually include these arguments unconsciously when copying code from other places or out of habit, which may lead to an inconsistent code style.

It would be great for Pylint to optionally enforce no-argument `super` calls. If this is something that the team would be interested in including, I can write a pull request to review.

**Comment by Pierre-Sassoulas** [comment]
I think this would be a great addition. How would you name it ? `consider-no-args-super`? Looking forward to your pull request!

**Comment by federicobond** [comment]
I'm not really sure how to name it. Is the `consider-X` pattern used in other Pylint checkers? I was thinking something along the lines of `super-with-args`, which describes what it found, not what should be done.

**Comment by Pierre-Sassoulas** [comment]
Yes, there is a lot of `consider-x` in the refactoring part (consider-swap-variables, "consider-using-in", etc.). `old-style-super` sounds great! But I don't think we want to be too assertive if we may have false positive where you really have to give the argument or the code would not work. A less assertive version if the user needs to think about the problem could be `consider-new-style-super`.
