### ISSUE TITLE
Safety library is reporting a vulnerability in `pylint < 2.5.0`

### ISSUE THREAD

**Issue by clintmod** [PyCQA/pylint#3562]
### Steps to reproduce
1. pip install pylint==2.4.4
2. pip install safety
3. safety check

### Current behavior
```
(.venv) 05/01/20 08:52:36.116 ~/c/g/f/t/till-backend (develop|✚1) safety check
+==============================================================================+
|                                                                              |
|                               /$$$$$$            /$$                         |
|                              /$$__  $$          | $$                         |
|           /$$$$$$$  /$$$$$$ | $$  \__//$$$$$$  /$$$$$$   /$$   /$$           |
|          /$$_____/ |____  $$| $$$$   /$$__  $$|_  $$_/  | $$  | $$           |
|         |  $$$$$$   /$$$$$$$| $$_/  | $$$$$$$$  | $$    | $$  | $$           |
|          \____  $$ /$$__  $$| $$    | $$_____/  | $$ /$$| $$  | $$           |
|          /$$$$$$$/|  $$$$$$$| $$    |  $$$$$$$  |  $$$$/|  $$$$$$$           |
|         |_______/  \_______/|__/     \_______/   \___/   \____  $$           |
|                                                          /$$  | $$           |
|                                                         |  $$$$$$/           |
|  by pyup.io                                              \______/            |
|                                                                              |
+==============================================================================+
| REPORT                                                                       |
| checked 164 packages, using default DB                                       |
+============================+===========+==========================+==========+
| package                    | installed | affected                 | ID       |
+============================+===========+==========================+==========+
| pylint                     | 2.4.4     | <2.5.0                   | 38224    |
+==============================================================================+
```

### Expected behavior
No vulnerabilities reported

### pylint --version output
```
(.venv) 05/01/20 08:53:27.713 ~/c/g/f/t/till-backend (develop|✚1) pylint --version
pylint 2.4.4
astroid 2.3.3
Python 3.7.7 (default, Apr  4 2020, 17:54:59)
[Clang 9.0.0 (clang-900.0.39.2)]
```

**Comment by Pierre-Sassoulas** [comment]
We can't fix an old version, 2.4.4 is always going to be unsafe. You should upgrade to `2.5.0`.

**Comment by clintmod** [comment]
@Pierre-Sassoulas why is it unsafe? I couldn't find any info.

**Comment by clintmod** [comment]
pylint 2.5.0 has a regression in so I can't upgrade yet

**Comment by clintmod** [comment]
in case anyone else encouters this… the message is here: https://github.com/pyupio/safety-db/blob/9cb84541a691044512dab8422dc2a36383e0fff3/data/insecure_full.json#L10825

>             "advisory": "Pylint 2.5.0 no longer allows ``python -m pylint ...`` to import user code. Previously, it added the current working directory as the first element of ``sys.path``. This opened up a potential security hole where ``pylint`` would import user level code as long as that code resided in modules having the same name as stdlib or pylint's own modules.",

**Comment by Pierre-Sassoulas** [comment]
As you found out the detail are available with the `--report-full` option of safety :) I don't think we can release a hotfix because one of the regression is actually caused by the fix of this security issue, so we kinda have a deadlock here. As you see the security issue isn't that bad, if you're analyzing your own code. It's more of a problem for someone like codacy that is analyzing other people code. I think you can probably keep using `2.4.4` but you'll be the judge of that.
