### ISSUE TITLE
 R1724 no-else-continue,  Unnecessary "else" after "continue" 

### ISSUE THREAD

**Issue by vlachoudis** [PyCQA/pylint#3574]
Recently updated to  2.4.4-2 and I get the following false-warning in a code like this
R1724 no-else-continue,  Unnecessary "else" after "continue"
```
for i in range(10):
	if i==5:
		print("Skip")
		continue
	else:
		print(i)
	print(i*i)
```

**Comment by Pierre-Sassoulas** [comment]
This is working as intended, your code is equivalent to
```
for i in range(10):
	if i==5:
		print("Skip")
		continue
	print(i)
	print(i*i)
```
