### ISSUE TITLE
Malformed .pylintrc crashes any execution

### ISSUE THREAD

**Issue by ahonnecke** [PyCQA/pylint#3576]
### Is your feature request related to a problem? Please describe
`pylint --version` will fail if the .pylintrc is malformed, this makes reporting an issue with parsing harder as I had to fix the file to get the version

### Describe the solution you'd like
`pylint --version` should print the version, even if the .pylintrc is malformed

### Additional context, this is what I was reporting
https://github.com/PyCQA/pylint/issues/3570

**Comment by Pierre-Sassoulas** [comment]
I can reproduce this on the latest version.
