### ISSUE TITLE
pylint reports no-member errors for some pytables imports

### ISSUE THREAD

**Issue by pylint-bot** [PyCQA/pylint#365]
Originally reported by: **Luke Lee (BitBucket: [durden](http://bitbucket.org/durden), GitHub: @durden?)**

---

Again, this might be related to the implementation in pylint or not, but I've seen no-member warnings when using pytables. I've personally seen the following calls lead to no-member errors in pytables:
- `tables.Float64Col`
- `tables.StringCol`

I would assume all the 'column' types do the same thing because of how they're imported or setup in the pytables project.

---
- Bitbucket: https://bitbucket.org/logilab/pylint/issue/365

**Comment by PCManticore** [comment]
This works in the latest pylint version
