### ISSUE TITLE
pylint can not resolve manually added import path

### ISSUE THREAD

**Issue by liesauer** [PyCQA/pylint#3674]
![image](https://user-images.githubusercontent.com/8676741/84144185-68e0e780-aa8a-11ea-9531-fccc5bcdcf94.png)

**Comment by PCManticore** [comment]
Pylint is not capable of inspecting the `sys.path` modification calls from the source code. You would need to run pylint with `--init-hook="import sys; sys.path.append('your paths go here')"` to be able to make this work.
