### ISSUE TITLE
Since pylint 2.5.0, a report section is no longer produced when jobs!=1

### ISSUE THREAD

**Issue by andy-maier** [PyCQA/pylint#3676]
Since Pylint 2.5.0, generating a report is ignored from either source (`--reports` option, `-r` option, `reports` parameter in rcfile) and treated as if specified with no, when jobs != 1.

### Steps to reproduce
0. Have no pylintrc file
1. echo "abc" >try/abc.py
2. pip install pylint==2.4.4
3. pylint -r y -j 4 try/abc.py
   output includes 3 messages and a report section
4. pip install pylint==2.5.0
5. pylint -r y -j 4 try/abc.py
   output includes only 3 messages but no report section
6. pylint -r y -j 1 try/abc.py
   output includes 3 messages and a report section

### Pylint version (when 2.5.0 was installed)
$ pylint --version
pylint 2.5.0
astroid 2.4.2
Python 3.8.2 (default, Mar 11 2020, 00:28:52) 
[Clang 11.0.0 (clang-1100.0.33.17)]

**Comment by PCManticore** [comment]
This has been fixed with pylint 2.5.3. Please upgrade and let us know if you can still reproduce the problem.
