### ISSUE TITLE
Unexpected keyword argument in constructor call error

### ISSUE THREAD

**Issue by demisx** [PyCQA/pylint#3683]
I have this class defined in https://github.com/wkeeling/selenium-wire/blob/master/seleniumwire/webdriver/browser.py#L53-L92
```py
# Original class
class Chrome(InspectRequestsMixin, _Chrome):
    """Extends the Chrome webdriver to provide additional methods for inspecting requests."""

    def __init__(self, *args, seleniumwire_options=None, **kwargs):
        """Initialise a new Chrome WebDriver instance.

        Args:
            seleniumwire_options: The seleniumwire options dictionary.
        """
        if seleniumwire_options is None:
            seleniumwire_options = {}

        self._client = AdminClient()
        addr, port = self._client.create_proxy(
            port=seleniumwire_options.pop('port', 0),
            proxy_config=seleniumwire_options.pop('proxy', None),
            options=seleniumwire_options
        )

        if 'port' not in seleniumwire_options:  # Auto config mode
            try:
                capabilities = kwargs.pop('desired_capabilities')
            except KeyError:
                capabilities = DesiredCapabilities.CHROME.copy()

            capabilities['proxy'] = {
                'proxyType': 'manual',
                'httpProxy': '{}:{}'.format(addr, port),
                'sslProxy': '{}:{}'.format(addr, port),
                'noProxy': ''
            }
            capabilities['acceptInsecureCerts'] = True

            kwargs['desired_capabilities'] = capabilities

        super().__init__(*args, **kwargs)

    def quit(self):
        self._client.destroy_proxy()
        super().quit()
```

I am instantiating it this way:
```py
driver = webdriver.Chrome( # <-- Unexpected keyword argument 'seleniumwire_options' in constructor call
    executable_path=binary_path,
    desired_capabilities=capabilities,
    seleniumwire_options=options,
)
```

Trying to pass the name param `seleniumwire_options=options` when instantiating this Chrome class results in the following lint error in VS Code. 

![Screen Shot 2020-06-12 at 9 31 24 AM](https://user-images.githubusercontent.com/4452412/84525924-4a990880-ac91-11ea-8e4d-f74f580a2378.gif)

I'd expect there would be no such error. I am new to Python, so it's possible I maybe misunderstanding something. 

### pylint --version output
```
pylint 2.5.3
astroid 2.4.2
Python 3.7.7 (default, Mar 10 2020, 15:43:33) 
[Clang 11.0.0 (clang-1100.0.33.17)]
```

**Comment by zhanghy88** [comment]
hi have the same error on python 3.7.9

Unexpected keyword argument 'start' in constructor callpylint(unexpected-keyword-arg)

**Comment by amiroshn** [comment]
Any news on this one?

**Comment by clavedeluna** [comment]
I've tried to reproduce this but could not, even with a smaller example. Though it's possible since I don't know the definitions of `InspectRequestsMixin, _Chrome` the issue could've come from that?

Is anyone able to reproduce at this time with latest pylint?

**Comment by Pierre-Sassoulas** [comment]
New link to the code is: https://github.com/wkeeling/selenium-wire/blob/master/seleniumwire/webdriver.py#L29

**Comment by clavedeluna** [comment]
Thanks @Pierre-Sassoulas! Even with that new code I cannot reproduce any unexpected keyword arg msg.
