### ISSUE TITLE
Feature request: Add a check for `raise foo from bar`

### ISSUE THREAD

**Issue by cool-RR** [PyCQA/pylint#3687]
I recently went over [Matplotlib](https://github.com/matplotlib/matplotlib/pull/16706), [Pandas](https://github.com/pandas-dev/pandas/pull/32322) and [NumPy](https://github.com/numpy/numpy/pull/15731), fixing a small mistake in the way that Python 3's exception chaining is used. I've done it here too (#3681 )

I suggested to @Pierre-Sassoulas that this should be a PyLint rule.

@jdufresne wrote a flake8 plugin that does this, plus catches two other raise-related issues that I like and could be added as well.

What do you think?

**Comment by PCManticore** [comment]
Sounds like a good idea, thanks for the suggestion!

**Comment by cool-RR** [comment]
I'm working on implementing this feature.
