### ISSUE TITLE
Slow linting on 2.5.3, Travis-CI timing out

### ISSUE THREAD

**Issue by LWprogramming** [PyCQA/pylint#3706]
Recently ran into really slow linting when updating Pylint to version 2.5.x [here](https://github.com/kensho-technologies/graphql-compiler/pull/853). Pylint 2.4.x doesn't make Travis-CI time out, but 2.5.3 does.

[Possibly related](https://github.com/PyCQA/pylint/issues/2519) but this is quite a few minor versions ago.

### Steps to reproduce
Reproduced [here](https://github.com/kensho-technologies/graphql-compiler/pull/854).

### Current behavior
Travis shows: 

```
*** Running pylint... ***

No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
```

### Expected behavior
Not time out. For instance, [853](https://travis-ci.org/github/kensho-technologies/graphql-compiler/builds/700977223) finished in 6 minutes 46 seconds.

### pylint --version output
2.5.3

**Comment by obi1kenobi** [comment]
This major performance regression is also reproducible locally with the same repo — it's not just Travis CI runs that take a really long time.

**Comment by obi1kenobi** [comment]
I ran `pylint==2.5.3` for over two hours on the GraphQL compiler repo referenced above, and it still didn't terminate. For comparison, `pylint==2.4.4` terminates in just a couple of minutes.
```
$ pylint --version
pylint 2.5.3
astroid 2.4.2
Python 3.8.5 (default, Jul 21 2020, 10:48:26) 
[Clang 11.0.3 (clang-1103.0.32.62)]

$ time pylint --rcfile=.pylintrc graphql_compiler/
^C
real    131m12.144s
user    131m9.018s
sys 0m2.527s
```

Is it possible that something in `pylint==2.5.3` is causing an infinite loop?

**Comment by PCManticore** [comment]
Thanks for the reports, it's entirely possible that the latest pylint version has some performance issue.

**Comment by obi1kenobi** [comment]
Thank you for looking into it, much appreciated. I'm not familiar with pylint's codebase but I'm very familiar with GraphQL compiler (the project where this issue arose) so if there's anything related to that project I can do to help track this down, please let me know.

**Comment by obi1kenobi** [comment]
Unfortunately neither of us works at the company or with the codebase where we encountered this issue anymore. In fact I think neither of us really writes Python much anymore :(

**Comment by Pierre-Sassoulas** [comment]
Thank you for the answer @obi1kenobi. I'm going to close as a lot happened performance wise since pylint 2.5.3.
