### ISSUE TITLE
New Logo

### ISSUE THREAD

**Issue by mbarkhau** [PyCQA/pylint#3712]
I thought it would be good for pylint to have a logo that is more iconic. I've made something very rough as an idea, and wanted to guage the apatite for this kind of change before proceeding.

![pylint-logo-new](https://user-images.githubusercontent.com/446561/85928730-b341d100-b89e-11ea-8773-61ae749e07e1.png)

**Comment by mbarkhau** [comment]
Since no feedback is forthcoming, is there perhaps a more appropriate venue for this idea?

**Comment by mnojek** [comment]
It would be good if you write some description of this logo - what it contains and explain why.
