### ISSUE TITLE
Support isort 5

### ISSUE THREAD

**Issue by dekked** [PyCQA/pylint#3722]
Hello,

[isort 5](https://timothycrosley.github.io/isort/docs/major_releases/introducing_isort_5/), a new major release which is very much improved, has just been released.

So far, [it is not possible to install](https://github.com/PyCQA/pylint/blob/master/pylint/__pkginfo__.py#L41) pylint and isort 5 together.

It would be great if pylint could add support for it :)

**Comment by saroad2** [comment]
This is much needed! would love to see this sooner than later.

**Comment by kmsquire** [comment]
Excited to see #3275!

One concrete reason to support `isort` 5 is for compatibility with `black`.  `isort` 4 and `black` conflict with each other slightly (https://github.com/timothycrosley/isort/issues/694), which makes it challenging to use `black` and `isort` 4 (or `pylint`, which depends on `isort` 4) together.

Right now in our code base, we have `isort` 5 and `black` installed, which keeps the formatting consistent, but have `pylint` disabled 😢.

**Comment by limburgher** [comment]
I maintain both isort and pylint for Fedora, and will be happy to test any proposed fixes.

**Comment by saroad2** [comment]
Hey @limburgher, it's seems as this issue has been fixed in #3725

**Comment by limburgher** [comment]
So it has, thank you!

**Comment by saroad2** [comment]
Is there a chance to add this issue to the closest milestone? this issue really important for my use case.

**Comment by sandrotosi** [comment]
For Debian, it would be extremely important to get https://github.com/PyCQA/pylint/pull/3725 merged and a new pylint release cut out soon: isort 5 was uploaded to our archive, so now pylint is getting removed from our users boxes because it conflicts with isort < 5

:(

**Comment by sandrotosi** [comment]
(i tried to adapt the https://github.com/PyCQA/pylint/pull/3725 changes to 2.5.3, but there are too many changes in between)

**Comment by LocutusOfBorg** [comment]
@sandrotosi I did the work, and attached to the Debian RC bug!

**Comment by saroad2** [comment]
Any progress with this issue? I'm stuck in this situation where I need to choose between *pylint* and *isort* because of it.
I cannot use *isort4* because of some bugs it causes in my CI/CD process.

For now, I chose *pylint* over *isort* because it points out a lot of important bugs and really elevates my code, but I really want to use both. I'm a true believer in clean code, and I try to keep my code as clean as possible. Please help me make that happen!

**Comment by adamcunnington** [comment]
This issue was raised over 6 months ago and isort is now at 5.7. How is this not done? What is the eta?
