### ISSUE TITLE
.py file with same name is processed instead of .pyw file

### ISSUE THREAD

**Issue by owillebo** [PyCQA/pylint#3723]
### Steps to reproduce
1. Create 2 files; foo.py and foo.pyw with 2 empty lines (just to trigger a pylint warning)
2. Execute; pylint foo.pyw

### Current behavior
pylint foo.pyw outputs;
************* Module foo
foo.py:1:0: C0305: Trailing newlines (trailing-newlines)
foo.py:1:0: C0102: Black listed name "foo" (blacklisted-name)

Note that foo.py is processed instead of foo.pyw. If foo.py is removed or renamed than pylint does process foo.pyw.

### Expected behavior
pylint processes foo.pyw (not foo.py), i.e.;
************* Module foo
foo.pyw:1:0: C0305: Trailing newlines (trailing-newlines)
foo.pyw:1:0: C0102: Black listed name "foo" (blacklisted-name)

### pylint --version output
pylint 2.5.3
astroid 2.4.2
Python 3.7.8 (tags/v3.7.8:4b47a5b6ba, Jun 28 2020, 07:55:33) [MSC v.1916 32 bit (Intel)]

**Comment by AWhetter** [comment]
I can't reproduce this issue. Might it be the case that `foo` is an installed module and it's reading the source file from there instead?

**Comment by owillebo** [comment]
Thanks,
If I do the same but with files named piet instead of foo I get the same result.

For convenience I created a script;

  @ECHO OFF
  REM ~ Start with an epmty folder.
  RMDIR /S /Q test
  MKDIR test
  PUSHD test
  REM ~ Clear environment.
  SET PYTHONPATH=
  SET PYLINTRC=
  SET PYTHONSTARTUP=
  pylint --version
  ECHO "" > piet.py
  ECHO "" > piet.pyw
  pylint --reports=n piet.pyw
  POPD

Output;

pylint 2.6.0
astroid 2.4.2
Python 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:01:55) [MSC v.1900 32 bit (Intel)]
************* Module piet
piet.py:1:2: C0303: Trailing whitespace (trailing-whitespace)
piet.py:1:0: C0112: Empty module docstring (empty-docstring)
