### ISSUE TITLE
Duplicate code warning unnecessarily triggered on lines that are almost all whitespace

### ISSUE THREAD

**Issue by eli88fine** [PyCQA/pylint#3726]
### Is your feature request related to a problem? Please describe
I use `black` to handle the whitespace of my code automatically.  After black reformats my files, there is often lines with very little non-whitespace characters in them. This then often triggers pylint warnings about duplicate code for sections like the following (which eats up 4 of the lines of the 'similarity limit'...effectively reducing the limit from 5 lines to 1):
`        ]`
`    ),`
`    [`
`        (`

I love the duplicate-code feature of pylint and I don't want to expand the number of 'minimum similarity lines'.  But this seems excessive.

### Describe the solution you'd like
Some sort of metric where the total number of non-whitespace characters needs to exceed some threshold for duplicate-code to be triggered (in addition to the minimum number of lines)

**Comment by AWhetter** [comment]
The similarity checker already strips whitespace (other than newlines). You're right though that it doesn't make sense for it to warn about lines that only have symbols on.

**Comment by eli88fine** [comment]
So would you be open to a Pull Request that somehow makes the Similarity Checker ignore lines that don't match the regex /[a-zA-Z]/ ?

**Comment by eli88fine** [comment]
@AWhetter I created a Pull Request here. All the checks are passing.  This is my first contribution to `pylint`, so let me know if I missed something in the checklist to create an acceptable Pull Request.  https://github.com/PyCQA/pylint/pull/3837
