### ISSUE TITLE
'No name 'QtWidgets' in module 'PyQt5' and 'Unable to import 'PyQt5.QtWidgets' errors in vscode

### ISSUE THREAD

**Issue by KikeSenpai** [PyCQA/pylint#3729]
Hello I am following the suggestion in the link below, about posting new issues for specifics modules in this case PyQt5
https://github.com/PyCQA/pylint/issues/1524#issuecomment-417575208

### Steps to reproduce
I imported the following classes from PyQt5 in order to build a Message Box:
```
from PyQt5.QtGui import QFont
from PyQt5.QtWidgets import (
    QApplication, QWidget, QLabel, QMessageBox, QLineEdit, QPushButton
)
```

Also I have the following setting in my settings.json:

```
"python.linting.pylintArgs": [
        "--extension-pkg-whitelist=PyQt5",
    ]
```

Thanks to this some error messages stopped showing but I still get the following errors in the problems tabs of vscode:

### Current behavior

'No name 'QtWidgets' in module 'PyQt5' 
'Unable to import 'PyQt5.QtWidgets'
'No name 'QtGui' in module 'PyQt5' 
'Unable to import 'PyQt5.QtGui'

### Expected behavior

No errors of this kind

### pylint --version output

pylint 2.5.3 with Python 3.7.3 using the anaconda distributor

**Comment by AWhetter** [comment]
I can't reproduce this issue. Are you sure that the message is coming from pylint and not PyLance or some other part of vscode?
What versions of astroid and PyQt5 do you have?

**Comment by Neighbouring** [comment]
I found the same problem. This problema was solved just with a Virtualenv.

**Comment by bersbersbers** [comment]
Had the same problem with `PySide6` on Linux. Problem seems to have been that system dependencies were not installed. `sudo apt-get -y install xorg libxkbcommon0` helped.

**Comment by RokeJulianLockhart** [comment]
https://stackoverflow.com/q/56726580/9731176 might be useful.

**Comment by JTignor-Raltron** [comment]
> Had the same problem with `PySide6` on Linux. Problem seems to have been that system dependencies were not installed. `sudo apt-get -y install xorg libxkbcommon0` helped.

I had this exact issue migrating to PyQt6, except it was manifesting in my linting github workflows. Your solution worked but Installing xorg and it's dependencies slows the workflow down significantly so I investigated and discovered you could run `sudo apt-get -y install libgl1 libegl1` within that context and speed things up quite a bit.
