### ISSUE TITLE
Detect when an f-string is a plain string

### ISSUE THREAD

**Issue by ethan-leba** [PyCQA/pylint#3730]
### Problem statement
```
variable = f"foo"
```
 Often times when refactoring code it's easy to leave an `f` on a string that doesn't need it. It would be nice if pylint could catch this and display a warning or a refactoring message. 

### Describe the solution you'd like
Essentially the opposite of #2507, but should probably be easier to implement. Raise a warning if an f-string has no expressions.

**Comment by DavidCain** [comment]
Hi, Ethan! This functionality exists on pylint 2.5, under the checker name `f-string-without-interpolation`

From the [release notes](http://pylint.pycqa.org/en/latest/whatsnew/2.5.html#new-checkers):

> This check is emitted whenever pylint detects the use of an f-string without having any interpolated values in it, which means that the f-string can be a normal string.

**Comment by ethan-leba** [comment]
Should’ve checked first, thanks for letting me know!
