### ISSUE TITLE
Some numpy top-level funcs are not ignored even with `ignored-modules=numpy` set

### ISSUE THREAD

**Issue by igozali** [PyCQA/pylint#3736]
### Steps to reproduce
1. Create `pylintrc` file with the following content
```
[TYPECHECK]
ignored-modules=numpy
```
2. Create `test.py`
```py
import numpy as np
xs = np.array([1, 1, 2])
np.unique(xs, return_index=False)
```
3. Run pylint:
```
pylint --rcfile=./pylintrc -E test.py
```

### Current behavior
```
igozali@abcdef $ pylint --rcfile=./pylintrc -E test.py
************* Module test
test.py:3:0: E1123: Unexpected keyword argument 'return_index' in function call (unexpected-keyword-arg)
```

### Expected behavior
No errors since the module `numpy` is supposed to be ignored.

### pylint --version output
```
igozali@abcdef $ pylint --version
pylint 2.5.3
astroid 2.4.2
Python 3.6.4 |Anaconda, Inc.| (default, Mar 13 2018, 01:15:57)
```

**Comment by igozali** [comment]
Checked preview versions and didn't find any newer ones than the above version.

Seems related? https://github.com/PyCQA/pylint/issues/3135

Also the [generated-members trick](https://github.com/PyCQA/pylint/issues/3134#issuecomment-537206429) didn't help since `np.unique` isn't generated...

**Comment by igozali** [comment]
Another data point, downgrading to `pylint==2.3` seems to make it work.

**Comment by AWhetter** [comment]
`ignored-modules` will disable member checks on the module. It does not disable all checks associated with that module.
This looks like an issue with pylint not being able to understand that `np.unique()` takes a `return_index` keyword argument. This is already covered in #3825 so I'm closing in favour of that issue instead.
