### ISSUE TITLE
Do not trigger attribute-defined-outside-init for attributes defined in __enter__

### ISSUE THREAD

**Issue by lcerman** [PyCQA/pylint#3741]
Some context managers do not require `__init__` and all initialization can happen in their `__enter__` when the context manager is entered. However, the linter would complain about it. I would prefer this would be legal or at least separated message that could be disabled independently of `attribute-defined-outside-init`.

**Comment by AWhetter** [comment]
A context manager is like any other class so I think the message is correct.
