### ISSUE TITLE
dummy variables not ignored in nested functions

### ISSUE THREAD

**Issue by molasses11** [PyCQA/pylint#3768]
When writing a nested function, any "dummy" variables that are used are *not* ignored by pylint and give the `unused-variable` warning.

Code to reproduce:

```python
def outer_func():
    def inner_func():
        _, two = (1, 2)  # gets "unused-variable" warning for `_`
        dummy = 1  # also gets "unused-variable" warning
        print(two)
        for _i in range(2):  # same here for `_i`
            print("foo")
    return inner_func
```

pylint version: 2.5.3
asteroid version: 2.4.2
python version: 3.7.8

**Comment by AWhetter** [comment]
I can't reproduce this with the latest pylint. Please could you update and let us know if this is still an issue.
