### ISSUE TITLE
Remaining work from the issue #20

### ISSUE THREAD

**Issue by pylint-bot** [PyCQA/pylint#377]
Originally reported by: **Claudiu Popa (BitBucket: [PCManticore](http://bitbucket.org/PCManticore), GitHub: @PCManticore)**

---

We could try to implement some checks for the following:
-     Exceptions escape except statement
-     Loop variant escapes listcomp
-     list.sort(cmp=..)/sorted(cmp=...)
-     except Exception, exc: ... syntax
-     dict.items() et. al. not in an iterable context or in a list() call
-     Indexing bytes using type inference

---
- Bitbucket: https://bitbucket.org/logilab/pylint/issue/376

*Left to implement in 2018*

- [x]  Exceptions escape except statement
-  [x]  Loop variant escapes listcomp
-  [x]  except Exception, exc: ... syntax

**Comment by PCManticore** [comment]
I think at least `Exceptions escape except statement` would be useful. I'm going through a big Python codebase and stumble upon this one from time to time.
