### ISSUE TITLE
Ignore special argument names on Parameter Documentation checker

### ISSUE THREAD

**Issue by luigibertaco** [PyCQA/pylint#3800]
### Is your feature request related to a problem? Please describe
Yes. Pylint handles special variables names (`_`, `__`, `ignored_`, etc) very well in most cases. However, it doesn't have the same behaviour for *Parameter Documentation checker*.

This code:

```python 
def function_foo(name, _):
    """function foo ...

    Parameters
    ----------
    name: str
        description
    """
    print(name)
```

Will complain about not documenting the parameter "_"

```
************* Module pylint_config
pylint_config.py:1:0: W9015: "_" missing in parameter documentation (missing-param-doc)
pylint_config.py:1:0: W9016: "_" missing in parameter type documentation (missing-type-doc)

------------------------------------------------------------------
Your code has been rated at 0.00/10 (previous run: 0.00/10, +0.00)
```

### Describe the solution you'd like
It would be helpful if the [ignored argument names](https://github.com/PyCQA/pylint/blob/master/pylint/checkers/variables.py#L67-L68) were also ignored on docstrings.

Alternatively, a way for disabling the check for ignored arguments would also work. 

Or even a regex config to be used on `.pylintrc` like:

```
missing-param-doc=^(_) # ignore docs for parameters starting with _
```

**Comment by AWhetter** [comment]
To any new contributors looking to implement this issue, the `pylint.extensions.docparams` extension is responsible for raising this warning. We can use `pylint.utils.get_global_option()` to get the value of the `ignored-argument-names` option. Then `DocstringParameterChecker.check_arguments_in_docstring()` can use the value of the option to add any matching arguments to the ignore lists.
