### ISSUE TITLE
https://pylint.pycqa.org/ keeps redirecting to non-HTTPS link

### ISSUE THREAD

**Issue by alanyee** [PyCQA/pylint#3802]
I am unsure if this repo is the best place to raise this issue, but I have noticed that https://pylint.pycqa.org/ keeps redirecting http://pylint.pycqa.org/en/latest/ which is a HTTP link instead of the HTTPS link https://pylint.pycqa.org/en/latest/. I am unsure what other languages the pylint documentation maintains, but I have been experiencing the problem for English.

**Comment by AWhetter** [comment]
I'm not sure who looks after the domain so I've cross posted this to https://github.com/PyCQA/meta because the maintainers there may know more.

**Comment by graingert** [comment]
The desired redirect pattern is:

http://pylint.pycqa.org -> 301 -> https://pylint.pycqa.org -> 302 -> https://pylint.pycqa.org/en/latest/

**Comment by graingert** [comment]
@AWhetter it looks like this is an RTFD hosted page going via cloudflare?

```
Vary: Accept-Language, Cookie
X-RTD-Redirect: system
X-RTD-Domain: pylint.pycqa.org
X-RTD-Project: pylint
X-RTD-Project-Method: cname
X-RTD-Version-Method: path
```

might be possible to configure using an `.readthedocs.yml`

**Comment by graingert** [comment]
otherwise configurable with a meta-equiv-refresh redirect: https://www.w3.org/TR/WCAG20-TECHS/H76.html or by @logilab and @PCManticore

**Comment by graingert** [comment]
@AWhetter I'd highly recommend porting your rtfd config to `.readthedocs.yml` anyway - see https://github.com/PyCQA/modernize/blob/master/.readthedocs.yml

**Comment by graingert** [comment]
@AWhetter https://docs.readthedocs.io/en/stable/user-defined-redirects.html#exact-redirects

**Comment by AWhetter** [comment]
Thanks for the help @graingert!
@PCManticore only you have permissions so I've assigned this to you, but feel free to give another maintainer permissions as well if you would prefer someone else to complete the work.

**Comment by graingert** [comment]
@AWhetter you can use a meta-equiv-refresh and readthedocs.yml with only repo commit access

**Comment by PCManticore** [comment]
@AWhetter @brycepg @hippo91 @Pierre-Sassoulas Let me know what is your readthedocs handle so I can add you to the project.

**Comment by Pierre-Sassoulas** [comment]
@PCManticore, nice to see you :) My handle on read the doc is `pierre-sassoulas`. It's unrelated but could you also add me to the pypi group so I can publish a new version manually, please ?

**Comment by AWhetter** [comment]
Mine is `AWhetter`

**Comment by hippo91** [comment]
@PCManticore happy to see you again! My handle is hippo91.

**Comment by DanielNoord** [comment]
This is still an issue. Have the readthedocs maintainers been updated? And if so, can this be fixed?
