### ISSUE TITLE
pylint does not detect attributes added via modifying __all__

### ISSUE THREAD

**Issue by pylint-bot** [PyCQA/pylint#382]
Originally reported by: **Emil Sit (BitBucket: [sit](http://bitbucket.org/sit), GitHub: @sit?)**

----------------------------------------

As reported in #58 by @samking:

I suspect that dynamically modifying `__all__` broke support.

I have the same issue with App Engine ndb imports. Eg, I get

    Module 'google.appengine.ext.ndb' has no 'StringProperty' member

when I have

    from google.appengine.ext import ndb
    ndb.StringProperty()

The App Engine __init__.py is available [here](https://code.google.com/p/googleappengine/source/browse/trunk/python/google/appengine/ext/ndb/__init__.py). The members are added dynamically [here](https://code.google.com/p/googleappengine/source/browse/trunk/python/google/appengine/ext/ndb/model.py).

----------------------------------------
- Bitbucket: https://bitbucket.org/logilab/pylint/issue/382

**Comment by PCManticore** [comment]
Fixed by https://github.com/PyCQA/astroid/commit/5f9f8df7aa92981fbb41ea01535c5928ec8c2e08. We should not have this problem anymore, if it is related to ``__all__`` computation.
