### ISSUE TITLE
find_pylintrc doesn't respect --rcfile option

### ISSUE THREAD

**Issue by kontsaki** [PyCQA/pylint#3838]
Hello, i'm trying to setup init-hook to append paths to sys.path so emacs flycheck works correctly when linting while not in the project root directory, i have also tried the steps below with the CLI and the behavior is the same. Adding a `print(find_pytlinrc())` in the init-hook of the file --rcfile is pointing to shows this behavior.

### Steps to reproduce
1. have a `~/.pylintrc`
2. use `find_pylintrc()` in init-hook of the file that `--rcfile` is pointing to
3. use `--rcfile` option to point to a pylintrc file not in the current directory
4. run something like `pylint --rcfile ../../.pylintrc module.py`

### Current behavior
`find_pylintrc()` returns `~/.pylintrc.`

### Expected behavior
`find_pylintrc()` should return the file `--rcfile` is pointing to

### pylint --version output
pylint 2.6.1-dev1
astroid 2.4.2
Python 3.8.2 (default, Jul 16 2020, 14:00:26)
[GCC 9.3.0]

**Comment by kontsaki** [comment]
this also seem to happen when using `pyproject.toml` instead of `pylintrc` even without the `--rcfile` option

**Comment by DanielNoord** [comment]
@kontsaki Is the `find_pylintrc()` function used in emacs for anything? We don't use it internally (anymore) so that might explain why there is a discrepancy. Does it offer any functionality to you?

**Comment by kontsaki** [comment]
Hello, i was using it to point pylint to the project's pylint configuration in cases where pylint run from a different directory than the root of the project. I'm not using this anymore since i always run pylint from project's root now through an lsp.

**Comment by DanielNoord** [comment]
Ah okay! I'm going to close this issue then and going forward with the removal of this function. It doesn't really do what its name suggests and we have better functions to do what people like want with it.

Glad to hear you found another solution!
