### ISSUE TITLE
I am getting some warnings about wrong PATH when installing Pylint on Linux and Windows.

### ISSUE THREAD

**Issue by spirulin** [PyCQA/pylint#3841]
### Steps to reproduce
On Linux
1. Did "sudo apt install python3-pip"
2. then "pip3 install pylint" 
3. gives me the same Warnings as on Windows 10 screenshot but that the things were installed in /home/user/.local/bin which is not the path.

-------------------

On Windows 10 Home 2004 fresh install fully updated I used the VScode to install it ( When it shows pop up that Linter is not installed and you can press Install and it loads the needed code to install it, there got the same Path error).

### Current behavior
![93283029-5dfbc880-f7d8-11ea-8552-fa5ee1e1d924](https://user-images.githubusercontent.com/34941936/93549744-a353fd80-f972-11ea-8eb0-19e176d806b2.png)

### Expected behavior
Not to give these Path warnings. Last time I installed it on fresh install a month ago or so there were no such Warnings.

### pylint --version output

pylint 2.6.0
astroid 2.4.2
Python 3.8.2 (default, Jul 16 2020, 14:00:26) 
[GCC 9.3.0]

**Comment by PCManticore** [comment]
Thanks for the report but I am not entirely sure what this issue is about. About the warnings in yellow? That's not related to `pylint` itself.

**Comment by Ishika-Kanoi** [comment]
Too late, but i'm getting the same error!

Has anyone figured it out yet?
