### ISSUE TITLE
filter OS based imports

### ISSUE THREAD

**Issue by rupakbajgain** [PyCQA/pylint#3847]
suppose i am on linux
how can i do

```
import os

if os.name == 'nt':
     import pywin32
```

i need to turn on some extra features when i am on windows but are not available to linux ,
pyodbc is another library that is needed similar way.

**Comment by hippo91** [comment]
@rupakbajgain is your problem related to `pylint`?

**Comment by rupakbajgain** [comment]
@hippo91 try with pylint ,in linux, i get
```
test.py:4:5: E0401: Unable to import 'pywin32' (import-error)
```
actually there is no such library in linux only on windows.
