### ISSUE TITLE
move doc build checks from travis to readthedocs PR checks

### ISSUE THREAD

**Issue by graingert** [PyCQA/pylint#3850]
Currently builds are checked with tox/travis, but the readthedocs environment is different/more restrictive than travis.

It would be better to have readthedocs build and check the docs for PRs rather than travis: https://docs.readthedocs.io/en/stable/guides/autobuild-docs-for-pull-requests.html

It's probably worth leaving the docs test in tox for local development

![github readthedocs build status report animation](https://docs.readthedocs.io/en/stable/_images/github-build-status-reporting.gif)

**Comment by hippo91** [comment]
@graingert i think it is a good idea. I would like to know what @Pierre-Sassoulas , @AWhetter and @PCManticore think about it.

**Comment by Pierre-Sassoulas** [comment]
Sounds good to me too.

**Comment by graingert** [comment]
steps that are needed:

go here: ​https://readthedocs.org/dashboard/pylint/advanced/#id_external_builds_enabled and tick this box ​![image](https://user-images.githubusercontent.com/413772/94362678-f6395d80-00b4-11eb-875a-3c0fd040fe55.png)

then screenshot the "Default settings" fromset, it should look something like this: ![image](https://user-images.githubusercontent.com/413772/94362748-6f38b500-00b5-11eb-879b-ae7a067660f8.png) I can use that to create a .readthedocs.yml file

then go here ​https://readthedocs.org/dashboard/pytlint/integrations/create/ to double check the webhook is enabled
![image](https://user-images.githubusercontent.com/413772/94532735-278d6700-0236-11eb-996a-e2c90baea895.png)

**Comment by graingert** [comment]
@Pierre-Sassoulas or I can set this up, with admin access to the pylint repo and readthedocs project

**Comment by Pierre-Sassoulas** [comment]
I'm a pylint-admin now, let's do this :D
