### ISSUE TITLE
30% performance regression

### ISSUE THREAD

**Issue by belm0** [PyCQA/pylint#3855]
### Current behavior
on a project with about 50 checks disabled, I observe:

pylint v2.4.4 wall time: 3m15s
pylint v2.6.0 wall time: 4m15s

is it because an existing check got slower?  added checks?

### pylint --version output
```
$ ./venvrun pylint --version
pylint 2.6.0
astroid 2.4.2
Python 3.7.6 (default, Dec 30 2019, 19:38:36)
[Clang 10.0.0 (clang-1000.11.45.5)]
```
```
$ ./venvrun pylint --version
pylint 2.4.4
astroid 2.3.3
Python 3.7.6 (default, Dec 30 2019, 19:38:36)
[Clang 10.0.0 (clang-1000.11.45.5)]
```

**Comment by hippo91** [comment]
@belm0 thanks for the report. Can we have the sources you are linting in order for us to investigate?

**Comment by belm0** [comment]
Unfortunately I can't share the source as it's proprietary.

It would be great if pylint could report the cumulative time spent by each checker.  Then comparing runs we could easily see what has caused a regression (new check vs. existing, etc.).

**Comment by Pierre-Sassoulas** [comment]
It makes sense. We need more tool for performance analysis if we want to be a able to work on it. There's a ticket for that I'll find it later as I'm on mobile right now.

**Comment by hippo91** [comment]
@belmo are you using the similarity reporter? Is your code annotated with generic?
Currently we have two causes for performance problem. One is with inheritance and GenericType annotations, the other deals with the similarity reporter.
If you are using this last one, can you try to run `pylint --disable=RP0801`?
Thanks in advance.

**Comment by belm0** [comment]
We do not have similarity reporter enabled.
At the time of this report there were no Generic definitions.

To be clear, we're looking for a regression rather than a checker that's known to be generally slow.  (E.g. I assume similarity reporter has always been slow.)

**Comment by Pierre-Sassoulas** [comment]
Closing as 2.6.0 went out a long time ago and there isn't much information here, any performance analysis will be more fruitful by direct analysis of the latest code.
