### ISSUE TITLE
detect redundant annotation forward references

### ISSUE THREAD

**Issue by graingert** [PyCQA/pylint#3874]
### Is your feature request related to a problem? Please describe
when moving to non-conditional typing imports, or `from __future__ import annotations` it's often easy to forget to remove annotation forward references

before:
```python
if MYPY:
    from typing import Optional, Tuple, Type, TypeVar
    _E = TypeVar("_E", bound=BaseException)

@attrs.frozen
class ExcInfo:
    _excinfo = attr.ib(type="Optional[Tuple[Type[_E], "_E", TracebackType]]")
```

after:
```python

from typing import Optional, Tuple, Type, TypeVar
_E = TypeVar("_E", bound=BaseException)

@attrs.frozen
class ExcInfo:
    _excinfo = attr.ib(type=Optional[Tuple[Type["_E"], "_E", TracebackType]])
```

note we forgot to remove the forward reference from the `"_E"`!

fixed:
```python
from typing import Optional, Tuple, Type, TypeVar
_E = TypeVar("_E", bound=BaseException)

@attrs.frozen
class ExcInfo:
    _excinfo = attr.ib(type=Optional[Tuple[Type[_E], _E, TracebackType]])
```

### Describe the solution you'd like
detect redundant forward references

### Additional context
Add any other context about the feature request here.

**Comment by hippo91** [comment]
@graingert thanks for this suggestion. It makes sense.

**Comment by cdce8p** [comment]
You could use `pyupgrade` for that. Not sure we need to implement this in pylint, too.
https://github.com/asottile/pyupgrade#remove-quoted-annotations

**Comment by Pierre-Sassoulas** [comment]
I agree, let's close.
