### ISSUE TITLE
Support file url/uri in msg-template

### ISSUE THREAD

**Issue by stefaneidelloth** [PyCQA/pylint#3886]
I would like to be able to click on a hyperlink in the console to open the file where a linting issues occurred.
For that it would be helpful, if I could include the file uri (instead of file path) in the msg-template on windows.

I tried 

msg-template='(file:///{abspath}:{line}) :{column}: {msg_id}: {msg} ({symbol})'

however, that result in something like

(file:///C:\EclipsePython\workspace\...

and the backward slashes \ break the url.

Also see
https://stackoverflow.com/questions/64277280/how-to-format-file-path-in-msg-template-of-pylint-as-url-on-windows

**Comment by hippo91** [comment]
@stefaneidelloth thanks for your report.

**Comment by Pierre-Sassoulas** [comment]
I think it's possible to do, see the answer to the stackoverflow post : https://stackoverflow.com/a/64282107/2519059
