### ISSUE TITLE
Cannot detect imports inside pyz package

### ISSUE THREAD

**Issue by galah92** [PyCQA/pylint#3887]
### Is your feature request related to a problem? Please describe
A clear and concise description of what the problem is.
I'm building and packaging my app using the `zipapp` module to create a `myapp.pyz` app. Then, I'm able to import modules from inside it (in a new python script). `pylint` can't detect these imports and can't search for the code inside.

### Describe the solution you'd like
I'd like `pylint` to support importing from `.pyz` files.

Thanks!

**Comment by hippo91** [comment]
@galah92 thanks for this idea. However i m unable to estimate the amount of work required to achieve this.

**Comment by PCManticore** [comment]
I think this makes sense but it will be mostly handled in `astroid`.
