### ISSUE TITLE
Add bad code smell for open without encoding=

### ISSUE THREAD

**Issue by FredHappyface** [PyCQA/pylint#3897]
### Is your feature request related to a problem? Please describe
A clear and concise description of what the problem is.

Python on Windows defaults to an encoding that differs to the standard utf-8 on other platforms (pretty sure it's code page 1525 or something like that). This often means that my code contains bugs that are only triggered under Windows. Having looked into this, it seems to be a pretty common issue and it looks like PSF are reluctant to set the default to uft-8 on all platforms...

### Describe the solution you'd like

I would very much appreciate it if pylint was willing to add a bad code smell or similar level finding for functions such as open, Popen lacking a user defined encoding 

### Additional context
Add any other context about the feature request here.

Thanks for this fantastic project

**Comment by FredHappyface** [comment]
My bad looks like I missed

https://github.com/PyCQA/pylint/issues/3826

**Comment by hippo91** [comment]
@FredHappyface no pb! :smile:
