### ISSUE TITLE
Pylint Becomes FAST

### ISSUE THREAD

**Issue by leandrogmuller** [PyCQA/pylint#3902]
How can I become the PYLINT more fast.
I need to check sources during development, but the pylint expend 8 seconds to check the source.

**Comment by hippo91** [comment]
@leandrogmuller have you try to run multiple jobs with `-j` option?

**Comment by leandrogmuller** [comment]
Using the -j run on the same time.
Is there any parameter to debug pylint?
I need to check if pylint check occurs with multiprocessing.
I tried -j4 and --jobs=4

**Comment by hippo91** [comment]
@leandrogmuller the best wat to debug `pylint` is to clone the repo and dig into it.
