### ISSUE TITLE
Pylint does not use multprocessing

### ISSUE THREAD

**Issue by leandrogmuller** [PyCQA/pylint#3912]
I'm tring to execute pylint with four process, but it's like using only one process.
A simple command
pylint -j4 --jobs=4 kernel\editor\source_editor.py
The source_editor use many imports, about 37.

pylint 2.6.0
astroid 2.4.2
Python 3.8.5 
pylint -j4 --jobs=4 kernel\editor\source_editor.py

Windows process shows only one process working.
[https://i.ibb.co/1qG68Ry/process.png](url)

**Comment by hippo91** [comment]
@leandrogmuller thanks for the report. Could you try without duplicate between `-j` and `--jobs`:
```
pylint -j4 kernel\editor\source_editor.py
```?

**Comment by leandrogmuller** [comment]
Yes, the same thing happened.

**Comment by hippo91** [comment]
@leandrogmuller thanks for your answer. Have you the possibility to run the same command on another operating system (Linux or MacOS for example)?

**Comment by leandrogmuller** [comment]
I tried on Ubuntu LTS and happened the same.
look.
https://i.ibb.co/hMjGNp7/linux-top.png

The source has many imports.
You can look below my code:

https://github.com/leandrogmuller/coop/blob/main/source_editor.py

**Comment by leandrogmuller** [comment]
I checked the pylint source, the multiprocess work by python file, so, I can't check the source import in another process.
The pylint's source need a update to split process during checking of the import files.

**Comment by hippo91** [comment]
@leandrogmuller you are right if you have only one file to lint the multiprocess work will not help.

**Comment by leandrogmuller** [comment]
I think the check imports don't need to be the same process. If we have 10 imports on module, pylint will get all data info before to check the owner module. So, we could check imports separate process. Or create a cache to modules imports because they not usually change. On big source we have a long time wait the check module.

**Comment by hippo91** [comment]
@leandrogmuller it is probably a good idea but will require a big amount of work. Feel free to dig in and propose a PR. I'll be happy to review it.
