### ISSUE TITLE
Get duplicate errors and a segfault with any value of --jobs != 1

### ISSUE THREAD

**Issue by pbecotte** [PyCQA/pylint#3915]
### Steps to reproduce
1. pylint -j <any number not 1> src_dir

### Current behavior
$ pylint -j 4 srcdir
************* Module oneofmyfiles.
oneofmyfiles.py:51:24: W1309: Using an f-string that does not have any interpolated variables (f-string-without-interpolation)
onefmyfiles.py:51:24: W1309: Using an f-string that does not have any interpolated variables (f-string-without-interpolation)
oneofmyfiles..py:51:24: W1309: Using an f-string that does not have any interpolated variables (f-string-without-interpolation)
oneofmyfiles..py:51:24: W1309: Using an f-string that does not have any interpolated variables (f-string-without-interpolation)
`
lots more errors, reproduced a seemingly random number of times. When i went to reproduce, expected it to just be "4"`

Segmentation fault (core dumped)

### Expected behavior
$  pylint -j 1 henry tests
************* Module oneofmyfiles.
oneofmyfiles.py:51:24: W1309: Using an f-string that does not have any interpolated variables (f-string-without-interpolation)

Your code has been rated at 9.97/10 (previous run: 9.97/10, +0.00)

### pylint version
pylint version:
pylint 2.6.0 (tried with 2.5.3 as well)
astroid 2.4.2

**Comment by hippo91** [comment]
@pbecotte thanks for your report. This issue is very similar to #3584. Thus it should be solved by #3738. I close this issue but feel free to reopen it if needed.

**Comment by pbecotte** [comment]
It does sound like a fix- can't say easily since it's not released. At least having the ticket should help.save the next person some time :)
