### ISSUE TITLE
[Python 3.9 compat] Check for __class_getitem__

### ISSUE THREAD

**Issue by JulienPalard** [PyCQA/pylint#3951]
Python 3.9 starts to make a great use of `__class_getitem__` for exemple in collections.deque.

`pylint/checkers/typecheck.py` should probably look for it to infer if something is subscriptable.

Reproducer:

```python
import collections
print(collections.deque[int])
```

which give:
```
test.py:11:6: E1136: Value 'collections.deque' is unsubscriptable (unsubscriptable-object)
```

while the code works thanks to the `__class_getitem__`.

Related to #3890.
See also #3882.

**Comment by hippo91** [comment]
:+1:

**Comment by cdce8p** [comment]
This seems to be fixed with: https://github.com/PyCQA/astroid/pull/885
So non blocker after an `astroid` update 🎉

**Comment by hippo91** [comment]
@cdce8p :+1:
