### ISSUE TITLE
Is there any Jenkins plugin for pylint results?

### ISSUE THREAD

**Issue by arielman** [PyCQA/pylint#3963]
I have Pipeline which run Jenkinsfile. one of the stage is pylint:
`python -m pylint --rcfile=.pylintrc --exit-zero ${MODULE} > ${WORKSPACE}/testreport/pylint.log`

I know there was used to be violations plugin which is now deprecated. is there any alternative?

**Comment by Pierre-Sassoulas** [comment]
We do not maintain a jenkins plugin here. This is probably a question more suited for something like https://softwarerecs.stackexchange.com/ ;)
