### ISSUE TITLE
Drop support of Python 3.5

### ISSUE THREAD

**Issue by dbaty** [PyCQA/pylint#3965]
Python 3.5 has [reached its end of life](https://www.python.org/downloads/release/python-3510/) (end of September 2020). I think it's time to remove its support in pylint.

The idea has been discussed [here](https://github.com/PyCQA/pylint/issues/3881#issuecomment-710778055) and [there](https://github.com/PyCQA/pylint/pull/3959#issuecomment-735242673) and seems to be approved of. (These 2 issues actually have a few clues as to what could be simplified or removed.)

**Comment by PCManticore** [comment]
Sounds like a good idea.

**Comment by Pierre-Sassoulas** [comment]
That was done in 2.7.0.
