### ISSUE TITLE
Is it possible to make Pylint lint docstrings in C-extensions?

### ISSUE THREAD

**Issue by AndreiPashkin** [PyCQA/pylint#4000]
## Question
Currently Pylint completely ignores presence/absence of docstrings in C-extension modules. I wonder if it's possible to make it lint them or maybe if it's not - would it worth to be implemented in a PR?

**Comment by PCManticore** [comment]
Thanks for opening an issue. Pylint needs access to Python source code files for its checks, so it's not possible to check the presence / absence of docstrings in C-extension modules.
