### ISSUE TITLE
Is there a way to set option for a particular module only?

### ISSUE THREAD

**Issue by karolius** [PyCQA/pylint#4014]
I can use `# pylint: enable=` to enable messages per module and i see there's `init-import` option for config file to check unused imports in init file but i don't know how to enable it for a particular module. Is it currently possible?

**Comment by hippo91** [comment]
@karolius, if you are talking about `init-import` for particular module, to my knowledge there is not yet such possibility.
Maybe @PCManticore can tell more about this subject.
