### ISSUE TITLE
Extract method not working from function with `encoding=` keyword argument

### ISSUE THREAD

**Issue by brand17** [PyCQA/pylint#4029]
### Steps to reproduce
1. Create this code:
```
class my_class():
  def my_method(self, encoding='UTF-8'):
    var = {}
```
2. Select the last line
3. Press right mouse button and choose "Extract Method"

### Current behavior
Raising error:
> Cannot perform refactoring using selected element(s). (Refactor failed. unknown encoding: 
> [<FrameSummary file c:\Users\FA\.vscode\extensions\ms-python.python-2020.12.424452561\pythonFiles\refactor.py, line 380 in watch>, <FrameSummary file c:\Users\FA\.vscode\extensions\ms-python.python-2020.12.424452561\pythonFiles\refactor.py, line 368 in _process_request>, <FrameSummary file c:\Users\FA\.vscode\extensions\ms-python.python-2020.12.424452561\pythonFiles\refactor.py, line 313 in _extractMethod>, <FrameSummary file c:\Users\FA\.vscode\extensions\ms-python.python-2020.12.424452561\pythonFiles\refactor.py, line 128 in refactor>, <FrameSummary file c:\Users\FA\.vscode\extensions\ms-python.python-2020.12.424452561\pythonFiles\refactor.py, line 230 in onRefactor>, <FrameSummary file C:\Users\FA\AppData\Roaming\Python\Python36\site-packages\rope\refactor\extract.py, line 69 in get_changes>, <FrameSummary file C:\Users\FA\AppData\Roaming\Python\Python36\site-packages\rope\refactor\extract.py, line 216 in extract>, <FrameSummary file C:\Users\FA\AppData\Roaming\Python\Python36\site-packages\rope\refactor\extract.py, line 244 in _collect_info>, <FrameSummary file C:\Users\FA\AppData\Roaming\Python\Python36\site-packages\rope\refactor\extract.py, line 304 in _find_definition>, <FrameSummary file C:\Users\FA\AppData\Roaming\Python\Python36\site-packages\rope\refactor\extract.py, line 422 in __init__>, <FrameSummary file C:\Users\FA\AppData\Roaming\Python\Python36\site-packages\rope\refactor\extract.py, line 469 in _create_info_collector>, <FrameSummary file C:\Users\FA\AppData\Roaming\Python\Python36\site-packages\rope\refactor\extract.py, line 806 in _parse_text>, <FrameSummary file C:\Users\FA\AppData\Roaming\Python\Python36\site-packages\rope\base\ast.py, line 16 in parse>, <FrameSummary file C:\Users\FA\AppData\Roaming\Python\Python36\site-packages\rope\base\fscommands.py, line 202 in unicode_to_file_data>])
> 

### Expected behavior
no error

### pylint --version output
2.6.0

**Comment by dbaty** [comment]
It looks like you are using [rope](https://github.com/python-rope/rope), not pylint. What makes you think that this is a pylint issue? If not, I would suggest closing this issue and reporting the bug to the rope maintainers instead.
