### ISSUE TITLE
Extract method not working for files outside of the folder if the line contain `self.`

### ISSUE THREAD

**Issue by brand17** [PyCQA/pylint#4030]
### Steps to reproduce
1. Create a file and save it to the parent directory (outside of the project folder):
```
class my_class():
  def my_method(self):
    self.var = 1
```
2. Select the last line
3. Press right mouse button and choose "Extract method"

### Current behavior
The error raised (looks like pylint looking for a module named as a parent directory):
> Cannot perform refactoring using selected element(s). (Refactor failed. Module Colab Notebooks not found
> [<FrameSummary file c:\Users\FA\.vscode\extensions\ms-python.python-2020.12.424452561\pythonFiles\refactor.py, line 380 in watch>, <FrameSummary file c:\Users\FA\.vscode\extensions\ms-python.python-2020.12.424452561\pythonFiles\refactor.py, line 368 in _process_request>, <FrameSummary file c:\Users\FA\.vscode\extensions\ms-python.python-2020.12.424452561\pythonFiles\refactor.py, line 313 in _extractMethod>, <FrameSummary file c:\Users\FA\.vscode\extensions\ms-python.python-2020.12.424452561\pythonFiles\refactor.py, line 128 in refactor>, <FrameSummary file c:\Users\FA\.vscode\extensions\ms-python.python-2020.12.424452561\pythonFiles\refactor.py, line 230 in onRefactor>, <FrameSummary file C:\Users\FA\AppData\Roaming\Python\Python36\site-packages\rope\refactor\extract.py, line 69 in get_changes>, <FrameSummary file C:\Users\FA\AppData\Roaming\Python\Python36\site-packages\rope\refactor\extract.py, line 216 in extract>, <FrameSummary file C:\Users\FA\AppData\Roaming\Python\Python36\site-packages\rope\refactor\extract.py, line 245 in _collect_info>, <FrameSummary file C:\Users\FA\AppData\Roaming\Python\Python36\site-packages\rope\refactor\extract.py, line 258 in _find_matches>, <FrameSummary file C:\Users\FA\AppData\Roaming\Python\Python36\site-packages\rope\refactor\similarfinder.py, line 101 in get_matches>, <FrameSummary file C:\Users\FA\AppData\Roaming\Python\Python36\site-packages\rope\refactor\similarfinder.py, line 113 in _get_matched_asts>, <FrameSummary file C:\Users\FA\AppData\Roaming\Python\Python36\site-packages\rope\refactor\similarfinder.py, line 155 in find_matches>, <FrameSummary file C:\Users\FA\AppData\Roaming\Python\Python36\site-packages\rope\base\ast.py, line 66 in call_for_nodes>, <FrameSummary file C:\Users\FA\AppData\Roaming\Python\Python36\site-packages\rope\base\ast.py, line 66 in call_for_nodes>, <FrameSummary file C:\Users\FA\AppData\Roaming\Python\Python36\site-packages\rope\base\ast.py, line 63 in call_for_nodes>, <FrameSummary file C:\Users\FA\AppData\Roaming\Python\Python36\site-packages\rope\refactor\similarfinder.py, line 160 in _check_node>, <FrameSummary file C:\Users\FA\AppData\Roaming\Python\Python36\site-packages\rope\refactor\similarfinder.py, line 172 in _check_statements>, <FrameSummary file C:\Users\FA\AppData\Roaming\Python\Python36\site-packages\rope\refactor\similarfinder.py, line 179 in __check_stmt_list>, <FrameSummary file C:\Users\FA\AppData\Roaming\Python\Python36\site-packages\rope\refactor\similarfinder.py, line 221 in _match_stmts>, <FrameSummary file C:\Users\FA\AppData\Roaming\Python\Python36\site-packages\rope\refactor\similarfinder.py, line 204 in _match_nodes>, <FrameSummary file C:\Users\FA\AppData\Roaming\Python\Python36\site-packages\rope\refactor\similarfinder.py, line 197 in _match_nodes>, <FrameSummary file C:\Users\FA\AppData\Roaming\Python\Python36\site-packages\rope\refactor\similarfinder.py, line 185 in _match_nodes>, <FrameSummary file C:\Users\FA\AppData\Roaming\Python\Python36\site-packages\rope\refactor\similarfinder.py, line 228 in _match_wildcard>, <FrameSummary file C:\Users\FA\AppData\Roaming\Python\Python36\site-packages\rope\refactor\similarfinder.py, line 65 in _does_match>, <FrameSummary file C:\Users\FA\AppData\Roaming\Python\Python36\site-packages\rope\refactor\wildcards.py, line 48 in matches>, <FrameSummary file C:\Users\FA\AppData\Roaming\Python\Python36\site-packages\rope\refactor\wildcards.py, line 62 in _check_object>, <FrameSummary file C:\Users\FA\AppData\Roaming\Python\Python36\site-packages\rope\refactor\wildcards.py, line 97 in __init__>, <FrameSummary file C:\Users\FA\AppData\Roaming\Python\Python36\site-packages\rope\refactor\wildcards.py, line 172 in _evaluate>, <FrameSummary file C:\Users\FA\AppData\Roaming\Python\Python36\site-packages\rope\base\project.py, line 59 in get_module>])

### Expected behavior
no error

### pylint --version output
2.6.0

**Comment by dbaty** [comment]
Like #4029, it looks like you are using [rope](https://github.com/python-rope/rope), not pylint. What makes you think that this is a pylint issue? If not, I would suggest closing this issue and reporting the bug to the rope maintainers instead.
