### ISSUE TITLE
Is there any way to set the level of a specific message?

### ISSUE THREAD

**Issue by mikeyjkmo** [PyCQA/pylint#4037]
Hello,

In eslint it's possible to set the level of individual messages. e.g. unused-import can be upgraded from a warning into an error.

Is there any way to achieve this using Pylint?

I can't find anything about this anywhere.

**Comment by hippo91** [comment]
@mikeyjkmo to my knowledge it is not possible but let ask @PCManticore, @Pierre-Sassoulas or @AWhetter .

**Comment by AWhetter** [comment]
This isn't currently possible.

**Comment by Pierre-Sassoulas** [comment]
I also think it's not possible, but you can disable messages, enable messages so if you're using the `--error-only` option you could switch to disabling all warnings, except `unused-import` and removing the `--error-only` option.  You can use `pylint .|grep -o "([a-z\-]*)$"|cut -d "(" -f2|sort|uniq|sed s/\)/,/` to gather them for the disable option in your configuration file.
