### ISSUE TITLE
expression in assignments are evaluated and can cause pylint to run out of memory or time

### ISSUE THREAD

**Issue by jkrinke** [PyCQA/pylint#4041]
### Steps to reproduce
1. Create a file that only contains `v=999999999999999**999999999999999`
2. Run pylon on it.

### Current behavior

Pylint seems to evaluate the expression of the assignment which will take a very long time and in the end will run out of time.

### Expected behavior

Pylint should not attempt evaluation expressions.

### pylint --version output

pylint 2.6.0
astroid 2.4.2
Python 3.8.6 (default, Sep 28 2020, 04:41:02) 
[Clang 11.0.3 (clang-1103.0.32.62)]

**Comment by hippo91** [comment]
@jkrinke thanks for this report. However i'm not sure this is really an issue.
`astroid`, the inference engine used by `pylint`, has to evaluate some simple expression to be able to infer correctly more complex expressions. Moreover if `plyint` takes a long time to evaluate, then `python` will do so.
It may be interesting to monitor this execution time and raise a warning if it takes too much time.

**Comment by jkrinke** [comment]
@hippo91 the behaviour is problematic in a CI/CD setting where one expects that a static analysis tool would not crash (run out of memory) or not terminate.

I am currently running pylint on the above file. After 48h of run time, the process now uses 4GB of main memory.  I expect that the machine would come to a grinding halt within 96h of run time.  Let's assume an extremely fast processor - then pylint would crash running out of main memory within a short time.  I would consider this a bug...

**Comment by jkrinke** [comment]
It may be a problem of Python 3 in general: https://stackoverflow.com/questions/34113609/why-does-python-preemptively-hang-when-trying-to-calculate-a-very-large-number

**Comment by hippo91** [comment]
@jkrinke it seems indeed that it is not related to `pylint`. 
I close the issue but will reopen it if needed.
