### ISSUE TITLE
format-string inconsistencies and bugs

### ISSUE THREAD

**Issue by thisch** [PyCQA/pylint#4042]
At work we stumbled upon a bug in an old code, that used `%` formatting, but the fmt string was wrong, because it didn't contain any replacement fields. It would be nice if pylint could warn about format strings without any replacement fields.

### Current behavior

```py
def demo(param):
    print("1asfasfdsf dasfdadfsdf" % param)  # no warning (code like this line was used in our code-base)
    print("2asfasfdsf dasfdadfsdf" % ())  # no warning
    print("3asfasfdsf dasfdadfsdf" % [])  # pylint outputs too-many-format-args

    # this line raises when you run the script using cpython
    print("4asfasfdsf dasfdadfsdf" % None)  # pylint outputs too-many-format-args

demo(())
```

```
demo.py:4:10: E1305: Too many arguments for format string (too-many-format-args)
demo.py:7:10: E1305: Too many arguments for format string (too-many-format-args)
```

When using `.format` the behavior is a bit different (both in cpython as well as in pylint)

```py
def demo(param):
    print("1asfasfdsf dasfdadfsdf".format(param))  # pylint outputs too-many-format-args
    print("2asfasfdsf dasfdadfsdf".format(()))  # pylint outputs too-many-format-args
    print("3asfasfdsf dasfdadfsdf".format([]))  # pylint outputs too-many-format-args
    print("4asfasfdsf dasfdadfsdf".format(None))  # pylint outputs too-many-format-args

demo(())
```

Contrary to the first example, this one doesn't raise an exception when you run it using cpython. However, pylint considers all print  function calls as invalid, which is wrong, because cpython doesn't raise.

```py
demo_usint_dot_format.py:2:10: E1305: Too many arguments for format string (too-many-format-args)
demo_usint_dot_format.py:3:10: E1305: Too many arguments for format string (too-many-format-args)
demo_usint_dot_format.py:4:10: E1305: Too many arguments for format string (too-many-format-args)
demo_usint_dot_format.py:7:10: E1305: Too many arguments for format string (too-many-format-args)
```

### Expected behavior

I don't understand why python supports format strings without any replacement fields. Maybe because if the fmt string and the args passed to e.g. `.format` are determined dynamically.

**Anyway, I think pylint should output an error (e.g. `bad-format-string`) if the format string is a string without any replacement fields** (as in the examples above).

Things I want to mention but I don't care about them:
 
There is an inconsistency between lists and tuples if used as format string args:

```py
    print("2asfasfdsf dasfdadfsdf" % ())  # no warning
    print("3asfasfdsf dasfdadfsdf" % [])  # pylint outputs too-many-format-args
```

There are differences between `%` formating and `.format` formatting in pylint.

### pylint --version output

```
pylint 2.6.0
astroid 2.4.2
Python 3.8.6 | packaged by conda-forge | (default, Oct  7 2020, 19:08:05) 
[GCC 7.5.0]
```

**Comment by hippo91** [comment]
@thisch thanks for this report. It makes sense.
