### ISSUE TITLE
pylint in GitHub Actions. Result is right, but exit-code is non-zero

### ISSUE THREAD

**Issue by krisstinkou** [PyCQA/pylint#4046]
## Question

I have simple Django-poject in repositories. I used pylint for checking my project. On my local mashine pylint shows me all warnings, here is no problem. I tried start pylint in workflow and what I see:

```
...
 -----------------------------------
Your code has been rated at 1.82/10

Error: Process completed with exit code 30.
```
Workflow failed.
In workflow file:
```
      - name: Install dependencies
        run:
          python -m pip install --upgrade pip
          pip install pylint
      - name: Lint with pylint
        run:
          pylint hrm/*
```
Project structure:
**my_project_folder
|_hrm (contains django-project files, python files)
|_same-files**

<details>
<summary>Full output</summary>
<code style="white-space: nowrap">

Run pylint hrm/*

************* Module department_app.admin
hrm/department_app/admin.py:1:0: C0114: Missing module docstring (missing-module-docstring)

hrm/department_app/admin.py:1:0: E0401: Unable to import 'django.contrib' (import-error)

hrm/department_app/admin.py:1:0: W0611: Unused admin imported from django.contrib (unused-import)

************* Module department_app.apps

hrm/department_app/apps.py:1:0: C0114: Missing module docstring (missing-module-docstring)

hrm/department_app/apps.py:1:0: E0401: Unable to import 'django.apps' (import-error)

hrm/department_app/apps.py:4:0: C0115: Missing class docstring (missing-class-docstring)

hrm/department_app/apps.py:4:0: R0903: Too few public methods (0/2) (too-few-public-methods)

************* Module hrm.asgi

hrm/hrm/asgi.py:12:0: E0401: Unable to import 'django.core.asgi' (import-error)

************* Module hrm.wsgi

hrm/hrm/wsgi.py:12:0: E0401: Unable to import 'django.core.wsgi' (import-error)

************* Module hrm.urls

hrm/hrm/urls.py:16:0: E0401: Unable to import 'django.contrib' (import-error)

hrm/hrm/urls.py:17:0: E0401: Unable to import 'django.urls' (import-error)

************* Module manage

hrm/manage.py:11:8: C0415: Import outside toplevel (django.core.management.execute_from_command_line) (import-outside-
toplevel)

-----------------------------------
Your code has been rated at 1.82/10

Error: Process completed with exit code 30.
</code>
</details>

I don't understand.

**Comment by dbaty** [comment]
I am not sure I understand. Are you saying that the output is literally 3 dots and that pylint warnings do _not_ appear ? Can you provide the full output of that step?

Tip: use this snippet to report the output here if it is large (and check with the "Preview" tab):

```
<details>
<summary>Full output</summary>
<code style="white-space: nowrap">Paste the output here</code>
</details>
```

**Comment by krisstinkou** [comment]
I updated question. Thx for tip, useful feature :)

**Comment by dbaty** [comment]
If I understand correctly, you are wondering about the "Error: Process completed with exit code 30." message.

It comes from GitHub Action itself. It says that pylint exited with a non-zero exit code (i.e. a non-success exit code). This is expected when pylint detects warnings.

**Comment by krisstinkou** [comment]
Thank you very much! It works! I lost 2 days for fix it. Now workflows execute succesfull.
