### ISSUE TITLE
New release for Python 3.9?

### ISSUE THREAD

**Issue by juliangilbey** [PyCQA/pylint#4055]
At the moment, the latest pylint release (2.6.0) is hundreds of commits behind `master`; is there a plan to release a newer version in the near future?

Thanks for all your work on this!

**Comment by Pierre-Sassoulas** [comment]
We're going to release in the near future, we need to merge https://github.com/PyCQA/astroid/pull/890 first, then all the pylint's approved merge request that are blocked by it.

**Comment by Pierre-Sassoulas** [comment]
We released astroid 2.5, and started to merge the current approved merge request. We're going to continue doing that and also check what is causing #4093

**Comment by Pierre-Sassoulas** [comment]
I cleared the MR log, but I think the main problem is the max recursion error that make pylint slow or even make it crash. Are you confident about the genuinely large recursion in the current version of astroid @hippo91 ? Seeing the discussion in #4106 (freeze in debian just started), we might want to release this week if we want to have a working pylint for python 3.9 in the latest debian.

**Comment by hippo91** [comment]
@Pierre-Sassoulas i noticed two kinds of problems. One deals with long execution time and seems to be linked to Generic types. The second deals with infinite recursion but seems to occur only when pandas object have to be inferred. Am i correct?

**Comment by Pierre-Sassoulas** [comment]
I reached this conclusion too after checking (some of) the recursion issues and performance issues. Another thing to consider is that 2.6.0 suffer from the same problem, so maybe it's not a show stopper for releasing 2.7.0 ? Especially considering that astroid 2.5 got better for a lot of cases except pandas and 2.6.2 is not compatible with astroid 2.5 ?

**Comment by hippo91** [comment]
@Pierre-Sassoulas totally agree with you!

**Comment by Pierre-Sassoulas** [comment]
Let's release 2.7.0 today then ? We'll then have 2 weeks to fix the crash and bugs that might appear so pylint can be packaged into debian 😄

**Comment by cdce8p** [comment]
> Let's release 2.7.0 today then ? We'll then have 2 weeks to fix the crash and bugs that might appear so pylint can be packaged into debian 😄

Sounds good. Should we update the astroid dependency?

https://github.com/PyCQA/pylint/blob/34cce21d29f9692a34fec22a76bee70939e628a5/pylint/__pkginfo__.py#L43

I would suggest using `~=2.5` for pylint 2.7. That way we track the Bugfix branch of astroid.
Once it is released, we could update it again on the master branch to `>2.5.0`.

Should also update this here, to follow the 2.5 branch

https://github.com/PyCQA/pylint/blob/34cce21d29f9692a34fec22a76bee70939e628a5/requirements_test_pypy.txt#L1

I plan on updating the Github Action caching algorithm today to account for the different astroid branch. At the moment the cache key is always based of of `master`.

**Comment by cdce8p** [comment]
Opened a MR to update the `astroid` dependency: #4111

**Comment by Pierre-Sassoulas** [comment]
pylint `2.7.0` has just been released and should be compatible with python 3.9 :)

**Comment by cdce8p** [comment]
@Pierre-Sassoulas Thanks for doing the release! I was just testing the new version on another project and noticed that https://github.com/PyCQA/astroid/issues/905 might be more of an issue than we though. Especially since we pinned the astroid version.

@hippo91 I haven't looked at the issue in detail yet, but what would be necessary to fix it?

**Comment by hippo91** [comment]
@Pierre-Sassoulas thanks for the release!
@cdce8p honestly i do not have any idea about the problem. I just think that reverting the faulty commit is not a solution.
I will try to have a look ASAP but it won t be before next week-end i think.

**Comment by juliangilbey** [comment]
Thanks for your work on this, everyone!  @sandrotosi has got it into Debian testing in time for the new release!  Hugely appreciated :+1:
