### ISSUE TITLE
Can not disable broad-except on v2.6.0

### ISSUE THREAD

**Issue by iulianbarbu** [PyCQA/pylint#4063]
### Steps to reproduce
`test.py`:
```
"""Module docstring."""

# pytest: disable=W0703
def raise_exception():
    """Raise exception."""
    try:
        raise Exception("bla")
    except Exception as err:  # pytest: disable=W0703
        print(err)

```
### Current behavior
I constantly get while running `pylint test.py`:
```
************* Module test
test.py:8:11: W0703: Catching too general exception Exception (broad-except)

------------------------------------------------------------------
Your code has been rated at 8.00/10 (previous run: 8.00/10, +0.00)
```
### Expected behavior
I expect `# pytest: disable=W0703` to disable the lint rule.

### pylint --version output
pylint 2.6.0
astroid 2.4.2
Python 3.6.9 (default, Oct  8 2020, 12:12:24) 
[GCC 8.4.0]

**Comment by dbaty** [comment]
You made a typo in your comment. It should start with `# pylint` ("py**lint**", not "py**test**").

**Comment by iulianbarbu** [comment]
Huh, indeed. Thanks  a lot! Closing this.
