### ISSUE TITLE
Add check for redundant u prefixed string in Python 3

### ISSUE THREAD

**Issue by federicobond** [PyCQA/pylint#4102]
### Is your feature request related to a problem? Please describe

In Python 3, the `u` prefix is no longer necessary to indicate that a string is unicode, but some programmers may put it there out of habit or because they copied the code from somewhere else.

### Describe the solution you'd like

Pylint should flag instances of u-prefixed strings in Python 3 with the `redundant-string-prefix` code.

---

I can contribute this check if there is interest in it.

**Comment by Pierre-Sassoulas** [comment]
This sound reasonable; maybe `redundant-u-string-prefix` would be clearer ?

**Comment by Pierre-Sassoulas** [comment]
This sound reasonable; maybe redundant-u-string-prefix would be clearer ? Also, this should probably tell the user to run 2to3 because I think 2to3 removes that prefix. Maybe the reason why the check is not implemented yet in pylint ?

**Comment by federicobond** [comment]
> This sound reasonable; maybe redundant-u-string-prefix would be clearer ? 

I was thinking about leaving the door open to check for f-strings without interpolation and maybe other cases.

> Also, this should probably tell the user to run 2to3 because I think 2to3 removes that prefix. Maybe the reason why the check is not implemented yet in pylint ?

For projects that have already been translated to Python 3, 2to3 is not very useful and I believe many would prefer to just remove the prefix manually once it's flagged by the linter.

**Comment by Pierre-Sassoulas** [comment]
Ok, it makes sense for those that did not run 2to3 in the past.

We already have a message for `f-string` without interpolation :) : `W1309: Using an f-string that does not have any interpolated variables (f-string-without-interpolation)`

**Comment by DanielNoord** [comment]
You can assign this to me. However, I would like to have #4787 first because I would include it in the `visit_const` function add on line 903 there.
