### ISSUE TITLE
Benchmark tests broken on master and 2.7.0

### ISSUE THREAD

**Issue by Pierre-Sassoulas** [PyCQA/pylint#4119]
### Steps to reproduce

    pip3 install -r requirements_test.txt
    python3 -m pytest . -k test_baseline_benchmark_j1_all_checks_lots_of_files

I think this is due to the fact that we're not launching those test on Github Actions we should launch them once (so test are fasters in general).

**Comment by Pierre-Sassoulas** [comment]
This one was tricky to bisect because the problem is the version of astroid (6e2de8e3a2e2c5586e876ca305f0844bdd822db3).

I ended up using `pip3 uninstall pylint astroid;pip3 install "astroid==2.4.2";pip3 install -e . -U;python3 -m pytest -k test_baseline_benchmark_j1_all_checks_lots_of_files` as test. 

Fixed by putting `    "astroid>=2.4.0,<=2.6",` back in the documentation. Broken again by putting `astroid>=2.5.0`

It means astroid `2.5.0` is breaking this benchmark test. Do you have an idea why @hippo91 ? Should I open a bug in astroid ?

**Comment by hippo91** [comment]
@Pierre-Sassoulas please open a new issue on astroid side. I will try to have a look ASAP. Sorry for this...

**Comment by Pierre-Sassoulas** [comment]
I bissected the problem in astroid and opened https://github.com/PyCQA/astroid/issues/909
