### ISSUE TITLE
Improve NaN-comparison checker to support inferred name of numpy library

### ISSUE THREAD

**Issue by orSolocate** [PyCQA/pylint#4124]
### Is your feature request related to a problem? Please describe
nan-comparison checker #3966 support for numpy right now is naïve and incomplete because it expliciltly only support names `numpy`, `nmp` and `np` as in the implementation:

`node.expr.name in ("numpy", "nmp", "np")`

The more elegant way to ask if a comparison node is numpy's NaN using astroid is to check if the variable inferred name is `numpy`. this way import with any name would work, e.g. `from numpy import npy`

### Describe the solution you'd like
I want to change the `_is_numpy_nan` func to this:
```py
  def _is_numpy_nan(node):
            if isinstance(node, astroid.Attribute) and node.attrname == "NaN":
                if isinstance(node.expr, astroid.Name):
                    # return node.expr.name in ("numpy", "nmp", "np")
                    inferred_module = next(node.expr.infer())
                    if isinstance(inferred_module, astroid.Module) and inferred_module.name == "numpy":
                        return True
            return False
```

### Additional context
There is a bug in the tox environement that it does not include numpy. It causes an error when you try to infer to numpy library. it has to be fixed before integrating the new implentation. refer to conversation in #3966

**Comment by orSolocate** [comment]
@PCManticore  Could you have a look at the conversation with hippo91 regarding this environment change with tox. and let me know if you want to make to change?

**Comment by orSolocate** [comment]
@Pierre-Sassoulas  Any update regarding this change? If not clear I could explain again..

**Comment by Pierre-Sassoulas** [comment]
I don't think we should start adding dependencies to external lib, even numpy, during our tests, is there really no other way to make it works ?

**Comment by orSolocate** [comment]
@Pierre-Sassoulas  look at #3966 hippo91's comment (on JAN 1) .
The question is do you want to fully support numpy.nan for NaN comparison but have the overhead of adding numpy dependency, or do you prefer to keep a partial simple implementation and avoid this overhead.
I think that to answer that we need to understand if there are any new checkers we want to add regarding the use of numpy.

**Comment by Pierre-Sassoulas** [comment]
We're (@cdce8p and me) thinking about adding a single github actions with dependencies. Black does check against popular lib with black-primer so there's a precedent. Also the amount of numpy errors we get is too damn high(.jpg) so checking against it seems reasonable after all.

**Comment by orSolocate** [comment]
@Pierre-Sassoulas  Okay so decided to leave checker implementation as it is? close the issue?

**Comment by Pierre-Sassoulas** [comment]
Hello, regarding the check itself, I think we should probably check the performance implication of this change because right now while yes the check is naive and do not work on all cases, it's also computationally cheap and sufficient in most cases. (I never personally saw a tutorial with numpy imported as something other than np or numpy). 

Regarding popular dependencies installed during tests (numpy, pandas, lxml...), I'm for adding a specific job with them, because it will prevent a lot of problem with popular libraries.

**Comment by orSolocate** [comment]
@Pierre-Sassoulas  - if the tox environment does not include `numpy` than this issue should be considered closed (NO DO).

**Comment by Pierre-Sassoulas** [comment]
We discussed recently the possible creation of a ``pylint-numpy`` plugin so the specificity of numpy are handled somewhere else than in pylint / astroid. Would you be interested in maintaining such a plugin @orSolocate ? (See https://github.com/PyCQA/astroid/issues/1312)

**Comment by orSolocate** [comment]
@Pierre-Sassoulas  So the `pylint-numpy` would have numpy in its environemnt obviously and will use pylint infrastructure? just without the checkers? and it will have only it's numpy specific checkers?
Like the user would run 2 commands `pylint` and `pylint-numpy` the check their code?

**Comment by Pierre-Sassoulas** [comment]
I think it should override some checker to add specific behavior, and register a properly maintained numpy brain for astroid. But the way to use pylint should not change. It's just additional plugin if you use numpy, marshmallow, etc.

**Comment by orSolocate** [comment]
@Pierre-Sassoulas  I don't think I can commit for something like that right now.. but some new Pylint checkers are on the plan..

I close it for now..
