### ISSUE TITLE
empty_comment errors reduces reported score by too much

### ISSUE THREAD

**Issue by orSolocate** [PyCQA/pylint#4156]
### Steps to reproduce
1. open `empty_comment,py` unit-test data file path in terminal at: `tests/extensions/data/empty_comment.py`

2. run Pylint with the empty-comment extension #3870:
`pylint --load-plugins=pylint.extensions.empty_comment empty_comment.py`

3. Watch Pylint output in the console.

### Current behavior
************* Module empty_comment
empty_comment.py:2:0: R2044: Line with empty comment (empty-comment)
empty_comment.py:3:0: R2044: Line with empty comment (empty-comment)
empty_comment.py:5:0: R2044: Line with empty comment (empty-comment)
empty_comment.py:7:0: R2044: Line with empty comment (empty-comment)

-----------------------------------
Your code has been rated at 3.33/10

--> Score is very low!

### Expected behavior
Since this error is of type Refactor, you would expect it would not reduce the score by that much.

### pylint --version output
pylint 2.8.0-dev1
astroid 2.5
Python 3.7.5 (tags/v3.7.5:5c02a39a0b, Oct 15 2019, 00:11:34) [MSC v.1916 64 bit (AMD64)]

**Comment by orSolocate** [comment]
I wrote the checker so I could fix it. Just let me know what `priority` value to put. right now the priority level is `-1` which is very high. should `-5` be good enough?

**Comment by orSolocate** [comment]
@Pierre-Sassoulas  you agree with the change?

**Comment by Pierre-Sassoulas** [comment]
Yes, but I think this is something that should be fixed with #2399. I don't think there is a specific checker to do ? Also what does the priority have to do with the score ? Isn't it the message type that has an influence ? (Error being *5 right now and all the other * 1)

**Comment by orSolocate** [comment]
@Pierre-Sassoulas  Yeah you are right the priority is for the linter to figure out how to order the checkers in a 'run queue'. doesn't affect the score. The message type `R` seems to be right for me for this checker. Might be related to the score calculation bug you mentioned. 
You could close this issue.

**Comment by Pierre-Sassoulas** [comment]
Thanks for your input, I'm closing in favor of #2399
