### ISSUE TITLE
Pyreverse output directory

### ISSUE THREAD

**Issue by t4n1o** [PyCQA/pylint#4159]
Could pyreverse (included with pylint) please have an option to choose an output directory?

I wrote a script that auto-generates UML diagrams for each .py file in my package, but then I have to copy them one by one with shutil.move(), because you don't have an option to specify the output path in pyreverse. (Only the output format).

Also I'm not the only one who needs this feature:
https://stackoverflow.com/questions/48689311/pyreverse-how-to-set-output-directory-for-generated-diagrams

**Comment by t4n1o** [comment]
Example use case:
https://gist.github.com/t4n1o/87a8949589e1aefd6542f1887fd654d3

It would be easier if we could specify the output path and didn't have to copy every single file into the documentation folder.

**Comment by Pierre-Sassoulas** [comment]
Make sense, thank for opening the issue.

**Comment by matusvalo** [comment]
@Pierre-Sassoulas shouldn't be closed this MR?

**Comment by Pierre-Sassoulas** [comment]
Good catch, I thought  it was done automatically during merge.
