### ISSUE TITLE
Make it possible to allow lower case enum names

### ISSUE THREAD

**Issue by libre-man** [PyCQA/pylint#4181]
### Is your feature request related to a problem? Please describe
With #3834 enums are now required to be in all caps, and seem to be treated equal to normal constants. However, existing code bases can't simply change all enum values, as this backwards incompatible, and adding an ignore to each member is a lot of noise.

### Describe the solution you'd like
Add a new regex or option to change the allowed way enum values can look

**Comment by cdce8p** [comment]
I agree. Adding a new naming style might be the way to go. Maybe something like `--class-const-naming-style`. This could also be applied to class attributes annotated with `Final`. @Pierre-Sassoulas What do you think?

**Comment by Pierre-Sassoulas** [comment]
Makes sense !

**Comment by cdce8p** [comment]
Opened #4185 to add `--class-const-naming-style`
