### ISSUE TITLE
Migration to pyproject.toml

### ISSUE THREAD

**Issue by Pierre-Sassoulas** [PyCQA/pylint#4193]
The packaging of pylint is a little dated, old files are kept and do not serve any purpose anymore (debian packaging is done elsewhere). The information are in multiple places and we still have a compatibility with distutils when it has been replaced by setuptools a long time ago. This might benefit from a little poetry 😉 

### Additional context
https://github.com/PyCQA/pylint/issues/3686#issuecomment-791688280

**Comment by Pierre-Sassoulas** [comment]
We migrated to setuptools and cleaned a lot of thing, I think this is good enough for now.

**Comment by cdce8p** [comment]
> We migrated to setuptools and cleaned a lot of thing, I think this is good enough for now.

I fully agree. `setuptools` seem to work fine. Using `poetry` would mean that current devs need to change their requirements / environment handling and might alienate some. Without a clear advantage, I wouldn't recommend changing.
