### ISSUE TITLE
tox -e pylint failing

### ISSUE THREAD

**Issue by pkolbus** [PyCQA/pylint#4201]
Commit 6721cd1c causes a failure in the `pylint` testenv under `tox`.

### Steps to reproduce

1. Check out commit 6721cd1c
2. `tox -e pylint` (or `tox`)

### Current behavior
```
************* Module pylint.checkers.deprecated
pylint/checkers/deprecated.py:55:4: W9012: Missing return type documentation (missing-return-type-doc)
pylint/checkers/deprecated.py:64:4: W9012: Missing return type documentation (missing-return-type-doc)

--------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 10.00/10, -0.00)

ERROR: InvocationError for command /home/kolbus/projects/pylint/.tox/pylint/bin/pylint -rn --rcfile=/home/kolbus/projects/pylint/pylintrc --load-plugins=pylint.extensions.docparams, pylint.extensions.mccabe pylint tests/message tests/checkers tests/extensions tests/utils tests/acceptance tests/conftest.py tests/test_config.py tests/test_func.py tests/test_functional.py tests/test_import_graph.py tests/test_pragma_parser.py tests/test_pylint_runners.py tests/test_regr.py tests/test_self.py tests/unittest_config.py tests/lint tests/unittest_pyreverse_diadefs.py tests/unittest_pyreverse_inspector.py tests/unittest_pyreverse_writer.py tests/unittest_reporters_json.py tests/unittest_reporting.py (exited with code 4)
__________________________________________________________________________________________________________ summary __________________________________________________________________________________________________________
ERROR:   pylint: commands failed
```

### Expected behavior

No errors

**Comment by Pierre-Sassoulas** [comment]
Thank you for the report, we relied on ``pre-commit`` without having exactly the same args than ``tox -e pylint``

**Comment by pkolbus** [comment]
Thanks for the quick fix! 

Follow up question— does the `pylint` testenv still have any value, or should `tox` run the `formatting` env by default now?

**Comment by Pierre-Sassoulas** [comment]
I don't understand what you mean by pylint testenv ? I'm not sure if it's answering the question but you should be able to check the formatting with both ``pre-commit`` and ``tox``, the exact same command is used now (some files were not checked by tox and some plugin were not used by pre-commit).

**Comment by pkolbus** [comment]
In tox.ini, I’m wondering if `testenv:pylint` (and pylint in the `envlist`) still makes sense, or if `formatting` should be in the envlist instead since it runs all of the pre-commit checks. Then contributors can just run one command `tox` and have better assurance that the change is good.

**Comment by Pierre-Sassoulas** [comment]
Ho, you have a point we could rework this for sure. pre-commit include mypy, formatting, flake8 and pylint.
