### ISSUE TITLE
pylint pre-commit hook is not compatible with pre-commit auto-update

### ISSUE THREAD

**Issue by ssbarnea** [PyCQA/pylint#4245]
Even if pylint exposes the pre-commit hook and can be used, it does not work with auto-update mechanist of pre-commit tool: `pre-commit autoupdate`.

When you run it it will fail to pick the latest release of pylint and will pick an older version: `pylint-2.6.0`. This is happening because pre-commit is only looking for tags from the default branch, and the last tag on on this branch is outdated.

Even if user is manually changing the tag to use current `pylint-2.7.2` version, next time it runs autoupdate, it will downgrade the version. As users can easily have lots of pre-commit hook repositories configured, it would mean that they will always have to undo the downgrade.

I did contact @asottile on discord about this issue, but it seems that he does not consider this to be a bug of pre-commit and more of a particular issue with pylint development workflow, where release tags are not created on main branch.

I am not sure where the "blame" is, but I hope we can find a solution that does not cripple use of pre-commit auto-update. Any ideas?

**Comment by asottile** [comment]
idk why you didn't include the conclusions from the discussion -- the easiest fix is to history-only merge tags into mainline as they are released to mark them as released

**Comment by ssbarnea** [comment]
Sorry, I missed that bit as it was not clear to me how it can be done. I guess an additional github action that runs on tags-create that does this,... if it can be done in a safe way.

**Comment by Pierre-Sassoulas** [comment]
@asottile what do you mean by "history-only merge tags into mainline as they are released" ? (Maybe a git command I don't know ?)

 We have a 2.7 branch with only the bug fixes for 2.7 cherry-picked here. Say D is a bug fix and C a feature :

```
2.7.0 - C - D <-master
    \
      D' <- 2.7
```

What should we do when we release ? If we merge 2.7 in master before tagging master, then we ship C which is meant for 2.8 in 2.7.1 and we don't want that. 

```
2.7.0 - C - D - 2.7.1 <-master
    \             /
      D' -         <- 2.7
```

We could rebase master on 2.7 and tag on D', but then we don't want to rewrite master either.

```
A - 2.7.0 - D' (2.7.1) - C' <-master rebased
```

Also what would be the problem with ``pre-commit autoupdate`` getting the latest tag on any branches ?

**Comment by asottile** [comment]
Here is how to perform a history-only merge marking a tag as released:

```console
$ git describe --tags --abbrev=0
pylint-2.6.0
$ git merge --no-edit --strategy=ours pylint-2.7.2
Merge made by the 'ours' strategy.
$ git describe --tags --abbrev=0
pylint-2.7.2
```

note that `--strategy=ours` means that *no changes* are integrated from the tag

> Also what would be the problem with pre-commit autoupdate getting the latest tag on any branches ?

- there isn't really a way to discover all branches from a remote repository
- there may be tags on feature branches that shouldn't be considered (and no reasonable way to filter them out)
- a maintenance tag may be tagged on an old release that's not newer than the latest release (newer by date)
- "oh well just look at all tags globally and pick the latest version" - tags are just strings, there's no valid comparison method (pylint for instance would fail parsing as a version due to it's very-non-standard tagging scheme)

**Comment by Pierre-Sassoulas** [comment]
Thank you @asottile I learned something today :)

We're going to release 2.7.3 soonish and the problem will fix itself by following the new release process introduced in #4247 .
