### ISSUE TITLE
load-plugins not working if configured in setup.cfg [pylint.MASTER]

### ISSUE THREAD

**Issue by mteiste** [PyCQA/pylint#4272]
load_plugins option does not work if defined in [pylint.MASTER] section of setup.cfg

### Steps to reproduce

Given a config file `setup.cfg`
```
[pylint.MASTER]
load_plugins=pylint.extensions.bad_builtin
[pylint.DEPRECATED_BUILTINS]
bad-functions=print
```
and a python file `a.py`
```python
print("Hello World!")
```

### Current behavior
Result of `pylint --rcfile=setup.cfg a.py
```
************* Module a
a.py:1:0: C0114: Missing module docstring (missing-module-docstring)

-----------------------------------
Your code has been rated at 0.00/10
```

### Expected behavior
```
************* Module a
a.py:1:0: C0114: Missing module docstring (missing-module-docstring)
a.py:1:0: W0141: Used builtin function 'print' (bad-builtin)

---------------------------------------------------------------------
Your code has been rated at -10.00/10
```
### pylint --version output

Result of `pylint --version` output:
```
pylint 2.7.4
astroid 2.5.2
Python 3.8.5 (default, Jan 27 2021, 15:41:15) 
[GCC 9.3.0]
```

**Comment by mteiste** [comment]
Suspect the issue is in `option_manager_mixin.py`

**Comment by cdce8p** [comment]
If you use `setup.cfg` the correct config should be
```ini
[MASTER]
load-plugins=pylint.extensions.bad_builtin

[pylint.DEPRECATED_BUILTINS]
bad-functions=print
```
Notice that it's only `[MASTER]` not `[pylint.MASTER]`

You could also use `pyproject.toml`. In that case, this would be the correct config
```ini
[tool.pylint.MASTER]
load-plugins= "pylint.extensions.bad_builtin"

[tool.pylint.DEPRECATED_BUILTINS]
bad-functions= ["print"]
```
Here you shouldn't need to specify the `--rcfile` option.

**Comment by mteiste** [comment]
Still a bit confusing way (also you could use `[pylint.master]` which does work). I would assume that sections marked with pylint. would be the ones pylint uses and it should ignore any section that is not specifically marked for pylint.

**Comment by mteiste** [comment]
There is also an other slightly nasty side effect from this. If you have setup.cfg with sections for other tools that use same option names those will be taken in by pylint. For example the following setup.cfg 
```
[MASTER]
load-plugins=pylint.extensions.bad_builtin

[pylint.DEPRECATED_BUILTINS]
bad-functions=print

[pycodestyle]
ignore=E722,W503
```
has the effect of setting pylint's exclude to E722,W503, hence there is a lot of possibilities to have hard to find configuration problems when using setup.cfg.

**Comment by cdce8p** [comment]
I almost always use a `pylintrc` file for my pylint config, not `setup.cfg`
As for the `pylint.` prefix, I think this isn't used because it should be a separate file. Could be wrong though, maybe @Pierre-Sassoulas knows more?

**Comment by mteiste** [comment]
True, there are workarounds / arguably better options, just commenting that the current support for setup.cfg is slightly confusing.

**Comment by Pierre-Sassoulas** [comment]
Thank you for the issue @mteiste, evidentely setup.cfg is not super well supported. 

I did not modify a lot of configuration code, but I think we'd get some benefit of having a single standardized point of entry like flake8 (ask for pyproject.toml or setup.cfg support here, see how fast assotile closes the issue :smile: ). @AWhetter convinced me that actually merging #3769 would be shooting ourselves in the foot. Maybe we need to consider a breaking change in 3.0.0 where we only support `.pylintrc` and local `pyproject.toml`

**Comment by akaihola** [comment]
> If you use `setup.cfg` the correct config should be
> 
> [MASTER]
> load-plugins=pylint.extensions.bad_builtin

It's now 4 years later, and with `pylint==3.3.8` this seems to work for me instead:

`setup.cfg`
```ini
[pylint.MASTER]
load-plugins =
  pylint_per_file_ignores
```
