### ISSUE TITLE
Warn about mismatched number of logging formatting arguments

### ISSUE THREAD

**Issue by exquo** [PyCQA/pylint#4273]
### Is your feature request related to a problem? Please describe
When writing a `logging.…()` call, it's possible to provide too few, or too many arguments:

	logging.debug("%s %s", 42)
	logging.debug("%s", 42, 43)

This would print a logging error when encountered. However, if the logging level is set higher than in the `logging.…` function (`debug` in this example), it will not be immediately noticed.

### Describe the solution you'd like
Pylint already checks for this type of error for format strings (both `%` and `{}`) with `too-{many/few}-format-args`. Would be nice if it could also do it for `logging` format strings.

**Comment by Pierre-Sassoulas** [comment]
This already exists, Upgrade to the latest version of pylint or maybe change your logging settings in the configuration.

```python
    logging.debug("%s %s", 42) # [logging-too-few-args]
    logging.debug("%s", 42, 43) # [logging-too-many-args]
```
(https://github.com/PyCQA/pylint/pull/4276/files)

**Comment by exquo** [comment]
I see it now, sorry for the noise!

**Comment by hippo91** [comment]
@exquo no pb!
