### ISSUE TITLE
--msg-template not working in python

### ISSUE THREAD

**Issue by omides248** [PyCQA/pylint#4286]
Code
```
from pylint import epylint as lint

(pylint_stdout, pylint_stderr) = lint.py_run(
    "my_app.py -E --disable=E1111 --msg-template='{category} {module} {obj} {line}: {column} {msg}'",
    return_std=True)

print(pylint_stdout.read())

```
Output:
```
************* Module {module}
 fatal
 ************* Module {obj}
 fatal
 ************* Module {line}:
 fatal
 ************* Module {column}
 fatal
 ************* Module {msg}'
 fatal
 ************* Module my_app
 error
```

How using --msg-template with python ? 
space not working.
How custom message.
thanks

**Comment by Pierre-Sassoulas** [comment]
Hello, what does ``my_app.py`` contains ?
a.py:
```python
from pylint import epylint as lint

(pylint_stdout, pylint_stderr) = lint.py_run(
    "a.py -E --enable=all --msg-template='{category} {module} {obj} {line}: {column} {msg}'",
    return_std=True,
)

print(pylint_stdout.read())
```
Result of ``python3 a.py``:
```
************* Module a
 convention a  1: 0 Missing module docstring

```

**Comment by omides248** [comment]
<img width="958" alt="cccc" src="https://user-images.githubusercontent.com/37228870/113448394-01c56280-9411-11eb-8cb5-1c867a8a6970.PNG">

**Comment by Pierre-Sassoulas** [comment]
Thanks, I can reproduce now.

**Comment by Pierre-Sassoulas** [comment]
Please do not use images, this can't be indexed by search engines and blind user won't be able to read it either :)

**Comment by Pierre-Sassoulas** [comment]
You can make it works with:

```python
from pylint import epylint as lint

(pylint_stdout, pylint_stderr) = lint.py_run(
    "my_app.py -E --disable=E1111 --msg-template='{category} {module} {obj} {line} {column} {msg}'",
    return_std=True,
)
print(pylint_stdout.read())
```
Notice the `'` around the msg-template.

**Comment by omides248** [comment]
thank you . I tested this code on both Linux and Windows, 
but this code works on Linux, but it has the previous error in Windows.

**Comment by Pierre-Sassoulas** [comment]
I added some tests and checked that. This will make more sense in order to understand what is happening here:
```
pylint my_app.py -E --disable=E1111 \
    --msg-template='{category} {module} {obj} {line} {column} {msg}' {module} {obj} {line} {column} {msg}
************* Module {module}
fatal {module}  1 0 No module named {module}
************* Module {obj}
fatal {obj}  1 0 No module named {obj}
************* Module {line}
fatal {line}  1 0 No module named {line}
************* Module {column}
fatal {column}  1 0 No module named {column}
************* Module {msg}
fatal {msg}  1 0 No module named {msg}
************* Module my_app
```

 We can't do any better for error handling regarding the mistake when launching the command, because the command is equivalent to:

``pylint my_app.py {module} {obj} {line} {column} {msg} -E --disable=E1111 --msg-template='{category}'``

So we can't detect that there is a problem and we cannot change it or we break the multifile analysis.

**Comment by DudeNr33** [comment]
@omides248 I ran into a very similar issue on Windows. Can you try omitting the ``=`` between ``--msg-template`` and the string afterwards?

```  Python
from pylint import epylint as lint

(pylint_stdout, pylint_stderr) = lint.py_run(
    "my_app.py -E --disable=E1111 --msg-template '{category} {module} {obj} {line} {column} {msg}'",
    return_std=True,
)
print(pylint_stdout.read())
```

**Comment by Pierre-Sassoulas** [comment]
Also, the test are not passing for windows on #4287

**Comment by Pierre-Sassoulas** [comment]
@DudeNr33 is right under windows (unlike Linux) the equal must be removed. You still need the ``'`` :) Thank you for fixing the MR for me :)
