### ISSUE TITLE
Lint all Python files

### ISSUE THREAD

**Issue by AustinScola** [PyCQA/pylint#4289]
It would be very convenient to be able to tell pylint to lint all Python files recursively. Maybe with a syntax like `python3 -m pylint .` for example. Instead I often find myself using `find` and piping the files to pylint.

**Comment by Pierre-Sassoulas** [comment]
Yes, but it's a duplicate of  the oldest issue in the repo #352

**Comment by AustinScola** [comment]
Sorry about that, I did a search but didn't find that one.

**Comment by Pierre-Sassoulas** [comment]
No problem :)
