### ISSUE TITLE
tox [testenv:docs] fails due to missing dependencies

### ISSUE THREAD

**Issue by DudeNr33** [PyCQA/pylint#4290]
### Steps to reproduce

1. Clone the repository
2. Create a new virtual environment
3. Install tox 
4. Run ``tox -e docs``

### Current behavior
The command fails with:
```
tox -e docs --recreate
docs recreate: /Users/andreas/programming/forks/pylint/.tox/docs
docs installdeps: -r/Users/andreas/programming/forks/pylint/requirements_docs.txt
docs installed: appdirs==1.4.4,distlib==0.3.1,filelock==3.0.12,packaging==20.9,pluggy==0.13.1,py==1.10.0,pylint==2.8.0.dev1,pyparsing==2.4.7,six==1.15.0,toml==0.10.2,tox==3.23.0,virtualenv==20.4.3
docs run-test-pre: PYTHONHASHSEED='3523030654'
docs run-test: commands[0] | sphinx-build -W -b html -d _build/doctrees . _build/html
Sphinx v3.5.3 in Verwendung

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/Users/andreas/programming/forks/pylint/.tox/docs/lib/python3.8/site-packages/sphinx/config.py", line 327, in eval_config_file
    execfile_(filename, namespace)
  File "/Users/andreas/programming/forks/pylint/.tox/docs/lib/python3.8/site-packages/sphinx/util/pycompat.py", line 88, in execfile_
    exec(code, _globals)
  File "/Users/andreas/programming/forks/pylint/doc/conf.py", line 22, in <module>
    from pylint.__pkginfo__ import version
ModuleNotFoundError: No module named 'pylint'

ERROR: InvocationError for command /Users/andreas/programming/forks/pylint/.tox/docs/bin/sphinx-build -W -b html -d _build/doctrees . _build/html (exited with code 2)
___________________________________ summary ____________________________________
ERROR:   docs: commands failed
```

### Expected behavior
Command succeeds and documentation is built.

### pylint --version output
No version output, since this is not an issue of the package itself.
Current commit in master branch: https://github.com/PyCQA/pylint/commit/f5e0968d6be95ae1bf9608e6bab6afcb8aa54663

I guess this was introduced with [this commit](https://github.com/PyCQA/pylint/commit/2e149d2ca8314ec7b4aaaa3b730a2b41bcf9b4a2#diff-ef2cef9f88b4fe09ca3082140e67f5ad34fb65fb6e228f119d3812261ae51449), which added as ``skipinstall = True`` for the docs testenv. Removing that line helps, as this will install all required dependencies.

**Comment by Pierre-Sassoulas** [comment]
If I understand well removing the  ``skipinstall=True`` would fix it ?

**Comment by DudeNr33** [comment]
Yes, that is the minimum to get it working again. 
The tox configuration before the change also had the ``usedevelop = True`` option set, but this seems to be not necessary.

I guess creating a pull request for this one liner is more work than changing it directly?

**Comment by Pierre-Sassoulas** [comment]
A merge request is the way :)
