### ISSUE TITLE
Have spellchecker ignore code in docstring or comments (i.e. things flanked with double backticks)

### ISSUE THREAD

**Issue by eli88fine** [PyCQA/pylint#4319]
### Is your feature request related to a problem? Please describe

When I run the spellchecker, I have comments like 
> The ``.qsize()`` method requires that blah blah blah

The spellchecker raises an error saying qsize is not a word. I would prefer not to have to add all these things into the 'words to ignore' dictionary, as I really only want qsize to be allowed if I explicitly flank it with backticks to indicate that it is code...if I accidentally typed qsize instead of size in a comment I would still want that flagged.  I also don't want to have to disable pylint spellchecking for that whole line of comment or the whole docstring.

### Describe the solution you'd like

Anything flanked in backticks should be ignored by the spellchecker (a likely easy implementation would be to add another filter like is already in place for Sphinx directives).

Would you be open to a PR to address this?

**Comment by Pierre-Sassoulas** [comment]
Thank you for opening the issue :) ! I think this would make a lot of sense.

**Comment by eli88fine** [comment]
Should it require double backticks on each side?  or should it be more open, and anything flanked in either single or double backticks be considered code?

**Comment by Pierre-Sassoulas** [comment]
Markdown require a single backtick and rst double backticks, so I think it's ok to permit both.
