### ISSUE TITLE
Performance degradation between version 2.7.2 and 2.7.4?

### ISSUE THREAD

**Issue by tyralla** [PyCQA/pylint#4353]
I know there other issues dealing with the performance of Pylint 2.7.0 and generics, but this problem seems a little different to me.

20 days ago, Pylint evaluated my project (which uses generics) on Travis-CI in the usual amount of time (806 seconds). This is what Travis installed then:

```
Successfully installed astroid-2.5.1 isort-5.8.0 lazy-object-proxy-1.6.0 mccabe-0.6.1 pylint-2.7.2 wrapt-1.12.1
```

Now, Pylint cannot finish within any reasonable time limit. This is from the latest log file:

```
Successfully installed astroid-2.5.3 isort-5.8.0 lazy-object-proxy-1.6.0 mccabe-0.6.1 pylint-2.7.4 wrapt-1.12.1
```

On my local computer, both version 2.7.2 and 2.7.4 and also some older versions I tried are way too slow (I manually stopped the process after more than an hour; I cannot remember this happened ever before). Note that Travis-CI uses Python 3.6, and I use Python 3.8 on my local computer.

**Comment by Pierre-Sassoulas** [comment]
Thank you for opening the issue. Do you use generic classes ? (#4079)

**Comment by tyralla** [comment]
Yes, I do. But as I mentioned, performance was okay 20 days ago, while issue #4079 is a little older.

**Comment by tyralla** [comment]
I made some test and, at least for Python 3.6, there seems to be an issue with astroid.

As mentioned above, with this combination of packages Pylint runs (almost) forever:

`Successfully installed astroid-2.5.3 isort-5.8.0 lazy-object-proxy-1.6.0 mccabe-0.6.1 pylint-2.7.4 wrapt-1.12.1`

For this combination, its the same:

`Successfully installed astroid-2.5.3 isort-5.8.0 lazy-object-proxy-1.6.0 mccabe-0.6.1 pylint-2.7.2 wrapt-1.12.1`

However, going back to astroid 2.5.1 restores the original performance:

`Successfully installed astroid-2.5.1 isort-5.8.0 lazy-object-proxy-1.6.0 mccabe-0.6.1 pylint-2.7.2 wrapt-1.12.1`

I am almost sure the problem arises when Pylints analyses a chain of generic classes in my codebase. Possibly due to "Fix mro for classes that inherit from typing.Generic*" of astroid 2.5.3?

**Comment by hippo91** [comment]
@tyralla thanks for your report and investigation!

**Comment by hippo91** [comment]
@tyralla are you facing the same problem with latest versions of `astroid` and `pylint`?
If so, is it possible to have access to the sources you are linting?

**Comment by tyralla** [comment]
@hippo91: Sorry for the late response. Pylint now finishes within a reasonable time limit again on my local computer (Pylint 2.9.5, Astroid 2.6.5, Python  3.8.5, Windows). Unfortunately, I cannot check it on Travis-CI (Python 3.6) anymore - no more free open source support.

Thank you very much for your effort!
