### ISSUE TITLE
Discord invitation link is broken in the docs

### ISSUE THREAD

**Issue by h-joo** [PyCQA/pylint#4393]
The discord server invitation link: https://discord.gg/kFebW799 mentioned [here](https://github.com/PyCQA/pylint/blob/master/doc/development_guide/contribute.rst#discord-server) is broken. It says it's an invalid invite.

**Comment by Pierre-Sassoulas** [comment]
Thanks for the report, I'm going to fix that !

**Comment by Pierre-Sassoulas** [comment]
The invitation link is https://discord.gg/Egy6P8AMB5

**Comment by h-joo** [comment]
Thank you :) the link works great
