### ISSUE TITLE
Rename default branch to ``main``

### ISSUE THREAD

**Issue by cdce8p** [PyCQA/pylint#4410]
Many projects are renaming their default branch from ``master`` to ``main`` recently, CPython will do so next month. I suggest we do the same for `pylint` and `astroid`.

Github makes this fairly easy, see link below. AFAIK all we would need to do is change all references in `CI` (trigger on push to `main`) and update all links that currently point to the master branch (mainly the license headers and in the readme).

The individual dev would only need to do
```bash
git branch -m master main
git fetch origin
git branch -u origin/main main
```

**Links**
https://docs.github.com/en/github/administering-a-repository/renaming-a-branch
https://mail.python.org/archives/list/python-dev@python.org/thread/QWW7KGBW5UH2N5FOZOFXQBQPYELWQM3O/

**Comment by Pierre-Sassoulas** [comment]
Now that pylint/astroid are so modern with their fancy setup.cfg, github actions, standardized tag and automatically generated versions (well, only pylint so far for the last two), this is the next step !

**Comment by cdce8p** [comment]
The renaming was done between `v2.9.1` and `v2.9.2` for `pylint` and `v2.6.2` and `v2.6.3` for `astroid`.
