### ISSUE TITLE
Primer acceptance tests like in black or mypy

### ISSUE THREAD

**Issue by Pierre-Sassoulas** [PyCQA/pylint#4413]
Created this ticket following a discord and #4390 discussion with @cdce8p

**Comment by Pierre-Sassoulas** [comment]
> > The difference is that both are focused on maintaining stability whereas we constantly add new things as well.

> Ha, very true. But we can check that pylint is "not crashing". And I think we could check for the presence of error. There's a very slim possibility that there is a real error in a release of those very big libraries but I would bet on a pylint false positive or regression every time. And in particular if suddenly there's a ton of import-error or no-module-error because namespace packages are broken we would detect it.

https://github.com/PyCQA/astroid/pull/1211#issuecomment-943637484

**Comment by cdce8p** [comment]
This issue might be something we should prioritize. Both #5162 and #5170 could have been prevented if detected earlier.

**Comment by Pierre-Sassoulas** [comment]
I was going to say exactly that. Let's do it.

**Comment by cdce8p** [comment]
> I'm already finding crash which is encouraging (#5172). However I think we'll need to install the environment of the project for this to work pylint need to be able to import dependencies. Also we can't easily add project because `pylint .` do not work without an `__init__.py` at the root level.

I haven't looked at it closely yet, but from what I think, you're right: We'll need to install all import dependencies for each project. That's different to what `black_primer` does. Maybe it's an idea to look how [mypy_primer](https://github.com/hauntsaninja/mypy_primer) does it instead? They should also need to install dependencies.

> Maybe we could install with pip and lint the dependencies installed in the tests ? What pip install is a package and is supposed to work, so we would not have this issue.

Not sure about that. `git clone --depth 1` is probably better.

> I'm going to create a draft so we can discuss.

Thanks for doing this 🚀 I'm looking forward to it!
