### ISSUE TITLE
W0611 in __init__.py is fine

### ISSUE THREAD

**Issue by whg517** [PyCQA/pylint#4451]
## Question

when unused-import (W0611) in __init__.py, pylint is fine.

## example 

[Example Project](https://github.com/whg517/pythonic-project-samples/tree/85e502bff7cb1a0f56570e36f1ae0342294f8fa3)

[example code](https://github.com/whg517/pythonic-project-samples/blob/85e502bff7cb1a0f56570e36f1ae0342294f8fa3/src/file2mongo/config/__init__.py#L5)

In `__init__.py` , `import os` exist, and not use `os`

But, [run pylint](https://github.com/whg517/pythonic-project-samples/runs/2532766156#step:5:35) in CI is fine

**Comment by Pierre-Sassoulas** [comment]
This is due to the fact that in an ``__init__.py``, it could be imported in order to create an API (The API should be defined in ``__all__``but that's not always the case).
