### ISSUE TITLE
Refactor pylint/config modules to avoid using deprecated optparse module.

### ISSUE THREAD

**Issue by matusvalo** [PyCQA/pylint#4455]
### Steps to reproduce
Following files:

* pylint/config/man_help_formatter.py
* pylint/config/option.py
* pylint/config/option_manager_mixin.py
* pylint/config/option_parser.py
* pylint/config/options_provider_mixin.py

Are using deprecated `optparse` module.  Currently `deprecated-module` check is disabled to suppress errors.  When disable is removed, pylint is raising error for given modules.

### Current behavior
`optparse` module is used in mentioned modules, `deprecated-module` check is disabled to suppress errors.

### Expected behavior
Modules should be refactored to avoid using `optparse` module. `deprecated-module` check should not be disabled.

**Comment by DanielNoord** [comment]
Closing this in favour of #5392.
