### ISSUE TITLE
redefined-builtin not working when using inside iterator 

### ISSUE THREAD

**Issue by patrickelectric** [PyCQA/pylint#4472]
### Steps to reproduce

Given a file `a.py`:
```python
# pylint: disable=missing-docstring
filters = [lambda a: a, lambda b: b]
print([filter(1) for filter in filters])
```
### Current behavior
```
--------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 10.00/10, +0.00)
```
### Expected behavior
```
W0622: Redefining built-in 'filter' (redefined-builtin)
```

### pylint --version output

Result of `pylint --version` output:
```
pylint 2.7.4
astroid 2.5.3
Python 3.9.4 (default, Apr 20 2021, 15:51:38) 
[GCC 10.2.0]
```

**Comment by Pierre-Sassoulas** [comment]
This one is voluntary. If a builtin is redefined in  a function or liste comprehension chances are you don't need pylint to tell you why your builtin does not work, it is under your nose. But 'id' and 'file' are useful as variable name. (I'm on mobile so I can't easily link the related issue/mr but there is one)
