### ISSUE TITLE
is "WordsWithDigigtsFilter" a typo?

### ISSUE THREAD

**Issue by jcwill23** [PyCQA/pylint#4482]
pylint 2.7.4 checkers\spelling.py

has class WordsWithDigigtsFilter

which I assume is just a typo (WordsWithDigitsFilter)

**Comment by Pierre-Sassoulas** [comment]
I think this can be fixed in 2.8 and is probably not a breaking change (at least it's one I'm willing to risk doing).

**Comment by jcwill23** [comment]
Just checked latest in github 2.8 and this is fixed in latest. Sorry to waste your time.
