### ISSUE TITLE
How to return error when function is not specified type by annotation.

### ISSUE THREAD

**Issue by thanhpd-teko** [PyCQA/pylint#4497]
## Question
Hi,
I would like to setup pylintrc rule so that it will check some functions those don't have type annotation, then return warning or error. How can I do it with pylint? Thanks.

**Comment by cdce8p** [comment]
I think you might what do look at a dedicated type checker for that, e.g., `mypy`.
In particular: https://mypy.readthedocs.io/en/stable/command_line.html?highlight=strict#untyped-definitions-and-calls

**Comment by Pierre-Sassoulas** [comment]
We're not going to compete with mypy, it does its job and it does it well. We could integrate mypy to pylint like we integrated isort though.

**Comment by thanhpd-teko** [comment]
Thanks.
