### ISSUE TITLE
Performance regressions with astroid 2.5.7

### ISSUE THREAD

**Issue by Pierre-Sassoulas** [PyCQA/pylint#4524]
https://github.com/PyCQA/astroid/issues/1003

**Comment by cdce8p** [comment]
I think this can be closed as well now that https://github.com/PyCQA/astroid/pull/1009 is merged.

**Comment by Pierre-Sassoulas** [comment]
Actually, let me release 2.5.8 and change the version used in pylint :)

**Comment by RuRo** [comment]
@Pierre-Sassoulas am I correct in assuming that now that this issue is fixed, you'll be able to release pylint 2.9.0 reasonably soon?

**Comment by Pierre-Sassoulas** [comment]
:crossed_fingers:

**Comment by Pierre-Sassoulas** [comment]
You can check what need to be done here: https://github.com/PyCQA/pylint/milestone/25

Right now there is two small documentation tasks, one big checker and one checker that we would remove if @yushao2 is not available and the three other tasks are done.
