### ISSUE TITLE
When to set `runtime-typing` to no?

### ISSUE THREAD

**Issue by nth10sd** [PyCQA/pylint#4545]
## Question

For `runtime-typing`, it [is mentioned to](http://pylint.pycqa.org/en/v2.8.3/technical_reference/extensions.html#typing-checker-options) `Set to no if the app / libary does NOT need to support runtime introspection of type annotations`. May I clarify what this means? I have `from __future__ import annotations` turned on throughout, but it does not seem to make a difference.

(Reason: I have `Optional[str]` usages and I realised that pylint only advises to turn them to `str | None` only if `runtime-typing` is a non-default `no` - I would have thought they should be turned to `str | None` as long as we have `from __future__ import annotations`)

Sidenote: minor [typo here](https://github.com/PyCQA/pylint/blob/0e7c2c4318f99f72d7326d4fb1e5758560ec7368/pylint/extensions/typing.py#L127), `libary` -> `library`.

**Comment by cdce8p** [comment]
Thanks for the question. The most common examples for runtime introspection are `typing.get_type_hints` and `eval`. Besides that there are libraries that use type annotations to generate code. If you rely on annotations just for type checking, you are probably fine.

Some more information: https://mypy.readthedocs.io/en/stable/runtime_troubles.html#annotation-issues-at-runtime

However, just using the default (`runtime-typing=yes`) is definitely the safer option. I would even go as far as to say, only set it to `no` if you already know what it means.

> I would have thought they should be turned to str | None as long as we have from __future__ import annotations

My intention was to only suggest it when it's truly safe to do so as it is a stylistic choice anyway. `Optional` and `Union` haven't been deprecated. Someone might have added `from __future__ import annotations` to solve a forward reference or something else without realizing the actual impact.

**Comment by nth10sd** [comment]
This does help, thank you!
