### ISSUE TITLE
Add documentation for ``pyreverse`` and ``symilar``

### ISSUE THREAD

**Issue by DudeNr33** [PyCQA/pylint#4616]
### Is your feature request related to a problem? Please describe

``pyreverse`` is an awesome tool to visualize the project structure and dependencies.
However, it is not even mentioned once in the documentation.
I think adding at least some basic instructions on how to use it and what the output looks like would make it a bit more widely known.

Probably ``symilar`` should get a few sentences as well, but I must admit that I do not know if it is really intended to be used from the command line directly?

The last console script which gets installed additionally to ``pylint`` is ``epylint``. I do not think that it needs additional documentation, since as I understand it its main purpose is the integration with Emacs, which is already described properly in the docs.

### Describe the solution you'd like

Add documentation pages for at least ``pyreverse``, probably also ``symilar``.

You can assign this issue directly to me, if you want.

**Comment by Pierre-Sassoulas** [comment]
I agree, we need more documentation (in general too, but for pyreverse in particular). Especially if there is a new fancy plantuml option 😄
