### ISSUE TITLE
pylint and astroid AttributeError: 'Module' object has no attribute 'col_offset'

### ISSUE THREAD

**Issue by AndreasLuckert** [PyCQA/pylint#4671]
As I'd [already asked on StackOverFlow](https://stackoverflow.com/questions/68194128/pylint-and-astroid-attributeerror-module-object-has-no-attribute-col-offset/68244801), versions `2.9.0` and `2.9.3` seem to have this bug.

A workaround is to downgrade `pylint` to version [2.8.3](https://pypi.org/project/pylint/2.8.3/), which still works.

**EDIT:**

I've just updated the [OP](https://stackoverflow.com/questions/68194128/pylint-and-astroid-attributeerror-module-object-has-no-attribute-col-offset) with all python-packages involved in this testing environment, as well listing some attempts which did not work out to solve the problem.

**Comment by Pierre-Sassoulas** [comment]
Do you have an hint about the code that provoked the crash ? I'd want to add a regression test if possible (and also possibly do more than just avoid the crash and do the right thing). Ideally it would be a python file that would crash pylint with ``pylint a.py`` but simply the code around the problem could help too.

**Comment by AndreasLuckert** [comment]
I'm afraid this is not possible at the moment to provide such information.
I'm working in a dev team on a complex project of a multi-national company involving highly confidential data.
Also, the code is built in a quite intricate and nested manner.

Let's hope that you will the issue, or other people experience similar problems and will be able to provide a full-working example code.

**Comment by Pierre-Sassoulas** [comment]
Ok, thank you for providing as much details as you can 😄 Blind fix it is then :) Could you maybe tell me if there is still a crash when installing astroid via : ``pip install git+git://github.com/PyCQA/astroid.git@c37b6fd47b62486fd6cbe77b913b568b809f1a6d#egg=astroid``, please ?

**Comment by AndreasLuckert** [comment]
Thanks a lot for this hint!

Indeed, the combination
```
pip install pylint==2.9.3
pip install git+git://github.com/PyCQA/astroid.git@c37b6fd47b62486fd6cbe77b913b568b809f1a6d#egg=astroid
```

worked out without a failure (the entire AWS CodePipeline process testing and building the packages).

The dev team on my side decided that we're going to keep on using `pylint==2.8.3` for this time being until there is a new official/stable version of `pylint` and `astroid` respectively.
Please let me know as soon as this is the case, so that we can update our build-scripts accordingly.
