### ISSUE TITLE
Document a better release process than the current one

### ISSUE THREAD

**Issue by Pierre-Sassoulas** [PyCQA/pylint#4701]
See #4651

**Comment by yushao2** [comment]
@Pierre-Sassoulas i think this can be closed now? 🎉

**Comment by Pierre-Sassoulas** [comment]
I don't think we implemented git flow we have a simpler flow right now, [maybe it's enough](https://www.endoflineblog.com/gitflow-considered-harmful). I'm not sure that we're strictly following OneFlow either, but we don't have major issue with how we do thing right now. Thoughts @cdce8p ?

**Comment by cdce8p** [comment]
From what I can tell, it mostly works how we need it to. So I don't really see a reason to change it just to conform to some specification. Btw. I always though of it as close to the GithubFlow, although we don't have a separate release branch ;)

**Comment by Pierre-Sassoulas** [comment]
I'm going to try a 2.13 branch where we back-port bug fixes and crash fixes to be released as patch this time. So we do not have crash fixes waiting for month while we finalize a minor release There's a "Needs Backport" label let's start using this and squashing the MR that needs backport for easy cherry-picking. This is going to massively increase the release cadence for bug/crash fixes. Putting this in 2.13.0 milestone so I remember to document the process.

**Comment by DanielNoord** [comment]
@Pierre-Sassoulas For clarity, it might be good to add a "backported" label which can replace the "needs backport" label after a PR has been back ported. That allows us to easily see if all recently merged PRs that need back porting have had it.

**Comment by cdce8p** [comment]
Home Assistant has a label named `cherry-picked`. Every bugfix PR gets assigned to the  corresponding milestone and once it's "backported" `cherry-picked` is added.
