### ISSUE TITLE
getting `unnecessary-dict-index-lookup` when deleting an item by value

### ISSUE THREAD

**Issue by 2bndy5** [PyCQA/pylint#4716]
I was wondering if I'm doing this wrong. I'm trying to remove a dict item when searching the dict's `items()` to re-assign a certain unique value to a new key.

-------------------------------
### NOTES

1. The dict I'm managing is a private class member and will not have multiple keys with the same value.
2. I'm using pylint v2.9.3 (had the same problem with v2.9.0 previously)

------------------------------
I've added `# pylint:` comments around the controversial line
```python
    def _set_address(self, node_id, address, search_by_address=False):
        """Set or change a node_id and network address pair on the master node."""
        for n_id, addr in self._addr_dict.items():
            if not search_by_address:  # search by key
                if n_id == node_id:
                    self._addr_dict[n_id] = address
                    break
            else:  # search by value
                if addr == address:
                    # pylint: disable=unnecessary-dict-index-lookup
                    del self._addr_dict[n_id]
                    # pylint: enable=unnecessary-dict-index-lookup
                    self._addr_dict[node_id] = address
                    break
        if node_id not in self._addr_dict.keys():
            self._addr_dict[node_id] = address
```

The pylint message suggests I use `addr` instead, but that doesn't help when deleting an item by key.

**Comment by Pierre-Sassoulas** [comment]
Thank you for opening the issue, I think it's a false positive.

**Comment by 2bndy5** [comment]
I was able to work around this in a separate instance by using dict comprehension.
```python
new_dict = {}
for k, v in old_dict.items():
    if v != val_to_remove:
        new_dict[k] = v
old_dict = new_dict
```
But, applying this workaround to the snippet in the OP would be more work than its worth because I'm also re-assigning the previously used value to a new key.

**Comment by cdce8p** [comment]
This is a false-positive, `unnecessary-dict-index-lookup` should not be emitted for `del` statements.
I'm able to reproduce the error with this snipped:
```py
d = {}
for key, val in d.items():
    del d[key]
```

/CC: @yushao2

**Comment by yushao2** [comment]
Thanks, assigned myself to look into this
