### ISSUE TITLE
Add Github issue forms

### ISSUE THREAD

**Issue by cdce8p** [PyCQA/pylint#4735]
### Is your feature request related to a problem? Please describe

The current issue template for bug reports can sometimes be quite confusing. Especially since it's not always clear where a comment starts/ends and what someone needs to fill out.

### Describe the solution you'd like

Start using **Github issue forms** to make filing a bug report easier.

### Additional context

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms

**Comment by Pierre-Sassoulas** [comment]
It looks amazing, thank you for bringing that up.

**Comment by Pierre-Sassoulas** [comment]
Made a first try here : https://github.com/Pierre-Sassoulas/pylint/issues/new/choose

I think it looks very nice. the only problem is linked to yaml where you can't import so we'll have to duplicate.

I was thinking about making  "Crash", "Bug", "False Positive", "False Negative", "Feature request" and "Question", what do you think ?

**Comment by cdce8p** [comment]
Not sure we should really differentiate too much. It doesn't help if we have a nice form but a beginner doesn't know which to choose. We triage them afterwards anyway. Therefore I would suggest to stick to just `Bug`, `Feature request`, and `Question`.

One more thing, with the current template we assume that the issue is caused by multiple files: `Given file a and given file b`. At least from what I've seen so far, most are actually just caused by a single one. Maybe we should remove `file b`.

**Comment by Pierre-Sassoulas** [comment]
That would permit to apply label automatically and have a template that is more relevant. But I think you're right, there's already a lot with all the link added and not a lot changing from false positive/negative and bug.
