### ISSUE TITLE
multiple-imports/misplaced-future/wrong-import-order checkers is slow for scan

### ISSUE THREAD

**Issue by jimxzcai** [PyCQA/pylint#4738]
## Question
Below checkers are slow for scan。 How to speed up？

multiple-imports
misplaced-future
wrong-import-order

**Comment by Pierre-Sassoulas** [comment]
There's a documentation regarding checkers performance analysis in the documentation thank to @DudeNr33 now, see https://pylint.pycqa.org/en/latest/development_guide/contributor_guide/profiling.html
