### ISSUE TITLE
Update Coveralls to use `main` branch as standard branch

### ISSUE THREAD

**Issue by DanielNoord** [PyCQA/pylint#4805]
### Current problem

Currently `pylint` on Coveralls uses the `master` branch as standard branch.
See: https://coveralls.io/github/PyCQA/pylint
This should probably be updated to `main`, as this is now the standard branch and `master` has been removed.

### Desired solution

/

**Comment by Pierre-Sassoulas** [comment]
Thank you for opening the issue, we had to sync to github in the settings.

**Comment by DanielNoord** [comment]
Happy to help!

**Comment by DanielNoord** [comment]
By the way, as shown [here](https://coveralls.io/builds/41920338/source?filename=pylint%2Flint%2Frun.py) Coveralls seems to fail to load source files. I have done a quick google search and some users seem to note that this is due to wrong folder links used in the Coveralls config. Perhaps this is something we can look into? Should I create an additional issue? Or is this something you can easily fix?

**Comment by Pierre-Sassoulas** [comment]
The coveralls config might be a file that is modifiable in the repository ? I don't see any directory configuration in the coveralls.io web interface.

**Comment by Pierre-Sassoulas** [comment]
https://github.com/lemurheavy/coveralls-public/issues/886#issuecomment-266094774

**Comment by DanielNoord** [comment]
Our config is found [here](https://github.com/PyCQA/pylint/blob/main/.coveragerc). I think you might be seeing different things on Coveralls as a maintainer compared to regular users. I don't see the "set prefix" options on Coveralls for example.

**Comment by Pierre-Sassoulas** [comment]
Once logged I can see the sources... so I don't have the option to set the root correctly. I'll check that later.

**Comment by Pierre-Sassoulas** [comment]
It's not fixable, but everyone should be able to login and see the source. See:

https://github.com/lemurheavy/coveralls-public/issues/572#issuecomment-125849601

> We pull the source from Github on-demand so it doesn't inflate our storage size, and we need to use your Github access token so ours doesn't get rate limited.
