### ISSUE TITLE
Prompt pylint class additional parents

### ISSUE THREAD

**Issue by voronind** [PyCQA/pylint#4833]
### Question

Can we prompt `pylint` to use additional class parents via plugin? It can be useful for https://github.com/odoo/odoo modules model inheritance way.

```python
class ParentModel(odoo.models.Model):
    _name = 'specifier'
```
Other Odoo module. Install/uninstall independently of other modules.
```python
class Model(odoo.models.Model):
    _inherit = 'sprecifier`
```
Odoo make that `Model` inherits `ParentModel` cause `specifier`. That's why many checks of `pylint` doesn't work.

### Documentation for future user

May be some `pylint` plugins do that.

**Comment by Pierre-Sassoulas** [comment]
I would say it's something that could be done in a ``pylint-odoo`` plugin (like ``pylint-pytest`` or ``pylint-django``) and not in the main pylint code.
