### ISSUE TITLE
New check: Walrus operator recommended

### ISSUE THREAD

**Issue by nickdrozd** [PyCQA/pylint#4862]
### Current problem

Consider this still-common pattern:

```python
match = re.match(regex, string)
if match:
    do_stuff(match)
```

### Desired solution

As of Python 3.8, this can be rewritten with the "walrus":

```python
if (match := re.match(regex, string)):
    do_stuff(match)
```

Pylint should recommend using the walrus operator in situations like this.

### Additional context

See https://www.python.org/dev/peps/pep-0572/

**Comment by Pierre-Sassoulas** [comment]
Thank you, nice suggestion !

**Comment by cdce8p** [comment]
Opened a PR for it: #4876

**Comment by Pierre-Sassoulas** [comment]
Moving to 2.11 as I feel we already have a lot of things in 2.10 and we're sitting on great unreleased performance improvement.
