### ISSUE TITLE
Report refactor for missing main when file has shebang

### ISSUE THREAD

**Issue by PanderMusubi** [PyCQA/pylint#4873]
### Current problem

When a Python file has a shebang on the first line, such as

    #!/usr/bin/env python3

the file van be executed directly. In order to place a much as possible not in the top-level scope but in functions to promote reusage, the file ideally should have the main code in or called from

    if __name__ == "__main__":
        ...

### Desired solution

When the first line has

    #!/usr/bin/env python3

but the file is missing

    if __name__ == "__main__":

pylint should report this as an item for refactoring.

User should be able to suppress this with

    # pylint:disable=missing-main

in some way. Not sure how that combines with the shebang line.

### Additional context

See also:
- https://github.com/PyCQA/pylint/pull/1250
- https://github.com/PyCQA/pylint/issues/516

**Comment by Pierre-Sassoulas** [comment]
Thank you for opening the issue. Wouldn't there be the corollary too when the ``if __name__ == "__main__":`` exists but not the shebang ?

**Comment by PanderMusubi** [comment]
Yes, good one. It can have this line to disable it

    # pylint:disable=missing-shebang

**Comment by PanderMusubi** [comment]
Note that support needs to be for 

    if __name__ == "__main__": 

and for

    if __name__ == '__main__':

**Comment by PanderMusubi** [comment]
One of the advantages of having a main function is that code has the same base indentation in the entire file. This makes moving code between functions easier for editors that have more challenges with autoindentation.

**Comment by DudeNr33** [comment]
I don't think the opposite assumption (shebang necessary if a ``if __name__ == "__main__"`` exists) is true.
For example on Windows you don't have a shebang, and all Windows devs would have to disable the check. 

Pylint could check the current operating system and only issue the message if it runs under Unix, but keep in mind that you could also have the situation where Pylint is run on a Linux server for CI but the script is used under Windows.

**Comment by Pierre-Sassoulas** [comment]
But windows code could be run on unix systems where the sheband is useful, and the shebang does not hurt on windows ? I see that as a cross-platform check, like ``specify-encoding``, the ``encoding="utf8"`` is useless on linux but it helps make the code better for windows users.

**Comment by DudeNr33** [comment]
I did not know about ``specify-encoding``, and the argument with cross-platform compatibility is valid.

**Comment by cdce8p** [comment]
I don't think we should add a `missing-shebang` check. Consider the following cases in which shebangs aren't necessary:
1. Python files can be "installed" / used with `entry_points`.
2. Just execute a python script with `python script.py`

**Comment by Pierre-Sassoulas** [comment]
Closing as the final comments is up-voted by 2 maintainers and the issue creator.
