### ISSUE TITLE
Use 2.9, 2.10, master/main or 3.0 series?

### ISSUE THREAD

**Issue by nth10sd** [PyCQA/pylint#4882]
### Question

Just curious, how long will pylint stay on the 2.x series? e.g. 2.9 was released a few weeks ago when 3.x was released, 2.10 was just released not long ago.

### Documentation for future user

Will 2.11, 2.12, 2.x be used for quite a long time before pylint makes the switch to 3.x?

**Comment by Pierre-Sassoulas** [comment]
Right now there is no urgency to release 3.0 as it would make a lot of conversation issue and milestone become obsolete and create a lot of project management work.  3.0 requires big refactor and as maintainer we're mainly handling issue and reviewing merge request, with no time to do major refactor. We did not make a lot of planned breaking changes in 3.0.0 alpha yet, only a fix for the json output that still need to be finalized. (This is also why there is not alpha equivalent for 2.10.0 yet, we had feedback for the json output that is not handled yet) So yes we're probably going to stick with 2 for some time.

**Comment by nth10sd** [comment]
Great, thanks for clarifying! It'll be nice to have this documented somewhere, or we could point folks here then.
