### ISSUE TITLE
Instance of 'Index' has no 'tz' member

### ISSUE THREAD

**Issue by lureza** [PyCQA/pylint#4910]
### Bug description

When running `pylint` (tested with versions 2.8.3 and 2.10.2) on a Python script with a `DatetimeIndex` variable, `pylint` raises an error when the `tz` attribute of the variable is being accessed. The errors are:

```bash
E1101: Instance of 'ExtensionIndex' has no 'tz' member (no-member)
E1101: Instance of 'Index' has no 'tz' member (no-member)
```

This is a bug since `date_range` returns a [`DatetimeIndex`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.date_range.html) object, which have a [`tz`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DatetimeIndex.tz.html) attribute.

#### Reproduction steps

Create a script `index_tz_member.py` with the following lines:

```python
import pandas as pd

days = pd.date_range("2021-08-01", "2021-08-31")
assert days.tz is None
```

This bug does not appear if using `pandas==1.2.4`.

This bug seems related to https://github.com/PyCQA/pylint/issues/3344

### Command used

```shell
pylint index_tz_member.py
```

### Pylint output

```shell
E1101: Instance of 'ExtensionIndex' has no 'tz' member (no-member)
E1101: Instance of 'Index' has no 'tz' member (no-member)
```

### Expected behavior

No error being raised by pylint.

### Pylint version

```shell
pylint 2.10.2
astroid 2.7.2
Python 3.8.10 (default, Jun  2 2021, 10:49:15)
```

### OS / Environment

Ubuntu 20.04

### Additional dependencies

pandas==1.3.2

**Comment by mbyrnepr2** [comment]
I cannot reproduce this one using:
```python
pylint --version
pylint 2.16.0-dev
astroid 2.13.0-dev0
Python 3.10.4

pip freeze |grep pandas
pandas==1.5.1
```

The results can change depending on the version of Pandas used; there is currently nothing pandas-specific in astroid to handle this.

@Pierre-Sassoulas  the `Needs astroid Brain` labelled is applied - Do you prefer an `astroid brain` to be the place to handle these issues or a `pylint_pandas` plugin?

**Comment by Pierre-Sassoulas** [comment]
Well obviously a panda plugin but as there is none afaik the brain is the best second thing we have.

**Comment by clavedeluna** [comment]
@mbyrnepr2 I also cannot reproduce this one, or the related https://github.com/PyCQA/pylint/issues/3344

I'm going to close both but if anyone believes this is still an issue please re-open.

**Comment by Pierre-Sassoulas** [comment]
@gaebor could you upgrade to latest pylint (3.0.2) and open a new issue if the problem still exists, please ?
