### ISSUE TITLE
Documentation: fix referencing/SEO & inter-linking

### ISSUE THREAD

**Issue by xmo-odoo** [PyCQA/pylint#4958]
When looking up pylint stuff, it's common for Google got still surface pages from the 1.6 documentation e.g. I was looking for the `too-many-lines` lint but didn't remember its exact name so hit google for [pylint module too long](https://www.google.com/search?hl=en&q=pylint%20module%20too%20long), and for me the first two lints on pylint.org are [the 1.6 FAQ](https://docs.pylint.org/en/1.6.0/faq.html) and [the 1.6 features page](https://docs.pylint.org/en/1.6.0/features.html).

And while RTD supports `link[rel="canonical"]` which is supposed to fix this issue, it might be that search engines ignore it because the features page has moved, meaning the canonical page RTD advertises [is a 404](https://docs.pylint.org/en/latest/features.html). I don't know if RTD supports remapping (or redirections) so that might have to be done by hand in google's backend or something.

A second related issue is that while there is a banner on the Features page advertising "v2.10.2" as the latest stable, because the page has moved between versions the link is dead much like RTD's.

**Comment by Pierre-Sassoulas** [comment]
There is a redirection feature available in readthedoc so it's possible to do, but the biggest work is figuring out what need to be redirected where.

**Comment by Pierre-Sassoulas** [comment]
The SEO is pretty good since we created a page for each messages. I'm going to close as won't fix for the other issue because retro-compatibility and redirection for everything in the old doc is going to be really hard and not very impactful now that searching for a message bring something in the first page of results.
