### ISSUE TITLE
Pylint b64encode

### ISSUE THREAD

**Issue by NikaBatsmanova** [PyCQA/pylint#4994]
### Bug description

```python
Module 'base64' has no 'b64encode' memberpylint(no-member)
```

### Configuration

```ini
VSCode 
Версия: 1.60.0 (user setup)
Фиксация: e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff
Дата: 2021-09-01T10:41:52.311Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
ОС: Windows_NT x64 10.0.19042
```

### Command used

```shell
pylint base64
```

### Pylint output

```shell
Module 'base64' has no 'b64encode' memberpylint(no-member)
```

### Expected behavior

Your code has been rated at 10/10

### Pylint version

```shell
pylint 2.10.2
```

### OS / Environment

Выпуск	Windows 10 Pro
Версия	20H2
Дата установки	‎10.‎11.‎2020
Сборка ОС	19042.1165
Взаимодействие	Windows Feature Experience Pack 120.2212.3530.0

### Additional dependencies

aniso8601==8.1.0
astroid==2.7.3
attrs==20.3.0
Automat==20.2.0
autopep8==1.5.7
certifi==2020.12.5
cffi==1.14.4
chardet==4.0.0
click==7.1.2
colorama==0.4.4
constantly==15.1.0
cors==0.9.7
cryptography==3.3.1
cssselect==1.1.0
filelock==3.0.12
Flask==1.1.2
Flask-Cors==3.0.10
Flask-RESTful==0.3.8
future==0.18.2
gevent==21.1.2
greenlet==1.0.0
hyperlink==21.0.0
idna==2.10
incremental==17.5.0
isort==5.9.3
itemadapter==0.2.0
itsdangerous==1.1.0
Jinja2==2.11.2
jmespath==0.10.0
jsonpath==0.82
lazy-object-proxy==1.6.0
lxml==4.6.2
MarkupSafe==1.1.1
mccabe==0.6.1
parse==1.19.0
parsel==1.6.0
platformdirs==2.3.0
psycopg2==2.8.6
pyasn1==0.4.8
pyasn1-modules==0.2.8
pybase64==1.2.0
pycodestyle==2.7.0
pycparser==2.20
PyHamcrest==2.0.2
pylint==2.10.2
pyTelegramBotAPI==3.7.6
pytz==2020.5
requests==2.25.1
requests-file==1.5.1
six==1.15.0
tldextract==3.1.0
toml==0.10.2
ujson==4.0.2
urllib3==1.26.2
w3lib==1.22.0
Werkzeug==1.0.1
wrapt==1.12.1
zope.event==4.5.0
zope.interface==5.2.0

**Comment by Pierre-Sassoulas** [comment]
I don't understand the issue the way it is right now, what is the code pylint was runned on ?

**Comment by DanielNoord** [comment]
@NikaBatsmanova Could you provide the code you ran `pylint` over?
