### ISSUE TITLE
Support Pytest fixture defines and can recognize fixture inject to testcase 

### ISSUE THREAD

**Issue by oslo254804746** [PyCQA/pylint#4999]
### Current problem

when use Pylint to scan Pytest testcase, If use pytest fixture to inject attrs, Pylint will report `E1101: Instance of 'x' has no 'xx' member` Error, I had write custom checker to avoid this, but some `assign` obj is very diffcult to resolve......

### Desired solution

pytest testcase when use fixture which add testcase cls attr, pylint may report an no attr error, like this:

`# conftest.py
import pytest
import logging
from lib.ssh import SSHClient

@pytest.fixture(scope='class')
def add_logger(request):
    request.cls.logger = logging.Logger(__name__)

@pytest.fixture(scope='class', autouse=True)
def add_ssh(request):
    request.cls.ssh = SSHClient(
        username='root',
        password="234234",
        host='127.0.0.1',
        port=22
    )`

and a single test py file

`import pytest

@pytest.mark.usefixtures('add_logger')
class TestPylint:

    def setup(self):
        pass

    @pytest.mark.TestCaseMark(author="pwd")
    def test_pylint_with_fixture(self):
        assert self.logger
        assert self.ssh
`

In this case, when I use pylint to scan this file it will report errors:
`************* Module pylinttest.test_pylint
pylinttest/test_pylint.py:1:0: C0114: Missing module docstring (missing-module-docstring)
pylinttest/test_pylint.py:5:0: C0115: Missing class docstring (missing-class-docstring)
pylinttest/test_pylint.py:7:4: C0116: Missing function or method docstring (missing-function-docstring)
pylinttest/test_pylint.py:11:4: C0116: Missing function or method docstring (missing-function-docstring)
pylinttest/test_pylint.py:12:15: E1101: Instance of 'TestPylint' has no 'logger' member (no-member)
pylinttest/test_pylint.py:13:15: E1101: Instance of 'TestPylint' has no 'ssh' member (no-member)
`

There are some plugins can resolve this problem and I had write my personal plugin to resolve this problem, but I suggest Pylint support Pytest case.

**Comment by Pierre-Sassoulas** [comment]
There's [pylint-pytest](https://pypi.org/project/pylint-pytest/) for that. Generally if there's something specific to a library to be done it will be an external plugin (see [pylint-django](https://pypi.org/project/pylint-django/) for example).
