### ISSUE TITLE
Pylint does not support astroid 2.8.0

### ISSUE THREAD

**Issue by HilitOreny** [PyCQA/pylint#5011]
### Bug description

```python
I manually updated astroid from version 2.7.3 to version 2.8.0.

Pip's dependency resolver warned me about the following dependency conflict:
pylint 2.10.2 requires astroid<2.8,>=2.7.2, but you have astroid 2.8.0 which is incompatible.
```

### Command used

```shell
Pylint was not invoked.
```

### Pylint output

```shell
Pylint was not invoked.
```

### Expected behavior

Please support astroid 2.8.0

### Pylint version

```shell
pylint 2.10.2
astroid 2.8.0
pip 21.2.4
Python 3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit (AMD64)] on win32
```

### OS / Environment

Windows 10 Home 64-bit (version 10.0.19043.1202) Laptop

**Comment by DanielNoord** [comment]
We are currently working on `pylint` 2.11.0 which does support `astroid` 2.8.0. Looking at the 2.11.0 [milestone](https://github.com/PyCQA/pylint/milestone/39) I don't think it will take long until 2.11.0 is released. Until then you will need to downgrade back to `astroid` 2.7.3 to keep using `pylint`.

**Comment by Pierre-Sassoulas** [comment]
We won't make old versions of pylint compatible with new astroids. Astroids is released before pylint so there will always be a short period when the latest published pylint isn't compatible with the latest published astroid (as indicated by the requirements in the packaging).
