### ISSUE TITLE
Possibly move ``MessagesHandlerMixIn`` into ``PyLinter``

### ISSUE THREAD

**Issue by DanielNoord** [PyCQA/pylint#5108]
### Current problem

The `MessagesHandlerMixIn` currently sits in its own document within the `pylint/message` directory. [Link](https://github.com/PyCQA/pylint/blob/main/pylint/message/message_handler_mix_in.py)
The class is always mixed with `PyLinter` except for one occasion where a class method is used.

https://github.com/PyCQA/pylint/blob/86c073e49fc099d8111da96cfbb2f30ccd659338/pylint/message/message_handler_mix_in.py#L235-L258
One of its most used methods is `add_message`, which handles the messages added by all checkers. However, this method is also a good example of why we are running into trouble with `MessagesHandlerMixIn` being its own class. We added `self: "PyLinter"` because we needed the `PyLinter` annotation for `self.msgs_store.get_message_definitions(msgid)`. However, `add_message` is also called from within `MessagesHandlerMixIn` and `self` is then not `PyLinter`. `mypy` complains about this (justifiably). 
There are many more methods were we basically need to type `self` as being simultaneously `PyLinter` and `MessagesHandlerMixIn`.
I have created a [branch](https://github.com/DanielNoord/pylint/tree/typing-message-mix-in) with a commit that adds typing to `MessagesHandlerMixIn`. You can clone this branch locally and see that `mypy` will fail with 20+ errors all related on the double dependency of `PyLinter` and `MessagesHandlerMixIn`.

### Desired solution

I would propose to merge `MessagesHandlerMixIn` into `PyLinter` to avoid these problems of dependency on each other. 

Another solution would be to find a way to type `self` to be two classes simultaneously. But I don't think this is possible (or desirable in general).

**Comment by Pierre-Sassoulas** [comment]
I hate the current design, so I like this proposition ! But merging pylinter and MessageHandlerMixin could mean having to extract an independant MessageHandler class and possibly others because the pylinter class already is humungous.

**Comment by DanielNoord** [comment]
I wonder how many methods will remain for the independent class. A quick look shows that most current methods use attributes/methods from most classes. 

We could separate those into different method that call each other but that might make the code more confusing, for example with `add_message`. 
I can take a look at this after the work on `LinterStats` has been approved and merged. I'll assign myself.

Input from others is still appreciated!
