### ISSUE TITLE
Support Enum with self defined members 

### ISSUE THREAD

**Issue by OldIMP** [PyCQA/pylint#5138]
### Current problem

False positive E1101 are reported for self defined member in Enums. 

Example:
- [Enum `Layout` w/ self defined members `col` & `row`](https://github.com/OldIMP/volksschule/blob/ba0dc09ad4590439d5ae8c3c7b7639b45869db70/r_quiz.py#L139)
- [Here](https://github.com/OldIMP/volksschule/blob/ba0dc09ad4590439d5ae8c3c7b7639b45869db70/r_quiz.py#L174) will then be reported falsely as E1101:
  > r_quiz.py:174:12: E1101: Instance of 'SIMPLE' has no '`row`' member (no-member)
  > r_quiz.py:174:12: E1101: Instance of 'SCHRIFTLICH' has no '`row`' member (no-member)
  > r_quiz.py:174:25: E1101: Instance of 'SIMPLE' has no '`col`' member (no-member)
  > r_quiz.py:174:25: E1101: Instance of 'SCHRIFTLICH' has no '`col`' member (no-member)

#### pylint --version
pylint 2.11.1
astroid 2.8.2
Python 3.9.7 | packaged by conda-forge | (default, Sep 29 2021, 19:15:42) [MSC v.1916 64 bit (AMD64)]

### Desired solution

According to [Python doc](https://docs.python.org/3/library/enum.html#planet), self defined members in Enums are allowed. Therefore no issues should be reported for the example above.

**Comment by marianhlavac** [comment]
Any progress on this?
