### ISSUE TITLE
Compatibility issue with package requiring older `typing-extensions`

### ISSUE THREAD

**Issue by Pierre-Sassoulas** [PyCQA/pylint#5186]
### Bug description

```python
It's impossible to install pylint 2.11+ or astroid 2.8.3 and tensorflow 2.4.1 in the same environment.
```

### Command used

```shell
`pip install tensorflow==2.4.1 pylint==2.11.1`
```

### Pylint output

```shell
ERROR: Cannot install mypackage and tensorflow==2.4.1 because these package versions have conflicting dependencies.
The conflict is caused by:
pylint 2.11.1 depends on typing-extensions>=3.10.0; python_version < "3.10"
tensorflow 2.4.1 depends on typing-extensions~=3.7.4
To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
```
Or by cheating: 
```shell
ERROR: astroid 2.8.3 has requirement typing-extensions>=3.10; python_version < "3.10", but you'll have typing-extensions 3.7.4.3 which is incompatible.
ERROR: pylint 2.11.1 has requirement typing-extensions>=3.10.0; python_version < "3.10", but you'll have typing-extensions 3.7.4.3 which is incompatible.
```

### Expected behavior

Being able to install pylint despite the typing extensions. typing-extensions is not critical, and we still have a lot of typing to add.

### Pylint version

```shell
2.11.0+
```

### Additional dependencies

tensorflow 2.4.1

**Comment by DanielNoord** [comment]
Based on https://github.com/tensorflow/tensorflow/issues/44654#issuecomment-921529858 I think this might be fixed in the next release of TF and was due to TF being too restrictive.

**Comment by Pierre-Sassoulas** [comment]
I was wondering is there's a way to stay compatible with older version of typing extension, but let's close then. Seeing the issue you linked it's seems that using a less restrictive requirement in tensorflow is not an issue at all for them

**Comment by DanielNoord** [comment]
Although we could explore this option, I don't think this should be necessary for `typing extension`. It's based on `typing` and thus on PEPs which in general seem to favour not changing existing coding patterns. So, most projects shouldn't really have an upper bound for `typing extension` and only a lower bound for when a particular feature the project used was added. Obviously this might change in the future, but seeing as TF could change so easily I think for now this holds true.
