### ISSUE TITLE
pylint.extensions.docparams default options are not working correctly

### ISSUE THREAD

**Issue by adamcunnington-gdt** [PyCQA/pylint#5223]
### Bug description

The [documentation for pylint.extensions.docparams](https://pylint.pycqa.org/en/latest/technical_reference/extensions.html#parameter-documentation-checker-options) describes that by default, `accept-no-yields-doc` and `accept-no-return-doc` are **yes** (along with other configuration options).

However, if I run `pylint myfile.py` with no pylint configuration except for enabling the plugin*, I see lots of entries of:

```
... W9011: Missing return documentation (missing-return-doc)
... W9013: Missing yield documentation (missing-yield-doc)
```

\* my only configuration is:
```toml
[tool.pylint.master]
load-plugins = ["pylint.extensions.docparams"]
```

In all situations, I am deliberately excluding :yields: and :rtype: from the docstring because I am using type annotations.

Am I missing something or is the documented behaviour wrong?

### Pylint version

```shell
pylint 2.11.1
astroid 2.8.4
Python 3.9.5 (default, May  8 2021, 00:04:35) 
[GCC 8.3.0]
```

### OS / Environment
Debian Buster

**Comment by DanielNoord** [comment]
@Pierre-Sassoulas Pinging you again because I think you might have missed this. 

If you just didn't have time to look at this, please consider this message unsent!

**Comment by Pierre-Sassoulas** [comment]
It look like the original intent in #934 was to permit to disable part of the check, so I guess it's a (somewhat solidified with tests since ?) bug and we should update the code, and tests.
