### ISSUE TITLE
How to ignore typing stub pyi files? ignore-options don't work/break

### ISSUE THREAD

**Issue by ewerybody** [PyCQA/pylint#5230]
### Question

Hello! I'm using latest pylint through VS Code `1.61.2` and often have a couple super long `.pyi` files open.
Most of these are not written by me and I'm not interested in any issues there.

But I AM interested in pylint judging my very own code. So: HOW do I make it so that it ignores these `pyi`s?
From [the features documentaion](https://pylint.pycqa.org/en/latest/technical_reference/features.html) there are a couple of ignore options:
* `--ignore=*.pyi` - no change at all as if it wasn't there
* `--ignore-paths=*.pyi` or `--ignore-patterns=*.pyi` causes empty pylint returns like:
    ```
    ...
    ##########Linting Output - pylint##########
    ##########Linting Output - pylint##########
    ##########Linting Output - pylint##########
    ##########Linting Output - pylint##########
    ##########Linting Output - pylint##########
    ```
    at least in VS Code.
    If I try this in the commandline it yields a huge traceback:
    ```
    Traceback (most recent call last):
    File "C:\Python39\lib\runpy.py", line 197, in _run_module_as_main
        return _run_code(code, main_globals, None,
    File "C:\Python39\lib\runpy.py", line 87, in _run_code
        exec(code, run_globals)
    File "C:\Python39\Scripts\pylint.exe\__main__.py", line 7, in <module>
    File "C:\Python39\lib\site-packages\pylint\__init__.py", line 24, in run_pylint
        PylintRun(sys.argv[1:])
    File "C:\Python39\lib\site-packages\pylint\lint\run.py", line 332, in __init__
        args = linter.load_command_line_configuration(args)
    File "C:\Python39\lib\site-packages\pylint\config\option_manager_mixin.py", line 342, in load_command_line_configuration
        (options, args) = self.cmdline_parser.parse_args(args=args)
    File "C:\Python39\lib\optparse.py", line 1387, in parse_args
        stop = self._process_args(largs, rargs, values)
    File "C:\Python39\lib\optparse.py", line 1427, in _process_args
        self._process_long_opt(rargs, values)
    File "C:\Python39\lib\optparse.py", line 1501, in _process_long_opt
        option.process(opt, value, values, self)
    File "C:\Python39\lib\site-packages\pylint\config\option.py", line 168, in process
        value = self.convert_value(opt, value)
    File "C:\Python39\lib\optparse.py", line 771, in convert_value
        return self.check_value(opt, value)
    File "C:\Python39\lib\optparse.py", line 766, in check_value
        return checker(self, opt, value)
    File "C:\Python39\lib\site-packages\pylint\config\option.py", line 25, in _regexp_csv_validator
        return [_regexp_validator(_, name, val) for val in _csv_validator(_, name, value)]
    File "C:\Python39\lib\site-packages\pylint\config\option.py", line 25, in <listcomp>
        return [_regexp_validator(_, name, val) for val in _csv_validator(_, name, value)]
    File "C:\Python39\lib\site-packages\pylint\config\option.py", line 20, in _regexp_validator
        return re.compile(value)
    File "C:\Python39\lib\re.py", line 252, in compile
        return _compile(pattern, flags)
    File "C:\Python39\lib\re.py", line 304, in _compile
        p = sre_compile.compile(pattern, flags)
    File "C:\Python39\lib\sre_compile.py", line 764, in compile
        p = sre_parse.parse(p, flags)
    File "C:\Python39\lib\sre_parse.py", line 948, in parse
        p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
    File "C:\Python39\lib\sre_parse.py", line 443, in _parse_sub
        itemsappend(_parse(source, state, verbose, nested + 1,
    File "C:\Python39\lib\sre_parse.py", line 668, in _parse
        raise source.error("nothing to repeat",
    re.error: nothing to repeat at position 0
    ```
this .. could also be a bug🐛? I don't know 😶 

### Documentation for future user

I'd like to see some examples on what to write on the ignore options here:
https://pylint.pycqa.org/en/latest/technical_reference/features.html

And maybe what NOT as well.

**Comment by Pierre-Sassoulas** [comment]
It look like we could also handle bad regex more gracefully, as it look like pylint crashed because of a regex.

**Comment by ewerybody** [comment]
@DanielNoord plz pardon the late reply.
I can confirm:
* `"--ignore-patterns=.*.pyi"` works ✔
* `"--ignore-paths=.*.pyi",` works ✔
* `"--ignore=.*.pyi",` does not work ❌ 

Why that is and what should be where: I'd really like to read in the documentation :)

**Comment by DanielNoord** [comment]
We might want to change `regex` in the docs to `regular expressions`? Would that be clearer for you? Other than that I don't really know how this could be made clearer in the docs..

**Comment by ewerybody** [comment]
Have some examples for each option.
In **text** as in "Use this to do ..."
and in **code** like `=test.py,test_something_else.py` or with the above: `.*.ext` to exclude `.ext`-files or an example with something in the middle like `=*ignore_me*`?. And if these can be separated by commas or semi-colons?

If too convoluted, there could even be a link to examples for these.

**Comment by ewerybody** [comment]
The term `regex` is not the problem. But **how**! I mean I'm not fluent in these but to me it is not clear why `.*.pyi` works and `*.py` breaks the whole thing.

**Comment by DanielNoord** [comment]
I'll try and think of a good example, which is also not too long. I don't want think we want to give a full tutorial on regex in those few lines 😄 

As Pierre said, breaking on incorrect regex should never happen and is an issue on its own.

> The term `regex` is not the problem. But **how**! I mean I'm not fluent in these but to me it is not clear why `.*.pyi` works and `*.py` breaks the whole thing.

This breaks because in in regex `*` needs something to repeat. A `.` stands for "any type of character so `.*.pyi` means an unlimited amount of characters followed by a single "any type of character" followed but `pyi`.
With `*.py` there is nothing to repeat by `*` so the pattern breaks. I really like https://regex101.com to test out my regex's and the site also has a good debugger!

**Comment by ewerybody** [comment]
Oh yes! thanks!🙇‍♀️ That's a pretty sweet page! ✔**bookmarked**.

I just see to actually match `anybasename.pyi` we'd need the regex: `.*\.pyi` ! It would grab `name.blapyi` otherwise as well.

So far I'm just familiar with the `*.*` type. I thought it to be common for when it's about files. Works in the Windows File Explorer search. Works with Pythons `fnmatch`, Works in the VS Code search include/exclude patterns ... I had no idea thats not "real" regex :D
