### ISSUE TITLE
Create test for exclusivity of message id prefixes

### ISSUE THREAD

**Issue by DanielNoord** [PyCQA/pylint#5255]
I think the prefixes have an important aim: to make sure that a checker can evolve to new message types with the security that the corresponding ids are not used yet.

Take a checker that only emits F3101 and F3102. At some point we might think of a new message for that checker, which does not go at the Fatal level. We would then want to emit E3101. If we do not "reserve" the "31" prefix for this checker it might actually be the case that another checker is already issuing E3101 and E3102. Thus the first checker would then need to emit F3101, F3102 and E3201.
Although this might not create immediate inconsistenties, illogical numbering of messages like this will (probably) create problems in the future (just like we are seeing now). In any case it will make maintaining `pylint` more "illogical" and thus (probably) more difficult.

I can understand that you do not want to change the id for any of the current messages, but I would really argue against removing the restriction all together. I think I'll be able to create a test that sees if a checker has a unique message id prefix, while ignoring the 4/5 prefixes that are currently non-exclusive. I think that would be the best way forward here!

_Originally posted by @DanielNoord in https://github.com/PyCQA/pylint/issues/5248#issuecomment-959866640_

Further discussion in that PR.

**Comment by cdce8p** [comment]
Just a thought: Do we really want to allow `F3101` and `E3101` to coexist?

I would probably prefer if each number is unique, even if that results in `E3103`. It's far to easy to confuse `E` and `F`, especially for users who don't know about it.

**Comment by DanielNoord** [comment]
I think you're making a good point and I would like to follow that logic. However, that would be an even larger breaking change than making prefixes exclusive. Do you want to start a discussion/proposal on doing this, or only from now on?

In any case, when creating this test I can probably also write a test that new message should have an exclusive number as well as each checker having an exclusive prefix.

**Comment by cdce8p** [comment]
I would prefer to avoid renaming existing message numbers as much as possible. If at all, this should probably be done for `3.0`.

For now, my proposal would be to consider this only for new checks being added.

--
Another thing, if each checker gets its own prefix, we are essential limited to `100`. That might work for us, but what about `plugins`? Should we consider 5 digits? For existing checks, we could add a leading `0`. We need to keep in mind though that is might also be a breaking change. So I suggest `3.0` for it, too.

**Comment by DanielNoord** [comment]
Based on our own code I think we already reserve `> 50` for plugins.
https://github.com/PyCQA/pylint/blob/16c09cb48a3c66f453faccdf380aea6969d61202/pylint/checkers/__init__.py#L43

So we are already (officially) limiting ourselves to `50`.

Accepting five digits would indeed need to got in a `x.0` update. I think when we start to use prefix 40/45 we might want to consider this, but for now it seems a bit premature?

**Comment by cdce8p** [comment]
> Based on our own code I think we already reserve `> 50` for plugins.
> 
> https://github.com/PyCQA/pylint/blob/16c09cb48a3c66f453faccdf380aea6969d61202/pylint/checkers/__init__.py#L43
> 
> So we are already (officially) limiting ourselves to `50`.
> 
> Accepting five digits would indeed need to got in a `x.0` update. I think when we start to use prefix 40/45 we might want to consider this, but for now it seems a bit premature?

Is it though? Don't think we are planning on doing major release regularly. So it might make sense to include it.

**Comment by DanielNoord** [comment]
Yeah you're right, we should probably tackle this while we can.

I can create an issue, add to the milestone `3.0` and create a `3.0` project if you want me to?

If so, the current milestone has two very old issues attached to it? Do we want to keep those for `3.0`? Or should I move the current `3.0` milestone to a new milestone (and what should I then name it)?

**Comment by cdce8p** [comment]
> I can create an issue, add to the milestone `3.0` and create a `3.0` project if you want me to?
>
> If so, the current milestone has two very old issues attached to it? Do we want to keep those for `3.0`? Or should I move the current `3.0` milestone to a new milestone (and what should I then name it)?

Let's leave the `3.0` milestone alone for now. It's still some time away. I would suggest we track those tasks just in a project for now. Create a bare bone one for it: https://github.com/PyCQA/pylint/projects/12
(Sadly, the new project boards aren't supported on a repository level just jet.)

**Comment by Pierre-Sassoulas** [comment]
Once this is done we can add the script to pre-commit to avoid issue with new checkers like in https://github.com/PyCQA/pylint/pull/5470
