### ISSUE TITLE
Generated man page for pylint are untested and unused

### ISSUE THREAD

**Issue by Pierre-Sassoulas** [PyCQA/pylint#5283]
### Question

@sandrotosi, how do you generate the man page for pylint when you release ? Is that handled in your own debian repository for pylint ? After some retro-engineering I realized that the generation functions still exist, but are untested and probably unused (?) 

### Documentation for future user

The option for man page generation should be detailed /tested or removed.

**Comment by sandrotosi** [comment]
we dont generate the manpages; we noticed they were removed recently from the archive, and we simply stop installing them altogether.

**Comment by Pierre-Sassoulas** [comment]
Thank you for the quick answer. We removed them because they were very out of date some time ago. If I understand well the outdated one were used, so either we keep not providing man pages or we provide you with a script and a documentation to generate them for a release.
