### ISSUE TITLE
Document setup with pre-commit

### ISSUE THREAD

**Issue by adamchainz** [PyCQA/pylint#5291]
### Current problem

I can see the `.pre-commit-hooks.yaml` file in the repository, but I can't find any documentation on how to set it up.

### Desired solution

A short section on how to set up pre-commit like https://flake8.pycqa.org/en/latest/user/using-hooks.html

**Comment by DanielNoord** [comment]
There is a short introduction to it here:
https://github.com/PyCQA/pylint/blob/main/doc/development_guide/contribute.rst
(Search for `pre-commit`, sadly I can't seem to link to line numbers in `rst` files).

It is rendered like this:
https://pylint.pycqa.org/en/latest/development_guide/contribute.html#repository


I agree it might not be as visible and clear as the `flake8` one. If you have any specific suggestions on how to improve that section please feel to open a PR committing to that file or discuss them here. I can also make a PR based on your suggestions :)

**Comment by adamchainz** [comment]
That's about setting up the pre-commit hooks for contributing to Flake8. It's not about how to add pylint to *my* project via pre-commit.

**Comment by adamchainz** [comment]
More context: I'm writing a book covering some code quality tools, using pre-commit, and I want somewhere to link to with install instructions.

**Comment by DanielNoord** [comment]
Ah sorry I misunderstood your question. I think I should be able to write something to link to in the coming days.

**Comment by Pierre-Sassoulas** [comment]
The specificity of pylint is that it requires to be a system hook because it needs to be able to import the dependencies of the code to analyze it properly. I agree that we should add this documentation. There's some detail in #4505
