### ISSUE TITLE
Follow-up to primer tests for pylint 2.12.2

### ISSUE THREAD

**Issue by Pierre-Sassoulas** [PyCQA/pylint#5306]
- [x] #5315 
- [ ] #5364
- [x] #5387 -> Create ``primer`` marker with ``addoption``. This allows removal of ``ignore=primer`` in settings and full discovery of tests in IDEs. See https://docs.pytest.org/en/6.2.x/example/simple.html -> 
- [x] Improve error message and provide information of error location on fail
- [x] Stop running all CI jobs if one jobs fails.
- [x] #5387 -> Add documentation
- [x] #5359 First step done in https://github.com/PyCQA/pylint/pull/5425

**Comment by Pierre-Sassoulas** [comment]
@DanielNoord I would put the better primer in 2.13 at least, even 2.14 for false positive detection, what do you think ?

**Comment by DanielNoord** [comment]
I think we can close this, make quality of life improvements for `2.13` and add false positive detection in `2.14` and beyond. I'll update the `2.13` issue with some other things I thought of!

**Comment by Pierre-Sassoulas** [comment]
Done in #5425
