### ISSUE TITLE
Add checkers for names annotated with typing.Final

### ISSUE THREAD

**Issue by mbyrnepr2** [PyCQA/pylint#5313]
### Current problem

Add three checkers related to `typing.Final` which was introduced in Python version 3.8 
- `overridden-final-name`
- `redefined-final-name`
- `using-final-annotation-in-unsupported-version`

This is a similar issue to https://github.com/PyCQA/pylint/issues/3197 where checkers related to the `typing.final` decorator were added. It is also suggested in a comment on that issue.
It is also similar to https://github.com/PyCQA/pylint/issues/5134 where an unsupported-version checker was added for the `typing.final` decorator.

### Desired solution

Scenario 1 - Running pylint with Python version 3.8 or later (or py-version=3.8 or later):
`pylint my_test.py --py-version=3.8`
Emit `overridden-final-name` warning when a name is overridden in a subclass
Emit `redefined-final-name` warning when a name is re-defined

Scenario 2 - Running pylint with Python version lower than 3.8 (or py-version lower than 3.8)
`pylint my_test.py --py-version=3.7`
Emit `using-final-annotation-in-unsupported-version` warning when a name is overridden in a subclass or a name is re-defined

### Additional context

https://docs.python.org/3/library/typing.html#typing.Final
https://www.python.org/dev/peps/pep-0591/

**Comment by mbyrnepr2** [comment]
If it is an accepted issue it can be assigned to me.

**Comment by cdce8p** [comment]
Hmm 🤔 It's that what type checkers like `mypy` do, only much better?
It did make somewhat sense for the `typing.final` decorator as it's also useful in partially annotated code. The issue with `Final` however is that it's much more difficult (and expensive) to check. You would probably need to do lookups for every single `Name` and `Attribute` node. Not to mention that `Final` is part of the variable annotation which can also be a string.

All in all I feel like type checkers can do a much better job here.

As for `using-final-annotation-in-unsupported-version`, something like [flake8-typing-imports](https://github.com/asottile/flake8-typing-imports) can do that, too.

**Comment by Pierre-Sassoulas** [comment]
Thank you for pitching the idea :) ! There's still a lot of issue around typing if you want to contribute to that @mbyrnepr2 :)
