### ISSUE TITLE
Remove module lines in "text" and "parseable" reporter

### ISSUE THREAD

**Issue by cykerway** [PyCQA/pylint#5362]
Any chance we can have an option to remove these module lines from "text" reporter? They are annoying when parsing the messages and require an extra step of filtering. This is also true for the "parseable" reporter. At least make this option available in the "parseable" reporter?

https://github.com/PyCQA/pylint/blob/d29bcf68393b6a1654aa6cd3d5351ed63edb42ad/pylint/reporters/text.py#L198

**Comment by Pierre-Sassoulas** [comment]
There are [multiple easily parseable outputs](https://pylint.pycqa.org/en/latest/user_guide/output.html#output-options) , we're not going to make a breaking change to the output without a really good reason.

**Comment by cykerway** [comment]
There aren't "multiple" easily parseable outputs. The only one I've found easily parseable is the `json` reporter, which still isn't very easily with command line tools.

However, I found the "parseable" format is going to be deprecated:

https://github.com/PyCQA/pylint/blob/d29bcf68393b6a1654aa6cd3d5351ed63edb42ad/pylint/reporters/text.py#L222

It'd be very easy to keep it useful by overwriting `handle_message` like:

~~~python
def handle_message(self, msg: Message) -> None:
    """manage message of different type and in the context of path"""
    self.write_message(msg)
~~~

Is that by intention that pylint output is going be parsed in json anyway?

**Comment by cykerway** [comment]
Yes, I know this *intra-line* formatting is very configurable (and works great), but what I'm asking here is about *inter-line* formatting. Those extra `*************` markers are annoying when parsing pylint output using line-based command line tools. So what I'm doing now is writing:

~~~bash
pylint ... | grep -v '\*\*\*\*\*\*\*\*\*\*\*\*\*'
~~~

As you can see this is awkward. If you omit those markers we can save the `grep`. Given that you are deprecating `parseable`, maybe keeping it for such use is a better idea.

**Comment by clavedeluna** [comment]
@Pierre-Sassoulas what's the right way to add a new configuration options, such as `--no-header`? I'm looking thru the code and it's confusing, probably because it's streamlined. Is it to add this option to base_options.py? Somewhere else?

**Comment by Pierre-Sassoulas** [comment]
You can check ``_make_run_options`` in ``pylint.lint.base_options.py``, there's pre-processing of some options elsewhere, but I don't think we need pre-processing for this one.
