### ISSUE TITLE
Catch same names for exceptions in nested try-except blocks

### ISSUE THREAD

**Issue by birkenfeld** [PyCQA/pylint#5370]
### Current problem

Given this code
```py
try:
    something
except Exception as err:
    try:
        something else
	except Exception as err:
		handle
	print(err)
```

Depending on whether the second `except` triggers, `err` will be undefined in the print statement.

### Desired solution

Pylint should probably catch this and suggest to rename one of the `err` variables.

**Comment by jacobtylerwalls** [comment]
Good candidate for `redefined-outer-name`.
