### ISSUE TITLE
pylint_fail_under failing since pylint 2.12.0

### ISSUE THREAD

**Issue by PascalRoose** [PyCQA/pylint#5405]
### Bug description

After updating Pylint to 2.12.1 (also tried 2.12.0) it seems that pylint_fail_under does not work properly anymore. After downgrading to 2.11.1 everything seemed to work as expected.

### Command used

```shell
pylint-fail-under --fail_under 7.0 --rcfile=.pylintrc src
```

### Pylint output

```shell
-----------------------------------
Your code has been rated at 8.73/10

Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\***\venv\Scripts\pylint-fail-under.exe\__main__.py", line 7, in <module>
  File "c:\users\***\venv\lib\site-packages\pylint_fail_under\__main__.py", line 42, in main
    score = results.linter.stats["global_note"]
TypeError: 'LinterStats' object is not subscriptable
```

### Expected behavior

Would expect the program to exit with proper exit code, without raising an exception.

### Pylint version

```shell
pylint-fail-under 0.3.0

pylint 2.12.0
astroid 2.9.0
Python 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 24 2018, 00:16:47) [MSC v.1916 64 bit (AMD64)]
```

### OS / Environment

Windows 10 Enterprise

**Comment by Pierre-Sassoulas** [comment]
Do not use ``pylint-fail-under``, we have a fail-under option directly in pylint.

```diff
-pylint-fail-under --fail_under 7.0 --rcfile=.pylintrc src
+pylint --fail-under=7.0 --rcfile=.pylintrc src
```

**Comment by PascalRoose** [comment]
@Pierre-Sassoulas Did not know about this. Seems like all of my CI/CD pipelines need an update. Thanks for your help!

**Comment by parvathirajan** [comment]
> 

@Pierre-Sassoulas Sorry to bother you again, Still `--fail-under` is not failing for me, even the score is lesser. It should return exit code 1 but it doesn't. 

```bash
run_check (){
    message="LOCATION: $repo_dir"
    echo -e "\033[1;34mInfo: $message\033[0m"
    
    message="CHECK: Checking with '$check_name'"
    echo -e "\033[1;34mInfo: $message\033[0m"
    
    pylint --fail-under=8.0 --rcfile=.pylintrc $repo_dir
    
    if [ $? -eq 1 ]; then
        message=$2
        echo -e "\033[1;31mERROR: $message\033[0m";
        exit 1
    else
        message="[PASSED] Passed $check_name checking."
        echo -e "\033[1;32mOK: $message\033[0m"
        exit 0
    fi
}
```

**Output:**

```bash
------------------------------------------------------------------
Your code has been rated at 7.76/10 (previous run: 7.76/10, +0.00)

OK: [PASSED] Passed pylint checking.
```

**Comment by Pierre-Sassoulas** [comment]
@parvathirajan the exit code is not necessarily 1, it's [a bit encoded exit code](https://pylint.pycqa.org/en/latest/user_guide/run.html?highlight=exit%20code#exit-codes) from 0 to 32

**Comment by parvathirajan** [comment]
> @parvathirajan the exit code is not necessarily 1, it's [a bit encoded exit code](https://pylint.pycqa.org/en/latest/user_guide/run.html?highlight=exit%20code#exit-codes) from 0 to 32

Oh Sorry! I felt really dumb here, Didn't read the word it's a bit encoded. tested it, and it's working as expected.

Also one more question if you don't mind me ☺️ Is there a way that I can get the output of the score, from pylint cmd.

Like how we can do it with `Run` - `score = results.linter.stats.global_note`?

**Comment by Pierre-Sassoulas** [comment]
No problem :) The score is shown in the output by default ``Your code has been rated at 7.76/10 (previous run: 7.76/10, +0.00)`` you could also use a custom reporter. The json reporter will have score in pylint 3.0 for example see #4741 .

**Comment by parvathirajan** [comment]
Amazing Work! hats off, Thank you so much and I really appreciate your help. Will try to contribute in the future. :)
