### ISSUE TITLE
Check imports of private modules / variables (with leading underscores)

### ISSUE THREAD

**Issue by cgebbe** [PyCQA/pylint#5463]
### Current problem

Given a file like

```
from hello import _world
import _my_private_module
```

### Desired solution

... I would wish for an error message that says: "Error: Import of private module / object"

Or have I overlooked something in https://pylint.pycqa.org/en/latest/technical_reference/features.html#imports-checker ?

**Comment by Pierre-Sassoulas** [comment]
Thank you for opening the issue, this seems reasonable.
