### ISSUE TITLE
Expose types

### ISSUE THREAD

**Issue by kasium** [PyCQA/pylint#5488]
### Current problem

Pylint support plugins which might want to type-check their code. Therefore it would be great, if pylint could expose it's types.

### Desired solution

Add missing types and add a `py.typed` file. Else add dedicated stubs files.

**Comment by DanielNoord** [comment]
Ref #2079

**Comment by kasium** [comment]
Thanks!

**Comment by jacobtylerwalls** [comment]
Blocked by PyCQA/astroid#1680
