### ISSUE TITLE
i want use pylint in github ci.how can i do?

### ISSUE THREAD

**Issue by Wangwuyi123** [PyCQA/pylint#5571]
### Question

i want use pylint in github workflow,How should I use it？

### Documentation for future user

    - name: Lint with Black
      run: |
        pip install --upgrade pip
        pip install black wheel
        black xxx

Similar to the format above

**Comment by Pierre-Sassoulas** [comment]
Hello, what did you try ? 
```
- name: Lint with Pylint
  run: |
    pip install --upgrade pip
    pip install pylint
    # pip install your dependencies
    pylint xxx
```

**Comment by Wangwuyi123** [comment]
I want to check all the .py files in the folder through pylint
And add this function to the continuous integration Ci, check all the pr
I did not find any relevant examples in your documentation

**Comment by Pierre-Sassoulas** [comment]
Please see https://pylint.pycqa.org/en/latest/user_guide/run.html#invoking-pylint
