### ISSUE TITLE
[Testing] `--update-functional-output` generates changes on main

### ISSUE THREAD

**Issue by jacobtylerwalls** [PyCQA/pylint#5650]
### Bug description

`--update-functional-output` generates quotation changes just on main branch, see:

https://github.com/PyCQA/pylint/compare/main...jacobtylerwalls:functional-output-diff

### Configuration

```ini
Or, is this my fault for not having a testing package installed?
```

### Command used

```shell
python test_functional.py --update-functional-output
```

### Pylint version

```shell
pylint 2.13.0-dev0
astroid 2.9.2
Python 3.10.1 (v3.10.1:2cd268a3a9, Dec  6 2021, 14:28:59) [Clang 13.0.0 (clang-1300.0.29.3)]
```

### OS / Environment

Tested on both MacOS 11.6 and 10.13.6

**Comment by DanielNoord** [comment]
Which OS are you using? I know I looked into this previously and thought all issues with escaping quotes in the functional tests had been fixed..

**Comment by jacobtylerwalls** [comment]
My fault for assuming not relevant. MacOS 11.6 and 10.13.6

**Comment by DanielNoord** [comment]
Hmm, I used the same OS to update all tests recently when we added end line and column.

@Pierre-Sassoulas added this specific test a couple of days ago. Could it be that the escaping is different on his OS? (Linux, I believe). That would be problematic

**Comment by Pierre-Sassoulas** [comment]
The second part of the diff is especially strange, it seems like it's not escaping and actually a different string entirely ?
```diff
- missing_raise_for_parent:"""NameError""" not documented as being raised:UNDEFINED
+ missing_raise_for_parent:"""NameError"" not documented as being raised":UNDEFINED
```

**Comment by DanielNoord** [comment]
No that's actually escaped correctly I think (for this system of escaping). The string is put between quotes and then any string within the string is double-quoted.

@Pierre-Sassoulas Could you test if you get the same diff on your local machine?

**Comment by Pierre-Sassoulas** [comment]
I can reproduce the issue under ubuntu with pyhon 3.8.

**Comment by DanielNoord** [comment]
But is the output different for `3.8` and `3.10`? As in, is there something wrong with our updater or does this test currently pass with incorrect escaping and will it be enough to just update it once?

**Comment by Pierre-Sassoulas** [comment]
It's the same diff. I guess to solve this long term we'd need to add a test for the update too ? I.e. no diff when launching the update. It would take a while for almost no benefit though.

**Comment by DanielNoord** [comment]
Yeah, this seems to be a rare case then. 

@jacobtylerwalls Since you found this, do you want to make a PR created by running the updater over all functional tests so they are all up to date again?

**Comment by jacobtylerwalls** [comment]
> do you want to make a PR created by running the updater over all functional tests so they are all up to date again?

Indeed, it was only these two strings! Done in #5660
