### ISSUE TITLE
Use `good first issue` label on issues

### ISSUE THREAD

**Issue by areveny** [PyCQA/pylint#5693]
### Current problem

GitHub now gives special meaning to the `good first issue` label on issues. I think it would be good to conform to this standard replacing `contributor friendly`.

Issues labeled with `good first issue` are surfaced in a couple places to help potential contributors find things to work on. Furthermore, not using the label means anybody trying to search on it will think there are no issues marked for new contributors which can be discouraging.

### Desired solution

Replace the `contributor friendly` label with `good first issue`.

Alternatively, use both with a slightly different meaning assigned to each, e.g. `good first issue` is something already investigated with a clear direction and a fairly simple closed-ended fix.

**Comment by DanielNoord** [comment]
Good suggestion and I think it makes sense.

However, I think before doing so it would be good to do some "maintenance" and see if these issues are actually beginner friendly. I like your "clear direction and a fairly simple closed-ended fix". I think for many of these issues a consensus on the name for the new checker is missing, which would greatly help with the "clear direction" aspect.

**Comment by Pierre-Sassoulas** [comment]
We also conflate "help wanted" with "beginner friendly" right now. Sometime an issue is very hard but we still want help 😄

**Comment by DanielNoord** [comment]
@areveny Did you move the labels? Or are we keeping them both?

**Comment by Pierre-Sassoulas** [comment]
I only changed the label content from "Contributor friendly" to "good first issue", as it's really fast / easy to do. Identifying "good first issue" in the current 700+open issues and checking that the current one are really "good first issue"  and not simply "help wanted" would take a huge time. I don't think I can do that as I'm already struggling with reviewing opened MR😄 So I agree with closing.
