### ISSUE TITLE
'missing-final-newline' is surprisingly slow on a large codebase

### ISSUE THREAD

**Issue by skirpichev** [PyCQA/pylint#5724]
### Bug description

I'm trying to enable the 'missing-final-newline' checker in [this PR](https://github.com/diofant/diofant/pull/1202).  Unfortunately, the Github CI run doesn't finish in a reasonable time (i.e. default job timeout).

The codebase of the [Diofant](https://github.com/diofant/diofant/) is big, however I think that this check should be reasonably cheap (shouldn't involve AST parsing etc).  Unfortunately, it's not true and I think it's an issue for pylint.  At least, I would appreciate any workaround.

AFAIR, same is true for 'mixed-line-endings', 'trailing-newlines' and 'trailing-whitespace' checkers.

### Configuration

```ini
see the project's pyproject.toml (on the PR's branch)
```

### Command used

```shell
pylint diofant
```

### Pylint output

```shell
Nothing (timeout)
```

### Expected behavior

Tests pass.

### Pylint version

```shell
pylint 2.12.2
astroid 2.9.3
Python 3.10.0+ (heads/3.10:045f205ba4, Nov  8 2021, 05:21:54) [GCC 10.2.1 20210110]
```

**Comment by Pierre-Sassoulas** [comment]
Thank you for opening the issue, those checkers should indeed be almost instantaneous.

**Comment by skirpichev** [comment]
FYI: in the same pr I did tests for other mentioned checkers (normally they should finish in 10-15 min on the Github Actions CI).

**Comment by skirpichev** [comment]
I did more tests.  It seems, `pylint --ignore-patterns=test_ode.py diofant` - pass.  See [these](https://github.com/diofant/diofant/actions/runs/1816890580) jobs (with [that diff](https://github.com/diofant/diofant/pull/1205/commits/1c710dea9f1b928cf151ee3cbd5698645316d174)).

The matched [test_ode.py](https://github.com/diofant/diofant/blob/6e280e9d0c974a239f850b95e0162f1dd209da20/diofant/tests/solvers/test_ode.py) has very long lines (up to 5699; ~50 lines with more 1000 symbols).

I don't know how this (and related) checker works, but if it uses regrexps I would expect that the issue might be related with the catastrophic backtracking.

**Comment by DanielNoord** [comment]
I ran a quick and dirty profile on the linting of that specific file. If you look at the profile it might not actually be the final new line:
```console
         77898208 function calls (58290819 primitive calls) in 46.514 seconds
   Ordered by: cumulative time
   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
    417/1    0.007    0.000   46.534   46.534 {built-in method builtins.exec}
        1    0.000    0.000   46.533   46.533 runpy.py:199(run_module)
        1    0.000    0.000   46.532   46.532 runpy.py:63(_run_code)
        1    0.000    0.000   46.532   46.532 __main__.py:1(<module>)
        1    0.000    0.000   46.532   46.532 __init__.py:21(run_pylint)
        1    0.000    0.000   45.650   45.650 run.py:76(__init__)
        1    0.000    0.000   45.392   45.392 pylinter.py:1042(check)
        1    0.000    0.000   45.392   45.392 pylinter.py:1101(_check_files)
        1    0.000    0.000   45.378   45.378 pylinter.py:1123(_check_file)
        1    0.007    0.007   42.349   42.349 pylinter.py:1290(check_astroid_module)
        1    0.000    0.000   42.342   42.342 pylinter.py:1307(_check_astroid_module
  46869/1    0.345    0.000   38.345   38.345 ast_walker.py:54(walk)
275582/35596    0.112    0.000   22.190    0.001 {built-in method builtins.next}
488073/71544    0.999    0.000   22.178    0.000 node_ng.py:121(infer)
266666/51105    0.444    0.000   22.026    0.000 decorators.py:101(wrapped)
301300/57460    0.215    0.000   21.972    0.000 decorators.py:138(raise_if_nothing_
217596/95463    0.364    0.000   19.292    0.000 bases.py:140(_infer_stmts)
    94/49    0.003    0.000   18.725    0.382 manager.py:103(ast_from_file)
    94/49    0.047    0.001   18.722    0.382 builder.py:115(file_build)
39855/23061    0.111    0.000   17.507    0.001 inference.py:232(infer_call)
26926/25288    0.043    0.000   15.991    0.001 scoped_nodes.py:676(import_module)
26933/25288    0.020    0.000   15.758    0.001 manager.py:157(ast_from_module_name)
26794/25383    0.088    0.000   14.346    0.001 inference.py:279(infer_import_from)
26874/25360    0.063    0.000   13.932    0.001 mixins.py:92(do_import_module)
      196    0.002    0.000   12.978    0.066 builder.py:178(_data_build)
      196    0.002    0.000   11.711    0.060 rebuilder.py:136(visit_module)
      196    0.002    0.000   11.707    0.060 rebuilder.py:152(<listcomp>)
286849/3171    0.268    0.000   11.705    0.004 rebuilder.py:488(visit)
4682/4408    0.043    0.000   11.322    0.003 rebuilder.py:1503(_visit_functiondef)
4659/4388    0.005    0.000   11.312    0.003 rebuilder.py:1558(visit_functiondef)
   196/51    0.002    0.000   10.605    0.208 builder.py:159(_post_build)
    10430    0.035    0.000   10.592    0.001 utils.py:1241(safe_infer)
4682/4408    0.008    0.000   10.354    0.002 rebuilder.py:1549(<listcomp>)
14945/14178    0.040    0.000   10.278    0.001 inference.py:947(infer_assign)
   153462    0.674    0.000    9.685    0.000 decorators.py:171(wrapper)
27914/19542    0.061    0.000    9.257    0.000 scoped_nodes.py:1871(infer_call_resu
     7957    0.138    0.000    9.206    0.001 typecheck.py:1332(visit_call)
7154/5982    0.011    0.000    8.757    0.001 inference.py:311(infer_attribute)
14542376/786850    6.842    0.000    8.736    0.000 node_ng.py:527(nodes_of_class)
   153475    0.106    0.000    8.536    0.000 inspect.py:3243(signature)
   153475    0.115    0.000    8.430    0.000 inspect.py:2989(from_callable)
153476/153475    0.928    0.000    8.315    0.000 inspect.py:2369(_signature_from_ca
     7957    0.033    0.000    8.112    0.001 refactoring_checker.py:996(visit_call)
     8244    0.221    0.000    8.080    0.001 typecheck.py:666(_no_context_variadic)
```
`nodes_of_class` which is being called by `_no_context_variadic` is taking a considerable amount of time. That might be the culprit here.

![out](https://user-images.githubusercontent.com/13665637/153295329-6fd1a423-a2cd-4a4b-bd69-3b81290cfe5c.svg)

**Comment by skirpichev** [comment]
> it might not actually be the final new line

Well, my point is that the problem is triggered by the 'missing-final-newline' checker (or other mentioned above checkers).  If [remove](https://github.com/diofant/diofant/pull/1205/commits/50ec46a5c27128f129364de1ad88f3de5ae298c6) these lines, `pylint diofant` doesn't timeout on CI.

**Comment by DanielNoord** [comment]
My bad, I forgot you `missing-finale-newline` is disabled by default (although the other issue is also quite interesting performance-wise).

For those looking to tackle this issue. The issue is with this `re.search` call:
https://github.com/PyCQA/pylint/blob/851b63e897fdcdb07b939ac7873e9ea3a94f1115/pylint/checkers/format.py#L778

We get stuck here on the file @skirpichev mentioned.

The pattern is:
https://github.com/PyCQA/pylint/blob/851b63e897fdcdb07b939ac7873e9ea3a94f1115/pylint/utils/pragma_parser.py#L11-L23

**Comment by DanielNoord** [comment]
Submitted a PR as the fix proved to be very easy. 😄

**Comment by skirpichev** [comment]
Oh, I think my guess was correct.  The nested construct with catastrophic backtracking seems to be the problem.
