### ISSUE TITLE
A single changelog file instead of two

### ISSUE THREAD

**Issue by Pierre-Sassoulas** [PyCQA/pylint#5728]
### Current problem

We duplicate the changelog in two files. It's burning contributor and maintainer time for no reasons.

### Desired solution

One file only (probably the what's new ? markdown) and some automated checks on it. Maybe like the one black does for its own changelog ? Also maybe some consistency check of the old release when removing one of the file.

### Additional context

[Original idea by @DanielNoord](https://github.com/PyCQA/pylint/pull/5708#discussion_r792190109)

**Comment by mbyrnepr2** [comment]
I think this has been achieved via https://github.com/PyCQA/pylint/pull/6974. Can we close @Pierre-Sassoulas?

**Comment by Pierre-Sassoulas** [comment]
Sure, thank you for noticing !
