### ISSUE TITLE
Pylint needs to forbid to re-use the msgid or symbol of old deleted msgid/symbol

### ISSUE THREAD

**Issue by Pierre-Sassoulas** [PyCQA/pylint#5729]
### Bug description

Right now it's possible to reuse old msgid that were removed, for example, everything from the python 3 checker (the problem was detected with ``using-f-string-in-unsupported-version`` vs ``apply-builtin``), or mixed-indentation, bad-whitespace, bad-continuation... maybe other that I don't remember that we deleted.

We have a mechanism in place for renamed message with old_name, but nothing for removed message.

Related to #5723 and https://github.com/PyCQA/pylint/issues/5607

This is going to cause occasional bug, but more than that confusion and inconsistencies when searching for the msgid online.

### Expected behavior

Impossible to use an old message id or symbol.

**Comment by DanielNoord** [comment]
I would suggest to see if we can find a way to do this in the form of a `test`. Registering a dict of `old_names` during runtime unnecessarily impacts performance. We could do something similar to how I recently added a check for non overlapping symbol prefixes.

**Comment by Pierre-Sassoulas** [comment]
> Registering a dict of old_names during runtime unnecessarily impacts performance. 

I completely agree, I think we should probably generate an efficient and pre-checked message store that's why I think it's related to #5607
