### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by Avasam** [PyCQA/pylint#5746]
### Bug description

Pylint crashes for me whenever it's called.
Repo: https://github.com/Avasam/speedrun.com_global_scoreboard_webapp

### Configuration

```ini
# https://github.com/PyCQA/pylint/blob/main/examples/pylintrc
# https://pylint.pycqa.org/en/latest/technical_reference/features.html
[tool.pylint.REPORTS]
# Just like default but any error will make drop to 9 or less. warning and conventions are worth more
evaluation = "10.0 - error - ((float((warning + convention) * 10 + refactor ) / statement) * 10)"
[tool.pylint.MASTER]
fail-under = 9.0
# Needed for Pylint to discover our own modules
init-hook = "from pylint.config import find_pylintrc; import os, sys; sys.path.append(os.path.join(os.path.dirname(find_pylintrc()), 'backend'))"
# https://pylint.pycqa.org/en/latest/technical_reference/extensions.html
load-plugins = [
  "pylint.extensions.emptystring",
  "pylint.extensions.confusing_elif",
  "pylint.extensions.consider_ternary_expression",
  "pylint.extensions.bad_builtin",
  "pylint.extensions.mccabe",
  "pylint.extensions.check_elif",
  "pylint.extensions.redefined_variable_type",
  "pylint.extensions.overlapping_exceptions",
  "pylint.extensions.empty_comment",
  "pylint.extensions.set_membership",
  "pylint.extensions.typing",
  # External plugins
  "pylint_flask",
  "pylint_flask_sqlalchemy",
  # TODO: Maybe later
  # "pylint.extensions.docparams",
  # Not wanted/needed
  # "pylint.extensions.broad_try_clause",
  # "pylint.extensions.code_style",
  # "pylint.extensions.comparetozero",
  # "pylint.extensions.docstyle",
  # "pylint.extensions.while_used",
  # Didn't work
  # "pylint.extensions.comparison_placement",
  # "pylint.extensions.for_any_all",
]
ignore-paths = [
  # We expect stub files to be incomplete or contain useless statements
  "^.*\\.pyi$",
]
# Dynamic/Generated members from SQLAlchemy
ignored-classes = ["scoped_session"]
disable = [
  # No need to mention the fixmes
  "fixme",
  # Strings are ok. Pylance also doesn't seem to see our overriden Exception classes
  "invalid-sequence-index",
]

[tool.pylint.DESIGN]
# Same as SonarLint
max-args = 7
# Arbitrary to 2 bytes
max-attributes = 16
max-locals = 16

[tool.pylint.FORMAT]
max-line-length = 120

[tool.pylint.'MESSAGES CONTROL']
# Same as SonarLint
max-complexity = 15
max-branches = 15
# https://pylint.pycqa.org/en/latest/user_guide/options.html#naming-styles
module-naming-style = "any"
# Can't make private class with PascalCase
class-rgx = "_?_?[a-zA-Z]+?$"
# https://github.com/PyCQA/pylint/issues/2018
good-names = ["x", "y", "a0", "i", "t0", "t1", "fn", "pb", "wr"]
disable = [
  "missing-docstring",
  # We group imports
  "wrong-import-position",
  # Already taken care of and grayed out. Also conflicts with Pylance reportIncompatibleMethodOverride
  "unused-argument",
  # Already taken care of by Flake8
  "unused-import",
  # TODO: Diabled until using *proper* class based logic
  "protected-access",
]
```

### Command used

```shell
`pylint --score=n --output-format=colorized $(git ls-files 'backend/*.py')`
```

### Pylint output

```shell
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python39\lib\runpy.py", line 87, in _run_code
  File "C:\Program Files\Python39\Scripts\pylint.exe\__main__.py", line 7, in <module>
  File "C:\Program Files\Python39\lib\site-packages\pylint\__init__.py", line 24, in run_pylint
    PylintRun(sys.argv[1:])
  File "C:\Program Files\Python39\lib\site-packages\pylint\lint\run.py", line 315, in __init__
    cb_init_hook(
  File "C:\Program Files\Python39\lib\site-packages\pylint\lint\run.py", line 49, in cb_init_hook
    exec(value)  # pylint: disable=exec-used
  File "<string>", line 1, in <module>
  File "C:\Program Files\Python39\lib\ntpath.py", line 223, in 
dirname
    return split(p)[0]
  File "C:\Program Files\Python39\lib\ntpath.py", line 185, in 
split
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

### Expected behavior

No crash, and/or a better error message explaining what's hapening.

### Pylint version

```shell
pylint 2.11.1
astroid 2.8.5
Python 3.9.6 (tags/v3.9.6:db3ff76, Jun 28 2021, 15:26:21) [MSC 
v.1929 64 bit (AMD64)]
```

### OS / Environment

Windows 10

### Additional dependencies

altgraph==0.17
astroid==2.8.5
attrs==21.2.0
autopep8==1.5.7
bandit==1.7.1
black==21.11b1
certifi==2021.5.30
cffi==1.15.0
charset-normalizer==2.0.4
click==7.1.2
colorama==0.4.4
dodgy==0.2.1
flake8==4.0.1
flake8-polyfill==1.0.2
flake8-pyi==20.10.0
flake8-quotes==3.3.1
Flask==2.0.1
Flask-SQLAlchemy==2.5.1
flask-sqlalchemy-stubs @ git+https://github.com/ssfdust/flask-sqlalchemy-stubs.git@103bf6c7802d778c87938ea9d06ee24b1e552b52   
future==0.18.2
gevent==21.8.0
gitdb==4.0.9
GitPython==3.1.24
greenlet==1.1.1
grequests==0.6.0
httplib2==0.19.1
idna==3.2
ImageHash==4.2.1
install==1.3.5
isort==5.10.1
itsdangerous==2.0.1
Jinja2==3.0.1
keyboard==0.13.5
lazy-object-proxy==1.6.0
livesplit==1.0
MarkupSafe==2.0.1
mccabe==0.6.1
mouse==0.7.1
MouseInfo==0.1.3
mss==6.1.0
mypy==0.790
mypy-extensions==0.4.3
mysql-connector==2.2.9
numpy==1.22.0rc1
opencv-python==4.5.3.56
packaging==21.3
pathspec==0.9.0
pbr==5.7.0
pefile==2021.5.24
pep8-naming==0.10.0
Pillow==8.4.0
platformdirs==2.4.0
prospector==1.5.1
PyAutoGUI==0.9.53
pycodestyle==2.8.0
pycparser==2.21
pydocstyle==6.1.1
pyflakes==2.4.0
PyGetWindow==0.0.9
pyinstaller==4.7
pyinstaller-hooks-contrib==2021.2
PyJWT==2.1.0
pylama==7.7.1
pylint==2.11.1
pylint-celery==0.3
pylint-django==2.4.4
pylint-flask==0.6
pylint-flask-sqlalchemy==0.2.0
pylint-plugin-utils==0.6
PyMsgBox==1.0.9
pyparsing==2.4.7
pyperclip==1.8.2
PyQt6==6.1.0
pyqt6-plugins==6.1.0.2.2
PyQt6-Qt6==6.2.1
PyQt6-sip==13.1.0
PyRect==0.1.4
PyScreeze==0.1.27
PySide6==6.2.1
python-dotenv==0.19.0
PyTweening==1.0.3
PyWavelets==1.1.1
pywin32==302
pywin32-ctypes==0.2.0
pywin32-stubs==0.1.4
PyYAML==5.4.1
qt6-applications==6.1.0.2.2
qt6-tools==6.1.0.1.2
regex==2021.11.10
requests==2.26.0
requests-cache==0.7.3.dev0
requirements-detector==0.7
scipy==1.7.1
setoptconf-tmp==0.3.1
shiboken6==6.2.1
simplejson==3.17.3
six==1.16.0
smmap==5.0.0
snowballstemmer==2.1.0
SQLAlchemy==1.4.22
sqlalchemy-stubs==0.4
sqlalchemy2-stubs==0.0.2a19
stevedore==3.5.0
toml==0.10.2
tomli==1.1.0
typed-ast==1.4.3
types-requests==2.26.1
types-simplejson==3.17.2
typing_extensions==4.0.0
url-normalize==1.4.3
urllib3==1.26.6
Werkzeug==2.0.1
wrapt==1.13.3
zope.event==4.5.0
zope.interface==5.4.0

**Comment by DanielNoord** [comment]
This crash results from your `init-hook`. Which is `"from pylint.config import find_pylintrc; import os, sys; sys.path.append(os.path.join(os.path.dirname(find_pylintrc()), 'backend'))"`

I guess `find_pylintrc()` returns `None` in your case. You can see it doing so here:
https://github.com/PyCQA/pylint/blob/c2a3e84f32559c434208ae1eede65ad5ca767b8d/pylint/config/find_default_config_files.py#L73-L78

Since your config is in `pyproject.toml` it can't find it with this function. Doesn't your previous `init-hook` work?
