### ISSUE TITLE
AttributeError: module 'pylint.testutils' has no attribute 'Message'

### ISSUE THREAD

**Issue by Hynn01** [PyCQA/pylint#5762]
Hi, I'm writing a pylint plugin(https://github.com/Hynn01/dslinter) and trying to use CI for automating tests. However, I run into the `AttributeError: module 'pylint.testutils' has no attribute 'Message'` and have no idea how to fix it. The tests run quite well on my local machine but don't work on the docker container. Could someone help?

### Steps to reproduce:
1. docker pull hynn0633/dslinter
2. pytest . 

### Current behavior:
`AttributeError: module 'pylint.testutils' has no attribute 'Message'`

### Versions:
pylint==2.12.2
astroid==2.9.3

**Comment by Pierre-Sassoulas** [comment]
This is a private class that has been renamed to ``MessageTest`` https://github.com/PyCQA/pylint/blob/main/pylint/testutils/output_line.py#L17`recently. We're not going to make compatibility code so the import should be changed.

**Comment by Hynn01** [comment]
Thank you for your answer!
