### ISSUE TITLE
Add a link to the checker's page from a message's documentation

### ISSUE THREAD

**Issue by Pierre-Sassoulas** [PyCQA/pylint#5782]
### Current problem

The SEO for individual message start to take effects :

![bad_builtin](https://user-images.githubusercontent.com/5493666/153153405-dbe0cf30-f909-421c-91c3-c2d0c50b0233.png)

Result:

![bad_builtin](https://user-images.githubusercontent.com/5493666/153154298-f5d265d3-d779-4f1c-ad35-71927109af74.png)

But we lack some information to easily navigate. The information I wanted here was ``This checker is provided by pylint.extensions.bad_builtin. ``

### Desired solution

 It would be convenient when on a message documentation to be able to go to the source checker documentation.

I.e. for this page : https://pylint.pycqa.org/en/latest/messages/warning/bad-builtin.html
The checker should link to this : https://pylint.pycqa.org/en/latest/technical_reference/extensions.html?highlight=bad_builtin#pylint-extensions-bad-builtin

### Additional context

Search realized to answer https://stackoverflow.com/a/71036231/2519059

**Comment by DanielNoord** [comment]
To make this more actionable, I'd say that:
1) For messages coming from standard checkers it should say something like:
`This message is emitted by standard checker xxx. You can view the source code here.`
2) For messages coming from extensions it should say something like:
`This message is emitted by the optional extension xxx. You can view the source code here. To turn this extension on add the following to your configuration file:
...`

Should be fairly easy to implement.

**Comment by DanielNoord** [comment]
This has been fixed and implemented some time ago.

Examples of 1 and 2 can be seen https://pylint.pycqa.org/en/latest/messages/fatal/astroid-error.html and https://pylint.pycqa.org/en/latest/messages/warning/while-used.html.
