### ISSUE TITLE
Is there an option to set a threshold limit on duplicate-code detection

### ISSUE THREAD

**Issue by kushal-ti** [PyCQA/pylint#5807]
### Question

I'm not very familiar with pylint, so apologies if i'm asking a dumb question. I'm not quite sure how the duplicate code detection works, but i'm guessing it uses some kind of tree matching algorithms for the ast to detect similarity. if that is the case, is there a way to set the threshold for similarity beyond which the code is reported as duplicate

### Documentation for future user

I could not find anything related to threshold for the configuration of the similarities checker in https://pylint.pycqa.org/en/latest/technical_reference/features.html#similarities-checker 

### Additional context

The only relevant question on i found on stackoverflow was https://stackoverflow.com/questions/29206482/pylint-duplicate-code-false-positive and it led me to thi https://pylint.pycqa.org/en/latest/technical_reference/features.html#similarities-checker, which doesn't have any configurations listed for similarity-threshold.

**Comment by Pierre-Sassoulas** [comment]
The option is called ``min-similarity-lines`` and is in the documentation you provided. What description would you propose so it's easier to understand what it does ?

**Comment by kushal-ti** [comment]
> The option is called `min-similarity-lines` and is in the documentation you provided. What description would you propose so it's easier to understand what it does ?

Sorry, perhaps i was not clear in my original question. min-similarity-lines set's the threshold according to a certain number of lines. What i was hoping for was a similarity threshold in percentage (ex. two pieces of code are 80% similar) or something along those lines. I come from an NLP background, and document similarity in NLP is usually measured in those terms. I'm not sure if such an option is available in pylint and was hoping to find out

**Comment by Pierre-Sassoulas** [comment]
No we don't have this option.

>  having 4 lines of similar code in 10 line function is vastly different than having those same 4 lines in a 60 line function

In the context of programming I don't think so, in both case the 4 duplicated lines could be factorized.

**Comment by kushal-ti** [comment]
> https://github.com/PyCQA/pylint/issues/5807#issuecomment-1040006937
Yeah fair enough. Thanks for the response. I'll be closing this issue now
