### ISSUE TITLE
Missing badge for pylint

### ISSUE THREAD

**Issue by kurianbenoy-aot** [PyCQA/pylint#5819]
### Current problem

Our project is using pylint, and we want a badge like in case of black to show in our README

### Desired solution

- Create a shareable badge which can be easily attached in project README like in case of [black](https://github.com/psf/black#show-your-style)

**Comment by Pierre-Sassoulas** [comment]
Thank you for opening the issue ! 

I've found this one : https://img.shields.io/badge/Pylint-10.00/10-green, apparently it's possible to create a badge dynamically see : https://github.com/ResidentMario/missingno/issues/49#issuecomment-362469117, but an official badge would be nice for uniformity.

Do you want to create the badge and open a merge request to add it to our readme ? :)
