### ISSUE TITLE
Links for spyder in documentation are broken

### ISSUE THREAD

**Issue by evohnave** [PyCQA/pylint#5830]
### Question

The links for spyder, in the documentation, seem to be broken.

For example, in [Editor and IDE Integration](https://pylint.pycqa.org/en/latest/user_guide/ide-integration.html#ide-integration) it lists a good link as [this](https://docs.spyder-ide.org/pylint.html), which gives you a 404 error.  

Also the [Pylint home page](https://www.pylint.org/) lists [this](https://pythonhosted.org/spyder/pylint.html) which can't be reached.

I'm not sure, but there are probably other places you've got the wrong spyder link...

### Documentation for future user

I think the better link is [this](https://docs.spyder-ide.org/current/panes/pylint.html)

**Comment by Pierre-Sassoulas** [comment]
Thank you for opening this. Do you want to become a contributor as you're the one who detected the issue :) ?

**Comment by evohnave** [comment]
I'll look at it this weekend.
