### ISSUE TITLE
pylint in embedded python interpreter

### ISSUE THREAD

**Issue by laurentcau** [PyCQA/pylint#5836]
### Current problem

We're facing 2 issues:
1. pylint exit application when parsing is finished. (Perhaps I missed the option to prevent that.)
2. I made a hack in our application to prevent exit but when I try to re-evaluate the file several times, it only display first evaluated warnings and errors.  
code used:
```
import pylint.lint
pylint_opts = ['myfile.py']
pylint.lint.Run(pylint_opts)
#change myfile.py
pylint.lint.Run(pylint_opts)
```
### Desired solution

Ability to evaluate same file several times in same python session.
Perhaps a workaround would be to create some virtual env to start pylint ?

**Comment by Pierre-Sassoulas** [comment]
Hello, could you check the documentation [here, after "It is also possible to call Pylint from another Python program"](https://pylint.pycqa.org/en/latest/user_guide/run.html#invoking-pylint), please ? I'm thinking about creating a new title so it's easier to find this part of the doc, please let me know what we can make clearer too :)

**Comment by Pierre-Sassoulas** [comment]
> The python interpreter exited automatically after pylint.lint.Run call.

Yes, it's "intended" as in "it works this way and it would be a breaking change to change this". See exit code at the bottom of the doc from my next answer. Regarding the issue with the output see https://pylint.pycqa.org/en/latest/user_guide/output.html?highlight=stream#output-options

```python
import pylint.lint

pylint_output = StringIO() # Custom open stream
reporter = text.TextReporter(pylint_output)
pylint_opts = ['myfile.py']
pylint.lint.Run(pylint_opts], reporter=reporter, do_exit=False)
print(pylint_output.getvalue()) # Retrieve and print the text report
```

**Comment by laurentcau** [comment]
ok, do_exit=False is what I needed for the first point. Thanks.
For second, here is my test case:
test.py is:
```
fct()
```
```
C:\Users\Laurent.Caumont>c:\devtools\Python38\python.exe
Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pylint.lint
>>> pylint_opts = ['-E', r'c:\tmp\test.py']
>>> pylint.lint.Run(pylint_opts, do_exit=False)
************* Module test
c:\tmp\test.py:1:0: E0602: Undefined variable 'fct' (undefined-variable)
<pylint.lint.run.Run object at 0x000002224CCC0AF0>
```
now edit test.py:
```
#fct()
```
in same python session:
```
>>> pylint.lint.Run(pylint_opts, do_exit=False)
************* Module test
c:\tmp\test.py:1:0: E0602: Undefined variable 'fct' (undefined-variable)
<pylint.lint.run.Run object at 0x000002225160FC70>
```
It report the same error.
Should use of reporter fix this issue ?
I was not able to test your code because I don't know what is "text" in "text.TextReporter(pylint_output)"

**Comment by Pierre-Sassoulas** [comment]
It's ``from pylint.reporters.text import TextReporter``

**Comment by laurentcau** [comment]
Hi Pierre,
I tested and that doesn't fix my second issue: The file is not re-evaluated in second call.

**Comment by Pierre-Sassoulas** [comment]
Can you show your code ?

**Comment by laurentcau** [comment]
start python session:
```
C:\Users\Laurent.Caumont>c:\devtools\Python38\python.exe
Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from pylint.reporters.text import TextReporter
>>> from io import StringIO
>>> import pylint.lint
>>> pylint_output = StringIO()
>>> reporter = TextReporter(pylint_output)
>>> pylint_opts = ['-E', r'c:\tmp\test.py']
>>> pylint.lint.Run(pylint_opts, reporter=reporter, do_exit=False)
<pylint.lint.run.Run object at 0x00000115248FE850>
>>> print(pylint_output.getvalue())
************* Module test
c:\tmp\test.py:1:0: E0602: Undefined variable 'fct' (undefined-variable)
```
edit c:\tmp\test.py (remove error)
and on **same** python console:
```
>>> pylint.lint.Run(pylint_opts, reporter=reporter, do_exit=False)
<pylint.lint.run.Run object at 0x0000011528D4E7F0>
>>> print(pylint_output.getvalue())
************* Module test
c:\tmp\test.py:1:0: E0602: Undefined variable 'fct' (undefined-variable)
c:\tmp\test.py:1:0: E0602: Undefined variable 'fct' (undefined-variable)

>>>
```

**Comment by Pierre-Sassoulas** [comment]
It seems the file is reevaluated as it should in the second call as there are 2 ``undefined-variable`` instead of one. You need to use another reporter if you want a new report.
