### ISSUE TITLE
Ignore specific project folders or files

### ISSUE THREAD

**Issue by omonimus1** [PyCQA/pylint#5855]
### Question

Hi, in Django is easy to locally have a venv, migrations files, cache folders;
How can I run pylint excluding the check on a list of folders or files?

### Documentation for future user

README.md (and pipy website)

**Comment by Pierre-Sassoulas** [comment]
Here's a stackoverflow answer covering the subject : https://stackoverflow.com/questions/2503717/ignore-by-directory-using-pylint

Here's the pylint documentation: https://pylint.pycqa.org/en/latest/technical_reference/features.html?highlight=ignore-patterns#general-options

Please let me know how we could make the documentation better or more discoverable :)

**Comment by omonimus1** [comment]
@Pierre-Sassoulas , thank you very much <3
