### ISSUE TITLE
Support for mccabe >= 0.7.0

### ISSUE THREAD

**Issue by priv-kweihmann** [PyCQA/pylint#5878]
mccabe 0.7.0 has been released 1.5 months ago - so far I don't see any breaking API changes, so it should be supported by pylint easily

**Comment by priv-kweihmann** [comment]
> `mccabe` `0.7.0` only supports 3.7 =<, `pylint` still supports 3.6. So that would need to be resolved first.

allowing mccabe for py>=3.7 while remaining on 0.6.x for <3.7 isn't an option?

**Comment by DanielNoord** [comment]
> > `mccabe` `0.7.0` only supports 3.7 =<, `pylint` still supports 3.6. So that would need to be resolved first.
> 
> allowing mccabe for py>=3.7 while remaining on 0.6.x for <3.7 isn't an option?

I think it might be, but we're wanting to remove `3.6` support ourselves as well.
We're just caught up in the `astroid` `2.11` release, which is blocking `pylint` `2.13`, which is blocking dropping `3.6`.

So I don't think any of the active maintainers will have time to look into such temporary measures while we're working on these issues ourselves.

**Comment by Pierre-Sassoulas** [comment]
We could switch from ``mccabe>=0.6,<0.7`` to ``mccabe>=0.6,<0.8`` in ``setup.cfg`` (python 3.6 would get < 0.7). I don't think it's too much work but we already have a lot on our plate as @DanielNoord said. Please feel free to open a PR.
