### ISSUE TITLE
Make sure to package the ``pylintrc`` from testutils

### ISSUE THREAD

**Issue by DanielNoord** [PyCQA/pylint#6028]
### Bug description

We have discussed this in the ``pylint-django`` repo but I haven't got the time to get to it.

If somebody else knows how to do this please go ahead. I'm no expert in `setuptools`.

Basically, there is a pylintrc file in the testutils that should be packaged with `pylint` as the `testutils` depend on it at runtime.

**Comment by jpy-git** [comment]
Will add this 👍
