### ISSUE TITLE
TypeError in `unnecessary-list-index-lookup`

### ISSUE THREAD

**Issue by jacobtylerwalls** [PyCQA/pylint#6049]
### Bug description

```python
pairs = [(0, 0)]
for i, (a, b) in enumerate(pairs):
    print(pairs[i][0])
```

### Command used

```shell
pylint a.py
```

### Pylint output

```shell
Exception on node <For l.2 at 0x106f22e00> in file '/Users/.../.../a.py'
Traceback (most recent call last):
  File "/Users/.../pylint/pylint/utils/ast_walker.py", line 73, in walk
    callback(astroid)
  File "/Users/.../pylint/pylint/checkers/refactoring/refactoring_checker.py", line 651, in visit_for
    self._check_unnecessary_list_index_lookup(node)
  File "/Users/.../pylint/pylint/checkers/refactoring/refactoring_checker.py", line 2037, in _check_unnecessary_list_index_lookup
    and index.lookup(value_variable.name)[1][-1].lineno
TypeError: '>' not supported between instances of 'NoneType' and 'int'
```

### Expected behavior

no crash, and potentially, a message to use `a` and not `[i][0]`

### Pylint version

```shell
pylint 2.14.0-dev0
astroid 2.12.0-dev0
Python 3.10.2 (v3.10.2:a58ebcc701, Jan 13 2022, 14:50:16) [Clang 13.0.0 (clang-1300.0.29.30)]
```

**Comment by jacobtylerwalls** [comment]
FYI @timmartin -- perhaps you would like to take a look? Would be much appreciated.

**Comment by timmartin** [comment]
Sure, I'll take a look at this.

**Comment by DanielNoord** [comment]
@jacobtylerwalls Not sure how you found this, but is this project a potential candidate for the primer?

**Comment by jacobtylerwalls** [comment]
> is this project a potential candidate for the primer?

Sure. It's [music21](https://www.github.com/cuthbertLab/music21), which I help maintain. I've used it to report issues like #4891 #4664 and #6074. And I should be able to help contributors interpret behavior changes if we get the message-differ wired up.
