### ISSUE TITLE
Missing `W0612: Unused variable` warning if exception name is being reused

### ISSUE THREAD

**Issue by ptagl** [PyCQA/pylint#6077]
### Bug description

Save the following code in a file like `pylint_test.py`.

```py
"""
Dummy module.
"""

def my_function():
    """
    Dummy function.
    """

    try:
        my_var = 1/0
    except ZeroDivisionError as exception:
        assert exception

    try:
        my_var = 1/0
    except ZeroDivisionError as exception:
        # The following line makes "exception" unused
        #pass
        # For the second run, comment the line above and uncomment the line below
        print(exception)
        # Why "exception" at line 26 is not marked as unused?

    try:
        my_var = 1/0
    except ZeroDivisionError as exception:
        pass

    print(my_var)

my_function()

```

### Command used

```shell
pylint pytlint_test.py
```

### Pylint output

```shell
`pylint_bug.py:17:4: W0612: Unused variable 'exception' (unused-variable)` when line 19 is not commented and line 21 is commented, nothing when line 19 is commented and line 21 is not.
```

### Expected behavior

I would expect to get a "unused variable" warning for line 26 at least when commenting line 19 and uncommenting line 21, like:

`pylint_test.py:26:4: W0612: Unused variable 'exception' (unused-variable)`

### Pylint version

```shell
pylint 2.13.2
```

### OS / Environment

Opensuse Tumbleweed

**Comment by jacobtylerwalls** [comment]
Hi @ptagl, thanks for the writeup. The variables checker warns once per variable per scope. For fishy patterns in the same scope (redefining a variable inside an except handler or nested loop) we have `redefined-outer-name`, but still no further messages for `unused-variable`.

For instance, just one warning is emitted for:
```python
def a():
    x = 0  # [unused-variable]
    x = 0
```

If you have thoughts I'd be happy to continue discussing on #4391. Thanks for opening the ticket; it forced me to go back through that discussion again.

**Comment by jacobtylerwalls** [comment]
Oh, by the way, we also have #5838 open for warning about "dead stores" of reassigning "as e" and doing nothing with it. That's probably the better superseder.

**Comment by ptagl** [comment]
@jacobtylerwalls thanks a lot for your answers, it's ok for me to close this issue: I'm not a Python expert, so I'm not sure what a linter should or should not report.

By the way, I just wanted to let you know that I've found that both `Flake8` and `Pyflakes` correctly detect the unused variable in my example, not sure if such information is useful or not.

**Comment by jacobtylerwalls** [comment]
Interesting. I had a look and it turns out that `pyflakes` is actually unsatisfied with their handling of this, so although your example works, they are issuing false positives, see PyCQA/pyflakes#378.
