### ISSUE TITLE
Re-enable ``bad-docstring-quotes`` for Python 3.7

### ISSUE THREAD

**Issue by DanielNoord** [PyCQA/pylint#6087]
### Current problem

With changes to `doc_node` in astroid we can now check docstring quotes in `3.7` as well. This was turned off in #5526.

### Desired solution

Turn the checker on again.

### Additional context

@kasium Do you still want to do this? Should I assign you?

**Comment by kasium** [comment]
@DanielNoord thanks for checking. Seems I was too slow 😄
