### ISSUE TITLE
Typo in W0402 message

### ISSUE THREAD

**Issue by tushar-deepsource** [PyCQA/pylint#6169]
W0402 (`deprecated-module`) error message says "Uses of a deprecated module 'optparse'".

I think it should say "Use of a deprecated module 'optparse'" instead of "Uses". Either "Use", or "Usage". "Uses" seems grammatically incorrect to me. What do you think?

**Comment by omarandlorraine** [comment]
I think the message you describe could also be phrased more tersely, or more uniformly.

`E0602` says "Undefined variable <variable-name>". In that vein, I suggest "Deprecated module <module-name>" for `W0402`.

While we're at it, the description for W0402 has some similar weirdness as well: "Used a module marked as deprecated is imported."

**Comment by jacobtylerwalls** [comment]
Sounds good. @omarandlorraine, would you like to prepare a patch?

**Comment by omarandlorraine** [comment]
Yep, I'll get to it on Tuesday.
