### ISSUE TITLE
What does the ``TypeVar`` pattern for ``invalid-name`` refer to?

### ISSUE THREAD

**Issue by skuukariel** [PyCQA/pylint#6184]
Can anyone please tell me what's this exactly expressing?

https://github.com/PyCQA/pylint/blob/ce42d69f623bfab62d15263bc1d95bd0725c4701/pylint/checkers/base/name_checker/checker.py#L30

**Comment by DanielNoord** [comment]
I think this comment has the best summary of what this pattern does and does not allow:
https://github.com/PyCQA/pylint/pull/5221#discussion_r776501605

**Comment by cdce8p** [comment]
Some examples for good and bad TypeVar names can also be found here: https://pylint.pycqa.org/en/latest/user_guide/options.html#predefined-naming-patterns

**Comment by Pierre-Sassoulas** [comment]
Closing as there already is some official documentation on the topic.
