### ISSUE TITLE
Spellchecking Proper nouns in docstrings / comments

### ISSUE THREAD

**Issue by sylvain-ri** [PyCQA/pylint#6236]
### Current problem

I would to use spellchecking (with pyenchant), but there are too many false positives with Proper nouns like John Alex etc.

### Desired solution

A flag to disable spellchecking of words in docstrings or comment that starts with a capital letter ?

### Additional context

Somehow related to #945.

**Comment by Pierre-Sassoulas** [comment]
I thinks it's an issue related with pyenchant configuration and not with pylint's. The solution could be to create [a custom dictionary](https://stackoverflow.com/questions/22898355/pyenchant-spellchecking-block-of-text-with-a-personal-word-list).

If we start adding an overlay on top of enchant for thing that are not maintained in enchant itself the maintenance burden would become unreasonable really fast.

**Comment by Pierre-Sassoulas** [comment]
Closing as won't fix.
