### ISSUE TITLE
`ignore-imports` option ignored

### ISSUE THREAD

**Issue by jacobtylerwalls** [PyCQA/pylint#6350]
### Bug description

The `ignore-imports=yes` option is ignored in 2.14.

Place two files that both read like this (ideally in their own dir so you can just run that dir):
```python
import os
import sys
import argparse
import random
import math
```

### Configuration

```ini
I reproduced in an environment without a `pylintrc`.
```

### Command used

```shell
pylint package_name --enable=duplicate-code --ignore-imports=y
```

### Pylint output

```shell
************* Module c
sim/c.py:1:0: W0611: Unused import os (unused-import)
sim/c.py:2:0: W0611: Unused import sys (unused-import)
sim/c.py:3:0: W0611: Unused import argparse (unused-import)
sim/c.py:4:0: W0611: Unused import random (unused-import)
sim/c.py:5:0: W0611: Unused import math (unused-import)
************* Module b
sim/b.py:1:0: W0611: Unused import os (unused-import)
sim/b.py:2:0: W0611: Unused import sys (unused-import)
sim/b.py:3:0: W0611: Unused import argparse (unused-import)
sim/b.py:4:0: W0611: Unused import random (unused-import)
sim/b.py:5:0: W0611: Unused import math (unused-import)
sim/b.py:1:0: R0801: Similar lines in 2 files
==b:[0:5]
==c:[0:5]
import os
import sys
import argparse
import random
import math (duplicate-code)
```

### Expected behavior

Proper output in 2.12:

```shell
************* Module c
sim/c.py:1:0: W0611: Unused import os (unused-import)
sim/c.py:2:0: W0611: Unused import sys (unused-import)
sim/c.py:3:0: W0611: Unused import argparse (unused-import)
sim/c.py:4:0: W0611: Unused import random (unused-import)
sim/c.py:5:0: W0611: Unused import math (unused-import)
************* Module b
sim/b.py:1:0: W0611: Unused import os (unused-import)
sim/b.py:2:0: W0611: Unused import sys (unused-import)
sim/b.py:3:0: W0611: Unused import argparse (unused-import)
sim/b.py:4:0: W0611: Unused import random (unused-import)
sim/b.py:5:0: W0611: Unused import math (unused-import)

------------------------------------------------------------------
Your code has been rated at 0.00/10 (previous run: 0.00/10, +0.00)
```

### Pylint version

Caused in 03cfbf3df1d20ba1bfd445c59f18c906e8dd8a62

**Comment by Pierre-Sassoulas** [comment]
Hmm, isn't ``ignore-imports=yes`` an option of the similar checker ? I think we put them in the global configuration namespace but the name is now misleading and should be something like "ignore-import-for-similarity".

**Comment by DanielNoord** [comment]
I think I know what is causing this. `set_option` of `Similar` sets the options from `.config` to an attribute of the checker. This allows running `Similar` standalone as it no longer requires a `linter.config` object.
With `optparse` `set_option` got called all the time (which is one of the things we wanted to avoid in `argparse`).

However, I think we might be calling it a little too little now. I'll assign myself, although I'm not sure if I can fix this before the weekend.
