### ISSUE TITLE
Pyreverse: support type annotations inside quotes

### ISSUE THREAD

**Issue by ChrisKeefe** [PyCQA/pylint#6465]
### Current problem

Possibly related to https://github.com/PyCQA/pylint/issues/3765

Recursive type annotations must be quoted for mypy compliance. These quoted annotations are dropped from the pyreverse outputs I've checked (PlantUML and .png), leaving missing types.

E.g. This
![image](https://user-images.githubusercontent.com/39198770/165376336-c0613329-7328-43a7-8472-656a6348f8fe.png)

produces this:
![image](https://user-images.githubusercontent.com/39198770/165376481-292ca0b6-5cda-45e5-be35-3868dd139a2e.png)

### Desired solution

pyreverse renders the quoted type annotations (perhaps as unquoted strings)

**Comment by ChrisKeefe** [comment]
Of course. Sorry for the oversight!

![image](https://user-images.githubusercontent.com/39198770/165553332-d1aaee3a-69e5-4e2e-9b26-4ff261eb230d.png)
Running on OpenSUSE Tumbleweed.

**Comment by Pierre-Sassoulas** [comment]
Hello, thank you for opening the issue. Next time could you provide the code and example as text instead of as an image ? Text is crawl-able by search engines, readable by visually impaired persons and copy pastable to test the issue fast, while images are not. :)

**Comment by DudeNr33** [comment]
@ChrisKeefe I can reproduce the issue with pylint 2.12.2, but it is already fixed in the current 2.13.7 release.
Can you confirm that upgrading your pylint version fixes the problem?

**Comment by ChrisKeefe** [comment]
Confirmed! As you described above, in `2.13.7`, "the type hint is displayed (in quotes, which could be nicer, but not completely missing like in your example)" Thanks again for looking into this little QOL issue!
