### ISSUE TITLE
PRs creating extensions will always fail the documentation check

### ISSUE THREAD

**Issue by jacobtylerwalls** [PyCQA/pylint#6470]
#6058 generates links to GitHub pages for optional checkers. This page won't actually be live until a new checker is merged.

#6292 added a documentation check to CI.

The combination of these two facts means PRs adding extensions will always fail the documentation check. We can tolerate that, I guess, but are there better ideas?

See https://github.com/PyCQA/pylint/runs/6210620669?check_suite_focus=true

**Comment by DanielNoord** [comment]
Ah that's oversight on my part.

Can this be fixed by using internal links instead? Those should pass `linkcheck` as that runs after documentation has been built.

**Comment by DanielNoord** [comment]
I just checked and we can't use an internal link here. We can use `linkcheck_ignore` though, see https://www.sphinx-doc.org/en/master/usage/configuration.html?highlight=linkcheck#options-for-the-linkcheck-builder.

Adding the extensions folder on Github should fix this issue.
