### ISSUE TITLE
too-many-locals should ignore underscore variable names

### ISSUE THREAD

**Issue by ayoung19** [PyCQA/pylint#6488]
### Current problem

Not sure how underscores are handled everywhere else, but it would be nice if they didn't count toward local variable counts since they aren't being used.

### Desired solution

When unpacking triple, I am ignoring the middle variable with an "_" and it shouldn't count towards the local variable count, especially as it doesn't count as an unused variable. Basically I could easily avoid this by not unpacking my lists, referencing them with `triple[0]` and `triple[2]`, but that would lead to very obscure code.

**Comment by Pierre-Sassoulas** [comment]
Thank you for opening the issue, I think it make sense.

**Comment by ayoung19** [comment]
I can help with implementing this if no one has started yet, my company uses pylint and I had to change my code to fit the requirements 😭

**Comment by ayoung19** [comment]
Thanks for letting me tackle this @DanielNoord and @Pierre-Sassoulas! Please look at #6492 when you have time and let me know if my solution is an acceptable way to do this as I'm a bit unfamiliar with the codebase.
