### ISSUE TITLE
Pep8 check for exception names

### ISSUE THREAD

**Issue by kasium** [PyCQA/pylint#6522]
### Current problem

According to PEP8, exception class names should end with "Error" if they define an actual exception.
However, pylint doesn't offer such an check.

### Desired solution

Add a new naming check which checks if a class extends any known exception class. Then check it's name. Since an exception can also be used as a non-error offer a configuration like a "allow-list" similar to good-names.

### Additional context

https://peps.python.org/pep-0008/#exception-names

**Comment by DanielNoord** [comment]
This sounds quite opinionated. I'd be fine with adding this as a possible extension, but it should probably not be part of the base checkers or disabled by default.

**Comment by Pierre-Sassoulas** [comment]
How would you assess the ``(if the exception actually is an error)`` part programmatically ? Inherit from an exception that itself uses the Error suffix ?

**Comment by jacobtylerwalls** [comment]
I would suggest the check be permissive enough to allow "Exception" as a suffix e.g. `PylintException`. I think it's really splitting hairs to say one or the other is worse.

**Comment by Pierre-Sassoulas** [comment]
To add to what @jacobtylerwalls said, I don't think the meaning of the PEP is : everything that inherit from ``BaseException`` should have the ``Error`` suffix. ``(if the exception actually is an error)`` carry a lot of meaning (there's an entire [literature on the distinction between exception and errors elsewhere](https://stackoverflow.com/a/912352/2519059)).

> Errors tend to signal the end of your application as you know it. It typically cannot be recovered from and should cause your VM to exit.

I checked the [existing builtin exceptions](https://docs.python.org/3.10/library/exceptions.html#exception-hierarchy) to get a feeling of what "exception are not an error":
```
BaseException
 +-- SystemExit
 +-- KeyboardInterrupt
 +-- GeneratorExit
 +-- Exception
      +-- StopIteration
      +-- StopAsyncIteration
      +-- ArithmeticError
      |    +-- FloatingPointError
      |    +-- OverflowError
      |    +-- ZeroDivisionError
      +-- AssertionError
      +-- AttributeError
      +-- BufferError
      +-- EOFError
      +-- ImportError
      |    +-- ModuleNotFoundError
      +-- LookupError
      |    +-- IndexError
      |    +-- KeyError
      +-- MemoryError
      +-- NameError
      |    +-- UnboundLocalError
      +-- OSError
      |    +-- BlockingIOError
      |    +-- ChildProcessError
      |    +-- ConnectionError
      |    |    +-- BrokenPipeError
      |    |    +-- ConnectionAbortedError
      |    |    +-- ConnectionRefusedError
      |    |    +-- ConnectionResetError
      |    +-- FileExistsError
      |    +-- FileNotFoundError
      |    +-- InterruptedError
      |    +-- IsADirectoryError
      |    +-- NotADirectoryError
      |    +-- PermissionError
      |    +-- ProcessLookupError
      |    +-- TimeoutError
      +-- ReferenceError
      +-- RuntimeError
      |    +-- NotImplementedError
      |    +-- RecursionError
      +-- SyntaxError
      |    +-- IndentationError
      |         +-- TabError
      +-- SystemError
      +-- TypeError
      +-- ValueError
      |    +-- UnicodeError
      |         +-- UnicodeDecodeError
      |         +-- UnicodeEncodeError
      |         +-- UnicodeTranslateError
      +-- Warning
           +-- DeprecationWarning
           +-- PendingDeprecationWarning
           +-- RuntimeWarning
           +-- SyntaxWarning
           +-- UserWarning
           +-- FutureWarning
           +-- ImportWarning
           +-- UnicodeWarning
           +-- BytesWarning
           +-- EncodingWarning
           +-- ResourceWarning
```           
The class not ending with ``Error`` are ``SystemExit``, ``KeyboardInterrupt``, ``GeneratorExit``, ``StopIteration``, ``StopAsyncIteration`` and ``Warning`` and its subclasses.

It looks like that if we implement this we could reasonably ask for a suffix between ``Error``, ``Exception``, ``Exit``, ``Interrupt``, (``Iteration``?) and ``Warning``, (maybe based on the suffix of the parent class, ie. a class that inherit ``Warning``should be suffixed ``Warning``). It's still opinionated but only ``Error`` / ``Exception`` would be too limited imo.

**Comment by kasium** [comment]
Sorry for the late reply. Thanks for all the comments and opinions. Based on that, I think a check is too opinionated and will most likely cause more questions and harm than benefits. Therefore I would close this issue
