### ISSUE TITLE
Ignore options and recursive.

### ISSUE THREAD

**Issue by yaleman** [PyCQA/pylint#6525]
### Question

I'd like to know how to use ignore in combination with recursive.

I'd expect this to work, and ignore my local `.venv` directory:

```
pylint --ignore='.venv' --recursive=y .
```

I've also tried this and a whole bunch of other regexes without success:

```
pylint --ignore-paths='^\\.venv' --recursive=y .
```

### Documentation for future user

Examples of valid regexes would be really useful. I could find vague references to them, but not *actionable* information on what's supported, known edge cases etc.

### Additional context

I've looked through the various examples and issues closed in recent history, and they all claim to have fixed things, but I can't work out what I'm doing differently.

**Comment by DanielNoord** [comment]
Sadly, these options are currently broken. See https://github.com/PyCQA/pylint/issues/6471.

Closing this as duplicate.
