### ISSUE TITLE
mypy and pylint disagree about uselessness of return statements

### ISSUE THREAD

**Issue by clo-vis** [PyCQA/pylint#6530]
### Bug description

```python
from contextlib import AbstractContextManager
from types import TracebackType
from typing import Optional, Type


class Playground(AbstractContextManager["Playground"]):
    def __exit__(
        self,
        exc_type: Optional[Type[BaseException]],
        exc_value: Optional[BaseException],
        traceback: Optional[TracebackType],
    ) -> Optional[bool]:
        print("closing what needs to be closed")
        return None
```

### Command used

```shell
pylint playground.py
```

### Pylint output

```shell
src\playground.py:7:4: R1711: Useless return at end of function or method (useless-return)
```

### Expected behavior

No error message, because without `return None` mypy complains: 

> error: Missing return statement  [return]

And mypy swears that they are right, see for example https://github.com/python/mypy/issues/3974

(By the way, the signature from __exit__ was copied from https://mypy.readthedocs.io/en/stable/protocols.html#contextmanager-t)

### Pylint version

```shell
pylint 2.13.8
astroid 2.11.4
Python 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]
```

**Comment by Pierre-Sassoulas** [comment]
I think both tools are right according to pep8 : ``Either all return statements in a function should return an expression, or none of them should.``

If you don't want to return anything use ``-> None`` instead of `` -> Optional[bool]``, mypy will be happy :)

**Comment by mbyrnepr2** [comment]
To add to Pierre's comment, there is also an instructive docstring relating to this:
https://github.com/PyCQA/pylint/blob/main/pylint/checkers/refactoring/refactoring_checker.py#L1866

**Comment by Pierre-Sassoulas** [comment]
Closing as answered.

**Comment by clo-vis** [comment]
> If you don't want to return anything use -> None instead of -> Optional[bool], mypy will be happy :)

A better answer is "use `# type: ignore` and mypy will be happy.

Even though for the example above using `-> None` does the job, you cannot always just replace the type of the return value with `-> None` and expect that mypy won't complain, as in

```python
from typing import overload, Union, Literal


@overload
def fetch_data(parse: Literal[True]) -> int:
    ...


@overload
def fetch_data(parse: Literal[False]) -> None:
    ...


@overload
def fetch_data(parse: bool) -> Union[int, None]:
    ...


def fetch_data(parse: bool) -> Union[int, None]:  # type: ignore[return]
    print(parse)
```
