### ISSUE TITLE
pyreverse Aggregation and Composition arrows are same

### ISSUE THREAD

**Issue by khashashin** [PyCQA/pylint#6543]
### Bug description

pyreverse generates same diagram for aggregation and composition. Here is the sample code:

```python
# Aggregation
class Student:
    def __init__(self, id):
        self._id = id

    def registration_number(self, department_id):
        return str(self._id) + '-' + department_id


class Department:
    def __init__(self, id, student):
        self._id = id
        self._student = student

    def student_registration(self):
        return self._student.registration_number(self._id)


if __name__ == '__main__':
    student = Student(50)
    department = Department('ENG', student)

    print(department.student_registration())
```
---
```python
# Composition
class Student:
    def __init__(self, id):
        self._id = id

    def registration_number(self, department_id):
        return str(self._id) + '-' + department_id


class Department:
    def __init__(self, department_id, student_id):
        self._id = department_id
        self._student = Student(student_id)

    def student_registration(self):
        return self._student.registration_number(self._id)


if __name__ == '__main__':
    department = Department('ENG', 50)

    print(department.student_registration())

```

### Command used

```shell
pyreverse -o png -p composition.py .
pyreverse -o png -p aggregation.py .
```

### Pylint output

```shell
Format png is not supported natively. Pyreverse will try to generate it using Graphviz...
parsing ./__init__.py...
parsing /mnt/d/GitHub/test/django_with_sass/experiments/composition.py...
parsing /mnt/d/GitHub/test/django_with_sass/experiments/__init__.py...

Format png is not supported natively. Pyreverse will try to generate it using Graphviz...
parsing ./__init__.py...
parsing /mnt/d/GitHub/test/django_with_sass/experiments/aggregation.py...
parsing /mnt/d/GitHub/test/django_with_sass/experiments/__init__.py...
```

### Expected behavior

Different Arrow type.

![image](https://user-images.githubusercontent.com/17837758/167272523-36270d0a-6c63-493e-bb68-52c282f4d8ea.png)
[Source](https://www.visual-paradigm.com/guide/uml-unified-modeling-language/uml-class-diagram-tutorial/)

### Pylint version

```shell
pylint --version
pylint 2.13.8
astroid 2.11.4
Python 3.10.0 (default, Dec  3 2021, 00:34:18) [GCC 9.3.0]
```

### OS / Environment

Windows 11
WSL2

### Additional dependencies

sudo apt install graphviz

**Comment by dgutson** [comment]
CC @qequ

**Comment by Pierre-Sassoulas** [comment]
Do you want me to assign this to you @qequ ? 😅

**Comment by qequ** [comment]
@Pierre-Sassoulas please assign this to me :+1:

**Comment by Pierre-Sassoulas** [comment]
My first instinct would be to tell you to use inference (``NodeNG.infer()``).

**Comment by DudeNr33** [comment]
Thanks @qequ for taking this on!

I will have to take a closer look at this and hope that I find the time for that on the weekend.
To add to Pierre's comment, my first thoughts are:

* why is the `_student` *attribute* identified as a `ClassDef`? This itself seems like a bug to me.
* I would try to differentiate between the composition and aggregation case by trying to find out if the instance was created in the scope of the class or not. If yes --> Composition, else --> Aggregation. Relying on type hints has the disadvantage that this feature will only benefit those users who actually use them.

**Comment by qequ** [comment]
@DudeNr33 
The `_student` attribute identified as a `Classdef` happens when using type hints.
Having an aggregation with no type hints like this
```python
# Aggregation
class Student:
    def __init__(self, id):
        self._id = id

    def registration_number(self, department_id):
        return str(self._id) + '-' + department_id


class Department:
    def __init__(self, id, student):
        self._id = id
        self._student = student

    def student_registration(self):
        return self._student.registration_number(self._id)


if __name__ == '__main__':
    student = Student(50)
    department = Department('ENG', student)

    print(department.student_registration())

```

`_student` is identified as `Uninferable` and no association is created

![classes](https://user-images.githubusercontent.com/19431622/202743013-f12fc428-0693-4028-9ca9-6255c1e951cc.png)

When using type hints like in the example I showed in the previous message `_student` is identified as a `ClassDef`. I didn't know this was a bug. I'm not familiar with how astroid works, I thought this was normal behaviour 😬.


About the second point, my first thought was that: finding a way to check if the instance had been created in the instance of the class, but I coudn't find a way to.  Neither `ClassEntity` nor `NodeNG` seems to keep information about the instance creation to check if it was created in the scope or not, that's why I tried with type hints. Is there any way to get that information?

**Comment by DudeNr33** [comment]
I tried around myself a bit. 
To distinguish if the value of the attribute is a class instance created inside the scope of the class itself or not, I would start around here:
https://github.com/PyCQA/pylint/blob/57f38c39ae8df066212df75d684f8608b9f41b9e/pylint/pyreverse/inspector.py#L179-L184

You will need to inspect the `parent` of the `assignattr` and look at the `value` that is assigned:
```python
assignattr.parent.value
```

For the following code
```python
class Dependency:
    pass


class Compositor:
    def __init__(self):
        self.composition = Dependency()


class Aggregator:
    def __init__(self, dep: Dependency):
        self.aggregation = dep
```
you should see that the `composition` attribute of `Compositor` will have a `Call` object as `assignattr.parent.value`. You can then try to infer the value of the `Call`'s `func` attribute, which in this case would be the `ClassDef` of `Dependency`:
```python
set(assignattr.parent.value.func.infer())  # --> {<ClassDef.Dependency...10ae4c700>}
```

If you do the same for the `aggregation` of `Aggregator`, you would find that `assignattr.parent.value` is not a `Call`, but a `Name` (at least in the example above).


This is just a hint where and how you could start, feel free to explore different approaches.

Also this would only handle the simplest case, where the creation of the object takes place directly in the assignment to the attribute itself. One could think of more complicated examples, like creating the object in a helper method and assigning the return value to the attribute:

```python
class Compositor:
    def __init__(self):
        self.composition = self._create_dep()
    def _create_dep(self) -> Dependency:
        return Dependency()
```

Or storing the created object first in a intermediate local variable before assigning it:

```python
class Compositor:
    def __init__(self):
        intermediary = Dependency()
        self.composition = intermediary
```

Those cases would require more logic.
However, I would start with the simple case from above. Realizing this feature will require also enhancements to other parts of `pyreverse` to distinguish between composition and aggregation, so the final pull request won't be too small. 
So I would propose to first implement only the simple case, make a PR, and then if needed enhance the logic to cover more complex cases in later PRs.

**Comment by Pierre-Sassoulas** [comment]
Closing as #7836 was merged, thank you @qequ, great feature !

**Comment by qequ** [comment]
@DudeNr33 @Pierre-Sassoulas should we open a new issue for the cases that @DudeNr33 pointed out that pyreverse can´t handle yet?

```python
class Compositor:
    def __init__(self):
        self.composition = self._create_dep()
    def _create_dep(self) -> Dependency:
        return Dependency()
```

```python
class Compositor:
    def __init__(self):
        intermediary = Dependency()
        self.composition = intermediary
```

**Comment by Pierre-Sassoulas** [comment]
I don't know if we want to open this can of worms. If we start to handle those two "simple" cases we'll have to handle a large number of arbitrarily hard (or rather Turing complete hard) other use cases. I'll let @DudeNr33 decide.

**Comment by DudeNr33** [comment]
We don't have a policy that you *must* open an issue in order to create a pull request.

I would open an issue first if
* the proposed change needs discussion and decision before implementation - for example a change where you're not sure whether a direct PR would be accepted or not
* you have a specific bug/feature request you'd like to see implemented, but are not able to provide a PR yourself right away

In other cases feel free to directly open a PR. If the change requires a changelog entry, you can first create the PR itself, and then add a changelog entry referencing the PR number instead of an issue and push that in a second commit.
