### ISSUE TITLE
Custom colour palettes for `pyreverse`

### ISSUE THREAD

**Issue by DudeNr33** [PyCQA/pylint#6738]
### Current problem

See [this SO question](https://stackoverflow.com/questions/72294217/pyreverse-uml-diagram-with-customized-color): 
The `--colorized` option uses a fixed colour palette. 
If one wants to use other colours, (s)he has to use a text-based output format and do a search-and-replace.

### Desired solution

As the colour palette is just a simple list of strings inside `pylint.pyreverse.writer.DiagramWriter` it should be possible to make this configurable.

**Comment by nickdrozd** [comment]
Related to this is the choice of default colors. Currently colors are chosen in alphabetical order:

```python
        self.available_colors = itertools.cycle(
            [
                "aliceblue",
                "antiquewhite",
                "aquamarine",
                "burlywood",
                "cadetblue",
                "chartreuse",
                "chocolate",
                "coral",
                "cornflowerblue",
                "cyan",
                "darkgoldenrod",
                "darkseagreen",
                "dodgerblue",
                "forestgreen",
                "gold",
                "hotpink",
                "mediumspringgreen",
            ]
        )
```

Thus the first two colors chosen are _alice blue_ and _antique white_, which is really a hideous combination.

I think a more thoughtful choice of default colors would be nice. Anyone with a little design sense (definitely not me) should be able to come up with something suitable for general use.

Better defaults would to some extent allay the need for configurability. Personally I don't want to configure colors, I just want colors that aren't ugly.

**Comment by DudeNr33** [comment]
I agree, but...

> I just want colors that aren't ugly

Ouch. 😄 
But yes, I did not put much thought into the color selection and I am also not a design person at all. So you got a point. 😄 

When I had to create diagrams for university I really like `seaborn`. What do you think about taking one of their [qualitative color palettes](https://seaborn.pydata.org/tutorial/color_palettes.html#qualitative-color-palettes). Maybe even directly the "colorblind" version to improve accessibility.

**Comment by nickdrozd** [comment]
> When I had to create diagrams for university I really like `seaborn`. What do you think about taking one of their [qualitative color palettes](https://seaborn.pydata.org/tutorial/color_palettes.html#qualitative-color-palettes). Maybe even directly the "colorblind" version to improve accessibility.

That looks fine to me. Choosing default colors raises the dangers of bikeshedding and analysis paralysis, so to make the decision easy, I propose using the colorblind palette starting from dark blue and going clockwise.
