### ISSUE TITLE
Slow performance with large numbers

### ISSUE THREAD

**Issue by ywanHK** [PyCQA/pylint#6745]
### Bug description

I'm currently working with a project that involves calculations of large numbers.

If I have a file named `test.py` containing the single line:
```python
test0 = 15 ** 20220529
```
It takes on average 1 minute to produce any output

### Command used

```shell
python3 -m pylint test.py
```

### Pylint output

```shell
------------------------------------
Your code has been rated at 10.00/10
```

### Expected behavior

```
------------------------------------
Your code has been rated at 10.00/10
```

### Pylint version

```shell
pylint 2.12.2
astroid 2.9.3
Python 3.9.7 (default, Sep 23 2021, 09:13:41)  [GCC 10.3.0 64 bit (AMD64)]
```

### OS / Environment

MSYS2 MinGW-64

**Comment by jacobtylerwalls** [comment]
We do actually perform the math here: https://github.com/PyCQA/astroid/blob/152083468dffb8ede7465f7f0250d081b8da3523/astroid/protocols.py#L119. 

`**` certainly seems like the most dangerous operator. Would you be interested in proposing a reasonable limit and submitting a patch?
