### ISSUE TITLE
local variable muddle

### ISSUE THREAD

**Issue by da-dada** [PyCQA/pylint#6779]
local variables are viewed strangely
[pylint_error.odt](https://github.com/PyCQA/pylint/files/8809469/pylint_error.odt)

**Comment by Pierre-Sassoulas** [comment]
Sorry but this issue is not detailed enough as is.

**Comment by da-dada** [comment]
well, I thought the details were obvious:

- if you run pylint on it there are just two trivial conventions (C0104 & C0321, which can easily be avoided)
- if you actually run it there is a local variable error on line 2 and if you comment that line out there is the next error on line 3

but I don't mind, I get along with it..

**Comment by Pierre-Sassoulas** [comment]
Please use markdown formatting to show the problematic code, use the template we provide to guide the reporting, and put at least as much effort in creating the issue as we will expand when reading it.
