### ISSUE TITLE
Outdated plugin pylint-i18n linked

### ISSUE THREAD

**Issue by kasium** [PyCQA/pylint#6793]
On the [pylint pypi page](https://pypi.org/project/pylint/) and the README the plugin [pylint-i18n](https://github.com/amandasaurus/python-pylint-i18n) is linked, which latest commit is from 2014, so 8 years ago.
Since the plugin seems to be outdated, I would suggest to remove the link. What do you think?

**Comment by DanielNoord** [comment]
Agreed! https://github.com/omegacen/pylint-sonarjson seems like a good replacement. I know its maintainer recently hopped into the repository to ask some question so they are also active on Github and seem to be actively maintaining the package.

**Comment by PrajwalBorkar** [comment]
I can work on this issue. Should I change the name also with the new repo name?

**Comment by DanielNoord** [comment]
> I can work on this issue. Should I change the name also with the new repo name?

Yes! That would be the best I think!

**Comment by PrajwalBorkar** [comment]
Fixed issue 👍 . Also contributing.md file have a link to doc which is not working. Should I create a new issue for this or there is it already available?
