### ISSUE TITLE
Configuration parsing fails if options for an unused extension are present

### ISSUE THREAD

**Issue by Mr-Pepe** [PyCQA/pylint#6799]
### Bug description

I run pylint twice, once without `pylint.extensions.docparams` and once with. Both use the same `pyproject.toml` configuration file. This was not a problem until 2.14.0 but now the first call crashes because the docparams options are not recognized.

### Configuration

```ini
[tool.pylint.master]
accept-no-param-doc = "no"
accept-no-raise-doc = "no"
accept-no-return-doc = "no"
accept-no-yields-doc = "no"
```

### Command used

```shell
pylint src
```

### Pylint output

```shell
pyproject.toml:1:0: E0015: Unrecognized option found: accept-no-param-doc, accept-no-raise-doc, accept-no-return-doc, accept-no-yields-doc (unrecognized-option)
```

### Expected behavior

Unused options do not lead to a crash or section names in `pyproject.toml` are honored.

### Pylint version

```shell
pylint 2.14.0
astroid 2.11.5
Python 3.9.5 (default, Nov 18 2021, 16:00:48) 
[GCC 10.3.0]
```

### OS / Environment

Kubuntu 21.04

**Comment by DanielNoord** [comment]
I think this sort of use-case might warrant an additional discussion.  Running two versions of `pylint` with a single configuration file was not one of the things we had in mind when we worked in the configuration refactor for `2.14`. I also don't know if we want to explicitly support it.

For now I'd suggest disabling `unrecognized-option`. You could also do ``pylint --accept-no-param-doc=no etc.`` in your second invocation. Then you could keep using the same file without disabling the message.

**Comment by Mr-Pepe** [comment]
That's unfortunate but makes sense. I will disable `unrecognized-option` for the time being. Thank you for the prompt replies! :)

**Comment by DanielNoord** [comment]
No worries! I'm going to put this on the milestone for our next minor release so we make sure to take a decision before releasing it (which will probably in a couple of months).

**Comment by DanielNoord** [comment]
> I think it would make sense to hard-code every extensions checker's options, and every deleted messages msgid/symbol (we already have a deleted messages list) and treat them differently with a message that could be disabled without touching `bad-option-value` and `unrecognised-option`. We discussed that during implementation but I did not realize that the use case of using the same configuration for two calls of pylint existed.

I'm really against any form of hard-coded list. I already kinda dislike the deleted messages list. How can any new or somewhat experienced contributor now that they need to add a message there? It really raises the bar for entry for maintainers/contributors. Same goes for any other hard-coded list which becomes necessary for correct functionality.

**Comment by Pierre-Sassoulas** [comment]
There's no other way than a hard coded list for deleted messages to avoid msgid collision. We have a "hard coded" list of messages in checkers originally, so it's just moving code around when you delete something. It's just data, it could be a json. Besides casual contributors are not supposed to take decision regarding removal of features.

For extensions we don't have to hard code it, we could recover the options dynamically.

**Comment by Pierre-Sassoulas** [comment]
I think we're forcing users to cleanup their pylint configuration instead of letting them choose if they want to (they have to disable a valuable warning if they don't want to). Another use case that is probably happening a lot as long as we don't have sane default or template : they copy paste a pylint conf online and comment an extension they don't want. Now they have to disable ``unrecognised-option`` and not be warned if there really is an unrecognised option, or they have to remove the option related to the extension the commented out (I.e. have to clean their pylint configuration).

**Comment by DanielNoord** [comment]
For me `unrecognised-option` is similar to `useless-suppression`: it's an informational message telling you that you could potentially clean up your code/configuration. If you don't want to receive such messages you can disable them completely.

We could include `unrecognised-option` in the discussion in https://github.com/PyCQA/pylint/issues/3512. However, I believe there is a difference between `useless-suppression` and `unrecognised-option`. As `unrecognised-option` can also warn you about misspelled options or renamed options that no longer work. That in itself is (for me) a reason to enable this by default and have users who don't want to receive such informational messages disable it once in their configuration. There is more benefit to this message than for some of the other informational messages.

I do think we could have communicated this a little better and should perhaps add some comment about this in our release notes summary.

**Comment by DanielNoord** [comment]
> Ho, I see. I think we have two features mixed inside the same message and we're not talking of the same one.
> 
> For me the main use of this message is not for configuration cleanup it's to warn you that you misstyped an option. I.e. you used `diszble=missing-dicstring` and it tells you why pylint is not taking the conf into account. If you're annoyed by having to cleanup and you disable unrecognised-option, then you loose this very useful feature.
> 
> I think 'misstyped-option' (or 'unrecognised-option') and 'useless-option' should be separated.

But how can we reliably determine what is useless want what is mistyped? To give a very crude example: is `disable=missing-signature-docstring` a mistype of `disable=missing-function-docstring` or an useless option of an extension that has removed or renamed that message? I don't think we can reliably determine that.

**Comment by Pierre-Sassoulas** [comment]
We can know that an option exists in pylint's unloaded extension, i.e ``accept-no-param-doc`` is not a typo, it's a valid option in ``pylint.extensions.docparams``.

**Comment by DanielNoord** [comment]
We can only know this by actually loading the extension. For extensions from `pylint` itself this could be done, although it goes a bit against the idea of `load-plugins`. But for external extensions we wouldn't know what to load if the extensions is not intentionally loaded. So the fix would only work for pylint's own extensions. That would complicate the situation further imo.

**Comment by DanielNoord** [comment]
This should now be solvable by just disabling `unrecognised-option` before you define the options that are used sometimes but not all times.

@Mr-Pepe Is that solution good enough for you?

**Comment by Mr-Pepe** [comment]
@DanielNoord  Sorry, I don't understand what you mean. Is there a related commit that I can look at or can you explain what exactly you mean?

**Comment by DanielNoord** [comment]
> @DanielNoord Sorry, I don't understand what you mean. Is there a related commit that I can look at or can you explain what exactly you mean?

```toml
[tool.pylint]
accept-no-param-doc = "no"
```

Will raise `unrecognised-option` without the plugin loaded.
However, the following should stop the message:
```toml
[tool.pylint]
disable=unrecognised-option
accept-no-param-doc = "no"
```

Note that this won't work, as the order is important:
```toml
[tool.pylint]
accept-no-param-doc = "no"
disable=unrecognised-option
```

**Comment by Mr-Pepe** [comment]
That works, thank you!
