### ISSUE TITLE
AttributeError: 'Call' object has no attribute 'name'

### ISSUE THREAD

**Issue by skirpichev** [PyCQA/pylint#6805]
### Bug description

Happens with 2.14.

See stacktrace in the [build log](https://github.com/diofant/diofant/runs/6705072636?check_suite_focus=true).

### Configuration

```ini
See pyproject.toml of the project.
```

### Command used

```shell
pylint diofant
or (more minimal ;)) pylint -j1 diofant/stats/drv.py
```

### Pylint output

```shell
Crash
```

### Expected behavior

No crash, as before.

### Pylint version

```shell
pylint 2.14.0
astroid 2.11.5
Python 3.10.2+ (heads/3.10:75c5dbc27e, Feb 19 2022, 06:58:32) [GCC 10.2.1 20210110]
```

**Comment by jacobtylerwalls** [comment]
Hi @huwcbjones it looks like an issue was found in #5847. Would you have any interest to take a look? The assumption that a return statement consists of a name is being violated here.

```python
class SingleDiscreteDistribution(Expr, NamedArgsMixin):
    def __new__(cls, *args):
        args = list(map(sympify, args))
        return Expr.__new__(cls, *args)
```

**Comment by skirpichev** [comment]
@jacobtylerwalls, I'm still get an exception on the master.

**Comment by huwcbjones** [comment]
Thanks for finding this bug @skirpichev , apologies for not expecting it 🙈 
Whilst I cook up a fix, you should be able to workaround the bug by assigning your return value to a temporary variable like so:
```py
class SingleDiscreteDistribution(Expr, NamedArgsMixin):
    def __new__(cls, *args):
        args = list(map(sympify, args))
        ret_val = Expr.__new__(cls, *args)
	return ret_val
```

**Comment by huwcbjones** [comment]
@jacobtylerwalls , yeah you can assign me to this - from the surface it doesn't look too hard to solve :)

**Comment by huwcbjones** [comment]
Actually it's not what we thought at all. It's getting caught on this line here: https://github.com/diofant/diofant/blob/98990d25c5f561f028285919d2453cd53b37c88b/diofant/stats/drv.py#L37
It seems that pylint can't find `pdf`, then goes down the Enum rabbithole when it arguably shouldn't 😕

**Comment by DanielNoord** [comment]
@huwcbjones I was able to reproduce the crash by taking the example you added:
https://github.com/huwcbjones/pylint/blob/44a3d96e1af985c6ad290a51555b9c7ced0a7079/tests/functional/e/enum_self_defined_member_5138.py#L16-L22
And returning on L16 instead of L22. You'll need to change some stuff to make this actually unable with `python`, but the crash still occurs.

We might need to fix another issue with recognition of `Enums`, but the crash with `return` not always having a `nodes.Name` is still valid.

**Comment by huwcbjones** [comment]
Yeah, I came up with the following test case because it seems that this code path was triggered because it looked like an Enum but wasn't an Enum. PR coming soon
```py
"""Tests for self-defined Enum members (https://github.com/PyCQA/pylint/issues/6805)"""
# pylint: disable=missing-docstring
class Foo(type):
    pass

class Parent:
    def __new__(cls, *args, **kwargs):
        return object.__new__(cls)

class NotEnumHasDynamicGetAttrMetaclass(metaclass=Foo):
    def __new__(cls):
        return Parent.__new__(cls)

    def __getattr__(self, item):
        return item

    def magic(self):
        return self.dynamic

NotEnumHasDynamicGetAttrMetaclass().magic()
```

**Comment by Pierre-Sassoulas** [comment]
Removing the 'need-backport' label because it's an issue, the merge request is what we're backporting.
