### ISSUE TITLE
Mark v3.0.0-a5 release as prerelease

### ISSUE THREAD

**Issue by SuperSandro2000** [PyCQA/pylint#6816]
### Current problem

v3.0.0-a5 is marked as a full release and would e.g. trigger the update bot in NixOS. If it would be marked as prerelease that would not happen and it would clearly convey that pylint 3 is not ready yet.

### Desired solution

Change v3.0.0-a5 release to a prerelease.

**Comment by Pierre-Sassoulas** [comment]
I think this is github treating alpha releases like real release if you do not use the right option in the GUI. I was wrongly assuming that if it's an alpha then it's a pre-release. It also explain why dependabot was suggesting 3.0 alpha 4 some time ago. Imo this is github trying to take pypi's job and butchering it. At least it's easy to fix that by editing the release, which is what I'm going to do now.

Thank you @SuperSandro2000 that's very helpful we won't have to release an alpha for 3.0 for each major thanks to you :) !

**Comment by Pierre-Sassoulas** [comment]
> I think there is only one issue fixed in the beta, which has created issues of its own. Perhaps we should just jank them for now?

I removed the json change from the 3.0 alpha it was only the bump from 2.14 to 3.0. This was a semantic release for those who want to use the latest version so they don't use pylint 2.9 unknowingly.
