### ISSUE TITLE
not-callable and subclassing

### ISSUE THREAD

**Issue by da-dada** [PyCQA/pylint#6868]
````python
class Base():
  def __new__(cls):
    inst = super().__new__(cls)
    if init := getattr(inst, 'init', None):
      init()

class Derived(Base):
  def init(self):
    print(f"'init' of {self.__class__}")

Derived()
````
`init` **is** callable but _pylint_ thinks not

**Comment by jacobtylerwalls** [comment]
`init`(the result of `getattr`) is not callable if it's `None`, which `pylint` thinks it is because that's what `getattr` returns for `Base`.

Please use the issue template when reporting new issues. There are multiple lines in your example that refer to "init".
