### ISSUE TITLE
Should we switch to ``codecov`` instead of ``coveralls``

### ISSUE THREAD

**Issue by DanielNoord** [PyCQA/pylint#6935]
Lately I have been getting increasingly annoyed with ``coveralls``. This is for a number of reasons:
* It can take 15/20 minutes for their comment to actually be posted after the CI step passed
* They don't show the commit for which the comment was posted (see https://github.com/lemurheavy/coveralls-public/issues/1638), which is annoying as you can't be sure that the comment is updated due to 1.
* You can't see the annotated code without an account
* They handled their more than a week long outage very poorly this winter

That's why for my own project I have switched to [codecov](https://about.codecov.io). I think it is the main other service and it is used (for example) by `home-assistant` and `pytest`. Both of which are projects that I value highly in terms of CI and project maintenance.

The switch to `codecov` is pretty easy, see: https://github.com/DanielNoord/pydocstringformatter/pull/112
For public projects you don't need to set up any environment variables and can just start using the service.

It would be good to give some administration rights to some members though to perhaps tweak the PR comments.

I'd be willing to create a PR to do this, but I want some discussion/confirmation first.

_Tagging for input @Pierre-Sassoulas @jacobtylerwalls_

**Comment by Pierre-Sassoulas** [comment]
>It would be good to give some administration rights to some members though to perhaps tweak the PR comments.

I need someone to be a member of PyCQA to be able to add him to the pylint's internal maintainer/dev/admin group. PCManticore want sigmavirus24 confirmation to grant me the right to add someone to PyCQA so right now it's not possible (but I'm pestering Ian about it with some regularity 😄). 

I don't have strong opinion about the subject, I think I got accustomed to coveralls more or less working over the years. But I trust you if you think codecov is better. Being able to merge multiple pipelines result would be nice as it's impossible to do with coveralls (but it's probably out of scope for the migration.)

**Comment by jacobtylerwalls** [comment]
+0

> I don't have strong opinion about the subject, I think I got accustomed to coveralls more or less working over the years.

Same.

**Comment by clavedeluna** [comment]
I'd like to help improve code coverage but as mentioned above, I can't see annotated code right now.

**Comment by Pierre-Sassoulas** [comment]
You need to login with your GitHub account @clavedeluna coverall need to use your api key to make the call to get the code or they would be rate limited by GitHub

**Comment by Pierre-Sassoulas** [comment]
I'm now admin in PyCQA, and Jacob, Marc and Daniel should be admin in pylint (let me know if that's not the case).

**Comment by DanielNoord** [comment]
I'll prepare the PR for this tonight. You might need to turn a switch somewhere but this should be relatively straightforward :smile:
