### ISSUE TITLE
Please add category ({C}) to 'text' and 'parseable' output format

### ISSUE THREAD

**Issue by absurd34** [PyCQA/pylint#6943]
### Current problem

With the 'text' (default) and 'parseable' output formats, text editors will not detect levels of parsed issues.

For emacs, this means there's no (warn/error/info) eye candy (where desired). You can also not skip info-only messages (via 'compilation-skip-treshold'), which is more significant for me.

### Desired solution

I'd love to see the default msg-template (imho for both, 'text' and 'parseable') to be

`{path}:{line}: {C}: [{msg_id}({symbol}), {obj}] {msg}`

This is what I use at the moment, working oob for emacs, at least.

As this seems rather obvious, maybe I am missing something here :)? Maybe that format does not work for many
other editors?

Thanks!

Stephan

**Comment by Pierre-Sassoulas** [comment]
Message's id contain the level of parsed issues in the starting letter. In ``a.py:2:3: C0303: Trailing whitespace (trailing-whitespace)`` the ``C`` from ``C0303`` indicate that it's a convention level message.

Changing the default value for a setting carry the risk of breaking settings that work for a lot of users. It's also possible to use a template for the message in your configuration, and there's a emacs specific plugin, did you try it ?

**Comment by absurd34** [comment]
Hi Pierre,

thx for your answer.

I am fully aware that the default format carries the *information* (and specialized tools can certainly parse it), however it seems to me that over the years many linters/compilers etc. mostly adhere to an unspoken convention

`<file>:<line>[:<col>]: <severity>: <msg>`

, with `<severity>` being one of the well-known logger prefixes/log level names (and yes, the pylint message id like 'I123' is not one of them). Also, pylint's (2.14.1) default parseable output looks rather like this

`a.py:2: [I0011(locally-disabled), ] ...`

Adhering to that "convention" *by default* would (imho) make many "parse-use-cases" just work oob, with no further strings need to be attached.

However, your argument that it may break a lot of users is certainly strong ;).

So I'd still love to see it, but I am also fine custom-"fixing" it using --msg-template (as I do now).

Thx!

S

**Comment by DanielNoord** [comment]
@absurd34 Thanks for opening the issue. I think @Pierre-Sassoulas is right that the churn and backwards incompatibility might be too problematic.

That said, we have been looking for an user of `Emacs` to provide some feedback on #344. Could you perhaps take a look and see if the changes discussed there make sense? It would be very much appreciated 😄

**Comment by absurd34** [comment]
> I think `a.py:2:3: C0303: Trailing whitespace (trailing-whitespace)` is very close to `<file>:<line>[:<col>]: <severity>: <msg>` in fact I don't think changing it to `a.py:2:3:C:0303: Trailing whitespace` is worth the churn, even in 3.0. The output of pylint has been well established for over a decade and the `--msg-template` option exists. I'm closing as won't fix.

Just to avoid any misunderstanding (you added it twice), this is **not** the format pylint produces, neither for default 'text' nor for 'parsable'. 

For people maybe reading this through the internets having the same little issue ("no severity with vanilla lint-like parsers (like emacs compilation mode) for default output"), I'd recommend using

`--msg-template="{path}:{line}:{column}: {C}: {msg_id}: ({symbol}), {obj}] {msg}"`

in your custom call. Don't configure this [user-]global though as it might break specialized tools (like emacs pylint support in python mode).

Hth,

S
