### ISSUE TITLE
Create ``useless-explicit-parent`` message

### ISSUE THREAD

**Issue by DanielNoord** [PyCQA/pylint#6954]
### Current problem

Ref. https://github.com/PyCQA/pylint/issues/5083.

New message based on a change that `pyupgrade` makes.

This:
```python
class A:
    def method():
        ...

class B(A):
    def method_two():
        A.method()
```

Is changed into:
```python
class A:
    def method():
        ...

class B(A):
    def method_two():
        super().method()
```

### Desired solution

Raise ``useless-explicit-parent`` for this pattern.

**Comment by hmc-cs-mdrissi** [comment]
https://github.com/asottile/pyupgrade/pull/548#issue-1009877759 That change got reverted. In general when multiple inheritance happens it is undefined what one class’s next parent will be.

**Comment by DanielNoord** [comment]
Thanks @hmc-cs-mdrissi, we would have never caught that.

Closing as I trust their judgement about this!
