### ISSUE TITLE
pylint 2.7 hangs on many-core Windows machines

### ISSUE THREAD

**Issue by randomascii** [PyCQA/pylint#6965]
### Bug description

We use PyLint in Chromium and we have been switching to Python 3 and PyLint 2.7 recently. While testing on a many-core (96 logical processor) machine I found that PyLint reliably hangs. This is due to a known Python 3 bug with multi-processing on machines with more than 56 (possibly more than 63 or 64) logical processors. We first hit this bug last year (discussed in crbug.com/1190269) but only recently discovered that PyLint is vulnerable.

If we were running PyLint from the command line then we could just pass a -j value that is capped at 56 (or 63, or 64) but I have not been able to figure out how to cap the jobs value when invoking PyLint through lint.Run().

Internally PyLint should cap its parallelism until the Python 3 bug (not yet reported I believe, sorry) is fixed.

### Configuration

```ini
96 logical processor Windows machine
The version of Windows does not seem to matter. This only happens on Python 3 and it is believed to affect all versions of Python 3.
```

### Command used

```shell
I invoke pylint quite directly using "git cl presubmit --all --force" from Chromium. This ends up invoking many steps including pylint_main.py, like this:

  from pylint import lint  # pylint: disable=bad-option-value,import-outside-toplevel
  lint.Run(argv)

https://source.chromium.org/chromium/chromium/tools/depot_tools/+/main:pylint_main.py;l=17?q=pylint_main.py&sq=
```

### Pylint output

```shell
No output - it hangs.
```

### Expected behavior

I expect the PyLint run to complete.

### Pylint version

```shell
pylint 2.7
Python 3.8.10
```

### OS / Environment

Windows 10

**Comment by Pierre-Sassoulas** [comment]
It seems easy to fix once we know the precise number we should use. Maybe 50 is close enough ?

Regarding using pylint API there's [this documentation](
https://pylint.pycqa.org/en/latest/development_guide/api/pylint.html#as-you-would-launch-the-command-line):

I suppose it would work with:
```python
from pylint.lint import Run

Run(argv=["--jobs 42", "myfile.py"])
```

**Comment by DanielNoord** [comment]
> This odd limit is presumably because WaitForMultipleObjects allows a maximum of MAXIMUM_WAIT_OBJECTS in its array (MAXIMUM_WAIT_OBJECTS == 64) and there must be four other handles (besides the child processes) which multiprocessing ends up waiting on.

This indeed seems like a bug in `multiprocessing`. You seem to have much more knowledge about this than me (I never heard of logical processors until today). I did some (short) digging in the Python bug tracker and found https://github.com/python/cpython/issues/71090 and then https://github.com/python/cpython/issues/72355.
I think the comment in https://github.com/python/cpython/issues/71090#issuecomment-1093713677 might allude to a potential problem here? More events being listened to so the previous fixes no longer work?

Either way, I think a bug report to `cpython` would be appreciated. Now that they are on Github that should be fairly easy. I'd be happy to do so, but considering you clearly have more knowledge about the topic perhaps it is better if you could do this?

> The bad news is that the --jobs feature does not let me _decrease_ the number of jobs. That is, if I pass '--jobs', '42' on my 96 logical-processor machine then I still get 96 jobs.

Hmm, that's weird. If you're able to do so it would be helpful if you could add a `print(jobs)` at L139 here:
https://github.com/PyCQA/pylint/blob/bc7f8dac5a1d9ac2a1f6966029f5fc134d139f2f/pylint/lint/parallel.py#L140

That's what we are passing to `multiprocessing` so it would narrow down the issue to either `pylint` or `multiprocessing`.

> This slow startup time presumably explains the bug I saw about how ineffectual multiprocessing was for pylint. You would need a _huge_ batch of files to justify doing significant multi-processing.

Yeah, this is a bug issue. Which I'm not actually sure how to resolve. We would need a complete rewrite of the `parallel` code. We currently spin up a new `PyLinter` class for every job. That is taking way too long (probably).
But I'm not sure what the best approach is to create a `PyLinterLite`...

> I don't know whether the slow startup is a bug in multiprocessing or in pylint. I just measured some of our presubmits and 60-way parallelism more than doubles the time that they take, from ~30 to ~70 s.

I feel like it is a combination but we could certainly do better here.

**Comment by randomascii** [comment]
Thanks for all the help!

Now that I know enough about this issue I will file a CPython bug and get the root cause fixed.

I dropped in a bit of logging as you suggested and eventually realized that the -jobs weirdness is self inflicted. We are _already_ passing --jobs to PyLint when we run it in our self-defined parallel mode. When we run it in serial mode we don't pass --jobs at all and then PyLint uses its default. So, all I was doing was changing our serial mode into parallel. Sigh... And, it is ironic that we were already passing --jobs to lint.Run, just in a totally different part of the code.

So, I _can_ work around this and I will cap the value at some reasonable number to avoid this bug and reduce startup overhead.

I don't know if PyLint should add a mitigation or if it should just wait for a CPython fix.

**Comment by DanielNoord** [comment]
> Now that I know enough about this issue I will file a CPython bug and get the root cause fixed.

👍 

> So, I _can_ work around this and I will cap the value at some reasonable number to avoid this bug and reduce startup overhead.

🎉 

> I don't know if PyLint should add a mitigation or if it should just wait for a CPython fix.

Well, I don't think this will be classified as a security bug so it won't be backported to all the versions we support. So we should at least mitigate on older versions.
_And CPython development can be slow for issues with low interest. Considering nobody has run into this yet I'm not sure it will be top priority 😄_

Btw, since you did most of the work here you're obviously more than welcome to make the bug fix for `pylint` yourself. You've already familiarised yourself with the relevant code. But I can understand if this issue has taken you more time than planned.

**Comment by Pierre-Sassoulas** [comment]
Thank you for the analysis @randomascii, much appreciated. I opened https://github.com/PyCQA/pylint/issues/6967 for the other issue with multi-processing startup time.

**Comment by randomascii** [comment]
This is the change I am proposing in Chromium's depot_tools. By limiting cpu_count and _pool_size this may mitigate this python 3 bug across multiple parts of our presubmit system. Plus, I cap the number of jobs at 1 + file_count // 10 to avoid the situation where 96 child processes are created for just a few inputs (I assume that input files are not shared across processes, but I might be wrong). Here is the proposed depot_tools/Chromium CL:

https://chromium-review.googlesource.com/c/chromium/tools/depot_tools/+/3711282

**Comment by randomascii** [comment]
I landed my depot_tools change so Chromium no longer hangs when running presubmits, but as promised I'm investigating what's going on under the hood and how it should be changed. Whoo boy - this whole thing is a bug farm.

For starters, this CPython comment is wrong:
https://github.com/python/cpython/commit/39889864c09741909da4ec489459d0197ea8f1fc#diff-84a955ea642d41d9f164e9f94499d8eb33c357ec7f4362a341951f6f67ab21a1R114
WaitForMultipleObjects can wait for a maximum of 64 objects, not 63.

However, if the maximum was 63 then given that there are two other handles that multiprocessing waits for then 61 would be the correct maximum pool size, as this comment says:
https://github.com/python/cpython/commit/39889864c09741909da4ec489459d0197ea8f1fc#diff-eb5cd13d65d2f215d8dc0d95eb1a1341ff69b226ac56ec6099e39582edecc8cfR219

However there is a CPython bug. When I use a pool size of 61 with Python 3.8.10 I get this error:
  ValueError: need at most 63 handles, got a sequence of length 63

So, CPython is range-checking with the wrong value (63 instead of 64) and it is (was, actually) checking with >= instead of >. The comparison-operator bug was fixed here (issue was https://github.com/python/cpython/issues/84444):
https://github.com/python/cpython/commit/92b5dc780db968f6277f42cb06926dddb7475dc6

Therefore, while the CPython pool-size limit on Windows _should_ be 62, it is actually 60. Once the fix above ships then the limit will go up to 61, which is still not where it should be.

The other problem, however, is that the ValueError exception gets thrown but Python still hangs. If output is not being displayed then the ValueError exception is invisible and we just have a hang.

BTW, after landing my fix I noticed some new Pylint warnings in some scripts that hadn't changed in a long time. I eventually tracked the new warnings to the change in parallelism. That is, when I analyzed these files with jobs=1 I got eight extra warnings that I didn't get when analyzing them with jobs=2 or higher. More details and the change that I had to land to fix these issues are here:
https://chromium-review.googlesource.com/c/chromium/src/+/3712154
Is this a known problem with parallel Pylint? I'm tempted to do serial Pylint everywhere because the parallelism buys us little and risks missing some warnings.

I have a couple of CPython bugs to file, I guess.
https://github.com/python/cpython/issues/94242 - Off-by-one error in _winapi.WaitForMultipleObjects
https://github.com/python/cpython/issues/94243 - Pool constructor should reject too many processes rather than hanging later

As for Pylint, I suspect that a version of this fix that I made to wpt is appropriate:
https://github.com/web-platform-tests/wpt/commit/bdc35e89ff09e7b496b9543746a85031ddfcc83d

This fix wouldn't actually help Chromium (because we passed in our own jobs parameter) but it could help others.

**Comment by DanielNoord** [comment]
> BTW, after landing my fix I noticed some new Pylint warnings in some scripts that hadn't changed in a long time. I eventually tracked the new warnings to the change in parallelism. That is, when I analyzed these files with jobs=1 I got eight extra warnings that I didn't get when analyzing them with jobs=2 or higher. More details and the change that I had to land to fix these issues are here: https://chromium-review.googlesource.com/c/chromium/src/+/3712154 Is this a known problem with parallel Pylint? I'm tempted to do serial Pylint everywhere because the parallelism buys us little and risks missing some warnings.

Yeah this is sadly a known issue. There are some messages that depend on the state of other files/messages which we don't really handle well for multiprocessing. I know there was a contributor who was planning to look into this for `2.15`, but obviously we can't make any promises!

**Comment by randomascii** [comment]
After discussion on https://github.com/python/cpython/issues/94242 it appears that 61 is the correct maximum because Python requires space for _three_ extra handles. The comments give the wrong reason for the 61 limit, but 61 is correct (assuming Python 3.9 or higher).
