### ISSUE TITLE
 Class <---------> has no 'DoesNotExist' member (no- member)

### ISSUE THREAD

**Issue by SugamChhatkuli** [PyCQA/pylint#6990]
### Question

except Post.DoesNotExist:
            return Response(status=status.HTTP_404_NOT_FOUND)

### Documentation for future user

for solving DoesNotExist in pylint

**Comment by Pierre-Sassoulas** [comment]
Please use the bug template and give the current code, current result and what you expect the code to do. We're unpaid volunteer, if you want us to help you, then you should at least invest some time in creating a good issue first.
