### ISSUE TITLE
Pylint is ignoring the `ignore-paths` instruction from `.pylintrc`

### ISSUE THREAD

**Issue by tanogedler** [PyCQA/pylint#7108]
### Bug description

After the last release of Pylint, to version [2.14.4](https://pypi.org/project/pylint/2.14.4/), Pylint is not recognizing properly the `ignore-paths` instruction from `.pylintrc`

It works fine from the command line. 

I tested with the previous version 2.14.3 and it worked both in the command line and from `.pylintrc`

### Configuration
[MASTER]
ignore-paths=^.*/\.ignore_dir
```

This is part of my `pyproject.toml` file

```
[tool.poetry.dependencies]
python = "^3.9"
numpy = "^1.22.3"

[tool.poetry.dev-dependencies]
pylint = "2.14.4"
```
```

### Command used

```shell
poetry run pylint --recursive=y .
```

### Pylint output

```shell
************* Module file_to_be_ignored
.ignore_dir/file_to_be_ignored.py:13:4: E0001: invalid syntax (<unknown>, line 13) (syntax-error)

------------------------------------------------------------------
Your code has been rated at 0.00/10 (previous run: 0.00/10, +0.00)
```

### Expected behavior

poetry run pylint --recursive=y --ignore-paths .ignore_dir/ .

--------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 0.00/10, +10.00)

### Pylint version

```shell
pylint 2.14.4
astroid 2.6.6
Python 3.9.12 (main, Apr  5 2022, 06:56:58) 
[GCC 7.5.0]
```

### OS / Environment

Ubuntu 22.04

**Comment by DanielNoord** [comment]
Closing as duplicate of https://github.com/PyCQA/pylint/issues/5398. We welcome any suggestions to allow both Windows as Unix paths as well as allowing \ to be used as escape character.

**Comment by SteveHespelt** [comment]
To be fair to @tanogedler, his OP wasn't about allowing windows path delimiters to be specified. His example shows only Unix path delimiter.
