### ISSUE TITLE
Add a configuration file in documentation example for message

### ISSUE THREAD

**Issue by Pierre-Sassoulas** [PyCQA/pylint#7143]
### Current problem

Right now we do not show the configuration used for example. We could and it would:

- show readers what need to be done to activate the check if it's an extension, or a standard but optional check (soon ™️)
- permits to create simpler examples by lowering the values to something sane (i.e. max line length = 15 instead of having 120+ character in the example, max-return-values = 2 instead of 11...)
- demonstrate some options that can affect the message (!)

### Desired solution

Show the configuration used in bad/good and use it as an example of configuration related to a message. There's some issue with this:

- How to identify related options?

It's not easy to determine that without reading the code, we struggle as much as user here.

- How to show the difference between the default value and the value being used in a test?

If the default value is 120 we need a way to show what it is if we change it to 15.

- How to handle duplication of the load-plugins warning

We already have a message for extensions right now.

### Additional context

Initially discussed in https://github.com/PyCQA/pylint/pull/7142#pullrequestreview-1031209077

**Comment by Pierre-Sassoulas** [comment]
We should do https://github.com/PyCQA/pylint/pull/7144#discussion_r915813472, right after this is implemented.

**Comment by stdedos** [comment]
_Well, since you are so kind to pinpoint me exactly where to make the fix ..._ 😄
