### ISSUE TITLE
Does pylint have similar thing to `flake8 --disable-noqa`

### ISSUE THREAD

**Issue by copdips** [PyCQA/pylint#7207]
### Question

My goal is to check all the ignored `inline` pylint errors/warnings

### Documentation for future user

the argument to have similar thing to `flake8 --disable-noqa`

**Comment by Pierre-Sassoulas** [comment]
You can enable [suppressed-message](https://pylint.pycqa.org/en/latest/user_guide/messages/information/suppressed-message.html) in your configuration or with CLI : ``pylint --enable=suppressed-message``
