### ISSUE TITLE
Need help writing a plugin that needs to be robust to different import pattens

### ISSUE THREAD

**Issue by psalvaggio-dl** [PyCQA/pylint#7223]
### Question

I am trying to write my first pylint plugin and coming across some issue. The plugin's purpose is to enforce some best practices. Here's the general idea of what I am trying to do:

I am using a third-party library, let's call it `lib`. In that library, there is a submodule (let's call is `sub`) and in there is a class (let's call it `MyClass`. This class's constructor takes a keyword argument `kw_arg` that defaults to `None`. I want to write a check that makes sure the user is passing a non-`None` value to this parameter, as if they pass `None`, we get into issues downstream.

My challenge is this, this type `lib.sub.MyClass` can show up a few different ways. The different import behaviors I see are:
```python
import lib
from lib import sub as some_alias
from lib.sub import MyClass
```
which results in the following call sites:
```python
foo = lib.sub.MyClass(...)
bar = some_alias.MyClass(...)
baz = MyClass(...)
```
This results in differing nodes in `astroid`:
```
Attribute.MyClass(attrname='MyClass',
                              expr=<Attribute.sub l.39 at 0x7f6647d59400>)

Attribute. MyClass(attrname='MyClass',
                              expr=<Name.some_alias l.41 at 0x7f6647d13790>)

Name. MyClass(name='MyClass')
```
Is there a way to write a visitor to filter all calls down to calls of the `lib.sub.MyClass` constructor while being robust to these different import behaviors?

### Documentation for future user

Maybe an advanced guide to writing plugins. The basics are pretty simple.

**Comment by Pierre-Sassoulas** [comment]
You can use inference, an introduction to inference can be found here : https://pylint.pycqa.org/projects/astroid/en/latest/inference.html here's also a small example: https://github.com/guilatrova/tryceratops/issues/35#issuecomment-955055991

**Comment by psalvaggio-dl** [comment]
Thanks! I was able to call `infer()` and that does seem to normalize over the three import conventions, which is great. However, I am not seeing a way to get the `lib.sub` part of the class name anywhere, all the names I am seeing are just the name of the class, `MyClass` in my example. Any idea how one would figure out the module name of the class? In my particular case, the class name from the third-party library if very generic and I don't want to false alarm on the same class name in a different module?

**Comment by psalvaggio-dl** [comment]
Ahh, I found `.qname()`. That's exactly the solution I was looking for, thanks!

**Comment by Pierre-Sassoulas** [comment]
Glad it helped ! Any ideas on how to make this more discoverable in our doc ?
