### ISSUE TITLE
`check_parallel` does not restore `sys.path` to the original value

### ISSUE THREAD

**Issue by jacobtylerwalls** [PyCQA/pylint#7246]
`check_parallel` does not restore `sys.path` to the original value.

Discovered while working on #7117, but unrelated to the issue it tested.

Opening an issue purely for the sake of satisfying the towncrier pre-commit check, which requires issues for all bugfixes.

**Comment by Pierre-Sassoulas** [comment]
> Opening an issue purely for the sake of satisfying the towncrier pre-commit check

Can't we use the PR number ?

**Comment by jacobtylerwalls** [comment]
I wondered, but we may not even merge that PR.

**Comment by Pierre-Sassoulas** [comment]
I meant the number of the PR we open to fix the issue in this case  #7247 (we do need to open it then create the towncrier fragment or hope for no other issue/PR to be opened before we create ours though).

**Comment by jacobtylerwalls** [comment]
But then I have to `no-verify` my changes to get them up to Github. Opening an issue seemed lower friction.

**Comment by Pierre-Sassoulas** [comment]
> I have to no-verify my change

Is there a towncrier pre-commit check ? I often forgot to add the fragment myself I'd like this 😄

**Comment by jacobtylerwalls** [comment]
```shell
Check newsfragments......................................................Failed
- hook id: check-newsfragments
- exit code: 1

doc/whatsnew/fragments/slug.bugfix: does not respect the standard format 🤖👎

The standard format is:

<one or more line of text>
<one blank line>
<issue reference> #<issuenumber>

Where <issue reference> can be one of: Refs, Closes, Follow-up in, Fixes part of

For example:

``pylint.x.y`` is now a private API.

Refs #1234
```

**Comment by jacobtylerwalls** [comment]
Added in 54e54ad099c321fe825ed7328ffc54f794a339fe

**Comment by Pierre-Sassoulas** [comment]
Ha right, but this does not check that the number is an issue or that it actually exists in github, only that the format is standard. So I think you can "cheat" 😄

**Comment by jacobtylerwalls** [comment]
Where <issue reference> can be one of: Refs, Closes, Follow-up in, Fixes part of

"Fixes part of too lazy to open an issue" 🤣

**Comment by Pierre-Sassoulas** [comment]
>"Fixes part of too lazy to open an issue" 🤣

🤣 

It's funny because it's true. I'm pretty sure 50% of the time when I "reference" something it means this is a lazy pull request with no attached issue 😄

**Comment by DudeNr33** [comment]
The pre-commit check only triggers if you have created a new file in the newsfragments folder.
You can use the PR number if you'd like, but you will have to push at least twice (as you don't know the PR number beforehand).

I'm open to ideas how to improve this! 😊

**Comment by Pierre-Sassoulas** [comment]
It was mostly just a discussion on the benefit of creating a small issue vs a two stage PR, both are fine and we don't need to change anything imo.
