### ISSUE TITLE
Homepage on pypi.org leads to a non existing page

### ISSUE THREAD

**Issue by kasium** [PyCQA/pylint#7298]
### Bug description

1. Open https://pypi.org/project/pylint/
2. Click on "Hompage"
3. Page https://www.pylint.org/ opens which doesn't exist

### Configuration

```ini
n/a
```

### Command used

```shell
n/a
```

### Pylint output

```shell
n/a
```

### Expected behavior

Correct page is linked

### Pylint version

```shell
n/a
```

### OS / Environment

n/a

### Additional dependencies

n/a

**Comment by Pierre-Sassoulas** [comment]
Nice catch, thank you for opening an issue !
