### ISSUE TITLE
Primer test does not fail a CI correctly when it finds a crash

### ISSUE THREAD

**Issue by DanielNoord** [PyCQA/pylint#7328]
### Bug description

When a PR creates a new crash in one of the projects the CI should fail. Currently this isn't the case.

See:
https://github.com/PyCQA/pylint/pull/7327#issuecomment-1221539878
And the associated run:
https://github.com/PyCQA/pylint/runs/7938783923?check_suite_focus=true

**Comment by jacobtylerwalls** [comment]
I thought @Pierre-Sassoulas was -1 on this, as this would introduce a dependency on bleeding edge astroid to pylint's CI. (As part of the Grand Compromise where I got permission to use bleeding edge astroid on primer runs.)

But I do think we should remove the sentence that says "... unlikely to have been caused by..."

**Comment by DanielNoord** [comment]
Yeah, but since we supply run `type` to the `--run` command can't we make the `PR` type raise a fatal exception? Now that I have removed the potential for an `astroid` bump a PR can never trigger a crash due to bleeding edge `astroid` that is not already included in a `main` run 😄

**Comment by jacobtylerwalls** [comment]
Yes, I like that. Thanks for walking me through it.

**Comment by DanielNoord** [comment]
I did forget how we previously made the `CI` fail on `fatal` errors. Do you happen to still know this? And if so, would you want to create a PR for this? I can obviously figure something out, but might take me a bit longer.

**Comment by jacobtylerwalls** [comment]
All we did was `assert` no fatal errors inside the primer command, which works but prevents reporting anything non-fatal also. (I was never really worried about that.)
