### ISSUE TITLE
check_docs checking return tags

### ISSUE THREAD

**Issue by rneu31** [PyCQA/pylint#734]
pylint.extensions.check_docs should check for documentation explaining the return. If a return is present, enforce that it is there. If a return is not present, check that documentation is NOT there (I have seen developers explain a return that was not even present).

**Comment by PCManticore** [comment]
@AWhetter you might be interested in checking this one. AFAICT, it is dealt partially, do you think it's easy to add support for checking if there is extraneous documentation for missing returns?
