### ISSUE TITLE
Let pyreverse show abstract methods differently

### ISSUE THREAD

**Issue by dgutson** [PyCQA/pylint#7346]
### Current problem

Currently, there's no way to distinguish abstract methods.

### Desired solution

Abstract methods are shown in italic in UML diagrams.
I propose to get that idea and shows `@abstractmethod` also in italic.
CC @qequ

**Comment by dgutson** [comment]
@Pierre-Sassoulas @mbyrnepr2 did this make it into 2.16?

**Comment by mbyrnepr2** [comment]
It did indeed @dgutson! 2.16 isn't released yet but you can keep an eye on the progress here: https://github.com/PyCQA/pylint/milestone/71
