### ISSUE TITLE
check_docs accept-no-param-doc

### ISSUE THREAD

**Issue by rneu31** [PyCQA/pylint#735]
Where in the pylintrc file should accept-no-param-doc=yes be specified? 

The code below does not trigger warnings about missing documentation for arg_d, arg_e, nor arg_f.

    def hello2(arg_d, arg_e, arg_f):
        """Hello.
    
        
        """
        arg_d = 4
        arg_e = 5
        arg_f = 4
        return arg_d, arg_e, arg_f

**Comment by PCManticore** [comment]
This works by running ``pylint a.py -rn --load-plugins=pylint.extensions.check_docs --accept-no-param-doc=n`` or by putting accept-no-param-doc in MASTER section in pylintrc file. Hope this helps.

**Comment by stevekuznetsov** [comment]
This should really be documented better -- would never have thought to put it under the `[MASTER]` heading

**Comment by PCManticore** [comment]
The problem is that extensions don't necessarily have their own section. Feel free to open a new issue if you have any suggestion for improving this.
