### ISSUE TITLE
``pylint.org`` is defunct and we might need to move some stuff

### ISSUE THREAD

**Issue by DanielNoord** [PyCQA/pylint#7384]
### Question

I got an email from readthedocs.org that it can nog longer find the `docs.pylint.org` domain to serve the documentation to. I can remove the configuration for that domain but I want to be sure we're giving up on the domain.

There might be other places where this is necessary after `pylint.org` is now no longer in the air.

### Documentation for future user

/

**Comment by Pierre-Sassoulas** [comment]
Thanks for opening the issue, I was looking at it too. The current domain ``https://pylint.pycqa.org`` is going to need to be changed if we don't get admin right for pycqa soon and if we have to create another organization. (I've been trying to add you as an admin for months, but you're not the only one that need more rights in pylint and I can't do that right now. I'm sure you know the context.). ``docs.pylint.org`` is a very nice domain but I don't know who set up this, and I don't think I want to buy (a/the) domain myself. logilab recently removed the pylint mail archive too. I have no idea how other open source project handle this. [But it seems there's a default domain for read the doc](https://docs.readthedocs.io/en/stable/custom-domains.html#custom-domains). We could use this one at least.

**Comment by DanielNoord** [comment]
I think `pylint.org` was also hosted/bought by `logilab`. They probably cleaned up some of their older projects.

I'm fine with removing `docs.pylint.org` and staying on `pylint.pycqa.org`.

_Slightly off topic, but for now I don't think we should create our own organisation. For me personally the benefits don't outweigh the negatives at the moment._

**Comment by Pierre-Sassoulas** [comment]
Let's remove ``docs.pylint.org`` from the read the doc configuration and let me do a quick follow up on the code then.

Could you join discord to chat, or we could create a common private project on github ? I have no way to contact you privately :)

**Comment by Pierre-Sassoulas** [comment]
Closing as I removed the configuration for the domain in read the doc, and there's no reference to it anywhere in the repository (nor in astroid repository).

**Comment by Pierre-Sassoulas** [comment]
@The-Compiler searched for what happened, I'm going to copy paste his finding here:

> The domain doesn't seem to be in control of Logilab at
> all anymore... Judging from the report for [pylint.org](http://pylint.org/) shown by
> https://completedns.com/dns-history/ this is what happened:
> 
> - It looks like Logilab always paid for the domain in June and extended
>   it for 2 years - you can see it being dropped in 2016, 2018, and 2020,
>   and then restored a few days later...
> - In April 2022, it was moved from Logilab to Gandi.net. Not quite sure
>   what happened there? It might be Logilab still moving some
>   infrastructure (though [logilab.org/.fr](http://logilab.org/.fr) is still using their own
>   nameservers), or maybe it was transferred to someone already?
> - In June 2022, the domain expired yet again, but apparently nobody took
>   care of extending it...
> - In August 2022 (probably after some holding period), DropCatch.com took
>   control of it, which seems to be a business specialicing on auctioning
>   off expired domains: https://www.dropcatch.com/hiw/overview
>   Also see: https://web.archive.org/web/20220917041022/http://www.pylint.org/
> - At the same time, https://github.com/PyCQA/pylint/issues/7384 was
>   opened, but it looks like nobody there found out what's going on or
>   wanted to take control over the domain.
> - Finally, in October 2022, it got transferred to [xserver.jp](http://xserver.jp/), which
>   seems to be a Japanese server hoster. And indeed the IP [pylint.org](http://pylint.org/) is
>   pointing to nowadays is owned by [xserver.jp](http://xserver.jp/). It looks like it
>   originally did show some Japanese blog (?):
>   https://web.archive.org/web/20221006104954/https://pylint.org/
>   and then, a few days later, started to look like now:
>   https://web.archive.org/web/20221013033155/https://pylint.org/
> 
> I suppose this explains the ad banners for some dodgy japanese pill
> seller website on [pylint.org](http://pylint.org/) then... I suppose what happened is that
> they copied and deployed the original webpage to appear legitimate, and
> then added their ads.

It's very unlikely that we're going to be able to recover the domain at this point.
