### ISSUE TITLE
Add a minimal option to pylint --generate-toml-config

### ISSUE THREAD

**Issue by cclauss** [PyCQA/pylint#7485]
### Current problem

`pylint --generate-toml-config` can produce 500+ lines of TOML config and comment.  This is a lot of text to understand, search, and edit compared to the configuration of other tools.  Can we create a far less chatty version `pylint --generate-toml-config` that strips all settings that match the pylint default and all nonessential comments.

### Desired solution

A _default value trimmer_ could be used to slim down existing TOML configurations and/or be run as a post-process to `pylint --generate-toml-config`.

### Additional context

PyCQA/astroid#1793

**Comment by DanielNoord** [comment]
This will be available with https://github.com/PyCQA/pylint/pull/7489

It can be invoked with ``pylint-config generate --interactive``.
To take a previous `rcfile` into account use ``pylint-config --rcfile=MYFILE generate --interactive``

**Comment by cclauss** [comment]
Can we please reopen this issue?

I did `pylint-config --rcfile=pylintrc generate --interactive .` in the `astroid` repo and selected `t` and then `my_file.toml`.  The result was a 551-line file which is clearly not what this issue was targeting.  The file was chock full of comments and default values and ended with three blank lines which will trigger other pre-commit tools like `end-of-file-fixer`.

**Comment by DanielNoord** [comment]
Did you use the version on the `main` branch? The PR that fixed this was not back ported to the just released version as it contained a new feature. We only put fixes in the patch releases to guard against potential new regressions in new features.
