### ISSUE TITLE
Should not report unneeded-not inside __ne__ implementation

### ISSUE THREAD

**Issue by nbastin** [PyCQA/pylint#749]
You cannot implement `__ne__` using `!=`, but pylint suggests that you should:

    C: 39,11: Consider changing "not self == other" to "self != other" (unneeded-not)

For the code:

    def __ne__ (self, other):
      return not self == other

**Comment by PCManticore** [comment]
Closed by ac80c33d5a23d78c37eba0585dce19b864eb14f5
