### ISSUE TITLE
Check for raise Exception or BaseException

### ISSUE THREAD

**Issue by avylove** [PyCQA/pylint#7494]
### Current problem

Linting a codebase with a lot of `raise Exception()` statements. This is a bad practice as it makes it impossible to write narrow exception clauses.

### Desired solution

Forgive me if I missed it, but as far as I can tell, a check doesn't currently exist. The check should fail when an instance of `Exception` or `BaseException` is raised directly.

**Comment by Pierre-Sassoulas** [comment]
That would be [``broad-except``](https://pylint.pycqa.org/en/latest/user_guide/messages/warning/broad-except.html), can you try to enable it ?

**Comment by avylove** [comment]
Isn't `broad-except` on the catch side, not the raise side?

**Comment by Pierre-Sassoulas** [comment]
Ha, right !

**Comment by clavedeluna** [comment]
What should the linter name be here, `broad-raise`?

**Comment by Pierre-Sassoulas** [comment]
I'm thinking that we could rename broad-except to broad-exception-caught and name this one broad-exception-raised. We need to use 'old-names' for that.

**Comment by clavedeluna** [comment]
> 'old-names' for that.

That's a way to handle backward compat, right? Or since this is a breaking change would this only be released in pylint 3.x? Trying to understand where to put this PR to

**Comment by Pierre-Sassoulas** [comment]
Yes, old names handle the backward compatibility so that it's not a breaking change. See C0111 /missing-docstring for example.

**Comment by clavedeluna** [comment]
> See C0111 /missing-docstring for example.

Just curious since I've used this msg as an example. Should code using `module-docstrong` such as `@utils.only_required_for_messages("missing-docstring", "empty-docstring")` be updated at some point to use the new name(s)? That way the old name only ever appears in `old_name`. As it stands right now the code / tests are confusing.

**Comment by Pierre-Sassoulas** [comment]
We could replace it by the three new names yes (not in tests because sometime we're testing that the old_names work for multiple new name with this message).
