### ISSUE TITLE
fales positive: unnecessary-dunder-call (__aiter__, __anext__)

### ISSUE THREAD

**Issue by belm0** [PyCQA/pylint#7529]
### Bug description

As of recent pylint versions, I'm seeing the errors below, even though it's suggesting the wrong builtin (`iter()` rather than `aiter()`), and even though I'm on Python 3.8 (which doesn't have `aiter()` and `anext()` builtins).

### Command used

```shell
pylint
```

### Pylint output

```shell
C2801: Unnecessarily calls dunder method __aiter__. Use iter built-in function. (unnecessary-dunder-call)
C2801: Unnecessarily calls dunder method __anext__. Use next built-in function. (unnecessary-dunder-call)
```

### Expected behavior

no errors

### Pylint version

```shell
pylint 2.15.3
astroid 2.12.10
Python 3.8.12 (default, Sep 23 2021, 08:42:37)
[Clang 12.0.0 (clang-1200.0.32.29)]
```

**Comment by DanielNoord** [comment]
@jpy-git Do you happen to know anything about this? Or would you want to take a look at this?

**Comment by belm0** [comment]
1. fix entries in `DUNDER_METHODS`.  "Use {iter,next}" --> "Use {aiter,anext}"

https://github.com/PyCQA/pylint/blob/ec85e2988679a28dbe11f46d60056b4dd569c44b/pylint/checkers/dunder_methods.py#L108-L109

2. this checker needs to have awareness of the Python version.  The brute force for this case would be to declare the set of builtins requiring >= 3.10, and add it to the checker condition.

```python
NEEDS_PYTHON_3_10 = {'__aiter__', '__anext__'}
```

**Comment by DanielNoord** [comment]
> 1. fix entries in `DUNDER_METHODS`.  "Use {iter,next}" --> "Use {aiter,anext}"
> 
> https://github.com/PyCQA/pylint/blob/ec85e2988679a28dbe11f46d60056b4dd569c44b/pylint/checkers/dunder_methods.py#L108-L109
> 

This is an easy fix. Would you want to open a PR for this? You've done all the work already!

> 2. this checker needs to have awareness of the Python version.  The brute force for this case would be to declare the set of builtins requiring >= 3.10, and add it to the checker condition.
> 
> ```python
> NEEDS_PYTHON_3_10 = {'__aiter__', '__anext__'}
> ```
> 
> (If there is no time to do this for the next release, at least disable these entries in `DUNDER_METHODS`.)

I'm not sure I understand this. If you're using `__aiter__` then `aiter()` is available as well right?

**Comment by belm0** [comment]
> I'm not sure I understand this. If you're using `__aiter__` then `aiter()` is available as well right?

No-- this is the misunderstanding of this checker.    `__aiter__` / `__anext__` came with async iterators in Python 3.5.  `aiter()` / `anext()` convenience builtins were added in Python 3.10.

**Comment by belm0** [comment]
some reasons to consider dropping `__aiter__` / `__anext__` from the table for now:
  1. the current pylint guidance is possible harmful (suggesting the wrong, non-async builtins)
  2. even if (1) is corrected, since the builtins were only introduced in a recent Python version, often following the pylint guidance will not be the right thing to do.  For example, if the `__aiter__` reference is in a library that's trying to be compatible with older, but not yet EOL Python versions.
  3. (I could contribute the change, but it's probably 1-2 hrs for me to work out, included proper tests-- not sure when I could get to it)

**Comment by DanielNoord** [comment]
I'll work on a fix today which uses `py-version`, that option allows you to specify which Python version you support.
