### ISSUE TITLE
Redefined variable type when using json.load

### ISSUE THREAD

**Issue by nbastin** [PyCQA/pylint#753]
The following code triggers `redefined-variable-type`:

```
import json

class Ham(object):
    def problem(self):
        self.f = {}
        self.f = json.load(open("foo.txt"))
        return self.f
```

More specifically it complains that `self.f` is being redefined to `bool`:

```
R:  6, 8: Redefinition of self.f type from dict to bool (redefined-variable-type)
```

**Comment by PCManticore** [comment]
Closing this. Feel free to ignore this error, it has been demoted to an extension in the next release, being disabled by default. It has a lot of rough edges and does not perform well, and probably will never be performing well enough.
