### ISSUE TITLE
pre-commit mypy crashes on Windows  for missing imports and typing objects

### ISSUE THREAD

**Issue by orSolocate** [PyCQA/pylint#7530]
### Bug description

When running `pre-commit` mypy complains about unrelated changes:

```
mypy.....................................................................Failed
- hook id: mypy
- exit code: 1

pylint\reporters\text.py:285: error: Cannot find implementation or library stub for module named "colorama"  [import]
pylint\reporters\text.py:285: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
pylint\config\configuration_mixin.py:31: error: "list" is not subscriptable, use "typing.List" instead  [misc]
pylint\config\configuration_mixin.py:31: error: "tuple" is not subscriptable, use "typing.Tuple" instead  [misc]
Found 3 errors in 2 files (checked 2 source files)
```

might be related to a previous bug #5627, I saw that the solution fetched there does not exist anymore in `setup.cfg`

any idea how to fix it?

### Command used

```shell
pre-commit when there are staged `.py`  files
```

### Pylint output

```shell
N/A
```

### Expected behavior

Should pass.

### Pylint version

```shell
pylint 2.16.0-dev
astroid 2.12.10
Python 3.8.10
```

### OS / Environment

Windows 10 Pro 64 Bit

**Comment by Pierre-Sassoulas** [comment]
Thank you for opening the issue. Could you try adding colorama here https://github.com/PyCQA/pylint/blob/main/pyproject.toml#L119 ? I don't think they have stubs (we only need this on windows and only tests this on linux).

**Comment by DanielNoord** [comment]
`colorama` is my bad. I recently used a flag `mypy` has to remove unnecessary config flags. It showed up as unnecessary as I was on Mac. We should re-add it and add a comment about it's necessity on windows.

The crash is unexpected. Are you sure you are on `main`? Is there a `import __future__` statement?

**Comment by orSolocate** [comment]
@DanielNoord @Pierre-Sassoulas  - I managed to fix all errors now thanks to your help. it happened on `main` too btw.
the `import __future__` statement did fix the second error for `mypy`.
Could you please verify and approve the PR?
