### ISSUE TITLE
Why my pylint checks are not successful?

### ISSUE THREAD

**Issue by itttgg** [PyCQA/pylint#7536]
### Question

I have a project that is using pylint workflow, but my checks are not successful. Why? Please fix it.

### Documentation for future user

Please fix bug with failing checks in workflows

### Additional context

Python version: 3.8.14
PyLint version: 2.15.3
Astroid verrsion: 2.12.10

Additional info: https://github.com/itttgg/dispy/actions/runs/3138242747/jobs/5097358205

**Comment by Pierre-Sassoulas** [comment]
Duplicate of https://github.com/PyCQA/pylint/issues/7438 :)

**Comment by itttgg** [comment]
> Duplicate of #7438 :)

No. I'm talking about github workflows failing. Your issue is not about it. Sorry, i don't understand you

**Comment by Pierre-Sassoulas** [comment]
We're not going to fix your code for you. There's an issue so pylint can fix code automatically which is the closest thing to what you're asking for.

**Comment by itttgg** [comment]
Ok, i

> We're not going to fix your code for you. There's an issue so pylint can fix code automatically which is the closest thing to what you're asking for.

Ok, i have fixed my error
