### ISSUE TITLE
pylint instructions error

### ISSUE THREAD

**Issue by vgren** [PyCQA/pylint#7540]
### Question

upon running pylint we got following error:

[ERROR] program.py contained more than one line of pylint instructions. Please reduce it to one.

however pylint exited with code 0:

[INFO] Exiting with code: 0

can not find anywhere how we can configure pylint in such way that it will exit with exit code 1  for this error

### Documentation for future user

can you please provide way to configure pylint in such a way that it will exit with code 1 on mentioned error

**Comment by Pierre-Sassoulas** [comment]
It look like you're reporting a bug, but without following the template for a bug so we can't reproduce easily your problem. Would you mind adding the missing information (command used, output, expected behavior, pylint version), please ?
