### ISSUE TITLE
Update Contributor guide to include pre-commit

### ISSUE THREAD

**Issue by clavedeluna** [PyCQA/pylint#7542]
### Current problem

As I start contributing more and more to pylint, I'd like to get my development process to be faster and more streamlined. It took me a while to realize that pre-commit is running in CI and that takes time and resources. 

### Desired solution

I suggest updating [this section](https://pylint.pycqa.org/en/latest/development_guide/contributor_guide/contribute.html#tips-for-getting-started-with-pylint-development) or [this section](https://pylint.pycqa.org/en/latest/development_guide/contributor_guide/tests/install.html) to mention the [pre-commit](https://pre-commit.com/) installation guide.

**Comment by Pierre-Sassoulas** [comment]
The second links you gave mention pre-commit (https://pylint.pycqa.org/en/latest/development_guide/contributor_guide/tests/install.html#basic-installation). But feel free to make the change you feel are necessary so it's easier to notice :)
