### ISSUE TITLE
Suggest >2 arguments for min/max functions

### ISSUE THREAD

**Issue by bje-** [PyCQA/pylint#7546]
### Current problem

Some Python users may be unaware that the `min` and `max` functions allow for more than two arguments.

### Desired solution

Expressions of the form: `min(a, min(b, min(c, d))` can be replaced with the simpler `x = min(a, b, c, d)`.

**Comment by osherdp** [comment]
Should be simple enough. I'll take a look

**Comment by DanielNoord** [comment]
@Pierre-Sassoulas You gave this an `Optional Checker`, but shouldn't this be part of `RefactoringChecker`?

**Comment by Pierre-Sassoulas** [comment]
I thought about an extension at first but yeah why not.

I think this is a discussion we already had at some point, ideally I would want to have checker handling less messages and be more decoupled. If this is in an independent file it means less work if we change our mind (i.e. we don't have to copy paste code from the RefactoringChecker we can switch a boolean somewhere).
