### ISSUE TITLE
Bad link for Pycharm integration in the docs

### ISSUE THREAD

**Issue by arusahni** [PyCQA/pylint#755]
[The documentation](http://docs.pylint.org/ide-integration) provides a link for PyCharm integration that no longer works ( http://blog.saturnlaboratories.co.za/archive/2012/09/10/running-pylint-pycharm ) - instead my session gets hijacked by an ad service.

**Comment by PCManticore** [comment]
Care to provide a patch? I don't use pycharm and I don't know what is the sanctioned way for doing the integration with pycharm.

**Comment by PCManticore** [comment]
Care to provide a patch? I don't use pycharm and I don't know what is the sanctioned way for doing the integration with pycharm.

**Comment by arusahni** [comment]
Neither do I, but I'll try to whip something together.
