### ISSUE TITLE
Check for imports only needed for type annotations

### ISSUE THREAD

**Issue by finswimmer** [PyCQA/pylint#7583]
### Current problem

Imports, that are only needed for type annotations, should be placed into a `if TYPE_CHECKING` block. This avoids circular imports during runtime and unnecessary loading of modules.

### Desired solution

It would be great if `pylint` would detect imports, which should be placed in the `if TYPE_CHECKING` block. Unless [PEP 563](https://peps.python.org/pep-0563/) is used, it must also detect, that imports placed in this block, must be quoted wherever they are used.

It should also detect the other way round: Imports that are used for more than type annotations, but are place in the `if TYPE_CHECKING` block, are not valid.

### Additional context

This is inspired by the `flake8` plugin [flake8-type-checking](https://pypi.org/project/flake8-type-checking/).

**Comment by cdce8p** [comment]
It could be possible to write a check for it. However, I'm not sure we should do that. What value could `pylint` provide here that isn't already covered by the `flake8` plugin? It would just add additional maintenance load.

**Comment by Pierre-Sassoulas** [comment]
Closing for the same reason than https://github.com/PyCQA/pylint/issues/7584
