### ISSUE TITLE
TypeError in enchant Broker

### ISSUE THREAD

**Issue by exploide** [PyCQA/pylint#759]
As a follow up to https://github.com/AtomLinter/linter-pylint/issues/106 I want to report this bug here.

When running pylint on my scripts, sometimes the following exception occurs. This is not repeatable (linting the same file immediately again) but happens in enough cases that it is annoying.

```
Exception ignored in: <bound method Broker.__del__ of <enchant.Broker object at 0x7f2658388940>>
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/enchant/__init__.py", line 244, in __del__
  File "/usr/lib/python3.4/site-packages/enchant/__init__.py", line 273, in _free
TypeError: 'NoneType' object is not callable
```
```
$ pylint --version
pylint 1.5.2, 
astroid 1.4.2
Python 3.4.3 (default, Jun 29 2015, 12:16:01) 
[GCC 5.1.1 20150618 (Red Hat 5.1.1-4)]
```
python3-enchant: 1.6.6

Let me know if I should provide more information.

**Comment by PCManticore** [comment]
This seems to be an enchant-related issue, which was fixed in https://github.com/rfk/pyenchant/pull/56. Probably a newer version of enchant wasn't released though.
