### ISSUE TITLE
`no-name-in-module` issued depending on type of exception caught

### ISSUE THREAD

**Issue by bersbersbers** [PyCQA/pylint#7633]
### Bug description

```python
"""Bug"""
try:
    from matplotlib.cm import jet
except BaseException:
    pass

print(jet)
```

Interestingly, the issue is not seen here:

```python
"""No bug"""
try:
    from matplotlib.cm import jet
except ModuleNotFoundError:
    pass

print(jet)
```

### Command used

```shell
pylint bug.py
```

### Pylint output

```shell
************* Module project.bug
project\bug.py:4:7: W0703: Catching too general exception BaseException (broad-except)
project\bug.py:3:4: E0611: No name 'jet' in module 'matplotlib.cm' (no-name-in-module)
```

### Expected behavior

No E0611 message.

### Pylint version

```shell
pylint 2.15.4
astroid 2.12.11
Python 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]
```

### OS / Environment

Windows 10

### Additional dependencies

matplotlib==3.6.1

**Comment by Pierre-Sassoulas** [comment]
Seems like it's working as intended, we don't want to raise a message if an import is in a try catch telling us that the user know that the import might fail with ``ModuleNotFoundError`` or ``ImportError``. Those exceptions means that at least in some environment it's expected that the import will fail.

**Comment by bersbersbers** [comment]
Seems like `pylint` is smarter than I had expected ;)

I think my main misunderstanding was that `BaseException` is not raising anything incorrectly - by contrast, the import statement itself raises an error (due to `matplotlib` internals, I guess) that (only) `ModuleNotFoundError` (correctly) hides.

I'll close this, thanks!
