### ISSUE TITLE
Conditional MESSAGES CONTROL

### ISSUE THREAD

**Issue by marrak** [PyCQA/pylint#7657]
### Question

I have two Pylint (2.13.9 on Py 3.6.8 and 2.15.4 on Py 3.10) and one .pylintrc rcfile.
Py 3.6.8 is system RedHat 8 Python, which prevents update of Pylint to latest version.

If I have disable=no-self-use, there is issue R0022: Useless option value for '--disable', 'no-self-use' was moved to an optional extension (useless-option-value) on 2.15.4
If I add load-plugins=pylint.extensions.no_self_use, there is issue E0013: Plugin 'pylint.extensions.no_self_use' is impossible to load, is it installed ? ('No module named 'pylint.extensions.no_self_use'') (bad-plugin-value) on 2.13.9

I do not want to add neither useless-option-value nor bad-plugin-value to disabled.
Is there any possibility to disable it conditionally per py version or pylint version?
Or any other, better solution to fix it and use one rcfile and different Pylint versions?

Thank you.

### Documentation for future user

Q/A

**Comment by Pierre-Sassoulas** [comment]
You could reasonably lint only on python 3.10 / pylint 2.15.4 with the ``py-version`` option set to ``3.6``. Imo the easier fix for you is to disable both ``no-self-use`` and ``useless-option-value``. (``useless-option-value`` will probably not warn you of anything else than no-self-use as long as you don't add new bad config in your pylintrc).
