### ISSUE TITLE
wrong-import-error false positives

### ISSUE THREAD

**Issue by belak** [PyCQA/pylint#768]
I've been messing with a library recently, so I installed it via `python setup.py develop` however pylint seems to think this is a local library as it is complaining about:

`C:  4, 0: external import "import requests" comes before "from PyIRC.extensions import BaseExtension" (wrong-import-order)`

When I install PyIRC using `pip install -e git+https://code.foxkit.us/IRC/PyIRC.git`, these errors go away.

**Comment by brbsix** [comment]
I think I've encountered a related issue. For example, consider the following sample script:

    # pylint:disable=missing-docstring,unused-import
    import requests
    import urllib3

Both requests and urllib3 are external imports, yet it barks out:

`C:  3, 0: external import "import urllib3" comes before "import requests" (wrong-import-order)`.

`isort` knows it's ordered correctly, but for some reason pylint does not.

**Comment by PCManticore** [comment]
This should be fixed by https://github.com/PyCQA/pylint/commit/9812c5a49ae430945e9ad5dde7ec523904498805, where we switched to using isort internally.
