### ISSUE TITLE
Colored output displays incorrectly in PowerShell

### ISSUE THREAD

**Issue by PrahlM93** [PyCQA/pylint#770]
Hello,
When running pylint 1.4.4 in PowerShell, the colored output at the beginning shows strange characters as shown here:
```
[1;31mE[0m: 52, 8: [1;31mNo value for argument 'message' in function call[0m ([1;31mno-value-for-parameter[0m)
[1;31mE[0m: 83, 8: [1;31mNo value for argument 'message' in function call[0m ([1;31mno-value-for-parameter[0m)
[1;31mE[0m:115, 8: [1;31mNo value for argument 'message' in function call[0m ([1;31mno-value-for-parameter[0m)
```

Running the same pylint check in a command-prompt window displays the colored output properly.

Thank you for looking into this.

**Comment by PCManticore** [comment]
Could you try with 1.5.2? There were some improvements to the colorized output in 1.5.0.

**Comment by PrahlM93** [comment]
@PCManticore Yes the latest pylint works. Thank you!
