### ISSUE TITLE
incorrect report of bad-super-call in except handler

### ISSUE THREAD

**Issue by smoser** [PyCQA/pylint#773]
Given 'my.py' below, both python 2 and python3 pylint complain about bad-super-call.  The reason for the try/except is to define TimeoutExpired in python2.

    #!/usr/bin/python
    import subprocess
    try:        
        TimeoutExpired = subprocess.TimeoutExpired
    except AttributeError:
        class TimeoutExpired(subprocess.CalledProcessError):
            def __init__(self, *args, **kwargs):
                returncode = -1
                self.timeout = -1
                if 'timeout' in kwargs:
                    self.timeout = kwargs.pop('timeout')
            
            #subprocess.CalledProcessError.__init__(self, returncode, **kwargs)
            super(TimeoutExpired, self).__init__(returncode, **kwargs)

$ python3 -m pylint --errors-only  my.py
 No config file found, using default configuration
 ************* Module my
 E: 15,12: Bad first argument 'TimeoutExpired' given to super() (bad-super-call)
        
            
$ python2 -m pylint --errors-only  my.py   
No config file found, using default configuration
************* Module my
E: 15,12: Bad first argument 'TimeoutExpired' given to super() (bad-super-call)

**Comment by PCManticore** [comment]
This should be fixed in astroid by https://github.com/PyCQA/astroid/commit/b2ece4f4d0e32cdc4791ccb7e7ba6758ac615491. Thanks for the report!
