### ISSUE TITLE
View code coverage in CI

### ISSUE THREAD

**Issue by nickdrozd** [PyCQA/pylint#7848]
Is there a way to look at the code coverage in CI? I mean a page that shows the code itself with lines marked as covered / not covered. When I click through Coveralls, it ends up saying SOURCE NOT AVAILABLE. I have no idea if this is a config issue, or permissions, or what.

I would run it locally, but my laptop is crappy and slow :black_cat:

**Comment by DanielNoord** [comment]
You need to (sadly) log in to Coveralls for the source coverage to work. They can't make unlimited requests to Github so they need access to your user account to make requests through it to get the source.

**Comment by nickdrozd** [comment]
After switching to Codecov, this is now possible!
