### ISSUE TITLE
Diff-mode/line filter

### ISSUE THREAD

**Issue by xmo-odoo** [PyCQA/pylint#785]
For older codebases piecemeal update can be a better idea (if only for political reasons) than trying to update the whole codebase to new standards at once: new changes must fit the standard, but old code doesn't have to be updated until it's touched for other reasons.

Some analysis tools have a diff/patch filter: when given a diff/patch file, they'll only display messages for the LOCs affected by the patch, that's convenient for CI/pull requests as it only displays issues related to the specific change, rather than all of the codebase's.

Of course it's possible to perform this filtering by hand (especially with custom message templates), but it would still be convenient and make pylint easier to use/integrate in this context.

**Comment by rneu31** [comment]
I have a custom solution that does something similar to this that I would love to get rid of. I made the decision to enforce errors function-by-function. So if you make a change to a line in the function/method you inherit all pylint errors for that function.

**Comment by xmo-odoo** [comment]
@PCManticore @The-Compiler I can probably work on this, but I don't know the codebase so I'm not sure how (where) to do it. My initial idea would be to add a `--diff-filter (-|path)` option to `PyLinter` and override `is_message_enabled` there so that if a diff filter was provided there's a pre-check against `self.current_file` and the `line` parameter.

Now after looking a bit in there (to monkey-patch this feature in locally) `current_file` can be `None`, I don't know in which situations exactly, I just let the message through in that case but maybe it should be filtered instead? (assuming diff-filter was enabled)

**Comment by PCManticore** [comment]
Hey @xmo-odoo I have no idea right now to be honest. Let me think about it and I'll be back tonight with some ideas we could use. You can also find us on IRC ``#pylint`` as well.

**Comment by PCManticore** [comment]
I'm closing this. I don't think this solution belongs in pylint per se and we'll probably not have enough bandwidth / energy for implementing it.
