### ISSUE TITLE
Suggest explicitly relative import instead of absolute imports

### ISSUE THREAD

**Issue by xmo-odoo** [PyCQA/pylint#787]
Currently, given

```
foo
|-- __init__.py
`-- bar
    |-- __init__.py
    `-- baz.py
```

Upon encountering an implicit relative `import baz` (in `foo/bar/__init__.py`) pylint will recommend replacing it with an absolute `import foo.bar.baz`.

It would be nice if:
- pylint could be configured to recommend an explicit relative `from . import baz` instead
- pylint could also be configured to recommend explicit relative imports for intra-package absolute imports e.g. suggest that `import foo.bar.baz` be replaced by `from . import baz` in this case

**Comment by PCManticore** [comment]
This could be useful probably in some projects, so I don't mind having it, as long at it is controlled by a new flag which will control the behavior of the checker. It might also need someone to write the code.

**Comment by PCManticore** [comment]
Closing as not sure if this is a big of a problem right now. It could be okay to have it, but unless someone volunteers a patch, I doubt it's going to happen.
