### ISSUE TITLE
Crash when disabling some messages

### ISSUE THREAD

**Issue by sthenault** [PyCQA/pylint#789]
`pylint --disable=all --enable=bare-except,deprecated-pragma,eval-used,not-callable,no-self-argument,function-redefined,redefined-builtin  project`

  Traceback (most recent call last):
  ...
  File "/home/syt/.local/lib/python2.7/site-packages/pylint/checkers/classes.py", line 590, in visit_attribute
    self._accessed[-1][attrname].append(node)
 IndexError: list index out of range

The error disappears when we run with all messages enabled.

**Comment by PCManticore** [comment]
Fixed already.

**Comment by porridge** [comment]
We get this with 1.5.4, is it fixed after that release? Do you intend to roll a new release anytime soon?

**Comment by PCManticore** [comment]
It seems that this didn't get released, thanks for bringing it up. We'll roll out a new bug fix release shortly, in the following days (there is another crashing fix in astroid which needs to be released as well).

**Comment by PCManticore** [comment]
I just released 1.5.5, which should have this fix. Sorry for the excruciating delay!
