### ISSUE TITLE
PyLint resolves realpath when adding a root to sys.path but not when converting files to modules

### ISSUE THREAD

**Issue by xmo-odoo** [PyCQA/pylint#791]
When invoking `pylint {item}`, PyLint will forcefully add the lint targets to the `sys.path`, after canonicalising them through `pylint.lint._get_python_path` whose important feature is to call `os.path.realpath(os.path.expanduser())` in the path. **This is only done on the sys.path addition, not on the original parameter**.

When converting matched python files to python modules, PyLint calls `astroid.modutils.modpath_from_file()` which only performs `os.path.abspath` on the filename before trying to find if the target is within any `sys.path` (or `extrapath`) subtree.

On OSX, `/tmp` is a symlink to `/private/tmp`, targeting a subtree of `/tmp` with pylint blows up this process as `/private/tmp/{subtree}` is added to the sys.path, after which pylint tries to find matches for `/tmp/{subtree}/file`.

Demonstration (on a clone of pypa/pip):
```
> pylint /tmp/pip/pip                                                                                                                                                                                         ~
No config file found, using default configuration
Traceback (most recent call last):
  File "bin/pylint", line 11, in <module>
    sys.exit(run_pylint())
  File "lib/python2.7/site-packages/pylint/__init__.py", line 23, in run_pylint
    Run(sys.argv[1:])
  File "lib/python2.7/site-packages/pylint/lint.py", line 1313, in __init__
    linter.check(args)
  File "lib/python2.7/site-packages/pylint/lint.py", line 734, in check
    self._do_check(files_or_modules)
  File "lib/python2.7/site-packages/pylint/lint.py", line 845, in _do_check
    for descr in self.expand_files(files_or_modules):
  File "lib/python2.7/site-packages/pylint/lint.py", line 878, in expand_files
    result, errors = utils.expand_modules(modules, self.config.black_list)
  File "/Users/masklinn/projects/tiny/odoo/lib/python2.7/site-packages/pylint/utils.py", line 844, in expand_modules
    submodname = '.'.join(modpath_from_file(subfilepath))
  File "lib/python2.7/site-packages/astroid/modutils.py", line 320, in modpath_from_file
    filename, ', \n'.join(sys.path)))
ImportError: Unable to find module for /tmp/pip/pip/__main__.py in /private/tmp/pip, 
bin, 
lib/python27.zip, 
lib/python2.7, 
lib/python2.7/plat-darwin, 
lib/python2.7/plat-mac, 
lib/python2.7/plat-mac/lib-scriptpackages, 
Extras/lib/python, 
lib/python2.7/lib-tk, 
lib/python2.7/lib-old, 
lib/python2.7/lib-dynload, 
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7, 
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin, 
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk, 
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac, 
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages, 
lib/python2.7/site-packages, 
lib/python2.7/site-packages/astroid/brain
```

This seems like it could be solved by:
* not canonicalising sys.path
* canonicalising the `args` list itself, not just the bits injected into `sys.path`
* canonicalising filenames in astroid

**Comment by PCManticore** [comment]
Sorry for the delay in tackling this issue, as well as providing a relevant answer in a timely manner.

It should be fixed now, the fix being included in astroid. I actually did not understand the second suggestion of canonicalising the args list itself, not just the bits injected into sys.path.

**Comment by moylop260** [comment]
FYI Now I have the following error https://github.com/PyCQA/astroid/issues/338

**Comment by smurfix** [comment]
In case anybody who is/was affected by this issue still follows this: could you test whether
https://github.com/pylint-dev/astroid/pull/2128
reverts this bugfix? Because if it does we'd need to fix either this or that issue in some other way.

**Comment by smurfix** [comment]
Ugh. Thanks. I'll have to think of some other way to fix that then. (Why does pylint resolve symlinks when adding something to `sys.path` anyway? CPython doesn't do that either, so …)
