### ISSUE TITLE
[MISCELLANEOUS] code tag without message doesn't track

### ISSUE THREAD

**Issue by glegoux** [PyCQA/pylint#793]
You have this configuration by default :  

~~~
...

[MISCELLANEOUS]

# List of note tags to take in consideration, separated by a comma.
notes=FIXME,XXX,TODO

...
~~~

When a code tag (TODO, FIXME, XXX) has not a message, pylint doesn't display the warning.

For example, I use only the code tag `TODO` with the option `--notes` : 

*file : issue_code_tags.py*
~~~python
# Run: pylint issue_code_tags.py --reports=no --notes=TODO

# TODO message
# OK...

# TODO
# KO...

# Show:
# No config file found, using default configuration
# ************* Module issue_code_tags
# W:  3, 0: TODO message (fixme)

# Expected:
# No config file found, using default configuration
# ************* Module issue_code_tags
# W:  3, 0: TODO message (fixme)
# W:  6, 0: TODO (fixme)
~~~

**Note** : It's ok for `TODO:` with at least one character at the end (here `:`).

**Version**
pylint 1.5.4, 
astroid 1.4.4
Python 3.4.3 (default, Oct 14 2015, 20:28:29) 
[GCC 4.8.4]
Ubuntu 14.04.3 LTS

**Comment by PCManticore** [comment]
Probably there's a problem with the regular expression from here https://github.com/PyCQA/pylint/blob/master/pylint/checkers/misc.py#L88. If you'd like to contribute a patch, I'd be happy to review it. Otherwise it's going to take a bit until I can fix it.

**Comment by glegoux** [comment]
Thanks, I try to patch that.

**Comment by glegoux** [comment]
Done !
