### ISSUE TITLE
HTML output dumps to a single file.

### ISSUE THREAD

**Issue by ptthiem** [PyCQA/pylint#796]
I was able to do this with:

* pylint 1.5.4
* installed into a virtual env
* default config in an rcfile except for:
  * output-format = html
  * files-output = yes

All modules produce an HTML skeleton, but it would seem that all of them except the summary and one other are empty (no rows).  Looking at the other one reveals that the messages from all the other modules are being dumped into that one file.

**Comment by ptthiem** [comment]
I bisected the issue to: 38d68ea1746b9b50be26acd83d997b8b663409e1.  It looks like HTMLReporter.set_output function is calling _display (which had been repurposed).  Change set_output to call dispaly_messages instead restores the previous behavior, but puts all the cells on a single row.  

Regarding that, It seems that self.header is getting constantly appended: msgs = self.header followed by an inplace append (msgs += ...). Explicitly copying self.header as a list in the _display (msgs = list(self.header)) then fixes that issue.

**Comment by PCManticore** [comment]
Thanks for reporting this and sorry for the long delay! I'll try to do better at responding issues from now on.

I tested this with 1.5.3 and it seems it didn't even actually work properly (so files-output=yes and -fhtml results in almost empty files). On 1.5.0 the situation is different as well, with only one file having the actual content corresponding to itself, while the other one is empty, without the HTML skeleton.

**Comment by PCManticore** [comment]
Closing this, since we removed support for HTML reporting in Pylint 2.0. I think we now have a better reporting through the JSON reporter, which can be used as a basis for prettier HTMLs, made by external tools. Also, it was always a second class citizen, having a couple of bugs such as this one and others, and the UI was too bare to be worth keeping it.
