### ISSUE TITLE
Nested lambdas lead to undefined-variable messages

### ISSUE THREAD

**Issue by dbaum** [PyCQA/pylint#798]
This code:

get = lambda x: lambda y: getattr(x, y)

Results in this warning:

Undefined variable 'x' (undefined-variable)

But there should be no warning since x is defined by the outer lambda.

**Comment by dbaum** [comment]
nevermind - duplicate of https://github.com/PyCQA/pylint/issues/760

**Comment by PCManticore** [comment]
Yup, that's a duplicate.
