### ISSUE TITLE
import-outside-toplevel to ignore `if TYPE_CHECKING` block

### ISSUE THREAD

**Issue by SimonSchick** [PyCQA/pylint#8087]
### Current problem

Many typings are 'virtual' and cannot be imported property at runtime (such as the case with many 3rd party stubs).

### Desired solution

Imo this check should not trigger when explicitly checking for `if TYPE_CHECKING` imported from the `typings` module.

**Comment by DanielNoord** [comment]
This is really more about style, but the `TYPE_CHECKING` allows you put the import at the top of the file.

**Comment by SimonSchick** [comment]
Actually I think I filed this ticket in error, after a fresh install/update it is no longer flagging these imports.
