### ISSUE TITLE
Thought on Mapping + dangerous-default-value

### ISSUE THREAD

**Issue by jamesbraza** [PyCQA/pylint#8090]
### Current problem

Here is a code snippet:

```python
from collections.abc import Mapping

# pylint: disable-next=unused-argument
def function(arg: Mapping[str, int] = {"foo": 1}) -> None:
    """Does something."""
```

Currently, `pylint==2.15.10` will throw `W0102: Dangerous default value {} as argument (dangerous-default-value)`, which makes sense... the default argument is mutable.

However, upon closer inspection, we see the type hint is `Mapping`, which [does not implement `__setitem__`](https://github.com/python/typeshed/blob/ddfaca3200144415de1f338bcce5cc5f2c71f621/stdlib/typing.pyi#L578) so it's not mutable.

### Desired solution

So we have:
- Mutable default argument
- Typing that the argument is not mutable

Do you think `pylint` should throw `dangerous-default-value` in this case or not?

### Additional context

```bash
> pylint --version
pylint 2.15.10
astroid 2.13.2
Python 3.10.9 (main, Jan  6 2023, 11:19:20) [Clang 14.0.0 (clang-1400.0.29.102)]
```

**Comment by jamesbraza** [comment]
Okay thinking about this further, imagine the case when the `arg` gets returned:

```python
from collections.abc import Mapping

# pylint: disable-next=unused-argument
def function(arg: Mapping[str, int] = {"foo": 1}) -> Mapping[str, int]:
    return arg

output = function()
assert output == {"foo": 1}, "Default is not in tact."

output["bar"] = 2
assert function() == {"foo": 1}, "Default is not in tact."
```

The last assertion will fail, so `pylint` should actually throw `dangerous-default-value` here.

Perhaps `pylint` could check if the `arg` is being returned, and if not, then maybe not throw `dangerous-default-value`.

However, there are sneaky ways the default could be returned or manipulated (e.g. via a closure) without an explicit return.

```python
from collections.abc import Mapping

data_structure = []

# pylint: disable-next=unused-argument
def function(arg: Mapping[str, int] = {"foo": 1}) -> None:
    data_structure.append(arg)

function()
assert data_structure[-1] == {"foo": 1}, "Default is not in tact."

data_structure[-1]["bar"] = 1
function()
assert data_structure[-1] == {"foo": 1}, "Default is not in tact."
```

Thus, I think `pylint` should actually throw `dangerous-default-value` here.  Closing this out, and cheers!

**Comment by Pierre-Sassoulas** [comment]
I don't think the typing with mapping matter here, the default arg is a mutable dictionnary. Consider the following:
```python
from collections.abc import Mapping



# pylint: disable-next=unused-argument

def function(arg: Mapping[str, list[int]] = {"foo": []}) -> Mapping[str, int]:

    arg["foo"].append(1)

    print(arg)

    return arg



function()

function()

function()



function()



function()





(venv)  pierre@pylint  ~/pylint  ↱ main ±✚  python a.py

{'foo': [1]}

{'foo': [1, 1]}

{'foo': [1, 1, 1]}

{'foo': [1, 1, 1, 1]}

{'foo': [1, 1, 1, 1, 1]}

```

**Comment by jamesbraza** [comment]
Agreed, thanks for the comment!

**Comment by randolf-scholz** [comment]
I disagree with the comments here. In both code examples, `mypy` raises errors when the mutation occurs. The whole point of allowing a mutable default when the type hint indicates immutability is that the type checker will catch the bug instead of the linter, and we are blessed with less boilerplate code. (getting rid of `arg = { if arg is None else arg}`)

Also, immutable python objects can be mutated anyway: https://github.com/ionite34/einspect/

I would advocate for the following behavior, possibly one could enable it via a config flag.

```python
from collections.abc import *

def foo(
    configA: Mapping[str, Any] = {},         # needn't raise dangerous-default-value
    configB: MutableMapping[str, Any] = {},  # should raise dangerous-default-value
    configC: dict[str, Any] = {},            # should raise dangerous-default-value
    seqA: Sequence[str] = [],                # needn't raise dangerous-default-value
    seqB: MutableSequence[str] = [],         # should raise dangerous-default-value
    seqC: list[str] = [],                    # should raise dangerous-default-value
    setA: Set[str] = set(),                  # needn't raise dangerous-default-value
    setB: MutableSet[str] = set(),           # should raise dangerous-default-value
    setB: set[str] = set(),                  # should raise dangerous-default-value
): ...
```
