### ISSUE TITLE
False negative: unused-import used in dict

### ISSUE THREAD

**Issue by belak** [PyCQA/pylint#810]
https://github.com/belak/pyseabird/blob/math-plugin/seabird/modules/math.py

In there, I import math and it is found to be an unused-import even though math.pi and math.e are added to a dict later in the file.

**Comment by PCManticore** [comment]
Can you provide a sample example for reproducing this? That link you posted does not exist anymore.

**Comment by belak** [comment]
This is where the code has temporarily moved to. https://gitlab.com/seabird/pyseabird/blob/master/seabird/modules/math.py

I'll try to get a smaller example.

**Comment by belak** [comment]
This appears to be working in the latest pylint... it may have been an issue with the module name (seabird.modules.math) vs the module that was being imported (just math), but I can't confirm that... anyway I'm going to close this since it appears to be fixed.
