### ISSUE TITLE
Disabled messages are ignored with >4 jobs

### ISSUE THREAD

**Issue by The-Compiler** [PyCQA/pylint#815]
When using `-j4` everything seems fine - but starting with `-j5`, often (not always, but 9 in 10 tries) disabled messages seem to be ignored (i.e. I get hundreds of messages even though those are disabled in the config).

This can be reproduced in the qutebrowser repo by doing `tox -e pylint --notest` and `PYTHONPATH=$PWD/scripts/dev ./.tox/pylint/bin/python -m pylint qutebrowser -j5`

**Comment by PCManticore** [comment]
Thanks for patience ;-)

**Comment by The-Compiler** [comment]
Thanks, I can confirm `-j80` works fine now (speeding things up from 2:43 to 29s on the machine I'm testing this on) :wink:
