### ISSUE TITLE
Insure that a score has not deteriorated compare to previous score

### ISSUE THREAD

**Issue by SkyBazzz** [PyCQA/pylint#8158]
### Current problem

After two years on a project without any linter you need to verify the code quality. You install pylint and check the current score is 6.01/10. You want to add score verification to CI. You want to make sure that a score has not deteriorated after committing a new code. All this you need before reaching 10/10.

current workaround for me is the following set of commands in cosole:

`threshold=$(python -c 'import pickle

with open("/PATH_TO_DOT_STATS_FILE", mode="rb") as stream:
    stat = pickle.load(stream)
    threshold = stat["global_note"]
    print(threshold)')

pylint --fail-under=$threshold $(find ${PROJECT_FILES} -iname ${PY_FILES})
`

### Desired solution

pylint --fail-under=PREVIOUS_SCORE
or 
pylint --fail-under-score-decreasing=<y_or_no>

**Comment by jacobtylerwalls** [comment]
Thanks for the report. We have an issue for implementing a "baseline" that would solve this use case. Please feel free to join the discussion at #5403.

**Comment by ap-viavi** [comment]
The discussion in #5403 is about legacy, I don't see how this feature request ONLY applies to legacy code.

We are currently implementing the same via `! grep 'previous run.*-' pylint.log` which fails if there is a negative sign anywhere after "previous run" in the report...

This would be an obvious feature to have in pytlint, like @SkyBazzz suggested, useful for anybody who wants to foster improvement of code quality.
