### ISSUE TITLE
Too many arguments false positive when strings are joined together

### ISSUE THREAD

**Issue by PCManticore** [PyCQA/pylint#816]
Given this code, pylint emits a too-many-format-args because it doesn't understand that the strings were joined.

print("Lorem %s ipsum %s " +
"dolor %s" % (foo, bar, baz))

**Comment by rogalski** [comment]
Included example raises `TypeError: not all arguments converted during string formatting` on both Python 2.7 and Python 3.6. It's expected behaviour, as [`%` binds more strongly comparing to `+`](https://docs.python.org/3/reference/expressions.html). It should be closed as not a bug.

**Comment by PCManticore** [comment]
Right, good catch. Don't remember when I encountered this.
