### ISSUE TITLE
Enhance the testing for docstrings so that it needs arguments if there are attributes that are not the self attribute

### ISSUE THREAD

**Issue by ollie-iterators** [PyCQA/pylint#8170]
### Current problem

It would be good if docstrings required having a description of what the attributes in the function are used to to complete the docstring

### Desired solution

When I make a docstring it would be nice if it were necessary to add the attribute information for the docstring

**Comment by Pierre-Sassoulas** [comment]
You should use the doc param checker, add this to the ``load-plugins`` option: ``pylint.extensions.docparams``. See doc here : https://pylint.readthedocs.io/en/latest/user_guide/checkers/extensions.html#pylint-extensions-docparams
