### ISSUE TITLE
False positive: no-value-for-parameter using python voluptuous library

### ISSUE THREAD

**Issue by dave-mccowan** [PyCQA/pylint#818]
The attached file throws this error when storing a callable in a dictionary.
This is the proper use of the voluptuous python library.

E: 24,39: No value for argument 'v' in function call (no-value-for-parameter)

[pylint_test.py.txt](https://github.com/PyCQA/pylint/files/134541/pylint_test.py.txt)

**Comment by PCManticore** [comment]
Yeah, this happens because we don't have currently a proper understanding of decorators, which voluptuous seems to use, but it's on our road map. Unfortunately, the only solution that I have for now is to recommend you disabling the error locally or in pylintrc.

**Comment by jacobtylerwalls** [comment]
Closing as duplicate of general thread for decorator support: #1694
