### ISSUE TITLE
pyreverse: Add option to exclude standard library

### ISSUE THREAD

**Issue by avylove** [PyCQA/pylint#8181]
### Current problem

When creating class diagrams, there is no option to exclude imports from the standard library, which can add a lot of information that may not be completely relevant depending on what you're doing.

### Desired solution

It would be good to add a CLI option to exclude standard library imports, similar to show-builtin: False for builtins.

**Comment by DudeNr33** [comment]
I agree, getting `pyreverse` diagrams into a usable sized format is hard, so I would fully support this feature if someone wants to contribute a pull request for this!
