### ISSUE TITLE
UserWarning: Module Six already imported

### ISSUE THREAD

**Issue by ortizmj12** [PyCQA/pylint#820]
I've been getting the following error whenever I run pylint:
> /Library/Python/2.7/site-packages/logilab/common/__init__.py:31: UserWarning: Module six was already imported from /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six.pyc, but /Library/Python/2.7/site-packages is being added to sys.path
  import pkg_resources
Warning: option include-ids is deprecated and ignored.
Warning: option symbols is deprecated and ignored.

I'm on a Macbook Pro running Mac OS X 10.10.4 using Python 2.7.6.

Let me know if there's any other information needed.

**Comment by PCManticore** [comment]
This seems to use an older version of pylint, since it depends on logilab.common, which was removed as a dependency in pylint 1.5.0. On the other hand though, I don't think the warning has anything to do with pylint. You might try investigating on StackOverflow or similar sites like this.
