### ISSUE TITLE
Unsuitable asteroid version needed while compiling pylint 

### ISSUE THREAD

**Issue by rohsaini** [PyCQA/pylint#822]
Steps to reproduce:
python setup.py install

Issue:
https://pypi.python.org/simple/astroid/ doesnot have asteroid version greater than 1.5.0.

Output:
Installing pylint script to /usr/local/bin
Installing epylint script to /usr/local/bin
Installing pyreverse script to /usr/local/bin
Installing pylint-gui script to /usr/local/bin
Installing symilar script to /usr/local/bin

Installed /Library/Python/2.7/site-packages/pylint-2.0.0-py2.7.egg
Processing dependencies for pylint==2.0.0
Searching for astroid>=1.5.0,<1.6.0
Reading http://pypi.python.org/simple/astroid/
No local packages or download links found for astroid>=1.5.0,<1.6.0
error: Could not find suitable distribution for Requirement.parse('astroid>=1.5.0,<1.6.0')
ROHSAINI-M-P03M:pylint rohitsaini$ ls

**Comment by PCManticore** [comment]
You need to install the astroid version from the repository when working with pylint's master.
