### ISSUE TITLE
It is a bit difficult to get the invalid-character errors to cause errors

### ISSUE THREAD

**Issue by ollie-iterators** [PyCQA/pylint#8236]
### Question

I have been checking out the documentation in the file: https://github.com/PyCQA/pylint/blob/main/pylint/checkers/unicode.py to try to find out the invalid characters for the pylint error about invalid characters. I added a string to the bad.py file and no error was caused.

### Documentation for future user

I need some information about how to make the invalid-character errors to happen. Should the file be changed to a different type of encoding other than UTF-8?

**Comment by clavedeluna** [comment]
Grep the repo for `[invalid-character` you'll find _some_ testing for this such us in bad_char_esc.py

**Comment by ollie-iterators** [comment]
Ok, thanks for the tip
