### ISSUE TITLE
False positive:   Module 'mmh3' has no 'hash' member (no-member)

### ISSUE THREAD

**Issue by allan-simon** [PyCQA/pylint#825]
The module though do have a hash function 
https://pypi.python.org/pypi/mmh3/2.3.1

I think it's because the module is actually written in C and not directly in python

**Comment by PCManticore** [comment]
This looks like an extension module. Have you tried running it with ``pylint --extension-pkg-whitelist=mmh3 your_file.py`` and see if it reproduces?

**Comment by PCManticore** [comment]
It works if you use ``--extension-pkg-whitelist``

    claudiu@claudiu-VirtualBox:~/src/lll/mmh3$ python -m pylint a.py -rn
    No config file found, using default configuration
    ************* Module a
    C:  2, 0: Unnecessary parens after 'print' keyword (superfluous-parens)
    C:  1, 0: Missing module docstring (missing-docstring)
    E:  2,11: Module 'mmh3' has no 'hash' member (no-member)
    claudiu@claudiu-VirtualBox:~/src/lll/mmh3$ python -m pylint a.py -rn --extension-pkg-whitelist=mmh3
    No config file found, using default configuration
    ************* Module a
    C:  2, 0: Unnecessary parens after 'print' keyword (superfluous-parens)
    C:  1, 0: Missing module docstring (missing-docstring)
    claudiu@claudiu-VirtualBox:~/src/lll/mmh3$
