### ISSUE TITLE
Expected [E0602] "undefined-variable" error do not show up with pylint 1.5.4 (but with 1.3.1 and 1.4.4)

### ISSUE THREAD

**Issue by Aufschlauer** [PyCQA/pylint#826]
I've the following code snipped:
```
import inspect

class nothing():
    def setF(self, p_i):
            try:
                Log.trace("trace")
    
                t = self.getT()
                if isinstance(t, b):
                    if isinstance(p_i, int):
                        t.setF(p_r)
                    else:
                        Log.err("bad" %
                                p_r)
                        raise Exception("bad" %
                                        p_r)
                else:
                    Log.err("bad" % t)
                    raise Exception("bad" % t)
    
                Log.trace("trace")
            except Exception as l_e:
                Log.err("[%s, %s] bad (%s)" %
                        (__file__, str(inspect.currentframe().f_lineno), l_e))
                raise Exception("[%s, %s] bad (%s)" %
                                (__file__, str(inspect.currentframe().f_lineno), l_e))
```
Where I expect a [E0602] "undefined-variable" error. I get the error with pylint 1.3.1 and 1.4.4 but not with 1.5.4. The variable in question where I expect that pylint complains is "p_r", all other errors arises from the incomplete code snipped.

Any ideas?

Thank you.

**Comment by PCManticore** [comment]
Thanks. The problem was a misdesign, which considered some except blocks as catching particular classes of errors for which we didn't emit the messages. The initial idea though was to consider only those particular classes of errors when ignoring, so for instance if you do an except NameError in your program, pylint won't emit undefined-variable for names found inside that block.

**Comment by gpshead** [comment]
Who *wants* a `NameError` in their code?  Expecting to catch one of those has serious bad code smell.

**Comment by cclauss** [comment]
```python
try:
    xrange
except NameError.
    xrange = range
```
