### ISSUE TITLE
Require a space after control keywords (if, while, for).

### ISSUE THREAD

**Issue by jerub** [PyCQA/pylint#827]
The following syntax all lints clean:

```
if(1
   and 2):
    pass

while(0
      and 1):
    pass

for(x, y) in []:
    pass
```

This is not explicitly mentioned in PEP-008, but this is said:

> Then the conditional part of an if -statement is long enough to require that it be written across multiple lines, it's worth noting that the combination of a two character keyword (i.e. if ), **plus a single space,** plus an opening parenthesis creates a natural 4-space indent for the subsequent lines of the multiline conditional.

**Comment by Pierre-Sassoulas** [comment]
Closing as formatting is better handled by an auto-formatter like black or a linter like flake8.
