### ISSUE TITLE
Warn on using asyncio.create_task without keeping reference

### ISSUE THREAD

**Issue by CarliJoy** [PyCQA/pylint#8275]
### Current problem

Using `asyncio.create_task` without keeping a reference can lead to subtle bugs.

See https://textual.textualize.io/blog/2023/02/11/the-heisenbug-lurking-in-your-async-code/ for details or the [note in the documentation](https://docs.python.org/3/library/asyncio-task.html#asyncio.create_task)

> Important
>
> Save a reference to the result of this function, to avoid a task disappearing mid-execution. The event loop only keeps weak references to tasks. A task that isn’t referenced elsewhere may get garbage collected at any time, even before it’s done. For reliable “fire-and-forget” background tasks, gather them in a collection:

### Desired solution

If I call `create_task` but don't save a reference I expect an error telling me I need to keep a reference.

**Comment by Pierre-Sassoulas** [comment]
Thank you for filling the issue @CarliJoy ! This would indeed be a nice check. I'm closing as it's a duplicate of #8263.

**Comment by CarliJoy** [comment]
Thanks for managing the issues. Strange that gitlab didn't found the other issues while I was searching for `create_task`
