### ISSUE TITLE
Fail fast when there is a new commit for the pull request

### ISSUE THREAD

**Issue by ollie-iterators** [PyCQA/pylint#8285]
### Current problem

When a new commit is put into a pull request quickly after the previous comment, the previous comment still has to finish its tests.

### Desired solution

When I make a commit to a pull request quickly after the previous comment, I want the previous comment's tests to very quickly stop.

**Comment by Pierre-Sassoulas** [comment]
A comment on the merge request can be "Good job, let's merge this asap" so I don't think we should cut the tests for a new comment.

Are you talking about commit and not comment ? If that's the case tests should be passed locally first (to save runner time) so this should very seldom happen.

**Comment by ollie-iterators** [comment]
Yes, I meant commit

**Comment by ollie-iterators** [comment]
> A comment on the merge request can be "Good job, let's merge this asap" so I don't think we should cut the tests for a new comment.
> 
> Are you talking about commit and not comment ? If that's the case tests should be passed locally first (to save runner time) so this should very seldom happen.

You say that it seldom happens, but what about the pre-commit fixes. That can cause a commit to happen quickly after a commit has happened.

**Comment by Pierre-Sassoulas** [comment]
Frequent contributors and even new contributors often read the contribution guide or already knows pre-commit so they install pre-commit locally and the code is auto fixed before hitting the CI. But I'm not against the change, it would be better than the current situation.
