### ISSUE TITLE
Allow wildcard-import from __init__.py to files with __all__

### ISSUE THREAD

**Issue by NeilGirdhar** [PyCQA/pylint#831]
It's pretty common Python style to define an `__all__` variable in a module's source file and the do a wildcard-import from the corresponding `__init__.py`. In this particular case, it might be better to let wildcard import go unflagged.

**Comment by PCManticore** [comment]
Can you give me a concrete example? I'm having trouble understanding if you mean that the wildcard import is in the ``__init__`` file or in another file.

**Comment by NeilGirdhar** [comment]
I mean you have an `__init__.py` file with lines like `from .module import *` and in `module.py` you have `__all__ = […]`

**Comment by PCManticore** [comment]
In that case that should be fixed and should be pretty easy to do it. Would you like tackling it?

**Comment by NeilGirdhar** [comment]
I noticed you didn't use `__all__` in your project, which is fine, but it means that when you want to add an object that is exposed by the package you need to change both the source file and the `__init__.py`.  If you instead had a wildcard import in the `__init__.py`, you would just change the source file *and* the `__all__` list.

**Comment by NeilGirdhar** [comment]
@PCManticore Ummmmm okay?  I guess. Can you show me where to look?

**Comment by PCManticore** [comment]
Here: https://github.com/PyCQA/pylint/blob/master/pylint/checkers/imports.py#L348. You can check if you're in a ``__init__`` file by looking at node.root().file. Not sure if it's worth checking for ``__all__`` in an imported module, but if you decide to do it, you'll have to work with the importednode variable from that function (just don't ignore the check if that variable is none, which means that the module couldn't be found).

**Comment by NeilGirdhar** [comment]
Okay, I'll try to take a look at this in the next week.  I have a lot of work, but I'd like to help out too.
