### ISSUE TITLE
Support globbing pattern for input specification

### ISSUE THREAD

**Issue by alexey-pelykh** [PyCQA/pylint#8310]
### Current problem

As mentioned in https://github.com/PyCQA/pylint/pull/8281#issuecomment-1434375681 and https://github.com/PyCQA/pylint/issues/8290#issuecomment-1429340178, lets consider supporting `pylint --recursive=y packages/*/src`

cc @Pierre-Sassoulas @DudeNr33 @DanielNoord 

### Desired solution

Add globbing support right in this line
https://github.com/PyCQA/pylint/blob/dca394035268a234b29d0c103a4fcc201c84061f/pylint/config/config_initialization.py#L123

**Comment by DudeNr33** [comment]
Note: although the example includes the `--recursive=y` option, globbing should work without it as well.

**Comment by alexey-pelykh** [comment]
@Pierre-Sassoulas there's #8312 so the PR is there :D
