### ISSUE TITLE
There are three TODO's that are related to version 2.16 in pylint

### ISSUE THREAD

**Issue by ollie-iterators** [PyCQA/pylint#8335]
### Current problem

As I was looking through the pylint code, I noticed that there were three TODO's that are about pylint version 2.16.

I thought that it would be good to add that information as an issue

The TODO's and locations are:

- "pylint/checkers/variables.py": # TODO: 2.16: Consider using RefactoringChecker._is_function_def_never_returning
- "pylint/reporters/json_reporter.py": TODO: 2.16: Add a new JSONReporter handling abs-path, confidence and scores. (Ultimately all other breaking change related to json for 3.0)
- "script/fix_documentation.py": # TODO: 2.16.0: Upgrade script for change in changelog

### Desired solution

1. The TODO's are fixed
2. The TODO's have an issue that discuss them that are added to a miletone for a pylint version that is 2.16.x
3. The TODO's are moved to be done in a later version

**Comment by Pierre-Sassoulas** [comment]
Nice catch ! The TODO are indicative, we can do them for 2.17.0 or later there's no hard constraints about that.
