### ISSUE TITLE
[no-member] warning still issued for ignored modules

### ISSUE THREAD

**Issue by tyrann** [PyCQA/pylint#834]
I am using numpy and I have added the following to my .pylintrc:
    
    [TYPECHECK]

    ignore-mixin-members=yes

    ignored-modules = numpy,pygame

    ignored-classes = numpy

However I still get the following warning:
    `[no-member] Module 'numpy.random' has no 'rand' member`

    import numpy as np
    def main():

        num_samples, num_features = 10, 5
        data = np.random.rand(num_samples, num_features)
        print(data)

I am using pylint 1.5.4 and python 3.4.

**Comment by tyrann** [comment]
I found the following fix:

    [MASTER]
    extension-pkg-whitelist=numpy

Is there a better way to fix the problem described above?

**Comment by PCManticore** [comment]
The issue happened because ignored-modules needs a fully qualified name for the module to be ignored. In your case, it had to be numpy.random instead of numpy. Alternatively, you can use Unix glob patterns, as in "numpy.*" for ignoring everything coming from the numpy module.
