### ISSUE TITLE
check_docs false positive parameter warnings

### ISSUE THREAD

**Issue by alflanagan** [PyCQA/pylint#835]
I've found two cases where the check_docs extension finds a discrepancy between the Sphinx docstring and the function type hints, where there's no actual discrepancy.

Here's the shortest program I could write that shows both issues. See the comments for more explanation.

[pylint_problems.py](https://github.com/PyCQA/pylint/files/159283/pylint_problems.py.txt)

**Comment by PCManticore** [comment]
Thanks for reporting this. Not sure why this is happening, but I'll have a look.

**Comment by PCManticore** [comment]
I cannot reproduce it using the latest code. check_docs received a couple of improvements and was partially rewritten, so this might have been fixed then.
