### ISSUE TITLE
visit_call expects assignment

### ISSUE THREAD

**Issue by dmarkowvw** [PyCQA/pylint#8369]
### Bug description

When testing the class 
`
class AvoidUdf(BaseChecker):
    '''
    reference to palentir style guide:
    https://www.palantir.com/docs/foundry/transforms-python/pyspark-style-guide/#udfs-user-defined-functions
    '''
    
    name = "no-udf-s"
    priority = -1
    # TODO message code format
    msgs = {
        "W9994" : (
            "User defined functions should be avoided",
            "no-udf-s",
            "User defined function are slow since they don't run distributed and often unnecessary"
        )
    }

    def visit_call(self, node):
        if hasattr(node, "func"):
            if hasattr(node.func, "attrname"):
                if node.func.attrname == "udf":
                    self.add_message("no-udf-s", node=node)
            elif hasattr(node.func, "name"):
                if node.func.name == "udf":
                    self.add_message("no-udf-s", node=node)
`

with 

`class TestAvoidUdf(pylint.testutils.CheckerTestCase):
    CHECKER_CLASS = pyspark_checkers.AvoidUdf

    def test_find_udfs_import_f(self):
        nodes = astroid.extract_node("""
from pyspark.sql import functions as F

def convertCase(str):
    resStr=""
    arr = str.split(" ")
    for x in arr:
       resStr= resStr + x[0:1].upper() + x[1:len(x)] + " "
    return resStr 

convertUDF = F.udf(lambda z: convertCase(z),StringType()) #@
        """)
        print(nodes.value)
        with self.assertAddsMessages(
                pylint.testutils.MessageTest(
                    msg_id="no-udf-s",
                    node=nodes.value.func,
                    line=11,
                    col_offset=13,
                    end_line=1,
                    end_col_offset=57
                ),
            ): self.checker.visit_call(nodes.value)
`

I get the error message 
`E           AssertionError: Expected messages did not match actual.
E           
E           Expected:
E           MessageTest(msg_id='no-udf-s', line=11, node=<Attribute.udf l.11 at 0x7f5411f4af40>, args=None, confidence=Confidence(name='UNDEFINED', description='Warning without any associated confidence level.'), col_offset=13, end_line=1, end_col_offset=57)
E           
E           Got:
E           MessageTest(msg_id='no-udf-s', line=11, node=<Call l.11 at 0x7f5411f4ae50>, args=None, confidence=Confidence(name='UNDEFINED', description='Warning without any associated confidence level.'), col_offset=13, end_line=11, end_col_offset=57)

lib/python3.9/site-packages/pylint/testutils/checker_test_case.py:70: AssertionError`

Why is the visit_call method expecting an assignment? Shoudn't is expect a call?

### Command used

```shell
pytest module_test.py
```

### Pylint output

```shell
pytest output: 
E           AssertionError: Expected messages did not match actual.
E           
E           Expected:
E           MessageTest(msg_id='no-udf-s', line=11, node=<Attribute.udf l.11 at 0x7f5411f4af40>, args=None, confidence=Confidence(name='UNDEFINED', description='Warning without any associated confidence level.'), col_offset=13, end_line=1, end_col_offset=57)
E           
E           Got:
E           MessageTest(msg_id='no-udf-s', line=11, node=<Call l.11 at 0x7f5411f4ae50>, args=None, confidence=Confidence(name='UNDEFINED', description='Warning without any associated confidence level.'), col_offset=13, end_line=11, end_col_offset=57)

lib/python3.9/site-packages/pylint/testutils/checker_test_case.py:70: AssertionError
```

### Expected behavior

The visit_call method should expect a call, not an attribute

### Pylint version

```shell
pylint==2.16.2
Python 3.9.5
```

### OS / Environment

Ubuntu 22.04  (WSL 1)

### Additional dependencies

astroid==2.14.2
attrs==22.2.0
dill==0.3.6
exceptiongroup==1.1.0
iniconfig==2.0.0
isort==5.12.0
lazy-object-proxy==1.9.0
mccabe==0.7.0
packaging==23.0
platformdirs==3.0.0
pluggy==1.0.0
py4j==0.10.9.5
pylint==2.16.2
pyspark==3.3.2
pytest==7.2.1
tomli==2.0.1
tomlkit==0.11.6
typing-extensions==4.5.0
wrapt==1.14.1

**Comment by Pierre-Sassoulas** [comment]
@dmarkowvw you closed the issue, is that voluntary ?

**Comment by dmarkowvw** [comment]
@Pierre-Sassoulas yes I made a mistake. so there is no issue :)
