### ISSUE TITLE
Pylint rule against people overriding a method just to call super

### ISSUE THREAD

**Issue by shadow7412** [PyCQA/pylint#839]
As per the title, how difficult would this be to add to the pylint rule set?

It should pick up things like the following two cases.

    class Klass(SuperKlass):
        def __init__(self):
            super(Klass, self).__init__()

        def normal_method(with_arg):
            return super(Klass, self).normal_method(with_arg)

**Comment by PCManticore** [comment]
This should be relatively easy to implement. Would you like to work on a pull request? I could help you with the details.

**Comment by The-Compiler** [comment]
FWIW I don't have time to contribute to this currently, but I'd appreciate such a rule, I know I needed it myself in the past :wink:

**Comment by shadow7412** [comment]
I had a bit of a look at the checkers module - and I'm assuming that pylint/checkers/classes.py would be where I would have to add code.

Something to do with visit_functiondef and/or leave_functiondef...
If you could give some pointers @PCManticore I would appreciate it...

**Comment by PCManticore** [comment]
You'll have to write probably something like this:

1. you need a visit_functiondef that doesn't checks only methods, by doing a node.is_method check before it.
2. you need to verify if that function contains only one element, by looking at node.body attribute, it should probably contain something like [Expr()] or [Return()].
3. after filtering the previous results, you'll have to verify that you are indeed working with super calls. You can do that by accessing the function that's being called inside the expression. Something like this should do the trick:

**Comment by PCManticore** [comment]
Hey @shadow7412  how is this going, need any help?

**Comment by shadow7412** [comment]
Hi @PCManticore - I've just been super busy at work this last couple of weeks. I do plan to get around to it though. Sorry about the delay.

**Comment by PCManticore** [comment]
No worries, take your time.

**Comment by shadow7412** [comment]
For some reason or another, many of the tests fail in my environment... is there something special I need to do to get it to work? O.o

[pylintresults.txt](https://github.com/PyCQA/pylint/files/181078/pylintresults.txt)

**Comment by PCManticore** [comment]
How do you run the tests? It seems you're using pytest, but I'm not sure we support it. Could you try with ``tox`` or even with ``python -m unittest discover -p "*test*"`` inside the test directory?

**Comment by shadow7412** [comment]
I just assumed they were py.tests because they are what I"m used to :p 
Here is the output of the command you mentioned.

```
python -m unittest discover -p "*test*"
EEE
======================================================================
ERROR: test_functionality (pylint.testutils.LintTestUpdate)
update test of input file "None" (LintTestUpdate)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "pylint/testutils.py", line 276, in test_functionality
    tocheck = [self.package+'.'+self.module]
TypeError: cannot concatenate 'str' and 'NoneType' objects

======================================================================
ERROR: test_functionality (pylint.testutils.LintTestUsingFile)
file test of input file "None" (LintTestUsingFile)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "pylint/testutils.py", line 318, in test_functionality
    importable = join(self.INPUT_DIR, self.module)
  File "/home/steven/dev/python/env/lib/python2.7/posixpath.py", line 68, in join
    if b.startswith('/'):
AttributeError: 'NoneType' object has no attribute 'startswith'

======================================================================
ERROR: test_functionality (pylint.testutils.LintTestUsingModule)
module test of input file "None" (LintTestUsingModule)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "pylint/testutils.py", line 276, in test_functionality
    tocheck = [self.package+'.'+self.module]
TypeError: cannot concatenate 'str' and 'NoneType' objects

----------------------------------------------------------------------
Ran 3 tests in 0.000s

FAILED (errors=3)

```

**Comment by PCManticore** [comment]
It seems you are not running the tests from the ``test`` folder, can you try? You might also use ``tox`` directly from the root directory of the repository, that should be easier.

**Comment by shadow7412** [comment]
Running the unit test command from the tests directory ended in much more
success. Thanks for that, now I can actually write a test :P

**Comment by PCManticore** [comment]
Cool! Don't hesitate to let me know if you encounter any issue or need any help, here or even on IRC (#pylint-dev on freenode, although lately I haven't been that active there)

**Comment by shadow7412** [comment]
Hi @PCManticore.

This is what I have so far;
https://github.com/shadow7412/pylint/commit/3402a51928b1f1fb26d7be02888dcd9188d547ac

I struggled to find how to get a reference to the function that is being overridden... Could you please help me work out how to populate 'parent'?

**Comment by PCManticore** [comment]
Hey @shadow7412 

I somehow missed your comment. For the record, you can also find me on IRC (freenode) on #pylint, if I'm not responsive here.

You can retrieve the method being overriden using something as this:

    from astroid.test_utils import extract_node
    n = extract_node('''
    class B:
       def best(self, a, b):
           pass

    class A(B):
       def test(self):
           super(A, self).best(1) #@
    ''')
    super = next(n.func.expr.infer())
    attrname = n.func.attrname
    print(next(super.igetattr(attrname)))

Basically, you will try to infer the super object (which knows how to access the methods of the ancestors) and then you'll try to retrieve that particular method, which in this case would be a BoundMethod of best over B. A bound method will act as a function, so you could access its attributes as if it is a class. Of course, you need to add some checks: if the infer call fails, bail out. If the returned object is not a super object or if it is an Uninferable object, bail out. If AttributeInferenceError is raised when the method is retrieved with igetattr, bail out etc.

**Comment by PCManticore** [comment]
Hey @shadow7412 are you still planning to finish this? If not, can you send what you have so far as a PR and we can continue it from there?

**Comment by shadow7412** [comment]
Thanks for reminding me about this. I got really stuck trying to get the super function.
Hopefully you'll find at least the tests useful :)

https://github.com/PyCQA/pylint/pull/941

**Comment by PCManticore** [comment]
Thank you @shadow7412 ! If you still want to work on this feature, do not hesitate to ask me. I would try to take a look after the weekend to see what needs to be done to have this and I could leave what I'll gather as notes in the PR, if there is anyone interested in continuing it (if not, we'll get to it, but hopefully, after 2.0).

**Comment by belugame** [comment]
I have a similar request, but compared to this it can do a whole lot of damage: Overriding a method while not being aware or forgetting that their super() does return something. 

In my case it was the test runner which ran the tests fine but did not produce an error exit code when tests failed.

Would you be open to have this as a feature?

**Comment by AWhetter** [comment]
I don't think that I understand your example. Please could you explain further with some example code, what happens now, and what you expect. It might be better to open a new issue considering that this one is so old.

**Comment by jace** [comment]
I have found an edge case for this rule:

```python
class CustomError(Exception):
    def __init__(self, message="default"):
        super().__init__(message)
```

Pylint flags this as a useless super delegation, but it is not. The method signature is different.

**Comment by Pierre-Sassoulas** [comment]
@jace please open a new issue if it's still a problem on the latest main, this is going to get buried in this closed issue.

**Comment by shadow7412** [comment]
That depends on the signature of `super().__init__`. But yeah, this issue is ancient - best to create a new one (you can link this one if you like)
