### ISSUE TITLE
Deprecate / remove support for `.vcg` files in `pyreverse`

### ISSUE THREAD

**Issue by DudeNr33** [PyCQA/pylint#8416]
[Visual Compiler Graphs](https://www.rw.cdl.uni-saarland.de/people/sander/private/html/gsvcg1.html) is currently one of the supported output formats for `pyreverse`.
However this is a very old format (the linked article talks about MS Windows 3.1 😀), and it is really hard to even find tools that can render this format. 
The [link](https://rw4.cs.uni-sb.de/people/sander/private/html/gshome.html) included in the source code does not contain a download link as promised, and the mentioned debian package [cannot be found anymore](https://packages.debian.org/search?keywords=vcg&searchon=names&suite=stable&section=all).

I talked to various colleagues that I thought might have heard about this format, but no one ever did.

Especially because verifying changes to the `.vcg` testdata is hard and might even scare potential contributors, I propose to deprecate - or even better, as it is seemingly very outdated and probably not used anymore - remove `.vcg` support entirely.

Maybe we could put the deprecation warning in 2.17 and remove it for 3.0?

**Comment by DanielNoord** [comment]
:+1: remove!

**Comment by Pierre-Sassoulas** [comment]
In 3.0 even.

**Comment by DudeNr33** [comment]
Perfect!

I mean, we lose cool features like the fisheye view, but hey I guess that's the price to pay. 😆 
![image](https://user-images.githubusercontent.com/3929834/224119076-7b7a1f4c-a55a-4c35-9210-e4be074f9fc5.png)

**Comment by Pierre-Sassoulas** [comment]
The 90's were wild, impressive stuff.
