### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'frame'

### ISSUE THREAD

**Issue by jamadden** [PyCQA/pylint#846]
We (https://github.com/gevent/gevent) have some code in our project that crashes pylint (at least when it's used through prospector). 

Unfortunately, I can't (yet) reproduce this locally on either Python 2 or Python 3, and it also works fine on landscape.io (where they use Python 3). It only crashes on Travis CI.

I have some guesses as to what the file causing the problem might be, but I haven't been able to confirm them yet.

From reading the code, I thought that adding `undefined-all-variable` to the `disable` list in `.pylintrc` would fix the problem (that's the message being reported by `_check_all`, and the `add_message` method in `pylint/utils` bails if the message isn't enabled on line 416, before it gets to the crasher on line 439), but that didn't work. Workaround suggestions welcome :)

Versions:
- Python 2.7.11
- pylint 1.5.4
- astroid 1.4.4

Traceback
```
Traceback (most recent call last):
  File "//python2.7/bin/prospector", line 11, in <module>
    sys.exit(main())
  File "//python2.7/lib/python2.7/site-packages/prospector/run.py", line 159, in main
    prospector.execute()
  File "//python2.7/lib/python2.7/site-packages/prospector/run.py", line 65, in execute
    messages += tool.run(found_files)
  File "//python2.7/lib/python2.7/site-packages/prospector/tools/pylint/__init__.py", line 232, in run
    self._linter.check(self._args)
  File "//python2.7/lib/python2.7/site-packages/pylint/lint.py", line 734, in check
    self._do_check(files_or_modules)
  File "//python2.7/lib/python2.7/site-packages/pylint/lint.py", line 865, in _do_check
    self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
  File "//python2.7/lib/python2.7/site-packages/pylint/lint.py", line 945, in check_astroid_module
    walker.walk(ast_node)
  File "//python2.7/lib/python2.7/site-packages/pylint/utils.py", line 940, in walk
    cb(astroid)
  File "//python2.7/lib/python2.7/site-packages/pylint/checkers/variables.py", line 356, in leave_module
    self._check_all(node, not_consumed)
  File "//python2.7/lib/python2.7/site-packages/pylint/checkers/variables.py", line 392, in _check_all
    node=elt)
  File "//python2.7/lib/python2.7/site-packages/pylint/checkers/__init__.py", line 100, in add_message
    self.linter.add_message(msg_id, line, node, args, confidence)
  File "//python2.7/lib/python2.7/site-packages/pylint/utils.py", line 439, in add_message
    module, obj = get_module_and_frameid(node)
  File "//python2.7/lib/python2.7/site-packages/pylint/utils.py", line 125, in get_module_and_frameid
    frame = node.frame()
  File "//python2.7/lib/python2.7/site-packages/astroid/bases.py", line 440, in frame
    return self.parent.frame()
AttributeError: 'NoneType' object has no attribute 'frame'
```

Complete log is [here](https://travis-ci.org/gevent/gevent/jobs/115192148).

**Comment by jamadden** [comment]
Ahh, well, if I make `undefined-all-variable` the first thing in the list, that does workaround the problem.

It turns out that the Python 3 ConfigParser supports comments between the lines of a multi-line configuration statement, but the Python 2 parser does not :(

**Comment by PCManticore** [comment]
Hey, thanks for the report. It's unfortunate that the Python 2 configparser can't handle this though, not sure if what we can do to fix this. But the initial issue seems to be related with something totally different and I'd like to find this issue, since this is the actual root of the problem.

Can you run prospector with a pylint flag, which you can put in the configuration file if any. I'm interested in seeing how that node looks, so probably the result from this would help me:

``pylint .. --init-hook="import sys, code; sys.excepthook = lambda exc, exc_type, tb: print(tb.tb_next.tb_next.tb_next.tb_next.tb_next.tb_next.tb_next.tb_next.tb_next.tb_next.tb_frame.f_locals['node'])"`` 

If it doesn't seem to print the node, you can mess up with the tracebacks until we reach the actual method where it crashes.

**Comment by jamadden** [comment]
I wasn't trying to imply that fixing ConfigParser was a problem pylint needed to solve, or even that it had any impact on this issue. I was just sad that it took me awhile to figure that out. :)

I'm trying the init hook now; I have to run pylint manually to do so as prospector doesn't seem to offer that knob.

**Comment by PCManticore** [comment]
By the way, it's probably f_locals['self'] instead of node. :-)

**Comment by jamadden** [comment]
Fortunately (or unfortunately), pylint itself doesn't crash, although prospector still does. So something in the way prospector is setting pylint up triggers this.

**Comment by jamadden** [comment]
Ok, I wrapped prospector in the same basic excepthook. Here's the output for `_check_all` when the exception occurs:
```
<code object _check_all at 0x2b6468aca230, file "//python2.7/site-packages/pylint/checkers/variables.py", line 363> _check_all
self: <pylint.checkers.variables.VariablesChecker object at 0x2b6468ac17d0>
node: Module(gevent.core)
elt: Const(str)
---
```

The code in `_check_all` that's failing is this:
```
            if elt_name not in node.locals:
                if not node.package:
                    self.add_message('undefined-all-variable',
                                     args=(elt_name, ),
                                     node=elt)
```

(So maybe it should be `node=node` instead of `node=elt`?)

Here's the tail end of the traceback that actually throws the exception:
```
<code object frame at 0x2b6466f58b30, file "///python2.7/site-packages/astroid/bases.py", line 435> frame
self: Const(str)
---
```

**Comment by jamadden** [comment]
Module `gevent.core` looks something like this:

```python
try:
  from gevent import c_extension as _core
except ImportError:
  from gevent import pure_python as _core

for item in dir(_core):
   globals()[item] = getattr(_core, item)

__all__ = _core.__all__
```

Running pylint on that file indicates that it's taking the `except` block and inferring that we're using the `pure_python` version of `__all__`[1], because it reports that everything listed in `pure_python.__all__` is not defined...although weirdly instead of reporting it against `gevent.core`, it reports it against `gevent.pure_python`:

```
pylint --rcfile=.pylintrc gevent.core
************* Module gevent.pure_python
E: 10, 4: Undefined variable name 'get_version' in __all__ (undefined-all-variable)
E: 11, 4: Undefined variable name 'get_header_version' in __all__ (undefined-all-variable)
E: 12, 4: Undefined variable name 'supported_backends' in __all__ (undefined-all-variable)
E: 13, 4: Undefined variable name 'recommended_backends' in __all__ (undefined-all-variable)
E: 14, 4: Undefined variable name 'embeddable_backends' in __all__ (undefined-all-variable)
E: 15, 4: Undefined variable name 'time' in __all__ (undefined-all-variable)
E: 16, 4: Undefined variable name 'loop' in __all__ (undefined-all-variable)
```

[1] Probably because of this:
```
$ pylint --rcfile=.pylintrc gevent.c_extension
************* Module gevent.c_extension
F:  1, 0: error while code parsing: compile() expected string without null bytes (parse-error)
```

**Comment by jamadden** [comment]
I found why prospector causes the crash by pylint by default doesn't.

prospector turns on `unsafe-load-any-extension` (which would load our `c_extension`). If I turn that on for pylint, I can make it crash the same way locally, but *only under Python 2*.

If I make the change suggested above (`node=node`) it doesn't crash...

**Comment by PCManticore** [comment]
Thanks for the detailed information. I managed to reproduce this locally afterwards and the issue so far is that the ``__all__`` elements have no parent set. Trying to figure why this happens. In the undefined-all-variable pattern we can't use ``node=node`` unfortunately, since that will make the error be emitted for the entire module, not for the element which wasn't found inside the ``__all__`` declaration.

**Comment by PCManticore** [comment]
Okay, I got a resolution of this bug. It was caused by the fact that astroid 1.4.X is buggy with regard to C extensions and ``__all__`` computation. This wasn't easy to solve in this minor version, but we fixed it in astroid 2.0, which is the next big release we're working on now. You can actually test this with regard to gevent with this script:

	from astroid.test_utils import extract_node
	from astroid import MANAGER
	MANAGER.always_load_extensions = True
	n = extract_node('''
	import gevent.corecext as x
	x
	''')
	i = next(n.infer())
	all = next(i.igetattr('__all__'))
	print(all)
	for i in all.elts:
	   print(i, i.parent)

But since pylint 2.0 is quite far (probably somewhere in the summer), I decided to push a minor fix to undefined-all-variable, for ignoring the nodes which don't have a parent yet. Doesn't solve the underlying problem, it just makes things better until 2.0 gets out with the real solution.

**Comment by PCManticore** [comment]
Let me know though if the solution works for you.

**Comment by jamadden** [comment]
Thanks, I can confirm that fixes the crash! 

In practice, for now, we're just skipping having prospector check that file since it's small and pretty static.

I am curious what you mean though when you say:

> In the undefined-all-variable pattern we can't use node=node unfortunately, since that will make the error be emitted for the entire module, not for the element which wasn't found inside the __all__ declaration.

I get almost exactly the same output with `unsafe-load-any-extension=no` as I do with `node=node` and `unsafe-load-any-extension=yes`. The first case is above, here it is with `node=node`; the output is actually slightly better, as far as I can see, because it attributes the issue to `gevent.core` instead of `gevent.pure_python` (and those variables aren't statically defined, so it kinda makes sense they would be reported, although we play that trick in lots of other modules where we don't see that):
```
pylint --rcfile=.pylintrc gevent/core.py ************* Module gevent.core
E:  1, 0: Undefined variable name 'get_version' in __all__ (undefined-all-variable)
E:  1, 0: Undefined variable name 'get_header_version' in __all__ (undefined-all-variable)
E:  1, 0: Undefined variable name 'supported_backends' in __all__ (undefined-all-variable)
E:  1, 0: Undefined variable name 'recommended_backends' in __all__ (undefined-all-variable)
E:  1, 0: Undefined variable name 'embeddable_backends' in __all__ (undefined-all-variable)
E:  1, 0: Undefined variable name 'time' in __all__ (undefined-all-variable)
E:  1, 0: Undefined variable name 'loop' in __all__ (undefined-all-variable)
```

Anyway, it doesn't matter, I'm just curious. Thanks for your help and the quick turnaround on this!

**Comment by PCManticore** [comment]
What I was saying with that phrase is that each of the element can be on different lines and the reporting, if node was used instead, would report the problems on the first line of the module, not on each line of the elements.

For instance, for this code

    __all__ = (
       "a",
       "b",
       c,
       d
    )

it would result this output:

E:  1, 0: Undefined variable name 'a' in __all__ (undefined-all-variable)
E:  1, 0: Undefined variable name 'b' in __all__ (undefined-all-variable)

**Comment by jamadden** [comment]
Ahh, got it. That makes sense. I missed the subtle distinction of the line number differences in the output because I was just so excited to *get* output :) Thanks again.
