### ISSUE TITLE
Erroneous W0611 on import uuid

### ISSUE THREAD

**Issue by davidthewatson** [PyCQA/pylint#848]
I am using pylint 1.5.4 installed via pip/virtualenv on Mac OS X 10.11.

I have a django module with the following code:

```
import uuid

from django.db import models


class BaseModel(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    uuid = models.UUIDField(unique=True, default=uuid.uuid4, editable=False)

    class Meta:
        abstract = True
```

Running pylint on this module produces:

```
W:  5, 0: Unused import uuid (unused-import)
```

Despite the usage of uuid as the default field value here:

```
    uuid = models.UUIDField(unique=True, default=uuid.uuid4, editable=False)
```

**Comment by PCManticore** [comment]
I think the pattern might be confused by the fact that the attribute uuid has the same name as the import. Here's a shorter reproducer:

    import uuid

    def test(default=None): return default

    class BaseModel(object):
        uuid = test(default=uuid.uuid4)

**Comment by davidthewatson** [comment]
@PCManticore Yes, I believe that's correct. Changing the lvalue attribute name in your example quiets the erroneous W061. It's also interesting to note that the class appears to be causally related, as eliminating the class definition also eliminates the W0611.

**Comment by PCManticore** [comment]
I'll put this to minor for now, we'll get to it until the next release. The code that handles this pattern is messy and definitely needs to be refactored.

**Comment by PCManticore** [comment]
Fixed in master branch.
