### ISSUE TITLE
Is there an programly way to find variable name which is undefined?

### ISSUE THREAD

**Issue by eromoe** [PyCQA/pylint#8492]
### Question

I tried to use  pylint  search undefined variable in a script , and automatically genarate input parameters.
But after look official docs and the code , I am missing in the complicated logic .

### Documentation for future user

I know I can use regex to process the string output, but I don't know if it cover every undefined cases.

**Comment by Pierre-Sassoulas** [comment]
There's no way to fix the error raised by pylint automatically right now. But we're detecting ``undefined-variable`` see https://pylint.readthedocs.io/en/latest/user_guide/messages/error/undefined-variable.html

**Comment by eromoe** [comment]
No, maybe I don't express clearly. 
I just want to get the undefined variable list !  No matter `pylint` is wrong or right, but there is not a programly way to do it .

**Comment by Pierre-Sassoulas** [comment]
You could run pylint by API and create a custom reporter that only report undefined-variable https://pylint.readthedocs.io/en/latest/development_guide/api/pylint.html#recover-the-result-in-a-stream

**Comment by eromoe** [comment]
@Pierre-Sassoulas Could you mind give me a simple example , I have no clue now .

**Comment by Pierre-Sassoulas** [comment]
Here's an example of reporter : https://github.com/PyCQA/pylint/blob/main/pylint/reporters/collecting_reporter.py. There are other examples in the directory. The code to use it in the link I provided in the previous answer :)

**Comment by eromoe** [comment]
Actually the docs and this example is too simple to understand the logic... 
Since pylint code base is not small, I mean a case user view the code half hour and with no clear example, is very frustrated. 
Sorry, no mean to blame the docs,  but I have to give up and use regex to match undefine variable...
