### ISSUE TITLE
Nested subclass definition with the same name triggers undefined-variable

### ISSUE THREAD

**Issue by federicobond** [PyCQA/pylint#851]
The following code:

``` python
class MyError(Exception):
    pass

class MyClass(object):
    class MyError(MyError):
        pass
```

Triggers this pylint warning:

```
E:  5,18: Undefined variable 'MyError' (undefined-variable)
```

This is probably due to the apparently recursive class definition for `MyClass.MyError`, but the code is perfectly valid since the new name is declared inside the `MyClass` scope.

**Comment by PCManticore** [comment]
I can reproduce this, thanks for letting us know!

**Comment by PCManticore** [comment]
Fixed in master branch.
