### ISSUE TITLE
Detect incorrect usage of str.strip()

### ISSUE THREAD

**Issue by Storyyeller** [PyCQA/pylint#860]
One common mistake I see among new Python programmers is assuming that str.strip takes a substring to remove, instead of a set of characters to remove. This leads to code like s.rstrip('.java') which obviously doesn't do what the author expects.

I think there should be a warning for any usage of strip/lstrip/rstrip where the argument is a constant string, and that string contains duplicate characters, since this is almost certainly incorrect.

**Comment by PCManticore** [comment]
Pylint already warns about this:

    ************* Module a
    C:  1, 0: Final newline missing (missing-final-newline)
    E:  1, 0: Suspicious argument in str.rstrip call (bad-str-strip-call)
