### ISSUE TITLE
Can't run `pylint .`

### ISSUE THREAD

**Issue by demoneaux** [PyCQA/pylint#865]
When running pylint, I want to lint the current directory, which is a module. However, using `pylint .` changes all the metrics to zero as it only detects 1 module, presumably `__init__.py`. Using weird syntax like `pylint ../current-dir-name` works though, so I was wondering if my case could be supported.

**Comment by PCManticore** [comment]
This is not possible right now, there is an issue about supporting this feature, but no one got to implement it yet: https://github.com/PyCQA/pylint/issues/352
