### ISSUE TITLE
Multi line strings as decorator args lead to incorrect line numbers in warnings.

### ISSUE THREAD

**Issue by dbaum** [PyCQA/pylint#866]
In this code, the warning for INVALID_FUNC_NAME will have the wrong line number.  Note that if the result arg is a multi-line expression then the line is correct.  This appears to only happen when string concatenation is being used.

---

def decorator(result):
    def inner(func):
        return func(result)
    return inner

@decorator(result='a'
           'b')
def INVALID_FUNC_NAME():
    return 123

---

**Comment by dbaum** [comment]
I looked at this a little further.  I think the problem is in astroid rather than pylint.  The Const node for the string has fromlineno==tolineno, and the FunctionDef appears to base its lineno on what comes before.  I suspect this is coming from the underlying parser, so perhaps not fixable.

**Comment by PCManticore** [comment]
I feel we might need to drop the builtin ast module in favour of something like https://github.com/PyCQA/redbaron or a tree library based on 2to3, in order to have a better view of the source code in the treee.

**Comment by DanielNoord** [comment]
This has been fixed on `main` due to recent improvements on line number calculations.
