### ISSUE TITLE
Checking incorrect usage of the keyword 'nonlocal'  results in fatal errors.

### ISSUE THREAD

**Issue by xiaxinmeng** [PyCQA/pylint#8735]
If a 'nonlocal'  variable are assigned with a variable outside a function, Pylint fails to handle it. See the following example.

example.py:
```python
nonlocal X
X = whatever
```

### The expected output:
There is no a fatal error.

### The actual output:
```
>> pylint example.py
************* Module pylint_example
Desktop/pylint_example.py:1:0: C0114: Missing module docstring (missing-module-docstring)
Desktop/pylint_example.py:3:0: E0117: nonlocal name X found without binding (nonlocal-without-binding)
Exception on node <Assign l.4 at 0x7fdb12c04a90> in file '/home/xxm/Desktop/pylint_example.py'
Traceback (most recent call last):
  File "/home/xxm/.local/lib/python3.11/site-packages/pylint/utils/ast_walker.py", line 91, in walk
    callback(astroid)
  File "/home/xxm/.local/lib/python3.11/site-packages/pylint/checkers/variables.py", line 2043, in visit_assign
    self._check_self_cls_assign(node)
  File "/home/xxm/.local/lib/python3.11/site-packages/pylint/checkers/variables.py", line 2920, in _check_self_cls_assign
    scope = node.scope().parent.scope()
            ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'scope'
Desktop/empirical_type_checker/bug_report/pylint_example.py:1:0: F0002: /home/xxm/Desktop/pylint_example.py: Fatal error while checking '/home/xxm/Desktop/pylint_example.py'. Please open an issue in our bug tracker so we address this. There is a pre-filled template that you can use in '/home/xxm/.cache/pylint/pylint-crash-2023-06-06-15-56-31.txt'. (astroid-error)

------------------------------------------------------------------
Your code has been rated at 0.00/10 (previous run: 0.00/10, +0.00)
```

### Test Environment:
Ubuntu 18.04,
CPython 3.11.3
Pylint: 3.0.0b1
astroid 3.0.0a3

**Comment by xiaxinmeng** [comment]
Thanks, I hope these reported bugs are helpful for the development and maintenance of pylint.

**Comment by nickdrozd** [comment]
This is a bug that would have been revealed with better type checking. I doubt it is the only place where the code blows past the possibility of a null scope.

**Comment by jacobtylerwalls** [comment]
@nickdrozd while on the subject of type checking, do you have a view on whether we should move forward with pylint-dev/astroid#2167 or pylint-dev/astroid#2171? We're thinking of taking one of the two approaches to avoid assigning to methods, which is cluttering a lot of the mypy output now. If it would help for me to write up an astroid issue to summarize the state of the discussion, I'll gladly do it.

**Comment by nickdrozd** [comment]
The inference module is pretty gnarly, and it's also responsible for a lot of downstream gnarliness, so I'm in favor of obliterating it along the lines of https://github.com/pylint-dev/astroid/pull/2171.
