### ISSUE TITLE
[BUG] [pylint-2.0.0] wrong-import-order: Identify as standard a local import

### ISSUE THREAD

**Issue by moylop260** [PyCQA/pylint#875]
- Steps:
 - Save in `right_import_order_test_no_exceptions.py` file follow code:
  ```python
# standard imports
import os

# 3rd party imports
from lxml import etree

# local imports
from my_local_package import no_exceptions  # local
```
 - Run pylint with check wrong-import-order enabled:

   - `pylint -r n -d all -e C0411 -f colorized right_import_order_test_no_exceptions.py` 

 - Review result:
   - `(without errors)`

 - Save in `right_import_order_test_exception.py` file follow code:
  ```python
# standard imports
import os

# 3rd party imports
from lxml import etree

# local imports
from my_local_package import exceptions
```
 - Run pylint with check wrong-import-order enabled:

   - `pylint -r n -d all -e C0411 -f colorized right_import_order_test_exception.py` 

 - Review result:
   - `standard import "from my_local_package import exceptions" comes before "from lxml import etree" (wrong-import-order)`

- Saw
 - A error of wrong-import-order in right_import_order_test_exception.py file

- Expected
 - Result without error in right_import_order_test_exception.py file because is a right import order

- Environment
```bash
pylint --version
pylint 2.0.0,
astroid 1.5.0
Python 2.7.10 (default, Oct 23 2015, 19:19:21)
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)]
```

**Comment by PCManticore** [comment]
There are known problems with this check. It just needs someone to work on improving it.

**Comment by moylop260** [comment]
@PCManticore
Isort have 100% of coverage, have test for py2* and py3*, we are usign 1 year ago without problem..

A crazy idea:
What about use isort within pylint?
Check follow [comment](https://github.com/timothycrosley/isort/blob/develop/isort/isort.py#L8)

A workflow in current wrong_import_order check similar to:
 1) Get import's tokens from file
 2) transform import's tokens to string
 3) send string to isort to get string_sorted
 4) transform string_sorted to import's tokens
 5) Get diff of import's tokens sorted and import's tokens original to show check.

My apologies if this is a bad idea but I'm applying the concept of "better reuse than create"

What do you think?

**Comment by PCManticore** [comment]
If isort exports this feature through an API, we could try to see if it would work for us, but if it is shell only, it won't be a good fit.

Apart of this, just trying to improve this pattern we have right now would be a more fruitful approach in the short term.

**Comment by moylop260** [comment]
@PCManticore 
Thanks for reply

Ok, I got it
We will try with a first proposal to destroy it
Thanks

**Comment by dhoffman34** [comment]
@PCManticore, I am still getting this issue even after https://github.com/PyCQA/pylint/issues/879 was closed. Perhaps it should ve reopened?

**Comment by moylop260** [comment]
@dhoffman34 
Maybe you need update your pylint because we don't have this issue anymore.
Following the same example from main description:

```bash
$ cat right_import_order_test_no_exceptions.py
# standard imports
import os

# 3rd party imports
from lxml import etree

# local imports
from my_local_package import exceptions

$ pylint -r n -d all -e C0411 -f colorized right_import_order_test_exception.py
# no output here

$ pylint --version
pylint 1.7.1,
astroid 1.5.2
Python 2.7.10 (default, Feb  6 2017, 23:53:20)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
```

**Comment by dhoffman34** [comment]
@moylop260, ah, I am using a slightly different example which includes `from exceptions import TestException`, and the fact that it's a top-level module seems to make a difference. This is probably actually an isort bug, so I will open an issue there.
