### ISSUE TITLE
[WISHLIST] wrong-import-order: Add parameters to known_*_library (future, standard, third...)

### ISSUE THREAD

**Issue by moylop260** [PyCQA/pylint#876]
- Situation
 - Many times we don't have a full environment where a pylint command is executed (without all python depends installed, without all python version installed...), currently if we don't have installed a package then It is detected as a `local` package but really is other category.

- [Isort](https://github.com/timothycrosley/isort) is a excellent python library to auto-sort `import` sentences in python files running `pip install isort && isort myfile.py` this library have follow parameteres to known libraries.
  - KNOWN_FUTURE_LIBRARY, --future
     - Force sortImports to recognize a module as part of the future compatibility libraries.
   - KNOWN_STANDARD_LIBRARY, --builtin
     - Force sortImports to recognize a module as part of the python standard library.
   - KNOWN_THIRD_PARTY, --thirdparty
     - Force sortImports to recognize a module as being part of a third party library.
   - KNOWN_FIRST_PARTY, --project
     - Force sortImports to recognize a module as being part of the current python project.
Note: Output of command `isort --help | grep -v "]" | grep -i know -A 2`

IMHO is a good idea have similar parameters in pylint to avoid have even all python packages installed to have a good result of import order.

**Comment by PCManticore** [comment]
I'm not keen on adding 4 new command line options just for this. I don't have any other idea at this moment though, I'll have to think about it.
