### ISSUE TITLE
Detection Python 2.6 only code

### ISSUE THREAD

**Issue by hgrecco** [PyCQA/pylint#883]
Is there a lint that helps removing < Python 2.7 syntax in a cross Python code base?

I am thinking in code like `'{0}'` in (some) format strings, code that can be converted to dict comprehensions or set literals. All this can be rewritten in nicer way in Python 2.7 and 3.2+ It would be nice to have a way to find them easily.

**Comment by PCManticore** [comment]
You can try with pylint --py3k. This flag activates a Python 3 porting checker, which will disable all other checkers, in an effort of helping with the transition between Python 2 and 3. But there is nothing tailored in particular for Python 2.6..

**Comment by graingert** [comment]
@hgrecco you can probably modify 2to3 to do this for you.

**Comment by PCManticore** [comment]
You might also try modernize https://pypi.python.org/pypi/modernize. I'm closing this for now. If you find the need for additional checkers for the Python 3 porting checker, tailored for Python 2.6, please open a new issue with it.
