### ISSUE TITLE
dummy-variables-rgx should include double underscores

### ISSUE THREAD

**Issue by karyon** [PyCQA/pylint#889]
right now `dummy-variables-rgx` is `'_$|dummy'`. i propose adding `__` to it. a single underscore cannot be used in projects that use the idiom of importing gettext as a single underscore. in the internet there are various mentions of using double underscores for unused variables instead, which sounds good to me.

**Comment by PCManticore** [comment]
I never saw double underscore anywhere, only one underscore for denoting unused variables. This doesn't need a change in pylint itself, you can change the value of dummy-variables-rgx in your config file or at the command line.
