### ISSUE TITLE
lambda arguments are not always recognized

### ISSUE THREAD

**Issue by sam-s** [PyCQA/pylint#895]
I get the error
`(E0602, undefined-variable, foo.<lambda>) Undefined variable 'keep'`
in
`auc.map(lambda (cookie,(_a,(_t,keep))): (cookie,int(keep>0)))`
`keep` is a nested `lambda` argument

**Comment by PCManticore** [comment]
This seems to be tuple parameter unpacking, which was removed in Python 3.

**Comment by sam-s** [comment]
it is still present in 2.7 and that is not going away

**Comment by PCManticore** [comment]
I'm not saying that, only that supporting mildly peculiar features from Python 2 has its cost as well (and even if 2.7 is not going away, there will be a day somewhere close to 2020 when we won't support 2.X anymore ;-))

That's why it's marked as a minor bug for now.

**Comment by PCManticore** [comment]
I don't think we'll ever going to fix it, so I'm closing this for now.
