### ISSUE TITLE
Prepending "_" to a variable name to ignore W0612 does not work

### ISSUE THREAD

**Issue by nth10sd** [PyCQA/pylint#899]
https://github.com/PyCQA/pylint/issues/160#issuecomment-163172993 mentions that it should be possible to ignore W0612 by replacing the unused variable name with `_` or by prepending `_`.

```
def main():
    x = 'a'
    _x = 'a'
    _ = 'a'

if __name__ == '__main__':
    main()
```
<img width="321" alt="screen shot 2016-05-10 at 2 05 12 pm" src="https://cloud.githubusercontent.com/assets/488630/15162542/500f9982-16b8-11e6-9c1f-35435f0dc96e.png">

Unfortunately as you can see from the screenshot above, the prepending does not work.

OS version: 10.11.4
Atom version: 1.7.3
linter version: 1.11.4
linter-python version: 2.1.7
pip package versions:
* pylama==7.0.9
* pylama-pylint==2.2.1
* pylint==1.5.4

**Comment by The-Compiler** [comment]
The comment is wrong. You can however use something like this in your `pylint.ini` to get that behaviour:

```ini
[VARIABLES]
dummy-variables-rgx=_.*
```

**Comment by nth10sd** [comment]
Thanks for the headsup. Using your hint, I fixed this by creating ~/.pylama:
```
[pylama:pylint]
dummy-variables-rgx=_.*
```
and adding the absolute path (without ~) to the settings section of linter-python in Atom.

**Comment by jruderman** [comment]
What do you think of making this behavior the default? Rust has this feature, and it's very nice for unpacking tuples, as you can make it clear what values you're ignoring.

**Comment by The-Compiler** [comment]
FWIW I think a default of `_,_.*` would make sense - I use the `_foo` convention for all my projects. @PCManticore what do you think?

**Comment by PCManticore** [comment]
Sounds good! Anyone up for sending a PR?

**Comment by nth10sd** [comment]
Sounds like we're changing the defaults then. :)
