### ISSUE TITLE
wrong-import-order on conditional import

### ISSUE THREAD

**Issue by codingatty** [PyCQA/pylint#917]
### Steps to reproduce
    try:
         import ssl
         SSL_INSTALLED = True
     except ImportError:
         SSL_INSTALLED = False

### Current behavior
Triggers wrong-import-order.

### Expected behavior
Should not trigger wrong-import-order. This appears to be similar to  issue #750, but appears not to be corrected by that fix. Unlike the code in bug #750, there is no alternate module being imported, but later code changes behavior depending on the availability of the ssl module.

### pylint --version output

>pylint --version
pylint 1.5.5,
astroid 1.4.5
Python 2.7.8 (default, Jul  2 2014, 19:50:44) [MSC v.1500 32 bit (Intel)]

**Comment by moylop260** [comment]
This issue was corrected by the PR https://github.com/PyCQA/pylint/pull/906
Using the last sha f7643c0

<img width="604" alt="screen shot 2016-05-26 at 10 44 13 pm" src="https://cloud.githubusercontent.com/assets/6644187/15597190/66c0e784-2393-11e6-8392-4e83cac52001.png">

**Comment by PCManticore** [comment]
Closing as it seems fixed.
