### ISSUE TITLE
[1.5.5 -> master] no-member with PyQt signals

### ISSUE THREAD

**Issue by The-Compiler** [PyCQA/pylint#924]
I noticed a couple of issues when trying out astroid/pylint master, with a codebase which is pylint-clean with astroid 1.4.5 and pylint 1.5.5. I'll open an issue for thing I think is separate.

Those can all be reproduced by cloning the [qutebrowser repository](https://github.com/The-Compiler/qutebrowser) and running `tox -e pylint-master -r`. All line numbers are on commit 24db93f3eb17b97e8928d5faf26dd56221030493 of qutebrowser.

--- 

```
************* Module qutebrowser.mainwindow.mainwindow
E:255, 8: Method 'resize_completion' has no 'connect' member (no-member)
E:260, 8: Method 'reposition_keyhint' has no 'connect' member (no-member)
```

Those methods are actually PyQt signals which have a `connect` member. This was originally fixed in [this astroid commit](https://bitbucket.org/logilab/astroid/commits/212e1fa4427df18550bf06127bd0bb277f16ed8a) (#658) and works fine for the ~300 connect calls I have, except those two now.

```python
    def _connect_resize_completion(self):
        """Connect the resize_completion signal and resize it once."""
        self._completion.resize_completion.connect(self.resize_completion)   # <---
        self.resize_completion()

    def _connect_resize_keyhint(self):
        """Connect the reposition_keyhint signal and resize it once."""
        self._keyhint.reposition_keyhint.connect(self.reposition_keyhint)  # <---
        self.reposition_keyhint()
```

`self._completion` and `self._keyhint` are assigned in `__init__` of the same class FWIW.

**Comment by PCManticore** [comment]
Seems to be fixed as well by the latest astroid commit. Let me know if you can still reproduce it.
