### ISSUE TITLE
Pinned mccabe dependency

### ISSUE THREAD

**Issue by The-Compiler** [PyCQA/pylint#932]
In f34aac1b83889bdae058a447abbd2bd9a7c1996e, `mccabe ==  0.4.0` got added to `install_requires` of `setup.py` (via `__pkginfo__.py`).

This prevents me from using a newer mccabe (like 0.5.0) which works perfectly fine.

Why was this pinned? IMHO that shouldn't be done in a `setup.py`, see [setup.py vs requirements.txt](https://caremad.io/2013/07/setup-vs-requirement/).

cc @moylop260

**Comment by PCManticore** [comment]
I'm okay with removing the restriction.

Regarding setup.py vs requirements.txt, it was like this previously. Changing to requirements.txt shouldn't have been the purpose of the commit, but I wouldn't mind switching to it.

**Comment by moylop260** [comment]
Hello @The-Compiler 
Do you have planned create a new PR?

I don't know if your poposal is use
```diff
- 'mccabe ==  0.4.0',
+ 'mccabe ==  0.5.0',
```

or use:
```diff
- 'mccabe ==  0.4.0',
+ 'mccabe',
```

or other one...

**Comment by The-Compiler** [comment]
@PCManticore those aren't mutually exclusive - as explained in that article you usually use `setup.py` for "weak" dependencies, and `requirements.txt` for "strong" ones (with hardcoded version numbers, e.g. to get reproducibility on CI)

@moylop260 I don't know what'd be best either, that's why I opened an issue first. I think `mccabe` without a version would be best. Maybe `mccabe < 1.0.0` if you're really worried about backwards compatibility, but I don't think it's necessary.

**Comment by PCManticore** [comment]
This setup.py vs requirements.txt looks interesting. Anyway, for whomever submits a PR to this issue, let's change the mccabe version first, we should change the place of dependencies in a subsequent PR.

Also, I'm leaving in a vacation, so @The-Compiler or @AWhetter feel free to merge this when it happens.

**Comment by The-Compiler** [comment]
I opened #933 now.

@PCManticore hope you have a nice vacation! :sunny:
