### ISSUE TITLE
Keep the messages states per file

### ISSUE THREAD

**Issue by PCManticore** [PyCQA/pylint#938]
This issue is circumstantial with https://github.com/PyCQA/pylint/issues/618, which proposes making PyLinter classes as lightweight as possible, targeting one file.

Currently, we have some problems related to the fact that the messages stores and states are for the current analyzed file and not for all the files that Pylint should analyze. This means that currently, we can't have the information about a pragma disable in another file, which would be useful for solving #214 for instance.

Moving to a global message store for all the files seems in line with #618. The changes that this issue involves, without taking in consideration #618 for now, could be to move the token checker outside of PyLinter class and creating one per file, parsing the files to get the AST and for getting the pragmas, holding the pragmas and other relevant information somewhere where the checkers could access them and removing the global bits from PyLinter, which should be per file, instead of relying on the current analyzed file.
Since we are rewriting how the PyLinter class acts and behave, I think this is the best time to refactor this.
@AWhetter let me know what do you think. I will try to come up with better details later on.

**Comment by PCManticore** [comment]
Also, this might seem additional work for #618, but I can help implementing this, as long as we put the basis on what we need to achieve (and what gets changed for #618 as well), so that we won't duplicate the effort.

**Comment by AWhetter** [comment]
This sounds good to me! :+1:

**Comment by DanielNoord** [comment]
I'm going to close this as we're no longer focusing on making `PyLinter` light-weight and reusable.
