### ISSUE TITLE
xml.etree.ElementTree.iterparse is incorrectly listed as deprecated

### ISSUE THREAD

**Issue by geoffblack** [PyCQA/pylint#947]
Using pylint 1.5.6, xml.etree.ElementTree.iterparse is incorrectly listed as deprecated and issues `warning (W1505, deprecated-method) Using deprecated method iterparse()`. According to Python 3 docs, only the `parser` argument of `iterparse()` is deprecated as of Python 3.4, not the entire method: https://docs.python.org/3/library/xml.etree.elementtree.html#xml.etree.ElementTree.iterparse.

**Comment by PCManticore** [comment]
Thank you for reporting this issue. Would you like to send a PR?
