### ISSUE TITLE
psutil vmem instance total member, incorrectly marks as error

### ISSUE THREAD

**Issue by kfrendrich** [PyCQA/pylint#948]
### Steps to reproduce
1. from psutil import virtual_memory
2. memory = virtual_memory().total  # marks this line as error

### Current behavior
Mark as ERROR => Instance of 'vmem' has no 'total' member

### Expected behavior
Not mark as ERROR.

### pylint --version output
__main__.py 1.5.5,
astroid 1.4.5
Python 2.7.1 (r271:86832, Nov 27 2010, 18:30:46) [MSC v.1500 32 bit (Intel)]

**Comment by PCManticore** [comment]
Have you tried with --extension-pkg-whitelist=psutil?

**Comment by PCManticore** [comment]
I tried this with Python 2.7.10 on a Windows machine and it worked perfectly. What OS did you use and what version of psutil? Can you try to test with pylint 1.5.6 / astroid 1.4.6 and with the master version from the repository (both astroid and pylint)?

**Comment by kfrendrich** [comment]
Sorry I was wrong. It wasn't an error, just a "Convention" problem.
The --extension-pkg-whitelist cannot solved it.

I tried on Windows7 64 bit with:
   - Python 2.7.11
        __main__.py 1.5.6,
        astroid 1.4.6
        Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)]
  - Python 3.4.4 (without virtualenv)
        __main__.py 1.5.6,
        astroid 1.4.6
        Python 3.4.4 (v3.4.4:737efcadf5a6, Dec 20 2015, 20:20:57) [MSC v.1600 64 bit (AMD64)]
  - Python 2.7.11(with virtualenv)
        astroid 1.4.5
        Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)]
  - Python 3.4.4 (with virtualenv)
        pylint 1.5.6,
        astroid 1.4.6
        Python 3.4.4 (v3.4.4:737efcadf5a6, Dec 20 2015, 20:20:57) [MSC v.1600 64 bit (AMD64)]

**Comment by PCManticore** [comment]
But what is the convention problem, can you paste the output you are getting?

--extension-pkg-whitelist helps only in the case the module you are analyzing is an extension module and pylint would understand it better if it is actually imported (it does that for whitelisted extension modules). If it is a convention message, it does not help at all, only for warnings such as no-member & co.

**Comment by kfrendrich** [comment]
Ah... Our very old psutil version causes the problem.

Thanks for you help.
I close the issue.

**Comment by PCManticore** [comment]
Cool, thanks!
