### ISSUE TITLE
deprecated-module: bypass error when use "import" instead of "from import"

### ISSUE THREAD

**Issue by moylop260** [PyCQA/pylint#953]
### Steps to reproduce
1.  Use the following example file:
   ```python
from deprecated import foo
import deprecated
```

1. Execute `pylint -d all -e W0402 --deprecated-modules=deprecated example.py`

### Current behaviour
Show just one error:
`W:  1, 0: Uses of a deprecated module 'deprecated' (deprecated-module)`

### Expected behaviour
Show 2 errors

`W:  1, 0: Uses of a deprecated module 'deprecated' (deprecated-module)`
`W:  2, 0: Uses of a deprecated module 'deprecated' (deprecated-module)`

### pylint --version output
```bash
pylint 2.0.0,
astroid 1.5.0
Python 2.7.6 (default, Jun 22 2015, 17:58:13)
[GCC 4.8.2]
```

Is this a expected behaviour?
FYI If the answer is `no` I can work in the fix

**Comment by PCManticore** [comment]
It's not the expected behaviour, you might take a look for finding the problem!
