### ISSUE TITLE
Add test for assignments to self/cls in class methods

### ISSUE THREAD

**Issue by skirpichev** [PyCQA/pylint#977]
See `find_self_assignments` [in test_code_quality.py](https://github.com/diofant/diofant/blob/b4a1914/sympy/utilities/tests/test_code_quality.py) as an example of implementation.  This will catch code like

``` python
class A:
    def foo(self, arg):
        self = arg
```

or

``` python
class A(object):
    @classmethod
    def foo(cls, arg):
        cls = arg
```

Previous attempt for this feature request was [this](https://github.com/PyCQA/pep8-naming/issues/17).  I hope now this issue is in the right place.

**Comment by PCManticore** [comment]
I would imagine this would be useful in the case of classes, so I am okay with having a new check for this. Unfortunately, I am pretty busy, so I can't promise when a thing like this would happen, a pull request would be better now, since it can move things forward.

**Comment by AWhetter** [comment]
To any new contributors, this will require adding a check to `VariablesChecker` with a new warning. For each visited assign node, check if it exists in an instance method or class method, and if it does then make sure that the assignment isn't to the first argument, regardless of it's name.

**Comment by mar-chi-pan** [comment]
I'll take a look!

**Comment by mar-chi-pan** [comment]
What text would you like in the warning?

**Comment by skirpichev** [comment]
@PCManticore, I'm not sure if that's a right fix.

This will work for simple cases:
```
(pylint) sk@note:~ $ cat a.py 
class A:
    def foo(self, bar):
        self = bar
        print(self)

a = A()
a.foo(42)
(pylint) sk@note:~ $ pylint -d all -e W0642 a.py 
No config file found, using default configuration
************* Module a
a.py:3:8: W0642: Invalid assignment to self in method (self-cls-assignment)

------------------------------------------------------------------
Your code has been rated at 8.33/10 (previous run: 6.67/10, +1.67)
(pylint) sk@note:~ $ python3 a.py 
42
```

But not in general:
```
(pylint) sk@note:~ $ cat b.py 
class B:
    def foo(self, bar):
        def spam(x):
            nonlocal self
            self = x
        spam(bar)
        print(self)

b = B()
b.foo(42)
(pylint) sk@note:~ $ pylint -d all -e W0642 b.py 
No config file found, using default configuration

--------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 10.00/10, +0.00)
(pylint) sk@note:~ $ python3 b.py 
42
```

Should I open a new issue?

**Comment by PCManticore** [comment]
Yes please open a new issue
