### ISSUE TITLE
arguments-differ not emitted with keyword-only arguments

### ISSUE THREAD

**Issue by The-Compiler** [PyCQA/pylint#983]
With this:

```python
class AbstractFoo:

    def positional(self, a, b):
        raise NotImplementedError

    def kwonly(self, a, *, b, c):
        raise NotImplementedError


class Foo(AbstractFoo):

    def positional(self, a):
        pass

    def kwonly(self, a, *, b):
        pass
```

I only get `arguments-differ` for `positional`, but not for `kwonly`. I'm not sure if this is intended, but I think it's not?

**Comment by PCManticore** [comment]
Probably not intended, since when this check was added, there were no positional keyword only arguments, I presume.
